### ISSUE TITLE
NuGet issue - Can't install Devices.Client 1.2.10 on VS 2015 UWP Project using NuGet

### ISSUE THREAD

**Issue by cvasquez-github** [Azure/azure-iot-sdk-csharp#100]
Hello,

I'm trying to install Microsoft.Azure.Devlices.Client into a Visual Studio 2015 UWP Project, but is not working using NuGet. Get "Package restore failed. Rolling back package changes". 

Microsoft.Azure.Devices works, but not Devices.Client.

**Comment by cvasquez-github** [comment]
Hey guys,
No worries, found out the problem! 
Had to update Microsoft.NetCore.UniversalWindowsPlatform to **5.2.2** as defined in your sample UWP project (_project.json:"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2_")! 

Now working fine, receiving MQTT messages in UWP project!, let's see if works fine in HoloLens too :)

Hope this is helpful for others facing the same issue.

**Comment by tameraw** [comment]
@cvasquez-github - Thanks!
