### ISSUE TITLE
Missing Device Explorer msi installer for recent SDK releases

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-iot-sdk-csharp#1004]
## Description of the issue:
SDK documentation provides links to pages to get pre-built version of Device Explorer. But the most recent msi installer is from January of 2019. Presumably various bug fixes in SDK since then would be incorporated in a recent build of Device Explorer.

While at some point we will likely build locally, for initial prototyping and testing that is not something we want to undertake.
Thanks

**Comment by prmathur-microsoft** [comment]
Thanks for letting us know. We will modify our release steps to fix this.

**Comment by prmathur-microsoft** [comment]
We will have a release of device explorer in our next release.

**Comment by timtay-microsoft** [comment]
Closing this issue since we did include a release of the device explorer in a recent release

https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-9-11

**Comment by az-iot-builder-01** [comment]
@TurtleBeach, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
