### ISSUE TITLE
String date fields modified after serialization

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-csharp#1007]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 and Azure's Web Service OS (32 bit platform running, not sure which underlying OS)
- **Application's .NET Target Framework :** .NET CORE 2.1 and .NET 4.7.x
- **Device:** Laptop and Azure platform
- **SDK version used:** Tested with Microsoft.Azure.Devices.Client versions 1.20.3 and 1.18.1

## Description of the issue:
When invoking CloudToDeviceMethod with a String date inside the payload, sometimes the String gets modified after serialization, for example if the date is 
"2019-07-17T16:03:33.390Z" after sending the message we receive "2019-07-17T16:03:33.39Z", last zero is dropped. 

Strings should not be treated as dates and should never be modified when sending them through IoTHub, in our case this is making some naming mismatches in the receiving method causing unexpected bugs depending on the date String passed.

This has also been tested with a Java receiver code getting the same results.

## Code sample exhibiting the issue:

Sender (JsonConvert.SerializeObject(c) is not the one producing the issue):
```
serviceClient = ServiceClient.CreateFromConnectionString("CS_HERE");

while (true)
{
	Console.ReadKey();
	object c = new
	{
		Id = "test",
		Parameters = new Dictionary<string, object>
		{
			{"guid", "435ebbcc-92ea-4e7a-a5ec-19bfa6adfab7"},
			{"date", "2019-07-17T16:03:33.390Z"}
		}
	};

	CloudToDeviceMethod method = new CloudToDeviceMethod("default", TimeSpan.FromSeconds(5));
	method.SetPayloadJson(JsonConvert.SerializeObject(c));

	await serviceClient.InvokeDeviceMethodAsync("test", method).ConfigureAwait(false);
}
```
Receiver:
```
public async Task Start()
{
	deviceClient = DeviceClient.CreateFromConnectionString("CS_HERE");

	await deviceClient.SetMethodHandlerAsync("default", Handler, null).ConfigureAwait(false);

	while (true)
	{
		await Task.Delay(5000);
	}
}

private Task<MethodResponse> Handler(MethodRequest methodRequest, object userContext)
{
	Console.WriteLine();
	Console.WriteLine("\t{0}", methodRequest.DataAsJson);
	Console.WriteLine();

	return Task.FromResult(new MethodResponse(new byte[0], 200));
}
```

## Console log of the issue:
Expected:
`{"Id":"test","Parameters":{"guid":"435ebbcc-92ea-4e7a-a5ec-19bfa6adfab7","date":"2019-07-17T16:03:33.390Z"}}`

Received:
`{"Id":"test","Parameters":{"guid":"435ebbcc-92ea-4e7a-a5ec-19bfa6adfab7","date":"2019-07-17T16:03:33.39Z"}}`

**Comment by ewertons** [comment]
Hi @pizerg,
thank you very much for reporting this issue.
Unfortunately, this is not an issue restricted to the Azure IoT C# SDK. Indeed any client connected to Azure IoT Hub will experience the same issue.
We already have the root-cause and will work to address it as soon as possible.

**Comment by prmathur-microsoft** [comment]
Fix from Iothub service should be rolled out soon.

**Comment by timtay-microsoft** [comment]
Closing this issue since it is unrelated to the C# SDK itself

**Comment by az-iot-builder-01** [comment]
@pizerg, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
