### ISSUE TITLE
Feedbackreceiver stops receiving without Exceptions

### ISSUE THREAD

**Issue by DOliana** [Azure/azure-iot-sdk-csharp#1008]
## Description of the issue:

I have a service fabric service (.Net Core 2.1) that listens for device feedback. Since I have a simulated device that sends a message every two minutes with full ACK I know for sure that there should be feedback messages. What I experience is, that after some time (sometimes 3 hours, sometimes 12 hours, sometimes multiple days) the service keeps running, but does not receive any messages. I have a workaround that throws an Exception when there is no feedback for more than 10 minutes. I have observed this behaviour for at least half a year now (with all different versions - currently also with the latest 1.18.1) and decided to open an issue.

## Code sample exhibiting the issue:

This is the relevant code part:
```csharp
while (cancellationToken.IsCancellationRequested == false)
{
    try
    {
        var events = await retryPolicy.ExecuteAsync((c) => feedback.ReceiveAsync(TimeSpan.FromSeconds(2)), cancellationToken);
        if (events != null && events.Records.Any())
        {
            lastFeedbackTime = DateTime.UtcNow;
            await HandleFeedback(events);
            await feedback.CompleteAsync(events);
        }

        // it seems that ACKs get lost...
        if (lastFeedbackTime < DateTime.UtcNow.AddMinutes(-MAXTIME_NO_FEEDBACK_MINUTES))
        {
            var msg = $"No feedback received for {MAXTIME_NO_FEEDBACK_MINUTES} minutes (since {lastFeedbackTime}) - restarting listener and check for buffered messages.";
            logger.Info(msg);
            throw new NoFeedBackException(msg);
        }
    }
    catch (OperationCanceledException ex)
    {
        logger.Info(ex, "cancelation requested - stopping");
    }
    catch (Exception ex)
    {
        logger.Warn(ex, "Error while listening for feedback");
        throw;
    }
}
```

**Comment by ewertons** [comment]
Hi @DOliana,
do you get any exceptions from the SDK itself? Anything like a WebSocketException or WebException?
Also, which operating system is your application running on?
Do you get any printed logs during your execution?

When we try the same in a Windows 10 machine, using .NET core 2.1, after a couple seconds of no network there is an exception.

**Comment by bikamani** [comment]
@DOliana sorry for the delay getting back on this.
Are you still noticing this behavior? 

If so, can you provide the details below?
"I have a simulated device that sends a message every two minutes" - Can you explain this more? Are you using C# Device Client and if so, which version?
Can you post device receive code?

**Comment by bikamani** [comment]
Haven't heard back on this, if the issue still exists please re-open.

**Comment by az-iot-builder-01** [comment]
@DOliana, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by DOliana** [comment]
@bikamani the issue still exists. 
The device I am using is written in C# and runs as a stateless service in service fabric using this SDK version: "Microsoft.Azure.Devices.Client" Version="1.21.0" Do you need further details?

**Comment by DOliana** [comment]
@bikamani , @prmathur-microsoft are there any news?

**Comment by bikamani** [comment]
Hi @DOliana 

Thanks for letting me know, I will take a look at this shortly and get back to you on any further details if we need.

**Comment by bikamani** [comment]
@DOliana We will need more information such as hub details. Can you create a support ticket following https://github.com/Azure/azure-iot-sdk-csharp#need-support ?  That way we can better help you with this issue.

**Comment by DOliana** [comment]
I have done that already and the ticket has not been resolved. I also referenced this issue in the ticket...

**Comment by bikamani** [comment]
@DOliana what is the support ticket number/ ICM number?

**Comment by DOliana** [comment]
@bikamani it's 119073022000200
It was closed and I am currently trying to reopen it, but I have not been successful.

**Comment by bikamani** [comment]
@DOliana 
I could see the ticket, it seems we did not get requested information and it was closed.

Can you please open a new support ticket?

**Comment by DOliana** [comment]
Verdict is, I need to work on this through a ticket - right? Would you be helping on that ticket (or better if/when we get an open ticket is it any help if I give you the ticket no)? Maybe you could contact me via mail (as in the ticket) so we can talk directly?

**Comment by bikamani** [comment]
@DOliana Thanks for your patience on this. Once the support ticket is opened and necessary details are gathered, eventually our team will be the one looking at this for further analysis. It would be helpful to know ticket # for reference so we can also follow up on the same.

**Comment by bikamani** [comment]
Closing the issue. As requested earlier, please open up support ticket so we can collect more information and help with investigation.
