### ISSUE TITLE
Apparent Timing Issue

### ISSUE THREAD

**Issue by sasajl** [Azure/azure-iot-sdk-csharp#1009]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

In production, messages are not being received on a defined Module Client output .  However, message routing works in the IoT Edge Runtime simulator and also works in production if debug level logging is enabled on the IoT Edge runtime.  IoT Edge engineering team has been engaged and did not see any issues. Adding a delay to the container entry script works around the issue.

1. Used the Simulated Temperature App to generate data
2. Used a second container with routes connecting I/O between the 2 containers
3. When the containers start, the data should flow from the Temp thru the Edge Runtime to our container. This only works when the start of our consuming container has a delay added (10 seconds, maybe less would work). 

## Code sample exhibiting the issue:

From the sample program, maybe it has to do with the srand() call? Just guessing here.
void sampleConnector::iothub_module()
{
    srand((unsigned int)time(NULL));

    if (iotHubModuleClientHandle == NULL)
    {
        iotHubModuleClientHandle = InitializeConnection();
    }
    if (iotHubModuleClientHandle != NULL)
    {
        if (SetupCallbacksForModule(iotHubModuleClientHandle) == 0)
        {
            // The receiver just loops constantly waiting for messages.
            printf("Waiting for incoming messages.\r\n");
            while (0 == _pubThreadStop.get()) {
                IoTHubModuleClient_LL_DoWork(iotHubModuleClientHandle);
                ThreadAPI_Sleep(100);
            }
        }
    }

    DeInitializeConnection(iotHubModuleClientHandle);
}

**Comment by prmathur-microsoft** [comment]
As this is not C# SDK related  issue I'm closing this. Please open it on iotedge repo.

**Comment by ewertons** [comment]
Hi @sasajl ,
this seems to be an IoT Edge solution issue. I will file this issue on their repo, and once they investigate from their side, if needed please file an issue on the [Azure IoT Client C SDK repo](https://github.com/Azure/azure-iot-sdk-c).

**Comment by ewertons** [comment]
Please follow up on through this issue:
https://github.com/Azure/iotedge/issues/1478
Thanks.

**Comment by az-iot-builder-01** [comment]
@sasajl, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
