### ISSUE TITLE
Issue regarding "Microsoft.Azure.Devices" (1.2.3/1.2.4 and perhaps other versions) used with Azure Functions

### ISSUE THREAD

**Issue by BitProgress** [Azure/azure-iot-sdk-csharp#101]
I have compiled a dll, which I use in an Azure Function.
The dll references "Microsoft.Azure.Devices" (1.2.4).

When I load the dll and uses it in a Azure Function, I get the following exception:
`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Devices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.File name: 'Microsoft.Azure.Devices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at Com.CatchAlive.Shared.UpdateAuthorizationTokensHandler.Run(ITraceWriter log) at Submission#0.Run(TimerInfo myTimer, TraceWriter log) in :line 42WRN: Assembly binding logging is turned OFF.To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.Note: There is some performance penalty associated with assembly bind failure logging.To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

When I add the following code in the azure function (before I call into the dll) - everything works:
` // HACK - to fix issue!!!
    Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(iotHubConnectionString);
    // HACK - to fix issue!!!`

It might be something related to Azure Functions.

I uses the following dependencies
`{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Dapper": "1.50.2",
        "SendGrid": "9.2.0",
        "Microsoft.WindowsAzure.ConfigurationManager": "3.2.1",
        "Microsoft.Azure.Devices": "1.2.4"
      }
    }
  }
}
`

Am I using it wrong?

I have chosen to have the actual implementation in a dll to make testing easier.

BR
Martin

**Comment by enesuysal** [comment]
Hi @BitProgress 
In Azure Function, if you add following code to first line before your dll

#r "Microsoft.Azure.Devices"
then I believe you will not have that error.

Could you please test it and inform me?

**Comment by BitProgress** [comment]
Hi.

No, it does not help:

2017-08-28T16:19:04.466 Script for function 'UpdateAuthorizationTokens' changed. Reloading.
2017-08-28T16:19:04.466 Script for function 'UpdateAuthorizationTokens' changed. Reloading.
2017-08-28T16:19:04.670 run.csx(3,1): error CS0006: Metadata file 'Microsoft.Azure.Devices' could not be found
2017-08-28T16:19:04.670 Compilation failed.
2017-08-28T16:19:04.670 Compilation failed.
2017-08-28T16:19:05.252 Function started (Id=eb064cbb-98c4-4753-aa5f-d94af4448fde)
2017-08-28T16:19:05.474 Function compilation error
2017-08-28T16:19:05.474 Function compilation error
2017-08-28T16:19:05.474 run.csx(3,1): error CS0006: Metadata file 'Microsoft.Azure.Devices' could not be found
2017-08-28T16:19:05.474 run.csx(3,1): warning AF005: The reference 'Microsoft.Azure.Devices' is part of the referenced NuGet package 'Microsoft.Azure.Devices'. Package assemblies are automatically referenced by your Function and do not require a '#r' directive.
2017-08-28T16:19:05.503 Exception while executing function: Functions.UpdateAuthorizationTokens. Microsoft.Azure.WebJobs.Script: Script compilation failed.
2017-08-28T16:19:05.517 Function completed (Failure, Id=eb064cbb-98c4-4753-aa5f-d94af4448fde, Duration=255ms)

When I include the call:

   // HACK - to fix issue!!!
    Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(iotHubConnectionString);
    // HACK - to fix issue!!!

It works:

2017-08-28T16:20:55.834 Function started (Id=35329514-f54f-495b-a710-9024d866fe0f)

2017-08-28T16:20:55.834 Starting update for authorization tokens at: 8/28/2017 4:20:55 PM

2017-08-28T16:20:55.834 UpdateAuthorizationTokensHandler.Run: Starting (8/28/2017 4:20:55 PM) [Version: 1.1]

2017-08-28T16:20:56.209 Statistics:

2017-08-28T16:20:56.209 --------------------------------------------------

2017-08-28T16:20:56.209 Tokens require update: 15

2017-08-28T16:20:56.209 Tokens updated successfully: 15

2017-08-28T16:20:56.209 UpdateAuthorizationTokensHandler.Run: Complete (8/28/2017 4:20:56 PM)

2017-08-28T16:20:56.209 Function completed (Success, Id=35329514-f54f-495b-a710-9024d866fe0f, Duration=381ms)

But as you see, the ”Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(iotHubConnectionString);” is not used at all.

My code looks like:

#r "System.Configuration"
#r "Com.CatchAlive.Shared.dll"

using System.Configuration;
using Com.CatchAlive.Debug;
using Com.CatchAlive.Shared;


// Trace Writer Wrapper
public class MyTraceWriter : ITraceWriter
{
  TraceWriter log;

  public MyTraceWriter(TraceWriter log)
  {
    this.log = log;
  }

  public void Info(string str)
  {
    log.Info(str);
  }
}


public static void Run(TimerInfo myTimer, TraceWriter log)
{
  DateTime runTimeStampUTC = DateTime.UtcNow;

  log.Info($"Starting update for authorization tokens at: {runTimeStampUTC}");

  try
  {
    var catchAliveConnectionString = ConfigurationManager.ConnectionStrings["catchalive_sqldb_connection"].ConnectionString;
    var deviceServicesConnectionString = ConfigurationManager.ConnectionStrings["deviceservices_sqldb_connection"].ConnectionString;
    var iotHubConnectionString = ConfigurationManager.AppSettings["IoTHub_Administration"];

    // HACK - to fix issue!!!
    Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(iotHubConnectionString);
    // HACK - to fix issue!!!

    UpdateAuthorizationTokensHandler updateAuthorizationTokensHandler = new UpdateAuthorizationTokensHandler(catchAliveConnectionString, deviceServicesConnectionString, iotHubConnectionString);

    updateAuthorizationTokensHandler.Run(new MyTraceWriter(log));
  }
  catch (Exception ex)
  {
    var sendGridApiKey = ConfigurationManager.AppSettings["SENDGRID_APIKEY"];
    ServiceInterruptionHandler serviceInterruptionHandler = new ServiceInterruptionHandler(sendGridApiKey, false);

    serviceInterruptionHandler.Run("UpdateAuthorizationTokens", "Exception", ex.ToString(), runTimeStampUTC, new MyTraceWriter(log));
    throw;
  }
}




Best regards / Med venlig hilsen
Martin Jørgensen
Software Developer (B.Sc.E.E.)
BitProgress Development IVS
Møllegærdet 32, DK-6000 Kolding, Denmark
CVR: 35665811
Mobile: (+45) 5180 6095
E-mail: martin@bitprogress.com<mailto:martin@bitprogress.com>
Web: http://www.bitprogress.com

Fra: enesuysal [mailto:notifications@github.com]
Sendt: 28. august 2017 14:14
Til: Azure/azure-iot-sdk-csharp <azure-iot-sdk-csharp@noreply.github.com>
Cc: Martin Jørgensen <martin@bitprogress.com>; Mention <mention@noreply.github.com>
Emne: Re: [Azure/azure-iot-sdk-csharp] Issue regarding "Microsoft.Azure.Devices" (1.2.3/1.2.4 and perhaps other versions) used with Azure Functions (#101)


Hi @BitProgress<https://github.com/bitprogress>
In Azure Function, if you add following code to first line before your dll

#r "Microsoft.Azure.Devices"
then I believe you will not have that error.

Could you please test it and inform me?

**Comment by enesuysal** [comment]
Is it possible to share your dll's? I want to do some test locally

**Comment by BitProgress** [comment]
Hi.

I have added the source code for that dll.



Best regards / Med venlig hilsen
Martin Jørgensen
Software Developer (B.Sc.E.E.)
BitProgress Development IVS
Møllegærdet 32, DK-6000 Kolding, Denmark
CVR: 35665811
Mobile: (+45) 5180 6095
E-mail: martin@bitprogress.com<mailto:martin@bitprogress.com>
Web: http://www.bitprogress.com

Fra: enesuysal [mailto:notifications@github.com]
Sendt: 29. august 2017 10:48
Til: Azure/azure-iot-sdk-csharp <azure-iot-sdk-csharp@noreply.github.com>
Cc: Martin Jørgensen <martin@bitprogress.com>; Mention <mention@noreply.github.com>
Emne: Re: [Azure/azure-iot-sdk-csharp] Issue regarding "Microsoft.Azure.Devices" (1.2.3/1.2.4 and perhaps other versions) used with Azure Functions (#101)


Is it possible to share your dll's? I want to do some test locally

**Comment by enesuysal** [comment]
Hi @BitProgress,

I can only see your function app source code. Not source code for that dll.
It is difficult to reproduce without having that Com.CatchAlive.Shared.dll

Try to add #r "Microsoft.Azure.Devices" for function app 
and in the bin folder also add Microsoft.Azure.Devices.dll file

Could you please test it and inform me if you see the same error?

**Comment by enesuysal** [comment]
Hi @BitProgress,

Do you still have the same error?

**Comment by enesuysal** [comment]
@tameraw
Could you please close this one?

**Comment by BitProgress** [comment]
Yes, just close it.

Thanks

Best regards / Med venlig hilsen
Martin Jørgensen
Software Developer (B.Sc.E.E.)
BitProgress Development IVS
Møllegærdet 32, DK-6000 Kolding, Denmark
CVR: 35665811
Mobile: (+45) 5180 6095
E-mail: martin@bitprogress.com<mailto:martin@bitprogress.com>
Web: http://www.bitprogress.com

Fra: enesuysal [mailto:notifications@github.com]
Sendt: 28. september 2017 12:53
Til: Azure/azure-iot-sdk-csharp <azure-iot-sdk-csharp@noreply.github.com>
Cc: Martin Jørgensen <martin@bitprogress.com>; Mention <mention@noreply.github.com>
Emne: Re: [Azure/azure-iot-sdk-csharp] Issue regarding "Microsoft.Azure.Devices" (1.2.3/1.2.4 and perhaps other versions) used with Azure Functions (#101)


@tameraw<https://github.com/tameraw>
Could you please close this one?
