### ISSUE TITLE
ReceiveAsync won't accept both timeout and cancellationToken

### ISSUE THREAD

**Issue by saixiaohui** [Azure/azure-iot-sdk-csharp#1011]
Sometime we need to pass both Timeout value and cancellationToken to receiveAsync and ensure code honor both. But it can only support either of them now. 

**Here is the current SDK signature:**
```
        public Task<Message> ReceiveAsync(CancellationToken cancellationToken);
      
        public Task<Message> ReceiveAsync();
      
        public Task<Message> ReceiveAsync(TimeSpan timeout);
```

**Comment by timtay-microsoft** [comment]
Can you elaborate on a situation where you would need to pass both a cancellation token and a timespan? Both of those options are used in the exact same way within the SDK.

As far as the SDK is concerned, the TimeSpan is converted into a cancellation token. In both cases, there is a single timeout object that the SDK promises to respect.

Is one of the above 3 APIs not respecting the cancellationToken/timeout that you give it?

**Comment by timtay-microsoft** [comment]
@saixiaohui do you have more context that you can share about why you want an API that takes two different timeout primitives at the same time?

**Comment by timtay-microsoft** [comment]
Closing this issue since there is no use case for taking multiple different timeout primitives when application level code can combine them into one for the SDK to consume

**Comment by az-iot-builder-01** [comment]
@saixiaohui, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
