### ISSUE TITLE
Timeout is not used in ReceiveAsync method

### ISSUE THREAD

**Issue by saixiaohui** [Azure/azure-iot-sdk-csharp#1014]
Timeout is not respected by ReceiveAsync method.

Here is sample code. 
```
using System;
using System.Diagnostics;
using System.Threading.Tasks;

using Microsoft.Azure.Devices;
using Microsoft.Azure.Devices.Client;

namespace ReceiveAsyncTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            if (args.Length < 1)
            {
                return;
            }

            var connectionString = args[0];
            var deviceId = args.Length == 2 ? args[1] : Guid.NewGuid().ToString();
            var manager = RegistryManager.CreateFromConnectionString(connectionString);
            var device = new Device(deviceId)
            {
                Authentication = new AuthenticationMechanism()
                {
                    Type = AuthenticationType.Sas
                }
            };
            var returnedDevice = await manager.AddDeviceAsync(device);

            var hostName = Microsoft.Azure.Devices.IotHubConnectionStringBuilder.Create(connectionString).HostName;
            var deviceConnectionStringBuilder = Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.Create(hostName, new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, returnedDevice.Authentication.SymmetricKey.PrimaryKey));

            var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionStringBuilder.ToString());
            await deviceClient.OpenAsync();

            var stopwatch = Stopwatch.StartNew();
            var message = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(5));
            stopwatch.Stop();
            Console.WriteLine(stopwatch.Elapsed.TotalSeconds);

            Console.ReadKey();
        }
    }
}
```

You will expect the output to be something around **5** seconds, but the actual output is **60** seconds.

**Comment by saixiaohui** [comment]
Any update?

**Comment by mfalkvidd** [comment]
I think https://github.com/Azure/azure-iot-sdk-csharp/pull/1002 addresses this issue

**Comment by CIPop** [comment]
Timeout is used but with a cooperative cancellation semantic: the AMQP library allows us to specify an `OperationTimeout`.
This used to "work" in 1.18 by running the risk of the actual operation being abandoned (which could eventually complete and actually dequeue a C2D message). This was problematic as the service allows a maximum of 10 dequeued C2D messages that are not acknowledged prior to blocking the pipeline. The C2D pipeline would be blocked until the connection is dropped and re-established. 

We are deprecating the ReceiveAsync(TimeSpan) API: https://github.com/Azure/azure-iot-sdk-csharp/pull/1027 and recommending app-developers to use the CancellationToken equivalent.
We also recommend that you do not use small timeouts that may interfere with the IoTHub/AMQP protocol itself. 
Instead, we recommend that you implement a queue and perform ReceiveAsync without a cancellation token: when items are received you will have to enqueue them, allowing you to use any timing on the receive part.

**Comment by az-iot-builder-01** [comment]
@saixiaohui, @mfalkvidd, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mfalkvidd** [comment]
In case anyone else needs a workaround, here is what I've resorted to:
```
List<Task> tasks = new List<Task>();
Task<Message> msgTask = myDeviceClient.ReceiveAsync();
tasks.Add(msgTask);
tasks.Add(Task.Delay(1500));
await Task.WhenAny(tasks);
if (msgTask.IsCompleted)
{
    return msgTask.Result;
} else {
    return null;
}
```
It is ugly, but effective.
