### ISSUE TITLE
Having issues when I'm try to update multiple module identity twin reported properties using UpdateReportedPropertiesAsync()

### ISSUE THREAD

**Issue by Veda-Namada** [Azure/azure-iot-sdk-csharp#1015]
I'm using UpdateReportedPropertiesAsync() method to update multiple module identity twin property, and for some reason I'm getting the "service rejected the message with status: 400" exception (attached screenshot).

![image](https://user-images.githubusercontent.com/20346193/61919391-91aeda00-afa9-11e9-89d4-5209ca17d134.png)

Note: when I try and do a single property update using UpdateReportedPropertiesAsync() method all works fine, but it fail to update multiple attributes values at a time.

Any help would be much appreciated.

Thanks,
Veda.

**Comment by prmathur-microsoft** [comment]
Could you provide details requested in template for the issue - 

OS, version, SKU and CPU architecture used: 
Application's .NET Target Framework : 
Device: 
SDK version used:

**Comment by Veda-Namada** [comment]
Thanks for your reply.

OS


[cid:a73a9d0c-bee2-48b7-84a7-e7fef07a4c5c]


Device

[cid:78715499-68e4-448e-b23d-25da4c38a4a6]
Microsoft.NETCore.App - 2.1.0

Microsoft.NET.Sdk.Functions - 1.0.23

Looking forward to hear from you.

Thanks,
Veda.



Veda Namada
Software Engineer

M: +642108608747 | veda.namada@volparasolutions.com

[cid:2a4711af-1ca2-40fb-a3ee-caaf46c633b3]
Breast Imaging Analytics | www.volparasolutions.com<https://volparasolutions.com/>

Follow us:  Facebook<https://www.facebook.com/VolparaDensity/>  Twitter<https://twitter.com/VolparaDensity>  LinkedIn<https://www.linkedin.com/company/2613021/>
________________________________

**Comment by Veda-Namada** [comment]
Hi, I was wondering how are we going with this issue? were you able to replicate?
Please let me know if you need anything else from me.

**Comment by prmathur-microsoft** [comment]
Could you also provide details on 
Device:
SDK version used:

**Comment by Veda-Namada** [comment]
Thanks for your reply.
Device: IoTModuleClient

Microsoft.NET.Sdk.Functions : 1.0.29




Veda Namada
Software Engineer

M: +642108608747 | veda.namada@volparasolutions.com

[cid:cbc459fa-aaee-4456-a57a-1e69d12f9045]
Breast Imaging Analytics | www.volparasolutions.com<https://volparasolutions.com/>

Follow us:  Facebook<https://www.facebook.com/VolparaDensity/>  Twitter<https://twitter.com/VolparaDensity>  LinkedIn<https://www.linkedin.com/company/2613021/>
________________________________

**Comment by prmathur-microsoft** [comment]
Are you referring to Iot SDK from one of the releases on this GitHub repo [here?](https://github.com/Azure/azure-iot-sdk-csharp/releases) If not can you please do so ?
Also you are still missing details on **this** - 
**OS, version, SKU and CPU architecture used:**
Application's .NET Target Framework :
**Device:**
SDK version used:

**Comment by CIPop** [comment]
@Veda-Namada there is a known incompatibility between our SDK and Azure Functions v1 (the Newtonsoft.JSON). This is a known limitation: you need to switch to Azure Functions runtime v2 and .NET Core.
For more information, please refer to the Azure Functions runtime overview here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions

If you really need to work with v1 (this would be an unsupported scenario for the IoT SDK), see https://github.com/Azure/azure-iot-sdk-csharp/pull/1024 (you might also need to use binding redirects: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions)

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @Veda-Namada, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
