### ISSUE TITLE
Is there any way I can use this in android?

### ISSUE THREAD

**Issue by madhusameena** [Azure/azure-iot-sdk-csharp#1023]
I am planning to use Azure C# SDK on android Device
Could you please let me know - Is the any way I can compile and use this on Android?

**Comment by prmathur-microsoft** [comment]
We cannot officially claim support for Android as we don't test against it, however it would be interesting to see your results if you happen to try.

**Comment by madhusameena** [comment]
Hi @prmathur-microsoft I would like to do this
As of now we are trying to C-SDK.
But it is C# our live will be little easy.
Any clues how can start building this against android (ARM 64) ?

**Comment by madhusameena** [comment]
> We cannot officially claim support for Android as we don't test against it, however it would be interesting to see your results if you happen to try.

Any hints - How can I start ?

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and we will consider it as part of our planning cycle.

**Comment by madhu-sameena** [comment]
> 
> 
> Thanks for the feedback. This is currently in our backlog and we will consider it as part of our planning cycle.

Thank you for the response.
Any idea about tentative release ?

**Comment by abhipsaMisra** [comment]
> > We cannot officially claim support for Android as we don't test against it, however it would be interesting to see your results if you happen to try.
> 
> Any hints - How can I start ?

There is a sample application [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/XamarinSample) that might be able to help you get started. However, I do want to reiterate that we currently do not test, and hence claim support for Android; and these samples have not been maintained in a while.

**Comment by abhipsaMisra** [comment]
Closing this issue; currently we do not officially claim support for android, however, we do have a sample (linked above), that users can refer to for a starting point.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @madhusameena, @RubiaL, @madhu-sameena, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
