### ISSUE TITLE
No way to remove IoTHub subscriptions once they have been set

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#1026]
## Description of the issue:
Currently the C# SDK does not provide a way to remove subscriptions for DirectMethods, DesiredPropertyUpdates or C2D messages once they have been set. 

The EdgeHub has this requirement where it sets up subscriptions to IoTHub on behalf of the client (module or device) when the client sets up those subscriptions to EdgeHub. That allows one to trigger those subscriptions from the cloud.
But if the client disconnects, then EdgeHub needs to remove those subscriptions, so that they cannot be triggered from IoTHub. (Note that it cannot simply drop the connection for the client since there might be D2C telemetry that EdgeHub needs to send on behalf of the client)

AB#7304414

**Comment by prmathur-microsoft** [comment]
Thanks for filing request. We will keep this in our backlog for now and will add this feature in future.

**Comment by RubiaL** [comment]
Thanks for the feedback.This is currently in our backlog and will consider it as part of our planning cycle

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by and-rewsmith** [comment]
@RubiaL Is this still on the backlog?

**Comment by philipktlin** [comment]
Please re-open this issue and provide an update about this bug in the backlog.  thanks.

**Comment by and-rewsmith** [comment]
@prmathur-microsoft Is there a rough estimate for when this will get prioritized?

**Comment by timtay-microsoft** [comment]
@bikamani is taking a look at this now. From the look of things, IotHub itself does not respect MQTT unsubscribe messages, so it may take a while for the SDK to support this scenario.

**Comment by abhipsaMisra** [comment]
Turns out that we can unsubscribe from MQTT topics, so this fix has been added for both MQTT (will unsubscribe from topic) and AMQP (will close the links).
This has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-11-2
