### ISSUE TITLE
Possible bug when registering a device using dps

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-sdk-csharp#1039]
This issue is created after reading through the code, is completely theoretical, has not been verified to exist, and should be prioritized accordingly.

## Description of the issue:
I've looked at the code provisioning a device in the Device Provisioning Service in a couple of the supported languages, and in both C# and Java I reacted at the way the request id is created. In C#, in the class `Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningChannelHandlerAdapter`, the following code can be found:

```csharp
private ushort GetNextPacketId()
{
    unchecked
    {
        ushort newIdShort;
        int newId = Interlocked.Increment(ref _packetId);

        newIdShort = (ushort)newId;
        if (newIdShort == 0) return GetNextPacketId();

        return newIdShort;
    }
}
```

Although this provides us with a unique request id (`rid`) in the running process, it does not provide us with a globally unique id.

Imagine we would have two processes registering devices, and each of them would start at request id `1`, would there not be a risk that the first process would react to a request send from the second process just because the first process also send a request with the identical request id? Or is this somehow orchestrated by the DPS who then would have to be capable of differentiating requests from different clients although they share the same request id? My assumption was that the request id had to be unique within the DPS scope, but perhaps that is a wrong assumption?

The SDK written for JavaScript is calculating the request id using uuid (Guid in .NET). This makes more sense to me, not only because it is easier to implement, but also that it to the reader, e.g. me, doesn't start to question the boundaries of the domain this id has to be unique within.

**Comment by timtay-microsoft** [comment]
The MQTT library we use requires that packet Ids be in the form of ints, so there is no way to use a Guid here even if we wanted to. 

As for global uniqueness vs process uniqueness: The packetId only needs to be unique in the context of a given connection. Since two processes won't use the same connection, I don't see an issue with just maintaining process uniqueness.

Closing this issue due to lack of bug potential

**Comment by az-iot-builder-01** [comment]
@mattias-kindborg-axis-communications, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
