### ISSUE TITLE
Cant get SetDesiredPropertyUpdateCallback to work

### ISSUE THREAD

**Issue by Se3ker** [Azure/azure-iot-sdk-csharp#104]
I've tried a fix from below, but still does not work:
https://github.com/Azure/azure-iot-sdk-csharp/issues/45

Also isn't the device suppose to get desired properties on device boot??

Using
Microsoft.Azure.Devices.Client 1.2.10.
Win 10 IoT Core 10.0.15063.0 (Creators Update)
Raspberry Pi 3

```
    public sealed partial class MainPage : Page
    {
        DeviceClient client;

        const string deviceConnectionString = "HostName=***.azure-devices.net;DeviceId=***;SharedAccessKey=***";

        public MainPage()
        {
            this.InitializeComponent();
            client = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt);
            ListenForCloudCommandsAsync();
        }

        public async void ListenForCloudCommandsAsync()
        {
            await client.OpenAsync();
            await client.SetDesiredPropertyUpdateCallback(OnDesiredPropertyChanged, null);
        }

        private async Task OnDesiredPropertyChanged(TwinCollection desiredProperties, object userContext)
        {
            telemetryTimerPeriod = desiredProperties["TelemetryTimerPeriod"];
            txtTelemetryPeriod.Text = telemetryTimerPeriod.ToString();

            sensorsTimerPeriod = desiredProperties["SensorTimerPeriod"];
            txtSensorPeriod.Text = sensorsTimerPeriod.ToString();

            TwinCollection reportedProperties = new TwinCollection();
            reportedProperties["TelemetryTimerPeriod"] = telemetryTimerPeriod;
            reportedProperties["SensorTimerPeriod"] = sensorsTimerPeriod;

            await client.UpdateReportedPropertiesAsync(reportedProperties);
        }

    }
```

**Comment by Se3ker** [comment]
Figured out what was wrong, there was an exception
Exception thrown: 'System.Exception'
that I had to breakpoint line by line to figure out 

When I tried to update a User Interface element the callback crashed at:
txtTelemetryPeriod.Text = telemetryTimerPeriod.ToString();

with an error:
"The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"

very sneaky error.

So no UI updates here SetMethodHandlerAsync and here SetDesiredPropertyUpdateCallback

**Comment by olivierbloch** [comment]
@Se3ker - I suspect you hit the usual (sneaky) UI thread vs. main thread issue. I will go ahead and close the issue here, but in case people land here, I recommend looking into Dispatcher based solutions to have background tasks interact with UI elements of a UWP app.
