### ISSUE TITLE
Retry-after header should be used to delay and backup in case server returns statusCode >= 429

### ISSUE THREAD

**Issue by alextolp** [Azure/azure-iot-sdk-csharp#1042]
- **SDK version used:** 1.4 

## Description of the issue:

The issue we’re seeing is that retry-after header for HTTP is not observed when request are being throttled. In case of status code >= 429, there would be an exception thrown here:

https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/transport/http/src/ProvisioningTransportHandlerHttp.cs#L105 

When that happens we need to extract retry-after header and delay before retrying the operation.

**Comment by bikamani** [comment]
This is already been taken care of hence closing the issue.
