### ISSUE TITLE
Documentation for Service Client

### ISSUE THREAD

**Issue by bikamani** [Azure/azure-iot-sdk-csharp#1044]
Need high level overview documentation of features, APIs, errorcodes and when to expect for ex "DeviceNotFound" result etc for service client code

**Comment by CIPop** [comment]
Marking as a code bug since API documentation is written as `///` comments.

**Comment by abhipsaMisra** [comment]
Tracking this under #1185 ; which will have complete high-level documentation for SDK operations.

**Comment by az-iot-builder-01** [comment]
@CIPop, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
