### ISSUE TITLE
Default OperationTimeoutInMilliseconds  (4 mins) works in Disconnected State but not during Disconnected_Retrying State

### ISSUE THREAD

**Issue by vjrag** [Azure/azure-iot-sdk-csharp#1048]
**Default timeout (4 mins) works in Disconnected State but not during Disconnected_Retrying State.**

We are observing below issue with version 1.20.1 SDK (Using Default retry policy, MQTT for communication )

•	When we start the device program in Connected state and then disconnect the network (here state changes to Disconnected_Retrying due to Communication Error), SendEventAsync() and UpdateReportedPropertiesAsync() calls with await waits for ever & throws transient error when the state changes to connected. In this case Default timeout (4 mins) is not working, the program waits for ever & throws exception when it comes back to connected state.

•	When we start the device program in DisConnected state (here state changes to Disconnected due to Retry Expired), SendEventAsync() and UpdateReportedPropertiesAsync() calls with await waits for 4 mins & throws transient error. In this case Default timeout (4mins) is working.

**Comment by CIPop** [comment]
Thanks for reporting @vjrag ! This is a regression in the latest release where the behavior for retrying has changed: once the `DeviceClient` has been connected (either by implicit or explicit `OpenAsync`) it will remain connected until `Dispose` is called. The internal retry mechanism will retry forever, disregarding the `OperationTimeoutInMilliseconds`).

That said, operations themselves should timeout after the `OperationTimeoutInMilliseconds` while the SDK is still trying to connect.

**Comment by vjrag** [comment]
Thanks for the above details @CIPop . Does it mean if the Connection status changes to Disconnected or Disconnected_Retrying, SDK will internally retry forever to bring it back to Connected State ? Also, any await calls to SendEventAsync() and UpdateReportedPropertiesAsync()  should get timed out (throws transient errors) in OperationTimeoutInMilliseconds (defaulted to 4 mins ) irrespective of above states (be it Disconnected or Disconnected_retrying ?

Is my understanding is correct ? Can you pl. let me know which version of SDK has this fix ?

**Comment by CIPop** [comment]
Yes on both: the retry is already performed (it tries MaxLong number of times). The second part is the bug tracked by this issue: the operations should timeout based on the CancellationToken instead of waiting forever for the reconnect.

**Comment by davilu** [comment]
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment]
@CIPop, @vjrag, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
