### ISSUE TITLE
IotHubCommunicationException when using ReceiveAsync() on Amqp protocols

### ISSUE THREAD

**Issue by and-rewsmith** [Azure/azure-iot-sdk-csharp#1049]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Ubuntu 18.04 x64

- **Application's .NET Target Framework :** <NETVERSION> 
netcoreapp2.1

- **Device:** <DEVICETYPE> 
HP Z workstation

- **SDK version used:** <VERSION> 
\<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*" /\>

## Description of the issue:

Expected behavior:
According to the documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d), when calling the ReceiveAsync() method on the ```DeviceClient```, the message or null should be returned after the specified timeout.

"The ReceiveAsync method asynchronously returns the received message at the time that it is received by the device. It returns null after a specifiable timeout period "

This should happen when the ```DeviceClient``` is configured with any transport setting.

Issue:
If the ```DeviceClient``` is configured to use Mqtt, the expected behavior is observed. However, is the transport protocol is set to Amqp, null is never returned. Instead, an IotHubCommunicationException is thrown at the 4 minute mark.

See the original issue submitted in our iotedge repo: [link](https://github.com/Azure/iotedge/issues/1216)

## Code sample exhibiting the issue:

```
            Console.WriteLine("\nReceiving cloud to device messages from service");
            while (true)
            {
                Message receivedMessage = await deviceClient.ReceiveAsync();
                if (receivedMessage == null) continue;

                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("Received message: {0}", 
                Encoding.ASCII.GetString(receivedMessage.GetBytes()));
                Console.ResetColor();

                await deviceClient.CompleteAsync(receivedMessage);
            }
            
```

## Console log of the issue:

```
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.ReceiveAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
--- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass17_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync()
```

**Comment by CIPop** [comment]
Thanks for reporting @and-rewsmith !

**Comment by mikeasharp** [comment]
This is confirmed behaviour. I'm sure it didn't used to do it.

Ironically, if you specify the timeout, and set it to the default ReceiveAsync(Timespan.FromSeconds(240))
the exception does not occur and you get the expected NULL

**Comment by bikamani** [comment]
@and-rewsmith , @mikeasharp We have released Device client v1.21.2 which has fixes around receiveAsync on AMQP. Can you confirm whether you see this issue resolved?

**Comment by bikamani** [comment]
Have not heard back and as the issue is addressed in latest release, closing it. Please reopen if there are more questions.

**Comment by az-iot-builder-01** [comment]
@and-rewsmith, @CIPop, @mikeasharp, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Sbou** [comment]
Hi,

I upgraded my project with the release 1.21.2 and I have this exception if I don't set a specific timeout in the ReceiveAsync method.

Thanks,

**Comment by and-rewsmith** [comment]
@Sbou Is it the System.OperationCanceledException?

**Comment by bikamani** [comment]
@Sbou ,

Can you please provide more details? Are you using ReceiveAsync with CancellationToken on MQTT?

**Comment by Sbou** [comment]
It’s exactly the same behavior of the initial issue. 
I use Amqp transport protocol and I have got the same exception. 
If I set a timeout I haven’t exception and receive null value when the timeout is reached.

**Comment by bikamani** [comment]
@Sbou Can you please try a this [release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17) and let us know if you see the exception anymore?

For a timeout scenario - it is per [design ](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/DeviceClient.cs#L282)
