### ISSUE TITLE
Gateway with x509 cert

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-sdk-csharp#105]
There is no way to create a DeviceClient with both the GatewayHostName and an x509 cert properties set.  This could be fixed by providing a DeviceClient.CreateFromConnectionString which takes a DeviceAuthenticationWithX509Certificate and applies that to the DeviceClient Cert property before parsing the connection string.

**Comment by WilliamBerryiii** [comment]
I want to update this and suggest that this feature should not be implemented.  In the realm of helping developers fall into the pit of success ... mutual auth through a gateway/proxy is a non-trivial problem and one that is like very specific to the infrastructure that the solution is running on.
Assuming that the vast majority of developers will be using this sdk against Azure IoT Hub, the x509 mechanism requires one of the following 3 solutions: 

- tls/ssl client connections terminate at the IoT Hub service.
- device certificates must also be present on the intermediate gateway/proxy such that the intermediate service can masquerade as the field device for device Auth/Identity with IoT Hub.
- connections from the client must use an http/tcp proxy wrapper to pass through a transparent proxy that will allow tls/ssl termination at IoT Hub.

Given these very specific conditions ... I propose closing this issue until more developers express interest in such a feature.

**Comment by olivierbloch** [comment]
Agreed :-)
