### ISSUE TITLE
Ensure that all method responses are sent out (drained) when CloseAsync() is called

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#1050]
- **OS, version, SKU and CPU architecture used:** any
- **Application's .NET Target Framework :** any
- **Device:** any
- **SDK version used:** any DeviceClient/ModuleClient

## Description of the issue:
Today, `SetMethodCallbackAsync()` allows applications to set their own callback to receive method calls from IoT Hub. There is no way to ensure that after returning from this callback, the response actually made it to the hub prior to the application closing the connection.

__Proposed solution__
`CloseAsync()` will be modified for all protocols to ensure that any _internal_ pending I/O is completed (success or error) prior to closing the client.
_Known limitation:_ Error cases that do not result in disconnect will not be relayed to the application.

## Code sample exhibiting the issue:
```C#

// Method callback received, app returned from callback.
await deviceClient.CloseAsync();

// Today, there is a race condition that will allow the deviceClient to be closed without completing the internal response send I/O.
```

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our  backlog but do not have an ETA for this yet. Please vote on this [User voice](https://feedback.azure.com/forums/321918-azure-iot) item and it can also be used for tracking our plans. We would happily accept contributions if you decide to submit a pull request for this. Please refer to our [contribution guide.](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md)

**Comment by az-iot-builder-01** [comment]
@CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
