### ISSUE TITLE
DateTimeOffset offset is lost (converted) when using InvokeDeviceMethodAsync

### ISSUE THREAD

**Issue by arabelaa** [Azure/azure-iot-sdk-csharp#1051]
- **OS, version, SKU and CPU architecture used:** x64, Windows 10 
- **Application's .NET Target Framework :**  .NET Framework 4.6.2 
- **Device:** simulator 
- **SDK version used:** 1.18.1 

## Code sample exhibiting the issue:
I have a call on my local device that returns a DateTimeOffset. 
I am trying to call the method using a direct call. The problem occurs when
calling  `serviceClient.InvokeDeviceMethodAsync(deviceId, methodInvocation);`
Looking over the payload of CloudToDeviceMethodResult the offset dissapears.
My initial value is 

> 2019-09-09T15:52:01.416201+02:00

 and it gets converted into 

> 2019-09-09T16:52:01.416201+03:00

. 
What I wanted was for the initial value 2019-09-09T15:52:01.416201+02:00 to be kept (without conversion). I know I can set the DateTimeZoneHandling to DateTimeZoneHandling.RoundtripKind but I don't control the HttpClient that is used.

```

var serviceClient = ServiceClient.CreateFromConnectionString(_settings.IoTHubConnectionString); var cloudToDeviceMethodResult = await serviceClient.InvokeDeviceMethodAsync(deviceId, methodInvocation);
            return new DeviceMethodResponse
                {Status = cloudToDeviceMethodResult.Status, Response = cloudToDeviceMethodResult.GetPayloadAsJson()};
```

I had a look over the HttpClientHelper -
 

> private static async Task<T> ReadResponseMessageAsync<T>(
>       HttpResponseMessage message,
>       CancellationToken token)
>     {
>       if (typeof (T) == typeof (HttpResponseMessage))
>         return (T) message;
>       T obj = await message.Content.ReadAsAsync<T>(token).ConfigureAwait(false);
>       IETagHolder etagHolder = (object) obj as IETagHolder;
>       if (etagHolder != null && message.Headers.ETag != null && !string.IsNullOrWhiteSpace(message.Headers.ETag.Tag))
>         etagHolder.ETag = message.Headers.ETag.Tag;
>       return obj;
>     }

But I can't seem to find Json serializer settings being used when parsing the response.
The only option I have is to avoid using DateTimeOffset in the response payload, which I find very cumbersome.

Any help is super appreciated.

**Comment by arabelaa** [comment]
I noticed that the HttpClient used has 

`JsonFormatter.SerializerSettings.DateParseHandling = DateParseHandling.DateTime `

instead of `DateTimeOffset`. (the value for DateTimeZoneHandling is RoundtripKind, which is ok).

I think by setting the DateParseHandling to DateTimeOffset will fix the problem.

**Comment by CIPop** [comment]
Thanks for reporting @arabelaa ! We need to investigate this a bit more to understand if this is required by the IoTHub the way it is or just something that was missed in the original design.
As always, feel free to propose the change in a PR - running our E2E tests could confirm if there is any obvious problem. We would still need to understand how altering the date offset handling would impact the hub.

**Comment by abhipsaMisra** [comment]
You are correct @arabelaa , our SDK relies on the application's json serializer settings (and in it's absence, the default NewtonSoft JsonSerializerSettings) for deserializing the received method response object. Since the default DateParseHandling setting is DateTime, we end up losing some timezone information on deserialization. 

A solution would be to declare your own global json serializer setting, that sets the DateParseHandling to DateTimeOffset:

```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.DateTimeOffset,
};
```

Let me know if this helps.

**Comment by abhipsaMisra** [comment]
The above serialization settings can be used to ensure the date time offset returned is not deserialized to date time. Closing this issue.

**Comment by az-iot-builder-01** [comment]
@arabelaa, @CIPop, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
