### ISSUE TITLE
Failed to invoke method 'SetTelemetryInterval': Not found

### ISSUE THREAD

**Issue by gcogco10** [Azure/azure-iot-sdk-csharp#1060]
Hi Team

I am following this sample code using NodeJS(https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-control-device-node), this module is up and running locally on my machine, but each time run this command node BackendApplication.js i get the following error;
Failed to invoke method 'SetTelemetryInterval': Not found

var methodParams = {
  methodName: 'SetTelemetryInterval',
  payload: 10, // Number of seconds.
  responseTimeoutInSeconds: 30
};

What could i be missing, please help me team i cant troubleshoot further with this problem.

**Comment by timtay-microsoft** [comment]
You may be better off posting this issue to the Node IoT SDK issues page [here](https://github.com/Azure/azure-iot-sdk-node/issues). This issues page is for the C# IoT SDK

**Comment by CIPop** [comment]
Thanks @timtay-microsoft!

@gcogco10 I'm closing the issue here.

**Comment by az-iot-builder-01** [comment]
@gcogco10, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
