### ISSUE TITLE
Exception while trying to enroll the simulated device

### ISSUE THREAD

**Issue by IdanAviad** [Azure/azure-iot-sdk-csharp#1067]
Hello,
I’m trying to follow the IOT Provisioning Quickstarts tutorial (Create and provision a simulated TPM device using C# device SDK for IoT Hub Device Provisioning Service)
I keep getting the following exception while trying to enroll the simulated device.
Can you please help me figuring what is the problem?
I’m pretty sure that I entered a valid Endorsement key and Registration ID as displayed in the example command widow.

The Exception I get:

Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException
  HResult=0x80131500
  Message=HTTP transport exception: malformed server error message: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Certificate verification error</title>
<link rel="stylesheet" href="https://global.azure-devices-provisioning.net/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=block_style.css&sid=19512A6053955DCA4C72423A26E79FB354D479AB" type="text/css">
</head>
<body>

<div id="pagecontainer">
        <img class="icon" src="https://global.azure-devices-provisioning.net/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=images/block.png&sid=1D4BB774144039B25B1FAE9668BD032F4BCCB9A3"> 
        <h1>Certificate verification error</h1>

        <div class="row">
                <p class="label">Overview:</p>
                <p class="item">Access denied. Certificate validation failed for the following URL: global.azure-devices-provisioning.net </p>
        </div>
        <div class="row">
                <p class="label">Details:</p>
                <p class="item"><b><i>VERIFY DENY: depth=0</i></b>, Client Certificate requested: "global.azure-devices-provisioning.net"</p>
        </div>

        <div id="options">
                <p class="label">Options:</p>
                                 <form name="ask" method="get" action="https://global.azure-devices-provisioning.net/%24%24%24%26%3f%26%3f%24%24%24">
                                <INPUT type=hidden value="ask_add" name=cmd>
                                <INPUT type=hidden value="global.azure-devices-provisioning.net_a67e6792_200005DD67F9127C02CA3248A000000005DD67" name=arg>
                                
                                <INPUT type=hidden value="F0D9B52052B3FF9D2D974E51505AFD3CA941A3A9" name=sid>
                                <INPUT type=hidden value="https://global.azure-devices-provisioning.net/0ne0007BF2B/registrations/testtpmregistration1/register?api-version=2019-03-31" name=url>
                                <input type="submit" class="button" name="Override" value="   Visit Site anyway   "       >
                                </form><p class="item">Pressing the button allows you to visit the website although the certificate is not valid.</p> 
                <form action=""><input type="button" class="button" onclick="history.back();" value="   Go Back   "></form><p class="item">Click to return to the previous page:</p>
                                <p class="last-item">To find out more about why access was denied, please contact your administrator. The reference ID is 148.</p>
        </div>

        <div><img class="logo" title="Forcepoint" src="https://global.azure-devices-provisioning.net/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=images/wslogo_block_page.png&sid=6B5C8AACCD71D149375005FB9F726AF00676BE8E" alt="Forcepoint Logo">
                <div style="clear: both; overflow: hidden; height:1px;"></div>
        </div>
</div>

</body>
</html>'
  Source=Microsoft.Azure.Devices.Provisioning.Transport.Http
  StackTrace:
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.<RegisterAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.ProvisioningDeviceClientSample.<RunSampleAsync>d__3.MoveNext() in C:\IoT\azure-iot-samples-csharp-master\provisioning\Samples\device\Common\ProvisioningDeviceClientSample.cs:line 31
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.Program.Main(String[] args) in C:\IoT\azure-iot-samples-csharp-master\provisioning\Samples\device\TpmSample\Program.cs:line 71

Inner Exception 1:
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by timtay-microsoft** [comment]
Can you please provide the code that you are using that gives you this exception? And can you share more information about the device that is running it? Is this windows, linux, etc? What versions of the provisioning dependencies are you using?

**Comment by IdanAviad** [comment]
Hi,
This is the code sample from the  Azure IoT Samples for C# to simulate a TPM device on a development machine running the Windows OS:
public static int Main(string[] args)
        {
            if (string.IsNullOrWhiteSpace(s_idScope) && (args.Length > 0))
            {
                s_idScope = args[0];
            }

            if (string.IsNullOrWhiteSpace(s_idScope))
            {
                Console.WriteLine("ProvisioningDeviceClientTpm <IDScope>");
                return 1;
            }

            // Remove if a real TPM is being used.
            Console.WriteLine("Starting TPM simulator.");
            SecurityProviderTpmSimulator.StartSimulatorProcess();

            // Replace the following type with SecurityProviderTpmHsm() to use a real TPM2.0 device.
            using (var security = new SecurityProviderTpmSimulator(RegistrationId))

            // Select one of the available transports:
            // To optimize for size, reference only the protocols used by your application.
            using (var transport = new ProvisioningTransportHandlerHttp())
            // using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
            // using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.WebSocketOnly))
            {
                // Note that the TPM simulator will create an NVChip file containing the simulated TPM state.
                Console.WriteLine("Extracting endorsement key.");
                string base64EK = Convert.ToBase64String(security.GetEndorsementKey());

                Console.WriteLine(
                    "In your Azure Device Provisioning Service please go to 'Manage enrollments' and select " +
                    "'Individual Enrollments'. Select 'Add' then fill in the following:");

                Console.WriteLine("\tMechanism: TPM");
                Console.WriteLine($"\tRegistration ID: {RegistrationId}");
                Console.WriteLine($"\tEndorsement key: {base64EK}");
                Console.WriteLine("\tDevice ID: iothubtpmdevice1 (or any other valid DeviceID)");
                Console.WriteLine();
                Console.WriteLine("Press ENTER when ready.");
                Console.ReadLine();

                ProvisioningDeviceClient provClient =
                    ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, s_idScope, security, transport);

                var sample = new ProvisioningDeviceClientSample(provClient, security);
                sample.RunSampleAsync().GetAwaiter().GetResult();   //This is were I get the exception
            }

            return 0;
        }

The Device is windows 10!
What do you mean "Versions of the provisioning dependencies"? and were can I find it?

Thanks!
Idan

**Comment by timtay-microsoft** [comment]
When you add a nuget dependency to get the ProvisioningDeviceClient, you have to specify which version of the dependency you want. You can check your nuget package manager to find out which version you are using

**Comment by IdanAviad** [comment]
Hi, I updated to the latest versions:
Microsoft.Azure.Devices.Client: V1.21.1
Microsoft.Azure.Devices.Provisioning.Client: V1.4.0
Microsoft.Azure.Devices.Provisioning.Security.Tpm: V1.1.6
Microsoft.Azure.Devices.Provisioning.Transport.Amqp: V1.1.9
Microsoft.Azure.Devices.Provisioning.Transport.Http: V1.1.6
Microsoft.Azure.Devices.Provisioning.Transport.Mqtt: V1.1.8

Still, I get the same exception :(

Finally, I changed the transport layer from Http to Amqp and it worked! :)
Why it doesn't work with Http? I do not know.

**Comment by az-iot-builder-01** [comment]
@IdanAviad, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
