### ISSUE TITLE
Why Client.UWP version is not release on Nuget?

### ISSUE THREAD

**Issue by awong1900** [Azure/azure-iot-sdk-csharp#107]
I try use Microsoft.Azure.Devices.Client with Win10 iot UWP app. But it is not work. Then i found the sample on here, it use Microsoft.Azure.Devices.Client.UWP . So i want to know why this UWP library is not release on Nuget and How to use it from code?

**Comment by jasmineymlo** [comment]
@awong1900 Microsoft.Azure.Devices.Client.UWP is released with the Microsoft.Azure.Devices.Client nuget package.  Would you tell me what error you are seeing when you try to install it with your Win10 iot UWP app?  To be able to consume Microsoft.Azure.Devices.Client.UWP, we would need to use "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2".  Please check the project.json to ensure that the platform lib is at the right version.  By default, VS 2015 template has a lower version for UWP app.  Thanks.

**Comment by awong1900** [comment]
When i try use `SetMethodHandlerAsync` with Win10 iot core run on RI3. 
It is not return, just wait on here.  The same code is work on console app run on my x86 computer.
code like this:
```
        private async void button_Click(object sender, RoutedEventArgs e) {
            await deviceClient.SetMethodHandlerAsync("DisplayLCD", DisplayLCD, null);
        } 

        public static Task<MethodResponse> DisplayLCD(MethodRequest methodRequest, object userContext)
        {
            Debug.WriteLine("\t{0}", methodRequest.DataAsJson);
            return Task.FromResult(new MethodResponse(new byte[0], 200));
        }
```
BTW, i use vs2017, and the UniversalWindowsPlatform version > 5.2.2.

**Comment by awong1900** [comment]
I re-tested the UWP sample in the raspberry 3, it can run correctly. thank you for your help.
