### ISSUE TITLE
Connection status change reasons don't handle DeviceNotFoundException correctly

### ISSUE THREAD

**Issue by shantanu1singh** [Azure/azure-iot-sdk-csharp#1073]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** NETStandardLibrary 2.0
- **Device:** HP Z420
- **SDK version used:** 1.20.3-asc-edge

## Description of the issue:
The connection status change reasons currently don't correctly handle DeviceNotFoundException(s) returned from IoT hub. As a result, consumers of ModuleClient for example don't get a specific ConnectionStatusChangeReason indicating the reason and instead just get a generic Communication_Error as the reason.

## Code sample exhibiting the issue:
Not really required. If you create a ModuleClient for an edge module with a connection status change handler and then delete the device in IoT hub, the ModuleClient's connection status change handler will be invoked with a Communication_Error as the ConnectionStatusChangeReason.
The proposal is to add a new ConnectionStatusChangeReason 'Device_Not_Found' which is returned if IoT hub returns a DeviceNotFoundException.

## Console log of the issue:
None

**Comment by bikamani** [comment]
Hi @shantanu1singh ,

Why are you using 1.20.3-asc-edge? Can you use the latest version we released and let us know if the issue still exists?

Thanks.

**Comment by shantanu1singh** [comment]
I just tested with the latest version of the SDK 1.21.1 and I can confirm the issue still persists. Like I said, the code on master itself behaves this way so any version of the SDK will have the problem

**Comment by az-iot-builder-01** [comment]
@shantanu1singh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
