### ISSUE TITLE
Show recommended NuGet packages and versions in the README

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-sdk-csharp#1075]
As an OSS best practice, I'd like to know which release and pre-release package versions are recommended.

I've seen this practice used broadly in other OSS repos producing NuGet packages such as:
https://github.com/windows-toolkit/WindowsCommunityToolkit#nuget-packages

**Comment by CIPop** [comment]
@rido-min we already have the information here: 
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/doc/devguide.md#6-sdk-folder-structure 

I agree it's not as discoverable as it should be and we may want to clean up our readme.md file.

**Comment by rido-min** [comment]
@CIPop  the README links to the the doc, where I read: 
>Download from Nuget. The namespace is Microsoft.Azure.Devices.Clients, which contains IoT Hub Device Clients (DeviceClient, ModuleClient).

This information is hard to discover and is not accurate since there are packages produced from this repo that do not follow that prefix like [`Microsoft.Azure.Devices.Provisioning.Transport.Mqtt`](https://www.nuget.org/packages/Microsoft.Azure.Devices.Provisioning.Transport.Mqtt)

I'm asking for an easiest way to discover which NuGet packages are being produced from this repo, as well which are the recommended release and pre-release versions.

**Comment by abhipsaMisra** [comment]
Our latest recommended packages and their versions are maintained here:
Release packages: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/versions.csv
Pre-release packages: https://github.com/Azure/azure-iot-sdk-csharp/blob/preview/versions.csv

Would it help if we highlighted these files in our readme?

**Comment by rido-min** [comment]
yes please, also include the branch information like eg:

![image](https://user-images.githubusercontent.com/14916339/81873253-321dbd00-9530-11ea-90e0-7f3b85bea0ac.png)

**Comment by az-iot-builder-01** [comment]
@CIPop, @rido-min, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abhipsaMisra** [comment]
@rido-min I've updated our readme. This is how we are displaying the recommended versions now:
![image](https://user-images.githubusercontent.com/22563986/81966940-10274780-95cf-11ea-861d-2811d97bedd7.png)
