### ISSUE TITLE
Only 1000 devices visible in Device explorer

### ISSUE THREAD

**Issue by cima** [Azure/azure-iot-sdk-csharp#1076]
Only first 1000 device entries is listed from IoT hub in Device Explorer Twin tool. It is understandable that transfering unlimited amount of entities over network would impact both IoT hub and the desktop application but when we want to debug Device at IoT hub with more than 1000 devices we can't. It also brings lot of confusion because user is not aware of fact that only first 1000 devices are displayed.

Would it be possible to make the limit at least configurable? Of course displaying all devices is prefferable.

The limit is hardcoded here:
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/tools/DeviceExplorer/DeviceExplorer/MainForm.cs#L34

**Comment by prmathur-microsoft** [comment]
Thanks for your request, we want to evaluate if this request is something we can accommodate. In the meantime, feel free to submit a PR and I'll be happy to get it reviewed.

**Comment by timtay-microsoft** [comment]
We have officially deprecated the device explorer, so we won't add this feature.

**Comment by az-iot-builder-01** [comment]
@cima, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
