### ISSUE TITLE
How to use Device Explorer behind a proxy?

### ISSUE THREAD

**Issue by vanti** [Azure/azure-iot-sdk-csharp#108]
Hi I am trying to use the Device Explorer behind a proxy and am seeing issues. For example, when I click on "Monitor" button on the Data tab, it results in the error box below.  

![capture](https://cloud.githubusercontent.com/assets/1307572/26080510/c3fbf020-397b-11e7-9533-35d505316a9c.PNG)

Is there a port (or ports) we are expected to open up for this and other features in Device Explorer to work?

**Comment by vanti** [comment]
Also which URLs (or IP addresses) does the Device Explorer need to access?

**Comment by tameraw** [comment]
@vanti - DeviceExplorer uses AMQPs so port 5671 should be accessible on your machine, if not, then websockets port 443 should be enabled.
You need to provide DeviceExplorer with the IoT Hub connection string which contains the URL to your specific IoT Hub and the credentials.

**Comment by vanti** [comment]
Thank you tameraw for the confirmation. Would it be fair to say that the IP address for IoT hubs can be entirely different for different hubs and/or different user accounts? Just want to see if we can limit our proxy to open up port 5671 for just a subset of IP addresses as opposed to opening it for all IP addresses.

**Comment by tameraw** [comment]
@vanti - Once an IoT Hub is created, it is unlikely its IP address will change (but not 100% guaranteed). Different IoT Hubs in the same region can have different addresses and IoT Hubs across regions will definitely have different IP addresses.

A user can do an IP lookup of their hub after deployment and whitelist that, and it should work for the most part. If this is not acceptable (constant dynamic recreation of hubs, or they cannot at all tolerate IP address changes) then the user can whitelist the set of IPs based on this document here: https://www.microsoft.com/en-us/download/details.aspx?id=41653

Hope this helps.

**Comment by vanti** [comment]
Thank you for the info tameraw. Much appreciated.
