### ISSUE TITLE
iotedge module connection lose to edgeHub

### ISSUE THREAD

**Issue by scottmur** [Azure/azure-iot-sdk-csharp#1080]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Ubuntu 18.04
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> Vmware virtual machine 
- **SDK version used:** <VERSION> 

## Description of the issue:

No data is passed to azure iothub from iot edge.
EdgeHub connection lost.

service iotHub restart  - Starts processing for 2 minutes and then loses connection.
Service iotEdge restart  - Starts processing and then lose connection again

Shutdown -r - restart iot edge.   Seems to have fixed issue at the moment. 

Need to understand how to fix or stop this from occuring  again.

## Console log of the issue:

EdgeHub
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/opcpublisher is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/opcpublisher changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/opcpublisher
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/$edgeHub is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/$edgeHub changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/opcpublisher is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/opcpublisher changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/opcpublisher
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/$edgeHub is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/$edgeHub changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.140 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy] - Retrying cloud proxy operation SendMessageBatchAsync for nzs048iotedg01m/messageprocessor4j.
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpLinkHelper.SendAmqpMessageAsync(SendingAmqpLink sendingAmqpLink, AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendMessageAsync(AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendEventAsync(AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(IEnumerable`1 messages, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(IEnumerable`1 messages, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventBatchAsync(IEnumerable`1 messages)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Cloud
Proxy/ConnectivityAwareClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azu
re.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azu

/var/log/syslog  
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354757239+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=155
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354766152+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=156
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354775274+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=157
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354786440+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=158
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354797852+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=159
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354807274+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=160
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354822683+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=161
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354832543+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=162
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354843488+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=163
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354858423+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=164
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354867404+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=165
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354876459+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=166
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354886850+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=167
Oct  3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.355012093+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=168
Oct  3 14:45:51 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:45:51Z [INFO] - [mgmt] - - - [2019-10-03 01:45:51.658773524 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct  3 14:45:56 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:45:56Z [INFO] - [mgmt] - - - [2019-10-03 01:45:56.659222164 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct  3 14:46:01 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:46:01Z [INFO] - [mgmt] - - - [2019-10-03 01:46:01.668120591 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct  3 14:46:06 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:46:06Z [INFO] - [mgmt] - - - [2019-10-03 01:46:06.677292972 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)

**Comment by prmathur-microsoft** [comment]
Can you open this issue on Edgehub? I'm not sure what is needed to be fixed from C# SDK here.

**Comment by timtay-microsoft** [comment]
Closing this issue as off-topic. Feel free to file an issue on the [EdgeHub github page](https://github.com/Azure/iotedge/issues) if you have an issue with EdgeHub. If you have an issue with the C# SDK, then feel free to open a new issue that provides the context as to why the C# SDK isn't working as expected.

**Comment by az-iot-builder-01** [comment]
@scottmur, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
