### ISSUE TITLE
Null ref exception on calling some DeviceClient methods by passing null.

### ISSUE THREAD

**Issue by isyama** [Azure/azure-iot-sdk-csharp#1089]
C# Device SDK version 1.21.1.

We have some test that calls DeviceClient.AbandonAsync(message) by passing null that causes a null ref exception from SDK. There are a few more methods in DeviceClient that have the same issue (e.g. RejectAsync).

**Comment by timtay-microsoft** [comment]
Just to be clear, are you asking for the SDK to do null checks on these parameters and to throw ArgumentException if they are null?

**Comment by isyama** [comment]
yes. see the other methods in DeviceClient that throw ArgumentNullException.

**Comment by timtay-microsoft** [comment]
Closing this issue now that the fix has been checked in. The next release of this SDK will contain the proper null checks

**Comment by az-iot-builder-01** [comment]
@isyama, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
