### ISSUE TITLE
Hang occurs on calling DeviceClient.SendEventAsync when a client certificate expires.

### ISSUE THREAD

**Issue by isyama** [Azure/azure-iot-sdk-csharp#1090]
C# Device SDK version 1.21.1

We have test that does the following:
1.	Register a device with a client certificate that is about to expire.
2.	Create a DeviceClient instance with the same client cert.
3.	Check if DeviceClient.SendEventAsync succeeds before the cert expires. (it does)
4.	Wait for 30+ seconds until the cert expires.
5.	Check if DeviceClient.SendEventAsync fails after the cert expires.

Result:
The test waits on a task returned by DeviveClient.SendEventAsync that never completes or faults.

**Comment by davilu** [comment]
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment]
@isyama, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
