### ISSUE TITLE
Support for IoT PnP public preview

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-sdk-csharp#1093]
I cannot find any support for the [PnP functionality that is in public preview](https://docs.microsoft.com/en-us/azure/iot-pnp/). Is that something you are working on, or is PnP excluded from the C# SDK?

**Comment by prmathur-microsoft** [comment]
This project is work in progress and will be available soon (next month)

**Comment by mattias-kindborg-axis-communications** [comment]
Nice! What is the name of the branch if I would like to get a sneak peak?

**Comment by prmathur-microsoft** [comment]
Unfortunately we haven't yet published to github branch yet as it is WIP. We will publish it on github in few days. I'll keep you posted.

**Comment by timtay-microsoft** [comment]
The PnP SDK code has been checked into this repo's preview branch, and has had a preview release under the Microsoft.Azure.Devices.DigitalTwin.Client and Microsoft.Azure.Devices.DigitalTwin.Service nuget packages. Give it a try and let us know what you think!

**Comment by mattias-kindborg-axis-communications** [comment]
Thanks! I'll give it a try!

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @mattias-kindborg-axis-communications, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
