### ISSUE TITLE
An error "Malformed token" occur if DeviceID has Semicolon (e.g., X:1234;X:12;X:123456789)

### ISSUE THREAD

**Issue by wachi-yoshitaka** [Azure/azure-iot-sdk-csharp#1100]
An error "Malformed token" occured when access to IoTEdge via DPS (Individual Enrollments, X.509).
I specify DeviceID which has Semicolon (e.g., X:1234;X:12;X:123456789) to DPS as 'IoT Hub Device ID'.

The following is the code which is occured the error.

https://github.com/Azure/azure-iot-sdk-csharp/blob/41ae9b00c8d41f6829873714a07a4b0abdb49ea1/iothub/device/src/Common/Extensions/CommonExtensions.cs#L67

**Comment by timtay-microsoft** [comment]
Right now, the SDK uses semicolons as delimiters when parsing connection strings, so when semicolons are in the device id itself, the SDK throws this exception.

That being said, IoT Hub does allow for device ids to contain semicolons, so this behavior from the SDK is incorrect. We'll have to rethink how we parse these connection strings.

**Comment by timtay-microsoft** [comment]
The PR that you provided has now been merged into our master branch. Thanks for the contribution! I'll update this thread again once we have released a version of the SDK that contains this fix.

**Comment by wachi-yoshitaka** [comment]
Thanks.
