### ISSUE TITLE
Please make RetryStrategy public

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-iot-sdk-csharp#1101]
at present RetryStrategy is internal; IMHO this should be public to allow a developer to implement their own retry strategy

**Comment by timtay-microsoft** [comment]
The client library exposes a public interface IRetryPolicy that allows you to implement your own retry policy.

```
public class SomeCustomRetryPolicy : IRetryPolicy
{
    public bool ShouldRetry(int currentRetryCount, Exception lastException, out TimeSpan retryInterval)
    {
        //your retry definition
    }
}
```

```
IRetryPolicy customRetryPolicy = new SomeCustomRetryPolicy();
client.SetRetryPolicy(customRetryPolicy);
```

**Comment by timtay-microsoft** [comment]
@grahamehorner do you still need any help with implementing a custom retry policy?

**Comment by timtay-microsoft** [comment]
Closing this issue as it is already possible to implement custom retry policy with current APIs

**Comment by az-iot-builder-01** [comment]
@grahamehorner, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
