### ISSUE TITLE
Please, make Devices.Client.Message cloneable

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1103]
In certain use-cases we need replicas of a given Message instance. Some properties are stored in the internal dictionary SystemProperties. In normal situation it can be read through specific getters (e.g. 'MessageId' or 'To') however it doesn't differentiate between 'not defined' and 'has a default value'. E.g. if I get 'MessageId', from the returned null I cannot tell that it was defined as 'null' or wasn't defined at all.

As an effect, if I want to copy over members, and I get a 'null' value, I don't know If I should set it on the new instance. The problem is that if I chose to copy over 'null'-s, then on the target object SystemProverties will have an entry with the given property (e.g. 'MessageId' = null), and during serialization/conversion these will be written on the target (e.g. an ampq message will have a related property, see MessageConverter.cs how it checks that SystemProperties has a value defined or not) 

At this moment, I have two suboptimal options:
- treat 'null' as not defined and I don't copy those values
- access SystemProperties through reflection and read it directly

Please, add a Copy or Clone method which creates a replica of the given instance

**Comment by timtay-microsoft** [comment]
If you'd like to provide a PR for this feature, I'd be happy to review it and merge it in for you

**Comment by vipeller** [comment]
https://github.com/Azure/azure-iot-sdk-csharp/pull/1106

**Comment by abhipsaMisra** [comment]
Closing this since the related PR has been merged and fix has been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-03-31

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
