### ISSUE TITLE
Iot Hub support for IPv6

### ISSUE THREAD

**Issue by FelixXWS** [Azure/azure-iot-sdk-csharp#111]
Hello,

Does the Azure Iot Hub support IPv6? Didn't find any clear informations about that.
Thanks in advance.

**Comment by FelixXWS** [comment]
Solved it by myself.

**Comment by tojuasp** [comment]
If you solve a question, please post an answer as well.

**Comment by CIPop** [comment]
/cc @yzhong94 @nberdy 

@tojuasp There is some documentation about IPv6 support in Azure: within this FAQ: https://azure.microsoft.com/en-us/pricing/faq/ pointing here: 
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview
