### ISSUE TITLE
Cloud Explorer does not show credential errors

### ISSUE THREAD

**Issue by pkoronawa** [Azure/azure-iot-sdk-csharp#1118]
I recently changed the password to the account I used to access the Azure portal. Visual Studio was left running and continued to connect for a couple days until I had to reboot after installing system updates.

After rebooting none of my Azure resources would show up in Visual Studio, although it showed by account. Basically I could see the image below, but without the dropdown for the account.

![image](https://user-images.githubusercontent.com/47200230/68825456-07b97880-064f-11ea-9d43-e394fecf1e15.png)

Only when I checked my account in that screen did I get a message that credentials had failed. 
Please add a warning icon to the account display in this situation to remind the user to reset credentials.

**Comment by timtay-microsoft** [comment]
This issue isn't related to this codebase. This codebase is for the C# SDK for Azure IoT Hub, not for Visual Studio. If you have any issues with Visual Studio, you can report the issue [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

**Comment by az-iot-builder-01** [comment]
@pkoronawa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
