### ISSUE TITLE
Device SDK cannot be used in net standard 2.0 with some azure packages

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-sdk-csharp#112]
I faced trouble when I refer recent  `Microsoft.Azure.Devices.Client` package and `Microsoft.Azure.DocumentDB.TransientFaultHandling` package (it depends on the transient fault handling block) in my .NET 2.0 preview project. It is because .NET Core 2.0 enable using .NET Framework packages for .NET Core packages, so the type names of "transient fault handling" in the device client and original nuget packages conflict each other.

My idea is:
* Make `netstandard2.0` drop in addition to current `netstandard1.3` drop.
    * It refers `EnterpriseLibrary.TransientFaultHandling` again.
    * It removes clone of `System.Net.Http` clone of corefx.

Any thoughts?

**Comment by tameraw** [comment]
@yfakariya - You have a good point here. Give us a chance to look at another possible solution to avoid having to introduce more #ifdef in the code base.

**Comment by yfakariya** [comment]
Great, thank you!

**Comment by bmrpatel** [comment]
Any update on this support. I tried .Net Core 2.0 and get exception with error **NotImplementedException: missing API 2!** Thanks

**Comment by jasmineymlo** [comment]
@yfakariya @bmrpatel - 7efd4ba49ea03ece6a1c32b975c82bdf40c6e0a1 should fix this issue.  Please let us know if you are still seeing the issue with the latest release.  Thanks.
