### ISSUE TITLE
RegistryManager.GetTwinAsync throws exceptions

### ISSUE THREAD

**Issue by hanabi1224** [Azure/azure-iot-sdk-csharp#1122]
Message: 
    Microsoft.Azure.Devices.Common.Exceptions.IotHubException : Error converting value 1/1/0001 12:00:00 AM +00:00 to type 'System.DateTime'. Path 'statusUpdateTime', line 1, position 142.
      ----> Newtonsoft.Json.JsonSerializationException : Error converting value 1/1/0001 12:00:00 AM +00:00 to type 'System.DateTime'. Path 'statusUpdateTime', line 1, position 142.
      ----> System.InvalidCastException : Object must implement IConvertible.
  Stack Trace: 
    HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
    HttpClientHelper.GetAsync[T](Uri requestUri, TimeSpan operationTimeout, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, Boolean throwIfNotFound, CancellationToken cancellationToken)
    AzureIoTUtils.GetTwinAsync(String deviceId) line 41
    AzureIoTUtilsTests.TestGetTwinAsync(String deviceId) line 33
    GenericAdapter`1.BlockUntilCompleted()
    NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
    AsyncToSyncAdapter.Await(Func`1 invoke)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    SimpleWorkItem.PerformWork()
    --JsonSerializationException
    JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
    JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
    JsonSerializer.Deserialize(JsonReader reader, Type objectType)
    JsonSerializer.Deserialize[T](JsonReader reader)
    TwinJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
    JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
    JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    JsonSerializer.Deserialize(JsonReader reader, Type objectType)
    JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
    JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
    JsonConvert.DeserializeObject[T](String value)
    HttpClientHelper.ReadResponseMessageAsync[T](HttpResponseMessage message, CancellationToken token)
    <<GetAsync>b__9>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
    --InvalidCastException
    Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
    JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

**Comment by abhipsaMisra** [comment]
Thank you for reporting this. Could you also share the scenario and steps to reproduce this issue?

**Comment by hanabi1224** [comment]
Just set default JsonSerializerSettings.DateParseHandling to DateParseHandling.DateTimeOffset

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @hanabi1224, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
