### ISSUE TITLE
RefusedNotAuthorized:Error on PI3

### ISSUE THREAD

**Issue by awong1900** [Azure/azure-iot-sdk-csharp#113]
I have app to connect Azure with Microsoft.Azure.Devices.Client Library. When run on my computer x86 is work, but run on PI3 ARM is error. Got
```
 "Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.ni.dll
CONNECT failed: RefusedNotAuthorized:Error in sample: {0}"
````

Any advise for this?

**Comment by tameraw** [comment]
@awong1900 
1. Please confirm that have copy and pasted the correct connection string on the RPI3.
2. Also, run the [iothub-diagnostics](https://github.com/Azure/iothub-diagnostics) tool and examine the failure(s) if you get any.

**Comment by awong1900** [comment]
Thank you.  I get help from MS IoT Insider Lab. And i found the reason is time. The time of PI3 is wrong, is not sync with NTP server.

**Comment by tameraw** [comment]
@awong1900 - thanks for the update.
