### ISSUE TITLE
Missing evaluation of this.receivingSemaphore.WaitAsync(linkedCts.Token) in MqttTransportHandler.cs

### ISSUE THREAD

**Issue by mma-mm** [Azure/azure-iot-sdk-csharp#1130]
Hi,

I'm currently investigating an issue where i receive null Messages in ReceiveAsync even when timeout has not occured yet.
While trying to find out how DeviceClient works, i stumbled about this:

In iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs:306 in Method `async Task<bool> ReceiveMessageArrivalAsync(CancellationToken cancellationToken)` there is no evaluation of the WaitAsync:

    
    using (CancellationTokenSource linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, this.disconnectAwaitersCancellationSource.Token))
            {
                try
                {
      HERE ---->     await this.receivingSemaphore.WaitAsync(linkedCts.Token).ConfigureAwait(true);
                }
                catch (OperationCanceledException)
                {
                    if (!cancellationToken.IsCancellationRequested)
                    {

In the correspondig overload in iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs:282 the WaitAsync is evaluated:

    
     try
                {
    HERE--->         hasMessage = await this.receivingSemaphore.WaitAsync(timeout, linkedCts.Token).ConfigureAwait(true);
                }
                catch (OperationCanceledException)
                {
                    if (disconnectToken.IsCancellationRequested)
                    {

It might be able that messages are lost this way.

**Comment by davilu** [comment]
@mma-mm  Whenever there is message arrived `receivingSemaphore.Release()` is called on line 490 which will increase the count. While `ReceiveAsync` is called, it always acquire from `receivingSemaphore`. It could fail either device is disconnected or timeout. Otherwise  it will decrease the count and return a message. Could you please give an example of message lost?

**Comment by mma-mm** [comment]
What i'm observing:

In my Application im Receiveing Messages on the same connection object at 2 different places, once using ReceiveAsync with a Timeout set using a TimeSpan, once by handing over a CancellationToken. The one using a TimeSpan works flawlessly, receives all messages. The one using hte CancellationToken receives only null messages. I'm quite sure these are not timeouts, as is can control the sending of C2D-Messages. The null messages occur after the default timeout, or if i press the corresponding button in the cloud. 

The both calls to ReceiveAsync don't take place at the same time. 

I'm not quite sure whether the indicated line of code causes my issue, but i saw it while search for a potential issue, and was puzzled. Especially when i noticed, that before the last change to this line, hasMessage was still set.

**Comment by davilu** [comment]
@mma-mm Thanks for the details. There was a typo in last release. We're going to fix it next release.

**Comment by davilu** [comment]
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17

**Comment by az-iot-builder-01** [comment]
@davilu, @mma-mm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
