### ISSUE TITLE
[Preview] Twin desired property updates not received on AMQP

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#1132]
This issue affects the preview service API version. We are disabling these tests until service fixes this issue. ~Regular twin desired property updates are received successfully~

**Comment by abhipsaMisra** [comment]
This has been addressed as a part of #1345 . These changes need to be pulled into the `preview` branch as well.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked in, and will be released soon

**Comment by abhipsaMisra** [comment]
This has been released as a part of Microsoft.Azure.Devices.Client.1.29.1-preview-001: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2020-7-13.
Closing this issue.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
