### ISSUE TITLE
Problems with multiple instances of ModuleClient

### ISSUE THREAD

**Issue by pkoronawa** [Azure/azure-iot-sdk-csharp#1144]
## Expected Behavior
Multiple instances of **ModuleClient** should behave independently.

## Current Behavior
Order of operations on multiple instances can affect behavior. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Build the default CSharpTutorial app IoTEdgeModule1
2. Modify the Init procedure as below
3. Run in VisualStudio debug mode. It works as expected 
4. Uncomment the 4 instantiation lines and comment the 4 following. This only changes the order of method calls. Now running the app hangs and does not receive messages

```
        static async Task Init()
        {
            AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { amqpSetting };

            // Open a connection to the Edge runtime
            //ModuleClient listenerClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            //ModuleClient senderClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            //await listenerClient.OpenAsync();
            //await senderClient.OpenAsync();
            ModuleClient senderClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await senderClient.OpenAsync();
            ModuleClient listenerClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await listenerClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");

            // Register callback to be called when a message is received by the module
            await listenerClient.SetInputMessageHandlerAsync("input1", PipeMessage, senderClient);
        }
```

### Device Information
* Host OS: Windows 10
* Architecture: amd64
* Container OS: Windows containers
* docker: Version:          19.03.2
* edgeHubDev: Version - 1.0.8.4.26769994

## Logs
<details>
<summary>edgeHubDev logs</summary>

```
<4> 2019-11-27 11:01:38.429 -08:00 [WRN] - Unable to send message to DsgEdgeDevice/IotEdgeModule1 because ModuleMessages link was not found.
<4> 2019-11-27 11:02:08.434 -08:00 [WRN] - Did not receive ack for message 94b4bfb1-5288-4025-9556-e03d274deb19 from device/module DsgEdgeDevice/IotEdgeModule1
<4> 2019-11-27 11:02:08.436 -08:00 [WRN] - Error sending messages to module DsgEdgeDevice/IotEdgeModule1
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\device\DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\routing\ModuleEndpoint.cs:line 167
<4> 2019-11-27 11:02:12.210 -08:00 [WRN] - Unable to send message to DsgEdgeDevice/IotEdgeModule1 because ModuleMessages link was not found.
```
</details>

## Additional Information
I discovered this while researching #1108, but it also affected code I had written where I was separating message handling into subscriber and publisher classes, each with a private ModuleClient

**Comment by timtay-microsoft** [comment]
Which line in the above code hangs?

**Comment by pkoronawa** [comment]
It hangs in the sense that messages are not received by the handler. They time out because no ACK is received from the first message.

**Comment by timtay-microsoft** [comment]
@pkoronawa can you provide some SDK logs for this? Info on how to collect them can be seen here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by timtay-microsoft** [comment]
Closing this issue due to lack of customer input

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @pkoronawa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
