### ISSUE TITLE
ModuleClient with self signed certificates will fail on macOS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1145]
- **OS, version, SKU and CPU architecture used:** macOS 10.13, x86
- **Application's .NET Target Framework :** netcoreapp3.0
- **Device:** Desktop
- **SDK version used:** 1.29.0

## Description of the issue:
In EdgeModuleClientFactory::GetCertificateValidator [(1)](https://github.com/Azure/azure-iot-sdk-csharp/blob/2019-11-12/iothub/device/src/Edge/EdgeModuleClientFactory.cs#L114), we see that for non Windows operating system, this library uses InstalledCertificateValidator [(2)](https://github.com/Azure/azure-iot-sdk-csharp/blob/2019-11-12/iothub/device/src/Edge/InstalledCertificateValidator.cs#L39) and not CustomCertificateValidator. This leads to this library installing custom certificates on non Windows operating sysytems!

The problem is X509Store is not editable on macOS as shown in this corefx issue [(3)](https://github.com/dotnet/corefx/issues/19508) and [(4)](https://github.com/dotnet/corefx/blob/v3.1.0/Documentation/architecture/cross-platform-cryptography.md#x509store). Now this impacts any attempts at local debugging on macOS which needs environment variable `EdgeModuleCACertificateFile`. [Example issue](https://github.com/Azure/iotedgehubdev/issues/30).

**Comment by timtay-microsoft** [comment]
This does look like a bug on our SDK. If you are willing to provide a fix for this issue, I'd be happy to review it, and help it get merged in

**Comment by kiranpradeep** [comment]
This does not look like a 'good first issue' class of bug. The fix will mostly involve using CustomCertificateValidator across operating systems as the side-effect of installing certificates to user system is not acceptable (also not possible on macOS with netCore). But, InstalledCertificateValidator would have been developed when the original developer came across a blocker on non-Windows systems. I am sorry, this issue appears beyond me and most probably could only be fixed by someone with good knowledge of this SDK.

**Comment by stewartadam** [comment]
@timtay-microsoft any updates on this? This breaks the out-of-the-box local debugging on MacOS machines (i.e. when following [this](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-2018-06#develop-your-module)). See also https://github.com/Azure/iotedgehubdev/issues/308

**Comment by vinagesh** [comment]
Hi, we do not support macOS officially. We only support Windows and Linux. Thanks for reporting the issue. We do have a backlog item to support Xamarin, which is multi platform. As we are already doing some investigation on macOS, I will add this as something to investigate. However, I don't have any timelines to let you know when we will have any answers or fixes. If it happens anytime soon, I'll update here. Just to get some more understanding, do you use Visual Studio on mac?

**Comment by stewartadam** [comment]
Thanks for clarifying. That should be noted prominently on the docs - currently, the [development guides](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-2020-11) emphasize MacOS support:

> You can use a computer or a virtual machine running Windows, **macOS**, or Linux as your development machine.

**Comment by vinagesh** [comment]
Thanks for the feedback. We will update the documentation accordingly. At the moment there is no timeline or estimates for macOS support.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
