### ISSUE TITLE
Set ProductInfo in service SDK

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-sdk-csharp#1148]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10
- **Application's .NET Target Framework :** <NETVERSION> .net core 2.1
- **Device:** <DEVICETYPE> PC
- **SDK version used:** <VERSION> Microsoft.Azure.Devices 1.18.2

## Description of the issue:
Is there a way to set ProductInfo in service client?
In Azure IoT device client, there's a property `deviceClient.ProductInfo` which allows me to set ProductInfo. But in service client, no such property exists.

## Code sample exhibiting the issue:
No need to provide sample for this issue

## Console log of the issue:
No need to provide log for this issue

**Comment by timtay-microsoft** [comment]
No, there is no product info option in the service client

**Comment by blackchoey** [comment]
Thank you @timtay-microsoft Is there any plan to support setting product info in service client?

**Comment by timtay-microsoft** [comment]
No, we don't have any plans to add it now. Do you have a use case for it?

**Comment by az-iot-builder-01** [comment]
@blackchoey, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
