### ISSUE TITLE
[documentation request] using ModuleClient across threads

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1150]
This is a documentation request and so doesn't adhere to the template.

Is it safe to use a single ModuleClient instance object across threads? If yes, is it possible to add line to documentation clearing any doubt the lib user might have. Kindly point to one, if it exists.

**Comment by abhipsaMisra** [comment]
Thanks for bringing this up @kiranpradeep , I will highlight this in our documentation #1185 . 

It should be safe to use the same device client/ module client instance for client operations across threads. The only point I'd like to highlight is that if you handle the lifecycle of the client external to the SDK (for non-retryable faults, retry policy expiry, etc), you would need to make sure that the instances are properly handled while disposing and re-creating them, to ensure that you don't end up creating multiple instances across the different threads.

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
