### ISSUE TITLE
DeviceClient.ReceiveAsync() immediately times out on amqp / mqtt

### ISSUE THREAD

**Issue by and-rewsmith** [Azure/azure-iot-sdk-csharp#1154]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
OS: Ubuntu 18.04 amd64

- **Application's .NET Target Framework :** 2.1 
- **Device:** Local VM on desktop 
- **SDK version used:** 
    PackageReference Include="Microsoft.Azure.Devices" Version="1.18.2" 
    PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.21.2"

## Description of the issue:

Send a message to your desired device through ServiceClient.SendAsync(), then attempt to read the message through DeviceClient.ReceiveAsync(). It is supposed to wait for the default timeout, however immediately times out and returns null.

## Code sample exhibiting the issue:

Substitute device id and connection strings where appropriate.

```
namespace CSharpModule
{
    using System;
    using System.Text;
    using System.Threading.Tasks;
    using Microsoft.Azure.Devices;
    using Microsoft.Azure.Devices.Client;
    using Microsoft.Azure.Devices.Client.Transport.Mqtt;
    using System.Net.Security;
    using System.Security.Cryptography.X509Certificates;
    using TransportType = Microsoft.Azure.Devices.Client.TransportType;
    using Message = Microsoft.Azure.Devices.Client.Message;
    using Message2 = Microsoft.Azure.Devices.Message;

    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            Console.WriteLine(DateTime.Now);

            // var transportSettings = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            var transportSettings = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
            transportSettings.RemoteCertificateValidationCallback = (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) => true; 
            ITransportSettings[] settings = {  transportSettings };

            DeviceClient deviceClient = DeviceClient.CreateFromConnectionString("<YOUR CONNECTION STRING>", settings);
            Console.WriteLine("Initialized device client");

            Message received = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(2));
            if (received == null)
            {
                Console.WriteLine("First call to device client receive async returned null");
            }

            // This will make sure no more messages in your queue
            while (received != null)
            {
                Console.WriteLine("Removing old message from queue");
                received = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(2));
                if (received == null)
                {
                    Console.WriteLine("Done with cleanup. No more messages.");
                } 
            }

            Message2 message = new Message2();
            ServiceClient serviceClient = ServiceClient.CreateFromConnectionString("<YOUR CONNECTION STRING>");
            await serviceClient.OpenAsync();
            await serviceClient.SendAsync("<YOUR DEVICE ID>", message);

            Console.WriteLine("Starting test for ReceiveAsync with no args");
            received = await deviceClient.ReceiveAsync();
            if (received == null)
            {
                Console.WriteLine("TEST FAIL: ReceiveAsync with no args returned null");
            }
            else
            {
                Console.WriteLine("TEST SUCCESS: ReceiveAsync with no args returned message");
            }
            Console.WriteLine("Finished receive async");
            Console.WriteLine(DateTime.Now);
        }

        static Message CreateMessage()
        {
            string payload = Guid.NewGuid().ToString();
            string messageId = Guid.NewGuid().ToString();
            string property1Value = Guid.NewGuid().ToString();

            var message = new Message(Encoding.UTF8.GetBytes(payload))
            {
                MessageId = messageId,
                Properties =
                {
                    ["property"] = property1Value
                }
            };
            return message;
        }
    }
}
```

## Console log of the issue:

```
Time Elapsed 00:00:01.05
12/12/19 11:35:57 AM
Initialized device client
Removing old message from device client queue
Removing old message from device client queue
Removing old message from device client queue
Done with cleanup. No more messages.
Starting test for ReceiveAsync with no args
TEST FAIL: ReceiveAsync with no args returned null
Finished receive async
12/12/19 11:36:00 AM
```

**Comment by vipeller** [comment]
we tried to look at the recent changes and this might be related:

https://github.com/Azure/azure-iot-sdk-csharp/pull/1082/files

Our tests started failing after upgraded to 21.2 (we never used 21.1, but some version from before)
Also might be useful to know that the way our test is built is that it should receive a message really short after calling ReceiveAsync(). In fact if we specify a 0.1 second timeout value (we started from 60 secons), then most of the time the test turns green. This may indicate that the call without timeout does not wait any but returns immediately.

**Comment by and-rewsmith** [comment]
> * **OS, version, SKU and CPU architecture used:**  
>   OS: Ubuntu 18.04 amd64
> * **Application's .NET Target Framework :** 2.1
> * **Device:** Local VM on desktop
> * **SDK version used:**
>   PackageReference Include="Microsoft.Azure.Devices" Version="1.18.2"
>   PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.21.2"
> 
> ## Description of the issue:
> Send a message to your desired device through ServiceClient.SendAsync(), then attempt to read the message through DeviceClient.ReceiveAsync(). It is supposed to wait for the default timeout, however immediately times out and returns null.
> 
> ## Code sample exhibiting the issue:
> ```
> namespace CSharpModule
> {
>     using System;
>     using System.Text;
>     using System.Threading.Tasks;
>     using Microsoft.Azure.Devices;
>     using Microsoft.Azure.Devices.Client;
>     using Microsoft.Azure.Devices.Client.Transport.Mqtt;
>     using System.Net.Security;
>     using System.Security.Cryptography.X509Certificates;
>     using TransportType = Microsoft.Azure.Devices.Client.TransportType;
>     using Message = Microsoft.Azure.Devices.Client.Message;
>     using Message2 = Microsoft.Azure.Devices.Message;
> 
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             MainAsync().Wait();
>         }
> 
>         static async Task MainAsync()
>         {
>             Console.WriteLine(DateTime.Now);
> 
>             // var transportSettings = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
>             var transportSettings = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
>             transportSettings.RemoteCertificateValidationCallback = (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) => true; 
>             ITransportSettings[] settings = {  transportSettings };
> 
>             DeviceClient deviceClient = DeviceClient.CreateFromConnectionString("", settings);
>             Console.WriteLine("Initialized device client");
> 
>             Message received = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(2));
>             if (received == null)
>             {
>                 Console.WriteLine("First call to device client receive async returned null");
>             }
> 
>             // This will make sure no more messages in your queue
>             while (received != null)
>             {
>                 Console.WriteLine("Removing old message from queue");
>                 received = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(2));
>                 if (received == null)
>                 {
>                     Console.WriteLine("Done with cleanup. No more messages.");
>                 } 
>             }
> 
>             Message2 message = new Message2();
>             ServiceClient serviceClient = ServiceClient.CreateFromConnectionString("");
>             await serviceClient.OpenAsync();
>             await serviceClient.SendAsync("CI-test", message);
> 
>             Console.WriteLine("Starting test for ReceiveAsync with no args");
>             received = await deviceClient.ReceiveAsync();
>             if (received == null)
>             {
>                 Console.WriteLine("TEST FAIL: ReceiveAsync with no args returned null");
>             }
>             else
>             {
>                 Console.WriteLine("TEST SUCCESS: ReceiveAsync with no args returned message");
>             }
>             Console.WriteLine("Finished receive async");
>             Console.WriteLine(DateTime.Now);
>         }
> 
>         static Message CreateMessage()
>         {
>             string payload = Guid.NewGuid().ToString();
>             string messageId = Guid.NewGuid().ToString();
>             string property1Value = Guid.NewGuid().ToString();
> 
>             var message = new Message(Encoding.UTF8.GetBytes(payload))
>             {
>                 MessageId = messageId,
>                 Properties =
>                 {
>                     ["property"] = property1Value
>                 }
>             };
>             return message;
>         }
>     }
> }
> ```
> 
> ## Console log of the issue:
> ```
> Time Elapsed 00:00:01.05
> 12/12/19 11:35:57 AM
> Initialized device client
> Removing old message from device client queue
> Removing old message from device client queue
> Removing old message from device client queue
> Done with cleanup. No more messages.
> Starting test for ReceiveAsync with no args
> TEST FAIL: ReceiveAsync with no args returned null
> Finished receive async
> 12/12/19 11:36:00 AM
> ```

**Comment by az-iot-builder-01** [comment]
@and-rewsmith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by davilu** [comment]
Released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-12-17
