### ISSUE TITLE
Cloud-to-Device (C2D) messages don't work with device SDK 1.21.2

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#1159]
- **OS, version, SKU and CPU architecture used:** Tested on Windows 10 Desktop x64 and Ubuntu 18.04 x86
- **Application's .NET Target Framework :** Tested on .NET Core 2.x
- **Device:** Tested on laptop and Azure VM
- **SDK version used:** 1.21.2

## Description of the issue:
Cloud-to-Device (C2D) messages don't work with device SDK 1.22.2 for MQTT (it still works for AMQP though). When I roll back to 1.22.1 is starts working for MQTT, so it's a regression in the 1.22.2 update

## Code sample exhibiting the issue:
Follow the official tutorial for C2D with .NET:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d

## Console log of the issue:
[there is no log as the messages are never received]

**Comment by davilu** [comment]
Duplicated with #1130

**Comment by az-iot-builder-01** [comment]
@wickste, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
