### ISSUE TITLE
Nuget package names

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdk-csharp#116]
Please document the nuget packages to use, depending on the scenario. A search for "azure iot" returns too many results 
* https://www.nuget.org/packages?q=azure+iothub
* https://www.nuget.org/packages?q=azure+iot

I believe the main packages are 
* https://www.nuget.org/packages/Microsoft.Azure.Devices
* https://www.nuget.org/packages/Microsoft.Azure.Devices.Client

however there is also
* https://www.nuget.org/packages/Microsoft.Azure.IoTHub.IoTHubClient
* https://www.nuget.org/packages/Microsoft.Azure.Devices.Shared
* https://www.nuget.org/packages/Microsoft.Azure.Management.IotHub
* etc.

**Comment by olivierbloch** [comment]
Hi @dluc 
thanks for the input. We have already done some work to clean the Nuget Packages descriptions that are pretty descriptive today. I think what creates confusion is the other packages not directly related to Azure IoT that are showing up in the search. We'll look into this.
Regarding documentation indicating which to use for which scenario this can be clarified as well here and there.
Thanks
