### ISSUE TITLE
MQTT SendEventAsync doesn't timeout after default timeout period (4 mins)

### ISSUE THREAD

**Issue by ancaantochi** [Azure/azure-iot-sdk-csharp#1168]
- **OS, version, SKU and CPU architecture used:** <VERSION> Ubuntu 18.04 x86
- **Application's .NET Target Framework :** <NETVERSION>  netcoreapp2.1
- **Device:** <DEVICETYPE> Azure VM
- **SDK version used:** <VERSION> 1.21.3 

## Description of the issue:

The network goes down for 5 minutes, than comes back up but the SendEventAsync doesn't timeout after 4 minutes as expected. An exception is thrown after ~15minutes, which is the OS timeout for the socket. 

The code is using ModuleClient running in a container, sending directly to IotHub (no edgeHub in between).

I simulated network down in 2 ways, both with the same result:

1. ifconfig <network-interface-name> down 
2. using traffic controller to set 100% package drop

**Comment by davilu** [comment]
@ancaantochi  Which protocol was used? Could you please try latest version 1.21.3?

**Comment by ancaantochi** [comment]
I used 1.21.3 sdk version
MQTT

**Comment by ancaantochi** [comment]
Fixed by this commit: https://github.com/Azure/azure-iot-sdk-csharp/commit/c113bdecd15d06737d2cfb6335aa9bcdf96252df

**Comment by az-iot-builder-01** [comment]
@davilu, @ancaantochi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
