### ISSUE TITLE
Amqp Event Handler Memory Leaks (Closed Event...)?

### ISSUE THREAD

**Issue by thnk2wn** [Azure/azure-iot-sdk-csharp#1169]
- **OS, version, SKU and CPU architecture used:** Custom Debian based OS, ARM 32 
- **Application's .NET Target Framework :** 3.1.0-buster-slim-arm32v7
- **Device:** Custom gateway device with Raspberry Pi compute module
- **SDK version used:** 1.21.3

## Description of the issue:

During investigation of a memory leak with our application, I ran memory profiler tools such as [dotMemory](https://www.jetbrains.com/dotmemory/) and noticed various event handler memory leaks with `Amqp` objects inside of `Microsoft.Azure.Devices.Client`, most notably `AmqpIotSession`.

This shows some retained bytes with 1 hour of profiling locally.

![image](https://user-images.githubusercontent.com/120529/71825051-fe55f680-3068-11ea-9c78-2626c1d5a5ca.png)

When I look at source files such as [AmqpIotSession](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/AmqpIoT/AmqpIoTSession.cs), I see wiring of the `Closed` event without ever unwiring it.

It seems it should unsubscribe from these events, either in the event handler if a one-time event or upon disposal or wherever most appropriate.

While the retained memory here doesn't seem so bad, as our app runs for many days or weeks without restarts and sends telemetry events every 5 seconds or so, this seems to add up pretty quickly.

This app does recreate the IoT hub connection every 15 minutes. I believe this was because there were prior issues with the hub connection not being reliable long term where the connection would be lost and not automatically reconnected and then the device could no longer be remotely managed so the connection is monitored and periodically recreated. When recreated the existing device client connection sets the connection status change handler to null, disposes of device client, then recreates it.

# Reproducing
Use DeviceClient to send telemetry events to an IoT hub every few seconds. Every X minutes, recreate the device client connection. Run memory profiling tools as the app runs.

**Comment by davilu** [comment]
@thnk2wn [AmqpIotSession](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/AmqpIoT/AmqpIoTSession.cs) doesn't implement disposable and it will be garbage collected by dotnet framework. Once AMQP session is disconnected, the event handler will be triggered(only once). Once device client was disposed, all resources used by this instance(including AMQP session, AMQP link and all event handlers) will be set to no reference and will be collected by **next** garbage collection circle which is different from lower languages like c. Please refer to [C# Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals) for details.

**Comment by thnk2wn** [comment]
If disposing DeviceClient always fully cleaned up all the AMQP objects then I don't think I'd see the surviving AMQP bytes showing up in the dumps after the client is recreated and GC collection is performed. Time permitting I can try to see if I can put together a sample repo and see if the results are the same.

**Comment by thnk2wn** [comment]
I created a sample app here that pumps data through telemetry events with some diagnostics: https://github.com/thnk2wn/DeviceClientMemoryLeak. 

I haven't yet been able to reproduce the original conditions in the source app but changing that to not create the connection seems to have stopped the unbounded memory growth.

While the sample app doesn't reproduce the exact conditions, memory growth is more than expected, climbing from 24.2 MB to 43.4 MB and not dropping below 39.8 MB after several GC cycles. 

I'm guessing there's nothing from the caller side that can be done to reduce memory usage? Our app seems stable now but more memory is consumed than we'd think with less reclaimed than expected. I can probably close this but just curious is there's anything we can do in terms of optimization. We might favor reduced memory over sending speed with constrained IoT resources.

**Comment by az-iot-builder-01** [comment]
@davilu, @thnk2wn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
