### ISSUE TITLE
Frequently Getting DeviceMessageLostLockException in specific scenario

### ISSUE THREAD

**Issue by mathisharp** [Azure/azure-iot-sdk-csharp#117]
Hi Support, 

We are using DeviceClient of Azure IOT hub to receive data from cloud to device.

- **OS used:** <VERSION> Windows 7

- **Protocol used:** <VERSION> Amqp_WebSocket_Only

- **SDK version used:** <VERSION> IoT Device Client 1.2.6

- **programming language used:** <VERSION> C#

# Description of the issue:

We are using the device Id only once at a time. We repeatedly face this issue when the completeasync action in performed in disorder way. For eg.- Assume that we are performing completeaysnc action in sequence from 1 to 200 and for sometime skipping the sequencenumber 8 and 9 completeaction(until ttl expires of this messages (default ttl set for cloud to device is - 60 seconds) ) , then from 10 to 199 sequencenumber complete action is performed. Now when we are trying to do complete action for ttl expired messages 8 and 9. For Message 8 we get operation was cancelled error  and for message 9 complete action getting deviceMessagelostlockexception and also we are not setting any ExpiryTimeUtc for the message. I am writing the sample method which will reproduce the issue. Please let us know if you need anymore information. 

In simple term when two expired messages goes for completeAsync task in disorder sequence for the first message getting operation was cancelled and the second message gets devicemessagelostlockexception. Expected result is "The operation was cancelled" for second message too.

# Code sample exhibiting in C# for deviceMessagelostlockexception :

private static async void ReceiveC2dAsync()
        {
            
            Console.WriteLine("\nReceiving cloud to device messages from service");
            while (true)
            {
                try
                {
                    bool ContinueProcess = true;
                    Message receivedMessage = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(10));

                    if (receivedMessage == null) continue;
                    
                     _count = _count + 1;
                    if (_count == 8)
                    {
                        message8 = receivedMessage;
                        ContinueProcess = false;
                    }
                    else if (_count == 9)
                    {
                        message9 = receivedMessage;
                        ContinueProcess = false;
                    }
                    if (_count == 200 || _count == 201)
                    {
                        if (_count == 200)
                        {
                            
                            Console.WriteLine("localdatetime - {0}", message8.EnqueuedTimeUtc.ToLocalTime());
                            await deviceClient.CompleteAsync(message8.LockToken);
                        }
                        else
                        {
                            await deviceClient.CompleteAsync(message9.LockToken);
                        }
                    }
                    else if (ContinueProcess)
                    {
                         await deviceClient.CompleteAsync(receivedMessage.LockToken);
                    }

                    
                }
                catch (DeviceMessageLockLostException ex)
                {
                    Console.WriteLine("Error {0}", ex.Message);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error {0}", ex.Message);
                }

            }
        }

# Console log of the issue:

I have attached the sample project which will reproduce the issue. Please do run multiple project mode
 wait for 2 minutes watch receive message from cloud window the exception would raise.
[SampleProject.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1063853/SampleProject.zip)

Error The operation was canceled.
Error Exception of type 'Microsoft.Azure.Devices.Client.Exceptions.DeviceMessage
LockLostException' was thrown.

**Comment by mathisharp** [comment]
Hi Team, 
Any update.

**Comment by tameraw** [comment]
@mathisharp - Investigating with the IoT Hub service team.

**Comment by AnnapoorniS** [comment]
Hi,
It will be better if you could provide a solution for the above exception asap.
Thanks,
Annapoorni S

**Comment by mastermanu** [comment]
Hi,

Here is the basic update here:

There is a Service-Side bug where we close the AMQP Link between the Cloud and the Device if the Device attempts to complete a message that does not exist (as is the case when a message's TTL expires while the device is processing it).

We will fix the Service to not close the AMQP Link in this specific case. Thus, the expectation here will be to get a DeviceMessageLockLostException in both cases as opposed to OperationCanceledException and DeviceMessageLockLostException. There is no specific timeframe for this yet.

When you get a DeviceMessageLockLostException, the calling application should just trace it, ignore it and proceed. One of two things will happen:

1) DeviceClient receives the same message again on ReceiveAsync(). At this point, the DeviceClient can try to complete the message again.

2) DeviceClient never receives the same message again, in which case no action required anyways.

**Comment by jasmineymlo** [comment]
Just an update that service team will be working on this issue.  Thanks.

**Comment by jasmineymlo** [comment]
@mastermanu @simonporter, any update on the fix?  thanks.

**Comment by CIPop** [comment]
The way the repro is written I'm getting a lot of throttling from the serviceClient side as the Tasks are not properly awaited. (Please avoid using Wait() and instead create `async Task` methods.)

```
Error System.AggregateException: One or more errors occurred. (Device Queue depth cannot exceed 50 messages
Tracking Id:7a305ddcaa774b72abccb7e94061f5ca-G:4-TimeStamp:06/15/2018 19:39:54) ---> Microsoft.Azure.Devices.Common.Exceptions.DeviceMaximumQueueDepthExceededException: Device Queue depth cannot exceed 50 messages
Tracking Id:7a305ddcaa774b72abccb7e94061f5ca-G:4-TimeStamp:06/15/2018 19:39:54
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudToDeviceMessage.Program.<SendCloudToDeviceMessageAsync>d__3.MoveNext() in S:\repro\117\DevicetoCloudMessage\c2d\Program.cs:line 82
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CloudToDeviceMessage.Program.Main(String[] args) in S:\repro\117\DevicetoCloudMessage\c2d\Program.cs:line 64
---> (Inner Exception #0) Microsoft.Azure.Devices.Common.Exceptions.DeviceMaximumQueueDepthExceededException: Device Queue depth cannot exceed 50 messages
Tracking Id:7a305ddcaa774b72abccb7e94061f5ca-G:4-TimeStamp:06/15/2018 19:39:54
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudToDeviceMessage.Program.<SendCloudToDeviceMessageAsync>d__3.MoveNext() in S:\repro\117\DevicetoCloudMessage\c2d\Program.cs:line 82<---
```

Ran the sample for over 15 minutes without any errors after the initial few exceptions caused by the above service throttling.
