### ISSUE TITLE
Missing DPS Service client APIs for getting enrollment attestation mechanism

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#1183]
Currently, the GetIndividualEnrollment and GetEnrollmentGroup APIs don't return the symmetric key values if the enrollment uses symmetric keys for attestation. This is by design from the service side, but there are service APIs that allow you to get these values:

https://docs.microsoft.com/en-us/rest/api/iot-dps/getindividualenrollmentattestationmechanism/getindividualenrollmentattestationmechanism

https://docs.microsoft.com/en-us/rest/api/iot-dps/getenrollmentgroupattestationmechanism/getenrollmentgroupattestationmechanism

The provisioning service client should create new APIs that use the above APIs so that customers can get the symmetric key values

**Comment by timtay-microsoft** [comment]
Double check if Java SDK is missing this too, I suspect it is

**Comment by chewcw** [comment]
Hi I encountered the same problem, I remember I was able to get the symmetric key before, but now is not, just want to know if this issue being followed up by somebody?

**Comment by timtay-microsoft** [comment]
@chewcw go right ahead! No one was looking at this right now, but if you can provide a PR I'd be happy to help you merge it in.

**Comment by timtay-microsoft** [comment]
This new API has been added as of provisioning service client version 1.7.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
