### ISSUE TITLE
[documentation] Request for connection and reliability documentation

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1185]
This is a documentation request and so does not adhere to the issue template. Is it possible to add  documentation equivalent to azure-iot-sdk-c-reliability document [[1](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md)]. This help in better understanding of the sdk. Example queries since other language sdk (c, java etc) provides callbacks on message delivery/failure, but this sdk relies on exceptions

1. I like to know if the retry option set is applicable only to connection retry or is it equally applicable to messgae retries? For e.g. for MQTT, I like to know when does `DeviceClient::SendEventAsync` throw an exception (#91) for a half closed TCP connection ? 

2. I like to when on what condition does a `DeviceClient::SentEventAsync` return successfully for each of HTTP, MQTT and AMQP protocols. 
> For e.g. for MQTT does a return from SentEventAsync mean 
> 1. message is confirmed delivered to IoTHub (mqtt puback)
> 2. message is written to an sdk internal queue 
> 3. message is written to wire (os flush) ?

**Comment by abhipsaMisra** [comment]
Thanks for bringing this up @kiranpradeep ; a document like this will surely be helpful in understanding the SDK better. I am working on adding this in.

**Comment by abhipsaMisra** [comment]
To provide an update here - we've been improving the API comments throughout the library iteratively, and have a device sample [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample) that demonstrates the recommended usage pattern for our client. We've also listed the expected client status scenarios that you might encounter and how to handle them.

While this isn't completely exhaustive at the moment, we are working on adding and updating this document as we encounter areas that require further explanation.
Also, our doc team is also working on adding public documents that specify the different behavior per client protocol used.

For the question regarding `DeviceClient::SentEventAsync`, the completion of the async API represents that the data has been successfully written to the wire.

**Comment by vinagesh** [comment]
Documentation added - https://github.com/Azure/azure-iot-sdk-csharp/blob/master/DeviceConnectionAndReliabilityReadme.md
