### ISSUE TITLE
Unexpected throttle limit ServiceClient when sending C2D messages

### ISSUE THREAD

**Issue by msjonathan** [Azure/azure-iot-sdk-csharp#1189]
We are investigating an issue with our solution a azure function with eventhub ingress that sends C2D messages over IoT hub. 

Our IoT hub details are 
- We have a Standard (S1) plan
- 9 units
- Microsoft.Azure.Devices version 1.18.1 

These are the metrics of the C2D successfull message deliveries (1 min granularity) 
![image](https://user-images.githubusercontent.com/6077485/72432444-5a222d00-3797-11ea-9f8c-60481c43940d.png)

So actually we see not that many C2D messages 

Concerning the msdn page we expect to throttle from 900 message / min (9 units * 100 messages / unit) 

![image](https://user-images.githubusercontent.com/6077485/72432566-a8373080-3797-11ea-8dd0-f5ad66203ec8.png)

But we did hit multiple times the Throttle limit during that time limit - in application insights we see the following exception. 

> the request has been throttled. Wait 10 seconds and try again. Operation type: AmqpLinkOpen Tracking

The following questions arise: 

- Can we determine why we are hitting for us an unexpected throttle limit? 
- Should we re-use the instance of the ServiceClient or for each C2D message we send should we initiate a new ServiceClient (We've tested both and no difference)
- When using 1 instance of the ServiceClient there are occurrences once we hit the throttle limit no new C2D messages are sent, a restart of the Azure function fixes the issue (new instance is created) 

All remarks are welcome :-)

**Comment by davilu** [comment]
@msjonathan Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Neither connectionTimeout nor responseTimeout is passed to device side. They are used by service internally to figure out how long to wait for device to connect and device to response. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue.

**Comment by prmathur-microsoft** [comment]
As per the comment above, closing this issue. Feel free to reopen if you see further SDK side issues.

**Comment by az-iot-builder-01** [comment]
@msjonathan, @davilu, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
