### ISSUE TITLE
AMQP protocol SetConnectionStatusChangesHandler is not invoked when network goes offline/online

### ISSUE THREAD

**Issue by ancaantochi** [Azure/azure-iot-sdk-csharp#1192]
- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04 x86
- **Application's .NET Target Framework :**  netcoreapp2.1,
- **Device:** <DEVICETYPE> Azure VM
- **SDK version used:** <VERSION> 1.21.3

## Description of the issue:
I simulate network goes offline and back online with Linux tc 100% package loss
Here are the times when network goes offline/online:

2020-01-16 21:01:09.713 +00:00 Offline                                                                                                                                                                                                      2020-01-16 21:11:09.737 +00:00 [INF] Online

But the callback gets called:

<7> 2020-01-16 20:59:39.029 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Connection status changed to Connected with reason Connection_Ok                                                                                                                                                  <7> 2020-01-16 21:20:23.679 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Connection status changed to Disconnected_Retrying with reason Communication_Error                                                                                                                                <7> 2020-01-16 21:20:24.595 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Connection status changed to Connected with reason Connection_Ok

**Comment by davilu** [comment]
Fixed adding an API to enable client side heart beat for `AMQP`.

**Comment by davilu** [comment]
Close since new SDK was released.

**Comment by az-iot-builder-01** [comment]
@ancaantochi, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
