### ISSUE TITLE
No UploadToBlobAsync Operations Monitoring correlation

### ISSUE THREAD

**Issue by martinabbott** [Azure/azure-iot-sdk-csharp#12]
Hi,

When using the UploadToBlobAsync operation the SDK performs three actions that are logged in operational monitoring, e.g.,

{"time":"2016-12-21T07:31:24.1350268Z","operationName":"sasUriRequest","category":"FileUploadOperations","level":"Information","deviceId":"device1"}
{"fileUploadStatusCode":0,"time":"2016-12-21T07:31:24.8878250Z","operationName":"fileUploadToStorage","category":"FileUploadOperations","level":"Information","deviceId":"device1"}
{"time":"2016-12-21T07:31:24.8878250Z","operationName":"completionRequest","category":"FileUploadOperations","level":"Information","deviceId":"device1"}

The problem with this, is that if there are a lot of devices all uploading files, it can become nearly impossible to correlate events that relate to a single invocation of the method. I want to do this to build a dashboard so I can see when things are failing, but would currently have to group by deviceId and some vague bracket of time to determine the number of events I have, or have something like a count of each event type against a deviceId over time.

What would be good would be either the filename to be included in the monitoring, or a correlationId, or even better both.

Thanks,

Martin

**Comment by nberdy** [comment]
Thanks for the feedback! I've added a backlog item to the service to provide these fields.

Best,
Nicole

**Comment by tameraw** [comment]
@martinabbott - Closing this issue as it pertains to the service and not with the SDK. Thanks.
