### ISSUE TITLE
Getting exception when calling device method from either my code or latest Device Explorer

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#120]
I am getting the following exception when trying to call a device method:

> Microsoft.Azure.Devices.Common.Exceptions.IotHubException occurred
>   HResult=0x80131500
>   Message=Unexpected character encountered while parsing value: }. Path 'payload', line 1, position 24.
>   Source=Microsoft.Azure.Devices
>   StackTrace:
>    at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__30.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__23`2.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Azure.IoT.Extensions.ServiceClientExtensions.<InvokeDeviceMethodAsync>d__0.MoveNext() in C:\Wield\IoTHub\Wield.Gateway\Zeus\ServiceClientExtensions.cs:line 17
> 
> Inner Exception 1:
> JsonReaderException: Unexpected character encountered while parsing value: }. Path 'payload', line 1, position 24.

I have seen a post that suggested using an empty byte array in the MethodResponse would fix it but neither form is working for me:

```
			var response = new MethodResponse(new byte[0], 200);
			var response = new MethodResponse(200);

```

**Comment by v-tbert** [comment]
The error from Device Explorer: 
![image](https://user-images.githubusercontent.com/13632166/27205735-656deab6-51e7-11e7-8ab4-8c5b3de6b469.png)

**Comment by v-tbert** [comment]
I don't know if this is a correct workaround but this seems to prevent the exception by returning an empty JSON response:

var response = new MethodResponse(Encoding.UTF8.GetBytes("{}"), 200);

**Comment by jasmineymlo** [comment]
Thanks for the information.  It is a regression on the service and we are working on the fix.

**Comment by jasmineymlo** [comment]
Fix and deployed on 6/29.  Please let us know if you still see the issue.  Thanks.
