### ISSUE TITLE
RegisterInterfacesAsync does not handle ID issues, leading in wrong disconnects with retries

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-sdk-csharp#1202]
I'm using `microsoft.azure.devices.digitaltwin.client\1.0.0-preview-001`

When registering interfaces with the code below

```cs
class MyPnPInterface : DigitalTwinInterfaceClient
{
    public MyPnPInterface() : base("urn:rido:mypnpinterface:1", "myPnPInterfaceInstance"){}
}
        
class Program
{
    static async Task Main(string[] args)
    {
        var myPnPInterface = new MyPnPInterface();
        var deviceConnectionString = "<YOUR CONNECTION STRING>"; 
        using (var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt))
        {
            deviceClient.SetConnectionStatusChangesHandler((ConnectionStatus status, ConnectionStatusChangeReason reason) => Console.WriteLine(status));
            DigitalTwinClient digitalTwinClient = new DigitalTwinClient(deviceClient);
            await digitalTwinClient.RegisterInterfacesAsync("urn:rido:mydcmid", new DigitalTwinInterfaceClient[] { myPnPInterface }).ConfigureAwait(false);
        }
        Console.WriteLine("Done");
        Console.ReadLine();
    }
} 
```
The client gets disconnected and starts a retry loop
```
Connected
Disconnected_Retrying
Connected
Disconnected_Retrying
Connected
Disconnected_Retrying
```

This issue happens because the DCM ID does not follow the proper syntax
```
urn:rido:mydcmid->urn:rido:mydcmid:1
```
(note the version number)

To solve this issue:
- [ ] Clarify in docs which are the rules for DCM IDs
- [ ] If the DCM ID does not follow those rules throw an exception without trying to register
- [ ] Review the cases to start the retry logic

**Comment by davilu** [comment]
Thanks for your support. But unfortunately it's a service design issue and we're not able to solve it on SDK side. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue. Fortunately, send registration message will be optional and RegisterInterfacesAsync API is deprecated and hope it will be removed soon.

**Comment by timtay-microsoft** [comment]
Closing this issue because it is a service-side question of whether the client should send the dcm version as a part of the dcm id or not

**Comment by az-iot-builder-01** [comment]
@rido-min, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
