### ISSUE TITLE
SendEventBatchAsync does not work as expected over MQTT.

### ISSUE THREAD

**Issue by WillooWisp** [Azure/azure-iot-sdk-csharp#121]
For HTTP it works as expected, e.g. sending a batch of five messages only consumes one message in the IoT hub. But for MQTT it consumes the actual amount of messages in the batch. When looking at the implementation for MQTT in device client, it simply makes a foreach and send each message separately.

Is this a miss in the implementation or a limitation in the MQTT API that you have? It feels really bad that the behavior is not as expected for MQTT which should be the recommended protocol for IoT devices.

**Comment by WillooWisp** [comment]
Comment please, anyone?

**Comment by WillooWisp** [comment]
Come on, anyone responsible for this SDK from Microsoft must know!

**Comment by tameraw** [comment]
@WillooWisp - Apologies for the delay. Currently the service does not support Message Batching over MQTT.

**Comment by wesselkranenborg** [comment]
Any updates on this?

**Comment by tameraw** [comment]
@wesselkranenborg - Currently batching is not supported on the Service side for MQTT. For service related features, please submit in [user-voice](https://feedback.azure.com/forums/321918-azure-iot).
