### ISSUE TITLE
IotHubException on CancelJobAsync ("The requested resource does not support http method 'POST'.")

### ISSUE THREAD

**Issue by edvinnn** [Azure/azure-iot-sdk-csharp#1214]
## Description of the issue:
When calling `var status = await _jobClient.CancelJobAsync(jobId);`  it throws a IotHubException with the message 

> "The requested resource does not support http method 'POST'."

**Comment by timtay-microsoft** [comment]
Do you consistently see this behavior? Do you have a simple sample that repro's this exception?

**Comment by edvinnn** [comment]
I got the exception when calling the `CancelJobAsync` method with `jobId` argument as `null`. Apologies.

**Comment by az-iot-builder-01** [comment]
@edvinnn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
