### ISSUE TITLE
ProvisioningTransportHandlerMqtt does not support registration of a device using TPM

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-iot-sdk-csharp#1215]
## Description of the issue:
I have a little program which enrolls a device using TPM attestation in an Azure Device Provisioning Service.

This program also tries to register the device and assign it to an IoT Hub.   Since my devices will only be able to use MQTT as a transport, I have the following code:

## Code sample exhibiting the issue:
```csharp
using(var security = new SecurityProviderTpmHsm(registrationId) )
{
    // Code ommitted that enrolls the device in DPS

    using( var transport = new ProvisioningTransportHandlerMqtt(TransportFallbackType.TcpOnly) ) 
    {
        var provisioningDeviceClient = ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, idScope, security, transport);

        var result = await provisioningDeviceClient.RegisterAsync();  
}
```

When executing the code above, I get an exception that says:
```
ProvisioningClient RegisterAsync . . . 
Unhandled exception. Microsoft.Azure.Devic es.Provisioning.Client.ProvisioningTransportException: MQTT transport exception 
---> System.NotSupportedException: Security must be of type SecurityProviderX509 at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransport HandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken) 
--- End of inner exception stack trace ---at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransport HandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, Cancellat ionToken cancellationToken)
```

When I dive into the code of [ProvisioningTransportHandlerMqtt](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/transport/mqtt/src/ProvisioningTransportHandlerMqtt.cs) I indeed see that only `SecurityProviderX509` and `SecurityProviderSymmetricKey` are supported.
When I look at the [ProvisioningTransportHandlerAmqp](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/transport/amqp/src/ProvisioningTransportHandlerAmqp.cs) class however, I can see that TPM is supported, so my question is:

° Why is TPM not supported as a security type in `ProvisioningTransportHandlerMqtt` but it is supported in `ProvisioningTransportHandlerAmqp`
° Will it be added in the `ProvisioningTransportHandlerMqtt` class ?

- **OS, version, SKU and CPU architecture used:** Windows 10 x67
- **Application's .NET Target Framework :** .NET Core 3 (self contained assembly)
- **Device:** IoT Edge on Windows 2019 
- **SDK version used:**:
   ° Microsoft.Azure.Devices.Provisioning.Service 1.5.2
 ° Microsoft.Azure.Devices.Provisioning.Transport.Mqtt 1.1.9
 ° Microsoft.Azure.Devices.Provisioning.Security.Tpm 1.1.7
 ° Microsoft.Azure.Devices.Provisioning.Client 1.4.1

**Comment by timtay-microsoft** [comment]
Device provisioning using TPM is not supported over MQTT from the service side, so this isn't an SDK feature that we can add. If you want to see the service add this feature, I recommend reaching out on our [user voice channel](https://feedback.azure.com/forums/34192--general-feedback)

Closing this issue because there is nothing the SDK can add here.

**Comment by az-iot-builder-01** [comment]
@fgheysels, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
