### ISSUE TITLE
Increasing call latency over long periods of use

### ISSUE THREAD

**Issue by jezzsantos** [Azure/azure-iot-sdk-csharp#1224]
- **OS, version, SKU and CPU architecture used:** Windows 10 IoT Core arm32
- **Application's .NET Target Framework :** uap10.0
- **Device:** Custom carrier board, SolidRun NXP iMX6 SOM
- **SDK version used:** Microsoft.Azure.Devices.Client (1.22.0)

## Description of the issue:
Using the MQTT protocol, we have a UAP app that regularly (in a loop) calls various methods on `DeviceClient` including `SendEventAsync(cancellation)`, `GetTwinAsync(cancellation)` and `UpdateReportedPropertiesAsync(cancellation)`.

We also pass the `DeviceClient` instance to the `DeviceManagementClient` that we use from: https://github.com/ms-iot/iot-core-azure-dm-client. So DMClient is a possible influencer here too. 

We are seeing that over long periods of time, the time to complete the call to `UpdateReportedPropertiesAsync` gradually increases, from a few 100 milliseconds to a few hundred seconds over the course of 90mins!
This is with a permanent LAN connection on the bench.

See graph below. 
Time on the x-axis, 
Time to complete (in secs) on the y axis.
![image](https://user-images.githubusercontent.com/3137590/74275661-3099f880-4d79-11ea-8b97-8e623eba5cf8.png)

If we restart the UAP app, the latency of the calls returns to normal (~100ms).

If we force the current connection to close and reconnect, then the latency of the calls continues to grow.

See second graph below. 
Where the orange line shows where the app was restarted. 
![image](https://user-images.githubusercontent.com/3137590/74275695-427b9b80-4d79-11ea-82fb-1a15e8dcc7c8.png)

Is there something about the connection that is throttled? 
or is there something in IotHub that throttles this token's session? 
or is there some issue in the DeviceClient that needs looking at that is introducing this increasing latency?

**Comment by jezzsantos** [comment]
As another side-effect, whenever the call to `UpdateReportedPropertiesAsync` is executing, the CPU jumps from ~20% to ~80% pretty consistently.

**Comment by davilu** [comment]
@jezzsantos Thanks for reporting the issue. Could you please share what's the load(e.g.: operations/second/device, how many device client instances coexist)? 

From reviewing the code, it seems to me it is a little expensive to [handle connection status change event](https://github.com/ms-iot/iot-core-azure-dm-client/blob/c35cad18cea9833830cff3952d4b47743786e45a/src/IoTDMClientLib/AzureIoTHubDeviceTwinProxy.cs#L48). I would like to suggest you to modify it as following to improve the performance:
```
deviceClient.SetConnectionStatusChangesHandler(async (ConnectionStatus status, ConnectionStatusChangeReason reason) =>
{
    string msg = "Connection changed: " + status.ToString() + " " + reason.ToString();
    System.Diagnostics.Debug.WriteLine(msg);
    logAsyncHandler?.Invoke(msg, LoggingLevel.Verbose);

    if (status == ConnectionStatus.Disconnected && reason != ConnectionStatusChangeReason.Client_Close)
    {
        // only re-create new instance while device disconnected. 
        InternalRefreshConnection();
    }
});
```

Meanwhile there is a new release 1.23.0 for device client with several critical bug fixes for property operation might impact your application. Please let us know if it helps.

**Comment by abhipsaMisra** [comment]
@jezzsantos Another point - the code is recreating device client instance for any failure on device client operation; it is not advisable to recreate the device client instance on send message/ property update failure etc. The function `InternalRefreshConnection();` should be called **only** when the device client reports it's status as **DISCONNECTED** (as described in the example above). 
When we have multiple device client instances connecting with the same authentication token, the hub will kick off the existing connection and create a new connection. This will create an infinite loop of creating device client instances and subsequently getting kicked off. This will cause multiple device client instances fighting for the same resources, and create resource leak.

**Comment by jezzsantos** [comment]
Guys, thanks very much for the guidance. I will enact it immediately.

Also, as it turns out, we finally found the source of the CPU issues, and it was nothing to do with DeviceClient. 
With a reasonable CPU usage (<20%), the delays we see with IotHub are dramatically reduced to a few seconds.

You should probably close this issue. Sorry for wasted bandwidth.

**Comment by az-iot-builder-01** [comment]
@jezzsantos, @davilu, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abhipsaMisra** [comment]
No problem @jezzsantos ; glad to hear that you're unblocked now!
