### ISSUE TITLE
DeviceClient and its GetTwinAsync don't provide access to device id 

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#123]
DeviceClient is currently a one-to-one client of an IoTHub device. However, you can write a controller that has many DeviceClient connections that it manages. It would be helpful if the device id was exposed to ease managing many connections.

**Comment by tameraw** [comment]
@v-tbert - To unblock yourself. For managing device id --to--> device client mapping, can you simply store them as you you create them in a Dictionary<string, DeviceClient>?
