### ISSUE TITLE
Default retry policy still underflows after ~4500 retry attempts

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#1236]
Had a chat with a customer at Royal Mail who noticed that our default retry policy still underflows once it reaches very large retry counts. I need to investigate this

**Comment by davilu** [comment]
Current implementation of `ExponentialBackoff` is quite costly since it re-compute the delay from beginning. A fix could be calculate `maxedCount ` from `maxBackoff` and `deltaBackoff`, and return `maxInterval` while `currentRetryCount >= maxedCount `

**Comment by timtay-microsoft** [comment]
closing this issue due to lack of repro. We'll revisit potentially skipping calculating the backoff at a later point.

**Comment by az-iot-builder-01** [comment]
@davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
