### ISSUE TITLE
DeviceClient.SendEventAsync Blocks Indefinitely When Quota Reached using MQTT

### ISSUE THREAD

**Issue by MooVC** [Azure/azure-iot-sdk-csharp#1240]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64 (1903 18362.657)
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp3.x
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION> 1.23.0 (Microsoft.Azure.Devices.Client)

## Description of the issue:
When the quota has been reached on our free testing hub (8K), the SendEventAsync blocks indefinitely when using the TransportType MQTT, Mqtt_WebSocket_Only or Mqtt_Tcp_Only.  The same issue is not observed when using Amqp, Amqp_WebSocket_Only or Amqp_Tcp_Only.

The expected outcome is to have a DeviceMaximumQueueDepthExceededException, or some other variant that indicates the send has been unsuccessful, thrown - something other than an indefinite block.

## Code sample exhibiting the issue:

        private static async Task DoStuffAsync()
        {
            var connection = IotHubConnectionStringBuilder.Create(
                "<My Host Name>",
                new DeviceAuthenticationWithRegistrySymmetricKey("<My Device ID>", "<My Device Key>"));

            var device = DeviceClient.CreateFromConnectionString(connection.ToString(), TransportType.Mqtt);

            await device.OpenAsync();

            for (int x = 0; x < 10000; x++)
            {
                var message = new Message(Encoding.ASCII.GetBytes("Test"));

                WriteLine($"Sending {x}");

                await device.SendEventAsync(message);

                WriteLine($"Sent {x}");
            }

            await device.CloseAsync();
        }

**Comment by bikamani** [comment]
@MooVC Thanks for filing an issue, I will investigate further and post any findings.

**Comment by bikamani** [comment]
@MooVC I used a [sample ](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/MessageSample) to send messages using AMQP to ioTHub and noticed DeviceMaximumQueueDepthExceededException when reached quota. Which is expected.


Is this happening constantly for you? Are you noticing any exception when you run it again after reaching maximum quota?

**Comment by MooVC** [comment]
Hi @bikamani - thank you for taking a look at this for me.  I have indeed observed that the AMQP TransportType yields the expected DeviceMaximumQueueDepthExceededException almost immediately upon invocation.  

The issue is only being observed with MQTT.  I can also confirm that if the application is restarted, it blocks indefinitely immediately upon invoking SendEventAsync.

While I recognize that with MQTT, the DeviceMaximumQueueDepthExceededException is probably not possible it would be desirable if a timeout exception or something akin to it was thrown.  In the interim, I will be using the CancellationToken to achieve this behavior.

**Comment by bikamani** [comment]
@MooVC Sorry I did not notice you are asking for MQTT earlier. As per protocol spec " if either the Server or Client encounters a protocol violation, it MUST close the Network Connection on which it received that Control Packet which caused the protocol violation" so it is expected you would not see DeviceMaximumQueueDepthExceededException.

However I see "An existing connection was forcibly closed by the remote host" exception when using MQTT. Are you not seeing this exception when exceeded quota?

**Comment by MooVC** [comment]
Hi @bikamani - Unfortunately no, I am not seeing the "An existing connection was forcibly closed by the remote host" exception when using MQTT.  My process simply blocks, with nothing in the output window to indicate why this has happened.

**Comment by bikamani** [comment]
@MooVC sorry for the delay. Have you set any retry policy or seen a different behavior when you do so? You can refer this document for more info: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/devdoc/retrypolicy.md 

Also when you try to reconnect after reaching max quota, what's the behavior?

**Comment by bikamani** [comment]
Also can you share any logs with changes below?

```
int connectionStatusChangeCount = 0;
DeviceClient.SetConnectionStatusChangesHandler((status, statusChangeReason) =>
{
	connectionStatusChangeCount++;
	Console.WriteLine($"{nameof(ConnectionStatusChangesHandler)}: status={status} statusChangeReason={statusChangeReason} count={connectionStatusChangeCount}");
});
```

**Comment by MooVC** [comment]
Sincere thanks for the continued support.  Unfortunately I am out-of-pocket at this time and cannot commit to testing this anytime this week.  Apologies for any inconvenience.

**Comment by prmathur-microsoft** [comment]
We will be closing this for now. Once you have more information feel free to reopen this.

**Comment by az-iot-builder-01** [comment]
@MooVC, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
