### ISSUE TITLE
Mqtt subscribe to c2d topic has no topic name

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#1246]
There should be a topic like "devices/deviceid/devicebound/#", but there is not

See https://github.com/Azure/azure-iot-sdk-csharp/blob/9508bd8e5e4bfb96e9740fdda8f860cdc9974e10/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L643

**Comment by davilu** [comment]
@timtay-microsoft There was only telemetry and C2D at the beginning and C2D was called command. In `MqttTransportHandler`, while `SubscribeAsync` is called, it will call `MqttIotHubAdapter` method `SubscribeAsync(IChannelHandlerContext context, SubscribePacket packetPassed)`. If there is no topic set, it will by default use `DeviceCommandTopicFilterFormat` which is C2D topic. When more topics was introduced, the ancient code and name somehow was kept. It's not a bug but not pretty. I suggest:

- rename `SubscribeAsync` to `SubscribeC2DAsync` and set explicit topic `DeviceCommandTopicFilterFormat` in `SubscribePacket`.
- Remove the hack in `MqttIotHubAdapter` handling empty topic filter.

**Comment by az-iot-builder-01** [comment]
@davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
Closing this issue as it is now fixed. This has no meaningful impact on released packages, but it is nice from a code maintenance perspective
