### ISSUE TITLE
Device Client authenticating with invalid device Id over AMQP can get UnauthorizedException or DeviceNotFoundException depending on target framework

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-iot-sdk-csharp#1251]
## Description of the issue:

E2E test X509_InvalidDeviceId_Throw_UnauthorizedException_Amqp_WebSocket previously expected UnauthorizedException, but when we enabled netcoreapp1.1 we see DeviceNotFoundException which seems to make more sense.

The service actually returns different errors (validated through Kusto logs), and the AMQP library doesn't seem to be doing anything different based on framework. We should track the issue down to our code to see how the "open" is sent differently.

401 logs:
IsReceiver: True. Session Terminal Exception: , Link Terminal Exception: ExceptionId:3d0052aa-a65c-40c1-b1a8-55b750b5da00-Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"88758493d8ca47edb4f89956f10db351-G:5-TimeStamp:02/21/2020 02:21:26","message":"Unauthorized","timestampUtc":"2020-02-21T02:21:26.1121144Z"}

404 logs:
IsReceiver: True. Session Terminal Exception: , Link Terminal Exception: ExceptionId:5937d5f3-df0f-43b1-bc25-9b6978a332eb-Microsoft.Azure.Amqp.AmqpException: {"errorCode":404001,"trackingId":"2ecf2ce621f547fc9813fea2acdcf559-TimeStamp:02/21/2020 02:22:10-G:6-TimeStamp:02/21/2020 02:22:10","message":"DEVICE_NOT_EXIST_40ca037b-60e2-4910-b745-b485fb2c65aa","timestampUtc":"2020-02-21T02:22:10.9154923Z"}

hubName:drwE2eHubClose, deviceId:DEVICE_NOT_EXIST_40ca037b-60e2-4910-b745-b485fb2c65aa, exception:ErrorCode: DeviceNotFound
Message: Device DEVICE_NOT_EXIST_40ca037b-60e2-4910-b745-b485fb2c65aa at IotHub drwe2ehubclose not registered.
Timestamp: 02/21/2020 02:22:10
Tracking ID: 2ecf2ce621f547fc9813fea2acdcf559-TimeStamp:02/21/2020 02:22:10
Public Message: DEVICE_NOT_EXIST_40ca037b-60e2-4910-b745-b485fb2c65aa

**Comment by abhipsaMisra** [comment]
A `SendingAmqpLink` is opened as a part of the amqp session open process. The session and link properties and settings are exactly the same for both the open calls (from ns1.3 and ns2.0). We will need to check with service on the difference in behavior wrt the exception returned.

**Comment by abhipsaMisra** [comment]
Coordinating with service to investigate this difference in behavior; it's worth nothing here that ns1.3 implementation does not set client certificates, so we set `iothub-no-client-cert=true` on the websocketUri.
 
ns1.3: `{wss://abmisr-testhub02.azure-devices.net/$iothub/websocket?iothub-no-client-cert=true}`
ns2.0: `{wss://abmisr-testhub02.azure-devices.net/$iothub/websocket}`

**Comment by abhipsaMisra** [comment]
Received confirmation from service team that a device client instance attempting to connect to iot hub without having a corresponding device identity in the registry manager, should always throw UnauthorizedException. This is a security consideration, and device identities should be retrieved from the registry manager before establishing a device client connection. 
Service will fix this issue of returning different exception types, and will always return Unauthorized.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
