### ISSUE TITLE
Removing a registration for an enrollment group

### ISSUE THREAD

**Issue by salmanmanekia** [Azure/azure-iot-sdk-csharp#1252]
It would be great to have a method for removing the registration from a DPS enrolment group. Either that or having support for 'DELETE' statement in the query filter. 
The use case for us is that we are planning to have an admin UI through which the user can remove the registration records and also the IoT device.

Thanks!

**Comment by timtay-microsoft** [comment]
@alextolp does DPS have an API to accomplish this?

**Comment by vinagesh** [comment]
Hi,
DPS does support removing a registration from an enrollment group. Can you help me understand what you are looking for exactly?

https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/dps/registration?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-dps-registration-delete

https://docs.microsoft.com/bs-latn-ba/rest/api/iot-dps/deletedeviceregistrationstate/deletedeviceregistrationstate

Thanks,
Sindhu

**Comment by salmanmanekia** [comment]
hmm..
I looked into the code and the pages you shared and tried to delete a registration from a certain enrolment group but was not able to achieve that.

**Comment by vinagesh** [comment]
Can you share what you tried? What was the error you got?

**Comment by vinagesh** [comment]
I am closing this issue as I have not heard back anything. Feel free to re-open another issue if needed.

**Comment by az-iot-builder-01** [comment]
@salmanmanekia, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
