### ISSUE TITLE
Changing connection loss timeout

### ISSUE THREAD

**Issue by its-phil** [Azure/azure-iot-sdk-csharp#1257]
If I pull the Ethernet cable after having established a DeviceClient connection to IoT Hub it takes 4 min before the DeviceClient invokes the handler registered with `SetConnectionStatusChangesHandler`. Is it possible to change this 4 min timeout? Setting `DeviceClient .OperationTimeoutInMilliseconds` doesn't seem to affect the timeout after connection loss.

**Comment by abhipsaMisra** [comment]
Which protocol are you using for communication? It's worth noting that HTTP is stateless, and will not respond to connection status change events. MQTT and AMQP however should relay the connection status change events if you have a handler set.

**Comment by timtay-microsoft** [comment]
If you aren't actively sending any information over the connection, the SDK will only callback to the connection status change handler once the connection heartbeat is sent, and fails to be ack'd

**Comment by its-phil** [comment]
Thank you for your replies. I forgot to mention it. I'm using AMQP.
@timtay-microsoft So I'm guessing I'd have to change the connection heartbeat interval if I wanted to change the time it takes to detect a lost connection. Is the heartbeat interval an option that can be configured from the DeviceClient side?

**Comment by its-phil** [comment]
Adding to my own question: according to [these release notes](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/lts_2020-1-31) it seems possible. I'm looking into this.

**Comment by its-phil** [comment]
Ok, setting `AmqpTransportSettings.IdleTimeout` works for me. I wasn't aware of the new DeviceClient release. Thanks for pointing me in the right direction!

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @its-phil, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
