### ISSUE TITLE
Question: Could you please let us know what are openTimeout and operationTimeout means?

### ISSUE THREAD

**Issue by ganesanarun** [Azure/azure-iot-sdk-csharp#126]

**Comment by ganesanarun** [comment]
We found that operationTimeout is the one actually dealt with server timeout when it takes more than defined time on the server to process the request. Could you please tell us how can we override the timeout?
Many thanks in advance.

**Comment by ganesanarun** [comment]
Could  you please give us  your feedback as soon as possible?

**Comment by jasmineymlo** [comment]
operationTimeout is the maximum time limit applied to an operation.  By default, it is 4 minutes.  So, sdk is supposed to retry on the specific operation until timeout or successfully.  You should be able to change the timeout by setting OperationTimeoutInMilliseconds in device client.  Hope this helps
