### ISSUE TITLE
Question: Why is 'TransportType.Amqp' not supported?

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-sdk-csharp#1263]
Have a question regarding Amqp Transport, which originally tried to use TCP and then to fallback to websockets. 
Here is the code, which obiously require us to decide between two transports:

>   switch (transportType)
>             {
>                 case TransportType.Amqp_WebSocket_Only:
>                 case TransportType.Amqp_Tcp_Only:
>                     this.transportType = transportType;
>                     break;
>                 case TransportType.Amqp:
>                     throw new ArgumentOutOfRangeException(nameof(transportType), transportType, "Must specify Amqp_WebSocket_Only or Amqp_Tcp_Only");
>                 default:
>                     throw new ArgumentOutOfRangeException(nameof(transportType), transportType, null);
>             }

Why is this transport no more supported?

**Comment by barustum** [comment]
Hi Damir,

The C# SDK does support Amqp transport type if you create a DeviceClient while specifying the Amqp transport type:
`public static DeviceClient CreateFromConnectionString(string connectionString, string deviceId, TransportType transportType);`

In this case, the SDK will initialize the device client with TransportSettings Amqp_Tcp_Only and Amqp_WebSocket_Only. 

However, if you create the device client using a prioritized list of transports, by calling:
`public static DeviceClient CreateFromConnectionString(string connectionString, ITransportSettings[] transportSettings);`
then you would need to specify each transport setting with the transport type:
```
var amqpTransportTcp = new AmqpTransportSettings(Client.TransportType.Amqp_Tcp_Only);
// specify the transport specific settings, like operation timeout, keep-alive, proxy etc
var amqpTransportWs = new AmqpTransportSettings(Client.TransportType.Amqp_WebSocket_Only);
// specify the transport specific settings, like operation timeout, keep-alive, proxy etc
var transportSettings = new ITransportSettings[] { amqpTransportTcp, amqpTransportWs };
var deviceClient = DeviceClient.CreateFromConnectionString("<device_connection_string_here>", transportSettings );
```

I hope this helps.

**Comment by barustum** [comment]
I am closing this issue as I have not heard back from Damir. Feel free to re-open another issue if needed.

**Comment by az-iot-builder-01** [comment]
@ddobric, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
