### ISSUE TITLE
[API query] DeviceClient ReceiveAsync does not have delegate/callback handler 

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1289]
- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04 x86
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Laptop
- **SDK version used:** 1.20.0

## Description of the issue:
This is more of a query and API request. In DeviceClient[[1](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.receiveasync?view=azure-dotnet)], `ReceiveAsync` does not have delegate/callback handler API equivalent to SettMethodHandlerAsync[[2](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.setmethoddefaulthandlerasync?view=azure-dotnet)]/SetDesiredPropertyUpdateCallbackAsync/SetConnectionStatusChangesHandle API. 

This forces the lib user to poll for checking C2D messages (harder if there are multiple devices to manage). Is it intentional that every other method has a delegate/callback and not `ReceiveAsync`? If not, is it possible to provide delegate/callback API for receiving C2D messages?

AB#7288824

**Comment by prmathur-microsoft** [comment]
We will add this to our backlog and plan to address this in future.

**Comment by timtay-microsoft** [comment]
This API was designed this way likely because HTTP/MQTT/AMQPS all need to support receiving cloud to device messages. AMQPS/MQTT could theoretically have a callback like you want, but HTTP doesn't fit well with this approach since HTTP. Even if we tried to make HTTP fit into an API like this, the SDK would have to implicitly poll iothub to get those messages which seems messy.

@abhipsaMisra how feasible would it be to implement this suggested API with the caveat that it only works for amqp/mqtt?

**Comment by abhipsaMisra** [comment]
@timtay-microsoft Yes, that is how I see it; I would add callbacks for ReceiveAsync() that would be supported only over AMQP and MQTT, being in parity with how callback based method and twin APIs are also supported only over AMQP and MQTT.

**Comment by abhipsaMisra** [comment]
This has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-11-2

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, @prmathur-microsoft, @timtay-microsoft, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
