### ISSUE TITLE
Misleading NotSupportedException text in ProvisioningTransportHandlerMqtt

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-iot-sdk-csharp#1290]
## Description of the issue:
When no message security object is available `ProvisioningTransportHandlerMqtt` throws an exception stating the only supported type is X509, however this is untrue.  Both X509 and Symmetric Key are supported.

## Code sample exhibiting the issue:
[Link to unclear message](https://github.com/Azure/azure-iot-sdk-csharp/blob/5e09aae4a14aa7a1b47994960644e5c05f44a36b/provisioning/transport/mqtt/src/ProvisioningTransportHandlerMqtt.cs#L133)

## Console log of the issue:
```
Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException:
MQTT transport exception ---> System.NotSupportedException: Security must be of type SecurityProvierX509
```

**Comment by abhipsaMisra** [comment]
Thank you for identifying this issue and submitting this PR @jlorich !

While reviewing the code I found that our other transport protocols (HTTP and AMQP) also had the out-dated exception message, so I added the fix via #1295  .
The fix has been merged-in, and we will plan to get this released soon.

**Comment by abhipsaMisra** [comment]
This fix is now released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-03-31

**Comment by az-iot-builder-01** [comment]
@jlorich, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
