### ISSUE TITLE
[API query] Message class isn't serializable and deserializable

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1297]
## Description of the issue:
This is more of a query and API request and so not adhering to issue template. The Message class[[1](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.message?view=azure-dotnet)] `GetBytes` method gives only body content and not the message properties. 

This makes it to hard to serialize/deserialize the Message object. We have cases on which Message object need to be shared between computers. Is it possible add a new method and constructor to be inclusive of message properties?

**Comment by abhipsaMisra** [comment]
@kiranpradeep - The message class has a [public method](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Message.cs#L338) `CloneWithBody` which can be used to copy over the message content, along with the system and application properties. Would this method fulfil your requirement?

**Comment by kiranpradeep** [comment]
@abhipsaMisra Thanks for the reply. But, no, `CloneWithBody` will not help share `Message` object between computers.  In my case, I have an MQTT or AMQP broker (not the edgeHub) in between, through which I like to share the `Message` object. Only way is proper a serialize/deserialize inclusive of message properties.

**Comment by timtay-microsoft** [comment]
I'm hesitant to add serialization/deserialization logic to the message class considering this SDK never serializes/deserializes it. This request seems like something that could easily live in a helper function outside of this SDK considering how atypical this usage of our Message class is

**Comment by kiranpradeep** [comment]
@timtay-microsoft I agree. Thanks. Closing.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @kiranpradeep, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
