### ISSUE TITLE
Method CloseAsync from DeviceClient throws NotImplemented Exception

### ISSUE THREAD

**Issue by bartoszbr** [Azure/azure-iot-sdk-csharp#13]
Hi,
I updated library Microsoft.Azure.Devices.Client from NuGet to the newest version 1.1.4 and now calling method CloseAsync from DeviceClient object throws NotImplemented Exception.
I checked it on older version: 1.1.2 and 1.0.22 and it worked correctly.

**Comment by jasmineymlo** [comment]
Hi bartoszbr,

Sorry for the late reply.  This is a regression and the fix is ready in develop branch (commit 8e1611a2faf4d24541c3ff6f60bfa4d0ecd9b919)

Regards,
Jasmine
