### ISSUE TITLE
App crashes upon connection status change 

### ISSUE THREAD

**Issue by asadDivvy** [Azure/azure-iot-sdk-csharp#1306]
- **OS and version used:** Android 10 (Q)

- **Java runtime used:** Java 8 (version 1.8)

- **Microsoft.Azure.Devices.Client version used:** 1.24.0

- **Microsoft.Azure.Devices.Provisioning.Transport.Amqp version used:** 1.2.1

## Description of the issue:
I assign the connection status change handler using `DeviceClient.SetConnectionStatusChangesHandler`. While it works fine in most of the scenarios, it crashes the app in a particular scenario. try/catch doesn't prevent the app from crashing as the exception is thrown somewhere in the native code, and it is not propagated back. It can be reproduced by following the steps given below:

1. Launch the app and wait for it to connect successfully to the IoTHub (`ConnectionStatus` reported to be `Connected`)

2. Turn off the wifi through the Android quick settings (swipe down from the top of the screen to access the quick settings)

3. Wait for the `ConnectionStatus` to be reported `Disconnected_Retrying`

4. Now, keep the wifi off (effectively keeping the `DeviceClient` in the `Disconnected_Retrying` state) for at least 5 hours. **IMPORTANT:** Make sure that the app remains in foreground and the display of the device remains on during this whole time.

5. After at least 5 hours, turn the wifi back on through the Android quick settings.

Once the device connects to the internet successfully, the `ConnectionStatus` is reported back as `Connected` as expected but the app crashes within the next 40 seconds.

During those 40 seconds after the status report, the console window gets littered with the following logs:
<img width="980" alt="Screen Shot 2020-04-01 at 7 52 23 pm" src="https://user-images.githubusercontent.com/57643989/78118198-60e54580-7452-11ea-9159-fd4ccf4d1b82.png">

The last log entry indicates some native crash.

## Things tried so far

1.  Added some logic to remove the handler assigned using `DeviceClient.SetConnectionStatusChangesHandler` just before turning the wifi back on after 5 hrs. Since there was no handler assigned anymore, the status was never reported but the app didn't crash and those weird logs in the console never appeared.

2. Returned from the status change handler straightaway (effectively preventing the execution of any other logic in the handler) after the status was reported upon reconnect after 5 hrs. The app crashed again and there were those logs printed again. This test was conducted just to make sure that our app is not doing anything upon status change which leads to this crash.

AB#7288820

**Comment by abhipsaMisra** [comment]
Thank you for the detailed explanation @asadDivvy !
Before we dive into the specifics, I see that you are using Microsoft.Azure.Devices.Client version v1.24.0 on an Android app. 
- Are you using a xamarin app to run your application?
- Does this issue only occur if the device is disconnected for >5hrs? Is it able to recover successfully otherwise?
- For the pt 1 that you've tried above, is there any other operation that you carry out after turning the wifi back on? What I am getting at is, do you find the device client instance still usable at that point?
- You've mentioned that you're using our provisioning amqp transport package in your application. Which transport protocol are you using for initializing the device client?

**Comment by asadDivvy** [comment]
- Yes I'm using Xamarin.Android (NOT Xamarin.Forms) app.
- If disconnected for >5hrs, the issue always occurs.
- If disconnected for <5hrs, the issue happens extremely rarely; not sure about the steps to reproduce it at this stage though. Sometimes a connection loss for a few minutes and sometimes a momentary connection loss can trigger the issue.
- As I mentioned in the description, I return immediately from the handler I provide using `DeviceClient.SetConnectionStatusChangesHandler` to make sure none of my logic gets executed when this handler is called.
- I'm not carrying out any operation upon wifi state change; in fact nowhere in app I'm listening to the network changes to carry out any operation.
- I'm using `TransportType.Amqp` as transport type. DeviceClient creations looks like:
`async Task<DeviceClient> GetDeviceClient()
        {
            using (var security = new SecurityProviderX509Certificate(LoadProvisioningCertificate()))
            using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
            {
                var provClient = ProvisioningDeviceClient.Create(
                    Locator.SettingsProvider.GlobalDPSUrl,
                    Locator.SettingsProvider.DPSScopeID,
                    security,
                    transport);

                var result = await provClient.RegisterAsync();

                if (result.Status != ProvisioningRegistrationStatusType.Assigned)
                    throw new Exception("ProvisioningRegistrationStatusType != Assigned");

                var authMethod = new DeviceAuthenticationWithX509Certificate(
                    result.DeviceId,
                    (security as SecurityProviderX509).GetAuthenticationCertificate());

                return DeviceClient.Create(result.AssignedHub, authMethod, TransportType.Amqp);
            }
        }`

**Comment by abhipsaMisra** [comment]
Thanks for the update @asadDivvy !
We currently don't test our library against Android, so I am unable to comment if it is compatible right out-of-the-box, or if it requires any kind of modifications. 
Is there a specific scenario that you are looking to support where devices might go offline for around 5hrs?

**Comment by asadDivvy** [comment]
We are planning to deploy our devices in field and manage them remotely; a device will be running our app in a kiosk mode. We need to consider all possible conditions our device might be exposed to. Prolonged internet unavailability is one of those conditions that, practically speaking, can and will happen at some stage.

**Comment by abhipsaMisra** [comment]
I agree.

Coming back to the error above: since Android is not one of the platforms that we currently officially support, we do not have an existing setup to test this scenario in. I'll try to repro this issue in a standard console app, and verify if reconnection succeeds after 5hrs; in the meanwhile, would you be able to see if the following method works for you for collecting SDK logs: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs#console-logging
The SDK writes to event traces, which are usually collected via a tracing tool. Since we do not have an android specific instruction, would you be able to try routing the logs to the console output and collect them.

**Comment by asadDivvy** [comment]
On Xamarin, `EventSource.GetSources()` throws `NotImplementedException` even though according to [this](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource.getsources?view=netframework-4.8) document it is available on `Xamarin.Android 7.1`. I took a look at [EventSource.cs](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs) in the source code of the mono project and indeed it throws `NotImplementedException`. Is there any other way to grab the logs you're after? Android studio does provide tools to access system level logs (which I've already provided) but I assume you are after trace level logs?

**Comment by abhipsaMisra** [comment]
Thanks for analysis @asadDivvy ; yes, I am looking for our SDK logs, which will give us additional information on the state of the device client when this issue occurs. Our SDK writes to EventSource, but if that is not implemented by the mono project, then I am not sure how else we can capture those traces. I'll see if I can find any pointers on how to investigate this further.

**Comment by asadDivvy** [comment]
@abhipsaMisra could you please try to repro this issue in a standard console app, and verify if reconnection succeeds after 5hrs, just as you mentioned few days back. Thanks

**Comment by abhipsaMisra** [comment]
HI @asadDivvy ; sure, with a console app targeting .netcore app 3.1, the device client does recover it's connection successfully after 5hrs (I had it disconnected for ~7hrs).

**Comment by drwill-ms** [comment]
Moving all Xamarin issues to this discussion #2103.
