### ISSUE TITLE
[PnP] PnP Service client returns Response<x>, but Response is always null

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#1319]
The SDK should be returning the raw http response, but it is always null. We did this originally because we wanted to return Response<x> eventually, but the Azure.Core library wouldn't let us. Now the Azure Core library does allow us to build these Response objects, so we can fix this bug

**Comment by vinagesh** [comment]
Closing as something that will be implemented in the new track2 SDK. This was a design decision in the old SDK.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
