### ISSUE TITLE
Dead link on CaptureLogs Readme

### ISSUE THREAD

**Issue by yophilav** [Azure/azure-iot-sdk-csharp#1328]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:
On the read me page for CaptureLogs
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/tools/CaptureLogs/readme.md

The link http://blogs.microsoft.co.il/sasha/2017/03/30/tracing-runtime-events-in-net-core-on-linux/
under Linux section is not accessible due to Error establishing a database connection

**Comment by abhipsaMisra** [comment]
Thanks for bringing this up @yophilav ; I'll get this fixed right away!

**Comment by abhipsaMisra** [comment]
The fix is checked into master, closing this.

**Comment by az-iot-builder-01** [comment]
@yophilav, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
