### ISSUE TITLE
Error using Connection Pooling with DeviceClient, AMQP and X509 certificates

### ISSUE THREAD

**Issue by ChrWeinert** [Azure/azure-iot-sdk-csharp#1332]
We want to use AMQP to connect several IoT Devices through a field gateway to a Microsoft Azure IoT Hub. Each IoT Device has its own X509 certificate to authenticate itself at the IoT Hub.

Our field gateway will open a lot of connections to the IoT Hub - one for each IoT Device and one for himself. This may cause a firewall to block our communication because it looks like a DoS attack.

To prevent this, we want to use the AMQP Connection Pooling "feature". 
```
// some steps earlier I get the connection info from the 
// Azure Device Provisioning service
// and have the essential information stored
// in the _ConnectionInfo object

AmqpConnectionPoolSettings poolSettings = new AmqpConnectionPoolSettings();
poolSettings.MaxPoolSize = 1;
poolSettings.Pooling = true;
poolSettings.ConnectionIdleTimeout = new TimeSpan(0, 1, 0);

AmqpTransportSettings settings = new AmqpTransportSettings( TransportType.Amqp_WebSocket_Only , 50, poolSettings);
settings.ClientCertificate = _ConnectionInfo.ClientCertificate;
settings.OpenTimeout = new TimeSpan(0, 1, 0);
settings.OperationTimeout = new TimeSpan(0, 1, 0);

_Client = DeviceClient.Create(_ConnectionInfo.AssignedHub, _ConnectionInfo.AuthenticationMethod, new ITransportSettings[] { settings });
```
   
After doing some search at google it seems that the AMQP

Protocol does not support Connection Pooling wiht X509 certificate authentification.

Can someone confirm this or give me some hint what the reason for the connection issue may be.

Best Regards

Chris

**Comment by abhipsaMisra** [comment]
That is correct, we don't support pooling when the authentication mechanism is X509 certificates. This is because X509 authentication based connections do not have a cbs link, over which we otherwise multiplex the individual devices which share a common group auth token.

**Comment by timtay-microsoft** [comment]
Closing this issue since we don't support this use of pooling

**Comment by az-iot-builder-01** [comment]
@ChrWeinert, @abhipsaMisra, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
