### ISSUE TITLE
RegistryManager.GetDeviceAsync() is probably leaking TCP connections

### ISSUE THREAD

**Issue by smolyakoff** [Azure/azure-iot-sdk-csharp#1334]
- **OS, version, SKU and CPU architecture used:** Azure App Service for Windows (P1V2 service plan)
- **Application's .NET Target Framework :** netcoreapp2.2
- **SDK version used:** v1.20.1

## Description of the issue:
We are facing high outbound TCP connection usage on Azure App Service instances that communicate to IoT Hub during the load/stability tests. The monitoring information shows that more than 1.5K outbound TCP ports remain open while we simulate 100 users using our application (each user owns up to 3 devices during the test). 

![2020-04-15_14-37-41](https://user-images.githubusercontent.com/1292603/79333131-aad82c00-7f26-11ea-946c-97808d4f6e1a.png)

So far I was able to get a memory dump from a web job process under test and it seems that some references to `System.Net.Socket` objects stay retained in memory longer than needed. I've noticed references to quite many `HttpResponseMessage`, `Socket`, `System.Runtime.CompilerServices.AsyncTaskMethodBuilder+AsyncStateMachineBox<Microsoft.Azure.Devices.Device, Microsoft.Azure.Devices.HttpClientHelper+<GetAsync>d__10<Microsoft.Azure.Devices.Device>>` objects.

![2020-04-15_14-41-35](https://user-images.githubusercontent.com/1292603/79333473-42d61580-7f27-11ea-8f6a-79af5b8be372.png)

I'm not an expert in the memory dump analysis, so I would appreciate any help there and can send the dump to someone from Microsoft privately via email.

However, I tried the following. We have a helper method to invoke direct methods. Here's simplified version of it:

```csharp
private async Task<TResult> InvokeDirectMethodInternalAsync<TResult>(
    string deviceId,
    string methodName,
    IDirectMethodParameter parameter)
{
    var method = new CloudToDeviceMethod(methodName);
    if (parameter != null)
    {
        method.SetPayloadJson(JsonConvert.SerializeObject(parameter, _messageSerializerSettings));
    }
    try
    {
        var iotHubResult = await _serviceClient.InvokeDeviceMethodAsync(deviceId.ToLower(), method);
        var result = ParseResult<TResult>(deviceId, methodName, iotHubResult);
        return result;
    }
    catch (DeviceNotFoundException ex)
    {
        // We can't really use ex.Code here due to the SDK issue to distinguish between:
        // - DeviceNotRegistered
        // - DeviceNotConnected
        // https://github.com/Azure/azure-iot-sdk-csharp/issues/629
        // Parsing error message to extract the code is quite ugly

        var device = _registryManager.GetDeviceAsync(deviceId.ToLower());
        if (device == null)
        {
            throw new CustomInvalidOperationException(
                $"Failed to call '{methodName}' direct method on device '{deviceId}' because it is not registered.",
                ex,
                CustomInvalidOperationType.IoTDeviceNotFound);
        }
        throw new CustomInvalidOperationException(
            $"Failed to call '{methodName}' direct method on device '{deviceId}' because it is not connected.",
            ex,
            CustomInvalidOperationType.IoTDeviceNotConnected);
    }
}
```
In our test, all devices were offline, so every time there is an attempt to invoke the direct method, we also call `GetDeviceAsync` to find out if device was disconnected or not registered at all. I've changed the code to parse the exception message instead. 

```csharp
catch (DeviceNotFoundException ex)
{
    // We can't really use ex.Code here due to the SDK issue to distinguish between:
    // - DeviceNotRegistered
    // - DeviceNotConnected
    // https://github.com/Azure/azure-iot-sdk-csharp/issues/629

    // Parsing error message to extract the code is quite ugly but it avoids additional requests to IoT Hub
    // 404001 - means device is not registered or disabled
    // See https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-404001-devicenotfound
    if (ex.Message.Contains("404001"))
    {
        throw new CustomInvalidOperationException(
            $"Failed to call '{methodName}' direct method on device '{deviceId}' because it is not registered.",
            ex,
            CustomInvalidOperationType.IoTDeviceNotFound);
    }
    // Assume device is not connected in all other cases
    throw new CustomInvalidOperationException(
        $"Failed to call '{methodName}' direct method on device '{deviceId}' because it is not connected.",
        ex,
        CustomInvalidOperationType.IoTDeviceNotConnected);
}
```

It reduced the number of established connections. Under the same load, a maximum of ~400 connections was utilized. **So the removal of `GetDeviceAsync()` reduced the number of connections from 1.5 to 0.4K**

![2020-04-15_14-58-31](https://user-images.githubusercontent.com/1292603/79334768-95183600-7f29-11ea-967b-5d577e858fec.png)

Unfortunately, I can't reproduce the issue reliably in isolation (outside of our application code). I also created a support request with the Azure support team. But I would appreciate the following:

- It would be great to understand if there is indeed an SDK issue or such high usage of TCP connections is normal. I can provide additional data privately upon request.
- In my opinion, issue #629 should be reopened. It's a good practice for the client library to expose all error codes returned by the service. In our case, the lack of proper error code leads to the usage of additional API calls which is also not very nice for performance reasons.

**Comment by HiroyukiSakoh** [comment]
It might be helpful.

MaxConnectionsPerServer

https://github.com/dotnet/runtime/issues/1844
https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core

**Comment by vinagesh** [comment]
I have few question on the usage of RegistryManager in your code
1) Do you create multiple instances of the RegistryManager?
2) Do you dispose the RegistryManager? (RegistryManageris IDisposable)

**Comment by smolyakoff** [comment]
@vinagesh We use a single instance of `RegistryManager` and never dispose it (or it gets disposed with a DI container on application stop)

**Comment by vinagesh** [comment]
Which version of the SDK are you using?

**Comment by vinagesh** [comment]
I see that we you have upgraded to the latest SDK version where there were some fixes to reuse HttpClients. But looks like you are still facing an issue with high outbound connections. Am I right?

**Comment by smolyakoff** [comment]
@vinagesh Yes, we did upgrade to the latest SDK version. It helped, but not to the degree we were satisfied with. 

1. With SDK v1.20.0 the outbound connection usage was **very high** (many `SocketException` in logs). 
2. With SDK v1.20.1 and `RegistryManager.GetDeviceAsync` call the outbound connection usage was still **high** (less `SocketException` in logs).
3. With SDK v1.20.1 and without `RegistryManager.GetDeviceAsync` call the outbound connection usage seemed **normal** (no `SocketException` in logs for the same load as before). We can't really say about which usage is normal though as we don't have a baseline to compare with. 

Here is how cases compare on Azure monitoring charts. 

# Case 1 vs Case 2
The difference is in the number of connections in the "Time Wait" state. Please note that the total count of established TCP connections is still high with SDK v1.20.1.
![different-sdk-versions-public](https://user-images.githubusercontent.com/1292603/80567992-d5ce7f80-89fe-11ea-8f18-04235d083771.png)

# Case 2 vs Case 3
The difference now is in the total number of established connections. It was reduced greatly after the removal of the `GetDeviceAsync` call.
![get-device-async-comparison](https://user-images.githubusercontent.com/1292603/80568820-65286280-8a00-11ea-9ccf-6d2da528f85a.png)

**Comment by vinagesh** [comment]
And just re-confirming that the target framework you are using is netcoreapp2.2?

**Comment by smolyakoff** [comment]
@vinagesh Yes, the target framework is `netcoreapp2.2`

**Comment by vinagesh** [comment]
When you create the Registry manager, do you set your own HttpTransportSettings? If yes, what are those settings?

**Comment by smolyakoff** [comment]
No, we just use the defaults and provide a connection string only.

**Comment by vinagesh** [comment]
When I try to do this locally and capture the network traffic, all requests seem to use the same Http connection. So wanted to know how you are capturing the data? Where are you observing the SocketException? Is it an app deployed on webapp?

**Comment by smolyakoff** [comment]
> how you are capturing the data?

The charts come from Azure Monitor (TCP Connections metric for an app service plan) and a troubleshooting page in Azure App Service (when you click TCP connections, it will show specifically outbound connections with IP addresses). The exceptions are logged with Serilog into an Application Insights sink. 

> Where are you observing the SocketException?

They are logged to Application Insights.

> Is it an app deployed on webapp?

It is a web app and a worker service both running under a single app service plan. So, it's 2 processes. The web process handles HTTP requests, worker process handles Service Bus messages. The memory dump screenshot from my first message is taken from a worker process using Kudu (Azure App Service) troubleshooting tools. `RegistryManager.GetDeviceAsync` call was used in a worker process only. 

> When I try to do this locally and capture the network traffic, all requests seem to use the same Http connection.

I was unable to reproduce this in isolation just by calling `GetDeviceAsync` many times from different TPL tasks in the console app. I mentioned this in the first message. So it might be related to .NET runtime version or deployment environment. I can just tell that the removal of this call helped greatly, but I'm not sure why.

**Comment by vinagesh** [comment]
Thanks for the information. We are trying to get to the bottom of this. But I don't have any updates yet.

**Comment by vinagesh** [comment]
If I may ask, what tier app service do you use?

**Comment by smolyakoff** [comment]
@vinagesh It's P1V2

**Comment by vinagesh** [comment]
Do you not see any Socket Exceptions in your web service? If you are running two services under the same plan, it would be sharing the network resources. One can inhibit the other. Do you know how many requests you usually process in your web service? Is this GetDevices() API being called in the webjob?

**Comment by vinagesh** [comment]
I am not sure if this is feasible, but if you can try to run only one service on an app service plan, you could test to see if you still see these exceptions. You can also set auto-scaling based on number of requests being processed so that you get more instances.

**Comment by vinagesh** [comment]
I will close this issue as it does not seem to be an issue with the SDK code. This is more likely a infrastructure issue. If you could run experiments by running this separately and still find issues, please open a new issues and we can help.

**Comment by az-iot-builder-01** [comment]
@HiroyukiSakoh, @smolyakoff, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by smolyakoff** [comment]
@vinagesh 
> Do you not see any Socket Exceptions in your web service? If you are running two services under the same plan, it would be sharing the network resources. One can inhibit the other.

Yes, they are running under the same plan, and therefore the `SocketException` will happen in both processes in case there is a shortage of outbound TCP connections. 

> Do you know how many requests you usually process in your web service?

I'm not sure how to answer that and if the answer is helpful. We don't have much statistics data gathered as we aren't running in production yet. But we do have load testing results (with max. RPS achieved) which I can share privately. 

> I am not sure if this is feasible, but if you can try to run only one service on an app service plan, you could test to see if you still see these exceptions. You can also set auto-scaling based on a number of requests being processed so that you get more instances.

Yes, we can split them, but it'll also have an infrastructure cost impact 😄 So it's not like finding the root cause but fixing the consequences.

> I will close this issue as it does not seem to be an issue with the SDK code. This is more likely a infrastructure issue. If you could run experiments by running this separately and still find issues, please open a new issues and we can help.

It's fine as the workaround (remove `GetDeviceAsync` usage) fixes this issue (or makes the situation better). However, I don't really understand why is that an infrastructure issue if the application code change affects the number of used connections so much. There were no infrastructure changes between test runs (only different DLLs deployed in the same environment). 

Anyway, thanks for your help and we'll open new issues in case we face something similar later.
