### ISSUE TITLE
The PrimaryKey of SymmetricKeyAttestation from QueryResult is null.

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/azure-iot-sdk-csharp#1336]
We need to query PrimaryKey from DPS EnrollmentGroup.
I have tryied using 
`provisioningServiceClient.CreateEnrollmentGroupQuery("SELECT * FROM enrollmentGroups");`
But the PrimaryKey in result SymmetricKeyAttestation class is null.

**Comment by Dolphinsimon** [comment]
#1183

**Comment by az-iot-builder-01** [comment]
@Dolphinsimon, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
