### ISSUE TITLE
What's the best way to get IoT Hub name from a connection string?

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-iot-sdk-csharp#1337]
What's the best way to get IoT Hub name from a connection string?

There is a `IotHubConnectionString` class but it's internal and as far as I know `RegistryManager` doesn't provide the information as well.

Would be good to have this so that it can be used in telemetry for dependency tracking, etc.

**Comment by drwill-ms** [comment]
Hi @tomkerhove. Thanks for your question.

I'm not sure what the "best" way is, but there is a utility called [IotHubConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.iothubconnectionstringbuilder.create?view=azure-dotnet) in the service SDK you might find fits your needs. You'd want to use the `Create(string iotHubConnectionString)` static method on it, pass your connection string, and then get your desired value from the `HostName` property.

Regards,
David

**Comment by tomkerkhove** [comment]
Oh boy that was a stupid question 🙈

Thanks for the help!

**Comment by az-iot-builder-01** [comment]
@tomkerkhove, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by drwill-ms** [comment]
Not at all. It can be hard to navigate a library.

All the best,
David
