### ISSUE TITLE
How to get List of linked IoT hubs in a device provisioning service

### ISSUE THREAD

**Issue by Shyam268** [Azure/azure-iot-sdk-csharp#1357]
Two IoT hubs are linked to device provisioning service. how do we get the IoT hub details using device provisioning service connection string?

**Comment by abhipsaMisra** [comment]
This feature is not available through the client SDK; however, you can use the following [Azure IoT CLI](https://docs.microsoft.com/en-us/cli/azure/iot/dps/linked-hub?view=azure-cli-latest#az-iot-dps-linked-hub-list) command to view the list of IoT Hubs linked to your DPS instance:

`az iot dps linked-hub list --dps-name MyDps --resource-group MyResourceGroup`

**Comment by abhipsaMisra** [comment]
@Shyam268 Let us know if you have any more questions on this.

**Comment by abhipsaMisra** [comment]
The list of iot hubs linked to a DPS instance can be retrieved using the Azure IoR CLI command listed above.
The CLI installation steps are detailed in the document linked.

**Comment by az-iot-builder-01** [comment]
@Shyam268, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Shyam268** [comment]
We cannot use Azure CLI . Is there any other options(example: rest api..) to get Linked IoT hubs

**Comment by abhipsaMisra** [comment]
Updating here as well:
In that case, your best option is to use Iot Dps Resource. This will give you the metadata of your DPS instance, excluding the SAS keys:
https://docs.microsoft.com/en-us/rest/api/iot-dps/iotdpsresource/get

Under IotDpsPropertiesDescription there's a property named 'iotHubs' which lists the IoT Hubs linked to the DPS.
