### ISSUE TITLE
How to get Linked IoT hubs using Dps Connection string or resource group?

### ISSUE THREAD

**Issue by Shyam268** [Azure/azure-iot-sdk-csharp#1364]
Continuation to https://github.com/Azure/azure-iot-sdk-csharp/issues/1357? 
We cannot Use Azure CLI. Is any other way to get linked IoT hubs either Resource group or Rest Api ...?

AB#7281132

**Comment by abhipsaMisra** [comment]
Ah, I see. In that case, your best option is to use Iot Dps Resource. This will give you the metadata of your DPS instance, excluding the SAS keys:
https://docs.microsoft.com/en-us/rest/api/iot-dps/iotdpsresource/get#iotdpspropertiesdescription

Under IotDpsPropertiesDescription there's a property named 'iotHubs' which lists the IoT Hubs linked to the DPS.

Let me know if this option works for you.

**Comment by abhipsaMisra** [comment]
Do you still have any questions around this @Shyam268 ?

**Comment by az-iot-builder-01** [comment]
@Shyam268, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
