### ISSUE TITLE
ReceiveMessageAsync behavior with cancellation token unexpected

### ISSUE THREAD

**Issue by r1v3n** [Azure/azure-iot-sdk-csharp#1369]
https://github.com/Azure/azure-iot-sdk-csharp/blob/5989019076a643df51908e823d258b8bd8e94a29/iothub/device/src/Transport/Amqp/AmqpTransportHandler.cs#L205

I am developing a windows service with the dotnet core BackgroundService. I got the issue where stopping the service would let the process still running. After some investigation, I finally took a look at the source (thx to open source :) ) and realized that the cancellation token is only check once at first and then will block for a minute (by default). Meaning that if no message are sent to the device, we are stuck for a minute even if a cancellation occurs during that window. From a user point of view, I would have expected that the receive async would return null if default timeout is reached or OperationCancelledException thrown, regardless if the cancellation occurs before or during the receive operation. My workaround at the moment is to simply do not use the cancellation token and set a timeout of like one second, but thats not ideal. Any comments on the design?

**Comment by abhipsaMisra** [comment]
You are correct, ideally we would expect the cancellation token to be propagated directly to the transport library call, which could then regulate the cancellation during the receive operation. Our limitation here, however, is that the amp library being used underneath does not accept cancellation tokens, but takes in a `TimeSpan` instead. It is because of this that we check for cancellation before the receive operation has been triggered on the protocol library, and then pass it the `DefaultReceiveTimeout`.

**Comment by r1v3n** [comment]
Thank you for your answer. Indeed, if your transport library doesnt support cancellation then there's not much you can do. If I switch to MQTT, it behaves as expected, seeing the **CancelOperationException** in the **InnerException**. Then I can do exception handling by filtering with **GetBaseException()** for the **CancelOperationException**. Thank you.

**Comment by abhipsaMisra** [comment]
Closing this, since this is a design limitation brought in by our amqp library dependency.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @r1v3n, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
