### ISSUE TITLE
Windows 10 IoT + MQTT Not able to re-establish connection

### ISSUE THREAD

**Issue by zyofeng** [Azure/azure-iot-sdk-csharp#137]
Hi all

I am using Windows 10 IoT on a raspberry pi 3 with MQTT and direct methods.

I couldn't find any documentation for C# on how to handle disconnection so I came up with something like below.

The idea is basically to allow continuous re-connection attempts after Internet connection is disrupted. I tried different retrypolicy before going down this path and doesn't look like the iot sdk has any built in re-connection mechanism for my usage, or for some reason it doesn't work.

Problem is the SetMethodDefaultHandlerAsync method hangs and re-connection never took place.

You can reproduce this issue by physically disconnecting the device (Ethernet cable) from the internet after the initial connection then reconnect the ethernet cable after a couple of minutes.

Is there a bug in the MQTT transport code?

        public Program()
        {
            deviceClient = DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);
            deviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChanged);
            deviceClient.SetMethodDefaultHandlerAsync((request, context) => CallMethod(request), null).Wait();
        }

        private void ConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
        {
            if (status == ConnectionStatus.Disabled || status == ConnectionStatus.Disconnected)
            {
                while (true)
                {
                    try
                    {
                        deviceClient =
                            DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);
                        deviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChanged);
                        deviceClient.SetMethodDefaultHandlerAsync((request, context) => CallMethod(request), null)
                            .Wait();
                        return;
                    }
                    catch (Exception ex)
                    {
                        
                    }
                }
            }
        }

**Comment by jasmineymlo** [comment]
Looks like a bug to me.  I will take a look and get back to you when I have more details

**Comment by jasmineymlo** [comment]
fd7fae91193870da1ecc5909b6890179b984d47f should fix it.  Please test it out and let us know if you have issues.
