### ISSUE TITLE
Multi module ModuleClient connection issue

### ISSUE THREAD

**Issue by dme-development** [Azure/azure-iot-sdk-csharp#1371]
- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04.3 LTS arm64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** NVIDIA Jetson Nano
- **SDK version used:** 1.29.0-preview-004

## Description of the issue:
We have 2 different iot edge modules. Both modules create a ModuleClient with the exact same code. See below.
However only one module can make a connection to the Iot Hub. In the Azure Hub this is shown like this:
![image](https://user-images.githubusercontent.com/38321985/82303066-bbaf0e00-99ba-11ea-89a6-1e72e524a999.png)

In the logs we can see an error at the moment the module client is being used. See error below.

What am I missing here? Is the Mqtt connection limited to one per device? How can I use multiple moduleclients per device? In my opinion this should just work.

## Code sample exhibiting the issue:
```
            MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
            ITransportSettings[] settings = { mqttSetting };

            // Open a connection to the Edge runtime
            var ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
```

## Console log of the issue:

> Unhandled exception. System.AggregateException: One or more errors occurred. (MQTT channel open failed.)
>  ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel open failed.
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass84_0.<<CreateChannelFactory>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
>    at IoT.HealthCheck.Program.Init() in /app/healthcheck/Program.cs:line 106
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at IoT.HealthCheck.Program.Main(String[] args) in /app/healthcheck/Program.cs:line 51

AB#7257045

**Comment by dme-development** [comment]
It seems that azureiotedge-hub module was throwing errors (write permission) on persistent storage I tried setting up. After fixing this issue in azureiotedge-hub, my own two modules can both create a connection via the ModuleClient, so problem resolved.

**Comment by az-iot-builder-01** [comment]
@dme-development, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
