### ISSUE TITLE
DeviceClient SetConnectionStatusChangesHandler Not reconnect when Hub fails over

### ISSUE THREAD

**Issue by hhaaii** [Azure/azure-iot-sdk-csharp#1376]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp3.1
- **Device:** <DEVICETYPE> laptop
- **SDK version used:** <VERSION> 1.25.0

## Description of the issue:

The DeviceClient SetConnectionStatusChangesHandler does not re-establish the connection when IoT Hub fails over. I was using the MethodSample (https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/MethodSample) with a couple small tweaks to use MQTT protocol and wait indefinitely instead of 30 seconds at end of RunSampleAsync(). This sample uses the default retry policy which is ExponentialBackoff(int.MaxValue, TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(100));

First, ran the sample and ConnectionStatusChangesHandler reported the Connected status.
> Connection Status Changed to Connected
> Connection Status Changed Reason is Connection_Ok

Then conducted the Hub failover through the portal. During the failover processing, ConnectionStatusChangesHandler first reported the "Disconnected_Retrying" status and then the "Disconnected" status.

> Connection Status Changed to Disconnected_Retrying
> Connection Status Changed Reason is Communication_Error
> 
> Connection Status Changed to Disconnected
> Connection Status Changed Reason is Communication_Error

When the failover completed successfully, I was expecting DeviceClient will automatically re-establish the connection to the failed-over Hub. However, SetConnectionStatusChangesHandler never fired and above "Disconnected" was the last reported status. In another words, DeviceClient never recovered from the Disconnect status caused by breaking-away from the original Hub. Is DeviceClient connection designed to survive failover or I have to add custom handling code in ConnectionStatusChangesHandler to try to reconnect on observation of Disconnected status?

## Code sample exhibiting the issue:

https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/MethodSample/MethodSample.cs

## Console log of the issue:

Connection Status Changed to Connected
Connection Status Changed Reason is Connection_Ok

Use the IoT Hub Azure Portal to call methods GetDeviceName or WriteToConsole within this time.
         *** GetDeviceName was called.
         *** GetDeviceName was called.

Connection Status Changed to Disconnected_Retrying
Connection Status Changed Reason is Communication_Error

Connection Status Changed to Disconnected
Connection Status Changed Reason is Communication_Error

AB#7337228

**Comment by vinagesh** [comment]
This issue has been fixed now. I have tested it on my end and the device client reconnects after a manual failover. Please let me know if you are still blocked.

**Comment by az-iot-builder-01** [comment]
@hhaaii, @azabbasi, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
