### ISSUE TITLE
Remove PCL support

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-iot-sdk-csharp#138]
As of v1.3.0, the assemblies contained in the `Microsoft.Azure.Devices.Client` nupkg is:

```
- net45
  |- Microsoft.Azure.Devices.Client.dll
- netstandard1.3
  |- Microsoft.Azure.Devices.Client.dll
- uap10.0
  |- Microsoft.Azure.Devices.Client.UWP.dll
- portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+UAP10
  |- Microsoft.Azure.Devices.Client.PCL.dll
```

**Repro**

Because these assemblies are named differently across different profiles, it breaks runtime resolution in a few cases. The most common would be:

1. Create a .NET Standard 1.3 library that references `Microsoft.Azure.Devices.Client`
2. Reference in a .NET Framework 4.5 application **[Works]**
3. Reference in a UWP application **[Does not work]**

This is because the API name is a combination of the assembly name and the fully qualified API (namespace+class).

**What needs to be done?**

The assembly names should be reconciled to all be `Microsof.Azure.Devices.Client.dll` so that runtime resolution works as expected, especially in circumstances where a .NET Standard library references the devices library and is then referenced by a UWP or Xamarin project.

**Comment by arturl** [comment]
I removed the UWP suffix (https://github.com/Azure/azure-iot-sdk-csharp/commit/f5c3c0b1d08e0487d74c48a7404a40040c3f2900) 
PCL binary/nuget are not affected

**Comment by twsouthwick** [comment]
The PCL assembly will have the same issue - that suffix needs to be removed as well. This is a common pattern known as bait-and-switch for PCLs; all assemblies need to have the same name as that is part of the identity of an API. Is there a reason you have the suffix?

**Comment by arturl** [comment]
Someone from Azure team should comment on the roadmap for PCL support. .Net standard support should obsolete PCL. It does not require bait and switch.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tameraw** [comment]
@arturl - Agree. This is no longer supported. NetStandard 1.3 is our target.

**Comment by CIPop** [comment]
The plan is to remove the PCL build for the next release.
Support will be maintained for [.Net runtimes supporting NetStandard1.3](https://github.com/dotnet/standard/blob/master/docs/versions.md) as well as the non-NetStandard compliant .Net Framework 4.5 build.

**Comment by CIPop** [comment]
I have the work staged in https://github.com/CIPop/azure-iot-sdk-csharp/tree/pcl. Additional changes need to be made according to PR comments from here: #199 . 

I'm pausing work on this until we figure out why we're hitting #197. A workaround (using PCL?) seems to allow Android usage for now.
