### ISSUE TITLE
Limited Throughput for single client

### ISSUE THREAD

**Issue by wmattlong** [Azure/azure-iot-sdk-csharp#139]
Seeing low throughput for single IoT Client (Client SDK + IoTHub) using C# 
Results prompted additional testing and scenarios to increase throughput.
The results indicate limited throughput for a single client scenario regardless of # IOT Hub units.
[ClientSDK_Tests_07_07_2017.xlsx](https://github.com/Azure/azure-iot-sdk-csharp/files/1154370/ClientSDK_Tests_07_07_2017.xlsx)

**Comment by tameraw** [comment]
@wmattlong - We need to run benchmarks against the SDK to identify where issues are coming.

**Comment by CIPop** [comment]
@wmattlong please reopen if this is still an issue with the latest SDK.
If yes, do you see the same throughput issues with any other SDK (C/Java/Node)?
