### ISSUE TITLE
Usage of deprecated NuGet package: WindowsAzure.Storage 

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-iot-sdk-csharp#1391]
Greetings,

The NuGet package Microsoft.Azure.Devices.Client 1.25.0 uses the deprecated NuGet package [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/):

NOTE: As of version 9.4.0, this library has been split into multiple parts and replaced:  See Microsoft.Azure.Storage.Blob, Microsoft.Azure.Storage.File, Microsoft.Azure.Storage.Queue, and Microsoft.Azure.Storage.Common.
     For table support, see Microsoft.Azure.CosmosDB.Table.
     This client library enables working with the Microsoft Azure storage services which include the blob and file service for storing binary and text data, the table service for storing structured non-relational data, and the queue service for storing messages that may be accessed by a client.
     For this release see notes - https://github.com/Azure/azure-storage-net/blob/master/README.md and https://github.com/Azure/azure-storage-net/blob/master/changelog.txt
     Microsoft Azure Storage team's blog - https://blogs.msdn.com/b/windowsazurestorage/

This package has been deprecated.
Suggested Alternatives
Microsoft.Azure.Storage.Blob 9.4.0

Additional Details
Thank you for the interest in this package. Going forward this package has been split into the following packages.

Microsoft.Azure.Storage.Blob/9.4.0
Microsoft.Azure.Storage.File/9.4.0
Microsoft.Azure.Storage.Queue/9.4.0

If you are looking for the latest packages to interact with Azure Storage, please use the following libraries:
Azure.Storage.Blobs
Azure.Storage.Queues
Azure.Storage.Blobs.Batch
Azure.Storage.Files.Shares

**Comment by abhipsaMisra** [comment]
Thanks for reporting this @StannieV .
We have recently been made aware of the usage of this deprecated package in our library. We are working to get this updated, so that we can also benefit from new features added to azure storage (proxy support, etc).

**Comment by StannieV** [comment]
Great, I'll hope the new version will be available soon. Keep up the good work!

**Comment by azabbasi** [comment]
@StannieV Can you tell us more about this issue? Unfortunately we have to keep supporting .NET451 and the Azure.Storage.* packages do not support .NET451. The alternative is for us to maintain multiple code paths and keep referencing WindowsAzure.Storage package in our solution for net451 and that is something we are trying to avoid.
So even if we start referencing the new azure storage nuget package, we still need to reference the deprecated package for our net451 users.
Let us know why this is old package is an issue for you and we will investigate other possibilities for you.

Thanks
Azad

**Comment by StannieV** [comment]
@azabbasi There is no direct issue. The nuget package manager in Visual Studio actively indicates that my solution is using a deprecated NuGet package. After I traced it back to this library, I wanted to inform you about this. But apparently you are already aware of this. Also, I wasn't aware of the .NET451 limitations.

**Comment by timtay-microsoft** [comment]
As of now, the APIs that use that deprecated Azure Storage version are now deprecated, too. I'm not sure that we need to do anything here because of that.

**Comment by StannieV** [comment]
@timtay-microsoft Do you mean that the nuget package 'Microsoft.Azure.Devices.Client' is now deprecated? Meaning no more developments in this library? At least nog the .NET451 version?

**Comment by abhipsaMisra** [comment]
@StannieV , no, Microsoft.Azure.Devices.Client is not deprecated, the file upload APIs defined in the package (the ones that use the deprecated Storage SDK API internally) are being deprecated.
What this means is, instead of having a single API for file upload, doing the following:
1. Retrieve the sas URI from IoT Hub
2. Upload the file stream using storage SDK
3. Update the file upload status to IoT hub

we have now broken these to 3 separate steps. The Microsoft.Azure.Devices.Client SDK has new APIs for step 1 and step 3, while for step 2 the user is free to use any version of the Storage SDK to perform the actual upload operation.
This means that your application doesn't need to depend on the deprecated Storage SDK version to perform the file upload.

**Comment by abhipsaMisra** [comment]
Closing this issue, since Microsoft.Azure.Devices.Client v1.27.0 now exposes APIs that give you greater control over which Storage package to use, for file upload operations.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @StannieV, @azabbasi, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
