### ISSUE TITLE
UploadToBlobAsync does not modify Stream.Position for progress tracking.

### ISSUE THREAD

**Issue by OsaPL** [Azure/azure-iot-sdk-csharp#1399]
It makes progress report basically imposible.

(Here I'm using Win10 x64 machine, would have to test it on a Linux also)
Lets do a file upload. 
```c#
using (var data = new FileStream(path, FileMode.Open))
{
     var watch = System.Diagnostics.Stopwatch.StartNew();
     ProgressReport(blobPath, data, watch, cancellationTokenSource.Token);
     await deviceClient.UploadToBlobAsync(blobPath, data, cancellationTokenSource.Token);
     watch.Stop();
     _logger.LogInformation("Time to upload file: {0}ms", watch.ElapsedMilliseconds);
}
```

Then in a seperate Task:
```c#
private async Task ProgressReport(string file,Stream data, System.Diagnostics.Stopwatch watch,CancellationToken token)
{
    var length = data.Length;
    while (!token.IsCancellationRequested)
    {
        await Task.Delay(5000);
        _logger.LogInformation("Progress: {0} {1}% {2}s", file, data.Position/data.Length, watch.Elapsed.TotalSeconds);
    }
}
```

You will get something like this:
```
[13:58:31 Information ]
 Progress: Test.mp3 0% 35.0627038s
[13:58:36 Information ]
 Progress: Test.mp3 0% 40.1025024s
[13:58:41 Information ]
 Progress: Test.mp3 0% 45.116194s
[13:58:46 Information ]
 Progress: Test.mp3 0% 50.129142099999996s
[13:58:51 Information ]
 Progress: Test.mp3 0% 55.1335366s
[13:58:56 Information ]
 Progress: Test.mp3 0% 60.1507109s
[13:59:01 Information ]
 Progress: Test.mp3 0% 65.1606468s
[13:59:06 Information ]
 Time to upload file: 69286ms
```

Would love to get a way to actually track progress, either by using ``Stream.Position`` or something exposed by the ``DeviceClient``.

**Comment by timtay-microsoft** [comment]
Just a heads up, we are planning on deprecating that uplaod to blob API in favor of what I detailed [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/1037#issuecomment-641521842).

It's to solve a different issue, but this would allow you to use the Azure Storage SDK directly, and they may have a better way for you to track each upload

**Comment by OsaPL** [comment]
@timtay-microsoft 
Azure Blob Storage SDK has a way to implement `IProgress<T>`, so that would work for progress.

My question is, will this new way allow us to still use IoT based security?
In our current architecture, we don't want to keep any real authorization information on our IoT Device (besides the IoT key), also the container path may change sometimes, thats why we were using the Upload File function of the IotHub, that satisfies both of these requirements.

**Comment by timtay-microsoft** [comment]
Yes, with this new approach, you will still only need your iot device's security saved on the device. The file upload feature on IoT Hub allows you to create a blob on azure storage by using your device's IoT credentials. Fundamentally, nothing will change about this flow. We're just taking a 3 step API and splitting into 3 different APIs (where one is Azure Storage's upload API).

**Comment by timtay-microsoft** [comment]
Just for posterity here, even though we consider this fix checked in, we aren't fixing the behavior of the now deprecated upload to blob APIs. We are just deferring the responsibility here to the user to use the Azure Storage SDK directly since that SDK handles this correctly

**Comment by abhipsaMisra** [comment]
Microsoft.Azure.Devices.Client v1.27.0 has now been released. This update introduces additional APIs that allow you to use any version of the storage SDK to carry out the actual upload operation.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @OsaPL, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
