### ISSUE TITLE
SetMethodHandler does not handle errors correctly

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdk-csharp#14]
`SetMethodHandler` is a void method but calls a method returning Task internally, without awaiting the result:

```
// codes_SRS_DEVICECLIENT_10_005: [ The SetMethodHandler shall EnableMethodsAsync when called for the first time. ]
ApplyTimeout(operationTimeoutCancellationToken => this.InnerHandler.EnableMethodsAsync(operationTimeoutCancellationToken));
```

If `EnableMethodsAsync` fails, the errors are ignored and DeviceCient object gets into an invalid state.

To simulate `EnableMethodsAsync` failure, you can create the DeviceClient object with AMQP protocol.

I can think of a few ways to solve it, if you want to discuss let me know.

**Comment by BertKleewein** [comment]
This is all you Haitham.  I've been fighting the async fight for the last few weeks, so I have a few ideas here too, though Artur's ideas might be better.

**Comment by jasmineymlo** [comment]
I am working on it.

**Comment by jasmineymlo** [comment]
Added SetMethodHandlerAsync() and should be in the next release.
