### ISSUE TITLE
ExportDevicesAsync does not export all device twin properties

### ISSUE THREAD

**Issue by mzrks** [Azure/azure-iot-sdk-csharp#1401]
Hello!
I tried to use RegistryManager.ExportDevicesAsyncmethod, but it doesn`t export all properties. 
Missed properties: 
    - connectionState
    - statusUpdateTime
    - lastActivityTime

I`m using SDK Microsoft.Azure.Devices 1.20.1.

Is it possible to export these properties or maybe there is some workaround for it?

**Comment by prmathur-microsoft** [comment]
Can you provide more details on what steps and parameters you used to export devices?

**Comment by abhipsaMisra** [comment]
This looks like a limitation from service, since the sample format of exported data doesn't contain these properties either: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt#export-devices

We'll reach out to the service team for some clarification on this.

**Comment by abhipsaMisra** [comment]
@mzrks This is by service design issue and is out of scope from the SDK side. Please follow https://github.com/Azure/azure-iot-sdk-csharp#need-support to create a support ticket to address this issue.

**Comment by az-iot-builder-01** [comment]
@mzrks, @prmathur-microsoft, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
