### ISSUE TITLE
update Transport type options in sample

### ISSUE THREAD

**Issue by elhorton** [Azure/azure-iot-sdk-csharp#1418]
Pointed out by customers working with the docs team-- could we update samples with the latest TransportType info?

For example, the [Message sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/MessageSample/Program.cs) should be updated to reflect what is listed in [API reference docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.transporttype?view=azure-dotnet#fields)

Wanted to be sure this feedback got across somehow. Let me know if another process is preferred for tracking this. Thank you!

**Comment by abhipsaMisra** [comment]
This issue would be better tracked within the samples repo directly: https://github.com/Azure-Samples/azure-iot-samples-csharp/issues; I'll transfer it there.

**Comment by abhipsaMisra** [comment]
@prmathur-microsoft Looks like I do not have permissions to transfer issues to our samples repo, can we transfer this issue to https://github.com/Azure-Samples/azure-iot-samples-csharp/issues?

**Comment by drwill-ms** [comment]
Fixed with https://github.com/Azure-Samples/azure-iot-samples-csharp/pull/129

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
