### ISSUE TITLE
DeviceAuthenticationWithX509Certificate error when targetting UWP platform

### ISSUE THREAD

**Issue by raja4014** [Azure/azure-iot-sdk-csharp#142]
Throwing error "The name 'DeviceAuthenticationWithX509Certificate' does not exist in the current context" even after adding the package Microsoft.Azure>devices.Client 1.3.1 version when targeting UWP platform.
But its working fine when ran .net framework platform

**Comment by enesuysal** [comment]
As I see in the following link it is not supported yet for UWP platform

https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/AuthenticationMethodFactory.cs#L30

**Comment by raja4014** [comment]
@enesuysal:Yes.... But is there any specific reason for keeping that condition. So, how to go ahead with certificate authentication in UWP

**Comment by jasmineymlo** [comment]
@raja4014 System.Security.Cryptography was not included in the .NET for UWP.  But now it should with the latest.  We will look into it and implement accordingly.  Thanks for bringing this up.

**Comment by raja4014** [comment]
@jasmineymlo Can you suggest me any alternative meanwhile? I m working on an azure IOT hub project and my client wants to have X509 certificate authentication for the device to communicate with Azure IOT

**Comment by CIPop** [comment]
@raja4014 I didn't try this yet myself but, as a workaround, please try creating a .Net Standard 1.3 or 2.0 library and reference our latest SDK (1.6.2) within it. In your UWP application reference this library instead.

The right fix is for us to also ship a .Net Standard 2.0 DLL which has added lot more .Net APIs that are now supported in the 16299 UWP SDK.
