### ISSUE TITLE
[feature request] HTTPS support X.509 CA Certificate authentication also

### ISSUE THREAD

**Issue by sindhuvahinis** [Azure/azure-iot-sdk-csharp#1422]
Could HTTPS also be supported for X.509 CA authentication of device to IOT Hub?

**Comment by abhipsaMisra** [comment]
@sindhuvahinis Could you elaborate a bit on what you mean by this?
Do you mean to ask if a device client instance can authenticate via HTTPS protocol? If yes, then the answer is yes, the device client can indeed authenticate itself, and communicate with IoT Hub, over HTTPS: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/TransportType.cs#L20

```C#
var deviceClient = DeviceClient.CreateFromConnectionString(s_deviceConnectionString, TransportType.Http1)
```

Please let me know if that answers your question, or if you have any other question.

**Comment by sindhuvahinis** [comment]
@abhipsaMisra Right now, IOT SDK states this "X509-CA authentication over websocket and HTTPS are not supported." 

Does this X509-CA authentication over HTTPS feature available in your roadmap?

**Comment by abhipsaMisra** [comment]
@sindhuvahinis Ah, I see, thanks for the clarification. 
We have this in our backlog, and will need to investigate to access the feasibility and priority of this feature. Is this something that your product is relying upon? Is there a particular scenario due to which you would prefer to use http over, say mqtt?

**Comment by sindhuvahinis** [comment]
@abhipsaMisra Thank you for your response. Our main use case is the protocol should provide end-to-end message encryption of data. HTTPS is preferred mostly because of the familiarity of the protocol. 

Does azure suggest any secure protocol that goes along with X.509 CA cert auth? Any documentation for that?

**Comment by abhipsaMisra** [comment]
@sindhuvahinis All communication with IoT Hub is encrypted by TLS: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-tls-support

At the moment, we support CA based authentication over Mqtt and Amqp (over tcp); it is documented on our github repo here: https://github.com/Azure/azure-iot-sdk-csharp#iot-hub-device-sdk
You can find more details on IoT hub security here: https://docs.microsoft.com/en-us/azure/iot-fundamentals/iot-security-deployment

**Comment by abhipsaMisra** [comment]
@sindhuvahinis Do you still have any more questions around this?

**Comment by sindhuvahinis** [comment]
@abhipsaMisra No more question abhipsa. Thank you.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @sindhuvahinis, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
