### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-iot-sdk-csharp#143]
Hi,

We try to use Microsoft.Azure.Devices package v1.2.9 in an .NET core 1.1 console application.
We got the following exception at execution: 

System.Resources.MissingManifestResourceException:

`Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Devices.ApiResources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Devices" at compile time, or that all the satellite assemblies required are loadable and fully signed.'`

In 4.5.1 dll there is the Ressources folder but not in .net standard 1.3 dll.
Could it be linked with our issue?

**Comment by tameraw** [comment]
@Sbou  - Thanks for filing this issue. We'll investigate it.

**Comment by ryan-z-johnson** [comment]
@Sbou - What function are you trying to use when you get this error?

**Comment by Sbou** [comment]
We tried to use RegistryManager.GetDevice

Thanks

**Comment by ryan-z-johnson** [comment]
Thanks. Can you send me how you setup the RegistryManager object as well as the code surrounding your .GetDevice call? I was not able to replicate it but I could have set up my quick test differently then how you are using it.

**Comment by ryan-z-johnson** [comment]
@Sbou any update on this? Did the latest release fix your issue?

**Comment by EricVernie** [comment]
@Sbou I get the same error with a deviceId comporting a space. ex "Device 1". Resolved with "Device1".
Maybe this could help

**Comment by tameraw** [comment]
Please try with our latest release and reopen if still seeing issues. Thanks.

**Comment by marktsoper** [comment]
I am having this issue also. The strange thing is the same codes it works in one method in the same class but not the other.

**Comment by Sbou** [comment]
For me the issue was a space in the deviceid. Now it works. 
Thank you

**Comment by marktsoper** [comment]
@Sbou  - Your post help me figure out that it was deviceid related.  

I am using GUIDS and found that A works and B does not.

A: 27775286-3A2F-4A84-8DF2-4112C31FAC5E

B: 799EF0E6-178F-4DCC-A553-D2C5772A9404

Any ideas?

Thanks!

**Comment by CIPop** [comment]
@Sbou , @marktsoper If this is still an issue, please open a new issue with a repro using our latest SDK version (1.6.2).
