### ISSUE TITLE
[Bug Report] Cannot query devices with RegistryManager

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-iot-sdk-csharp#1434]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** desktop
- **SDK version used:** Microsoft.Azure.Devices v1.21.0

## Description of the issue
Console app quits when trying to query devices on IoT Hub.  When I debug this console application, execution stops on the first GetNextAsTwinAsync() call.  No exception is thrown, the console app just stops.

I can see and query the IoT Devices on the IoT Hub in the portal.

## Code sample exhibiting the issue

```
using System;
using Microsoft.Azure.Devices;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            GetDevices();
        }

        private static async void GetDevices()
        {
            try
            {
                var registryManager = RegistryManager.CreateFromConnectionString("HostName=<name>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=5eXgp...=");
                var query = registryManager.CreateQuery("SELECT * FROM devices", 100);
                while (query.HasMoreResults)
                {
                    var page = await query.GetNextAsTwinAsync();  // exits here
                    foreach (var twin in page)
                    {
                        // do work on twin object
                    }
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
}

```

Probably related - if I add a call to get an explicit device, after I get the RegistryManager, the console app stops as well:

`var device = await registryManager.GetDeviceAsync("moosetemp1");`

**Comment by RotateAt60MPH** [comment]
Resolved.  I was missing an async on the call to GetDevices.

**Comment by az-iot-builder-01** [comment]
@RotateAt60MPH, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
