### ISSUE TITLE
There's broken link in README.md

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-iot-sdk-csharp#144]
getting started guides: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/doc/get_started

**Comment by yzhong94** [comment]
@erich-wang  Thank you for letting us know!  We fixed the link on [readme](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/readme.md).  The correct link is [https://github.com/Azure/azure-iot-sdk-csharp/blob/master/readme.md](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-get-started)
