### ISSUE TITLE
Stopped Monitoring events. Exception of type 'Microsoft.ServiceBus.Messaging.MessagingException' was thrown.

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-iot-sdk-csharp#145]
When using Device Explorer, if I go to the "Data" tab, select a device and click "Monitor", the app hangs for a bit and then returns a MessagingException. Here's the full output:

> Receiving events...
> Stopped Monitoring events. Exception of type 'Microsoft.ServiceBus.Messaging.MessagingException' was thrown.

**Comment by tameraw** [comment]
@MisinformedDNA - Thanks for filing this. 
- Confirm that you are using a valid IoT Hub connection string.
- Has this ever worked on your machine?
- Can try to run the diagnostic tool.
https://github.com/Azure/iothub-diagnostics

**Comment by mani5219** [comment]
It might be  happening because of corporate proxy
