### ISSUE TITLE
C2D twin methods and properties don't work anymore against this client

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-csharp#146]
If I run the project DeviceClientMethodSample or the DeviceClientTwinSample as is (Master Branch), I cannot send direct methods or change desire properties form cloud to device.
ExceptionMessage "Not Registered"
Yet if I bring NuGet Package for Azure.Devices.Client 1.3.1 everything works as expected.

Do I need to clone a particular branch? I can help replicate if some investigation is needed.

**Comment by enesuysal** [comment]
Hi @ukluk 
I will test it locally today and let you know my feedback

**Comment by enesuysal** [comment]
@ukluk 
I have tested to run the project DeviceClientMethodSample and the DeviceClientTwinSample with the latest version of Master Branch. I do not get any ExceptionMessage as seen below
![image](https://user-images.githubusercontent.com/5776438/29031052-e47aa0da-7b84-11e7-9964-f63f57e11698.png)

Let me know how reproduce it?

**Comment by ukluk** [comment]
Thank you for testing, I get your results if I bring the NuGet Azure.Devices into the samples, but it fails with no error, the direct method if I use the project as a reference. It simply ignores all the incoming traffic.

I suspect that by loading the NuGet I have some broken references, although the compiler is not complaining.
I did not fork the repo so it is not easy to share my test bed, but if you want I can send you my code as a ZIP.

As far as more cycles, I am able to proceed with the NuGet, therefore I prefer not to invest more time into it.

Best regards
Uri

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by enesuysal** [comment]
@ukluk 

In that case, if possible, please send me your code as a ZIP.

**Comment by ukluk** [comment]
@enesuysal,

My fault, I tested again with the original code and it methods and properties work as expected.
I been spending a lot of time with this project, thanks for the good samples and documentation, and for your follow up trying to non existing bug.

Best regards,
Uri Kluk


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by enesuysal** [comment]
@ukluk 

Thanks alot for your reply. I am happy that you could resolve it :)
In that case, Could you please close this github issue?

**Comment by ukluk** [comment]
Closing the issue
