### ISSUE TITLE
Can't OpenAsync() success when DeviceID contain '#' and use MQTT

### ISSUE THREAD

**Issue by lairship** [Azure/azure-iot-sdk-csharp#149]
```
var authMethod = new DeviceAuthenticationWithRegistrySymmetricKey("D17#0001", AuthKey);
deviceClient = DeviceClient.Create(HostName, authMethod, TransportType.Mqtt);
            
Task.Run(async () =>
{
    await deviceClient.OpenAsync();
    Logger.LogInfo("Open success!");
});
```
Only first time, OpenAsync can success
The same code, run again, it's always failed.

**Comment by tameraw** [comment]
@lairship - Thanks for filing this issue. We'll investigate it.

**Comment by jasmineymlo** [comment]
@lairship - this is a bug on mqtt only.  We will work on a fix for it.  Thanks.

**Comment by jasmineymlo** [comment]
@lairship - After investigation, it seems that "#" is a reserved character in the mqtt protocol and when used as device id, it messed up the decoding.  Please refrain from using "#" in the device id if possible.  Thanks.

**Comment by lairship** [comment]
ok, thanks, maybe add some comment in SDK doc is better.
