### ISSUE TITLE
PnP sample: error on bad parameter for command is not explicit

### ISSUE THREAD

**Issue by ericmitt** [Azure/azure-iot-sdk-csharp#1492]
Running the sample Thremostat, with IotExploer if I send a command getMaxMinReport without parameter I got an error code 500. Should be 400, or more explicit if possible

**Comment by vinagesh** [comment]
Fix is checked in with latest code. Closing the issue.

**Comment by az-iot-builder-01** [comment]
@vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
