### ISSUE TITLE
Remove user context from SetMethodHandler

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdk-csharp#15]
The last parameter in `SetMethodHandler` is unnecessary. It's a throwback to the 80-s style of programming with `void*`. There are three problems with it:

- There are many cases where it's not necessary, so the user has to pass `null`. This is an invitation for `NullReferenceExceptions`.
- In the callback, the user is forced to downcast the `object` to the expected type, which can be a source of errors (the actual and expected types must be kept in sync)
- It makes the implementation more complex (it needs to maintain `Tuple<MethodCallback, object>` instead of just `MethodCallback`)

The context can be passed into the callback with the help of a lambda:

```
deviceClient.SetMethodHandler("CallMe", _ => CallMe(_, new MyType()));
...
void CallMe(MethodRequest methodRequest, MyType mytype)
{
    // use mytype directly without having to downcast it from object
}
```

C# devs are quite capable of this nowadays.

**Comment by BertKleewein** [comment]
I would tend to agree with Artur, but we've already had a few conversations about this and I'm not sure how hard I would push.

**Comment by arturl** [comment]
How about we come up with a single solution that covers this and https://github.com/Azure/azure-iot-sdk-csharp/issues/14? This is just a simplification of the existing API with no loss of functionality.

**Comment by jasmineymlo** [comment]
Agreed after several discussion within the team that we are going to leave the last parameter "dataContext" as is.  It's not blocking user to implement using lambdas but provides flexibility for those who choose not to write the callback in lambdas.
