### ISSUE TITLE
Device Streams support for Downstream devices connecting via IoT Edge Gateway

### ISSUE THREAD

**Issue by vjrag** [Azure/azure-iot-sdk-csharp#1501]
Is Device Streams supported for Downstream devices that connect via IoT Edge (Transparent gateway Pattern)

I am using same DeviceProxy sample given in Quick Starts examples and using Device Connection String with GatewayHostName appended to it (SDK version - 1.29.1-preview-002). 

https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Quickstarts/device-streams-proxy/device

The code flow is stuck in the below statement. This never returns any error / timeouts.

DeviceStreamRequest streamRequest = await _deviceClient.WaitForDeviceStreamRequestAsync(cancellationTokenSource.Token).ConfigureAwait(false);

Also noticing frequent Disconnected_Retrying messages in the Callback for Connection Status Change handlers (Attached logs below)...

03-08-2020 11:48:27 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:49:28 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:49:30 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:50:30 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:50:32 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:51:32 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:51:36 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:52:36 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:52:37 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:53:38 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:53:39 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:54:39 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:54:40 : Connection Status changed to: Connected due to Connection_Ok
03-08-2020 11:55:42 : Connection Status changed to: Disconnected_Retrying due to Communication_Error
03-08-2020 11:55:43 : Connection Status changed to: Connected due to Connection_Ok

**Comment by timtay-microsoft** [comment]
@varunpuranik do you know if Edgehub supports this scenario?

**Comment by varunpuranik** [comment]
@vjrag , @timtay-microsoft - 
No, this device streams is not yet supported for devices connecting through IoT Edge in a gateway scenario. It is on our backlog, but I don't have a timeline on when it might be available yet.

**Comment by vinagesh** [comment]
@vjrag - Closing this issue as the scenario is not supported. Feel free to open a new issue if you are facing other problems. We will be happy to help.

**Comment by az-iot-builder-01** [comment]
@vjrag, @timtay-microsoft, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
