### ISSUE TITLE
[Bug Report] DeviceClient.UpdateReportedPropertiesAsync does not provide helpful information when property name contains invalid characters

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-iot-sdk-csharp#1505]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** 1.27.0

## Description of the issue
`DeviceClient.UpdateReportedPropertiesAsync` does not provide helpful information when the property name contains invalid characters, but instead throws a `InvalidOperationException` with a message along the lines of `Service did not provide a response` and it took a while to notice that the name was not allowed (in my case `Example.Property`).

This is because Azure IoT Hub has some restrictions in the naming:

> **Keys:** All keys in JSON objects are UTF-8 encoded, case-sensitive, and up-to 1 KB in length. Allowed characters exclude UNICODE control characters (segments C0 and C1), and ., $, and SP.

Learn more on https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins.

## More context
Report originated on https://github.com/Azure/azure-iot-sdk-csharp/pull/1503 which has some additional context

**Comment by timtay-microsoft** [comment]
From my initial investigation, this seems to be an issue in our AMQP stack. When I run a basic test for sending reported properties where a property has the name ```Property.Example```, MQTT returns a 400 (bad format) error as expected (albeit without any explanation about why the message was poorly formatted). AMQP does seem to consistently return the exception detailed above.

I'll look into why AMQP is behaving differently here

**Comment by bikamani** [comment]
@tomkerkhove Thanks for filing this, I am investigating this issue further and will soon post update.
