### ISSUE TITLE
'HardwareToken'  /  'HardwareIdentification' could not be found when build c# device sdk using vs2017 on Win10 version 1703

### ISSUE THREAD

**Issue by SLdragon** [Azure/azure-iot-sdk-csharp#151]
I tried to build the c# device sdk using vs2017 on Win10 version 1703, however, I got some errors:  

'HardwareToken'  /  'HardwareIdentification' could not be found

![image](https://user-images.githubusercontent.com/5545529/29200343-22a1049e-7e87-11e7-97ed-5e2c683f9710.png)

![image](https://user-images.githubusercontent.com/5545529/29200374-6067eb58-7e87-11e7-96f1-f93827156aff.png)

I found that Windows.System.Profile library doesn't have these two Class.

I search the google and try to add some references:
![image](https://user-images.githubusercontent.com/5545529/29200417-ac84dece-7e87-11e7-962e-adbe32d8123f.png)

However, it didn't work.

So can you give some advice about how to solve the problem?

**Comment by tameraw** [comment]
@SLdragon - Thanks for filing this issue. We'll investigate it.

**Comment by arturl** [comment]
The API has been present since v10.0.10240.0 (see docs [here](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwareidentification)). It's part of the regular build of Azure IoT SDK.
Most likely, you are missing Tools for Windows in you VS installation.
