### ISSUE TITLE
.SetDesiredPropertyUpdateCallbackAsync does not work after .SetMethodHandlerAsync with AMQP

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-iot-sdk-csharp#1522]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 x64 10.0.19041.450
- **Application's .NET Target Framework :** .net Core 3.1
- **Device:** Laptop
- **SDK version used:** 1.27.0

## Description of the issue
In code, when using AMQP, calling `.SetMethodHandlerAsync` after `.SetDesiredPropertyUpdateCallbackAsync` breaks `.SetDesiredPropertyUpdateCallbackAsync`.  The code below shows the issue -- meaning you will never see `Task aa(TwinCollection desiredProperties, object userContext)` called.  It does not happen with MQTT.

## Code sample exhibiting the issue

```
using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.Devices.Shared;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static DeviceClient deviceClient;

        static async Task Main(string[] args)
        {
            Console.WriteLine("creating deviceClient");
            deviceClient = DeviceClient.CreateFromConnectionString("HostName=ksaye****.azure-devices.net;DeviceId=test;SharedAccessKey=KbD******MQ=", TransportType.Amqp);

            await deviceClient.SetDesiredPropertyUpdateCallbackAsync(aa, null);
            await deviceClient.SetMethodHandlerAsync("autoUpdate", autoUpdateHandler, null);

            Console.WriteLine("Done");

            while (true)
            {
                System.Threading.Thread.Sleep(1000 * 5);
            }
        }

        private static Task aa(TwinCollection desiredProperties, object userContext)
        {
            Console.WriteLine("aa");
            return Task.CompletedTask;
        }

        private static Task<MethodResponse> autoUpdateHandler(MethodRequest methodRequest, object userContext)
        {
            throw new NotImplementedException();
        }
    }
}

```

If you either change the protocol or the order of `.SetMethodHandlerAsync` before `.SetDesiredPropertyUpdateCallbackAsync`, it works.

**Comment by timtay-microsoft** [comment]
Looks like you are right, I'm looking into this now

**Comment by timtay-microsoft** [comment]
Oddly, I can only get this to repro if I'm using the Azure portal to send these twin updates. When I use the SDK itself for either UpdateTwin or ReplaceTwin, the callbacks fire as normal.

@ksaye Are you using the portal or something else to send the desired property updates?

**Comment by timtay-microsoft** [comment]
Something in our AMQP layer is a bit off from my investigation so far. By opening the method links, suddenly the twin links won't receive anything. I'll keep digging

**Comment by timtay-microsoft** [comment]
It also appears this bug has been around for quite a few versions now.

**Comment by timtay-microsoft** [comment]
Even more interestingly, this bug only happens when you send desired property updates through the azure portal. By using the C# SDK's registry manager to send the desired property updates (either with replaceTwin or updateTwin) will cause the expected device side callbacks to fire.

I don't see similar behavior from the Java SDK, so it still appears to be a C# SDK bug, but it may be less critical than I first thought

**Comment by bikamani** [comment]
@ksaye I am looking into this issue further. I could not repro with latest bits of dotnet with Amqp protocol. Is this something you are still noticing? Could you confirm with the [latest ](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-11-5)version of our SDK?

**Comment by timtay-microsoft** [comment]
I can confirm that this behavior still happens. Let's talk offline about it @bikamani

**Comment by bikamani** [comment]
Another interesting find is, this happens when we create a new device using registry manager. I couldn't repro the same with a device that already exists.

**Comment by bikamani** [comment]
@ksaye You can use Task.Delay or WhenAll instead of Thread.Sleep(), look at our samples for reference [here ](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/TwinSample/TwinSample.cs#L54)and [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L71)

Let me know if that resolved your problem and if you have any other questions.

**Comment by bikamani** [comment]
@ksaye We haven't heard back from you yet. If you still find any issues or have questions, feel free to reopen. Thank you.
