### ISSUE TITLE
MQTT Connection fails if broker sends unsolicited messages

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1525]
**Context**
We started using the C# SDK with a compliant MQTT broker that also "understands" IoT Hub topics and messaging structure. It works well except in some edge cases, and it is caused by how the SDK handles certain situations.

**Description of the problem**
The C# SDK (using MQTT) connects with CleanSession flag 0. This means that the MQTT broker will "remember" the subscriptions the client had before, also after connection, the MQTT broker starts sending out messages failed to send previously, or accumulated over time.
The effect is that after the C# SDK connects (sends the CONNECT mqtt message and received CONNANK), it immediately (meaning millisecs ) starts receiving messages.
Let's say that the client previously was subscribed to receive module-to-module messages (and it had the appropriate message handler set). At high message rate, when the client suddenly disconnects, there can be messages waiting in the broker memory to be sent out. When the client connects again, because of the clean session = 0, the broker immediately starts sending the left of the messages. In this case the client code most probably has not subscribed to module-to-module messages yet and no handler is set, so from the SDK perspective these messages are "unsolicited"
According to the MQTT specification, unsolicited messages should be ACK-ed, even if the receiving client cannot handle them.
The current SDK implementation seems to behave correctly, so it starts ACK-ing the messages, however the behavior is not consistent:

- most of the time the client disconnects after a few messages ACK-ed, and then it reconnects. It causes a lot of disconnect/connect cycles
- after a few disconnect/connect iteration the SDK seems get stuck, and going forward noting happens
- sometimes after a few disconnect/connect cycle the SDK throws a disposed exception as it tries to use an SslStream object
- sometimes everything works fine and the client "swallows" all the messages and starts working properly.

**Expected behavior**
The SDK should ACK the unsolicited messages without disconnecting/connecting (or throwing object disposed exception)

For testing/debugging, I can provide a self-containing  C# project with a "mini" broker in it that starts sending unsolicited messages after the client connects that demonstrates the problems.

**Comment by abhipsaMisra** [comment]
@vipeller Sure, a self-contained sample demonstrating this behavior will be helpful for us to debug this issue.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abhipsaMisra** [comment]
Just to update the status here, I am no longer able to reproduce this particular issue with the current codebase (from `master`). I am running some other validations on the sourcecode, following which I'll have more results.

**Comment by abhipsaMisra** [comment]
With the fixes on our mqtt implementation, this issue is no longer reproducible. The sdk will ack unsolicited (but previously subscribed) messages. Disconnects are also handled gracefully, and will initiate reconnection for transient faults.
Closing this issue, feel free to reopen this issue if you still face problems!

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
