### ISSUE TITLE
DeviceClient.RetryPolicy = RetryPolicyType.No_Retry has no effect

### ISSUE THREAD

**Issue by Steve0212a** [Azure/azure-iot-sdk-csharp#153]
In the hopes of disabling retries, I have tried setting the RetryPolicy to No_Retry as shown below.

```
var deviceClient = DeviceClient.CreateFromConnectionString("<connection string>", TransportType.Amqp);
deviceClient.RetryPolicy = RetryPolicyType.No_Retry;
deviceClient.OperationTimeoutInMilliseconds = 1000;
```

However, it does not appear to stop the retries.  I am testing in a disconnected state and even though I am setting this, I see it retrying over and over for a long time.  That is not what I want.  I want it to try once and fail if it can't connect.  When I look at DeviceClient.cs, I do not even see RetryPolicy used at all.

As a work around for now, I have set the operation timeout so that it will timeout the whole operation and end the retries, but I do not like that solution.

How can I disable retry logic?

**Comment by jasmineymlo** [comment]
We are working on hooking up the NO_Retry policy type.  Should be in the next release.  Thanks.

**Comment by Steve0212a** [comment]
Thank you so much for the update.  Do you have an estimate for the next release date?

**Comment by jasmineymlo** [comment]
@Steve0212a The next release is scheduled to be 9/8.

**Comment by jasmineymlo** [comment]
Please test it out and let us know if you see any issues.  Thanks.
