### ISSUE TITLE
AMQP DeviceClient takes very long to detect a lost connection

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#1535]
- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04 amd64
- **Application's .NET Target Framework:** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** 1.28.0

## Description of the issue
Unlike MQTT DeviceClient (3 minutes), AMQP DeviceClient takes long duration (24 minutes)  to detecting a lost network connection. Docker is used only to simulate network loss and also for consistent repro. Otherwise, it has no other intended relation to the issue.

```console
cd DeviceReconnectionSample
dotnet publish -c Release -o /tmp/out
docker run -it --rm --name=test-sdk --entrypoint=/bin/bash -v /tmp/out:/app mcr.microsoft.com/dotnet/core/runtime:3.1-bionic
$ cd /app
$ export DEBUG=*
$ export IOTHUB_DEVICE_CONN_STRING='HostName=************.azure-devices.net;DeviceId=testub20;SharedAccessKey=***************************************='
$ dotnet DeviceReconnectionSample.dll
```

```console
// after initial connection establishment by the sample (10 seconds), open a second terminal and disconnect docker network 
docker network disconnect bridge test-sdk

```

## Code sample exhibiting the issue
https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/183408/iot-hub/Samples/device/DeviceReconnectionSample

## Console log of the issue

> roots@roots-pc:/tmp/dc$ docker run -it --rm --name=test-sdk --entrypoint=/bin/bash -v /tmp/out:/app mcr.microsoft.com/dotnet/core/runtime:3.1-bionic
> root@81a52de9c59f:/# cd /app
> root@81a52de9c59f:/app# export DEBUG=*
> root@81a52de9c59f:/app# export IOTHUB_DEVICE_CONN_STRING='HostName=************.azure-devices.net;DeviceId=testub20;SharedAccessKey=***************************************='
> root@81a52de9c59f:/app# dotnet DeviceReconnectionSample.dll
> 2020-08-23T15:25:32.4724197>> Debug - Attempting to initialize the client instance, current status=Disconnected
> 2020-08-23T15:25:32.5317887>> Debug - Initialized the client instance.
> 2020-08-23T15:25:32.5354899>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:25:32.5355158>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:25:37.2679975>> Debug - Connection status changed: status=Connected, reason=Connection_Ok
> 2020-08-23T15:25:37.2684230>> Debug - ### The DeviceClient is CONNECTED; all operations will be carried out as normal.
> 2020-08-23T15:25:37.6005639>> Warning - No message received, timed out
> 2020-08-23T15:25:37.6011027>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:25:37.6011306>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:25:38.0026559>> Debug - Connection status changed: status=Disconnected_Retrying, reason=Communication_Error
> 2020-08-23T15:25:38.0030938>> Debug - ### The DeviceClient is retrying based on the retry policy. Do NOT close or open the DeviceClient instance
> 2020-08-23T15:25:39.2159171>> Debug - Connection status changed: status=Connected, reason=Connection_Ok
> 2020-08-23T15:25:39.2162485>> Debug - ### The DeviceClient is CONNECTED; all operations will be carried out as normal.
> 2020-08-23T15:25:42.9242412>> Warning - No message received, timed out
> 2020-08-23T15:25:42.9246225>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:25:42.9247409>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:25:47.9233603>> Warning - No message received, timed out
> 2020-08-23T15:25:47.9237276>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:25:47.9238217>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:25:52.9261168>> Warning - No message received, timed out
> 2020-08-23T15:25:52.9269471>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:25:52.9275835>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> ....
> ....
> // skipping since no useful logs other than repeats of above lines
> ....
> 
> 2020-08-23T15:48:48.1149207>> Warning - No message received, timed out

> 2020-08-23T15:48:48.1150234>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:48:48.1150711>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:48:53.1148032>> Warning - No message received, timed out
> 2020-08-23T15:48:53.1148515>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:48:53.1148765>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
> 2020-08-23T15:48:54.7502025>> Debug - Connection status changed: status=Disconnected_Retrying, reason=Communication_Error
> 2020-08-23T15:48:54.7502541>> Debug - ### The DeviceClient is retrying based on the retry policy. Do NOT close or open the DeviceClient instance
> 2020-08-23T15:48:58.1321320>> Error - A network related exception was caught, but will try to recover and retry explicitly: System.TimeoutException: Timed out to acquire handler lock.
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(TimeoutHelper timeoutHelper)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass18_0.<<ReceiveAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
>    at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync(TimeSpan timeout)
>    at Microsoft.Azure.Devices.Client.Samples.DeviceReconnectionSample.ReceiveMessageAndCompleteAsync() in /home/roots/src/try/DeviceReconnectionSample/DeviceReconnectionSample.cs:line 220
>    at Microsoft.Azure.Devices.Client.Samples.DeviceReconnectionSample.ReceiveMessagesAsync(CancellationToken cancellationToken) in /home/roots/src/try/DeviceReconnectionSample/DeviceReconnectionSample.cs:line 182
> 2020-08-23T15:48:58.1323966>> Information - Device waiting for C2D messages from the hub - for 00:00:05...
> 2020-08-23T15:48:58.1324307>> Information - Use the IoT Hub Azure Portal or Azure IoT Explorer to send a message to this device.
>

**Comment by abhipsaMisra** [comment]
Do you see the same behavior on Windows as well, or is this specific to Linux only?

**Comment by kiranpradeep** [comment]
@abhipsaMisra I did not try with Wiindows client. So not sure.

**Comment by abhipsaMisra** [comment]
@kiranpradeep Are you setting the Amqp [idle timeout](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/AmqpTransportSettings.cs#L108) when initializing the device client?

**Comment by abhipsaMisra** [comment]
@kiranpradeep Your concern is valid, 24 minutes for detecting a disconnection event is definitely excessive, and not a reasonable time for applications. The device client library currently sends the idle timeout to the amqp library only if the user supplies a valid Timespan. I'll look into modifying this and setting a reasonable default value.

A small note here: the device client library currently does not monitor the ping request/ response over amqp, but rather delegates that to the transport library. Hence I wanted to confirm if you still see the issue after setting an idle timeout in your transport settings.

The steps you've provided above are pretty descriptive, and I appreciate the effort. I'll give this a try and let you know if I need further input.

**Comment by abhipsaMisra** [comment]
The fix has now been checked in. I tested with with the repro steps you've mentioned above, and I can see the connection status change callback now being returned in about 2-3mins.

Thanks again for bringing this to our attention!

**Comment by abhipsaMisra** [comment]
This fix has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-10-15
