### ISSUE TITLE
Deployment using RegistryManager.ApplyConfigurationContentOnDeviceAsync - Malformed Content

### ISSUE THREAD

**Issue by jaypaddy** [Azure/azure-iot-sdk-csharp#1538]
I'm building a tool that can be used for Module deployment to IoTEdge based on a configured set or properties in a CMDB.

The tool is able to generate a Deployment manifest and is using the .NET SDK - specifically - RegistryManager.ApplyConfigurationContentOnDeviceAsync to apply the deployment.

The serialized string from ConfigurationContent is as follows. When this template is applied, there is no error in the SDK, however in the portal for the Edge it shows the status as 400 -- The deployment configuration is malformed or invalid.

This same template (just the ModulesContent) when applied using Single Device deployment in VSCode, works fine. So, not sure what is causing the template deployment to fail through RegistryManager. Unable to figure out the malformed content in the template. Appreciate any guidance.

`
{
  "ModulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "paddycontainers": {
                "username": "paddycontainers",
                "password": "Rfb1vT9QuW=x2v3Z37jKFYNCg11uoT9Y",
                "address": "paddycontainers.azurecr.io"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0.9.2",
              "createOptions": "{}"
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0.9.2",
              "createOptions": "{\"HostConfig\":{\"ExposedPorts\":{\"9600/tcp\":{},\"5671/tcp\":{},\"8883/tcp\":{}}}}"
            },
            "env": {
              "experimentalfeatures__enabled": {
                "value": true
              },
              "experimentalfeatures__enableMetrics": {
                "value": true
              }
            }
          }
        },
        "modules": {
          "PySendModule1": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "PySendModule2": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "PySendModule3": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "PySendModule4": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "PySendModule5": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "PySendModule6": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "paddycontainers.azurecr.io/pysendmodule:0.0.1-amd64.debug"
            }
          },
          "SimulatedTemperatureSensor1": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": "{}"
            }
          },
          "metricscollector1": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "veyalla/metricscollector:0.0.4-amd64",
              "createOptions": "{}"
            },
            "env": {
              "AzMonWorkspaceId": {
                "value": "7fa12df9-0fec-44e6-a258-47e02437ab14"
              },
              "AzMonWorkspaceKey": {
                "value": "UEzSktwn/Z7x/aF89Y40H3Xkd2GFpQY8gOwgPP0ES9X3nTTkPk6/UnXpRP3THwhBeFuFV5Q/bsKAbJHBXAEBtg=="
              }
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {},
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    },
    "PySendModule1": {
      "properties.desired": {
        "camera360": "172.1.1.1",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    },
    "PySendModule2": {
      "properties.desired": {
        "camera360": "172.1.1.2",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    },
    "PySendModule3": {
      "properties.desired": {
        "camera360": "172.1.1.3",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    },
    "PySendModule4": {
      "properties.desired": {
        "camera360": "172.1.1.4",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    },
    "PySendModule5": {
      "properties.desired": {
        "camera360": "172.1.1.5",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    },
    "PySendModule6": {
      "properties.desired": {
        "camera360": "172.1.1.6",
        "fontSize": "10",
        "message": 300,
        "format": "Json",
        "target": "AzureLogAnalytics",
        "endpoints": {
          "edgeHub": "http://edgeHub:9600/metrics"
        }
      }
    }
  },
  "DeviceContent": null
}`

**Comment by jaypaddy** [comment]
I don't exactly know the difference and why this works. I had a version of this tool being able to successfully deploy. I was using Newtonsoft for JSON parsing. I had switched to System.Text.Json in the CSharp SDK and that seems to have broken the JSON into a malformed state. I switched back to Newtonsoft and my deployments are good.

**Comment by az-iot-builder-01** [comment]
@jaypaddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
