### ISSUE TITLE
SetConnectionStatusChangesHandler – handler does not fire when the module becomes connected.

### ISSUE THREAD

**Issue by Pascal561** [Azure/azure-iot-sdk-csharp#1541]
Context

- **Windows 10 Desktop x64
- **.Net Core 3.1
- **SDK version used:** Assembly Microsoft.Azure.Devices.Client, Version=1.28.0.0
- IotEdge Device with 1 Edge Module
- The code is derived from the following lesson:
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module-windows

## Description of the issue
- Start = Device is Enabled and Connected.
- Change 1 = Disable device (at 10:34:31)
10:34:31 The Device.Status becomes Disabled in the Twin of the Device.
After a few minutes: 
10:41:01 The Module.ConnectionState becomes Disconnected in the twin of the Module.
The SetConnectionStatusChangesHandler receives 2 events within 1 minute.
10:41:01.378 ConnectionStatus=Disconnected_Retrying, ConnectionStatusChangeReason=Communication_Error
10:41:01.471 ConnectionStatus=Connected, ConnectionStatusChangeReason=Connection_Ok

## Problem
When we Enable the device, than there are no more events of the changed connectionState of the module
10:47:15 The device is Enabled. The Device.Status becomes Enabled.
10:51:51 The module becomes ConnectionState=Connected.

## Problem after the Module became connected:
- The module does not fire an event (SetDesiredPropertyUpdateCallbackAsync) when the Twin.Properties.Desired have changed while the module was disconnected.
- There are no events from the SetConnectionStatusChangesHandler that indicates to the module that it became connected. We need this to pull the latest desired properties.

## Code sample exhibiting the issue
In the Main():
await IoTHubModuleClient.SetDesiredPropertyUpdateCallbackAsync(twinsHostMonitor.OnDesiredPropertiesUpdate, null);
IoTHubModuleClient.SetConnectionStatusChangesHandler(StatusChangesHandler);

public static void StatusChangesHandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
{
    Log.Logger.Information("---------------------- StatusChangesHandler ----------------------");
    Log.Logger.Information($"- ConnectionStatus='{status}'");
    Log.Logger.Information($"- ConnectionStatusChangeReason='{reason}'");
}

public async Task OnDesiredPropertiesUpdate(TwinCollection desired, object userContext)
{
    //Process changes
}

**Comment by abhipsaMisra** [comment]
Which protocol are you using? Do you see this behavior over both mqtt and amqp?

**Comment by Pascal561** [comment]
I am using mqqt.

Sample from code:
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
ITransportSettings[] settings = { mqttSetting };
IoTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);

I don't know how to use amqp in the code of the module.
I get the error message "Unsupported Transport Type " whe I use:
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Amqp);
or
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Amqp_Tcp_Only );

**Comment by abhipsaMisra** [comment]
Thanks for the info.
When connecting over Amqp, you would need to initialize `AmqpTransportSettings`:
```csharp
AmqpTransportSettings transportSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { transportSetting };
IoTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
```

Note, when initializing transport settings, you need to specify the transport type to be either `TransportType.Amqp_Tcp_Only` or `TransportType.Amqp_WebSocket_Only`; you cannot use `TransportType.Amqp` (Tcp with fallback to Websocket).

**Comment by timtay-microsoft** [comment]
@Pascal561 do you still need help with anything here?

**Comment by Pascal561** [comment]
I performed a new test with the edge module connected via TransportType.Amqp_Tcp_Only.

Test 1: Disabeling the device.
11:48:27 All ok
•	Device.Status = Enabled
•	Device.ConnectionState = Connected
•	Module.ConnectionState = Connected
•	Module.TestCommand (a ServiceClient.InvokeDeviceMethodAsync command to check the command functions) = Success
11:49:00 Disabled the device via the Azure webportal.
11:49:08 Device status became Disabled
11:53:32 Module.ConnectionState became Disconnected, and the TestCommand failed.
11:58:27 Device.ConnectionState became Disconnected
11:58:30.507 The Module.StatusChangesHandler fired with ConnectionStatus='Disconnected_Retrying', ConnectionStatusChangeReason='Communication_Error'
11:58:30.563 The Module.StatusChangesHandler fired with ConnectionStatus='Connected', ConnectionStatusChangeReason='Connection_Ok'

This is strange:
•	Device.ConnectionState stayed Disconnected, and the StatusChangesHandler fired with ConnectionStatus='Connected'.

Test 2: Enabeling the device
12:08:00 Enabled the Device via the Azure webportal.
12:08:12 Device.Status became Enabled.
12:08:42 Module.ConnectionState became Connected

Something strange: 18 minutes later
•	Device.ConnectionState stayed Disconnected.
•	The Module.TestCommand kept failing.
•	I had to reboot the host, to get everything working again.

Test 3: Disabeling the device for the second time.
12:27:00 All ok
•	Device.Status = Enabled
•	Device.ConnectionState = Connected
•	Module.ConnectionState = Connected
•	Module.TestCommand = Success
12:28:00 Disabled the device via the Azure webportal.
12:28:08 Device status became Disabled
12:31:31 Module.ConnectionState became Disconnected, and the TestCommand failed.

Something strange: 45 minutes later
•	Device.ConnectionState stayed Connected.
•	The Module.StatusChangesHandler never fired.

Test 4: Enabeling the Device
13:18:00 Enabled the Device via the Azure webportal.
13:18:08 Device.Status became Enabled

Something strange: 19 minutes later:
•	Module.ConnectionState stayed Disconnected.
•	Module.Testommand kept failing
•	Had t orestart the Host to get everything online again

Questions:
•	Is it good practice to Disable and Enable the device via the Azure webportal? Is this reliable?
•	What is a better way to Disable and Enable devices?

**Comment by barustum** [comment]
Question: Are you trying to simulate a device offline scenario?

Some notes and observations I received from the Edge team:
When disabling a device on the portal, the fact that the module does not get the connection callback triggered is expected because the connection to the cloud is disconnected. However, the module to edgeHub is still connected.

Regarding the desired properties update callback, when a module connects to edgeHub it does not need to monitor the connection events to be able to receive desired properties updates. Per the edge team, it is not recommended because there is a connection to edgeHub which will continue to be connected even when the device is offline. EdgeHub detects when is goes offline and back online and if there was a desired property update while offline it will send it to the module which will trigger the callback from SetDesiredPropertyUpdateCallbackAsync. But we have a known issue that the callback is not triggered if the module didn’t call GetTwinAsync when it starts. Based on your snippet, this looks to be the case. If you can add GetTwinAsync in main when the modules starts I think the issue should be solved.

This seems to be a edge issue, if the fix I mentioned above doesn’t solve the issue I think they should open it with edge: https://github.com/Azure/iotedge/issues

**Comment by Pascal561** [comment]
In my current edge module, the GetTwinAsync was called BEFORE the SetDesiredPropertyUpdateCallbackAsync.
Is that OK, or must it be switched?

**Comment by barustum** [comment]
I believe that should be OK, per the suggestion from the Edge team. 

@ancaantochi  Based on the response from the customer, you mentioned this might be an edge issue. Should the customer log a bug in https://github.com/Azure/iotedge/issues?

**Comment by barustum** [comment]
@Pascal561 I confirmed with Anca from the Edge team. She recommended filing an issue with the Edge team:
https://github.com/Azure/iotedge/issues

Anca recommended turn on debug logs for edgeHub (set env variable RuntimeLogLevel to debug) and provide the logs.

**Comment by Pascal561** [comment]
Here a latest overview of the code the problem:

Initialization on startup of the iot edge module:

Log.Logger.Information($"Initialize Amqp_Tcp_Only: ModuleClient.CreateFromEnvironmentAsync");
AmqpTransportSettings transportSetting = new AmqpTransportSettings(Microsoft.Azure.Devices.Client.TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { transportSetting };
IoTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await IoTHubModuleClient.OpenAsync();
Log.Logger.Information("IoT Hub module client initialized.");
Twin moduleTwin = await IoTHubModuleClient.GetTwinAsync();
await OnPropertiesUpdate(moduleTwin.Properties.Desired, null);/Creates Logline: [inf] OnPropertiesUpdate Started.
...
Log.Logger.Information($"Init: OnPropertiesUpdate: Attach a callback for updates to the module twin's desired properties.");
await IoTHubModuleClient.SetDesiredPropertyUpdateCallbackAsync(OnPropertiesUpdate, IoTHubModuleClient);
Log.Logger.Information("Program started completely.");

ControlTest: When device is enabled:

13:50 Step 1: Reboot device
13:52:18.735 [inf] Initialize Amqp_Tcp_Only: ModuleClient.CreateFromEnvironmentAsync
13:52:23.986 [inf] IoT Hub module client initialized.
13:52:24.366 [inf] OnPropertiesUpdate Started.
13:52:25.151 [inf] Init: OnPropertiesUpdate: Attach a callback for updates to the module twin's desired properties.
13:52:33.586 [inf] Program started completely.

14:00 Step 2: perform an update of a desired property of the twins of the module via azure portal
+ Wait for the OnPropertiesUpdate - event
14:00:17.087 [inf] OnPropertiesUpdate: Started.

14:02 Step 3: Disable device via azure portal

14:08 Step 4: perform an update of a desired property of the twins of the module via azure portal
The OnPropertiesUpdate – event not triggered
This is normal.

14:10 Step 5: Enable theDevice via azure portal

14:58 Step 6: Wait OnPropertiesUpdate – event
When viewing the device and module twins via the azure portal:
Device. connectionState=Connected, status=Enabled, 
Module: connectionState=Connected, status=enabled
The OnPropertiesUpdate – event still not triggered

Problem:
After 40 minutes: the OnPropertiesUpdate – event was still not triggered.
I had to reboot the device to get the OnPropertiesUpdate  - events working.

How can I fix this, so that I don’t have to reboot the device after a Disable and Enable of the device?

**Comment by drwill-ms** [comment]
I'm curious why the device is being disabled. What is the intention here?

When a device is disabled, it is going to be disconnected and the SDK won't try to reconnect. You should get a connection status callback to that effect on the device. It would be up to application code to decide to retry connect after some time. See [this sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L136) for more instructions.

**Comment by barustum** [comment]
@Pascal561 Have you had the chance to add a connection status callback to the code per the sample David referenced? If so, did it help?

**Comment by Pascal561** [comment]
I implemented the example of the ConnectionStatusChangeHandler from:
https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L136

**Sequence of initialisation code:**
```
AmqpTransportSettings transportSetting = new AmqpTransportSettings(Microsoft.Azure.Devices.Client.TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { transportSetting };
IoTHubModuleClient = ModuleClient.CreateFromEnvironmentAsync(settings).GetAwaiter().GetResult();
Log.Logger.Information($"Initialize: Set ConnectionStatusChangeHandler");
IoTHubModuleClient.SetConnectionStatusChangesHandler(ConnectionStatusChangeHandler);
await IoTHubModuleClient.OpenAsync();
Log.Logger.Information("Initialize: IoT Hub module client initialized.");
```

**Versions:**
```
iotedge version
iotedge 1.0.10.2 (eef9f16bd3ec2572f83399ec0e3c56111b43242c)
```

```
iotedge list
NAME        STATUS           DESCRIPTION      CONFIG
myModule    running          Up an hour       xxxxxxxxx-windows-amd64
edgeAgent   running          Up an hour       mcr.microsoft.com/azureiotedge-agent:1.0
edgeHub     running          Up an hour       mcr.microsoft.com/azureiotedge-hub:1.0
```


**Test:**

**09:39 Startup device**

09:39:59.303 [inf] Main: ++++++++++ Module started ++++++++++
09:40:00.682 [inf] Initialize: Set ConnectionStatusChangeHandler
09:40:02.159 [dbg] ConnectionStatusChangeHandler: Connection status changed: status=Disconnected_Retrying, reason=Communication_Error
09:40:02.159 [dbg] ConnectionStatusChangeHandler: ### The DeviceClient is retrying based on the retry policy. Do NOT close or open the DeviceClient instance
09:40:05.919 [dbg] ConnectionStatusChangeHandler: Connection status changed: status=Connected, reason=Connection_Ok
09:40:05.920 [dbg] ConnectionStatusChangeHandler: ### The DeviceClient is CONNECTED; all operations will be carried out as normal.
09:32:47.800 [inf] Initialize: IoT Hub module client initialized.

**09:55 Disconnect the netwerk cable**

10:02:34 Read device and module twin:
Device. connectionState=Disconnected, status=Enabled, 
Module: connectionState=Disconnected, status=Enabled

**_10:27: NO ConnectionStatusChangeHandler events triggered._**

**10:28 Reconnect the network cable**

10:28:34 Read device and module twin:
Device. connectionState=Connected, status=Enabled, 
Module: connectionState=Connected, status=Enabled

10:44 Testing:
Commands: OK
TwinProperty updates: OK

**_10:45: NO ConnectionStatusChangeHandler events triggered._**


**Conclusions:**

- The ConnectionStatusChangeHandler was only triggered after the OpenAsync.
- The ConnectionStatusChangeHandler was NOT triggerd when the module became Disconnected or Connected_after_disconnected.


**Questions:**

- Why is there no callback when the module became Disconnected?
- Why is there no callback when the module became Connected after it was disconnected?
- The example was for an iot device. Does this also work for an iote edge **Module**?
- Are the versions up to date for the “iotedge version”  (1.0.10.2), EdgeAgent (1.0), HubAgent(1.0)?
- Does this method work with the TransportType.Amqp_Tcp_Only?

**Comment by barustum** [comment]
Thanks @Pascal561 for your reply.

Here are the answers to your questions:

> Why is there no callback when the module became Disconnected?
> Why is there no callback when the module became Connected after it was disconnected?

The fact that the module doesn’t get the connection callback triggered is expected because the connection to the cloud is disconnected, but the module to edgeHub is still connected. @ancaantochi, can you please confirm?

> The example was for an iot device. Does this also work for an iote edge Module?

Yes

> Are the versions up to date for the “iotedge version” (1.0.10.2), EdgeAgent (1.0), HubAgent(1.0)?

I actually am not sure what the latest versions of iot edge is. @ancaantochi can you please confirm?

>Does this method work with the TransportType.Amqp_Tcp_Only?

It should work for AMQP and MQTT.

**Comment by ancaantochi** [comment]
Hi @Pascal561

Latest release of edgeAgent and edgeHub are 1.0.10.3, but the behavior you described is expected so 1.0.10.2 would work the same.

From your recent comments I understand that the twin callback gets triggered when the device is back online, but the connection callback is not. This is expected behavior because the module connects to edgeHub and that connection works while the connection to the cloud is disconnected (that's between edgeHub and IotHub). 

For the iot device example do you connect the device to edge gateway? If yes, the connection callback in not triggered, if you connect directly to the cloud than I would expect to get connection callback when going offline/online.

If the twin updates callback is not triggered than there is an issue in edgeHub, you can open an issue with iotedge: https://github.com/Azure/iotedge/issues Please turn on debug logs and provide them in the issue: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2018-06#check-container-logs-for-issues

**Comment by Pascal561** [comment]
We only use iot edge devices. Not regular iot devices.

We completed a new test and confirm that the twin updates are triggered on the modules when the network connection is restored.

Thank you for all your efforts and explanation.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @Pascal561, @timtay-microsoft, @ancaantochi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
