### ISSUE TITLE
C2D Feedback reciever throws Operation was canceled 

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdk-csharp#156]
Opening on behalf of a customer.  They were sending C2D messages to their devices and then using a separate webjob to check that the messages had been received, based upon the suggestion in our documentation here:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d#receive-delivery-feedback 

Generally this worked fine for them, but recently they have started to see some exceptions from the Feedback Receiver and could not get it working correctly again until they restarted the entire webjob service.  For their immediate needs I have suggested they look at leveraging direct methods for a more real-time commands for the device, but believe we should also have better retry logic in our feedback receiver as well.

Here is the info from the customer:

Here is the link explains about IOTHub Feedback Listener
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d

To receive request delivery acknowledgements from IoT Hub devices, we have created a separate Webjob running continuously as singleton, this webjob fails randomly and erroring out, this causes huge impact to our project because we are relying on the IOTHub Feedback receiver to acknowledge the request delivery in real-time to the IOTHub devices. 

Here is the error we are receiving from the IOTHub Feedback Receiver, once we get this error then the state of the IOTHub Feedback Receiver is not reliable: 
`[8/24/2017 8:32:32 PM] - Exeption: The operation was canceled.:    at Microsoft.Azure.Devices.AmqpFeedbackReceiver.<ReceiveAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IOTResponseHandler.IOTHubFeedBackHandler.<ReceiveFeedbackFromIOTHub>d__7.MoveNext() in C:\Official\CFI\WLL\Source\WLLSolution\IOTResponseHandler\IOTHubFeedBackHandler.cs:line 45`

Not sure, how to recover from this issue without restarting the webjob. We are thinking to omit the IOTHub Feedback Receiver, wanted to get your ideas to resolve and find a solution.

**Comment by tameraw** [comment]
Currently retry logic for the service SDK is in our backlog.
However, we'll investigate why we're getting the Exception for the operation cancelled. 
Can you please share a snip-it of the code pertaining to this issue? thanks.

**Comment by CIPop** [comment]
Closing: very old, no answer from OP.

**Comment by PriyaDhiv** [comment]
Facing the same operation failure issue when trying to fetch the DeviceFeedback messages from IOTHUB using the [**var feedbackBatch = await feedbackReceiver.ReceiveAsync();**] statement in webjobs after deploying the code in azure. But when trying to run the same snippet in local, able to fetch the device feedback messages without any failure or time delay. 

The same code was working fine when deployed it in azure function. Can anyone helps to resolve this issue.

### 

at Microsoft.Azure.Devices.AmqpFeedbackReceiver.<ReceiveAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NextGenGw.WebJobs.Services.DeviceFeedback.FeedbackReceiver.<ReceiveFeedbackAsync>d__5.MoveNext()

**Comment by PriyaDhiv** [comment]
Below are few details regarding the issue, can anyone helps to resolve this issue with the following informaiton


Required information | Examples
-- | --
TimeFrame (include time zone) | 2019-08-28T07:19:19Z- 2019-08-28T07:24:19Z (UTC)
SDK that failed (include NuGet Version) | Devices
Configuration delta | Normal Azure function to receives the device ACK/NACK by listening IOTHUB.
OS version, SKU and CPU arch | Windows 10 Pro
.NET Target Framework Moniker | netcoreapp2.1
Device Type | Radio communication-based Loader
Device Id | For all devices
Description of issue | Facing the same operation failure issue when trying to fetch the DeviceFeedback messages from IOTHUB using the [var feedbackBatch = await feedbackReceiver.ReceiveAsync();] statement in webjobs after deploying the code in azure
Repro code [if available] | var feedbackBatch = await feedbackReceiver.ReceiveAsync();
Expected result | Need to record device feedback, but webjob was failed with exceptions.
Actual result | at Microsoft.Azure.Devices.AmqpFeedbackReceiver.d__15.MoveNext()--- End of stack trace from previous location where exception was thrown ---at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at NextGenGw.WebJobs.Services.DeviceFeedback.FeedbackReceiver.d__5.MoveNext()


![image](https://user-images.githubusercontent.com/55128272/65236878-1d02a280-daf7-11e9-8bc3-e2f47f6ebde2.png)

**Comment by bikamani** [comment]
Closing this old issue as there is already an [issue ](https://github.com/Azure/azure-iot-sdk-csharp/issues/1052) open here.

**Comment by az-iot-builder-01** [comment]
@jtanner-msft, @CIPop, @PriyaDhiv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
