### ISSUE TITLE
Could not load file or assembly System.Net.Http.Formatting, Version=5.2.6.0?

### ISSUE THREAD

**Issue by apostrophesoftware** [Azure/azure-iot-sdk-csharp#1563]
# Context

- **OS, version, SKU and CPU architecture used:** <VERSION> (Windows 10 Desktop x64,)
- **Application's .NET Target Framework :** <NETVERSION> (net461)
- **Device:** <DEVICETYPE> (Laptop)
- **SDK version used:** <VERSION> (1.22.0)

## Description of the issue
When I call ServiceClient.InvokeDeviceMethodAsync the method is called correctly and returns the correct result however an exception is generated in the caller code at the point the call returns.

I have just updated the library from 1.18.0 as the whole project was upgraded to version 12.0.3 of NewtonSoft.Json, prior to this upgrade the code was working correctly.

## Code sample exhibiting the issue
            LastErrorMessage = String.Empty;
            CloudToDeviceMethodResult result = new CloudToDeviceMethodResult
            {
                Status = (int)System.Net.HttpStatusCode.BadRequest
            };

            try
            {
                
                CloudToDeviceMethod method = new CloudToDeviceMethod(methodName, TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5));

                if (!String.IsNullOrEmpty(methodParameters))
                {
                    method.SetPayloadJson(methodParameters);
                }

                result = await client.InvokeDeviceMethodAsync(DeviceId, method);
            }
            catch(Exception ex)
            {
                LastErrorMessage = Utilities.GetFullExceptionMessage(ex);
                result.Status = (int)System.Net.HttpStatusCode.InternalServerError;
            }
            return result;

## Console log of the issue
ServiceClient.InvokeDeviceMethodAsync

Exception

Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   stack trace
   
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__38.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteWithCustomOperationTimeoutAsync>d__35.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__28`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VI_Device.Devices.AzureIoTDevice.<StartDeviceMethod>d__19.MoveNext() in E:\Data\Development\VisibleIndustry\repos\VI_CloudBase\VI_Device\Devices\AzureIoTDevice.cs:line 165
   
   Inner exception
   Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   
   Inner Exception
   Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   
   TargetType.DeclaringType.FullName
   Microsoft.Azure.Devices, Version=1.22.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Comment by abhipsaMisra** [comment]
It looks like we added an explicit reference to `'System.Net.Http` post 1.18.0, but that was added for net472 assembly. I am unable to reproduce this exception, neither on net461, nor on net472.
Would it be possible for you to try it with a different project target framework in your test environment, and see if you still hit this issue?

Also, so that I understand the issue completely, could you elaborate what this statement means?
> When I call ServiceClient.InvokeDeviceMethodAsync the method is called correctly and returns the correct result however an exception is generated in the caller code at the point the call returns.

Do you get an exception when you call `ServiceClient.InvokeDeviceMethodAsync`, or do you get the expected response?

**Comment by apostrophesoftware** [comment]
@abhipsaMisra When I call InvokeDeviceMethodAsync the method on the device is executed are returns correctly, when control returns to the cloud application the exception occurs, I am assuming that this is when the method is attempting to format the result?  So to answer your question I do not get the expected response from the method call.

I can try and find time to try a different target framework.  We do have a large number of projects in the solution so I don't know what additional impact that will have.

Currently we are unable to ship the latest version of the software

Regards
Dave

**Comment by apostrophesoftware** [comment]
I have cleaned the projects, cleared NuGet caches, updated all the libraries to the latest versions and framewrok to 4.7.2 and I am still unable to get the InvokeDeviceMethodAsync to return without generating the exception

**Comment by vinagesh** [comment]
I tried to reproduce this but I did not get any exceptions. Can you share your .csproj so that I can try to repro the error?

**Comment by vinagesh** [comment]
@apostrophesoftware - Let us know how we can help. We are not able to repro this and would like to know your setup.

**Comment by apostrophesoftware** [comment]
This is no longer a priority so I will close the issue

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @apostrophesoftware, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
