### ISSUE TITLE
C2D - Exception regarding MQTT PUBACK packet

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-sdk-csharp#157]
When sending a C2D message via MQTT which is not accepted / rejected from the device (for any reason) for all next messages we have the following exception:

_Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Client MUST send PUBACK packets in the order in which the corresponding PUBLISH packets were received (QoS 1 messages) per [MQTT-4.6.0-2]. Expected lock token: '82'; actual lock token: '7be4c322-b597-4ff4-9a4c-ff4fffa4b19792'_

It seems that the rest messages can not be either accepted or rejected by the device until the 1st one completed. How can we pass over this situation?

**Comment by jasmineymlo** [comment]
@mtheolog, For your reference, check out the Message Lifecyle https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d.  Devices must complete the received message or choose to reject/abandon the message.

**Comment by jasmineymlo** [comment]
@simonporter PTAL

**Comment by CIPop** [comment]
@mtheolog closing as this is a very old issue. Please let us know if the Message Lifecycle documentation was not sufficient by reopening the issue.
