### ISSUE TITLE
Device client too heavy for Windows FormAplicattion

### ISSUE THREAD

**Issue by enchiladaRoja** [Azure/azure-iot-sdk-csharp#159]
OS: Windows10
SDK: Microsoft.Azure.Devices  v1.3.2
Language: C#

Hello, I´m developing a Windows Form Application on C#. In this app, I´m sending messages to my IoT Hub using the NuGet Packet **Microsoft.Azure.Devices  v1.3.2** and receive those messages on a raspberry pi. 
Ony with this package install, the app is about 30 MB, and that´s ok for me.
The problem is that I need to receive messages from the IoT Hub in this app too, so what I did is to install the NuGetPacket **Microsoft.Azure.Devices.Client v1.5.0** that help me receive messages, but if I install this package, it increases the weight of the app like 300 MB more, and that´s way to heavier than I want it.

My question is, is there other way to receive message from my IoT Hub in my Windows Form Application without all that extra weight? Am I missing a package to help me do that in a more easy way?
Thank you in advance.

**Comment by sergaz-msft** [comment]
Hello @enchiladaRoja ,
The alternatives to using the SDK is to use MQTT protocol directly: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly or you can also leverage the REST API: https://docs.microsoft.com/en-us/rest/api/iothub/HttpRuntime/ReceiveDeviceBoundNotification .

You can also clone the Device SDK and remove all the unnecessary parts for your device\project.

+ @olivierbloch to add some comments as well.

All Best!
