### ISSUE TITLE
IoTHub direct methods showing high latency & connection pooling for ServiceClient Objects

### ISSUE THREAD

**Issue by nijasbrawther123** [Azure/azure-iot-sdk-csharp#1597]
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows, IoTHub .Net SDK
- **Application's .NET Target Framework :** <NETVERSION>  .Net Framework 4.8
- **Device:** <DEVICETYPE>  
- **SDK version used:** <VERSION>  1.19

## Description of the issue:

We are seeing high latency for IoTHub direct method calls with increased load.
Currently using IoTHub .Net SDK (1.19) for invoking direct methods on device. 

All the settings like Response timeout and Device Timeouts are kept to the default values. 

Scenario:

We have around 20 odd IoTHubs distributed to our clients and roughly 100k devices connected across all these IoTHubs. The number of devices will increase to 500-600k in few months time. 

Is there any recommendation around the service client instantiation in such scenarios. We can see there is an underlying connection pool implementation for the Device Client logic, However there is no such logic for Service Clients. 

Currently we create a service client object and dispose it per request. Is this ideal ? 

I can see in the MS service client SDK code( under https://github.com/Azure/azure-iot-sdk-csharp), that with each object MS creates 2 HttpClient objects behind the scene(with & without timeout). 
Does this creation of Service client object per request run into ephemeral port exhaustion and/or added latency ?

Should we be implementing a custom connection pooling logic for managing Service client objects in this scenario ?

## Code sample exhibiting the issue:

service = ServiceClient.CreateFromConnectionString(connectionString);

**Comment by bikamani** [comment]
Thanks for your question, we'll try to take a look at this soon.

Meanwhile could you describe a bit more about what is the latency noticed in this scenario?
Is the SDK version mentioned for Device Client/Service Client?
Is there anything blocking to update SDKs to latest version? 
If not, with latest version is it same behavior?
Could you also provide application/sample code exhibiting this issue for both your device and service client?

**Comment by bikamani** [comment]
For the question: "Currently we create a service client object and dispose it per request. Is this ideal ?"
>> Recommended approach is to hold on to the client created and not dispose per request. So it does not run into port exhaustion. If you need to create multiple connection perhaps use a concurrent dictionary. 

Currently we do not have a support for providing your own instance of http client but we will add it in our backlog which will resolve issue of disposing client. Let us know if this helps or if there are further questions.

**Comment by nijasbrawther123** [comment]
- Thanks for the recommendation/confirmation on the client management part. 

- Though we are not facing any throttling issues at the moment, but we will soon be hitting/using IoTHub methods at a larger scale. So is it ideal to do some kind of throttled request pattern from our side in such scenarios? Like at max only 'x' number of IoTHub direct method calls at a given time to a particular IoTHub? 


**To your earlier questions,**

- We are facing high latencies consistently for our IoTHub direct method calls and from the behavior we could see that its worsening with increased load. 
- Latency is around 15+ secs in average for successful IoTHub direct method invocations.
- SDK mentioned here is for Service Client

**Comment by nijasbrawther123** [comment]
Couple more queries on the Service Client part:

- **RETRY** - What are the ideal scenarios for a retry with Service client. Is there any inbuilt support to the Service client library for transient errors ?
Or we should be having a custom retry policy (eg: Polly etc) that looksup on the error code returned and then perform a retry ? - If yes whats the ideal error codes to do a re-try and any doc on this?

- Secondly on the scenario like, like in a second, if a particular device is targeted for a large number of Direct method calls, say 50 calls in a sec! , Is there a throttling at the IoTHub side per device level ? Or whats the ideal way to handle it, given the Direct methods are **synchronous**.

**Comment by bikamani** [comment]
Just to update here - this is being investigated through support channel and we will close the issue here.

To answer questions above:
- There isn't an inbuilt support for retry on service client. We have it in our backlog though, however it isn't something planned as of now. You can certainly add a retry mechanism on your own considering specific exceptions for which you'd like to retry. Here's a document of error codes: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-401003-iothubunauthorized
- Here's link to error codes for direct methods specifically: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#response
- IoT hub throttling is defined here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#response

**Comment by az-iot-builder-01** [comment]
@nijasbrawther123, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
