### ISSUE TITLE
[Bug Report] DPS Provisioning Status not set when enrollment is created via SDK

### ISSUE THREAD

**Issue by Werner-Prbk** [Azure/azure-iot-sdk-csharp#1604]
# Context

- **OS, version, SKU and CPU architecture used:** Azure App Service, .NET Core, 32bit
- **Application's .NET Target Framework :** .NET Core 
- **SDK version used:** Microsoft.Azure.Devices.Provisioning.Service (1.16.1)

## Description of the issue
Provisioning Status of DPS Individual Enrollment is ignored when set to 'Disabled' if the enrollment is created with Device Provisioning SDK. In DPS, the enrollment is always listed as 'Enabled'. Same tests with Azure CLI result in expected behavior.

## Code sample exhibiting the issue
```
public async Task EnrollDeviceAsync(string endorsementKey, string registrationId, CancellationToken cancelToken)
{
	using var provisioningServiceClient = ProvisioningServiceClient.CreateFromConnectionString(_dpsConnectionString);
	
	try
	{
		await provisioningServiceClient.DeleteIndividualEnrollmentAsync(registrationId, cancelToken);
	}
	catch(Exception){}
	
	Attestation attestation = new TpmAttestation(endorsementKey);

	var devTwin = await _deviceTwinProvider.GetInitialDeviceTwin(cancelToken);

	IndividualEnrollment individualEnrollment = new IndividualEnrollment(registrationId, attestation)
	{
		IotHubHostName = _iotHub,
		DeviceId = registrationId,
		InitialTwinState = devTwin,
		ProvisioningStatus = ProvisioningStatus.Disabled   // this is ignored at DPS
	};

	IndividualEnrollment individualEnrollmentResult =
		await provisioningServiceClient.CreateOrUpdateIndividualEnrollmentAsync(individualEnrollment, cancelToken);
}
```

**Comment by timtay-microsoft** [comment]
I haven't been able to reproduce this behavior. When I run your sample code on the latest provisioning service client version, the returned individualEnrollmentResult is marked as disabled as expected, and the Azure Portal shows the same status. When you run your sample code, is the returned individualEnrollmentResult not marked as disabled?

And when you say 

> In DPS, the enrollment is always listed as 'Enabled'

Are you referring to the Azure Portal view of your enrollments, or are you referring to how the enrollment actually behaves (i.e. it is marked as disabled, but can still be used)?

**Comment by timtay-microsoft** [comment]
Also, what version of .NET core are you using?

**Comment by Werner-Prbk** [comment]
Thank you for your quick response.
After testing the whole afternoon the problem disappeared and everything works as expected.
I could not figure out what the real problem was, I guess something during App Service deployment went wrong.
Sorry!

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @Werner-Prbk, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
No worries! I'm glad everything is working as expected now
