### ISSUE TITLE
Is DeviceClient ThreadSafe? 

### ISSUE THREAD

**Issue by mterwoord** [Azure/azure-iot-sdk-csharp#1613]
Many .NET classes have thread safety documented, like for example `List<T>` at https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-3.1#thread-safety.

It would be great to have similar documentation for DeviceClient and related classes.

**Comment by vinagesh** [comment]
Yes the DeviceClient is thread safe and we will look at adding it to the documentation.

**Comment by mterwoord** [comment]
Great. So I can use `SendEventAsync` from multiple threads without any synchronisation?

**Comment by vinagesh** [comment]
What is the expectation you have from SendEventAsync? Are you trying to send the same message or different messages?

**Comment by mterwoord** [comment]
I have several threads generating telemetry, and I'm hoping I can just share a `DeviceClient` instance and call `SendEventAsync` on that whenever the telemetry is generated.

**Comment by vinagesh** [comment]
You should be able to do that safely. If you run into any issues, feel free to reach out.

**Comment by mterwoord** [comment]
Thanks for clearing this up! This will simplify my code quite a bit.

**Comment by az-iot-builder-01** [comment]
@vinagesh, @mterwoord, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
