### ISSUE TITLE
deviceClient.OpenAsync() never finishes when called without internet connection

### ISSUE THREAD

**Issue by kolbster81** [Azure/azure-iot-sdk-csharp#1616]
Prerequisites / Tested Environment:
- Windows 10, dotnet core 3.1, windows service
- using TransportType.Mqtt
- deviceClient.OperationTimeoutInMilliseconds has been set to 10 Seconds
- Executing deviceClient.OpenAsync() while internet connection is gone

Under the above circumstances, the OpenAsync() method never finishes, even when internet-connection is up shortly after the call. 
If the device client has been opened once with internet connection, the OpenAsync() times out as expected after "OperationTimeoutInMilliseconds" millis.

Thanks and regards
Martin

**Comment by abhipsaMisra** [comment]
Do you mean to say that the client never opens up, even after the connection is available? Would you mind sharing the sdk logs: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by kolbster81** [comment]
Hi, I'm not sure if this is what you want (see  etl-file attached)
[iot_000003.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/5402287/iot_000003.zip)

Yes, the client never opens up: I have a non-async method which calls  deviceClient.OpenAsync().Wait();  within a "lock" section. I reused code which microsoft provided by this example here: https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample 

I started testing the code for several circumstances like interrupting internet connection, disconnect from iot hub, etc, and also what happens if the hardware is not even connected to the internet, but my code will start up. In this case, I noticed, the "OpenAsync().Wait()" never finishes, it does not even run into a timeout, which is what I expect.

Thanks,
Best regards
Martin

**Comment by kolbster81** [comment]
See comment above, no issue at all.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @kolbster81, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
