### ISSUE TITLE
Connection broken when very long values are set in the device twin

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-csharp#162]
We’ve run into a problem where one of our reported json values is about 570 bytes – and that caused the SDK to close the connection:

'Toaster.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\23983CETAthensQuality.IoTToasterSampleVS.Debug_x86.gmileka\System.Runtime.InteropServices.dll'. Symbols loaded.
Exception thrown: 'System.Exception' in Microsoft.Azure.Devices.Client.UWP.dll
Exception thrown: 'System.Exception' in Microsoft.Azure.Devices.Client.UWP.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
'Toaster.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\23983CETAthensQuality.IoTToasterSampleVS.Debug_x86.gmileka\System.Threading.Timer.dll'. Symbols loaded.
Connection changed: Disabled Client_Close
[AzureDM]    [Verbose]    Connection changed: Disabled Client_Close
Exception thrown: 'System.Exception' in Microsoft.Azure.Devices.Client.UWP.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
'Toaster.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\23983CETAthensQuality.IoTToasterSampleVS.Debug_x86.gmileka\System.Diagnostics.StackTrace.dll'. Symbols loaded.
[AzureDM]    [Error]    System.Exception: request 4e6fc495-5f64-4ee6-b3c7-872bdf590aa5 returned status 400
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<SendTwinRequestAsync>d__71.MoveNext()

**Comment by jasmineymlo** [comment]
@gmileka, do you mean reported property in TwinCollection?

**Comment by jasmineymlo** [comment]
Confirmed with service side that Iothub currently has a limitation of 512 bytes for property values that are strings.  A deployment this week will increase this to 4K.  So, this should be fixed after deployment.  Thanks.

**Comment by jasmineymlo** [comment]
The fix on service should now be available.  Thanks.
