### ISSUE TITLE
DeviceClient.SendEventAsync fails in versions  1.21.3 and newer of Microsoft.Azure.Devices.Client

### ISSUE THREAD

**Issue by mrtaunus** [Azure/azure-iot-sdk-csharp#1620]
# Context

- **OS, version, SKU and CPU architecture used:** <VERSION>Windows 10 and Azure Function App
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp3.1
- **Device:** <DEVICETYPE> Laptop + Cloud
- **SDK version used:** <VERSION> Microsoft.Azure.Devices 1.27.3, Microsoft.Azure.Devices.Client 1.21.2 - 1.32.0

## Description of the issue
I have had a working Function App sending messages to Azure IoT Hub via DeviceClient.SendEventAsync. After upgrading referenced packages, that stopped working. After testing several packages, I found that upgrading Microsoft.Azure.Devices.Client to anything newer than 1.21.2 breaks my function in both local testing in Visual Studio as well as running in the cloud in an Azure Function App. The error is shown below. After downgrading back to 1.21.2 everything starts to work again.

## Code sample exhibiting the issue
```
var iotHubConnectionString = await KeyVaultFacade.GetIotHubConnectionString( context );

iotHubConnectionString += $";DeviceId={deviceId};";

var deviceClient = DeviceClient.CreateFromConnectionString( iotHubConnectionString );

// This call fails
await deviceClient.SendEventAsync( new Message( Encoding.UTF8.GetBytes( requestData.ToString() ) ) );
```

## Console log of the issue
Exception: 
`Microsoft.Azure.Devices.Client.Exceptions.DeviceNotFoundException: 'error(condition:amqp:not-found,description:{"errorCode":404001,"trackingId":"5a7c2af5076f4f499fa51faffb2f2c9e-TimeStamp:10/20/2020 09:47:48-G:47-TimeStamp:10/20/2020 09:47:48","message":"MyDeviceId;","timestampUtc":"2020-10-20T09:47:48.0903707Z"},info:[com.microsoft:is-filtered:True])'`

**Comment by abhipsaMisra** [comment]
The exception message indicates that the device was not registered on Azure; however, from your explanation I understand that on simply downgrading the device client package version fixes this error for you (with no other change in the infrastructure setup).
Could you attach the [SDK logs](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs) for both scenarios - one where you get the above error with the latest SDK, and where your setup works with v1.21.2.

**Comment by barustum** [comment]
@mrtaunus can you try removing the semicolon at the end of the device id and see if that works for you? The hub thinks the semicolon is part of the device id. At some point, the hub used to support semicolons in the device id, but that's no longer the case.

**Comment by mrtaunus** [comment]
> @mrtaunus can you try removing the semicolon at the end of the device id and see if that works for you? The hub thinks the semicolon is part of the device id. At some point, the hub used to support semicolons in the device id, but that's no longer the case.

This resolved the issue! Without the semicolon everything works even with the newest version of the package. 

A bit bizarre the behaviour, though. Isn't the semicolon just a separator of different pieces in the connection string? Why is it suddenly interpreted as part of the device ID?

Anyhow, thanks a lot for your help!

**Comment by barustum** [comment]
Thanks for confirming.

The reason why the semicolon is interpreted as part of the device ID is because the SDK has an issue where it allows semicolons to be passed in, even though the service rejects it. We will address this issue from the SDK side soon.

**Comment by barustum** [comment]
I synched up with the Hub team. It turns out that there are still devices out there with semicolons. So a change in the SDK to disallow semicolons in the device names is a breaking change. The issue that spurred this PR seems to be resolved just by providing a connection string without a semicolon at the end, which seems like a reasonable expectation to put on the user.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @mrtaunus, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
