### ISSUE TITLE
ContentType not preserved between IotHub and ServiceBus

### ISSUE THREAD

**Issue by adminnz** [Azure/azure-iot-sdk-csharp#163]
I have an Iot Hub which is routing DeviceEvents to a Azure Service Bus Topic. 
When I send a Message to the Iot Hub from a Device, it is routed perfectly fine.
But when consuming the Azure Service Bus message the ContentType is no longer populated. 
I'm not sure if this is a problem with the Iot Hub Device client library or more an issue with how Azure is doing the IotHub -> Service Bus routing.

```
var msg = new Message(Encoding.UTF8.GetBytes(json));
msg.ContentType = "application/json";
msg.Properties.Add("TestProperty", "Test");
msg.MessageId = Guid.NewGuid().ToString("N");
```

The additional message details (e.g. "TestProperty", MessageId) appear to be preserved, just not the ContentType.

**Comment by CIPop** [comment]
@nberdy @simonporter PTAL - this appears to be a service-side issue/question.

**Comment by mastermanu** [comment]
We've confirmed a service-side bug on this issue. We will let you know when the fix is deployed. Thanks for letting us know about this!

**Comment by CIPop** [comment]
@adminnz I have confirmation from the service team that the bug has been fix and queued up for deployment. 
We'll let you know once the service has been updated.

**Comment by CIPop** [comment]
The service has been updated. 
Please try again now and let us know if you still see this issue.
