### ISSUE TITLE
Cannot resend a Message on ServiceClient - throws ObjectDisposedException

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#1638]
There is a bug in `Microsoft.Azure.Devices` where we cannot resend the same message using `ServiceClient.SendAsync()`.

This is because:
-  the AMQP message being created is a property of the IoT Hub `Message` class. 
- The AMQP message needs to be disposed after each send attempt made by the AMQP library.

As a result, repeated sends of the same IoT Hub message results in the SDK attempting to send a disposed AMQP message, resulting in an `ObjectDisposedException`.

**Comment by abhipsaMisra** [comment]
This has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-11-2

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
