### ISSUE TITLE
ObjectDisposedException for IoT Client in SetDesiredPropertyUpdateCallbackAsync

### ISSUE THREAD

**Issue by ntrpnr** [Azure/azure-iot-sdk-csharp#1643]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** .NET Framework 4.7.2 targeted
- **Device:** Laptop
- **SDK version used:** 1.30.0

## Description of the issue
We have built our implementation on top of **[this ](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample)** sample code.
It has been working well but during the night we got an object disposed exception when calling **SetDesiredPropertyUpdateCallbackAsync**. 

Prior to calling SetDesiredPropertyUpdateCallbackAsync we got an connection status change event with status **ConnectionStatus.Disconnected_Retrying**, which triggered InitializeClientAsync (as in the sample above), which then tried to call SetDesiredPropertyUpdateCallbackAsync where the exception took place.

## Code sample exhibiting the issue
Here's a small code snippet:
```
deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, transportType);
deviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChangeHandler);
deviceClient.OperationTimeoutInMilliseconds = (uint)operationTimeout.TotalMilliseconds;

await this.deviceClient.SetDesiredPropertyUpdateCallbackAsync(propertiesUpdatedCallback, null); //This is where the exception bubbled to.
```

The rest is very similar to this:
**[DeviceReconnectionSample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample)**

## Console log of the issue
Stack trace (sorry for the Swedish):
```
System.ObjectDisposedException: Det går inte att komma åt ett borttaget objekt.
Objektnamn: IoT Client.
   vid Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ThrowIfDisposed()
   vid Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   vid Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<EnsureOpenedAsync>d__31.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass23_0.<<EnableTwinPatchAsync>b__0>d.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<EnableTwinPatchAsync>d__23.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Azure.Devices.Client.InternalClient.<SetDesiredPropertyUpdateCallbackAsync>d__87.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Azure.Devices.Client.InternalClient.<SetDesiredPropertyUpdateCallbackAsync>d__86.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   vid <ApplicationName>.Client.Managers.DeviceClientManager`1.<InitializeClientAsync>d__19.MoveNext() i C:\_work\7\s\<ApplicationName>.Client\Managers\DeviceClientManager.cs:rad 69
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   vid <ApplicationName>.Client.Managers.DeviceClientManager`1.<ConnectionStatusChangeHandler>d__25.MoveNext() i C:\_work\7\s\<ApplicationName>.Client\Managers\DeviceClientManager.cs:rad 228
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   vid System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   vid System.Threading.ThreadPoolWorkQueue.Dispatch()
   vid System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by abhipsaMisra** [comment]
Thanks for bringing this to our attention.
One question on this statement:
> Prior to calling SetDesiredPropertyUpdateCallbackAsync we got an connection status change event with status ConnectionStatus.Disconnected_Retrying, which triggered InitializeClientAsync (as in the sample above), which then tried to call SetDesiredPropertyUpdateCallbackAsync where the exception took place.

We actually don't recommend disposing/ initializing your client when it is reconnecting, but rather to do that only when the status reported is "disconnected". When the device reports "Disconnected_Retrying", the transport layer is attempting to reconnect, and disposing and recreating a client from a different thread can cause the client to run out of sync.
In the statement above you've mentioned that you perform the initialization action on "Disconnected_Retrying"; if that is the case, could you move that action to "Disconnected" status event and give it a try.

**Comment by ntrpnr** [comment]
Yes, you are right of course. For some reason, we called InitializeClient although it is clearly stated in the sample that this should not be done.

Thank you for bringing this to our attention.

**Comment by abhipsaMisra** [comment]
Did the solution work for you @ntrpnr , or do you still see an issue?

**Comment by ntrpnr** [comment]
We changed the code to not call InitializeClient on Disconnected_Retrying and we haven't seen the error since - but we don't know for sure.

The ObjectDisposedException we saw might perhaps cause issues in other scenarios than ours?

**Comment by abhipsaMisra** [comment]
An `ObjectDisposedException` signifies that the device client is trying to perform an operation on an object which has already been disposed. Delegating the retrying responsibility entirely to the device client when it is in `Disconneced_Retrying` state will ensure that we do not have multiple actors trying to manage the client (and its transport layer's) state at the same time.

It could be related to the previous state your application was in, since if you try to dispose and recreate the device client while it is retrying internally, it could cause the transport layer underneath to go out of sync, and cause the device client to try to open a transport layer referencing an object which has now been externally disposed.

If you'd like, we can keep this issue open for another week while you test it some more. You can also re-open a closed issue, or open a new issue and add a link to this, if you face the same error again in the future!

**Comment by ntrpnr** [comment]
You can go ahead and close it for now. Thanks.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @ntrpnr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
