### ISSUE TITLE
[Bug Report] NullreferenceException when accessing twin metadata retrieved via DeviceClient

### ISSUE THREAD

**Issue by AieatAssam** [Azure/azure-iot-sdk-csharp#1667]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client 1.33.1

## Description of the issue
Upon retrieving TwinCollection device-side (not registry-side) via GetTwinAsync(), an attempt to call any metadata-related methods generates a meaningless NullReferenceException. Examples of methods are **GetLastUpdated**(), **GetLastUpdatedVersion**(), **GetMetadata**().

## Code sample exhibiting the issue
```csharp
using var deviceClient = DeviceClient.CreateFromConnectionString("<SNIP>");
	
var twin = await deviceClient.GetTwinAsync();
var lastUpdated = twin.Properties.Reported.GetLastUpdated();
```

## Cause
A number of methods inside of TwinCollection.cs retrieve data from _metadata field without checking it for null.

## Suggestion
Since the workflow here is indeed flawed (metadata for twin is available via RegistryManager and not DeviceClient), the system should generate an error. However, allowing NullreferenceException is just plain wrong. Instead, null check should be done and a meaningfull exception thrown instead. Alternatively, the methods in question should return nullable types and null values when metadata is nto present.

**Comment by bikamani** [comment]
@AieatAssam thanks for submitting this bug. I will discuss with rest of the team and get back on this soon.

**Comment by bikamani** [comment]
@AieatAssam Since adding a different exception here would change the behavior and break customers. For now, we have added appropriate [documentation ](https://github.com/Azure/azure-iot-sdk-csharp/pull/1734/files)(xml comments) and next release will have this change.

**Comment by AieatAssam** [comment]
Thank you. That is a very valid point. However, the xml documentation here does not actually explain why the metadata can be null (i.e. when used from the wrong side of the IoT Hub access - i.e. DeviceCLient rather than RegistryManager). Should this be added to the XML docs as well? I.e. highlight that it is not meant to be used from device side?

**Comment by bikamani** [comment]
@AieatAssam Somehow I missed your response, sorry for delay on getting back to this. In the link I mentioned above, we added xml comments at Line 31 regarding explanation for why metadata could be null and that it can result in NRE. Let me know if you think having this as part of GetLastUpdated() documentation rather than what we have currently is helpful.

**Comment by bikamani** [comment]
Since the fix is checked in and released, closing this issue. Feel free to reopen if you have more questions. Thank you!
