### ISSUE TITLE
TransportType "Amqp_WebSocket_Only" not working

### ISSUE THREAD

**Issue by FelixXWS** [Azure/azure-iot-sdk-csharp#167]
Hello,

I implemented a device simulator and uploaded it as a webjob. The TransportType of the DeviceClient I tried was "Amqp_WebSocket_Only". But I recognized that if I call the method "Task Device.Client.OpenAsync()" the process hangs and the code is no futher processed. Is there any explanation for that?

Kind regards,
Felix

**Comment by jasmineymlo** [comment]
@FelixXWS, What is the target platform for your application?

**Comment by FelixXWS** [comment]
Hello,

my platform target is "Any CPU". The Tagret Framework is .NET 4.6. The versions of the Microsoft.Azure.Devices.Client I tested are 1.4.2 and 1.5.0.

**Comment by jasmineymlo** [comment]
Hi @FelixXWS , Just wondering if you have tried other TransportType, say Amqp (without WS).  Are you using x509 certs?

**Comment by FelixXWS** [comment]
Hi @jasmineymlo,

the TransporType Amqp (without WebSocket) works without any problems. Just wondering why Amqp with Websocket does not work. I don't use any certs. And I don't think that our firewall is the problem.

**Comment by sodablue** [comment]
Ok, same thing here.   

Today I took the DeviceClientAmqpSample and modified it to connect to a IotHub I just created in my Azure test subscription.   I can connect and send messages using Amqp or Http, but not with Amqp_Websocket_only.

I ran this test on a Windows Virtual Machine that was created in US East, same as the IoTHub.   I wanted to make sure there were no firewall or web proxy issues like I might be encountered running the test from my desktop.

The connectionstring was a generated symmetric key for the device.

I found a unit test in Microsoft.Azure.Devices.E2ETests/MessageE2ETests.cs that tests transport type.   Looking at the code for SendSingleMessage() in that class, it did a OpenAsync() before calling SendEventAsync(), so I added that to see what would happen and received the same timeout error.

**Comment by jasmineymlo** [comment]
I ran DeviceClientAmqpSample as well and it works fine on my end, send and receive messages with Amqp_Websocket_only.

You might want to get network trace to get more info:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing

Wiresharks traces as well.

**Comment by sodablue** [comment]
I was able to figure this out.

It had to do with the combination of nuget packages.

Upgrading Microsoft.Azure.Amqp to version 2.1.0, 2.1.1 or 2.1.2 causes it to fail.    I tested and version 2.0.3 or 2.0.6 works.

This combination works:
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="DotNetty.Buffers-signed" version="0.3.2" targetFramework="net461" />
  <package id="DotNetty.Codecs.Mqtt-signed" version="0.3.2" targetFramework="net461" />
  <package id="DotNetty.Codecs-signed" version="0.3.2" targetFramework="net461" />
  <package id="DotNetty.Common-signed" version="0.3.2" targetFramework="net461" />
  <package id="DotNetty.Handlers-signed" version="0.3.2" targetFramework="net461" />
  <package id="DotNetty.Transport-signed" version="0.3.2" targetFramework="net461" />
  <package id="EnterpriseLibrary.TransientFaultHandling" version="6.0.1304.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.Azure.Amqp" version="2.0.3" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Client" version="1.2.6" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.0.11" targetFramework="net461" />
  <package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net461" />
  <package id="Microsoft.Data.Edm" version="5.7.0" targetFramework="net461" />
  <package id="Microsoft.Data.OData" version="5.7.0" targetFramework="net461" />
  <package id="Microsoft.Data.Services.Client" version="5.7.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="net461" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="net461" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="net461" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="net461" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="net461" />
  <package id="System.Spatial" version="5.7.0" targetFramework="net461" />
  <package id="Validation" version="2.2.8" targetFramework="net461" />
  <package id="WindowsAzure.Storage" version="7.1.2" targetFramework="net461" />
</packages>

**Comment by CIPop** [comment]
Thanks @FelixXWS and @sodablue for reporting and investigating this issue.
Tracking the dependency regression with https://github.com/Azure/azure-amqp/issues/81
