### ISSUE TITLE
azure-iot-hub System.IO.IOException: Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by ulaurent** [Azure/azure-iot-sdk-csharp#1673]
C# , Net Framework 4.7.2, I have built a connection to Azure IoT Hub using the provided device SDK's. My application functions as expected when running on a Win 10 OS. When I run my application on Win 7 I receive this exception:

Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: HTTP transport exception ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

With some research I fount that it may be due to the security protocol type, but I did not set the protocol type explicitly like the reference below state:

Authentication failed because remote party has closed the transport stream

What I am using is a SecurityProviderSymmetricKey to build a connection to the DPS.

I also verified that my Win 7 machine had TLS 1.2 enabled, since based on what I have researched it is not enable by default, & I still receive the exception.

What I also found it that the device SDK does not allow you to specify the protocol, & it uses the default of the machine.

https://github.com/Azure/azure-iot-sdk-csharp https://github.com/Azure/azure-iot-sdk-csharp/blob/master/configure_tls_protocol_version_and_ciphers.md

Any ideas on to why it would be building the connection properly on Win 10 and not Win 7? Any ideas on changes that need to be made, or how I can troubleshoot this issue further?

**Comment by drwill-ms** [comment]
Here are [instructions](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/configure_tls_protocol_version_and_ciphers.md) for how to configure Windows to enable/disable different TLS versions.

You can influence which TLS version is used with the [TlsVersions](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/shared/src/TlsVersions.cs) class.

Does this help?

**Comment by ulaurent** [comment]
Yes. thank you. Would the version of the TLS being used affect the opening of the tranport stream for the device SDK? What is the minimum version to set in order for the device SDK to build the connection stream? TLS 1.2?

The exception that we are seeing is when we are registering the device using the “ProvisioningDeviceClient” & “RegisterAsync”:

using (var transport = new ProvisioningTransportHandlerHttp())
                {
                    ProvisioningDeviceClient provClient =
                        ProvisioningDeviceClient.Create(GLOBAL_DEVICE_ENDPOINT, SCOPE_ID, security, transport);

                    result = await provClient.RegisterAsync();

                    return result;
                }

 System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

If so, would setting the minimum version through the TlsVersion class do the trick?

**Comment by ulaurent** [comment]
using (var transport = new ProvisioningTransportHandlerHttp())
{
ProvisioningDeviceClient provClient =ProvisioningDeviceClient.Create(GLOBAL_DEVICE_ENDPOINT, SCOPE_ID, security, transport);

                result = await provClient.RegisterAsync();

                return result;
            }

**Comment by az-iot-builder-01** [comment]
@ulaurent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ulaurent** [comment]
Sorry, closed it by mistake

**Comment by drwill-ms** [comment]
No, you are completely right here - we did not enable influencing the TLS version for DPS yet. I responded too quickly. Let me take a look. I think the best you could do right now is influence the OS.

**Comment by drwill-ms** [comment]
I got a Win7 SP1 VM running in Azure, cloned [this repo](https://github.com/Azure-Samples/azure-iot-samples-csharp), and ran [this sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/provisioning/Samples/device/SymmetricKeySample). It works fine for me (with protocol AMQP TCP only). I didn't change my Win7 state for TLS version enablement. Can you elaborate on your environment and settings more?

**Comment by ulaurent** [comment]
Yes, my target machine is a Win7 SP1. I am using protocol HTTP for provisioning and Http1 for transport type. I will try using AMQP with the sample that you have provided. Is there a reason why AMQP would work over HTTP on this type OS?

**Comment by ulaurent** [comment]
So I testing using AMQP and I was able to build a connection successfully. Thanks for the advice. Would there be a reason this to be the only protocol that works on Win 7?

**Comment by drwill-ms** [comment]
I tried using HTTP and encountered the same error.

I followed the instructions at <https://github.com/Azure/azure-iot-sdk-csharp/blob/master/configure_tls_protocol_version_and_ciphers.md> and from that at <https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-12>, and added the regkeys below, and it worked. Can you try to see if it works for you?

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```

**Comment by ulaurent** [comment]
Thank you for your help. I have tried the change and it has worked out. Thanks Again

**Comment by az-iot-builder-01** [comment]
@ulaurent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
