### ISSUE TITLE
Unable to create a twin update job for a lot of devices

### ISSUE THREAD

**Issue by FrankHoogmans** [Azure/azure-iot-sdk-csharp#1680]
# Context
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 / Azure WebApp Windows host
- **Application's .NET Target Framework :** netcoreapp2.2 (and up)
- **Device:** Laptop, Azure WebApp host
- **SDK version used:**     
    Microsoft.Azure.Devices - 1.20.1 (and up, have not tested earlier versions)
    Microsoft.Azure.Devices.Shared - 1.20.0 (and up, have not tested earlier versions)

## Description of the issue
I have an Azure IoTHub (S2) environment with 4000+ devices, to which I'm trying to send the same TwinPatch to update them.
I am hitting 2 different issues when trying to achieve this update.

**First**
To achieve this update, I am using the Azure IoT SDK JobClient (.NET), using the following code:

```csharp
    JobResponse result = await this._jobClient.ScheduleTwinUpdateAsync(
                            Guid.NewGuid().ToString("D"),
                            $"DeviceId IN [{String.Join(',', deviceIds.Select(d => $"'{d}'"))}]",
                            twinPatch,
                            DateTime.UtcNow,
                            172800)
```

This results in the following error:

>    Precondition failed: {"Message":"ErrorCode:PreconditionFailed;The etag in the request does not match the etag of the existing resource, as per RFC7232, please check and try again","ExceptionMessage":"Tracking ID:26317b31a7c54068bf72889047952787-G:3-TimeStamp:11/18/2020 10:55:20"}

Executing the 'DeviceId IN []' query (with 4000 device id's) on the Azure Portal, within the IoT Hub Query Explorer, results in the same RFC error as seen above.

After some trial and error, I found that reducing the number of devices in the request to around 250 will make it succeed again. I can't seem to find any documentation on a limit within this query. Is there any limit, and if so, where is it documented?

**Second**
Subsequently, when splitting this job into multiple jobs, I am running into the concurrent job limit of 5 for an S2 instance (updating 4000 devices in batches of 250 takes 16 jobs). I tried scheduling every next job further in the future, and shortening the max runtime (so they don't overlap), but the 5 concurrent job limit seems to include `Queued` jobs. Which makes it completely impossible to use this as a normal/primary scheduling mechanism, unless I'm missing something...

**Comment by timtay-microsoft** [comment]
For context, "PreconditionFailed" typically means that you sent an out of date ETag with the patch request. When scheduling twin patches, you'll need to make sure that you have the latest copy of the device's twin before trying to patch it. Granted, this is very complicated for twin patches scheduled in the future.

> After some trial and error, I found that reducing the number of devices in the request to around 250 will make it succeed again. I can't seem to find any documentation on a limit within this query. Is there any limit, and if so, where is it documented?

It's possible that, by making the request apply to fewer devices, you've decreased the likelihood of patching a twin with an out of date ETag

That said, most of these questions would be better answered by someone who could look at the logs for your particular hub. I recommend [opening a customer support ticket](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) as that will provide an avenue for you to share your hub details to a service team member who can confirm what is happening here.

Unless I'm misunderstanding, there doesn't appear to be a bug in the SDK itself. Especially if the Azure Portal's Query Explorer is hitting the same issue. Since this repo is strictly for the SDK, not the service, would you mind if I closed this issue?

**Comment by FrankHoogmans** [comment]
> 
> 
> For context, "PreconditionFailed" typically means that you sent an out of date ETag with the patch request. When scheduling twin patches, you'll need to make sure that you have the latest copy of the device's twin before trying to patch it. Granted, this is very complicated for twin patches scheduled in the future.
> 
> > After some trial and error, I found that reducing the number of devices in the request to around 250 will make it succeed again. I can't seem to find any documentation on a limit within this query. Is there any limit, and if so, where is it documented?
> 
> It's possible that, by making the request apply to fewer devices, you've decreased the likelihood of patching a twin with an out of date ETag
> 
> That said, most of these questions would be better answered by someone who could look at the logs for your particular hub. I recommend [opening a customer support ticket](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) as that will provide an avenue for you to share your hub details to a service team member who can confirm what is happening here.
> 
> Unless I'm misunderstanding, there doesn't appear to be a bug in the SDK itself. Especially if the Azure Portal's Query Explorer is hitting the same issue. Since this repo is strictly for the SDK, not the service, would you mind if I closed this issue?

Well, the ETag is not the one in the patch, but some HTTP thing from the RFC. This is proven by using the portal, where I am not updating, just querying said devices, and this gives me the same issue. Also, the error mentions an RFC for the HTTP protocol, also indicating the request is never reaching IoTHub, but failing somewhere in the HTTP layer before... See https://tools.ietf.org/html/rfc7232 for the actual RFC the error seems to be referring to.

Also, proving this has nothing to do with the ETag in the request, you can try 2 things on any given IoTHub (you don't actually need devices in there to get this query to fail exactly like mine):
- Query devices with a long IN condition, I use 4000 guid's, but it already fails around 500
- Try my update code (patch doesn't really matter), it will fail with the same error. Even when setting the ETag to *, which according to the documentation should match everything.

I would be fine contacting Microsoft Support through Azure, but it is not related to a specific IoTHub or Device, since I can reproduce this behavior across several different IoTHubs.

**Comment by FrankHoogmans** [comment]
I've gotten a response from Microsoft's Product team on a different question thread, so I will be closing this issue. 
It doesn't fully explain my issues, but it is enough to notice that my approach is not the recommended one. 

For reference, this was the response from product team:
>    1. It will update 10 per seconds and next will be subjects for https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#traffic-shaping and throttling.
>    2. However, it'll keep retrying throttled requests within specified job execution window. Hence, if windows is short there're chances it'll mark device job as throttled.
>    3. There's a separate bucket for jobs so it does not interfere with direct twin updates.
>    If you want to avoid throttling we recommend using https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-automatic-device-management

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @FrankHoogmans, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yang-cy-94** [comment]
> I've gotten a response from Microsoft's Product team on a different question thread, so I will be closing this issue.
> It doesn't fully explain my issues, but it is enough to notice that my approach is not the recommended one.
> 
> For reference, this was the response from product team:
> 
> > 1. It will update 10 per seconds and next will be subjects for https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#traffic-shaping and throttling.
> > 2. However, it'll keep retrying throttled requests within specified job execution window. Hence, if windows is short there're chances it'll mark device job as throttled.
> > 3. There's a separate bucket for jobs so it does not interfere with direct twin updates.
> >    If you want to avoid throttling we recommend using https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-automatic-device-management

would like to update here that there is actually a query limit for Azure IoT hub, which is around 8200 Bytes, i.e. 8200 characters. Any query exceeding this limit will report PreconditionFailed error.

**Comment by drwill-ms** [comment]
@FrankHoogmans I'm glad you got an answer from support that gives you better direction for how to use the IoT Hub service. It can be tricky, for sure.
