### ISSUE TITLE
[Bug Report] The second connection to the IoTHub using AMQP transport sometimes causes 2 disconnects instead of one.

### ISSUE THREAD

**Issue by anatoliibugaiev** [Azure/azure-iot-sdk-csharp#1682]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** net461
- **Device:** Desktop
- **SDK version used:**
```
  <package id="Microsoft.Azure.Amqp" version="2.4.7" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Client" version="1.33.1" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.26.0" targetFramework="net461" />
```

## Description of the issue
The second connection to the IoTHub using AMQP transport sometimes causes 2 disconnects instead of one.

**Steps to reproduce**
1) Establish 1st connection to IoTHub, set retry policy to NoRetry.
`_client.OpenAsync();`
2) Start receiving
` _client.ReceiveAsync(token)`
3) Establish 2nd connection to IoTHub using same connection string
4) Start receiving

**Expected behavior**:
1st connection drops

**Actual behavior**: 
both connections drop.

## Code sample exhibiting the issue
Please remove any connection string information!

```c#
using System;
using System.Configuration;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.Devices.Client;

namespace IotDevice
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var connectionString = ConfigurationManager.AppSettings["IoTHubConnectionString"];
            if (string.IsNullOrEmpty(connectionString))
            {
                Console.WriteLine("Connection string to the IoTHub is empty. Add connection string to the  App.config file as IoTHubConnectionString");
                Console.ReadLine();
                return;
            }
            ConnectionStatus status1 = ConnectionStatus.Disconnected;
            ConnectionStatus status2 = ConnectionStatus.Disconnected;
            int attempts = 1;
            var device1 = new Device("1");
            var device2 = new Device("2");

            do
            {
                Console.WriteLine($"--------------Attempt {attempts}----------------");
                CancellationTokenSource receiveCts1 = new CancellationTokenSource();
                CancellationTokenSource receiveCts2 = new CancellationTokenSource();
                var receiveToken1 = receiveCts1.Token;
                var receiveToken2 = receiveCts2.Token;
                Task t1 = Task.CompletedTask;
                Task t2 = Task.CompletedTask;
                if (status1 != ConnectionStatus.Connected)
                {
                    await device1.Connect(connectionString, receiveCts1);
                    t1 = device1.Receive(receiveToken1);
                }

                await Task.Delay(TimeSpan.FromSeconds(1));
                if (status2 != ConnectionStatus.Connected)
                {
                    await device2.Connect(connectionString, receiveCts2);
                    t2 = device2.Receive(receiveToken2);
                }
                await Task.Delay(TimeSpan.FromSeconds(1));
                await Task.WhenAny(t1, t2);
                Console.WriteLine($"Connection status of 1 device: {device1.ConnectionStatus}");
                Console.WriteLine($"Connection status of 2 device: {device2.ConnectionStatus}");
                status1 = device1.ConnectionStatus;
                status2 = device2.ConnectionStatus;
                attempts++;
            } while (status1 != status2);
            Console.WriteLine("Test finished");
            Console.ReadLine();
        }
    }
    public class Device
    {
        private readonly string _logId;
        private DeviceClient _client;
        public Device(string logId)
        {
            _logId = logId;
            ConnectionStatus = ConnectionStatus.Disconnected;
        }
        public ConnectionStatus ConnectionStatus { get; private set; }
        public async Task<bool> Connect(string connectionString, CancellationTokenSource cancellationTokenSource)
        {
            _client = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Amqp);
            try
            {
                _client.SetConnectionStatusChangesHandler((status, reason) =>
                {
                    Console.WriteLine($"[{DateTime.Now}] [{_logId}]: Connection status changed to: {status}. Reason: {reason}");
                    ConnectionStatus = status;
                });
                _client.SetRetryPolicy(new NoRetry());
                await _client.OpenAsync();
                return true;
            }
            catch (Exception)
            {
                Console.WriteLine($"[{DateTime.Now}] [{_logId}]: Connection Failed.");
                _client.Dispose();
                return false;
            }
        }
        public async Task<Message> Receive(CancellationToken token)
        {
            try
            {
                Console.WriteLine($"[{DateTime.Now}] [{_logId}]: Receiving messages.");
                Message message = await _client.ReceiveAsync(token);
                return message;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[{DateTime.Now}] [{_logId}]: Receiving messages Failed. Exception: {ex.Message}");
                return null;
            }
        }
        public async Task Close(CancellationToken token)
        {
            await _client.CloseAsync(token);
        }
        public void Dispose()
        {
            _client.Dispose();
        }
    }
}
```

This issue isn't 100% reproducible. Sometimes it needs several iterations to reproduce.
This is only reproducible when AMQP transport is used. Works fine for MQTT transport.

## Console log of the issue
In case of the attempt6 both devices were disconnected.
```
--------------Attempt 5----------------
[11/20/2020 3:11:05 PM] [2]: Connection status changed to: Connected. Reason: Connection_Ok
[11/20/2020 3:11:05 PM] [2]: Receiving messages.
[11/20/2020 3:11:05 PM] [1]: Receiving messages Failed. Exception: Amqp resource is disconnected.
[11/20/2020 3:11:05 PM] [1]: Connection status changed to: Disconnected. Reason: Retry_Expired
Connection status of 1 device: Disconnected
Connection status of 2 device: Connected
--------------Attempt 6----------------
[11/20/2020 3:11:07 PM] [1]: Connection status changed to: Connected. Reason: Connection_Ok
[11/20/2020 3:11:07 PM] [1]: Receiving messages.
[11/20/2020 3:11:07 PM] [2]: Connection status changed to: Disconnected. Reason: Retry_Expired
[11/20/2020 3:11:08 PM] [1]: Connection status changed to: Disconnected. Reason: Retry_Expired
[11/20/2020 3:11:09 PM] [2]: Receiving messages Failed. Exception: error(condition:amqp:resource-locked,description:A link with name 'TelemetryReceiverLink' is already attached in session 2.)
Connection status of 1 device: Disconnected
Connection status of 2 device: Disconnected
```

**Comment by abhipsaMisra** [comment]
Thanks for reporting this.
Let me start by just stating that we do not recommend initializing multiple instances of the same device client, since that will cause the client's transport layer to fight for the connection resources.
Having said that, I don't think you are trying to initialize multiple client instances for the sake of your application, but rather to test the client's resiliency in maintaining an open communication channel; is that correct?

For MQTT, this is pretty straightforward. As soon as you send a 2nd CONNECT packet, service will drop the previously connection connection and establish the new one. This is inherent to MQTT protocol, where you cannot send multiple CONNECT packets for the same connection (between the same pair of client and server).
For AMQP, however, this is not as straightforward, since AMQP has concepts of sessions and links. As per AMQP specs, if you attempt to open a link with the same identifier as a previously opened link, then the previously opened link should be closed with a "link-stolen" error code, and the new link should be opened. For the [AMQP library](https://github.com/Azure/azure-amqp) that the client sdk uses, however, we get a "resource-locked" on the new link that we attempt to open (for the 2nd client instance).

Your test from above seems to show some sort of race condition between the how service responds to the request to open a duplicate amqp connection (with duplicate session and links), and how the client handles the response (I see that you spin up parallel tasks and wait until the first one completes).

I'll need to debug the library logs to be able to conclusively state if this behavior is expected; we'll keep you updated on our findings!

**Comment by anatoliibugaiev** [comment]
Thank you for the quick response. 

Unfortunately this is not a testing situation, but a real life case. 

The device client sdk is used within the protocol gateway

And the connection looks like:

Device —MQTT—> [one of multiple Protocol Gateway instances] —AMQP—> IoTHub

In real life we experience MQTT disconnects as well as reconnect attempts. And it is not predictable which Protocol gateway instance will be chosen. In the case of “flickering” connectivity it is possible that device will connect, disconnect and try to connect again within seconds to the same instance of Protocol Gateway via MQTT 

One more comment regarding timings and race conditions. 

I was able to reproduce this issue with 2 Desktop GUI device simulators by opening 2 windows clicking manually “Connect” button on each simulator. So the delay between these connects was several seconds. Also I waited till the first client establishes connection before connecting second. 

And one more thing. 
I was able to reproduce this using JavaScript SDK too

**Comment by drwill-ms** [comment]
The problem with your architecture, is that the two device instances in the two different gateway instances will continue to fight for connection. Unless you have a way to tell one they are the loser, or have gateway affinity, two instances running will not work.

**Comment by anatoliibugaiev** [comment]
> The problem with your architecture, is that the two device instances in the two different gateway instances will continue to fight for connection. Unless you have a way to tell one they are the loser, or have gateway affinity, two instances running will not work.

This is the architecture, proposed by Microsoft:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-protocol-gateway 
https://github.com/Azure/azure-iot-protocol-gateway/blob/master/README.md

**Comment by drwill-ms** [comment]
I don't see the specific guidance around multiple gateway instances and simultaneous DeviceClient instances. Can you point me directly to where you see that?

**Comment by abhipsaMisra** [comment]
Another question in addition to David's questions above:

> And the connection looks like:
>
> Device —MQTT—> [one of multiple Protocol Gateway instances] —AMQP—> IoTHub

In which part of this architecture do you use the device client? Is that between the device -> protocol gateway part of the communication, which is over MQTT? I believe you've mentioned above (and I've tested it out at my end as well) that MQTT does reliably disconnect the previous connection. Are you trying to implement that first part of the communication over AMQP as well?

Also, instead of calling `ReceiveAsync()` and awaiting on the Task, would setting a [callback](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/DeviceClient.cs#L337) for receiving messages work better for you? The reason I recommend this is, under the hood `ReceiveAsync()` is more of a polling API that waits for messages, whereas a callback is more intuitively suited for this operation.
Also, since you would await the enabling of this callback, you'll see that it will give you a definitive behavior as well (the 2nd connection will always win, with the previous connection getting disconnected).

**Comment by anatoliibugaiev** [comment]
> I don't see the specific guidance around multiple gateway instances and simultaneous DeviceClient instances. Can you point me directly to where you see that?

There is no specific guidance. At the same time, I don't think it was designed to be a single point of failure, being a gateway for the IoT Hub.

However, this problem is reproducible on a single instance and there is no code that checks for existing connections either.

> In which part of this architecture do you use the device client? Is that between the device -> protocol gateway part of the communication, which is over MQTT? I believe you've mentioned above (and I've tested it out at my end as well) that MQTT does reliably disconnect the previous connection. Are you trying to implement that first part of the communication over AMQP as well?

As I said before, our project is the modified version of the GitHub project from Microsoft:
https://github.com/Azure/azure-iot-protocol-gateway/blob/master/README.md 

So the device client is used to establish connection PG -> IoTHub 

More specifically the ReceiveAsync is called here:
https://github.com/Azure/azure-iot-protocol-gateway/blob/master/src/ProtocolGateway.IotHubClient/CommandReceiver.cs

The GitHub version of this project (as well as ours) is still based on version 1.21

We've tried to use the recent version of this SDK and switch to callback and it seems to be a solution in the case of the test client in the console.

That means that we'll need to upgrade the version of SDK and change the way how CommandReceiver listens to the Cloud to device commands in our project.

Thank you for your assistance, I'll post here the results of this attempt.

**Comment by abhipsaMisra** [comment]
Were you able to make any progress @anatoliibugaiev , or do you still see errors at your end?

**Comment by anatoliibugaiev** [comment]
We've prepared the change in our project. So far it looks good and seems that this will solve our problem.
However, proper load testing still required.

**Comment by abhipsaMisra** [comment]
@anatoliibugaiev Do you still need any assistance from us on this issue? If not, we will go ahead and close this in 3 days.
As always, feel free to log a new issue or reopen this if you still see an error.

**Comment by abhipsaMisra** [comment]
Closing this issue since the solution has been discussed above.
@anatoliibugaiev Feel free to reopen this if you have any further questions!

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @anatoliibugaiev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
