### ISSUE TITLE
Clarification on ModuleClient.SendEventBatchAsync overloads

### ISSUE THREAD

**Issue by gimmi** [Azure/azure-iot-sdk-csharp#1687]
For the class `Microsoft.Azure.Devices.Client.ModuleClient` there are 2 overloads of method `SendEventBatchAsync`, with the following description from [the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.sendeventbatchasync?view=azure-dotnet):

1. `SendEventBatchAsync(IEnumerable<Message>)`: Sends a batch of events to IoT hub. Requires AMQP or AMQP over WebSockets.
2. `SendEventBatchAsync(String, IEnumerable<Message>)`: Sends a batch of events to IoT hub

What is unclear to me is:

* Why the first overload "Requires AMQP or AMQP over WebSockets", and the second not?
* What is the `outputName` for the first overload?
* Am I able to use the first overload to send message to other IotEdge modules?

**Comment by vinagesh** [comment]
Here is the answer to 1 -> All overloads are truly batch over AMQP and HTTPS. There is also an implementation for MQTT but it just loops over all the messages and sends them individually. Thanks for reporting this. We will update the documentation.

For 2 & 3, I will get back to you shortly.

**Comment by vinagesh** [comment]
2) There is no output if it is not set. This is optional. But it will determine how you setup routes.
3) Yes you can do that

You can find more details here - https://docs.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-2018-06#declare-routes

The above link shows how to setup routes based on the fact that you have output names defined or not. It has three parts. Source, where clause and sink. 

You can define the source as follows:
Ex: FROM /messages/* INTO $upstream - would pick up anything (output name not necessary)
     /messages/modules/<moduleId>/* - would pick up anything from a specific module (output name not necessary)

The sink can either be another module or the hub

If you want fine grained control on the output queues, you can specify the output name and create routes as follows:
/messages/modules/<moduleId>/outputs/* would pick up anything from a specific module through some output
/messages/modules/<moduleId>/outputs/outputname  would pick up anything from a specific module for a specific output

Let me know if you have further questions.

**Comment by az-iot-builder-01** [comment]
@gimmi, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by vinagesh** [comment]
Closing this issue due to no further questions. Please feel free to reach out again if you have questions.
