### ISSUE TITLE
Unable to receive the Message from Hub

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-csharp#1730]
Hi ,
I am using "https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send" for accessing data from Hub using BlobContainerClient but to my surprise control is not executing after this client (BlobContainer) got initialized.

{

            var consumerGroupName = EventHubConsumerClient.DefaultConsumerGroupName;

            //var consumer = new EventHubConsumerClient(consumerGroupName, eventConnStr, eventName);

            BlobContainerClient blob = new BlobContainerClient(blobStorageConnectionString, blobContainerName);

            EventProcessorClient eventProcessor = new EventProcessorClient(blob, consumerGroupName, eventConnStr, eventName);

            eventProcessor.ProcessEventAsync += EventProcessor_ProcessEventAsync;

            await eventProcessor.StartProcessingAsync();
        }

        private async Task EventProcessor_ProcessEventAsync(ProcessEventArgs arg)
        {
            Console.WriteLine("Data Received {0}\n", Encoding.UTF8.GetString(arg.Data.Body.ToArray()));

            await arg.UpdateCheckpointAsync(arg.CancellationToken);
        }

**Comment by bikamani** [comment]
Hi @Abhi2109 , You may want to check and open issue here: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs

The quickstart and code you mentioned is not something we manage.

**Comment by bikamani** [comment]
Please feel free to re-open if you have any questions for our dotnet SDK.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
