### ISSUE TITLE
[feature request] - API to convert IotHub connection string to Event Hub connection string

### ISSUE THREAD

**Issue by felipepessoto** [Azure/azure-iot-sdk-csharp#1732]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The old Service Bus SDK (WindowsAzure.ServiceBus) supported IotHub connection strings, but the newest SDKs (Azure.Messaging.EventHubs and Microsoft.Azure.EventHubs) doesn't: https://github.com/Azure/azure-sdk-for-net/issues/7175

We need a API to convert IotHub connection string to EH connection string.

**Describe alternatives you've considered**
https://github.com/Azure/azure-sdk-for-net/tree/master/samples/iothub-connect-to-eventhubs

**Comment by bikamani** [comment]
Hi @felipepessoto thanks for submitting feature request.

I run the sample you described and it is basically parsing a connection string to building eventhub connection string using this information 
` return $"Endpoint=sb://{ eventHubsHost }/;EntityPath={ eventHubName };SharedAccessKeyName={ parsedConnectionString.SharedAccessKeyName };SharedAccessKey={ parsedConnectionString.SharedAccessKey }";`

Could you explain some scenarios for which customers would need such API?

**Comment by felipepessoto** [comment]
We use Event Hub SDK to read the data from IoT Hub. So we need to first convert the IotHub connection string to EH connection string.
I'm aware the Azure Portal shows the EH compatible connection string, but I can't copy from there because our process is automatic, and it is also not recommended since the EH conn string changes after fail over:

![image](https://user-images.githubusercontent.com/1336227/103425321-5ba75980-4b90-11eb-9c4c-ff6f82158b0e.png)
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-ha-dr#cross-region-dr

The only way I found to convert it, is using the code in the sample, but that code uses low level APIs, and relies on data from a Exception to retrieve the eventHubsHost and eventHubName. (I believe the sample code was built based on this information: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-amqp-support#receive-telemetry-messages-service-client)

I believe this API would be used for most IotHub customers, unless they are using the EH compatible connection string from Azure Portal, what is not recommended for high availability applications.

**Comment by bikamani** [comment]
Thanks for all the info, we'll take a look and get back on this soon.

**Comment by felipepessoto** [comment]
Hi. Any update on this?

**Comment by bikamani** [comment]
@felipepessoto 
The control plane has a call to get the Event Hub compatible connection string. We don’t have support in the data-plane for it, because the Hub doesn’t provide that in the REST API.

**Comment by felipepessoto** [comment]
Thanks @bikamani
