### ISSUE TITLE
GetNextAsTwinAsync throws "No such host is known" exception if hostname have dash in the name

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-csharp#1739]
# Context

- **OS:** Windows 10 Desktop x64 & Azure web app (windows)
- **Application's .NET Target Framework :**  netcoreapp3.1
- **Device:** N/A
- **SDK version used:** 1.20.1 & 1.28.1

## Description of the issue
Calling `GetNextAsTwinAsync` throws "No such host is known" exception using a connection string with host name with a dash such as "foo-bar.azure-devices.net".

## Code sample exhibiting the issue
```csharp
using Microsoft.Azure.Devices;
using System;
using System.Threading.Tasks;

namespace ConsoleApp10
{
    class Program
    {
        static RegistryManager registryManager;
        static string connectionString = "HostName=foo-bar.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=...";
        static void Main(string[] args)
        {
            Test().Wait();
            Console.WriteLine("Hello World!");
        }

        static async Task Test() {
            try
            {
                var registryManager = RegistryManager.CreateFromConnectionString(connectionString);
                var query = registryManager.CreateQuery("SELECT * FROM devices WHERE tags.location.plant = 'Redmond43'", 100);
                var twinsInRedmond43 = await query.GetNextAsTwinAsync(); // This line fails
            }
            catch (Exception e) {
                Console.WriteLine(e.Message);
            }
        }
    }
}

```

**Comment by abhipsaMisra** [comment]
@wmmihaa I am unable to reproduce this issue. If I try to run a query against a hub with a hyphen in its hostname, and then iterate over the returned twins, I am able to do so successfully.
Can you confirm that the hub that you are trying to connect to does actually exist?
If you run the same application against a hub with only alphabets in its name, are you able to do so successfully then?

**Comment by wmmihaa** [comment]
@abhipsaMisra I've tried several iot hubs an they all fail. I can send you the connectionstring through an email or dm if you want.

**Comment by az-iot-builder-01** [comment]
@wmmihaa, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
