### ISSUE TITLE
[Bug Report] Exception while handling a null value in the array of reported properties

### ISSUE THREAD

**Issue by ggjjj** [Azure/azure-iot-sdk-csharp#1741]
I am filing this issue as one of customer faced this problem and details documented here: https://github.com/Azure/iotedge/issues/4159 

- **OS, version, SKU and CPU architecture used:** 
  - Host OS: debian9
  - Architecture: arm32
  - Container OS: Linux containers
- **Application's .NET Target Framework :** netcoreapp3.1
- **SDK version used:** 1.28.0 

## Description of the issue
The null value in arrays of reported properties in the modules causes an exception in Edgehub module using C# SDK .

## Code sample exhibiting the issue
Please refer to the linked issue.

## Console log of the issue
Please refer to the linked issue.

**Comment by ggjjj** [comment]
@GaryHsu77  could you update the device type here?

**Comment by abhipsaMisra** [comment]
It looks like this error is being returned from IoT hub service. I've reached out to the service team for clarification.

Request: 
{"a":[{"b":null}]}     

Response: 
{"errorCode":400004,"trackingId":"c3c3df4720ff47e58bf8d37c750f7ccb-G:7-TimeStamp:01/12/2021 22:23:43","message":"Value of Property or Tag cannot be null. Error inProperty/Tag b","timestampUtc":"2021-01-12T22:23:43.6426124Z"}

**Comment by abhipsaMisra** [comment]
Received confirmation from the service team: This is by design. Null values are not allowed inside arrays.

**Comment by az-iot-builder-01** [comment]
@ggjjj, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by imZack** [comment]
Thanks for the update.

@abhipsaMisra @ggjjj What's the purposed way to do things like this?

Also, can you help me to find where I can find this design in the [documents](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format). Thank you.

**Comment by abhipsaMisra** [comment]
@imZack This is currently a restriction of the way twin patching currently works on the service-side. Array values are replaced as a single entity, so it is not possible to update an object within in array as null. If an array property value needs to be removed, the entire property will need to be updated as null, eg: {"a": null}

Our service team is currently working to get the documentation updated accordingly.

**Comment by imZack** [comment]
I was expecting the object in the array should be an immutable entity. Therefore, the cloud service or the IoT SDK shouldn't look into or try to interpret the key/value of the object in the array but replacing the entire object instead. This is also based on our experience when we use other libraries/utility for things like this before.

Our edge module application can avoid this by removing all the keys with null values before updating the Twin by iterating the object in the array when the data arrived.

**Comment by abhipsaMisra** [comment]
You are correct, the sdk does not inspect any value that you provide for your properties, but instead, directly passes it through to the service. It is then the service's responsibility to patch/ update the twin with the supplied properties.

**Comment by abhipsaMisra** [comment]
@imZack Just to provide an update here: our service team is investigating if allowing null in arrays is something the service implementation can/ could support. If they come up with a workaround for this I'll let you know.

**Comment by imZack** [comment]
@abhipsaMisra Thank you for the update! That sounds promising.

**Comment by imZack** [comment]
@abhipsaMisra Any further updates for this one?

**Comment by abhipsaMisra** [comment]
@imZack Unfortunately no, I don't have any further update from the service team. Since it could take a while to get prioritization on this; it wouldn't hurt to add this as a feature request on [User Voice](https://feedback.azure.com/forums/321918-azure-iot).

**Comment by imZack** [comment]
Just checked https://feedback.azure.com/forums/321918-azure-iot-hub-dps-sdks/suggestions/20162305-support-arrays-for-tags-in-device-twins and looks like on one is updating the feedback actively... we'll see.

**Comment by florianbader** [comment]
+1 on this. It is really strange that we can provide objects to the twin which contain null properties but objects in array cannot contain null properties.
