### ISSUE TITLE
How to Mock ServiceClient for testing purpose.

### ISSUE THREAD

**Issue by yesidbalvin** [Azure/azure-iot-sdk-csharp#1761]
Is it possible to mock the ServiceClient in order to test methods like
```
var notificationReceiver = _serviceClient.GetFileNotificationReceiver();
var fileUploadNotification = await notificationReceiver.ReceiveAsync(_notificationReceiverTimeOut);
```
We tried to wrap the ServiceClient and we tried to mock it directly `Mock<ServiceClient>` getting errors.

We also tried to use the class `AmqpServiceClient.cs` but it was not possible to implement it due to this error, _azure.devices "serviceclient" does not contain a constructor that takes 0 arguments_

Thanks in advance.

**Comment by abhipsaMisra** [comment]
Our service client is currently not mockable, in that we don't expose an interface that you could mock. The initial reasoning behind this approach was that the API surface could change in the future, which meant the interface would require updates; which in turn would break people who've previously implemented this interface in their code.
There are definitely ways to work around this, but we haven't had any compelling reason yet to revisit this approach.

> We tried to wrap the ServiceClient and we tried to mock it directly `Mock<ServiceClient>` getting errors.

This would generally be our recommended approach for mocking/ unit testing such types, can you elaborate a bit on the error that you're seeing here?

**Comment by dserranoaPsl** [comment]
@abhipsaMisra The way that we are using is trying to wrap the base class ServiceClient. However, when we try to do this, we are getting that error: 
![image](https://user-images.githubusercontent.com/68237404/106334583-f8751980-6258-11eb-9175-ec7c52b36e48.png)

Even we have tried to use the same AmqpServiceClient.cs class that you used in your tests but we are getting the same error.

What other aproach can we use here?

**Comment by 2x01101110** [comment]
Implement base class with connection string?

**Comment by 2x01101110** [comment]
Can confirm, latest version of the SDK,

**Comment by yesidbalvin** [comment]
> Can confirm, latest version of the SDK,

Hi, we are using the latest one. 1.29.0

**Comment by vinagesh** [comment]
We are trying to make this class easy to mock. In the meantime, here is an approach you can try:

`
public abstract class ServiceClient
    {
        public static ServiceClient Create()
        {
            return new AmqpClient();
        }
        public abstract string func1();
        public abstract string func2();
    }
internal class AmqpClient : ServiceClient
    {
        public AmqpClient()
        {
        }
        public override string func1()
        {
            return "func1";
        }
        public override string func2()
        {
            return "func2";
        }
    }
public interface ICustomerServiceClient
    {
        string func1();
        string func2();
    }
public class CustomerImplementationClient : ICustomerServiceClient
    {
        private ServiceClient _client;
        public CustomerImplementationClient()
        {
            _client = ServiceClient.Create();
        }
        public string func1()
        {
            return _client.func1();
        }
        public string func2()
        {
            return _client.func2();
        }
    }
public class MyTest
    {
        [Test]
        public void MyTest1()
        {
            var client = new Mock<CustomerImplementationClient>();
            client.Setup(x => x.func1()).Returns("myfunc1");
            client.Setup(x => x.func2()).Returns("myfunc2");
        }
    }
`

**Comment by vinagesh** [comment]
@yesidbalvin - We have released a version of our clients that is mockable now - https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-6-8
Please let us know if this works well for you. We are looking forward to hear feedback.

**Comment by abhipsaMisra** [comment]
Closing the issue.
