### ISSUE TITLE
Sending an IoT Hub  message that is too large creates different behavior between AMQP and MQTT

### ISSUE THREAD

**Issue by barnstee** [Azure/azure-iot-sdk-csharp#1766]
# Context

## Description of the issue
Sending an IoT Hub  message that is too large creates different behavior between AMQP and MQTT:
1. When using AMQP as transport, you get an exception with a useful error message
2. When using MQTT as transport, the SendEventAsync() hangs indefinitely :-(

## Code sample exhibiting the issue
bytes[] buytesToSend = new byte[260]; // too large
Message hubMessage = new Message(bytesToSend);
hubMessage.ContentType = "application/json";
hubMessage.ContentEncoding = "UTF-8";
 _deviceClient.SendEventAsync(message, cancellationToken).ConfigureAwait(false);

## Console log of the issue
Consider setting the DEBUG environment variable to '*'. This will produce a much more verbose output that will help debugging
Don't forget to remove any connection string information!

**Comment by jamdavi** [comment]
Hey @barnstee is this happening on the latest SDK?

**Comment by barnstee** [comment]
Yep. I have a repro if you want to see it...

**Comment by jamdavi** [comment]
Thanks, I'm definitely gonna need a full repro. I tried the code in the description with a simple device and it did not hang.

**Comment by timtay-microsoft** [comment]
> bytes[] buytesToSend = new byte[260]; // too large

IoT Hub allows messages up to 256 kB, so I'm surprised that 260 byte messages hit an error message even in AMQP. Shouldn't this line be "new byte[260 * 1000];"?

**Comment by barnstee** [comment]
It should yes. Please reach out to me internally and I can show you a repo with our product.

**Comment by barnstee** [comment]
Can you please add an explanation why you closed the issue? This will help customers understand if it is fixed or not.
