### ISSUE TITLE
Remove localization from projects.

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#177]
We have no plans to localize the SDKs but we do have some of the libs using localization constructs. This is to track removal of the following form all projects:
- [ ] Resources.Designer.cs
- [ ] Resources.resx
- [ ] Update csproj files accordingly

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and we will consider it as part of our planning cycle

**Comment by az-iot-builder-01** [comment]
@CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
