### ISSUE TITLE
DeviceClient.Dispose() does not close socket connections

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-iot-sdk-csharp#1770]
I'm using Microsoft.Azure.Devices.Client 1.34.0 (the latest). It looks like this issue is back: https://github.com/Azure/azure-iot-sdk-csharp/issues/1098

To put it short: when DeviceClient.Dispose() is called, underlying socket connections remain open. Those are to our IoT Hub, port 6571.

This started to happen after updating from 1.33.1 and is wreaking havoc on our service. I see that 1.34.0 changelog has a bunch of "dispose"-related fixes, so one of those might be to blame here.

**Comment by vinagesh** [comment]
Thanks for reporting. We will take a look at it.

**Comment by jamdavi** [comment]
Thanks @dmytro-gokun I have a fix in PR, you'll have to downgrade to 1.33.1 to get around this issue.

**Comment by vinagesh** [comment]
We will update this thread about the SDK version with the fix as soon as it is released.

**Comment by jamdavi** [comment]
@dmytro-gokun We have released this fix today, you can get the latest release from NuGet

https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-02-08

https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.35.0

**Comment by dmytro-gokun** [comment]
@jamdavi Thanks for the quick fix!
