### ISSUE TITLE
[MS Docs] FeedbackReceiver vs FileNotificationReceiver

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#1808]
This issue was reported by @plillevold.  Please be sure to include them on any response.
---

The return text mentions incorrect return type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e98f62c-0dc0-8324-3bbb-0889d15153d9
* Version Independent ID: 19eb1d52-79ce-c4e0-d24b-51641ca7aa28
* Content: [ServiceClient.GetFileNotificationReceiver Method (Microsoft.Azure.Devices)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient.getfilenotificationreceiver?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Devices.ServiceClient.GetFileNotificationReceiver);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices/ServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices/ServiceClient.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by bikamani** [comment]
@plillevold Thank you for filing the issue. We will fix the documentation.

**Comment by abhipsaMisra** [comment]
The comments have now been updated, closing this issue: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-03-18
