### ISSUE TITLE
Enable FXCop for existing projects

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#181]
We would like to enable the following for Hub projects:
- [ ] Treat warnings as errors (`<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` )
- [ ] FXCop: (`<Features Condition=" '$(Configuration)' == 'Debug' ">IOperation</Features>` and `<PackageReference Condition=" '$(Configuration)' == 'Debug' " Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1" />`)
- [ ] SDL and CodeScanning Plugins to VSTS

This requires investigating and fixing all existing warnings.

**Comment by sharmasejal** [comment]
All our projects now have FXCop enabled.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
