### ISSUE TITLE
[feature request] Add option to set SAS token expiration for the ModuleClient.CreateFromEnvironmentVariable() flow.

### ISSUE THREAD

**Issue by maskimthedog** [Azure/azure-iot-sdk-csharp#1818]
In the Azure IoT Hub C SDK, the method below is available to set the default SAS token lifetime.  No such method is present in the Azure IoT Hub C# SDK.  I have to patch the code to set the hardcoded 60 minute expiration to something more tolerable data usage wise for cellular networks.  Please consider adding such a method.

```
size_t sas_token_lifetime = SAS_TOKEN_LIFETIME_SECONDS;
if (IOTHUB_CLIENT_OK != IoTHubClient_LL_SetOption(g_device->iotHubClientHandle, OPTION_SAS_TOKEN_LIFETIME, &sas_token_lifetime))
{​​​​​​​
    msg_error("failure to set option \"sas_token_lifetime\"\r\n");
}​​​​​​​
```

**Comment by abhipsaMisra** [comment]
Rather than configure the sas token's lifespan on an option on the client, we have the following authentication abstract class that you can implement, where you will be able to set custom values for the sas token's time to live and also the buffer percentage after which a token should be renewed: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/DeviceAuthenticationWithTokenRefresh.cs
Would this work for you?

**Comment by maskimthedog** [comment]
I totally understand that and I know how to use it.  However, your API method for establishing a connection to IoT Hub uses the constructor with the default TTL and percentage.  There is no way to change this without modifying the SDK unless MS provides a way to override so that the SAS token does not expire after the default 60 minutes and invalidates the connection to where it must be re-established.

**Comment by abhipsaMisra** [comment]
I think I might be misunderstanding your scenario. Could you help me understand it so that I can assist you better.

>  your API method for establishing a connection to IoT Hub uses the constructor with the default TTL and percentage

My understanding is that you would like to initialize a device client that has its sas tokens expire at a different frequency than the one hardcoded within the client (i.e. 1 hour). By default, if you initialize the device client using connection string, it will generate sas tokens that are valid for an hour. To override this behavior, you can implement the abstract class `DeviceAuthenticationWithTokenRefresh` and pass it to the device client `Create` method for initialization.

```csharp
internal class DeviceAuthenticationSasToken : DeviceAuthenticationWithTokenRefresh
{
    private readonly IotHubConnectionStringBuilder _connectionStringBuilder;

    public DeviceAuthenticationSasToken(
        string connectionString,
        int suggestedTimeToLiveSeconds,
        int timeBufferPercentage)
        : base (GetDeviceIdFromConnectionString(connectionString), suggestedTimeToLiveSeconds, timeBufferPercentage)
    {
        if (connectionString == null)
        {
            throw new ArgumentNullException(nameof(connectionString));
        }

        _connectionStringBuilder = IotHubConnectionStringBuilder.Create(connectionString);
    }

    protected override Task<string> SafeCreateNewToken(string iotHub, int suggestedTimeToLive)
    {
        // sas token generation logic here
    }
}

// In your application
using var auth = new DeviceAuthenticationSasToken(connectionString, 120, 50);
var builder = IotHubConnectionStringBuilder.Create(connectionString);

using var deviceClient = DeviceClient.Create(
    builder.HostName,
    auth,
    TransportType.Mqtt);
```

This would set your supplied ttl and renewal buffer percent to the client, and those values will be used to determine the sas token expiration and renewal time.

Does this address your scenario?
If not, could you provide an explanation of the scenario that you are trying the achieve and the limitation that you are facing.

**Comment by maskimthedog** [comment]
My application uses DPS to acquire a connection string, I left out that critical detail  I understand how to accomplish with a known IoT Hub connection string.

**Comment by maskimthedog** [comment]
By the way, thanks for your quick response.

**Comment by abhipsaMisra** [comment]
Not a problem, does this resolve your issue? Is there anything else that I can help you with?

**Comment by maskimthedog** [comment]
Not really, I am connecting via three IoT Edge modules, so I think I need to use ModuleAuthenticationWithTokenRefresh with connection string derived from...


```
private const string EdgehubConnectionstringVariableName = "EdgeHubConnectionString";
private const string IothubConnectionstringVariableName = "IotHubConnectionString";
.
.
.
private static string GetValueFromEnvironment(IDictionary envVariables, string variableName)
{
    return envVariables.Contains(variableName)
        ? envVariables[variableName].ToString()
        : null;
}
.
.
.
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_WebSocket_Only);
mqttSetting.KeepAliveInSeconds = 15 * 60;
ITransportSettings[] settings = { mqttSetting };

IDictionary envVariables = Environment.GetEnvironmentVariables();

string connectionString = GetValueFromEnvironment(envVariables, EdgehubConnectionstringVariableName) ?? GetValueFromEnvironment(envVariables, IothubConnectionstringVariableName);
```

**Comment by abhipsaMisra** [comment]
You can either use the device connection string (after having modified it to include the edge gateway hostname) or can provide the IoT Hub hostname, the edge gateway hostname and token generation specifications to your authentication method, and use that for your client initialization. You should then be able to communicate to edge hub using sas tokens with custom expiration time.

In the meanwhile, if you don't mind, I will repurpose this issue track a workitem to make sas tokens configurable via the `CreateFromEnvironment()` flow as well.

**Comment by maskimthedog** [comment]
_"In the meanwhile, if you don't mind, I will repurpose this issue track a workitem to make sas tokens configurable via the CreateFromEnvironment() flow as well."_

This would be a much welcome solution!

**Comment by asergaz** [comment]
Adding a cross link with a related thread in StackOverflow: https://stackoverflow.com/questions/65619913/iot-net-sdk-is-there-a-way-to-set-the-sas-token-life

**Comment by maskimthedog** [comment]
I was able to successfully able to override in order to connect individual modules to cloud.  However, module to module connectivity cannot be realized anymore.  I looked at the source behind the CreateFromEnvironment method and it is a lot more involved.  My only recourse then is to wait until the CreateFromEnvironment method is enhanced to allow specification of SAS token expiration.

**Comment by abhipsaMisra** [comment]
This feature has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-04-26

**Comment by maskimthedog** [comment]
Thank you so much for turning this over quickly.
