### ISSUE TITLE
[Bug Report] Semaphore release mismatch in InternalClient.cs

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#1821]
The implementation of SetMethodHandlerAsync() in InternalClient.cs seems to have an error that may cause releasing the semaphore (used as a lock) acquired by a different (logical) thread:

```
        public async Task SetMethodHandlerAsync(string methodName, MethodCallback methodHandler, object userContext, CancellationToken cancellationToken)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
   1)           await _methodsDictionarySemaphore.WaitAsync(cancellationToken).ConfigureAwait(false);

                // ... code removed for brevity 
            }
            catch (IotHubCommunicationException ex) when (ex.InnerException is OperationCanceledException)
            {
                cancellationToken.ThrowIfCancellationRequested();
                throw;
            }
            finally
            {
                try
                {
    2)            _methodsDictionarySemaphore.Release();
                }
    3)          catch (SemaphoreFullException)
                {
                    // this semaphore is typically grabbed at the start of the method, but if
                    // this method is canceled while waiting to grab the semaphore, then this semaphore.release
                    // will throw this SemaphoreFullException since it was never grabbed in the first place
                    if (Logging.IsEnabled)
                    {
                        Logging.Info(this, "SemaphoreFullException thrown while releasing methods dictionary semaphore, but will be ignored since that means the semaphore is available for other threads to grab again anyways");
                    }
                }                
            }
        }

```

Let's say, that a call on logical thread A) was made to this method, it acquired the semaphore and now it is working inside 'EnableMethodAsync()' or 'DisableMethodAsync()' (removed from the code above, but you can see it in the original code). Note, that although those calls pass 'cancellationToken', inside their implementation in case of Amqp they switch to an 'operationTimeout'. I mention this to emphasize that the call not necessarily will interrupt when the cancellationToken gets cancelled.

Now let's say that this operation takes really long and in the meantime a new call on thread B) is made. This call blocks on 1) and keeps hanging for a while, but eventually the cancellationToken cancels, so on Thread B) an exception will interrupt this call and lands in the 'finally' block.

Now on thread B) it executes a Release() call on the semaphore. Because earlier Thread A) decreased the counter of the semaphore, there is room to release it once, so this call will not fail (and does not get to 3) ). 

In this case if a tread C) makes a call into this function, at 1) it will be able to acquire the semaphore again, although Thread A) is still doing its job. Now bot Thread A) and Thread C) act in the same method despite it is protected by the lock.

This problem was discovered by an actual error analyzing the exception pattern, so the problem is not theoretical. We have a case when a call keep hanging (will be submitting a bug report about that soon), and as the caller times out, it retries and retries, where the second retry passes through the  semaphore (and fails at a different place later)

**Comment by timtay-microsoft** [comment]
Looks like you are right. I'll try to get this fixed shortly

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Microsoft.Azure.Devices.Client 1.36.0, so I'm closing this issue.
