### ISSUE TITLE
Connection with DeviceAuthenticationWithSharedAccessPolicyKey is failing

### ISSUE THREAD

**Issue by aribeironovaes** [Azure/azure-iot-sdk-csharp#183]
When Trying to connect using a DeviceAuthenticationWithSharedAccessPolicyKey, I'm getting the following exception: 
![image](https://user-images.githubusercontent.com/9369967/31400339-18a68a6c-ada4-11e7-82e4-b4705c63e83f.png)

Code that reproduces the problem: 
                IAuthenticationMethod sharedAccessKey = new DeviceAuthenticationWithSharedAccessPolicyKey("<your device id here>", "<your policy name here>", "<your key here>");
                DeviceClient deviceClient = DeviceClient.Create("<your hostname here>", sharedAccessKey);

                SendEvent(deviceClient).Wait();

**Comment by aribeironovaes** [comment]
An Update on this. This API is not application for the Device SDK, so this needs to be removed. 
PolicyName just makes sense for the Service SDK.

**Comment by CIPop** [comment]
@aribeironovaes I've tested and this works fine as long as you use the matching policy name and respective key.

I tried "iothubowner" and "device" and both worked as expected.

![image](https://user-images.githubusercontent.com/8635911/31746313-a3e928e6-b41b-11e7-829d-b8ec0d3a74ff.png)
