### ISSUE TITLE
Reopen Issue #56 - UWP - Exception thrown with message "Transient error occured, please retry" 

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-sdk-csharp#184]
The problem is still occurring **randomly** even though network connectivity is OK and the protocol selected is MQTT. Additionally the problem occurs **during** operation so there is no problem with the connection string. Apparently there is something else triggering it.  One scenario where we have managed to reproduce the event is as follows: 
protocol MQTT
more than one  simultaneous connections to same azure iot hub device.

**Comment by CIPop** [comment]
Thanks for reporting @mtheolog. I have reopened #56 - let's continue the discussion there.
