### ISSUE TITLE
[feature request] Graceful handling for IoT Hub failover

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-sdk-csharp#1844]
**Is your feature request related to a problem? Please describe.**

When the IoT Hub failover occurs, the built-in Event Hubs endpoint changes. The [documentation](https://github.com/MicrosoftDocs/azure-docs/blob/b5a3782c9a1f8b0b231ad84c51a363ff7724ef27/articles/iot-hub/iot-hub-ha-dr.md#cross-region-dr) has suggestion to to use the IoT Hub connection string to establish the connection.

As the discussion under [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/64272) indicates, it is not straightforward how to achieve this in a programmatic way with the current SDKs.

There are samples for different programming languages how to do a single-shot fetch of the Event Hubs endpoint such as [this for dotnet](https://github.com/Azure/azure-sdk-for-net/blob/da17d96002766d75e30292de3e50035d295ad62c/samples/iothub-connect-to-eventhubs/Program.cs#L56).

What the samples are missing is how to continuously monitor the changes and perform the failover in a way that it minimize the downtime.

**Describe the solution you'd like**

From end user perspective, a useful feature in the IoT Hub SDK would be to gracefully handle the failover. This could be a wrapping over the Event Hubs SDK so that the user wouldn't loose any of the APIs exposed there, but would gain handling for failover.

The second best option would be clear guidance and best practices how to achieve graceful handling if implementing it with a custom implementation. For example, sequence diagrams that would show which errors to subscribe to and in which order to instantiate and dispose the Event Hub consumers.

**Describe alternatives you've considered**

There are at least two ways to become aware of the failover and to get the built-in Event Hub endpoint:

1. [Via the AMQP protocol](https://github.com/Azure/azure-sdk-for-net/blob/da17d96002766d75e30292de3e50035d295ad62c/samples/iothub-connect-to-eventhubs/Program.cs#L56)
2. [Via monitoring the IoT Hub Azure resource](https://github.com/martin-weber/iothub-failover-findings/blob/823bccef8583e6f66669abf6a4172efe959e1fd3/samples/IoTHubObserver/IoTHubObserver/Program.cs#L42)

The two approaches has pros and cons, for example, related to how fast and reliably the failover can be detected and what kind of permissions the detection requires.

If different solution are applicable to different scenarios, these considerations would be good to document as well.

**Additional context**

This repository [https://github.com/martin-weber/iothub-failover-findings](https://github.com/martin-weber/iothub-failover-findings) has good additional details about what happens during failover both from the device and service perspective.

**Comment by bikamani** [comment]
@vjrantal Thanks for your request. We will look at it and get back to you soon.

**Comment by drwill-ms** [comment]
@vjrantal Thank you for sharing your findings. They are quite interesting.

We're aware of the issues with hub failover for the built-in event hub endpoint, and the Hub team is looking at redesigning how they use event hub to make failover seamless.

In the meantime, you are right that those two options you listed are the way to do it. That is all we'd be able to do if we wrapped the event hub SDK, so that isn't better.
