### ISSUE TITLE
Build error in .NET Core 2 console application using RegistryManager.GetTwinAsync("") or RegistryManager.UpdateTwinAsync("")

### ISSUE THREAD

**Issue by edchapel** [Azure/azure-iot-sdk-csharp#186]
* What SDK are you using (Node, C, C#, Python, Java?)
  **C#**
* What version of the SDK?
  **Microsoft.Azure.Devices 1.4.0 for .NET Core 2**
* Do you have a snippet of code that would help us reproduce the bug?
  **https://github.com/edchapel/bug-microsoft.azure.devices-.netcore2**
* Do you have logs showing what's happening?
  **Yes, see build error below**

### Unable to use the Azure IoT Hub `RegistryManager` to get or update Twin data from .NET Core 2.

For a new .NET Core 2 console application, using `RegistryManager.GetTwinAsync("")` or `RegistryManager.UpdateTwinAsync("")` results in a build error.

Steps to reproduce:

1. Create new .NET Core 2 console application
1. Install 'Microsoft.Azure.Devices' NuGet package (v1.4.0)
1. Add usage of `RegistryManager.GetTwinAsync("")` or `RegistryManager.UpdateTwinAsync("")`.

```
using System;

using Microsoft.Azure.Devices;

namespace IoTHubService
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var manager = RegistryManager.CreateFromConnectionString("");
            var twin = manager.GetTwinAsync("").Result;
        }
    }
}
```

The solution now fails to compile with the error:

```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,24): error CS0012: The type 'Twin' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [C:\Users\edchapel\source\IoTHubService\IoTHubService.csproj]
Program.cs(13,49): error CS0012: The type 'Twin' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [C:\Users\edchapel\source\IoTHubService\IoTHubService.csproj]

Build FAILED.

Program.cs(13,24): error CS0012: The type 'Twin' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [C:\Users\edchapel\source\IoTHubService\IoTHubService.csproj]
Program.cs(13,49): error CS0012: The type 'Twin' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [C:\Users\edchapel\source\IoTHubService\IoTHubService.csproj]
    0 Warning(s)
    2 Error(s)
```

I also tried installing the 'Microsoft.Azure.Devices.Shared' 1.1.1 NuGet package explicitly. However, this had no effect.

**Comment by jasmineymlo** [comment]
@edchapel Thanks for filing this issue.  Update to the latest Microsoft.Azure.Devices (1.5.0) should fix it.  Please reopen this if you find the same issue after upgrading.
