### ISSUE TITLE
Direct Methods support

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-sdk-csharp#19]
Are direct methods already supported in C# SDK (service + client) ?

**Comment by damonbarry** [comment]
Yes!

**Comment by v-tbert** [comment]
Correct me if I am wrong, but they are NOT supported in C# UWP, correct?

**Comment by damonbarry** [comment]
@tameraw?

**Comment by olivierbloch** [comment]
Correct, the MQTT support for UWP is in development and is required for Twins and Methods. Stay tuned

**Comment by SeanStayn** [comment]
Correct me if I am wrong, but they are NOT supported in C# PCL/Xamarin.Android, as well, correct? If I use Mqtt as TransportType, then device.OpenAsync().Wait(); cause a deadlock..

**Comment by CIPop** [comment]
@nbhargava123 we're not monitoring closed issues. In general, please open new issues to ensure you are getting answers.

> Is direct method supported in C# UWP now?

They should be after the last release. Let us know if you see any issues.

**Comment by ddobric** [comment]
Are direct methods still supported on MQTT only or we have in the mean time more options around AMQP, websockets,..
