### ISSUE TITLE
IoTHub device client not scalable.

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#190]
I have created an Iot edge gateway with a module that connects to Iothub. I have thousands of devices that don't send a lot of data but need to be constantly monitored. Iothub's model is to have every physical device represented as a logical device twin in iothub. So to connect the physical device to its twin, the device client ends up creating thousands of MQTT connections rather than using one network connection and having the endpoints handle it as needed. This would seem to create a scalabilty problem for anyone with a lot of devices going through gateways. Is there an established way to deal with this problem?

**Comment by tameraw** [comment]
@v-tbert - Currently we do not support multiplexing over MQTT. For your Edge scenario, it is recommended that you use AMQP which offers you multiplexing.

**Comment by v-tbert** [comment]
AMQP does not support device methods and other IoTHub functionality does it?

**Comment by ryan-z-johnson** [comment]
![image](https://user-images.githubusercontent.com/29990023/32621709-85142f1c-c535-11e7-8389-42092c8a3ccc.png)

We support  Device methods, twins, sending, and receiving messages over AMQP.

**Comment by v-tbert** [comment]
Don't know when that changed but that is the best news I have heard all day, thanks!

**Comment by v-tbert** [comment]
How do I re-open this? AMQP seems to be limited to multiplexing 10 devices in the latest RTM build.

**Comment by yzhong94** [comment]
@v-tbert we do not monitor closed issues.  Please open a new issue instead.  Thanks!
