### ISSUE TITLE
[Bug Report] Throw exception when using a non supported feature by protocol

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-sdk-csharp#1917]
Based on the feature matrix available [here](https://github.com/Azure/azure-iot-sdk-c#device-client-sdk)

I would expect the SDK to signal users when using a protocol with a non supported feature, eg the code below does not fail but does not perform any action

```cs
 var dc = DeviceClient.CreateFromConnectionString(<connectionString>, TransportType.Http1);
 TwinCollection reported = new TwinCollection();
 reported["status"] = "connected";
 await dc.UpdateReportedPropertiesAsync(reported);
```

Other cases when using HTTP (not limited to)
- Subscribing to DirectMethods
- Subscribing to DesiredPropertiesUpdates
- Announcing the Model ID

**Comment by abhipsaMisra** [comment]
This is a valid expectation. The only caveat here is that throwing an exception now would technically be a "breaking change", so we'd need to discuss this internally. 
We will either throw an exception for unsupported scenarios or document it explicitly in the API call signature.

**Comment by bjorn-jarisch** [comment]
Another important case that's completely ignored via HTTP:

* Updating reported properties

**Comment by rido-min** [comment]
@bjorn-jarisch this is the main case reported in this issue (look at the sample code). Are you referring to something else?
