### ISSUE TITLE
CreateFromConnectionString is failing if DeviceID has Semicolon (e.g.: DeviceName;1) 

### ISSUE THREAD

**Issue by aribeironovaes** [Azure/azure-iot-sdk-csharp#192]
If you create a device (using device explorer), that contains a semicolon on the name, get the connection string and tries to connect using the Device SDK, it raises an exception: 
Error in sample: Malformed Token. 

Workout around for this problem is to use Token directly (By Generating the token on Device Explorer). 

Thanks, 

Angelo Ribeiro.

**Comment by CIPop** [comment]
/cc @yzhong94 From the service side changing this would be a breaking change.

@aribeironovaes Are you able to create a device using the alternate [DeviceClient.Create ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.create?view=azure-dotnet#Microsoft_Azure_Devices_Client_DeviceClient_Create_System_String_Microsoft_Azure_Devices_Client_IAuthenticationMethod_) factory method?

**Comment by CIPop** [comment]
@yzhong94 @tameraw @simonporter @pierreca 
Closing: won't fix per internal decision. 

This is a corner case that can easily be avoided by not having devices containing ";" within the name when connection strings are used.
