### ISSUE TITLE
[Technical Question] Microsoft.Azure.Devices.Message.MessageSchema Property

### ISSUE THREAD

**Issue by Mikako-ff** [Azure/azure-iot-sdk-csharp#1953]
Sadly, according to information from the Azure Devices and IoT Support Team (TrackingID#2105110060000151), 
the "MessageSchema" property is not officially supported and should not be used.

Is there any documentation somewhere?

We implemented a server / client application using the "MessageSchema" property.
Now trying to implement the Java client, the SDK does not have the corresponding property,
If I use "iothub-message-schema" to make up, I can send but not receive (it becomes $ .schema instead).

**Comment by abhipsaMisra** [comment]
The message schema property "iothub-message-schema" does get translated to "$.schema" when written over the wire on MQTT. As for the official guidance and documentation, we'll need to reach out to the service team and docs team respectively. We'll use the tracking Id that you've shared above and get the resolution on this.
In the event of a particular system property not being officially supported, would it work for you to set an application property on your IoT Message, and use that for correlating and routing messages between your device and service: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct

"Application properties: A dictionary of string properties that the application can define and access, without needing to deserialize the message body. IoT Hub never modifies these properties."

**Comment by Mikako-ff** [comment]
Does "Application Properties" mean the same as "Microsoft.Azure.Devices.Message.Properties"?

**Comment by abhipsaMisra** [comment]
Yes, you are correct.

**Comment by vinagesh** [comment]
@Mikako-ff - I just wanted to confirm if the "Application properties" is working for you and this issues is resolved.

**Comment by Mikako-ff** [comment]
@vinagesh
"Application properties" is working well. 
Thank you.

**Comment by vinagesh** [comment]
Thank you for reporting this issue. The best way forward for you is using the "Application properties", which seems to be working well. If you face any other problems, please feel free to open a new issue..
