### ISSUE TITLE
[Bug Report] Cannot use a proxy inside a custom iotedge module

### ISSUE THREAD

**Issue by xela-95** [Azure/azure-iot-sdk-csharp#1956]
## Expected Behavior
I would like to make my custom iotedge module, named DeviceMonitor to connect to IoTHub using a static proxy configured on the host PC.

## Current Behavior
My module is not able to connect to IoTHub.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create the deployment manifest
2. Deploy iotedge on the PC
3. edgeAgent pulls my module
4. my module chrashes since it cannot connect to IoTHub to retrieve desired properties.

## Context (Environment)
Proxy is in the format http://url:port (no authentication); 
The module, called DeviceMonitor,  is developed in C# .NET Framework 4.7 and it uses SDK .NET to communicate with IoTHub.
My module , needs to access to some configuration Apis on Azure using:
```
var handler = new HttpClientHandler();
handler.DefaultProxyCredentials = System.Net.CredentialCache.DefaultCredentials;
```
Moreover, it needs to access to IoT Hub with several methods according with the operation it need to accomplish:

Microsoft.Azure.Devices.RegistryManager 
Microsoft.Azure.Devices.Client.DeviceClient 
Microsoft.Azure.Devices.Client.ModuleClient

**The major question here is: How can I be sure that all the connections attempted inside my module will go through the proxy? Do I have to modify every single line in my C# code to make it use the proxy or there is some configuration/env variable that can be set in the iotedge module so that automatically every connection attempted will go through the proxy?**

**Note: **I've already followed the microsoft documentation [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2018-06&preserve-view=true](here). In fact, edgeAgent and edgeHub modules are correctly using the proxy.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
PS C:\Windows\system32> iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: The system cannot find the file specified. (os error 2)
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 85 days (at 2021-08-01 09:32:29 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: The system cannot find the file specified. (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its C:\Windows\Temp\edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with DPS endpoint - Error
    Could not connect: unsuccessful tunnel
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect: unsuccessful tunnel
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect: unsuccessful tunnel
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to XXX.azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (A timeout while waiting for the proxy server at ::XXX on port XXX to respond.)
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to XXX.azure-devices.net:8883
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (A timeout while waiting for the proxy server at ::XXX on port XXX to respond.)

12 check(s) succeeded.
5 check(s) raised warnings.
5 check(s) raised errors.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows 10
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.1.1
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.1.40522521
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.1.40522521
* Docker/Moby [run `docker version`]: 
 Client:
 Version:           19.03.12+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0ed913b885c8919944a2e4c8d0b80a318a8dd48b
 Built:             Wed Jun 17 17:27:03 2020
 OS/Arch:           windows/amd64
 Experimental:      false

  Server:
  Engine:
  Version:          19.03.12+azure
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.11
  Git commit:       9dc6525e6118a25fab2be322d1914740ea842495
  Built:            Fri Jul 31 21:31:52 2020
  OS/Arch:          windows/amd64
  Experimental:     false
[DMC_BayCity_RHF_DeviceMonitor_Logs.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/6465588/DMC_BayCity_RHF_DeviceMonitor_Logs.txt)
[DMC_BayCity_RHF_$edgeAgent_Logs.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/6465589/DMC_BayCity_RHF_.edgeAgent_Logs.txt)
[DMC_BayCity_RHF_$edgeHub_Logs.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/6465590/DMC_BayCity_RHF_.edgeHub_Logs.txt)

**Comment by jamdavi** [comment]
@xela-95 

### Things we need to verify

1. Are you connecting via Web Sockets on the Module? (AMQP_WS or MQTT_WS)
2. Are you using X.509 Certificates, DPS, SAS?
3. Does your proxy inspect traffic or terminate SSL in any way?

### Timeout
I was reviewing the logs and I see these lines.

```
2021-05-10 14:48:02.5083 Debug AzureModuleClient..ctor [1] - Trying retrieving desired properties from iotHub' 
2021-05-10 14:48:24.1460 Debug AzureModuleClient..ctor [1] - Device Twin Connetion not availlable (An error occurred while sending the request.): Trying retrieving desired properties from local starage' 
```

To me this shows ~21.5 seconds between the error messages and relates to a **connection time out**. This would happen if the module is unable to connect to the endpoint.

### Proxy Questions

> How can I be sure that all the connections attempted inside my module will go through the proxy? Do I have to modify every single line in my C# code to make it use the proxy or there is some configuration/env variable that can be set in the iotedge module so that automatically every connection attempted will go through the proxy?

In the docs it tells you to set the `https_proxy` setting on the deployment manifest. That will ensure that the module gets the correct proxy address. You will just need to make sure all of your module clients are choosing the correct protocol over websockets.

### Edgecheck

In your edgecheck output I see that the host is unable to connect via DPS and I also see that the containers AMQP and MQTT are blocked. All of these are expected when there is a proxy/firewall.

**Comment by xela-95** [comment]
@jamdavy 
First of all, thank you for your quick answer!

We've made an improvement, making the registry manager use the proxy found in the https_proxy variable:
```
var proxy = Environment.GetEnvironmentVariable("https_proxy");
    HttpTransportSettings ts = null;
    if (!string.IsNullOrEmpty(proxy))
    {
        ts = new HttpTransportSettings();
        ts.Proxy = new System.Net.WebProxy(proxy);
    }
  
    RegistryManager registryManager = RegistryManager.CreateFromConnectionString(connectionString, ts);
    // Retrieve device twin from registry manager
    var twinData = registryManager.GetTwinAsync(DeviceId).GetAwaiter().GetResult();
```
However, as you can see in the updated logs of my module we have issue in the connection to the Azure Active Directory, so we are not yet at the point where we're attempting a connection to the IoTHub.

I'll try to answer to your questions:
 1. Yes we'll use WS, but up to now the error is on the authentication to Azure Active Directory.
 2. Yes we use DPS and SAS, no certificates
 3. The proxy is not inspecting Microsoft traffic


> ### Proxy Questions
> > How can I be sure that all the connections attempted inside my module will go through the proxy? Do I have to modify every single line in my C# code to make it use the proxy or there is some configuration/env variable that can be set in the iotedge module so that automatically every connection attempted will go through the proxy?
> 
> In the docs it tells you to set the `https_proxy` setting on the deployment manifest. That will ensure that the module gets the correct proxy address. You will just need to make sure all of your module clients are choosing the correct protocol over websockets.
> 

We have already set up that environment variable. In this way will the Module clients and device clients recognize this variable by default and hence will use the proxy?

[logs_DeviceMonitor_2021-05-11_Github.log](https://github.com/Azure/azure-iot-sdk-csharp/files/6467745/logs_DeviceMonitor_2021-05-11_Github.log)

**Comment by jamdavi** [comment]
@xela-95 Okay I think I'm on the same page now. Originally I was under the impression the ModuleClient was the issue here.

### Short Answer
The edge agent sets the HTTPS_PROXY environment variable. That's it.

### Follow up for IoT Clients

Typical development with Edge involves creating a ModuleClient. The ModuleClient is "edge-aware" and will use a number of environment variables to connect to the edge service over a named pipe if you use the `CreateFromEnvironment` factory method.

The RegistryManager is not "edge-aware" so you have to create the client with the transport settings as above. The same is true for DeviceClient.

**Comment by xela-95** [comment]
@jamdavi Ok thank you, this was a valuable info!
Now we have updated our code including the transport settings with the proxy info (if the ```http_proxy``` env. variable is found).

The problem that blocks us from attempting to connect to IoTHub is that we need to authenticate to Azure Active Directory in order to communicate with some configuration apis. 
**Can this kind of authentication be performed in an iotedge module using the proxy?**

**Comment by jamdavi** [comment]
@xela-95 

> Can this kind of authentication be performed in an iotedge module using the proxy?

I can't think of a reason why why AAD Identity wouldn't work behind a proxy inside of the Moby container. But, to be honest this sounds like a Azure Identity config/usage and it's not something that the IoT Hub SDK has control over.

**Comment by jamdavi** [comment]
@xela-95 If you're okay with it I will close this as it looks to be centered around the proxy which isn't part of the Hub SDK

**Comment by xela-95** [comment]
@jamdavi I have found the solution to this problem! I will post it here asap 😎

**Comment by xela-95** [comment]
@jamdavi sorry for the delay in the response.
Our solution to this issue is the following:

1. Add the http_proxy environment variable for the custom module in the deployment manifest
2. Set-up the use of proxy in the custom module code, both for generic web requests and for the Azure IoT objects that are not "edge-aware" like you said in a previous message. 

Here's a snippet of our code that solved the problem:
```
TransportType transportTypeWS = TransportType.Amqp_WebSocket_Only;
AmqpTransportSettings amqpSettingWS = new AmqpTransportSettings(transportTypeWS);

// Setting proxy for DeviceClient and ModuleClient
var proxyUri = Environment.GetEnvironmentVariable("https_proxy");
System.Net.WebProxy proxy = null;
if (!string.IsNullOrWhiteSpace(proxyUri))
{
	
	proxy = new System.Net.WebProxy(proxyUri);
	amqpSetting.Proxy = proxy;
	amqpSettingWS.Proxy = proxy;
}

ITransportSettings[] settings = { amqpSetting, amqpSettingWS };

 _deviceClient = DeviceClient.Create(IotHubHostname,
	new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey), settings);
	
_moduleClient = ModuleClient.CreateFromEnvironmentAsync(settings).GetAwaiter().GetResult();

// all web requests will use this setting
if (proxy != null)
{
	System.Net.WebRequest.DefaultWebProxy = proxy; 
}

// Setting Proxy for RegistryManager
HttpTransportSettings ts = null;
if (proxy != null)
{
	ts = new HttpTransportSettings();
	ts.Proxy = proxy;
}

RegistryManager registryManager = RegistryManager.CreateFromConnectionString(iotHubConnectionString, ts);

// Setting Proxy for EventHub
EventHubProducerClientOptions producerOptions = null;
if (proxy != null)
{
	producerOptions = new EventHubProducerClientOptions();
	producerOptions.ConnectionOptions.Proxy = proxy;
}

 _eventHubClient = new EventHubProducerClient(eventHubConnectionString, eventHubName, producerOptions);
```

I want to thank you for all your precious support, that helped us to find a solution. I think that this type of information can be useful if added to the (poor) documentation about proxy on IoT edge modules.
