### ISSUE TITLE
[feature request] Failover support for AMQP service client

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#1957]
As a follow up from our recent work to enable failover support on our HTTP service clients, we need to make the AMQP service client have this support as well.

For additional context, #1865 is the same issue, but for our HTTP clients

**Comment by barustum** [comment]
This needs to be supported by the service team. Will keep a work item on our side to keep track.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.
