### ISSUE TITLE
[Bug Report] - Breaking change in Microsoft.Azure.Devices.Common.Security for SharedAccessSignature blocking Microsoft-AED from upgrading assembly

### ISSUE THREAD

**Issue by ScottyMac-dev** [Azure/azure-iot-sdk-csharp#1960]
**Namespace**
Microsoft.Azure.Devices.Common.Security

**Issue Statement**
The access to SharedAccessSignature was changed from public to internal from version 1.29 to 1.30 of the assembly. AICS, the API  that Microsoft Vendors use to certify IoT devices in Azure.

**Blocking Issue**
We would like to make sure that our API stays in step with all updates of the dependencies that it uses. Currently we are 4 releases behind and stuck at 1.29.

**Request**
If it's not possible to revert the access then it could be useful to provide a workaround. Here is the code that we are using:

`
			if (SharedAccessSignature.IsSharedAccessSignature(SharedAccessSignatureString))
			{
				SharedAccessSignature.Parse(ServiceName, SharedAccessSignatureString);
			}
`

**Comment by drwill-ms** [comment]
@ScottyMac-dev We made that change because it is not referenced anywhere in the API surface, and we realized it should not be part of the public interface.

You can copy the code, or (as it seems you wish to use it directly) you could choose to use reflection to call it.

**Comment by ScottyMac-dev** [comment]
HI,

Thanks for the reply. Since it is not used I think I will try a different way.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
