### ISSUE TITLE
Unable to register device with CA attestation on macOS

### ISSUE THREAD

**Issue by Dietatko** [Azure/azure-iot-sdk-csharp#1996]
# Context

- **OS, version, SKU and CPU architecture used:** macOS 11.3 x64
- **Application's .NET Target Framework :** net5.0
- **Device:** MacBook
- **SDK version used:**
  - Microsoft.Azure.Devices.Client 1.37.0
  - Microsoft.Azure.Devices.Provisioning.Client 1.17.1" />
  - Microsoft.Azure.Devices.Provisioning.Transport.Amqp 1.14.1
  - Microsoft.Azure.Devices.Provisioning.Transport.Http 1.13.1
  - Microsoft.Azure.Devices.Provisioning.Transport.Mqtt 1.15.1

## Description of the issue
I have created a group enrollment with certificate attestation with self-signed root certificate. The root certificate is added to DPS certificates and is verified.
The device is trying to register with identity certificate signed by intermediate certificate which is signed by the root certificate. I created a PFX file containing all 3 certificates and imported this into certificate collection.
Registration with DPS throws exception "CA certificate not found." with error code 401002. The same problem happens with MQTT and AMQP transports.
The same code works on Windows.

## Code sample exhibiting the issue
```
var chain = new X509Certificate2Collection();
chain.Import(@"chain-from-identity-to-root-ca.pfx", "password-to-PFX-file");

var certificate = chain.Cast<X509Certificate2>().Last();
using var security = new SecurityProviderX509Certificate(certificate, chain);

var transport = new ProvisioningTransportHandlerAmqp();

var provClient = ProvisioningDeviceClient.Create(
    "global.azure-devices-provisioning.net",
    "scope-id",
    security,
    transport);

var result = await provClient.RegisterAsync();
```

## Console log of the issue
I do not see any relevant logs on mac unfortunately.

**Comment by vinagesh** [comment]
Hi, are you using Xamarin on mac ? We officially do not support this yet. However it is in our backlog to add support for Xamarin. I don't have any timelines but we are actively working on it.

**Comment by Dietatko** [comment]
As indicated this is a .Net core application executed on macOS (not Xamarin). The problem was detected on .net 5 but the same problem happens on .net core 3.1.

Why is this closed? Still seems to be a problem...

**Comment by vinagesh** [comment]
We do not officially support mac. We only support windows and linux and hence the issue was closed. However, we do have a backlog item to add support for Xamarin (for cross-platform). How are you using it in mac? The only SDK that supports mac at the moment is the C SDK. I can find out more details for you if you are interested.

**Comment by Dietatko** [comment]
Okay I see the lack of macOS support. Claiming "broad range of OS platforms" in sentence "The IoT Hub device SDK for .NET can be used with a broad range of OS platforms and devices, mainly modern versions Windows and Linux." is little misleading when it is actually only Windows and Linux.

Regarding how am I using it on mac... Well .net core is a cross-platform runtime so I can natively execute .net core app also on mac os.

**Comment by vinagesh** [comment]
> Okay I see the lack of macOS support. Claiming "broad range of OS platforms" in sentence "The IoT Hub device SDK for .NET can be used with a broad range of OS platforms and devices, mainly modern versions Windows and Linux." is little misleading when it is actually only Windows and Linux.
> 
> Regarding how am I using it on mac... Well .net core is a cross-platform runtime so I can natively execute .net core app also on mac os.

Thank you. So you are using Visual Studio right? As we are already doing some investigation on macOS, I will add this as something to investigate. However, I don't have any timelines to let you know when we will have any answers or fixes. If it happens anytime soon, I'll update here.

**Comment by Dietatko** [comment]
I am using Rider to develop on Mac. The target app will run on Linux so it should work in the end. I just found this while testing on Mac.

Thank you very much for looking into this in the future.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
