### ISSUE TITLE
[Bug Report] Тo eventhub event is NOT generated by UpdateReportedPropertiesAsync method

### ISSUE THREAD

**Issue by pesetskyps** [Azure/azure-iot-sdk-csharp#1998]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** .NET 5
- **Device:** simulated device
- **SDK version used:** 
![image](https://user-images.githubusercontent.com/6270100/120371068-fc579c00-c31d-11eb-9c21-99483fac88a8.png)

## Description of the issue
I would like to capture the event in EventHub when device reported Propreties are updated. I use 
`deviceClient.UpdateReportedPropertiesAsync(twinUpdate);`

According to documentation it should generate the `twinChangeEvents` event
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations

## Code sample exhibiting the issue
https://github.com/xaviermignot/device-twin-routing-demo

The events for Reported Property update is not generated. Only telemetry upper in screenshot below is captured in the event
![image](https://user-images.githubusercontent.com/6270100/120371726-e1d1f280-c31e-11eb-8ef4-fab4c7d095e4.png)

![image](https://user-images.githubusercontent.com/6270100/120371342-4fc9ea00-c31e-11eb-846e-4ad5606f62d2.png)

## Console log of the issue
Consider setting the DEBUG environment variable to '*'. This will produce a much more verbose output that will help debugging
Don't forget to remove any connection string information!

**Comment by timtay-microsoft** [comment]
From the linked documentation:

> To do so, your IoT solution needs to create a route and to set the Data Source equal to twinChangeEvents. By default, no such routes pre-exist, so no twin notifications are sent.

Can you confirm that you created a route in your IoT Hub where the data source is equal to "twinChangeEvents"?

**Comment by barustum** [comment]
as @timtay-microsoft mentioned, you need to setup a route on your hub.  For Endpoint, select 'events' and for Data source select 'Device twin Change Events'. 

I tested this with the code you provided with a route set up, and I was able to see the event on the hub.

**Comment by pesetskyps** [comment]
Yes that is exactly what I was missing. Sorry for distruction. If anyone interested in specific command to apply here is the comand:
`az iot hub route create --hub-name paveliothub001 -n route-device-twin-changes --source twinchangeevents --endpoint-name events`

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
