### ISSUE TITLE
 Azure Iot: Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException:

### ISSUE THREAD

**Issue by mohammednaseem** [Azure/azure-iot-sdk-csharp#200]
[http://azuregeon.blogspot.in/2017/10/azure-iot-c-certificate-connectivity.html](url)

Please check the above link. I was following the Microsoft documentation on Azure IoT but I am not able to connect (securely with X.509 certificates to the Azure IoT hub.
I have documented the completed steps in the above link. Please have a look and let know what I am missing.

**Comment by tameraw** [comment]
Please try using the script in this [tutorial](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started).
