### ISSUE TITLE
[QUERY] How to delete the blob on the edge by the SDK then it will also delete the blob on the cloud automatically

### ISSUE THREAD

**Issue by pintse** [Azure/azure-iot-sdk-csharp#2007]
**Query/Question**
When I upload the "helloworld.txt" into the blob storage on the IoT edge by the SDK, and it is upload to the storage account on the cloud automatically.

The file must keep saving in the IoT edge after it is uploaded to the cloud.

When I delete the "helloworld.txt" in the blob storage on the IoT edge by the SDK, but the file in the storage account on the cloud is not be deleted automatically.

How to delete the file in the cloud automatically when the file is deleted in the IoT edge?

The module twin setting:

```
{
    "deviceAutoDeleteProperties": {
        "deleteOn": false,
        "deleteAfterMinutes": 5,
        "retainWhileUploading": true
    },
    "deviceToCloudUploadProperties": {
        "uploadOn": true,
        "uploadOrder": "OldestFirst",
        "cloudStorageConnectionString": "<cloud storage account connectionString>",
        "storageContainersForUpload": {
            "customer01": {
                "target": "customer01"
            }
        },
        "deleteAfterUpload": false
    }
}
```
The .net core code uses WindowsAzure.Storage V9.3.3:

```
string storageConnectionString = "blob storage on iot edge connectionString";

CloudStorageAccount account = CloudStorageAccount.Parse(storageConnectionString);
CloudBlobClient serviceClient = account.CreateCloudBlobClient();

CloudBlobContainer container = serviceClient.GetContainerReference("customer01");
container.CreateIfNotExistsAsync().Wait();

CloudBlockBlob deletedBlob = container.GetBlockBlobReference("helloworld.txt");
deletedBlob.DeleteIfExistsAsync().Wait();
```

**Environment:**
 - WindowsAzure.Storage V9.3.3 
 - mcr.microsoft.com/azure-blob-storage:latest on Azure Ubuntu VM
 - the code run on Windows 10
VS Code 1.45.1
.NET Core SDK :
Version: 3.1.100
Commit: cd82f021f4
OS Name: Windows
OS Version: 10.0.17763
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
Version: 3.1.0
Commit: 65f04fb6db

.NET Core SDKs installed:
2.1.508 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I also ask the question in the [StackOverflow](https://stackoverflow.com/questions/62399976/how-to-delete-the-blob-on-the-edge-by-the-sdk-then-it-will-also-delete-the-blob)

**Comment by timtay-microsoft** [comment]
Just to be clear, you are asking if there is a setting that would make Edgehub forward the "delete file" request up to the Azure Storage blob just like how it currently forwards the "upload file" request?

I'll follow up with the Edgehub team and the Azure Storage team to get an answer for you

**Comment by timtay-microsoft** [comment]
From the Azure Storage team:

> There is no consistency between local and cloud storage. The module can only upload data written locally. There is no delete cloud data feature, or re-upload old data if it was deleted in the cloud. The module doesn’t compare local and cloud state (except for handling some specific errors), it uploads data based on locally maintained state.

I'm going to close this issue as "not supported" and because this is a service feature request, not and SDK issue.

If you'd like to push for this feature to be added to the relevant services, I'd suggest using the [user voice](https://feedback.azure.com/forums/34192--general-feedback) channel to share why you need this feature, and the service teams will pick up the work if possible

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
