### ISSUE TITLE
azure iothub device stops sending messages after sometime

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-iot-sdk-csharp#2009]
I developed an application in .net,  it was sending messages to the azure IoT hub all the time perfect for a long time but recently it started to show very strange behavior.  Application is ok with sending messages to the IoT hub for some time, but suddenly just stops sending. Without an error or anything else that helps me find the root cause for this. Just restarting the application is enough to get it working again either in release or debug mode. The packages version and code is given below 

```
 <package id="Microsoft.Azure.Amqp" version="2.4.2" targetFramework="net472" />
  <package id="Microsoft.Azure.Devices.Client" version="1.20.1" targetFramework="net472" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.16.0" targetFramework="net472" />
```

```
  client = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(deviceName, deviceKey), TransportType.Mqtt);
 var messageString = JsonConvert.SerializeObject(telemetry);
 var message = new Message(Encoding.ASCII.GetBytes(messageString));
 await client.SendEventAsync(message);
```

**Comment by timtay-microsoft** [comment]
@bilalmalik777 can you try upgrading to the latest device client version (1.37.2)? The version you are on is quite old

**Comment by azabbasi** [comment]
@bilalmalik777 Are you still hitting the same issue even after upgrading to the latest stable version?

**Comment by bilalmalik777** [comment]
No, after upgrading to the latest version, it is fixed.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
