### ISSUE TITLE
[feature request] DeviceStream feature disappears in the last preview SDK release 

### ISSUE THREAD

**Issue by algorni** [Azure/azure-iot-sdk-csharp#2031]
**Is your feature request related to a problem? Please describe.**
Starting from the below version of Service & Device SDK all the methods related to Device Stream disappeared! 

```
<PackageReference Include="Microsoft.Azure.Devices" Version="1.35.0-preview-001" />
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.38.0-preview-001" />
```

**Describe the solution you'd like**
Please re-include those features in the preview releases. 

**Describe alternatives you've considered**
Downgrade to a previous version of pre-released SDK

```
<PackageReference Include="Microsoft.Azure.Devices" Version="1.28.0-preview-001" />
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.32.0-preview-001" />
```

**Additional context**
![image](https://user-images.githubusercontent.com/45007019/121877246-b8479c80-cd0a-11eb-8ec7-6543b7bdf293.png)

Thank you for helping make this project even better!

**Comment by abhipsaMisra** [comment]
@algorni Is there anything else that we can help you with or does this answer your query?

**Comment by abhipsaMisra** [comment]
@algorni Let me know if you have any other questions regarding our release strategy, otherwise I'll close this issue in 3 days. Thanks!

**Comment by abhipsaMisra** [comment]
@algorni I'm closing this issue since this behavior is expected based on our preview strategy. Feel free to reach out to us in case you have any additional questions.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
