### ISSUE TITLE
Add specific documentation around what platforms this library supports

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-csharp#2032]
It'd be nice to have a formal document where we list which .NET versions and operating systems that we test this SDK against, and lists our stances on other platforms like Xamarin.

Once this document is added, the "new issue" templates should be updated to point users to them so that issues aren't filed for unsupported frameworks/operating systems.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
