### ISSUE TITLE
[Technical Question]Correct way to retrieve module configurations on a device

### ISSUE THREAD

**Issue by xela-95** [Azure/azure-iot-sdk-csharp#2037]
Hi,
in our project we have a IoT Device containing two custom modules (in addition to EdgeAgent and EdgeHub).
Up to now we have in the **device twin** the desired properties containing the configurations for the two modules. 
Each of the two modules has an initialization phase like this:
```
deviceClient = DeviceClient.Create(iotHubHostname,
                              new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, deviceKey), transportType);
await deviceClient.OpenAsync();
Console.WriteLine("Device client initialized");

// Register a callback for device client connection changes
deviceClient.SetConnectionStatusChangesHandler(OnConnectionStatusChanged);

await deviceClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertiesUpdate, null)
```
The transport type is AMQP_TCP.
However, with one of the two modules I'm experiencing issues because when the desired properties of the device twin are modified on IoTHub, it does not get notified. Or better, OnDesiredPropertiesUpdate gets called only a few times when the module is started and then nothing.

It can be a bug of my module or this is not the correct way to store and retrieve desired properties?
I'm thinking that maybe the two modules are competing for the connection with the device client, but I'm not sure... 
I do know that module twin exists but I have never used it, maybe it is better to store module specific configurations there, instead of using device twin?

**Comment by timtay-microsoft** [comment]
Hi Xela, for module code, you should be using the ModuleClient class, not the DeviceClient class. Each module client will have not only the deviceId in its connection string, but it will also have a moduleId to help differentiate between modules. We have some sample code [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/module/ModuleSample) that you can take reference from.

Once you have two separate module client connections open rather than two identical device client connections competing over the same connection, you should see your twin updates work the way you expect

**Comment by xela-95** [comment]
Thank you @timtay-microsoft 

I'm trying to create a module client but I'm having issues. I've tried using the CreateFromEnvironmentAsync(ClientOptions) but this gives me an error saying "providerUri scheme not supported". 
Then I've tried using CreateFromConnectionString(String, ClientOptions) but this gives me another error saying that the connection string must contain also the DeviceId.
What I'm missing?

**Comment by timtay-microsoft** [comment]
For the createFromEnvironment constructor, what does your IOTEDGE_WORKLOADURI environment variable look like? The SDK expects it to be an HTTP url, but does allow unix socket address for all platforms other than net451.

For the createFromConnectionString constructor, ModuleClient connection strings should look like: 

```HostName=<your IoT Hub's host name>;DeviceId=<the Id of the device that contains your module>;ModuleId=<your module's Id>;SharedAccessKey=<primary or secondary key>```

You can get this value from the Azure Portal

**Comment by xela-95** [comment]
@timtay-microsoft thank you. I resolved this issue using the createFromConnectionString constructor with the correct connection string. Thank you!

**Comment by timtay-microsoft** [comment]
That sounds like an issue with IoT Edge rather than this SDK. I'd suggest filing an issue [here](https://github.com/Azure/iotedge/issues) so that an IoT Edge developer can help you understand this issue

**Comment by timtay-microsoft** [comment]
Since the last part of this is figuring out what's going on inside of Edgehub rather than the SDK, I'm going to close this issue. Feel free to open a new issue if you run into any other problems with this SDK

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
