### ISSUE TITLE
System properties like sequence number is not populated in received C2D message using mqtt protocol

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-iot-sdk-csharp#206]
- **OS and version used:**  Windows 10
- **SDK version used:** 1.5.2 

# Description of the issue:
In received C2D message using mqtt protocol, system properties like sequence number is not populated

# Code sample exhibiting the issue:
Device:
```
var myDeviceClient = DeviceClient.CreateFromConnectionString(connectiongString, TransportType.Mqtt);
myDeviceClient.OpenAsync().Wait();
while (true)
{
         var receivedMessage = await MyDeviceClient.ReceiveAsync(TimeSpan.FromSeconds(1));
         if (receivedMessage == null) continue;

         Console.WriteLine($"{DateTime.Now} < Received message: {Encoding.UTF8.GetString(receivedMessage.GetBytes())} with SN {receivedMessage.SequenceNumber}");

          await MyDeviceClient.CompleteAsync(receivedMessage);
          await Task.Delay(100);
}

```
# Output:
![image](https://user-images.githubusercontent.com/20550718/31982741-b8affe50-b98c-11e7-98fa-fe93bdd19fcd.png)

If using other protocols, the sequence number shows correctly

**Comment by CIPop** [comment]
Thanks for reporting @allenhula. 
Do you know if this is something that the service side should fill in or we're just not properly setting this on the client side?

**Comment by allenhula** [comment]
I didn't debug into yet. Considering other protocols work fine, it seems client side issue.

**Comment by abhipsaMisra** [comment]
This looks like a bug from the service-side. For Amqp and Http, service does populate the sequence-no in the device bound message, while they don't do the same over Mqtt. Following this up with the service-team.

**Comment by abhipsaMisra** [comment]
This is by service-design. There is no API on Mqtt over which the message sequence no can be returned, so this property is not available for c2d messages over Mqtt.

**Comment by az-iot-builder-01** [comment]
@CIPop, @allenhula, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
