### ISSUE TITLE
ModuleId Validate does not validate with ModuleIdProperty name but for DeviceId

### ISSUE THREAD

**Issue by tjjkj** [Azure/azure-iot-sdk-csharp#2061]
In the below source code, IotHubConnectionStringBuilder->Validate() validates the ModuleId using DeviceIdPropertyName instead of ModuleIdPropertyName

Code:
  if (!string.IsNullOrEmpty(ModuleId))
            {
                ValidateFormat(ModuleId, DeviceIdPropertyName, s_idNameRegex);
            }

https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/IotHubConnectionStringBuilder.cs

**Comment by abhipsaMisra** [comment]
You are correct, we will fix this right away.

**Comment by abhipsaMisra** [comment]
This fix has been released in our latest release: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-8-11
Closing this issue.
