### ISSUE TITLE
[Bug Report] PnP APIs `TryGetValue` should not throw expected exceptions

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-sdk-csharp#2066]
The `Try..` pattern in .NET, like `int.TryParse`, is intended to do not throw exceptions. 

from the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-5.0):

> The TryParse method is like the Parse method, except the TryParse method does not throw an exception if the conversion fails. It eliminates the need to use exception handling to test for a FormatException in the event that s is invalid and cannot be successfully parsed.

reproes with #2065

**Comment by abhipsaMisra** [comment]
This bug has been fixed and released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-10-8.
