### ISSUE TITLE
Unable to add Microsoft.Azure.Devices namespace to Azure Function App.

### ISSUE THREAD

**Issue by SunainaDG** [Azure/azure-iot-sdk-csharp#209]
I have an Azure Function from which I need to send back messages to my devices through IoTHub.
Every time I try to add the statement:

using Microsoft.Azure.Devices;

I get the below error:

run.csx(11,23): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)

But strangely as the error suggests, if I just go for "using Microsoft.Azure", there are no compilation errors.

So I tried using Devices withing my code, like "static Devices.ServiceClient client;",but again the same error.

I have also tried using #r "Microsoft.Azure.Devices", but that didn't work either.

I tried creating a new Function App service altogether, but the same error just keeps poping up.

My project.json file looks something like this:

`{

     "frameworks": {
          "net46":{
               "dependencies": {
                    "Microsoft.Azure.Devices": "1.4.1"
               }
          }
     }
}`

I tried using "net47" also.

Small decription of my app:

So my function is supposed to be triggered by a ServiceBusTopic, has a BlobStorage as an Input, does stuff and return some data from the function app to my device.

**Comment by CIPop** [comment]
I'm not familiar with Azure Functions but .Net Core doesn't use project.json anymore.

Please follow instructions from https://www.microsoft.com/net/core#windowscmd . You can add references using the `dotnet` tool. Please see `dotnet add package -h`.
If your application is a .Net 4.7 app you may want to use [Visual Studio ](https://www.visualstudio.com/downloads/) to create the project and the References / NuGet integration to ensure that all dependencies are added.

@SunainaDG  Hope this answers the question. If not, please re-open the issue.
