### ISSUE TITLE
Adding Microsoft.Azure.Devices nuget package to a C# UWP unit test project causes build to fail

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#21]
Something about adding the package to unit test project causes it to look for a csproj file that doesn't exist, and I suspect shouldn't ever exist in a nuget package:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2156,5): error APPX0702: Payload file 'C:\Users\v-tbert\.nuget\packages\Microsoft.Azure.Devices\1.1.5\lib\uap10.0\Microsoft.Azure.Devices.Uwp\Microsoft.Azure.Devices.Shared.UWP.csproj' does not exist

FWIW, it does not happen when Microsoft.Azure.Devices.CLIENT is added to the same project.

**Comment by anhashia** [comment]
Investigating !

**Comment by v-tbert** [comment]
FYI, this does repro with 1.2.1 too. Thanks for looking into it!

**Comment by anhashia** [comment]
Hi @v-tbert 

I was able to reproduce the issue initially. But after cleaning the dependencies folders and **re-installing**  the package I no longer see the issue.

This is what I did. Here **username** will be your user name that you are using.
Under C:\Users\username\\.nuget\packages
I deleted following 3 packages
1.) Microsoft.Azure.Amqp
2.) Microsoft.Azure.Devices
3.) Microsoft.Azure.Devices.Shared
These are listed as dependencies under
https://www.nuget.org/packages/Microsoft.Azure.Devices/1.2.1

After that I  **uninstalled** and then **re-installed** the latest available 1.2.1 Microsoft.Azure.Devices (Service SDK for Azure IoT Devices) from https://www.nuget.org/packages/Microsoft.Azure.Devices/1.2.1.

This will trigger re-install of the packages and you should see following in the output (as an example)

`````
Installing Microsoft.Azure.Amqp 2.0.2.
Installing Microsoft.Azure.Devices.Shared 1.0.5.
Installing Microsoft.Azure.Devices 1.2.1.
Package restore completed successfully for 'UnitTestProject1'.

`````
After that **rebuild** the solution. With this approach, I no longer see the issue. You can try this approach to see if it fixes you issue also.

**Comment by anhashia** [comment]
Investigating this further !

**Comment by arturl** [comment]
I have a fix.

**Comment by arturl** [comment]
Fix checked in: https://github.com/Azure/azure-iot-sdk-csharp/commit/c5203bf051928d7957720fe9db46fac9528a3e28

**Comment by tameraw** [comment]
This is now in the latest release. Closing.
