### ISSUE TITLE
Upgrade 'Microsoft.Azure.Amqp' to latest version.

### ISSUE THREAD

**Issue by candersonio** [Azure/azure-iot-sdk-csharp#212]
# Description of the issue:
Currently, the DeviceClient package is built against Microsoft.Azure.Amqp 2.0.6, but doesn't have a maximum version so it can be used with Microsoft.Azure.Amqp 2.1.*.

There is a breaking change in Microsoft.Azure.Amqp 2.1.* from an abstract class that is used in DeviceClient. An example of an issue raised from this is #167. For more details on the breaking change, refer to [Azure/azure-amqp#81](https://github.com/Azure/azure-amqp/issues/81).

I've noticed some mentions of needing to upgrade this package in some of the pull requests comments, but since I haven't seen anything yet, I opened this issue. I'd like this to be resolved so I can be up to date with packages.

**Comment by CIPop** [comment]
Fixed by #308.
