### ISSUE TITLE
[Bug Report] Microsoft.Azure.Devices.Provisioning.Transport.Mqtt enforces .NET 5

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-iot-sdk-csharp#2149]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 (containerized)
- **Application's .NET Target Framework :** `netcoreapp3.1`
- **SDK version used:** v1.15.1 -> v1.16.0

## Description of the issue
When upgrading to Microsoft.Azure.Devices.Provisioning.Transport.Mqtt v1.16.0 it has an updated dependency for `DotNetty.Handlers` v0.7.0 which requires you to use .NET 5.

Since that is not an LTS version, we are not using .NET 5 and waiting for for.NET 6 so we can no longer upgrade.

Is it possible to keep using DotNetty v0.6.0?
Don't forget to remove any connection string information!

**Comment by tomkerkhove** [comment]
Same for `Microsoft.Azure.Devices.Client` v1.38.0

**Comment by abhipsaMisra** [comment]
Looking at DotNetty.Handlers v0.7.0, it is .NET Standard 2.0 compatible: https://www.fuget.org/packages/DotNetty.Handlers. 
Could you paste the error message that asks you to use .NET 5 instead?

**Comment by tomkerkhove** [comment]
People tend to not use .NET packages that are 5.x while still on 3.x but it would work here, closing as I'm wrong - Sorry!
