### ISSUE TITLE
DeviceClient.ReceiveAsync() fails with Xamarin.Android

### ISSUE THREAD

**Issue by maddentist** [Azure/azure-iot-sdk-csharp#216]
- **OS and version used:** 
Android API 25

- **SDK version used:** 
Microsoft.Azure.Amqp 2.1.2
Microsoft.Azure.Devices.Client 1.5.2
Microsoft.Azure.Devices.Shared 1.1.1

# Description of the issue:
Call to DeviceClient.ReceiveAsync() fails with xamarin.android. it throws an obscure exception linked to Microsoft.Azure.Amqp and some resource not found. (details below)

# Code sample exhibiting the issue:
```
private DeviceClient deviceClient;
// Some code removed for legibility //
internal AirproxEngine(DeviceTypes _type, string _serial = null, string _fname = null, string _key = null, bool isBlueTooth = false)
{
		{deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(DeviceSerial, deviceKey));
			ReceiveC2dAsync();
}
Task.Run(async () =>
				{
					while (true)
					{
						try
						{
							Message receivedMessage = await deviceClient.ReceiveAsync(TimeSpan.FromMilliseconds(400));
							if (receivedMessage == null)
							{
								continue;
							}

							byte[] payload = receivedMessage.GetBytes();
							await deviceClient.CompleteAsync(receivedMessage);
							await Task.Run(() => MessageTriage(payload));
						}
						catch (Exception ex)
						{
							TraceMess.WriteLine("ENG => Exception while receiving message ---------------------------------------------------------------");
							TraceMess.WriteLine("Message : " + ex.Message);
							TraceMess.WriteLine("HResult : " + ex.HResult);
							TraceMess.WriteLine("InnerException : " + ex.InnerException);
							TraceMess.WriteLine("Source : " + ex.Source);
							TraceMess.WriteLine("StackTrace : " + ex.StackTrace);
							TraceMess.WriteLine("TargetSite : " + ex.TargetSite);
							TraceMess.WriteLine("--------------------------------------------------------------------------------------------------------");
						}
						await Task.Delay(500);
					}
				});

```
# Console log of the issue:
> [0:] Message : Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Amqp.Amqp.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Amqp" at compile time, or that all the satellite assemblies required are loadable and fully signed.
> [0:] HResult : -2146233038
> [0:] InnerException : 
> [0:] Source : mscorlib
> [0:] StackTrace :   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000bf] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x000d9] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x00099] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) [0x00002] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Resources.ResourceManager.GetString (System.String name, System.Globalization.CultureInfo culture) [0x0005a] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at Microsoft.Azure.Amqp.Amqp.Resources.get_AmqpPutTokenFailed () [0x00005] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.AmqpCbsLink+SendTokenAsyncResult.ConvertToException (System.Int32 statusCode, System.String statusDescription) [0x000c5] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.AmqpCbsLink+SendTokenAsyncResult+<GetAsyncSteps>d__13.MoveNext () [0x002bc] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.IteratorAsyncResult`1[TIteratorAsyncResult].MoveNextStep () [0x00000] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.IteratorAsyncResult`1[TIteratorAsyncResult].EnumerateSteps (Microsoft.Azure.Amqp.IteratorAsyncResult`1+CurrentThreadType[TIteratorAsyncResult] state) [0x0015f] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.IteratorAsyncResult`1[TIteratorAsyncResult].StepCallback (System.IAsyncResult result) [0x00057] in <6762560bba6a4a31b520554a2d001f08>:0 
>   at Microsoft.Azure.Amqp.AsyncResult.AsyncCompletionWrapperCallback (System.IAsyncResult result) [0x00037] in <6762560bba6a4a31b520554a2d001f08>:0 
> --- End of stack trace from previous location where exception was thrown ---

**Comment by CIPop** [comment]
Thanks for reporting @maddentist . What Xamarin version are you using?

This might be related to https://github.com/Azure/azure-iot-sdk-csharp/issues/197 .

**Comment by ryan-z-johnson** [comment]
@maddentist Taking another look at this, would you try downgrading your AMQP to 2.0.6 and letting me know what happens it may be related to issue #212 as well.

**Comment by maddentist** [comment]
@CIPop these are the versions used (copied from VS) : 

Microsoft Visual Studio Enterprise 2017 
Version 15.4.2
VisualStudio.15.Release/15.4.2+27004.2006
Microsoft .NET Framework
Version 4.7.03013

Version installée : Enterprise

Visual Basic 2017   00369-60000-00001-AA384
Visual C# 2017   00369-60000-00001-AA384
Visual C++ 2017   00369-60000-00001-AA384
Visual F# 4.1   00369-60000-00001-AA384
Arduino for Visual Studio   1.0
ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET Core Razor Language Services   1.0
ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
Assistants Microsoft Visual C++   1.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.3.0000.1
Azure Data Lake Tools for Visual Studio   2.3.0000.1
Common Azure Tools   1.10
Fabric.DiagnosticEvents   1.0
Gestionnaire de package NuGet   4.4.0
JavaScript Project System   2.0
Merq   1.1.17-rc (cba4571)
Microsoft Azure HDInsight Azure Node   2.3.0000.1
Microsoft Azure Hive Query Language Service   2.3.0000.1
Microsoft Azure Stream Analytics Language Service   2.3.0000.1
Microsoft Azure Stream Analytics Node   1.0
Microsoft Azure Tools   2.9
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Node.js Tools   1.4.10918.1
Outils Azure App Service v3.0.0   15.0.30915.0
Outils de développement Office pour Visual Studio 2017 FRA   15.0.26818
Outils de livraison continue Microsoft pour Visual Studio   0.3
Outils Microsoft Azure Service Fabric pour Visual Studio   1.8
Package Microsoft Visual Studio VC   1.0
Package Outils Application Insights pour Visual Studio   8.9.00809.2
RelayCommand Extension   1.0
Service de langage JavaScript   2.0
SQL Server Data Tools   15.1.61707.200
Système de projet UWP JavaScript   2.0
ToolWindowHostedEditor   1.0
TypeScript   2.3.5.0
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools pour CMake   1.0
Visual Studio Tools pour les applications Windows universelles   15.0.27004.2006
Visual Studio Tools pour Unity   3.4.0.2
VisualStudio.IoT   1.0
VisualStudio.Mac   1.0
WebJobs Tools v1.0.0   15.0.30915.0
Workflow Manager Tools 1.0   1.0
**Xamarin   4.7.10.33 (70936af)**
**Xamarin.Android SDK   8.0.2.1 (HEAD/c2a33d8ea)**
Xamarin.iOS and Xamarin.Mac SDK   11.2.1.0 (12e80e0)

**Comment by maddentist** [comment]
@ryan-z-johnson, I've downgraded AWQP to 2.0.6 in the .NET standard lib and the Android project, the exact same problem occurs.

**Comment by tameraw** [comment]
@maddentist - Please try with 1.6.1 release and reopen if still having issues. Thanks.

**Comment by abhipsaMisra** [comment]
@maddentist - We have updated some Xamarin Android samples in our repository which implement send & receive messages. Could you please try with those and let us know if that helps! Thanks!

**Comment by abhipsaMisra** [comment]
@maddentist - Could you please try out using the latest samples and let us know if that helps. In case you face further issues, please open another GitHub issue. Thanks!
