### ISSUE TITLE
Registry manager ignores ";GatewayHostname=" in connection string

### ISSUE THREAD

**Issue by huguesBouvier** [Azure/azure-iot-sdk-csharp#2175]
## Description of the issue
With the IoT SDK it is possible to connect a leaf device through an iotedge gateway. For that GatewayHostname= is appended to the connection string and it works well for DeviceClient:

```
string connectionString = "HostName=nxxx;DeviceId=debugEdgeLeaf;SharedAccessKey=xxx=;GatewayHostname=some_ip";
var client = DeviceClient.CreateFromConnectionString(connectionString, new[] { transportSettings });
```

However, this doesn't work for registry manager. The GatewayHostname parameter is ignored and the leaf device connects directly to iotHub

## Code sample exhibiting the issue
RegistryManager registryManager = RegistryManager.CreateFromConnectionString(connectionString);

**Comment by drwill-ms** [comment]
Hi @huguesBouvier. Thanks for your feedback. Azure IoT Edge does not support routing service traffic, only device traffic. The SDK couldn't enable this.

Can you tell us more about your scenario? I can at least try to put you in touch with our Edge teammates so they understand your requirements.

Regards,
David

**Comment by huguesBouvier** [comment]
Creating modules from leaf through edge device is a request from our customers: https://github.com/Azure/iotedge/issues/5155.
With modules such as ADU that come on leaf devices and also the separation of edged and Identity service, customers will want to create module on leaf device.
Module is not as much and edge thing as it used to be.
