### ISSUE TITLE
[Bug Report] AddDevices2Async does not set the parent device scope

### ISSUE THREAD

**Issue by MaidaB** [Azure/azure-iot-sdk-csharp#2184]
## Description of the issue
When I use the AddDeviceAsync method to register a device with an IoT Hub, it works as expected. I set the device.Scope to the desired one, and pass the device as a parameter. However, when I use the batch version AddDevices2Async with the same device, the parent is not set in the IoT Hub.

## Code sample exhibiting the issue
This works:
var devices = new List<Device>();
foreach (var deviceId in deviceIds) {
    var device = new Device(deviceId);
    device.Scope = edgeDevice.Scope;
    // device.Authentication = ....
}
foreach (var device in devices) {
    await _registryManager.AddDeviceAsync(device).ConfigureAwait(false);
}

This does not work:
var devices = new List<Device>();
foreach (var deviceId in deviceIds) {
    var device = new Device(deviceId);
    device.Scope = edgeDevice.Scope;
    // device.Authentication = ....
}
await _registryManager.AddDevices2Async(devices).ConfigureAwait(false);

## Console log of the issue
If I go to the Azure Portal and look at the registered devices, I can see that their parent device is not set.

**Comment by timtay-microsoft** [comment]
Yep, this looks like a bug. I'll get a fix out for this soon.

**Comment by drwill-ms** [comment]
A [release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-11-01) with this fix is out.
