### ISSUE TITLE
[Bug Report] Can not read/write ModulesContent due to inconsistent property naming

### ISSUE THREAD

**Issue by SaraOlsson** [Azure/azure-iot-sdk-csharp#2185]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** 1.35.0

## Description of the issue
When using the RegistryManager to create IoT Edge module Configurations, the SDK expects the ConfigurationContent to be of type **ModulesContent**, while on the server side it is named **ModuleContent**, which could be confirmed by looking at the network traffic:

```
"content":{"moduleContent":{"properties.desired.configurations":{"key":"value" ..
```
note that while module**s**Content (with an 's') shows up on configurations that are IoT Edge deployments:

```
"content":{"modulesContent":{"$edgeAgent":{"properties.desired.runtime.settings ..
```

However, in code, I can only create module configuration content with:
```
configuration.Content = new ConfigurationContent
{
    ModulesContent = new Dictionary<string, IDictionary<string, object>>
    {
        {
            "properties.desired.configurations",
            new Dictionary<string, object>
            {
                {"name", "Sara"}
            }
        }
    }
};
````

.. as the ConfigurationContent does not contain a definition for ModuleContent. Using ModulesContent causes *The deployment configuration is malformed or invalid*. Due to this issue, we can not list our module configurations nor create new ones. Can this be fixed soon, or what may be a workaround?

**Comment by timtay-microsoft** [comment]
Taking a look at the service documentation around this [ConfigurationContent](https://docs.microsoft.com/en-us/rest/api/iothub/service/configuration/apply-on-edge-device) object shows that there is supposed to be both a ```ModuleContent``` and a ```ModulesContent``` object in this type. This strikes me as a bit odd though, so I'll reach out to a service engineer to confirm this.

There is no workaround for this bug as of now, but I'll try to get the fix checked in as soon as I can confirm what the service expects here.

**Comment by drwill-ms** [comment]
A [release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-11-01) with this fix is out.
