### ISSUE TITLE
Examples for QuerySpecification

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#2188]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET, [#24392](https://github.com/Azure/azure-sdk-for-net/issues/24392).

## Details

Hi there, 

It would be helpful if you guys included an 'examples' section in the QuerySpecification page. I haven't been able to find any examples of how to make the right queries to DPS other than "SELECT * FROM enrollments". 

In my case, I am trying to query a specific registrationId, but always get the enrollement information for all my devices, probably because my query is not correct ($"SELECT * FROM enrollments WHERE enrollments.registrationId = '{registrationId}'"   this query is in C# by the way.)

Thank you very much, 

Miguel Rincon. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07b1bea-e9c6-fe35-e16f-2f4a6017b6bb
* Version Independent ID: 8539d973-542c-f3ab-17b7-ba474cca0cc9
* Content: [QuerySpecification Class (Microsoft.Azure.Devices.Provisioning.Service) - Azure for .NET Developers](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.azure.devices.provisioning.service.queryspecification?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Provisioning.Service/QuerySpecification.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Provisioning.Service/QuerySpecification.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by azabbasi** [comment]
@marincon-sarmiento
Hello, 
Have you visited the [IoT Hub query language for device and module twins, jobs, and message routing](IoT Hub query language for device and module twins, jobs, and message routing)? 
Are you looking for a more comprehensive example set specifically around querying DPS?

**Comment by azabbasi** [comment]
I did a little bit of research and unfortunately, it sounds like IoT Hub still doesn't have full support for query options in DPS so the Sql query is ignored in QuerySpecification.
#794 This issue is known to the service team and they haven't provided an ETA for when this will be available.

**Comment by markcupito** [comment]
Did this ever get documented anywhere? Seems like the Enrollment Group Queries are still returning all enrollments.

**Comment by marincon-sarmiento** [comment]
I do t think so, I ended opting for a different approach.

**Comment by 2x01101110** [comment]
`new QuerySpecification("")`

Returns all groups. Doesn't seem to be any documentation anywhere.
