### ISSUE TITLE
Getting exception while reading the notifications for the file uploaded by device in Storage

### ISSUE THREAD

**Issue by sAndeeppandey12** [Azure/azure-iot-sdk-csharp#2193]
We have created an application that uploads file from 10 different devices concurrently to storage for 5 minutes continuously, also we have an application that keeps listening to the Notifications received for each of the file uploads.

To create file upload and Notification receiver application we have referred to : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-file-upload

Problem : File uploaded is working fine as expected. But while reading the notifications, initially till 80 to 100 notifications are received our application is working fine, but after this we are seeing exceptions getting thrown every time.

Package Version we tried :   1.35.0  and 1.34.0

Exception Details :
```
{
Message : Unknown error.
Source : Microsoft.Azure.Devices
StackTrace : at Microsoft.Azure.Devices.AmqpClientHelper.DisposeMessageAsync(FaultTolerantAmqpObject`1 faultTolerantReceivingLink, String lockToken, Outcome outcome, Boolean batchable)
}
```

Code Snippet :

 ```
try
            {
                Console.WriteLine("Receive file upload notifications\n");
                serviceClient = ServiceClient.CreateFromConnectionString(connectionString, TransportType.Amqp_WebSocket_Only);
                await ReceiveFileUploadNotificationAsync();
                await serviceClient.CloseAsync();
                Console.WriteLine("Press Enter to exit\n");
                Console.ReadLine();
            }
            catch (Exception e)
            {
                await serviceClient.CloseAsync();
                Console.WriteLine(e);
            }

        private static async Task ReceiveFileUploadNotificationAsync()
        {
            var notificationReceiver = serviceClient.GetFileNotificationReceiver();
            Console.WriteLine("\nReceiving file upload notification from service");
            int totalDownloadedFile = 1;
            var enqueTimeList = new List<double>();

            var stopwatch = Stopwatch.StartNew();
            while (true)
            {

                var fileUploadNotification = await notificationReceiver.ReceiveAsync();
                if (fileUploadNotification == null)
                    continue;

                var totalSeconds = (DateTime.UtcNow - fileUploadNotification.EnqueuedTimeUtc);

                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine($"Number of notification recieved :{totalDownloadedFile++}, TimeTaken : {stopwatch.ElapsedMilliseconds} , FileName : {fileUploadNotification.BlobName} ," +
                    $" DeviceId : {fileUploadNotification}");
                Console.ResetColor();
                await notificationReceiver.CompleteAsync(fileUploadNotification);
                enqueTimeList.Add(totalSeconds.TotalSeconds);
            }
}

```

**Comment by azabbasi** [comment]
The service team is investigating the issue on their side and will provide more details on the ICM ticket. As far as the SDK involvement goes, you should trap these exceptions that are thrown and retry the operation (Receive and Complete) and in most cases, it should be transient and resolved. 
According to the service team, this can happen especially when the client holds on to the notification for longer than the lock time (default is 60s) before completing it. 
We have published a [sample code](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/main/iot-hub/Samples/service/FileUploadNotificationReceiverSample) that shows how these operations can have retry logic around them.
Please feel free to re-open or create new issues if you come across any other problems.

Thank you
