### ISSUE TITLE
Nuget dependency not set for Microsoft.Azure.Amqp

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#22]
I have a simple UWP app that uses the Microsoft.Azure.Devices nuget package and the first call to RegistryManager fails. I get a file not found exception presumably because the nuget dependency for Microsoft.Azure.Amqp wasn't set.

System.IO.FileNotFoundException was unhandled by user code
  FileName=Microsoft.Azure.Amqp.Uwp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  HResult=-2147024894
  Message=Could not load file or assembly 'Microsoft.Azure.Amqp.Uwp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.Azure.Devices.Uwp
  StackTrace:
       at Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(String connectionString)
       at TestClient.share.TestClient.TestConnectionState()
       at App1.App.OnLaunched(LaunchActivatedEventArgs e)
  InnerException:

**Comment by jasmineymlo** [comment]
Thanks for the report.  We have fixed the issue and please use v1.2.1.
