### ISSUE TITLE
[Bug Report] Device client retry policy not working as expected

### ISSUE THREAD

**Issue by Werner-Prbk** [Azure/azure-iot-sdk-csharp#2202]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 (also on linux arm32) 
- **Application's .NET Target Framework :** .netcoreapp 3.1
- **Device:** Laptop (also on arm32 device with custom linux)
- **SDK version used:** 1.38.0

## Description of the issue
Setting a ExponentialBackoff retry policy with retry count N leads to N*N retry attempts before it completely stops retrying. 
I assume the expected behavior is, that the retry policy starts when the device client enters connection state (Disconnected_Retrying, Communication_Error), retries N times and finally changes to (Disconnected, Retry_Expired). Once it is in (Disconnected, Retry_Expired) no more retries shall be carried out and the connection state shall no more change.

I am not completely sure, but I guess the problem is in `RetryDelegationHandler.cs` because of a nested retry block:

* [SendEventAsync()](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/iothub/device/src/Transport/RetryDelegatingHandler.cs#L70) calls [EnsureOpenedAsync()](https://github.com/Azure/azure-iot-sdk-csharp/blob/4f888245d253692b6c18509fc68c2412ddd4b540/iothub/device/src/Transport/RetryDelegatingHandler.cs#L641) in a retry block
* EnsureOpenedAsync() calls [OpenInternalAsync()](https://github.com/Azure/azure-iot-sdk-csharp/blob/4f888245d253692b6c18509fc68c2412ddd4b540/iothub/device/src/Transport/RetryDelegatingHandler.cs#L750) in another retry block

## Code sample exhibiting the issue
```
static async Task Main()
{
      deviceClient = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Mqtt);

       // This should result in disconnected/retry_expired after a few seconds
      deviceClient.SetRetryPolicy(
          new ExponentialBackoff(
              6,   // retry counter
              TimeSpan.FromSeconds(1),
              TimeSpan.FromSeconds(10),
              TimeSpan.FromSeconds(1)));

      deviceClient.SetConnectionStatusChangesHandler((status, reason) =>
          Print($"Connection status changed: {status}, {reason}"));

      await deviceClient.OpenAsync();
      Print("Connected");

      try
      {
          while (true)
          {
              await Task.Delay(TimeSpan.FromSeconds(5));
              Print("Send message ... start");
              await deviceClient.SendEventAsync(new Message());
              Print("Send message ... OK");
          }
      }
      catch (Exception e)
      {
          Print($"Periodic sender exception: {e.Message}. Exit.");
      }
}
```
![image](https://user-images.githubusercontent.com/9977183/137221942-ed136ce1-adf6-464d-bd21-662cfd3a50e5.png)

## Console log of the issue
[retry_logs.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/7341632/retry_logs.txt)

**Comment by drwill-ms** [comment]
A [release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-11-01) with this fix is out.
