### ISSUE TITLE
E2E tests improper use of TPL

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#222]
A lot of code in the E2E tests are using Tasks the wrong way.
We need to remove all instances of .Result and .GetAwaiter().GetResult().

Initialization can be performed by calling the `async Task` init methods during test execution or using `AsyncLazy<T>` to ensure init-once semantics.

Examples: ClassInitialize/ClassCleanup calls to InitializeEnvironment and CloseAsync().

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
