### ISSUE TITLE
Formatting error on registrationId parameter description.

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#2222]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#24925](https://github.com/Azure/azure-sdk-for-net/issues/24925).

## Details

I think you messed up some formatting syntax here. It's rendering like this:
![image](https://user-images.githubusercontent.com/10708799/138867139-b3ab5c74-da55-4c81-b785-c9b56214bf01.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a5a94f5-1170-f55a-298b-c4437b925270
* Version Independent ID: ba9adf93-d5b9-7423-45b2-f18db20654c9
* Content: [ProvisioningServiceClient.GetIndividualEnrollmentAsync Method (Microsoft.Azure.Devices.Provisioning.Service) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.provisioning.service.provisioningserviceclient.getindividualenrollmentasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by azabbasi** [comment]
@jgn-epp 
 Thank you for reporting this issue. 
 We indeed messed this up. The fix has been checked in and it will be updated on the docs page when we release the next version.
