### ISSUE TITLE
Potential race condition in Mqtt protocol handler

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#223]
The following async code is called in a non-async callback context without being awaited:

https://github.com/Azure/azure-iot-sdk-csharp/blob/581b59cd37d98d2a78ec260f03d55e205036e327/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttIotHubAdapter.cs#L104

The following I/O will run in parallel:

https://github.com/Azure/azure-iot-sdk-csharp/blob/581b59cd37d98d2a78ec260f03d55e205036e327/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttIotHubAdapter.cs#L254

https://github.com/Azure/azure-iot-sdk-csharp/blob/581b59cd37d98d2a78ec260f03d55e205036e327/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttIotHubAdapter.cs#L106

and the `ChannelActive` callback may return before the `Connect` completes.

(Thanks @stephentoub for helping with this investigation!)

**Comment by ewertons** [comment]
According to conversation with @CIPop , the solution is to await for Connect within ChannelActive, guaranteeing base.ChannelActive and context.Read are not called before that.
A PR will be posted with the fix.

**Comment by timtay-microsoft** [comment]
Closing this issue since the fix was merged in. It will be in the next release

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
