### ISSUE TITLE
[Bug Report] DeviceClient throws Aggregate Exception while sending messages

### ISSUE THREAD

**Issue by jlingaa** [Azure/azure-iot-sdk-csharp#2238]
# Context

- **OS:** Mac BigSur 11.6
- **Application's .NET Target Framework :** .netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client 1.39.0

## Description of the issue

An aggregate exception is thrown while doing the same test as outlined in #2232 
This gets thrown suddenly while the app is running over a period of more than 30 min.

## Console log of the issue

Here is the call stack of the exception.

11/3/2021 5:25:14 PM: Exception sending message System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.EnsureValidState(Boolean throwIfNotOpen)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Test.IOTHub.Program.SendMessagesToIOTHub(Object sender, ElapsedEventArgs e)

**Comment by azabbasi** [comment]
Thanks for reporting this issue as well, 
I am currently working on both of the issues you filed against the repo.
The one thing that may be causing some of these issues is the rate at which a new thread is being spawned up and sending 5000 messages each time. 
I do not know what IoT hub tier you are using but the basic tier only allows for 400k messages per day. and you will exceed that rather quickly if you are using the same hub.
another issue that I am trying to investigate is that the iothub client can't send 25 * 5000 = 125k messages in 5 minutes, I am currently measuring the maximum capability and will get back to you on that. but if my assumption is correct, the threads you have spawned up will not close within the 5 minutes and you will keep adding new threads to the pool and will eventually exhaust the device client somehow. 
I will keep you posted on what I find out and will get back to you.

**Comment by jlingaa** [comment]
We are using the standard S1 tier but temporarily increased to 8 units making it 3.2m messages per day for this test. We are not even close to reaching that limit due to the errors that pop up. The errors even popped up once in a while doing 3000 messages with 25 threads. But this is all for the test.

On a realistic note, we anticipate sending around 10000 messages every 10 minutes scaled across 20 threads. We have seen some aggregate exceptions thrown with internal errors stating transient errors. We would like to know the following:

1.  Are there are any limitations with the approach related to throughput?
2. What is the app supposed to do when these errors are encountered? Does it retry internally?
3. Any other underlying issues that can cause with this approach?

This is just the starting point for the throughput and we are looking forward to increase the number of messages if iothub sdk supports it.

**Comment by azabbasi** [comment]
@jlingaa 

I did some testing of my own to gauge the throughput of the SDK.
It's really not a static measurement as there are a lot of variables involved, but it will give us a rough idea of how much pressure it can sustain.
Here are a few data points that may help us scale the application accordingly.

* In general, AMQP protocol is going to be much faster and multi-thread friendly as MQTT is FIFO.
* Based on your initial testing, I found that on average, 25 threads can send 125k messages in 19 minutes (rough estimate) if AMQP is used and the same operation will take 64 minutes on MQTT of course all these numbers depend on the agent running them, the network quality, ping time, hub response time, etc, but it gives us an idea of what we can expect here. I would like to expand on that. So if you attempt to send 125k messages across 25 threads every 5 minutes, you will end up spinning off 25 additional new threads every 5 minutes, slowing down the previous 25 threads, and eventually run out of resources. A more realistic attempt would be to use AMQP and set the timer every 20 minutes based on our testing. 

Do you mean 10k messages spread across 20 threads or 20 threads each sending 10k messages every 10 minutes?
The former is was doable in my test even in MQTT with a 7.35 minute and in AMQP in 44 SECONDS. 

We are still investigating the error messages and exceptions you came across and will try to mitigate them ASAP, in the meanwhile, I would like to set a reasonable expectation on the throughput.

I recommend using AMQP in your testing to maximize throughput.

**Comment by jlingaa** [comment]
@azabbasi 

Thanks for the info. We have an underlying service that pushes around 10000 messages every 10 min to some messaging service like Rabbit. We have another service that creates 20 consumers for the rabbit queue and tries to send the messages at the same time using one instance of device client, typically like 20 threads trying to call the device client to send messages.

It is quite interesting that there is a significant difference in the processing times with AMQP vs MQTT. To switch from MQTT to AMQP, do we just need to set the transport type while creating the deviceclient instance? Should the IotHub need to be configured differently if using AMQP?

DeviceClient.CreateFromConnectionString(ConnectionString, TransportType.Amqp_WebSocket_Only)

Are there any underlying complications with AMQP that we should be aware of? Please let us know.

**Comment by azabbasi** [comment]
@jlingaa 
There is no configuration change required, you simply change your transport protocol and start using AMQP instead. 

Not as far as we know, all features in the device client work just the same across the two protocols.
Let us know how that goes.

**Comment by jlingaa** [comment]
@azabbasi 

We will try it with AMQP and see how that goes. Does the throughput difference apply for C2D as well? We have seen some issues related to C2D. One of them is described in #2241

**Comment by azabbasi** [comment]
@jlingaa
C2D is only over AMQP and HTTP, there is no MQTT used in the service client.

**Comment by azabbasi** [comment]
> @azabbasi
> 
> We will try it with AMQP and see how that goes. Does the throughput difference apply for C2D as well? We have seen some issues related to C2D. One of them is described in #2241

We are looking into that one as well.

**Comment by jlingaa** [comment]
@azabbasi 

We ran some tests. We modified the test app to use AMQP. The app is set to push D2C messages and also subscribed to listen for C2D messages. The app is configured to have 20 threads send 5000 messages each every 20 min.

The app sent 4.7m messages in about 14 hours with no issues. We could never send more than 2m messages without an issue with MQTT before. So, this looks promising so far.

**Comment by azabbasi** [comment]
@jlingaa 
That is good to hear. We are investigating the shortcomings of our MQTT protocol layer.

**Comment by timtay-microsoft** [comment]
Closing as stale
