### ISSUE TITLE
[Bug Report] Proxy settings are ignored when connecting to IoT Hub over AMQP

### ISSUE THREAD

**Issue by backspacer80** [Azure/azure-iot-sdk-csharp#2242]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :**  netcoreapp3.1, net6.0
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client 1.39.0

## Description of the issue
An application that is located on premises of a customer connects over AMQP to IoT Hub. The customer uses a corporate proxy.
In the application I'm creating a DeviceClient instance and opening a connection to IoT Hub over AMQP.
No matter what I enter for property AmqpTransportSettings.Proxy it seems to be ignored.
Regardless if I enter the correct address of the corporate proxy or a fake address, the SDK behaves the same:
It always manages to connect to the IoT Hub. Is the Proxy property respected at all? See minimal example below.

## Code sample exhibiting the issue
```
// dotnet 6.0
using System.Net;
using Microsoft.Azure.Devices.Client;

RunExample();

void RunExample()
{
    using (DeviceClient deviceClient = CreateDeviceClient())
    {
        try
        {
            deviceClient.OpenAsync().GetAwaiter().GetResult();
        }
        catch (Exception e)
        {
            if (e.Message.Contains("IotHub") && e.Message.Contains("not registered"))
            {
                // We expect an exception because the device ID is made up: If that's the actual error message then we're connected!
                Console.WriteLine("Connected to IoT Hub successfully!");
            }
            else
            {
                Console.WriteLine("Not connected to IoT Hub :-(");
                throw;
            }
        }
    }
}

DeviceClient CreateDeviceClient()
{
    string deviceId = "Y2N0ZXN1";
    string authToken = "Y2N0ZXN2";
    string hostName = "example.azure-devices.net";
    string proxyHost = "10.11.12.13";
    int proxyPort = 3128;
    string? proxyUser = "***";
    string proxyPassword = "***";

    return DeviceClient.Create(
        hostName,
        new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, authToken),
        new ITransportSettings[]
        {
            new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
            {
                Proxy = new WebProxy(proxyHost, proxyPort)
                {
                    Credentials = new NetworkCredential(proxyUser, proxyPassword)
                }
            }
        });
}

```
## Console log of the issue
Connected to IoT Hub successfully!

**Comment by jamdavi** [comment]
@backspacer80 It looks like you're using `Amqp_Tcp_Only`. Proxy support is only for WebSocket connections. Can you try again using `Amqp_WebSocket_Only` and see it it honors the proxy setting.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.transporttype?view=azure-dotnet

**Comment by jamdavi** [comment]
@backspacer80 Please have a look at the linked PR and let me know if this documentation would have helped when writing the code. Here is what it looks like in Visual Studio.

![image](https://user-images.githubusercontent.com/73593426/144675902-75136c77-afaa-49eb-a8d3-c8ad19491bb0.png)

**Comment by backspacer80** [comment]
> @backspacer80 It looks like you're using `Amqp_Tcp_Only`. Proxy support is only for WebSocket connections. Can you try again using `Amqp_WebSocket_Only` and see it it honors the proxy setting.
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.transporttype?view=azure-dotnet

Yes, I switched to Amqp_WebSocket_Only and it does the job! Thank you.

**Comment by backspacer80** [comment]
> @backspacer80 Please have a look at the linked PR and let me know if this documentation would have helped when writing the code. Here is what it looks like in Visual Studio.
> 
> ![image](https://user-images.githubusercontent.com/73593426/144675902-75136c77-afaa-49eb-a8d3-c8ad19491bb0.png)

Yes, definitely it would have helped. I'm looking forward to the PR. I consider this one here solved and will close it. Thanks.
