### ISSUE TITLE
API documentation link is not working

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#226]
In the root readme.md the link for `The API reference documentation for .NET SDK is here.` is not working.

**Comment by CIPop** [comment]
@ryan-z-johnson @jasmineymlo @tameraw do you know where this link should point to?

**Comment by yzhong94** [comment]
Service: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices?view=azure-dotnet
Device: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client?view=azure-dotnet
