### ISSUE TITLE
What is replacement/updated method for CryptoKeyGenerator.GenerateKey(Int32)?

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#2265]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#26179](https://github.com/Azure/azure-sdk-for-net/issues/26179).

## Details
This page says that this method is going to obsolete and deprecated in the future but offer no alternative solution on how to move away from this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ff4e17-b177-be41-c0f6-b24f1458e8ab
* Version Independent ID: a8acaf6e-a0f1-6422-aba1-c46b36311592
* Content: [CryptoKeyGenerator.GenerateKey(Int32) Method (Microsoft.Azure.Devices.Common) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.common.cryptokeygenerator.generatekey?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Common/CryptoKeyGenerator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Common/CryptoKeyGenerator.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by drwill-ms** [comment]
@m-chau we marked `CrytpoKeyGenerator.GenerateKey` as obsolete, as mentioned in these [patch notes](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-11-01) and linked to the PR with reasoning [here](https://github.com/Azure/azure-iot-sdk-csharp/pull/2187). The gist is:

1. The underlying .NET method that enabled this was removed after .NET 4.7.2. As we've added new .NET targets, we don't have an implementation for it.
2. This helper method was not part of our core API. The reason for it being included before is unclear, but it seems mainly for testing purposes. We believe we shouldn't have such APIs in the client and therefore have chosen not to find a new implementation for newer .NET targets.
