### ISSUE TITLE
ModuleClient class thread safety

### ISSUE THREAD

**Issue by gimmi** [Azure/azure-iot-sdk-csharp#2317]
I need to use ModuleClient class in a multi threaded C# application with concurrent and independent calls to SendAsync. 

Is ModuleClient class thread safe in the mentioned scenario?

My plan is to create a singleton instance of ModuleClient at the beginning of the application and use that single instance for all the duration of the application. Will the class auto-recover from broken connection that can happen, or I need to detect and recreate the client when this appen?

**Comment by drwill-ms** [comment]
Yes, the app can access the client from multiple threads.

Although this sample uses the `DeviceClient`, the patterns are similar, and you should review [this sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/main/iot-hub/Samples/device/DeviceReconnectionSample) to know how to handle client lifetime, connection status, and how various loops in your program should handle errors from calls to the client.

**Comment by gimmi** [comment]
Thanks a lot!
