### ISSUE TITLE
X509 Authentication to Azure IoT Hub

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-csharp#232]
(Filed on behalf of @domenicoamelino)

Hi,

I am working in Windows 10 with a C# Application in order to connect to Azure IoT HUB with X509 Certificates. 

# Description of the issue
I am using the bash linux to generate the CA Identity tutorial shown on the Azure Website support and in this git repository.
I succeed to authenticate and verify the RootCA certificate but the C# Applications (from the example code on https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started) does successfully connect to the cloud. 

The device certificate, RootCA and proof of ownership of Root CA Certificate are generated using the certGen.sh  bash script.

# Code sample exhibiting the issue:
using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.Devices.Shared;
using System.Security.Cryptography.X509Certificates;
```sh
namespace SimulateX509Device
{
    class Program
    {
        private static int MESSAGE_COUNT = 5;
        private const int TEMPERATURE_THRESHOLD = 30;
        private static String deviceId = "MyDevice";
        private static float temperature;
        private static float humidity;
        private static Random rnd = new Random();

        static async Task SendEvent(DeviceClient deviceClient)
        {
            string dataBuffer;
            Console.WriteLine("Device sending {0} messages to IoTHub...\n", MESSAGE_COUNT);

            for (int count = 0; count < MESSAGE_COUNT; count++)
            {
                temperature = rnd.Next(20, 35);
                humidity = rnd.Next(60, 80);
                dataBuffer = string.Format("{{\"deviceId\":\"{0}\",\"messageId\":{1},\"temperature\":{2},\"humidity\":{3} }}", deviceId, count, temperature, humidity);
                Message eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                eventMessage.Properties.Add("temperatureAlert", (temperature > TEMPERATURE_THRESHOLD) ? "true" : "false");
                Console.WriteLine("\t{0}> Sending message: {1}, Data: [{2}]", DateTime.Now.ToLocalTime(), count, dataBuffer);

                await deviceClient.SendEventAsync(eventMessage);
            }
        }

        static void Main(string[] args)
        {
            try
            {
                var cert = new X509Certificate2(@"<new-device.cert.pfx>", "123");
                var auth = new DeviceAuthenticationWithX509Certificate("MyDevice", cert);
                var deviceClient = DeviceClient.Create("<NameoftheServer>.azure-devices.net", auth, TransportType.Amqp_Tcp_Only);

                if (deviceClient == null)
                {
                    Console.WriteLine("Failed to create DeviceClient!");
                }
                else
                {
                    Console.WriteLine("Successfully created DeviceClient!");
                   
                    SendEvent(deviceClient).Wait();
                }

                Console.WriteLine("Exiting...\n");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error in sample: {0}", ex.ToString());
            }
            Console.ReadLine();
        }
    }


}
```
In particular, when the C# Application tries to connect, i retrieve this Unexpected exception:
Successfully created DeviceClient!

>Device sending 5 messages to IoTHub...
>
>
>
>      14/11/2017 11:58:58> Sending message: 0, Data: >[{"deviceId":"MyDevice","messageId":0,"temperature":23,"humidity":72 }]
>
>Error in sample: System.AggregateException: One or more errors occurred. ---> >Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException:
>
>Tracking Id:3bfa37ae5da74bb4a24c7a1aba2bbda1-G:0-TimeStamp:11/14/2017 10:58:59
>
>  at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
>
>   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
>
>   at System.Threading.Tasks.Task.Execute()
>
>--- End of stack trace from previous location where exception was thrown ---
>
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>
>   at SimulateX509Device.Program.<SendEvent>d__6.MoveNext() in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 35

>   --- End of inner exception stack trace ---
>
>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>
>   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>
>   at System.Threading.Tasks.Task.Wait()
>
>   at SimulateX509Device.Program.Main(String[] args) in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 55
>
>---> (Inner Exception #0) Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException:
>
>Tracking Id:3bfa37ae5da74bb4a24c7a1aba2bbda1-G:0-TimeStamp:11/14/2017 10:58:59
>
>   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
>
>   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
>
>   at System.Threading.Tasks.Task.Execute()
>
>--- End of stack trace from previous location where exception was thrown ---
>
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>
>   at SimulateX509Device.Program.<SendEvent>d__6.MoveNext() in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 35

Any help? Thanks.

**Comment by ewertons** [comment]
This issue was originally filed under the azure-iot-sdk-c repo (https://github.com/Azure/azure-iot-sdk-c/issues/301).
It was moved to here and the original was closed.

**Comment by anhashia** [comment]
Hi @domenicoamelino

There are 2 scenarios here. Detailed steps are located at 
https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

Scripts are located at
https://github.com/Azure/azure-iot-sdk-c/tree/master/tools/CACertificates
These scripts are for testing and **demonstration** purpose only

**Scenario 1**
Setup : **Windows 10** using PowerShell (PS) script
Script generates cert chain with device cert signed by Root CA. Here structure is 
Root CA -> Device cert

Here you would get an output as MyDevice.pfx file as an example
This file is signed by Root CA.
Script does seem to hang at line 177
The hang is happening because there seems to be some conflict for prompt was password when openssl in run in context of PS

You can workaround this hang by passing the password in the script itself or use console prompt directly.
`openssl pkcs12 -in $newDevicePfxFileName -out $newDevicePemAllFileName -passin pass:"123" -nodes `

When you run the PS script, it will also install these certs in local certificate store of your PC.
If you are using C#, application then you would have .PFX file **already** created at the time when you hit line 177. You can directly use that .PFX file and it should work in the C# application.

**Scenario 2**
Setup: Ubuntu 16.04 using bash script
Script generates cert chain with Intermediate CA in between. Here structure is 
Root CA -> **Intermediate CA** -> Device cert

If you want to use there certificates on **Windows 10**, then you will have to install the cert chain first in the local store. Directly trying to use  device cert PFX will give authorization error as during the TLS handshake the application will only send device cert. It needs to also send **intermediate CA** during TLS handshake as part of client certificates as you only have Root CA validated in this case.

**Comment by anhashia** [comment]
https://github.com/Azure/azure-iot-sdk-java/issues/182

**Comment by labiraus** [comment]
This may be linked to the comment I just made on #259 
If you're running .net core with a X509 certificate, you can't upload files, only in .net.

**Comment by domenicoamelino** [comment]
@anhashia. Thanks, the problem was related to the installation of PowerShell/Unix Terminal certificate in Windowa 10. In order to use the C# Azure test application the CA generated certificates have to be installed in the operating system. 

Thank you for the support.

**Comment by anhashia** [comment]
Hi @domenicoamelino Yeah, that is correct :-)

**Comment by CIPop** [comment]
Thanks @anhashia for your help and unblocking @domenicoamelino !


> Script does seem to hang at line 177

@jspaith this sounds like a bug in the Certificate generation script in the C repo.

> Script generates cert chain with Intermediate CA in between. Here structure is
> Root CA -> Intermediate CA -> Device cert

> If you want to use there certificates on Windows 10 in C# .NET application, then you will have to install the cert chain first in the local store. Directly trying to use device cert PFX will give authorization error as during the TLS handshake the application will only send device cert. It needs to also send intermediate CA during TLS handshake as part of client certificates as you only have Root CA validated in this case with Azure IoT Hub.

@yzhong94, @dominicbetts  Looking at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security, the step of installing certificates within the Intermediate Authorities is missing.
On .Net Core for Linux, one would need to use https://gist.github.com/CIPop/baf530337cc6b29e3d6a88047661f69c to import the chain certificates in the Intermediate Authorities (as @anhashia pointed out, the Root cert is not required as it's not sent on the wire during TLS handshake). The same tool or certmgr.msc (or even double-clicking on the .cer or .p7b file) then selecting "Install Certificate . . ." can be used on Windows:
![image](https://user-images.githubusercontent.com/8635911/35130165-583bcf92-fc74-11e7-9b5f-cc735a9c0068.png)


In DPS we've added a convenience API that would import the intermediates, if [needed](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/shared/Microsoft.Azure.Devices.Shared/SecurityProviderX509Certificate.cs#L23). Certs are [installed by the ProvisioningClient if needed](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/device/src/ProvisioningDeviceClient.cs#L42).

**Comment by CIPop** [comment]
@dominicbetts /cc @jspaith @tameraw @yzhong94 I'm not sure that article is the right documentation to create an enterprise-grade PKI. There are multiple commercial PKIs including one offered by Microsoft through Windows Server Certificate Authority (https://msdn.microsoft.com/en-us/library/ms755466(v=vs.85).aspx).
The instructions above are .NET Specific. They apply for both Windows and Linux (NetCore).

**Comment by dominicbetts** [comment]
@CIPop - I've created a workitem in the docs VSTS to discuss the required docs changes. Thanks.

**Comment by yzhong94** [comment]
@tameraw @ewertons Closing as we made the documentation update for this
