### ISSUE TITLE
[Technical Question] - Serialization using System.Text.Json instead of  Newtonsoft ?

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/azure-iot-sdk-csharp#2333]
Hi, 

By setting desired property object to my devices using Services SDK I saw a problem with the json property names in my twin. 
I conclued that the SDK is using Newtonsoft serialization  while I was using System.Text.Json attributes to specify the property names ``JsonPropertyName``. 

As a workaround, I used both ``JsonPropertyName`` attribute (from System.Text.Json.Serialization) and ``JsonProperty`` attribute from Newtonsoft.Json) on my properties to specify the JSON property names. 

Is there a specific region to still use Newtonsoft  in a .NET 6 SDK ?

Environment: 
- C# / .NET 6.0
- Microsoft.Azure.Devices NuGet version 1.37.0

Kindly regards,

**Comment by abhipsaMisra** [comment]
Hi @kbeaugrand, you're right, the .NET SDK takes a dependency on NewtonSoft.Json for our serialization/deserialization requirements. We have it in our plans to remove this strongly tied dependency and provide users with an option to specify their serializer, that we're planning to put out as a part of a major revision update.

In the meanwhile, we have released a [preview](https://github.com/Azure/azure-iot-sdk-csharp/blob/f68cdb83756923fc5ebebbf26c6a5d91304cbdca/iothub/device/src/ClientOptions.cs#L83) version of our package that does allow users to specify their serializer. This being a preview package, I'd advise against referencing this in production applications but you could try out the APIs in your test environment and let us know your feedback. This [readme](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/preview/iot-hub/Samples/device/ConventionBasedOperations) should help you understand how to translate the existing APIs to the new serializer-configurable APIs.
I want to call out that even though the above readme heavily references [IoT Plug and Play](https://docs.microsoft.com/azure/iot-pnp/concepts-convention) (as that was one of the primary driving forces behind the serializer-configurable APIs) you can still make use of those APIs even if your device does not follow a DTDL model.

**Comment by kbeaugrand** [comment]
Hi @abhipsaMisra , 

Thank you for your clarification!
I'll take care about that. Nice to see that there will be an option to use only System.Text.Json Serializer.
