### ISSUE TITLE
Why the default timeout for the Microsoft.Azure.Devices.ServiceClient cannot be set below 100 seconds?

### ISSUE THREAD

**Issue by ZolotaikoRoman** [Azure/azure-iot-sdk-csharp#2344]
I faced a problem that doesn't allow setting the default operation timeout below 100 seconds. There is a logic that says that the custom timeout for the device cloud method can be only if it is more than 100 sec. The case is that I want to invoke a direct method on the device and I want the timeout to be 10-20 seconds, after it, I want to handle the timeout exception using my custom code. Currently, it is impossible due to the internal rules of the ServiceClient, and there is no possibility to override these rules.
It would be good if you explain why it is developed this way and suggest/advise me on what can I do.
Thanks.

![image](https://user-images.githubusercontent.com/37477984/162925736-e2c0e76a-7730-4d25-85a7-c8b537951e20.png)

**Comment by drwill-ms** [comment]
I don't see a good reason for it, and according to our [service documentation](https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-direct-methods#method-invocation) the limits are between 5 and 300 seconds.

The change was made back in 2018 and there aren't good comments in the commit to specify why, but it was changed from 60 seconds to 100 minimum.

@andyk-ms We should hand this off to the service team (who now owns this SDK) to let them decide how they want to change it. We've generally moved to the stance that the SDK should not to error checking like this, rather rely on the service to return an error.

**Comment by ZolotaikoRoman** [comment]
@drwill-ms Thanks for the quick response!
Please let me know when you have any updates from the service team.

**Comment by drwill-ms** [comment]
The fix for this has shipped with version 1.37.1.

<https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-5-6>
