### ISSUE TITLE
[Technical Question] documentation of properties State and ProvisioningState

### ISSUE THREAD

**Issue by DOliana** [Azure/azure-iot-sdk-csharp#2369]
I would like to understand what information is available in the properties ProvisioningState & State.

The IoT-Hub SDK allows to get an Object of the type `IotHubDescription` which contains the property `IotHubProperties`. This Property contains the string Properties State & ProvisioningState. To me it is not clear what these properties mean and how they can be used to react to certain states.

The current documentation reads as follows (with not very meaningful descriptions as "Gets the state"):
```
        //     Gets the hub state.
        [JsonProperty(PropertyName = "state")]
        public string State
        {
            get;
            private set;
        }

        //     Gets the provisioning state.
        [JsonProperty(PropertyName = "provisioningState")]
        public string ProvisioningState
        {
            get;
            private set;
        }
```

**Comment by abhipsaMisra** [comment]
Could you add a link to the file where these properties are defined; I don't see a type called `IotHubDescription` or `IotHubProperties` in our SDK.

**Comment by DOliana** [comment]
I am talking about the class referenced in this documentation: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.iothub.models.iothubproperties?view=azure-dotnet

**Comment by abhipsaMisra** [comment]
> I am talking about the class referenced in this documentation: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.iothub.models.iothubproperties?view=azure-dotnet

This is the IoT hub SDK for the management plane which includes APIs for creating and managing Azure resources. The sourcecode for this SDK is maintained [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/iothub/Microsoft.Azure.Management.IotHub) and you can ask your question [here](https://github.com/Azure/azure-sdk-for-net/issues). 

This repository is for the IoT hub device and service APIs that deal with creating, managing and communicating with device and module identities on IoT hub.

I'm closing this issue with the above explanation.
