### ISSUE TITLE
[Technical Question] ErrorCode:InvalidConfigurationContent when use ApplyConfigurationContentOnDeviceAsync

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-iot-sdk-csharp#2419]
Microsoft.Azure.Devices Version="1.37.0"
```
ConfigurationContent configurationContent = new()
            {
                DeviceContent = new Dictionary<string, object>
                {
                    { "properties.desired.DefaultData", "XXXX"}
                }
            };

await _registryManager.ApplyConfigurationContentOnDeviceAsync("DEUA0000000000000011", configurationContent);
```

Throws with the message

> {"Message":"ErrorCode:InvalidConfigurationContent;The content provided for configuration is invalid. Please check and try again","ExceptionMessage":"Tracking ID:1454007930b646bf9f457ddde7d4d11a-G:0-TimeStamp:05/31/2022 22:06:56"}

What's wrong with the content? Where can I find a docs for `ApplyConfigurationContentOnDeviceAsync`?

**Comment by Marusyk** [comment]
no useful info here
 https://docs.microsoft.com/en-us/rest/api/iothub/service/configuration/apply-on-edge-device
and here
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.applyconfigurationcontentondeviceasync?view=azure-dotnet
and here
https://github.dev/Azure/azure-iot-sdk-csharp/blob/main/iothub/service/src/Registry/RegistryManager.cs#L2413-L2431

**Comment by drwill-ms** [comment]
@Marusyk, I've struggled with getting the payload right myself. One way I did it was to create it in the Azure Portal and then get the configuration using the API. We built some basic tests that [look very similar](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/e2e/test/iothub/service/RegistryManagerExportDevicesTests.cs#L118) to what you have above.

The best guide I can find for content is here: <https://docs.microsoft.com/azure/iot-hub/iot-hub-automatic-device-management>.

**Comment by drwill-ms** [comment]
@Marusyk is the device this call is being made for an Edge device?

**Comment by drwill-ms** [comment]
It looks like having module content is a requirement for this API. I realize the documentation doesn't say that. We're learning as we go and will update the docs as we get it figured out.

You might look at the [AddConfigurationAsync](https://docs.microsoft.com/dotnet/api/microsoft.azure.devices.registrymanager.addconfigurationasync) method that can be used with all devices. It requires creating a configuration with a target condition (to identify devices it applies to) and configuration content (as you have above).

**Comment by Marusyk** [comment]
Ok, thank you very much.

**Comment by drwill-ms** [comment]
Indeed, 100 configs max per hub per the [quotas](https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits) documentation.

> Automatic device and module configurations | 100 configurations per paid SKU hub. 10 configurations per free SKU hub.

**Comment by timtay-microsoft** [comment]
@Marusyk do you need any further help here? Otherwise, I'll go ahead and close this thread.
