### ISSUE TITLE
RegistryManager->HttpClientHelper creates a non-static HttClient wich is an antipattern

### ISSUE THREAD

**Issue by tymtam2** [Azure/azure-iot-sdk-csharp#2420]
# Context

HttpClientHelper, created every time an instance of RegistryManager is created, creates a non-static HttpClient which is considered an antipattern. 

HttpClients documenation states:

> [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0) is intended to be instantiated once and reused throughout the life of an application. In .NET Core and .NET 5+, HttpClient pools connections inside the handler instance and reuses a connection across multiple requests. If you instantiate an HttpClient class for every request, the number of sockets available under heavy loads will be exhausted. This exhaustion will result in [SocketException](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketexception?view=net-6.0) errors.

## Singleton vs on demand

I could not find any documentation that makes it clear if RegistryManager should be used as a singleton (HttpClient pattern) or is `using var registryManager = ...` recommended. (If having a local variable on demand is the preferred way then it results in multiple HttpClients and this doesn't seem correct). I would have created a separate issue for the documentation to add this clarification but I couldn't find an appropriate documentation page.   

## Code sample exhibiting the issue

The example at https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/service/RegistryManagerSample/RegistryManagerSample.cs
shows having a local RegistryManager. RegistryManagerSample is used once in the application but arguably maybe RegistryManager  should be static anyway to promote correct techniques. (If having a local variable on demand is the preferred way then it results in multiple HttpClients and this doesn't seem correct). 

```
using RegistryManager registryManager = RegistryManager
                .CreateFromConnectionString(_parameters.IoTHubConnectionString);

            try
            {
                await CreateDeviceHierarchyAsync(registryManager);

                await AddDeviceWithSelfSignedCertificateAsync(registryManager);

                await AddDeviceWithCertificateAuthorityAuthenticationAsync(registryManager);

                await EnumerateTwinsAsync(registryManager);
            }
```

**Comment by drwill-ms** [comment]
I've taken a deeper look at the code and found that the `HttpClient` instances are created with a specific proxy and base URI as specified in the registry manager connection information. That means if we made them static then a process couldn't have multiple instances of `RegistryManager` working against different IoT hubs or, and as unlikely as this seems, with different proxy settings. I know we could avoid setting the base URI but it looks like we do that to set connection lease timeouts to fix [this issue](https://github.com/Azure/azure-iot-sdk-csharp/pull/1874). We'd need to investigate more to see if we can do that without specifying the base URI.

So, that said, unless I have something wrong, I think it would be best for a service application to create and cache the registry manager instance. I think the most important thing is that `RegistryManager` doesn't create a new `HttpClient` for each request, so as long as the SDK instance stays around, the client application should be fine WRT the `HttpClient` anti-pattern.

Thoughts @tymtam2?

**Comment by tymtam2** [comment]
@drwill-ms Thanks for looking into this. 

Not many thoughts :) We'll move to using a static RegistryManager.

Should I raise a separate issue for the [ServiceClient](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/iothub/service/src/Messaging/ServiceClient.cs)?

**Comment by tymtam2** [comment]
Good point, I was using 'static' as a shortcut to ~"not initialised->disposed often (e.g. per request)".
