### ISSUE TITLE
DeviceClient connect error with MQTT

### ISSUE THREAD

**Issue by getandplay** [Azure/azure-iot-sdk-csharp#2421]
# Context

- Windows 10 Desktop x64
- net472
- Laptop
- Microsoft.Azure.Devices.Client 1.40.0

## Description of the issue
I reported this Issue before, https://github.com/Azure/azure-iot-sdk-csharp/issues/2325#event-6635817451
It is because the devices can't connect to IotHub with Mqtt_Websocket_Only.

1. Then I found that there are some customers' devices that can't connect to IotHub with Mqtt (TCP first then Websocket).
When those devices try to connect to the IotHub with Mqtt, it will report : status: Disconnected_Retrying, reason: Communication_Error. 
Then it seems like it's blocked, none ConnectionStatusChanges recieved anymore.(wait more than 1 hour).
But sometimes they can reconnect successfully.
I got a chance to debug it, just found that it can connect with mqtt_websocket, but can't connect with TCP. 
When the "Blocked" thing happened, I tried to call `deviceClient.DisposeAsync()`, want to recreate an instance, but failed, and didn't get any message or exception.

2. There are several machines try to report Disconnected_Retrying after connect succesfully , then they will reconnect successfully.
Here is the log print by below codes:
5/31/2022 2:02:01 PM --------- Start Connecting with Mqtt----------------------------------
5/31/2022 2:02:02 PM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
5/31/2022 2:05:02 PM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
5/31/2022 2:05:02 PM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
...repeat about every 3 minutes...

This is the image from my AppInsight. All Reasons are the same (Communication_Error)
![image](https://user-images.githubusercontent.com/3829760/171473754-164e22dd-f8aa-4d38-a438-2e6c31464561.png)

So how to know what kind of TransportType I should use when I create the DeviceClient Instance?

I know that if port 443 is used, the WebSocket will fail, but what is the reason for TCP failure?

When should I use AMQP or HTTP1?

## Code sample exhibiting the issue

```CSharp
 private const string Token =
            "Your Token";

        private Guid _deviceId = Guid.Parse("Your Device Id");

        private const string Hub = "Hub address";

        private DeviceClient _iotClient;

        private ConnectionStatus? _status;

        public MainWindow()
        {
            InitializeComponent();
            Closed += MainWindow_Closed;
        }

        private async void MainWindow_Closed(object sender, EventArgs e)
        {
            await DisposeClient();
        }

        private async Task DisposeClient()
        {
            if (_iotClient != null)
            {
                await _iotClient.CloseAsync();
                _iotClient.Dispose();
            }
        }

        private async void Connect_OnClick(object sender, RoutedEventArgs e)
        {
            await DisposeClient();
            Log("Start Connecting with Mqtt------------------------------");
            var auth = new DeviceAuthenticationWithToken(_deviceId.ToString(), Token);
            _iotClient = DeviceClient.Create(Hub, auth, TransportType.Mqtt);
            _iotClient.SetConnectionStatusChangesHandler(ConnectionStatusChangeHandler);
            await _iotClient.OpenAsync();
        }

        private void ConnectionStatusChangeHandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
        {
            Log($"Iot Hub d2c Status changed from [{_status}] to [{status}]. Reason [{reason}]");
        }
```

**Comment by drwill-ms** [comment]
Hi @getandplay.

MQTT TCP uses port 1883. Could it be that port is blocked by a firewall?

As for transport protocol choice, MQTT seems to be embraced by most IoT solutions and devices, so that is the protocol we are (more and more) recommending. You'd use MQTT web socket if you need to get past a firewall port restriction or use a proxy.

AMQP is a heavier protocol but does offer a better experience for disconnection errors and any other transport errors in general.

HTTP isn't really a protocol I'd advise to use or a device. I'm not sure why our SDK offers it. As it is transactional, it cannot be used to receive commands, receive twin updates, or receive cloud-to-device messages (unless your device app is willing to poll for messages).

**Comment by getandplay** [comment]
Hi @drwill-ms ,

Thanks for your comment. That is really useful for me.

Any thoughts about when it will be "blocked" and wait so long time after it tries to connect TCP (but it can't).

And any ideas for the second issue, the repeat one.

**Comment by drwill-ms** [comment]
Not sure why there are devices reconnecting every 3 minutes. I see you are providing your own SAS token generator. What is the TTL on that SAS token? Otherwise, it could be a network issue and getting [SDK logs](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs) might help identify that. Does the same thing happen over AMQP? I ask because AMQP can give better error messages in some cases.

Can you elaborate on this question?

> Any thoughts about when it will be "blocked" and wait so long time after it tries to connect TCP (but it can't).

**Comment by getandplay** [comment]
The TTL on that SAS Token is 48 hours.

I didn't get a chance to connect to customer devices to try AMQP. I will do it in the next few days, and will get SDK Logs too from those devices. Then I will add comments here.

Maybe I misunderstood something.

I create a TCPListener to use port 1883. As I understand the port should be occupied and the MQTT should be failed.
![image](https://user-images.githubusercontent.com/3829760/171504593-31de8149-4afd-49d9-b6bd-17570b3b74e3.png)

But when I try to connect IotHub with MQTT, it seems working fine.
```
2022-06-01 3:26:59 PM --------- Start Connecting with Mqtt----------------------------------Dev
2022-06-01 3:27:00 PM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
```

Did I make something wrong?

**Comment by getandplay** [comment]
>Then I found that there are some customers' devices that can't connect to IotHub with Mqtt (TCP first then Websocket).
When those devices try to connect to the IotHub with Mqtt, it will report : status: Disconnected_Retrying, reason: Communication_Error.
Then it seems like it's blocked, none ConnectionStatusChanges received anymore. (wait more than 1 hour).

> Can you elaborate on this question?
>>Any thoughts about when it will be "blocked" and wait so long time after it tries to connect TCP (but it can't).

Sorry, I didn't describe it very clearly. I know how to reproduce it now.

As you can see, I have a Connect `Button` in the above code, and when you click the button it will trigger `Connect_OnClick` method.

Reproduce steps:
1. Click Connect Button to connect the IotHub, then it will print:
    > 2022-06-01 4:26:23 PM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
2. Disable your internet, it will print:
   >  2022-06-01 4:26:30 PM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
3. keep the internet disconnected, Click Connect Button Again. It will call `DisposeClient` method and wait until the internet connects.

I know it is by design. 

But when I try to connect to IotHub with MQTT, it will use TCP firstly, if it is failed, it may (not always) have the same behavior. You can't dispose of or disconnect the instance. If it happened, the program will just wait for the DisposeAsync() method forever. I can't try to recreate an instance with AMQP or WebSocket.

**Comment by drwill-ms** [comment]
I'm confused. Are you saying you don't want the SDK to try to use MQTT TCP first?

**Comment by getandplay** [comment]
Sorry to make you confuse.

I mean I have a device that only supports Websocket (It will fail when using TCP to Connect.)

But As a developer, I don't know it only supports Websocket. So I will try TCP to connect first.  But it fails and prints
> Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
Then I try to dispose of the instance, but it is keep waiting when I call `await deviceClient.DisposeAsyc()`.

This is what I saw in my customers' devices.

**Comment by getandplay** [comment]
> You are saying you want to write a device app that will work over MQTT but you don't know if the customer's network will support TCP or Websocket, so you want to make it work either way. However, when it fails to connect over TCP the call to DisposeAsync() hangs

Correct

> If you specify TransportType.Mqtt the [SDK](https://docs.microsoft.com/dotnet/api/microsoft.azure.devices.client.transporttype?view=azure-dotnet) will try TCP and failover to Websocket automatically. Will that work for you?

I am using MQTT now, something it will block at those devices. That is why I debug on those machines and find this issue.

>DisposeAsync() simply calls CloseAsync() and then Dispose(). What if you try calling CloseAsync() directly to see if that is the cause of the hang. If it is, you might try calling it with a cancellation token that expires after a short period to avoid any possible hang. Meanwhile, I'd love to get some SDK logs from you when making that call so we can find out where it might be hanging.

Yes, CloseAsync() hangs. I am trying to connect to my customer and then will get SDK logs from their machine. We will see.

**Comment by getandplay** [comment]
Hi @drwill-ms 

I got a chance to debug on the customer's device. And grab the SDK logs.

Here is the logs , the test application print:

>6/3/2022 11:16:31 AM --------- Machine Name - DRFCRT92BQKM3
6/3/2022 11:22:52 AM --------- Start Connecting with Mqtt----------------------------------Dev
6/3/2022 11:22:53 AM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
6/3/2022 11:22:54 AM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
6/3/2022 11:45:09 AM --------- Iot Hub d2c Status changed from [] to [Disabled]. Reason [Client_Close]
6/3/2022 11:45:09 AM --------- Mqtt - disposed connection
6/3/2022 11:45:10 AM --------- Ready to connect
6/3/2022 11:45:10 AM --------- Start Connecting with Mqtt_Tcp_Only--------------------------Dev
6/3/2022 11:45:10 AM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
6/3/2022 11:45:21 AM --------- Ready to connect
6/3/2022 11:45:21 AM --------- Start Connecting with Mqtt_WebSocket_Only------------------------------Dev
6/3/2022 11:45:21 AM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
6/3/2022 11:45:27 AM --------- Iot Hub d2c Status changed from [] to [Disabled]. Reason [Client_Close]
6/3/2022 11:45:27 AM --------- Mqtt_WebSocket_Only - disposed connection
6/3/2022 11:45:28 AM --------- Ready to connect
6/3/2022 11:45:28 AM --------- Start Connecting with Mqtt----------------------------------Dev
6/3/2022 11:45:28 AM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
6/3/2022 11:45:29 AM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
6/3/2022 11:49:17 AM --------- Iot Hub d2c Status changed from [] to [Disconnected]. Reason [Retry_Expired]
6/3/2022 11:49:17 AM --------- Transient network error occurred, please retry.
6/3/2022 11:49:17 AM --------- Mqtt_Tcp_Only - disposed connection

You can see that at 11:45:28 AM, the application try to connect to IotHub with Mqtt, and it failed for TCP connection and Tried WebSocket.

After it connects for about 4 minutes, it Disconnected and said there is Network Error.

Here is the SDK Log: [iot_000001.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/8835673/iot_000001.zip)

-----------------------------------------------------------------

I debugged on another machine and find that we can't connect the IotHub with MQTT_WebSocket

Here is the logs printed by My Application:

>6/3/2022 11:39:26 AM --------- Machine Name - DRFCRT21BQKM3
6/3/2022 11:39:33 AM --------- Start Connecting with Mqtt----------------------------------Dev
6/3/2022 11:39:34 AM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
6/3/2022 11:39:47 AM --------- Sending 11:39:47 AM on port 443
6/3/2022 11:39:47 AM --------- Sent: Sending 11:39:47 AM on port 443 on port 443
6/3/2022 11:40:07 AM --------- Iot Hub d2c Status changed from [] to [Disabled]. Reason [Client_Close]
6/3/2022 11:40:07 AM --------- Mqtt - disposed connection
6/3/2022 11:40:08 AM --------- Ready to connect
6/3/2022 11:40:08 AM --------- Start Connecting with Mqtt_WebSocket_Only------------------------------Dev
6/3/2022 11:40:08 AM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]
6/3/2022 11:40:47 AM --------- Received: on port 443
6/3/2022 11:44:16 AM --------- Iot Hub d2c Status changed from [] to [Disconnected]. Reason [Retry_Expired]
6/3/2022 11:44:16 AM --------- Transient network error occurred, please retry.
6/3/2022 11:44:41 AM --------- Mqtt_WebSocket_Only - disposed connection
6/3/2022 11:44:42 AM --------- Ready to connect
6/3/2022 11:44:42 AM --------- Start Connecting with Mqtt----------------------------------Dev
6/3/2022 11:44:42 AM --------- Iot Hub d2c Status changed from [] to [Connected]. Reason [Connection_Ok]
6/3/2022 11:54:26 AM --------- Iot Hub d2c Status changed from [] to [Disabled]. Reason [Client_Close]
6/3/2022 11:54:26 AM --------- Mqtt - disposed connection
6/3/2022 11:54:27 AM --------- Ready to connect
6/3/2022 11:54:27 AM --------- Start Connecting with Mqtt_WebSocket_Only------------------------------Dev
6/3/2022 11:54:28 AM --------- Iot Hub d2c Status changed from [] to [Disconnected_Retrying]. Reason [Communication_Error]

You see I try to test whether Port 443 is open or not.  And Seems like it is working fine.

At 11:54:27 AM I tried to connect to iothub with mqtt_websocket_only, but it failed.

Here is the SDK Logs:  [iot_000001 (1).zip](https://github.com/Azure/azure-iot-sdk-csharp/files/8835694/iot_000001.1.zip)


BTW
>MQTT TCP uses port 1883.
As I can see from my tool, the remote port for MQTT_TCP is 8883. 
And the one used by WebSocket is 443.

**Comment by drwill-ms** [comment]
@getandplay Totally right about 8883. I remembered the wrong value. 1883 is for non-SSL and 8883 is for SSL connections.

I'll look over the info you provided now.

**Comment by getandplay** [comment]
@drwill-ms  sure.  my email address is chentianlong0608@gmail.com

**Comment by drwill-ms** [comment]
From our call:

Me:

1. Check out the ETL logs.
1. From logs, look for reasons for `CloseAsync()` hanging and, in the second case, why web socket fails to connect.
1. Repro TCP blocked and call `CloseAsync()` on client to repro hang.

You:

1. Cache connection status and only call `CloseAsync()` if connected. See if that doesn't unblock for now.
1. Either use built-in factory method that takes a connection string or save off the `auth` parameter to the class. Does the disconnect after 3:45 still happen?
1. Review the [DeviceReconnectionSample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs) to employ a few other strategies to avoid client ping-pong.

**Comment by drwill-ms** [comment]
Hi @getandplay -

I've finished looking through the logs. I don't see anything of interest except maybe this one error.

> The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.

In all other cases it just indicates that it couldn't connect (but it could resolve the hostname, so we know DNS is working).

I don't see anything about number 2 above, but I'll work on number 3 to see if I can't repro/debug.

Anything new on your end?

**Comment by getandplay** [comment]
Hi @drwill-ms ,

We don't have much new here. 

For now, we write the code to switch among MQTT_TCP, MQTT_WebSocket, and AMQP_TCP. 
 
If one failed, we will switch to another one.

**Comment by drwill-ms** [comment]
Small update... I write a device app to initialize with Mqtt_Tcp_Only with the port blocked. `OpenAsync()` times out and fails. After, calling `CloseAsync()` does not hang for me. I suspect there is more to the repro that this simple repro, or perhaps I've misunderstood something. Thoughts?

**Comment by getandplay** [comment]
I can repro the `CloseAsync()` hang issue in my local after I block 8883 outbound in Firewall.

So I don't know why you can't repro it.

Could you send your demo code to me? I can try it in my local.

**Comment by drwill-ms** [comment]
Sure; it is very simple code. I'm using a .net 6.0 console project.

```csharp
using System.Diagnostics;
using Microsoft.Azure.Devices.Client;

using var client = DeviceClient.CreateFromConnectionString("redacted", TransportType.Mqtt_Tcp_Only);

var sw = Stopwatch.StartNew();

try
{
    Console.WriteLine("Opening connection...");
    using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
    await client.OpenAsync(cts.Token);
}
catch (Exception ex)
{
    sw.Stop();
    Console.WriteLine($"OpenAsync failed after due to [{ex.Message}]");
}

Console.WriteLine($"OpenAsync took {sw.Elapsed}");

try
{
    Console.WriteLine("Closing connection...");
    sw.Restart();
    using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
    await client.CloseAsync(cts.Token);
}
catch (Exception ex)
{
    Console.WriteLine($"CloseAsync failed due to [{ex.Message}]");
}

Console.WriteLine($"CloseAsync took {sw.Elapsed}");
```

Output is:

```console
Opening connection...
OpenAsync failed after due to [MQTT channel open failed.]
OpenAsync took 00:00:16.2494698
Closing connection...
CloseAsync took 00:00:00.0012192
```

I'm using Windows Defender Firewall to block port 8883.

**Comment by getandplay** [comment]
I tried your code, and get the same result as yours.

Then I change to this:
```
using System.Diagnostics;
using Microsoft.Azure.Devices.Client;


using var client = DeviceClient.CreateFromConnectionString("yourConnectString", TransportType.Mqtt_Tcp_Only);

var sw = Stopwatch.StartNew();

try
{
    Console.WriteLine("Opening connection...");
    using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
    client.SetConnectionStatusChangesHandler(ConnectionStatusChangeHandler);
    await client.OpenAsync();
}
catch (Exception ex)
{
    sw.Stop();
    Console.WriteLine($"OpenAsync failed after due to [{ex.Message}]");
}

Console.WriteLine($"OpenAsync took {sw.Elapsed}");

try
{
    Console.WriteLine("Closing connection...");
    sw.Restart();
    using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
    await client.CloseAsync(cts.Token);
}
catch (Exception ex)
{
    Console.WriteLine($"CloseAsync failed due to [{ex.Message}]");
}

Console.WriteLine($"CloseAsync took {sw.Elapsed}");

void ConnectionStatusChangeHandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
{
    Console.WriteLine($"Iot Hub d2c Status changed  to [{status}]. Reason [{reason}]");
}
```

Then it hangs on OpenAsync.

>Opening connection...
>Iot Hub d2c Status changed  to [Disconnected_Retrying]. Reason [Communication_Error]

Because I am using WPF to develop the demo, So when it hangs on `OpenAsync`. 
I can still click a button to call `CloseAsync`, then it looks like it is hanging on `CloseAsync`.

**Comment by drwill-ms** [comment]
So, the only code difference is signing up for connection status updates? I'll try that to see if I can repro.

The other difference is being in a WPF app. What happens if you add `.ConfigureAwait(true);` on all the awaited calls? Does it still repro?

**Comment by getandplay** [comment]
Oh the difference is `await client.OpenAsync();` I didn't use the CancelToken, When I call OpenAsync.

**Comment by drwill-ms** [comment]
Then I wonder if it still just stuck on `OpenAsync()` which causes `CloseAsync()` to wait. Thoughts around putting an outer boundary on `OpenAsync()` with a cancellation token?

**Comment by getandplay** [comment]
>Thoughts around putting an outer boundary on OpenAsync() with a cancellation token?

Yeah, I will do that.

**Comment by getandplay** [comment]
@drwill-ms  Yeah, it can solve the handing issue.
