### ISSUE TITLE
Setting property to null does not always erase it

### ISSUE THREAD

**Issue by tiagoshibata** [Azure/azure-iot-sdk-csharp#243]
- **OS and version used:** Windows 10 Insider Preview (Version	10.0.17035 Build 17035)
- **SDK version used:** 1.5.2

# Description of the issue:
Setting a reported property to null should remove that property, [as I understand from the docs](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations). It doesn't in some situations.

# Code sample exhibiting the issue:
```cs
using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.Devices.Shared;
using System;
using System.Threading.Tasks;

namespace IotHubClient
{
    class Program
    {
        static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();
        }

        static async Task MainAsync(string[] args)
        {
            var client = DeviceClient.CreateFromConnectionString("Connection string here");

            await client.UpdateReportedPropertiesAsync(new TwinCollection
            {
                ["a"] = null
            });

            await client.UpdateReportedPropertiesAsync(new TwinCollection
            {
                ["a"] = new TwinCollection
                {
                    ["b"] = null
                }
            });

            await client.UpdateReportedPropertiesAsync(new TwinCollection
            {
                ["a"] = new TwinCollection
                {
                    ["b"] = null
                }
            });
        }
    }
}
```

Use breakpoints and observe the device twin after each call. The first call will erase `a` from the document root as expected. The second call is buggy and creates object `a` with key `b`, containing `null`, instead of creating an empty object (I expect `b` to be removed). The third call (assigning `null` to a key containing `null`) works as expected (removing `b`). It seems like the issue only repros when creating a new object with null values.

Somewhat related to #86 .

This affects me when I want to remove keys (right now I would have to first check if the object nesting the key exists before trying to remove it).

**Comment by tiagoshibata** [comment]
It repros in both reported and desired properties:

![reported](https://user-images.githubusercontent.com/5521887/33103131-581490b6-ced5-11e7-9102-fe9280a527da.png)

![desired](https://user-images.githubusercontent.com/5521887/33103133-5c59413a-ced5-11e7-9152-9286d4aae293.png)

**Comment by CIPop** [comment]
Thanks for reporting @tiagoshibata ! 
We were able to repro the issue and now need to investigate to understand why this is happening.

**Comment by zolvarga** [comment]
@tiagoshibata 

Update: It is a server side issue and I reported to the service team.
I will update you with the timeline.

Best Regards,
Zoltan

**Comment by timtay-microsoft** [comment]
Closing this issue because it isn't an SDK bug. The tests we disabled while the bug got fixed have been re-enabled, so I don't see a reason to keep this issue open

**Comment by az-iot-builder-01** [comment]
@tiagoshibata, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
