### ISSUE TITLE
Correct the usage of await/async within sample code

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#244]
- [X] A lot of samples are using Task .Wait() / .GetAwaiter().GetResult() or .Result. We need to replace these instances with proper async/await patterns.
- [ ] Use the samples from https://github.com/Azure-Samples/azure-iot-samples-csharp
- [ ] Add #region snippet1 to outline doc code snippets

**Comment by CIPop** [comment]
I'm working on moving the samples to https://github.com/Azure/azure-iot-sdk-csharp/issues/510. 

For a while at least, I will keep them in both repos.

**Comment by CIPop** [comment]
This is fixed in the other repo by https://github.com/Azure-Samples/azure-iot-samples-csharp/pull/6

**Comment by prmathur-microsoft** [comment]
@CIPop  - As per your comment above, as this is fixed I will close it for now. feel free to reopen if you see anything missing.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
