### ISSUE TITLE
[Bug Report] Update Dependancy Versions - Security Vulnerabilities

### ISSUE THREAD

**Issue by leashjay** [Azure/azure-iot-sdk-csharp#2441]
# Context 
Several packages within this SDK bring medium- to high-security vulnerabilities. 

## Affected Dependencies 
Newtonsoft.Json@12.0.3: Insecure Defaults
System.Net.Http@4.3.3: Denial of Service
System.Net.Http@4.3.0: Improper Certificate Validation 
System.Net.Http@4.3.0: Privilege Escalation
System.Net.Http@4.3.0: Information Exposure 
System.Text.RegularExpressions@4.3.0: Regular Expression Denial of Service
System.Net.Http@4.3.0: Authentication Bypass

## Resolution 
This can be resolved by updating to:
Newtonsoft.Json@13.0.1 
System.Net.Http@4.3.4
System.Text.RegularExpressions@4.3.1

**Comment by brycewang-microsoft** [comment]
Hi @leashjay, thanks for bringing this to our attention! 

Vulnerabilities of `Newtonsoft.Json` < 13.0.1 should be fixed by [this](https://github.com/Azure/azure-iot-sdk-csharp/pull/2443). 
For `System.Net.Http`, we are using the version 4.3.4 in our latest codes. 
For `System.Text.RegularExpressions`, we are not using it in our latest codes.

**Comment by brycewang-microsoft** [comment]
Hi @leashjay , thanks for bringing this to our attention! Can you please let us know which vulnerabilities scanning tool you are using, and which version of which of our packages you are referring to? 

For `System.Net.Http`, we are directly depending on its latest version 4.3.4 in our latest codes, while we are not directly depending on `System.Text.RegularExpressions`.

**Comment by leashjay** [comment]
Tool: Snyk
Version: Latest available release `Microsoft.Azure.Devices.Client 1.41.0
```
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > Newtonsoft.Json@12.0.3
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Text.RegularExpressions@4.3.0
src@1.0.0 > Microsoft.Azure.Devices.Client@1.41.0 > WindowsAzure.Storage@9.3.2 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0
```

![Snyk_MC_SDK](https://user-images.githubusercontent.com/48419288/174197121-9ef795c0-b405-4346-810d-ea6bab6e70ac.jpg)
`

**Comment by brycewang-microsoft** [comment]
For `Newtonsoft.Json`, the fix [here](https://github.com/Azure/azure-iot-sdk-csharp/pull/2443) will upgrade its version to 13.0.1.

For `WindowsAzure.Storage`, it is deprecated and we have works to remove this dependency and relevant obsolete-marked APIs. As we are only using it for the method `UploadToBlobAsync` ([ref](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.uploadtoblobasync?view=azure-dotnet)) for now, the users are encouraged to use another API that doesn't depend on this package.

**Comment by brycewang-microsoft** [comment]
FYI, we just [released ](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-07-26)the latest device client package in **v1.41.1** to include the fix.
