### ISSUE TITLE
DeviceClient open/close error most frequently with iOS 15.5

### ISSUE THREAD

**Issue by arendigossweiler** [Azure/azure-iot-sdk-csharp#2486]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64, Android 10, iOS 12.5.5, iOS 15.2, iOS 15.5
- **Application's .NET Target Framework :** net6.0, xamarin
- **Device:** Laptop, Android, iOS
- **SDK version used:** Microsoft.Azure.Devices.Client Version=1.41.0

## Description of the issue
I noticed an issue with the Microsoft.Azure.Devices.Client library when the connection to the iot hub is opened, closed, disposed and opened again several times. 

It works fine when the code is executed on a Windows 10 machine in a unit test.

If the code is executed in an app, the device client can not be opened every time without an error.

I've made tests with several smart devices and OS version. 
Here is the result:
- iPhone 6plus with iOS 12.5.5: Failed 190 of 324, **59%** error rate
- Pixel 3 XL with Android 10: Failed 173 of 262, **66%** error rate
- iPhone XR with iOS 15.2: Failed 129 of 190,  **68%** error rate
- iPhone 12 with iOS 15.5: Failed 204 of 247,  **83%** error rate

Conclusion:
It is almost impossible to reopen a DeviceClient with iOS 15.5

There are two exception messages which occur:
- Transient network error occurred, please retry.
- TLS authentication error.

All smart devices and the Windows machine were connected to the same stable wifi network.

Please take a look at the attached sample project and add your iot connection string to the IotConnectionTest class to run it successfully. It includes a Xamarin.Forms App (Android and iOS) and a Unit Test which uses the same code.

## Code sample exhibiting the issue
```
for(int i = 0; i < 10; i++)
{
  var deviceClient = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Amqp_WebSocket_Only);
  deviceClient.SetRetryPolicy(new NoRetry());
  await deviceClient.OpenAsync(CancellationToken.None);
  await Task.Delay(2000);
  await deviceClient?.CloseAsync(CancellationToken.None);
  deviceClient?.Dispose();
  deviceClient = null;
  await Task.Delay(2000);
}
```
[IotTroubleshooting.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/9063875/IotTroubleshooting.zip)

**Comment by drwill-ms** [comment]
This SDK doesn't officially [support](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/supported_platforms.md#miscellaneous-support-notes) MacOS or Xamarin as a platform yet. That said, I'd be happy to work with you to try to find out why it isn't working.

I'd like to know if the environmental correlation of the failure is MacOS or Xamarin. Could you rerun your test in a console app on MacOS and as a Xamarin app in Windows?

**Comment by drwill-ms** [comment]
I can't say why the network stack on MacOS/Xamarin is worse than vanilla MacOS or Windows/Xamarin. You might take that up with the Xamarin team.

A device app can get disconnected for many reasons and a device app would want to be resilient to them. In order to handle disconnects with the SDK, we advise customers to follow the guidance in [this device sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/main/iot-hub/Samples/device/DeviceReconnectionSample) that shows how to be aware when a disconnect occurs that the device app must handle and how to safely handle it.

**Comment by arendigossweiler** [comment]
I was able to extract all inner exception.

The exception was catched on a iPhone 12 with iOS 15.5.

The top exception type is: Mono.Security.Interface.TlsException
The top message is: "Unknown Secure Transport error `-50'."

Please take a look to the exception in my debugger:
![grafik](https://user-images.githubusercontent.com/50207295/179173862-20e559e1-f87b-49e0-ac84-2f0f2625421d.png)

**Comment by drwill-ms** [comment]
I've advised (referencing the reconnection sample) on how to alter device app code to be resilient to disconnects and where to retry operations (like `OpenAsync()`). Also, as we've found that it only repros on Mac/Xamarin and the inner exception points to Mono, there is a GitHub issue tracking that.

I'm going to close this issue as it appears there is nothing more to be done for Azure IoT SDK.
