### ISSUE TITLE
UWP version of Microsoft.Azure.Devices nuget package not compatible with Microsoft.Azure.Amqp

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#25]
If you add Microsoft.Azure.Devices 1.1.5 to a UWP project with Microsoft.Azure.Amqp 1.1.5, calls to the RegistryManager will work fine. If you upgrade Microsoft.Azure.Amqp to 2.0.2, however, you get an exception:

> System.IO.FileNotFoundException was unhandled by user code
  FileName=Microsoft.Azure.Amqp.Uwp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  HResult=-2147024894
  Message=Could not load file or assembly 'Microsoft.Azure.Amqp.Uwp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.Azure.Devices.Uwp
  StackTrace:
       at Microsoft.Azure.Devices.RegistryManager.CreateFromConnectionString(String connectionString)
       at TestClient.share.TestClient.TestConnectionState()
       at Tests.UWP.ClientTests.ConnectionStateTest()
  InnerException: 

If you do this with the .Net versions of the same packages, everything seems to work fine.

**Comment by jasmineymlo** [comment]
Hi v-tbert 

The above issue should be fixed in Microsoft.Azure.Devices 1.2.1.  Please try and let us know.

**Comment by tameraw** [comment]
@v-tbert - Fixed in nuget package. Feel free to let us know if still having issues.

**Comment by v-tbert** [comment]
If I workaround the other issue here first: [https://github.com/Azure/azure-iot-sdk-csharp/issues/21](url) I can now build against Microsoft.Azure.Amqp 2.0.2. Thanks for the quick turnaround!
