### ISSUE TITLE
[Bug Report] DeviceClient.GetFileUploadSasUriAsync returns ErrorCode:IotHubUnauthorizedAccess;Unauthorized

### ISSUE THREAD

**Issue by Skaanning** [Azure/azure-iot-sdk-csharp#2502]
# Context

- **OS, version, SKU and CPU architecture used:** any
- **Application's .NET Target Framework :** <NETVERSION> dotnet 6
- **Device:** any
- **SDK version used:** 
"Microsoft.Azure.Devices" Version="1.37.1"
"Microsoft.Azure.Devices.Client" Version="1.41.0"
"Microsoft.Azure.Devices.Provisioning.Client" Version="1.19.1"
"Microsoft.Azure.Devices.Provisioning.Transport.Mqtt" Version="1.17.1"

## Description of the issue
When I attempt to get a uri to post my blob to with `DeviceClient.GetFileUploadSasUriAsync`, I receive a Unauthorized response.

- The device is registered to the IoT Hub via the DPS using a x509 certificate. 
- The IoT hub has a file storage blob configured.
- The device reports its connected to the IoT Hub and I can send events and communicate with the iot hub normally (except the GetFileUploadSasUriAsync)

## Code sample exhibiting the issue
```C#
        X509Certificate2 certificate = await CertificateHelper.Get(_config);

       var securityProvider = new SecurityProviderX509Certificate(certificate);
       var mqtt = new ProvisioningTransportHandlerMqtt();
       var deviceProvisioningScope = _config.DeviceEnvironment.GetDeviceProvisioningScope();

       var provisioningDeviceClient = ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, deviceProvisioningScope, securityProvider, mqtt);

        DeviceRegistrationResult registrationResult = await provisioningDeviceClient.RegisterAsync();
        var auth = new DeviceAuthenticationWithX509Certificate(registrationResult.DeviceId, certificate);

        var clientOptions = new ClientOptions
        {
            SdkAssignsMessageId = SdkAssignsMessageId.WhenUnset,
            FileUploadTransportSettings = new Http1TransportSettings
            {
                ClientCertificate = auth.Certificate
            }
        };

        var deviceClient = DeviceClient.Create(registrationResult.AssignedHub, auth, TransportType.Mqtt, clientOptions);

        var fileUploadSasUriRequest = new FileUploadSasUriRequest {BlobName = "blob.txt"};
        var fileUploadSasUri = await deviceClient.GetFileUploadSasUriAsync(fileUploadSasUriRequest); // ex thrown here

```

## Console log of the issue

```
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:3463bf6629c640a4a146c2fe5fec7526-G:0-TimeStamp:07/18/2022 10:52:25"}
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.GetFileUploadSasUriAsync(FileUploadSasUriRequest request, CancellationToken cancellationToken)

```

**Comment by brycewang-microsoft** [comment]
Hi @Skaanning, I tried to reproduce your scenario with the shared codes and reported packages which you were using. It worked normally and I could get a SAS URI back. 
<br>

> The device reports its connected to the IoT Hub

Where did you observe this, from the hub side or client side (SDK side)? If the hub side, could you please set the connection status change handler by calling `SetConnectionStatusChangesHandler()` from your device client? This way we can understand the client lifetime better around the time when "UnauthorizedException" was thrown. Please refer to the [sample ](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L126)for usage. 

After setting the status change handler and logging the status in your application, please share us the logs when reproducing this issue from your side. Thanks!

**Comment by brycewang-microsoft** [comment]
@Skaanning

Could you please let us know which type of x509 certificate you were using - self or CA-signed? If CA-signed, can you change the authentication type to self-signed certs or shared access signature and test further?

**Comment by brycewang-microsoft** [comment]
> I guess it would make sense that this is actually the IoT Hub that gets an unauthorized error trying to talk to the blob store, and just returns that error to the device.

I checked with the service team and it appeared that the `UnauthorizedException` was thrown while device talking to the hub, in the Auth layer, before it got anywhere near Storage.

**Comment by Skaanning** [comment]
Hi agian @brycewang-microsoft

It is a CA-signed certificate we use. I tried changing it to be self-signed, and that works.
So I guess its something to do with the CA signed certificate that works for most operations on the DeviceClient, but not for the GetFileUploadSasUriAsync method. 
Is it some configuration / setup that I might be missing?

**Comment by brycewang-microsoft** [comment]
@Skaanning 

Thanks for testing and helping confirm! For your questions,

> So I guess its something to do with the CA signed certificate that works for most operations on the DeviceClient, but not for the GetFileUploadSasUriAsync method.

\> This "issue" was actually caused by the current limitation of the Azure IoT Hub service which does not support CA-signed cert authentication over HTTP(HTTPS) (doc [ref](https://github.com/Azure/azure-iot-sdk-csharp#iot-hub-device-sdk)).


> Only thing I can think of it that the deviceclient is setup to use MQTT, and the GetFileUploadSasUriAsync is using HTTP?

\> Yes, you are correct. As per explanation on the same documentation, "File upload requires HTTPS connection, but can be initiated from client using any protocol for other operations."


> Can it be some configuration / setup of the certificatest that I might be missing?

\> Unfortunately no, as this is a scenario not supported by the service and there's not much we can do about it via configuring in the SDK. To make this work, you can use self-signed certs or shared access signature as the authentication type. 

Let me know if you have any questions further.

**Comment by Skaanning** [comment]
@brycewang-microsoft thanks for the help, I really didn't see that this what the case.
I guess I will think about switching over to self signed ca's
