### ISSUE TITLE
Invoke Device Method fails after sixteen method calls

### ISSUE THREAD

**Issue by gagwithgaffer** [Azure/azure-iot-sdk-csharp#2557]
Hello, I first raised this issue yesterday using the Azure Q&A forum and was asked to re-post the issue here for review. Original post can be found here: [https://docs.microsoft.com/en-us/answers/questions/957930/azure-iot-hub-service-client-sdk-issue-gt-invoke-d.html](url)

Issue Reported:

Invoking a device method fails after 16qty times in a row. Yesterday I went through various troubleshooting steps and narrowed the issue down somewhat by invoking the device methods directly from the hub within the Azure portal. This was to eliminate my client project and the use of the Azure Hub Service Client being the root cause.

I also used a minimal code sample for the IOT Device for testing and still find that the device method invoke fails after exactly 16qty times it's been called.

The sample IOT Device code for receiving the device method invoke request sis shown below:

```
namespace IotDeviceClientTest
 {
     internal class Program
     {
         private static DeviceClient s_deviceClient;
         private static readonly TransportType s_transportType = TransportType.Mqtt;
    
         private static async Task Main(string[] args)
         {
             Console.WriteLine("IoT Hub Quickstarts #1 - Simulated device.");
    
             // Connect to the IoT hub using the MQTT protocol
             s_deviceClient = DeviceClient.CreateFromConnectionString("HostName=myIotHubDeviceClientConnectionString", s_transportType);
    
             // Create a handler for the direct method call
             await s_deviceClient.SetMethodHandlerAsync("SetTelemetryInterval", SetTelemetryInterval, null);
    
             Console.ReadLine();
         }
    
         private static Task<MethodResponse> SetTelemetryInterval(MethodRequest methodRequest, object userContext)
         {
             var data = Encoding.UTF8.GetString(methodRequest.Data);
    
             // Acknowlege the direct method call with a 200 success message.
             string result = $"{<!-- -->{\"result\":\"Executed direct method: {methodRequest.Name}\"}}";
    
             Console.WriteLine("");
             Console.WriteLine(result);
                
             return Task.FromResult(new MethodResponse(Encoding.UTF8.GetBytes(result), 200));
         }
     }
 }
```
Screenshot shows the portal is waiting once it's sent the 17th method invoke request:

![image](https://user-images.githubusercontent.com/51385414/183408956-6b07eea5-d767-4559-8678-474609ec29ad.png)

Screenshot shows the error message on the 17th method invoke:

![image](https://user-images.githubusercontent.com/51385414/183409014-00040d45-3e25-437b-9bce-cea5ac896aa6.png)

**Troubleshooting steps I've tried:**

- Tried registering a new IOT Device in the Azure portal, and tested invoking methods directly from the hub for that device.
- Changed the Device Id to a simple name "TestDevice1" in case the SDK didn't like the fact I was using a MAC address as the id.
- Tried experimenting with using various different Reponse Timeout periods
- I fired the first 16qty device method invokes, then waited a few mins before firing off the 17th method invoke, the 17th call still failed.

My overall conclusion so far as follows:

There is either an issue with Azure IOT Hubs for my particular account

Or there is an issue with the Azure IOT Hubs C# Device Client SDK (Microsoft.Azure.Devices.Client current ver.1.41.1 but I have tried previous versons of the SDK as well, going down as far as 1.30.0)

Or there is some limitation I'm not aware of in being able to invoke device client messages more than 16qty times in a row, in a fairly short duration of 2 seconds apart from each call (seems unlikely going by the MS throttling quotas which are well within the tolerences of my basic testing)

This issue is a bog one for me because I can't preceded with my project in not knowing what the expected cause and affect should be by invoking the device methods more than 16qty times before a failure.

**Comment by gagwithgaffer** [comment]
I've found the issue and it definetly appears to lie within the SDK. 

I did a round of tests using my same test environment, but rolling back the version of the SDK until eventually I got it working on Microsoft.Azure.Devices.Client ver 1.31.1 (on this version I tested invoking a device method 50qty times in a row) Note I rolled back the SDK, then updated again twice round, just to be confident in highlighting the last known version to be working.

Any version more recent than this gives me the issue in that invoking a device method more than 16qty times in a row causes a timeout issue:

_Details: The operation failed because the requested device isn't online or hasn't registered the direct method callback. To learn more, see https://aka.ms/iothub404103
Time (UTC): 2022-08-08T17:55:58.001871501+00:00
Tracking ID: 75572247FEA447C7B975AC71E4FB7C10-G2:-TimeStamp:2022-08-08T17:55:58.001871501+00:00_

Some of the SDK versions tested are noted below:
1.37.2 Not Working
1.35.0 Not Working
1.32.0 Not Working
1.31.2 Not Working
1.31.1 working
1.31.0 working

Using such an old version ver 1.31.0 dated October 2020 is not only bad for a production scenario, but equally this older version now introducs a new issue, although it doesnt actually stop me being able to invoke the device method multiple times, i now get the output below:

![image](https://user-images.githubusercontent.com/51385414/183485289-08d37300-b328-4626-a809-63b594eba020.png)

My guess is some significant changes were made to the SDK around this time and since then, invoking the device method more than 16qty times in a row no longer works. 

Please provide a fix, my whole project greatly depends on this working correctly, using an outdated SDK really canot be a solution for me.

Thanks

**Comment by drwill-ms** [comment]
There were [2 changes reported](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-10-8) in the device client in 1.31.2 both having to do with platform dependency management.

What .NET target is your device application?

**Comment by gagwithgaffer** [comment]
Hello, I'm using .NET Core 6.0 on the Device Client (currently testing using a Console Application)

**Comment by gagwithgaffer** [comment]
If I role back the console application to use .NET Core 3.1, Microsoft.Azure.Devices.Client ver 1.31.1 gives me the same original issue in not being able to invoke the method more than 16qty times. I then tried updating the Client SDK to the latest version 1.41. and still have the same issue. 

It looks like there curently is no solution at all to move fowards with. As a recap:

Scenario 1 .NET 6.0 with Microsoft.Azure.Devices.Client ver 1.31.1 allows multiple device mthod invokes as expected, but then presents an issue which I beleive is something to do with the older SDK not returning an request id back to Azure i.e. https://aka.ms/iothub404103

Scenario 2  .NET 6.0 with Microsoft.Azure.Devices.Client ver 1.31.2 or higher fails after 16qty method invokes with a timeout error returned to Azure

Scenario 3 .NET Core 3.1 with Microsoft.Azure.Devices.Client ver 1.31.1 or upwards fails after 16qty method invokes with a timeout error returned to Azure

**Comment by gagwithgaffer** [comment]
Also just tried .NET 5, and gives the same issues as above.

**Comment by gagwithgaffer** [comment]
A reply from the original topic posted here: https://docs.microsoft.com/en-us/answers/questions/957930/azure-iot-hub-service-client-sdk-issue-gt-invoke-d.html pointed me in the right direction, the issue was caused by including the transport type in the connection string which I had set to MQTT. 

So by not including the transport type, the connection resolves to AMQP by default and this is now working as expected. 

I since found something on the MS Docs that says "Direct methods are HTTPS-only from the cloud side and MQTT, AMQP, MQTT over WebSockets, **or AMQP over WebSockets from the device side**." https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods

I'm absolutely gutted I missed this point and realize now why it wasnt working. My apologies to the support team, I will mark this as resolved, many thanks

**Comment by drwill-ms** [comment]
@gagwithgaffer don't beat yourself up. You haven't wasted our time; there may yet be an issue for us to look at here.

> Direct methods are HTTPS-only from the cloud side and MQTT, AMQP, MQTT over WebSockets, or AMQP over WebSockets from the device side.

Hmm, the way I read this (and I think it is potentially written poorly) is that the device client should work over one of the following 4 protocols:

1. MQTT TCP
2. MQTT web sockets
3. AMQP TCP
4. AMQP web sockets

The default for the device client is AMQP which tries TCP first, then web socket if that fails.

Can you say more about the connection string specifying the transport? What did that look like?

**Comment by drwill-ms** [comment]
@gagwithgaffer, after looking at your post, I realize you just mean you pass the transport as a factory method parameter. It isn't in the connection string; I just took that statement too literally.

I've tried reproing with MQTT and I cannot make it happen with the latest version or any other version listed above.

My code looks like:

```csharp
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using CommandLine;
using Microsoft.Azure.Devices;
using Microsoft.Azure.Devices.Client;
using System.Text;

namespace DirectMethodBug
{
    public class Program
    {
        private static DeviceClient s_deviceClient;
        private static readonly Microsoft.Azure.Devices.Client.TransportType s_transportType = Microsoft.Azure.Devices.Client.TransportType.Mqtt;
        private static int count;

        public static async Task Main(params string[] args)
        {
            // Parse application parameters
            Parameters parameters = null;
            ParserResult<Parameters> result = Parser.Default.ParseArguments<Parameters>(args)
                .WithParsed(
                    parsedParams =>
                    {
                        parameters = parsedParams;
                    })
                .WithNotParsed(
                    errors =>
                    {
                        Environment.Exit(1);
                    });

            // Connect to the IoT hub using the MQTT protocol
            s_deviceClient = DeviceClient.CreateFromConnectionString(parameters.DeviceConnectionString, s_transportType);

            // Create a handler for the direct method call
            await s_deviceClient.SetMethodHandlerAsync("SetTelemetryInterval", SetTelemetryInterval, null);

            using var serviceClient = ServiceClient.CreateFromConnectionString(parameters.ServiceConnectionString);
            for (int i = 0; i < 50; ++i)
            {
                try
                {
                    CloudToDeviceMethodResult methodResult = await serviceClient.InvokeDeviceMethodAsync(
                        "drwSample",
                        new CloudToDeviceMethod("SetTelemetryInterval", TimeSpan.FromSeconds(30)));
                    Console.WriteLine($"Invocation {i} results in {methodResult.Status}, {methodResult.GetPayloadAsJson()}");
                }
                catch (Exception ex)
                {
                    ConsoleColor current = Console.ForegroundColor;
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"Invocation {i} failed due to {ex}");
                    Console.ForegroundColor = current;
                }
            }

            await s_deviceClient.CloseAsync();
            s_deviceClient.Dispose();
        }

        private static Task<MethodResponse> SetTelemetryInterval(MethodRequest methodRequest, object userContext)
        {
            string result = $"{{\"result\":\"Executed direct method: {methodRequest.Name}\"}}";
            Console.WriteLine($"Device received command {count++}");
            return Task.FromResult(new MethodResponse(Encoding.UTF8.GetBytes(result), 200));
        }
    }
}
```

Do you see anything that looks off that may cause me not to repro?

**Comment by gagwithgaffer** [comment]
> @gagwithgaffer don't beat yourself up. You haven't wasted our time; there may yet be an issue for us to look at here.
> 
> > Direct methods are HTTPS-only from the cloud side and MQTT, AMQP, MQTT over WebSockets, or AMQP over WebSockets from the device side.
> 
> Hmm, the way I read this (and I think it is potentially written poorly) is that the device client should work over one of the following 4 protocols:
> 
> 1. MQTT TCP
> 2. MQTT web sockets
> 3. AMQP TCP
> 4. AMQP web sockets
> 
> The default for the device client is AMQP which tries TCP first, then web socket if that fails.
> 
> Can you say more about the connection string specifying the transport? What did that look like?

Hi [drwill-ms](https://github.com/drwill-ms)

I agree the MS Docs wasnt entirely clear, on this occasion i hadn't really obsereved the notes well enough.

I was using the code below to set the connection string:

`private static readonly Microsoft.Azure.Devices.Client.TransportType s_transportType = Microsoft.Azure.Devices.Client.TransportType.Mqtt;`

`// Connect to the IoT hub using the MQTT protocol
            s_deviceClient = DeviceClient.CreateFromConnectionString("HostName=myhubname-iothub.azure-devices.net;DeviceId=myDeviceId;SharedAccessKey=myprimaryconnectionkey=
", s_transportType);`

As soon as I removed the transport type, everything started working nicely. By not including the transport type in the connection string, it's using AMQP as a default type. 

My final solution was forcing the connection to use AMQP over websockets as I only want my IOT Device to make outbound connections on port 443 so in a corporate environement, I have less to worry about with firewalls etc. So in actual fact, I have put the transport type back into the connection string as above, but simply specified TransportType.Amqp_WebSocket_Only as using MQTT didnt work.

I would suggest that within the SDK, if you could throw some kind of exception when someone tries to use MQTT so at least we would understand the problem much quicker. I say this on the basis that using MQTT didnt actually stop the device method invokes from working, its just that it categorically fails after 16qty calls in a row, so this would be enough to confuse anyone that doesn't test the solution enough times to find out that eventually it will timeout. Thanks

**Comment by drwill-ms** [comment]
@gagwithgaffer Yeah, you aren't passing the transport type **in** the connection string. The connection string is a parameter, and the transport type is a parameter.

I've tested with MQTT and it works for me, even with the latest SDK version, or any other SDK version you listed. I used the code above to validate. It went for 50 iterations without error. I wonder what is different about your setup.

We wouldn't put an error in for using MQTT because it is supported.

**Comment by gagwithgaffer** [comment]
> @gagwithgaffer Yeah, you aren't passing the transport type **in** the connection string. The connection string is a parameter, and the transport type is a parameter.
> 
> I've tested with MQTT and it works for me, even with the latest SDK version, or any other SDK version you listed. I used the code above to validate. It went for 50 iterations without error. I wonder what is different about your setup.
> 
> We wouldn't put an error in for using MQTT because it is supported.

Hi, below is a simple code sample I just tried again (using .NET 6 Console)

```
namespace IotDeviceClientTest
{
    internal class Program
    {
        private static DeviceClient s_deviceClient;
        private static readonly TransportType s_transportType = TransportType.Mqtt;
        private static readonly TransportType t_transportType = TransportType.Amqp_WebSocket_Only;

        static void Main(string[] args)
        {
            Console.WriteLine("Waiting for methods!");

            // This fails after 16qty runs
            //var client = DeviceClient.CreateFromConnectionString("_myPrimaryConnectionStringFromAzureIotHubPortal_", s_transportType);

            // This works OK using AMQP
            //var client = DeviceClient.CreateFromConnectionString("_myPrimaryConnectionStringFromAzureIotHubPortal_");

            // This works OK using AMQP over websockets
            var client = DeviceClient.CreateFromConnectionString("_myPrimaryConnectionStringFromAzureIotHubPortal_", t_transportType);

            client.SetMethodDefaultHandlerAsync(HandleDefaultMethods, client).ConfigureAwait(false);

            Console.WriteLine("Press a key to exit");
            Console.ReadKey();
        }

        private static int index = 0;

        private static Task<MethodResponse> HandleDefaultMethods(MethodRequest methodRequest, object userContext)
        {
            index++;

            Console.WriteLine($"Default method  #{index}: {methodRequest.Name} handled with body {methodRequest.DataAsJson}");

            return Task.FromResult(new MethodResponse(new byte[0], 200));
        }
    }
 }
```

**Comment by drwill-ms** [comment]
@gagwithgaffer where are you sending the direct method requests? Manually from the portal or from Azure IoT Explorer?

In my code (very similar to yours) I'm sending it with the service client.

**Comment by gagwithgaffer** [comment]
> @gagwithgaffer where are you sending the direct method requests? Manually from the portal or from Azure IoT Explorer?
> 
> In my code (very similar to yours) I'm sending it with the service client.

For this particluar test regime, I'm invoking direct methods directly from the IOT Hub portal in Azure, as shown below:

![image](https://user-images.githubusercontent.com/51385414/183754428-f2350ed6-59d4-41e2-87e6-64e359632c72.png)

And when it times out (in my case after switching back to MQTT) I get the below:

![image](https://user-images.githubusercontent.com/51385414/183754722-f9265ccc-8371-4c62-b596-dc09a1ec2dbf.png)

![image](https://user-images.githubusercontent.com/51385414/183754782-2321e913-ba5b-406f-a4e9-a7fcb92ba5f3.png)

The console app just shows that it stopped working after 16qty runs:

![image](https://user-images.githubusercontent.com/51385414/183754942-94548d2e-7b4e-4072-bb34-2cc444661fc2.png)

**Comment by drwill-ms** [comment]
It fails at 16 and keeps failing?

I tried the same thing using the portal and still didn't see failures even after 50 tries, using MQTT. I'm not sure why I'm unable to repro what you see.

**Comment by gagwithgaffer** [comment]
Hi, Yes it fails at 16 and keeps failing. I had been testing this over three days now, after several different iterations of code sample, trying different combinations of versions of .NET and service client SDK.

If you want to PM me a Microsoft Teams meeting I'd be happy to run through my environment. I am working away from this afternoon so not back until Friday though, but free then. 

The only one last thing I could have tried from my side was to completely delete my IOT Hub account, but really I dont think that should have been necessary and would mess things up for me. 

As you can't reproduce the issue, but using the same code sample as me then I think you'd have to see my environment as this will be a more tricky one to get to the bottom of, thanks

**Comment by ngastelum-ms** [comment]
@gagwithgaffer Hi there, I was able to repro some of what you're seeing. When using SDK version 1.31.1 and below with the 6.0 .NET target I get the same 404 error, which is understandable based on the target [framework fixes](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-10-8) in 1.31.2.

Otherwise, I do not get any errors when using .NET 6.0 with Microsoft.Azure.Devices.Client 1.31.2 and above or .NET 3.1 with any Microsoft.Azure.Devices.Client version.

My email is ngastelum @ microsoft.com, could you send me the [SDK logs](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs#readme) for this issue? Thanks

**Comment by gagwithgaffer** [comment]
> @gagwithgaffer Hi there, I was able to repro some of what you're seeing. When using SDK version 1.31.1 and below with the 6.0 .NET target I get the same 404 error, which is understandable based on the target [framework fixes](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-10-8) in 1.31.2.
> 
> Otherwise, I do not get any errors when using .NET 6.0 with Microsoft.Azure.Devices.Client 1.31.2 and above or .NET 3.1 with any Microsoft.Azure.Devices.Client version.
> 
> My email is ngastelum @ microsoft.com, could you send me the [SDK logs](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs#readme) for this issue? Thanks

Hello, I'm back home tomorrow so will get the logs together for you tomorrow evening. Regards

**Comment by drwill-ms** [comment]
@gagwithgaffer Hi again! The IoT hub service team found the issue, made a fix, and the deployment is in pre-prod.

**Comment by drwill-ms** [comment]
I'm going to close this issue down now, as the service team identified a fix and our customer has a chosen workaround.
