### ISSUE TITLE
AMQP Support in C# PCL

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-csharp#26]
_From @vslepakov on April 13, 2016 7:9_

Great to see that there is now a PCL for C#. Are us guys plan on supporting AMQP in this PCL? As far as I know only HTTP is possible now.

_Copied from original issue: Azure/azure-iot-sdks#477_

**Comment by tameraw** [comment]
_From @arturl on April 13, 2016 20:32_

Hi @vslepakov, this is on our backlog. We also welcome contributions, if you want to help out on this!

**Comment by tameraw** [comment]
_From @vslepakov on April 13, 2016 20:39_

Hi @arturl thanks, I might do just that

**Comment by tameraw** [comment]
_From @djcasey on September 29, 2016 3:44_

Any advance on this?

**Comment by tameraw** [comment]
_From @arturl on September 29, 2016 17:38_

Hi @vslepakov,
We've added AMQP support for Android -- it will show up in the next release. 
Every platform in PCL has to have a different implementation, which is why it will yet be immediately available everywhere.

**Comment by tameraw** [comment]
_From @djcasey on September 30, 2016 1:6_

Hi @arturl,
When is the next release expected?

**Comment by tameraw** [comment]
_From @arturl on September 30, 2016 17:36_

Hi @djcasey, new releases come out every couple of weeks, so I expect this to come out very soon. I'll contact the dev team and make sure they include the updated AMQP library in the next release (that's the component that has the fix).

Also note that the PCL NuGet package is no longer needed, the "regular" Azure.Devices.Client NuGet package now supports PCL.

**Comment by tameraw** [comment]
_From @djcasey on October 28, 2016 2:45_

Hi @arturl, has this feature been delayed? A new version (1.0.21) was released but doesn't appear to support AMQP on Android yet.

**Comment by tameraw** [comment]
_From @arturl on October 28, 2016 2:57_

Yes, this is delayed sorry. @olivierbloch, care to comment on this?
I'll keep the issue open so it stays on the radar.

**Comment by tameraw** [comment]
@arturl - A new package for AMQP has been released in NuGet.

**Comment by tameraw** [comment]
Work is in progress to bring this support in the client SDK.

**Comment by arturl** [comment]
This is now supported in 1.2.3 version. (To be clear: AMQP on Android only, not universally for PCL)
