### ISSUE TITLE
[Bug Report] Diagram in ProvisioningServiceClient page isn't rendering properly

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#2695]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#31173](https://github.com/Azure/azure-sdk-for-net/issues/31173).

## Details

The diagram in the `Remarks` section of this page is not comprehensible due to improper rendering. Something's wrong in the markdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12039a8-e5ea-15f2-c5b9-98e7b373e92a
* Version Independent ID: 870ace1b-4689-9e7d-42f7-443c414105d1
* Content: [ProvisioningServiceClient Class (Microsoft.Azure.Devices.Provisioning.Service) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.provisioning.service.provisioningserviceclient?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by patilsnr** [comment]
Hey @devlie @jsquire -- I noticed that the broken diagram no longer appears at all in the docs page. Do we plan to have it return? A fix for the improper rendering was checked in about a month ago and I assumed we would have to wait for a release to see it reflected on the docs website. Cheers!

**Comment by jsquire** [comment]
@patilsnr : I'm afraid that I don't have insight.   My role in this was only to triage/transfer the issue that was opened in the Azure SDK repository.
