### ISSUE TITLE
TransportType.Mqtt not implemented in UWP version of Microsoft.Azure.Devices.Client

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#27]
Mqtt transport doesn't seem to be implemented in UWP version of Microsoft.Azure.Devices.Client. I believe this means that important functionality like Direct Methods and Jobs are not supported from UWP

System.NotImplementedException was unhandled by user code
  HResult=-2147467263
  Message=Mqtt protocol is not supported
  Source=Microsoft.Azure.Devices.Client.UWP
  StackTrace:
       at Microsoft.Azure.Devices.Client.DeviceClient.CreateFromConnectionString(String connectionString, TransportType transportType, IDeviceClientPipelineBuilder pipelineBuilder)
       at TestClient.share.TestClient.TestConnectionState()
       at Tests.UWP.ClientTests.ConnectionStateTest()
  InnerException:

**Comment by arturl** [comment]
Good timing! Working on it now!

**Comment by akiraueda** [comment]
I have encountered the same issue.
{"Mqtt protocol is not supported"}

**Comment by yuri1312** [comment]
hi.

do you have any updates on this request? We're looking forward to using DeviceManagement on some IoT devices, and b\c it only supports UWP and DeviceManagement only works with MQTT, we're depending on this.

Thanks!

**Comment by arturl** [comment]
Good to know, thanks. I expect the next building (coming out Feb 10 or so) will have MQTT support for UWP.
Interested in trying out pre-release implementation? I can explain how to get the source.

**Comment by akiraueda** [comment]
Thank you for updating bug info.
Please tell me where to get the source.

**Comment by yuri1312** [comment]
yes, we'd love to try out the pre-release . is it just a matter of getting the latest dev iot SDK from github?

**Comment by rneubauer** [comment]
HI all, is it confirmed that the MQTT support for UWP support will be release din the Feb. 10th build?

It is UBER important for out projects. Really looking forward to it!

**Comment by arturl** [comment]
Sorry for delay, more info to follow soon.

**Comment by arturl** [comment]
I just checked in the implementation: https://github.com/Azure/azure-iot-sdk-csharp/commit/5bcfe263012ac9694cf661b6a9b0a85f4fed19f7
If you want to take it for a test-drive, use `arturl-uwpmqtt2` branch.

The work depends on DotNetty version 0.4.2 which should be published on nuget.org very soon (in a few days, I hope). If you can't wait, build DotNetty from source yourself: https://github.com/Azure/DotNetty (`dev` branch)

In this iteration, only MQTT over TCP (not WebSockets) is supported.

**Comment by VadimUmojo** [comment]
Hello Artur,
DotNetty 0.4.2 has been just published on nuget.org, could you please share when we could expect MQTT protocol for UWP in Microsoft.Azure.Devices.Client on nuget.org?

**Comment by arturl** [comment]
Hi @VadimUmojo, @jasmineymlo is working on it today.

**Comment by arturl** [comment]
Version 1.2.3 is available on [NuGet.org](https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/) now.

**Comment by rneubauer** [comment]
Awesome! Thanks everyone!!!

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

Umojo
Check out our Enterprise PBX Platform and Voice service for Office 365


RICK NEUBAUER
FOUNDER AND CEO
1 E. Superior St.
Suite 402
Chicago, IL 60611
Office:+13122572501
Mobile:+1 6308155300
Email:rneubauer@umojo.com
www.umojo.com
