### ISSUE TITLE
Direct method call prevents M2M message acknowledgement back to EdgeHub

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#2709]
This problem is based on this issue at edge team:
https://github.com/Azure/iotedge/issues/6662

The problem:

There are two modules, 'A' and 'B'.  'A' sends messages that are routed to 'B' as M2M messages. The message-handler in 'B' simply returns 'completed'.  Both 'A' and 'B' uses MQTT as protocol. Starting this setup everything works fine.

'B' also has a direct method call handler. Once we send a direct method call to 'B' e.g. from Azure Portal, the direct method call will be responded (the response is visible on the portal). However, going forward, 'B' does not acknowledge back the received M2M messages anymore. Again, the method handler is a simple return of 'completed', so the module 'B' program logic does not seem to have any threading related problems that makes things get stuck.

As an effect, edgeHub resends the very same message to module 'B'. Module 'B' receives the message, the message handler returns the same 'completed' result as before. However, the acknowledgement does not seem to get back to edgeHub. Because of this, edgeHub reaches a timeout and sends the same message again. This keeps repeating and module 'B' keeps receiving the same message over and over (while new messages are being accumulated in edgeHub, as it will not send new messages until this stuck previous message gets acknowledged)

Changing the protocol between module 'B' and edgeHub to AMQP solves this problem, the direct method call does not break the M2M acknowledgment of module 'B', so the M2M messages keep working as expected.

At this moment I suspect that the direct method call breaks something in the MQTT specific part of the SDK that prevents sending back acknowledgments.

The customer uses the latest released version - we have not tried to roll back to previous versions of the SDK to see if the problem still happens.

Also, the customer has a code to repro, however, based on the description above it should be easy to repro for investigation. It appeared from the customer demonstration that the problem happens every single time (right after the direct method call)

Let me know if you need more info regarding this issue

**Comment by tmahmood-microsoft** [comment]
Hi @vipeller, I was able to reproduce the issue on my end and have the fix for it in the latest SDK release. You can find the release details here: [https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-11-16](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-11-16) 

Please let me know if the issue still persists.

**Comment by tmahmood-microsoft** [comment]
Closing this optimistically. Please let us know if you can repro the issue.
