### ISSUE TITLE
DeliveryCount does not increment on message redelivery.

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/azure-iot-sdk-csharp#2737]
Windows 10 , .NET 6, DeviceClient ReceiveMessageHandler methods using the latest 1.41.2 nuget of Microsoft.Azure.Devices.Client 

## Description of the issue
On Redelivery of a c2d message, the delivery count never increments.  From the below screengrab, you can see that the message creation date, IoT hub enqueue times, message Id and correlation Id are the same while being received on the device at different times, but the delivery count is always 0.
![image](https://user-images.githubusercontent.com/5896139/191941025-78fad549-7d19-4890-82df-9bfbaea5b4b3.png)

**Comment by tmahmood-microsoft** [comment]
Hi @sourabhkrishna, thank you for bringing it to our attention. 
Could you please elaborate on your specific use case for this?
Also, it would greatly help us if you could share a code snippet for how you are redelivering the same c2d message.

**Comment by tmahmood-microsoft** [comment]
Hi @sourabhkrishna, please please elaborate on your specific use case for this?

**Comment by sourabhkrishna** [comment]
Apologies for the late response, somehow missed these notifications.  I do not have any specific use case I was just testing and kept abandoning messages on the device client to check if IoTHub redelivers it, it does redeliver but for some reason the count didn't increment.

**Comment by tmahmood-microsoft** [comment]
Hi @sourabhkrishna, thank you for your response. Yes, delivery count field was deprecated and has been recently removed in v2 preview of the .NET SDK. You can find the PR [here](https://github.com/Azure/azure-iot-sdk-csharp/pull/2856).
