### ISSUE TITLE
Add ProvisioningClient MQTT keep-alive pings

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#274]
Tracking comment from https://github.com/Azure/azure-iot-sdk-csharp/pull/248#discussion_r153377316

**Comment by CIPop** [comment]
@nberdy @tameraw We should triage this feature and ensure all SDKs have the same level of support.
/cc @rajeevmv @simonporter .

**Comment by nberdy** [comment]
@yzhong94 FYI

**Comment by drwill-ms** [comment]
Tracking in ADO.
