### ISSUE TITLE
[documentation] RegistryManager UpdateTwinAsync eTag could be "*"

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#2749]
This is a documentation request and so not adhering to the template.

When updating twins (device or module) regardless of previous state, I like to avoid providing an etag. RegistryManager.cs ([1](https://github.com/Azure/azure-iot-sdk-csharp/blob/5456fd80b9d83aa2e9ed4f9bdc45bf890943c68a/iothub/service/src/Registry/RegistryManager.cs#L53)) allows for wild card etags. But this is not documented ([2](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.updatetwinasync?view=azure-dotnet)). Is that intentional? If not, could this be documented under /summary/param/ in cs files. Or else library user is not sure if an empty string is to be provided.

**Comment by timtay-microsoft** [comment]
We're working on a v2 of this SDK and we've revamped our ETag documentation in it to make this more obvious. We probably won't bother updating the documentation in v1 for this though.
