### ISSUE TITLE
[Bug Report] Edge module token expires but does not reconnect (possibly related TLS error)

### ISSUE THREAD

**Issue by MichaelKx** [Azure/azure-iot-sdk-csharp#2778]
# Context
- Our EdgeModule runs in windows docker container:   
    dotnet/runtime:6.0.9-nanoserver-1809
    dotnet/sdk:6.0.401-nanoserver-1809
    Microsoft.Azure.Devices.Client: 1.41.2
- Device: Windows Server 2019-1809 (VMware VM)

## Description of the issue
General description: We have edge servers in our different plants on premise which are then connected to our IoT Hub in Europe. Within the edge there is the edgehub, opcpublisher-modul and our Modul. We have roled out that infrastructur in several plants (Germany, Switzerland, Hungary, and Austria). For that plants everything is working fine. But now we implement the same infrastructure in our plant in Shanghai and we have some effects that data is sometimes queued in the edgehub and then send all at once. Then everything works for a while and randomly until data is again queued. 
Here the detailed description: 

1) Sometimes (randomly) data is queued on the edge hub in Shanghai
 ![grafik](https://user-images.githubusercontent.com/102668255/192804229-9d4d04fc-6e58-42f9-aaf5-df99e673de36.png)

2) In fix intervals (every hour) the edgebub clients the a) opcpublisher and b) our modul are disconnecting, because some token expires
![grafik](https://user-images.githubusercontent.com/102668255/192804295-0e192f48-c3cc-4aeb-a033-1660d4632cbd.png)

3) After the token expires, there is a reconnect and the new token is taken, but => sometimes that doesn’t work and our Modul stays unconnected (dark blue bar = successful connect of Modul, pink bar successful connection of OPC-UA publisher). We see in this times the Modul doesn’t seem to be connected but we also see that the queuelength in the edgehub goes up (Picture 1) (how is this possible if it is not connected???) . 
![grafik](https://user-images.githubusercontent.com/102668255/192804528-d29031d1-4543-4a28-b20b-ae37b2fc1af0.png)

If we observer the logs to that times, we find the following: 
![grafik](https://user-images.githubusercontent.com/102668255/192811208-66100c8c-e9d3-443e-a880-fd3e4cabfa68.png)
here some logs: 

## Console log of the issue (I replaced the name of our Module with the boxes) 
`<4> 2022-09-28 16:40:02.912 +08:00 [WRN] - Module  edgemodule is not connected
<6> 2022-09-28 16:39:49.053 +08:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2022-09-28 16:39:02.898 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:38:02.874 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:37:33.689 +08:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 410e32e5
<4> 2022-09-28 16:37:02.871 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:36:02.844 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:35:13.188 +08:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 27a45a9a
<4> 2022-09-28 16:35:02.817 +08:00 [WRN] - Module   edgemodule is not connected
<6> 2022-09-28 16:34:54.448 +08:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2022-09-28 16:34:54.448 +08:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2022-09-28 16:34:54.448 +08:00 [INF] - Cleaned up 0 messages from queue for endpoint   edgemodule/input1 and 0 messages from message store.
<6> 2022-09-28 16:34:54.447 +08:00 [INF] - Started task to cleanup processed and stale messages for endpoint   edgemodule/input1
<6> 2022-09-28 16:34:49.043 +08:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2022-09-28 16:34:02.810 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:33:02.795 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:32:02.782 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:31:02.757 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:30:02.742 +08:00 [WRN] - Module   edgemodule is not connected
<6> 2022-09-28 16:29:49.037 +08:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2022-09-28 16:29:02.738 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:28:02.727 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:27:02.710 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:26:02.678 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:25:02.662 +08:00 [WRN] - Module   edgemodule is not connected
<6> 2022-09-28 16:24:49.032 +08:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2022-09-28 16:24:02.620 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:23:02.604 +08:00 [WRN] - Module   edgemodule is not connected
<4> 2022-09-28 16:22:02.592 +08:00 [WRN] - Module   edgemodule is not connected
`
4) We also observe that the Modul is not connected to the IoT Hub in this moments. We see that this connection is disconnected during the time the Modul is disconnected (as described above) (we think that is the main issue):
![grafik](https://user-images.githubusercontent.com/102668255/192810042-11d517b4-e220-4e98-b2d2-21776244f9dd.png)

5) We can not make many adjustments on our side. 

Our main thoughts: 
A)	The problem now is that we are very unsure about if what we observe is really the problem or just a byproduct of another bigger problem? We are not sure why this TLS handshake fail is happening at all? 
B)	Is there a chance to get the new token, before the old token expires? => we should implement that urgently if possible
C)	We are pretty sure that the problem is between the Edgehub and the IoT Hub.
Does the situation that the Edge is in Shanghai and the hub in Europe creates any difficulites we are not aware off in this context?

**Comment by timtay-microsoft** [comment]
> B) Is there a chance to get the new token, before the old token expires? => we should implement that urgently if possible

If your module is using AMQP, then it will refresh its SAS token proactively. By comparison, MQTT requires a new connection each time you want to renew the SAS token. Based on the sample code you provided over email, you can start by switching from MQTT to AMQP if you suspect the token refresh is causing problems for you

**Comment by MichaelKx** [comment]
Thank you for ur tip! We tried that last week but we had no success :/. Today is unfortunately holidays in Germany, we will follow up on that tmr morning. Do you have any tipps or a guide how to implement AMQP in the best way and what to be aware of?

**Comment by timtay-microsoft** [comment]
Switching to AMQP doesn't require any special considerations/tips. It should just be a matter of editing your existing code to pass in the below transport settings instead of the MQTT transport settings you are currently using:

```csharp
AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { amqpSetting };
ModuleClient azureModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
```

**Comment by MichaelKx** [comment]
Dear timtay, thanks for your help! We added the code this morning and test it currently.

**Comment by MichaelKx** [comment]
Thank you for your support! The edge device is running well so far with the AMQP implementation. On monday we will do the final tests with data from new machines, but the problem seems to be solved. Thanks!
