### ISSUE TITLE
In .Net Framework: Microsoft.Azure.Devices.Shared could not be found.

### ISSUE THREAD

**Issue by MartinKutz** [Azure/azure-iot-sdk-csharp#286]
- **OS and version used:** Windows 10

- **SDK version used:** <VERSION> .Net Framework 4.7

# Description of the issue:
We want to use the Azure Device Provisioning Service with X509 Certificate. Under .Net Core 2.0 everything is working fine. If I use .Net Framework 4.7 (lower versions also tried), the assembly 'Microsoft.Azure.Devices.Shared' could not be loaded. The assembly is installed without problems with nuget. 
For example the class "SecurityProviderX509Certificate" is not available.

If i reference a .Net Standard 2.0 library with this code, i get the same error:
System.TypeLoadException : Could not load type 'Microsoft.Azure.Devices.Shared.SecurityProviderX509Certificate' from assembly 'Microsoft.Azure.Devices.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

# Code sample exhibiting the issue:

    private static async Task<string> ProvisioningDeviceAsync(X509Certificate2 certificate)
        {
            using (var security = new SecurityProviderX509Certificate(certificate))
            using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
            {
                var provClient = ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, IdScope, security, transport);

                Console.WriteLine($"RegistrationID = {security.GetRegistrationID()}");
                Console.Write("ProvisioningClient RegisterAsync . . . ");

                var result = await provClient.RegisterAsync();

                Console.WriteLine($"{result.Status}");
                Console.WriteLine($"ProvisioningClient AssignedHub: {result.AssignedHub}; DeviceID: {result.DeviceId}");

                if (result.Status != ProvisioningRegistrationStatusType.Assigned)
                    throw new InvalidOperationException("Failed to Provision!");

                return result.AssignedHub;
            }
        }

# Console log of the issue:

**Comment by CIPop** [comment]
Thanks @MartinKutz . I'll give this a try. 

It looks like the existing packages have several nuspec issues.

**Comment by CIPop** [comment]
This should be fixed by #309. Please try again using the latest release.
