### ISSUE TITLE
MQTT OnMessageReceived unknown exception

### ISSUE THREAD

**Issue by oldblindman** [Azure/azure-iot-sdk-csharp#288]
A gateway service connecting the Azure Cloud to a robot
- **OS and version used:** <VERSION> Windows10 Pro latest version

- **SDK version used:** <VERSION> 5ebc5bf 

# Description of the issue:

After running 24 to 38 hours we get an unknown thread exception deep in the kernel that occurs in the following code:  https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttTransportHandler.cs

Wrapping the OnMessageReceived method contents in a try catch keeps it from crashing.

# Code sample exhibiting the issue:

Crash in the OnMessageReceived method after many hours of running.  There are no signs of memory leaks since the image does not grow in size.
# Console log of the issue:

**Comment by CIPop** [comment]
Thanks for reporting this @oldblindman! Feel free to submit a PR containing the fix.

> Wrapping the OnMessageReceived method contents in a try catch keeps it from crashing.

I assume that shouldn't be sufficient unless the error is handled somewhere else already. Is your connection retried/faulted after this exception?

**Comment by oldblindman** [comment]
Yes. It retries, and everything works fine. We have run it for five days without any errors.

Gene

Gene A. Grindstaff
Executive Subject Matter Expert, SG&I
T: 1.256.730.6983 M: 1.256.566.5376 F: 1.256.730.1717
E: mailto:gene.grindstaff@HexagonSI.com

Hexagon Safety & Infrastructure
305 Intergraph Way
Madison, AL, 35758
hexagonsafetyinfrastructure.com | LinkedIn | Facebook | Twitter
________________________________

**Comment by CIPop** [comment]
Fixed by #288,
