### ISSUE TITLE
IoT Hub DeviceClient retry logic problems

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#290]
- **OS and version used:** All

- **SDK version used:** DeviceClient

# Description of the issue:

- [ ] The RetryLogic will always throw TimeoutException instead of any of the exceptions. 
This doesn't allow the application to understand cases such as media failure (Ethernet cable unplugged).
This also exposes developers to the danger of an operation never terminating and potential memory leaks if `deviceClient.OperationTimeoutInMilliseconds = 0` when the cable is unplugged.

- [ ] CancellationTokens are not properly handled by the underlying protocols. I'm disabling passing them down from the RetryDelegatingHandler and allow the operations to terminate in the background according to the protocol library.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
