### ISSUE TITLE
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/dotnet-api-reference missing in readme.md doc

### ISSUE THREAD

**Issue by noorrocks** [Azure/azure-iot-sdk-csharp#291]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by CIPop** [comment]
The correct link should be : https://docs.microsoft.com/en-us/dotnet/api/overview/azure/iot?view=azure-dotnet

**Comment by noorrocks** [comment]
Thanks CIPop
