### ISSUE TITLE
Dispose doesn't complete with MQTT

### ISSUE THREAD

**Issue by ancaantochi** [Azure/azure-iot-sdk-csharp#2920]
# Context

- **OS, version, SKU and CPU architecture used:**  Ubuntu 20.04 x86
- **Application's .NET Target Framework :** nercoreapp 6.0 
- **Device:** Azure VM (Laptop, Raspberry PI3, Android APIv25 etc.)
- **SDK version used:** 1.36.6 (Please include the NuGet package version for all involved components)

## Description of the issue
Call to Dispose blocks with MQTT protocol, it can be consistently reproduced. 
Running edge with UpstreamProtocol as Mqtt gets into the issue where Dispose doesn't return, a stack dump has many threads in this state:

Thread (0x55):
  [Native Frames]
  System.Private.CoreLib!System.Threading.ManualResetEventSlim.Wait(int32,value class System.Threading.CancellationToken)
  System.Private.CoreLib!System.Threading.Tasks.Task.SpinThenBlockingWait(int32,value class System.Threading.CancellationToken)
  System.Private.CoreLib!System.Threading.Tasks.Task.InternalWaitCore(int32,value class System.Threading.CancellationToken)
  System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(class System.Threading.Tasks.Task)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose()
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose()
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose()
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.Dispose()
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.InternalClient.Dispose()
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.ModuleClient.Dispose(bool)
  Microsoft.Azure.Devices.Client!Microsoft.Azure.Devices.Client.ModuleClient.Dispose()

**Comment by abhipsaMisra** [comment]
Syned offline. Have not been able to reproduce this with a simple setup on a Windows machine, but will try it on Azure VM as well.
A stopgap workaround would be to call CloseAsync() before calling Dispose(). A call to CloseAsync() will move the transport layer to Closed state, so the TryStop() conditional code inside the Dispose() call will no longer need to be executed.

**Comment by abhipsaMisra** [comment]
I have not been able to reproduce this at my end.
In order to ensure clean closure of the transport layer and cleanup of necessary resources, we recommend calling `CloseAsync()` and then `Dispose()`. 
The `CloseAsync()` call will gracefully close the transport layer and stop any retry policy currently active, while the `Dispose()` call will then clean up the resources.

@ancaantochi Will this resolution work for your scenario?

**Comment by abhipsaMisra** [comment]
Synced up offline - the above resolution works so closing this issue.
