### ISSUE TITLE
azure-iot-sdk - channel close exception

### ISSUE THREAD

**Issue by poojadube32** [Azure/azure-iot-sdk-csharp#2932]
When we send concurrent request like 50-60 for registering device to IOT Hub  we are getting channel close exception as mention below but when send 2-3 request its work fine.

-------------------------------------------------------------------------
"Exception stacktrace:    at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)\r\n   
Exception message: MQTT transport exception","category":"FunctionNameTest"
Exception e: Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: MQTT transport exception\r\n ---> System.IO.IOException: Channel is closed\r\n   
-------------------------------------------------------------------------
Environment Setup: 1 instance we have for IOT , 1 DPS and 1 Premium App service plan.
-------------------------------------------------------------------------
Code : 
 using( var transport = new ProvisioningTransportHandlerMqtt(TransportFallbackType.TcpOnly) ) 
    {
        var provisioningDeviceClient = ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, idScope, security, transport);
        var result = await provisioningDeviceClient.RegisterAsync();  
}

**Comment by brycewang-microsoft** [comment]
Hi @poojadube32, thanks for bringing this to our attention. Which version of .NET SDK you were using and seeing this issue?

**Comment by poojadube32** [comment]
Hi Brycewang,

Currently we are using  .netcore 6.0 version below is the refence 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CertificateManager" Version="1.0.8" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Service" Version="1.18.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>

**Comment by brycewang-microsoft** [comment]
Thanks for sharing the runtime version, but we are caring more about the version of our **.NET SDK**, for "Microsoft.Azure.Devices.Provisioning.Client" in particular. 

You can find all of the available versions on nuget.org [here](https://www.nuget.org/packages/Microsoft.Azure.Devices.Provisioning.Client/2.0.0-preview001#versions-body-tab).
