### ISSUE TITLE
Add support for UploadToBlobAsync in UWP

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdk-csharp#3]
This should now be possible after conversion from WinRT to .NET

**Comment by sergaz-msft** [comment]
Hi @arturl . See the changes here for enabling UploadToBlobAsync in UWP:
https://github.com/Azure/azure-iot-sdk-csharp/commit/9983d018833818a130847d9f3d7b6d4c503e1bf8

This is going into the master branch soon.
Thanks!

**Comment by pandazzurro** [comment]
I try this solution but I have this error:
_Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature._

**Comment by sergaz-msft** [comment]
Hello @pandazzurro,
Thanks for trying it. Are you trying my branch or the master one? This isn't on the master branch nor nugget package yet.

If you are using my branch can you detail a bit more what is the line and class it is failing?

Thanks

**Comment by pandazzurro** [comment]
Hi @sergaz-msft, 
I commit project:
https://github.com/pandazzurro/IoTHubUWP
I use your branch.
Thanks

**Comment by sergaz-msft** [comment]
Hi @pandazzurro ,
Instead of creating the stream ca you try using it like on our sample?

```csharp
public async Task UploadFile(Windows.Storage.StorageFile file)
        {
                var fileName = file.Name;
                using (Windows.Storage.Streams.IRandomAccessStreamWithContentType stream = await file.OpenReadAsync())
                await deviceClient.UploadToBlobAsync(fileName, stream.AsStream());
        }
```
You may need to use Windows.Storage.Streams since this is a UWP app.

Also you can now use the master branch, that already has the changes.
https://github.com/Azure/azure-iot-sdk-csharp/commit/5357642bd9974914ab7b3b400ac19cbb77362a36

**Comment by pandazzurro** [comment]
Hi @sergaz-msft,
I updated my project with master dll file.
I have created one project with IoT template and one project with UWP template.

I have same error.

**Comment by pandazzurro** [comment]
Hi @sergaz-msft,
Now work for me. 
I must unlink blob account from IoTHub, then I link it again.

ConnectionString is the same but now it work!
Great! :+1: 
Good Job!

You save my session in Global Azure Bootcamp

**Comment by sergaz-msft** [comment]
Glad that you made it @pandazzurro :). You shouldn't need to relink the Azure Blob in the Portal unless it had a TTL.

Good luck with the Global Azure Bootcamp :).

All Best
