### ISSUE TITLE
[Technical Question] BYO DigitalTwin ?

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-iot-sdk-csharp#3002]
The DeviceTwin client samples provided here are confusing because you don't reference the Azure.DigitalTwins.Core.
The code in this repo shows that you are re-writing the ADT client specifically for IoT Hub integration.

To create a DigitalTwin you pass the IoTHub connection string.
`using var digitalTwinClient = DigitalTwinClient.CreateFromConnectionString(parameters.HubConnectionString);`

Does it mean that there is a DigitalTwin instance running inside IoT Hub?

**I hope there isn't.** Integration with Digital Twin is desirable but needs to be compossible. The services are already bulky. ADT needs to be integrated to IoT Hub as a full citizen service, where developers are able to add other twins that are not devices, run the twin explorer and import external ontologies.

Recommendations

- Do not include an ADT instance in IOTH, but allow for BYO instance with integration and composition.
- There should be only one DigitalTwinClient and make it IoT Hub independent.

If this feedback reads critical, is because it appears that IoT Hub is taking dependencies on ADT, we want to help to make it compossible. Hope we have an opportunity to engage in discussion.

**Comment by drwill-ms** [comment]
Hi @uriel-kluk -

It definitely is confusing. I'm sorry about that. I dislike that we used similar naming for these. :(

I'll take a stab at clearing this up, but please be aware that we don't represent the Azure Digital Twins team. We work with them and are aware of the service. Primarily we work with IoT Hub and Device Provisioning Service, but our focus is on the service and device [data-plane](https://learn.microsoft.com/azure/azure-resource-manager/management/control-plane-and-data-plane#data-plane) SDKs. If you have more questions after this, I'll see about getting someone from one of those services to engage with you.

So, what we're looking at are 2 different, but related, services based on [DTDL](https://learn.microsoft.com/azure/digital-twins/concepts-models) modeling:

## Azure IoT Hub

Azure IoT Hub is for physical devices that have some interaction with the service. They may send telemetry or accept commands. The digital twin part of it is an extension of the twin feature that they've historically had, where properties of the device can be serialized to the cloud. Cloud-based solutions can read the reported properties and, if the device supports it, request for changes. For example, you might use your phone app to change your home thermostat heating point. With the advent of plug-and-play (aka PnP), one can use DTDL to model the device's supported API, including twin properties. When viewed this way through the DigitalTwin service client, one sees the same twin data as before, but formatted as parseable DTDL (.NET [NuGet](https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/3.12.7)). For more information, see <https://learn.microsoft.com/azure/iot-develop/concepts-digital-twin>.

## Azure Digital Twins

Azure Digital Twins is (originally, at least) made for logical entities and modeling relationships between them. A traditional example would be a campus, composed of buildings, composed of floors, composed of hallways and rooms. For more information, see <https://learn.microsoft.com/azure/digital-twins/overview>.

## To your question

> Does it mean that there is a DigitalTwin instance running inside IoT Hub?

No. It is merely a re-representation of the device twins feature.

## To your recommendations

> Do not include an ADT instance in IOTH, but allow for BYO instance with integration and composition.

An ADT instance is **not** included automatically. I can't speak to the ADT team's plans, but what I have heard is consistent with the BYO user experience. I suspect there is user value in linking the logical entities with physical devices (room 42 has a thermostat and an occupancy sensor), and that will most likely be done through linking up IoT Hub and ADT services (see <https://learn.microsoft.com/azure/digital-twins/how-to-ingest-iot-hub-data>).

> There should be only one DigitalTwinClient and make it IoT Hub independent

Per above, there are two clients for the two different services (different endpoints, different data stores). Using one is not a substitute for the other. Note that while IoT Hub has both device and service data-plane clients, ADT has only service data-plane clients.

Regards,
David Williamson

**Comment by uriel-kluk** [comment]
Thanks for the response.

Could you confirm the following:
IoT Hub does not host its own ADT instance.
The DigitalTwinChange events are operations to invoke on an external ADT instance

I would like to support an architecture with roaming devices that can connect to different hubs, but backed up by a single ADT
***@***.***

I created a route from iothub to a properties event hub using the DigitalTwinChange event.

I added a simple function to extract from the eventhub and post the operations in my ADT instance
Note: The iothub DigitalTwinClient utility supports passing the patch as a string, but the ADT client doesn’t. As feedback: add the method UpdateDigitalTwinAsync using strings to the ADT client.

But the patch operations fail, rejecting the metadata.

[2022-12-05T16:40:23.855Z] Content:
[2022-12-05T16:40:23.857Z] {"error":{"code":"JsonPatchInvalid","message":"Could not resolve path /cellular/$metadata/StatusInval/desiredVersion. Please provide a valid patch document. See section on update apis in the documentation https://aka.ms/adtv2twins."}<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fadtv2twins.%2522%257d&data=05%7C01%7Ctaanderson%40microsoft.com%7Cf68b381bdc1942ea802908dad6ea41ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638058599795265061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=n83jMbif9ygFfVKdqyvq3ossrBHN5oZeIEdbmqdbmaY%3D&reserved=0>}


Do you have a sample, or suggestion on how to apply the captured operations to the external ADT? Otherwise, what is the use for the generated event?

Here is the code:


        [FunctionName("DigitalTwinProperties")]
        public static async Task Run([EventHubTrigger("digitaltwinproperties", Connection = "CSdigitaltwinproperties")] EventData[] events, ILogger log)
        {
            var exceptions = new List<Exception>();
            DigitalTwinsClient client = new DigitalTwinsClient(new Uri(uriString), new DefaultAzureCredential());
            var updateTwinData = new JsonPatchDocument();

            foreach (EventData eventData in events)
            {
                try
                {

                    var json = eventData.EventBody.ToString();
                    dynamic elements = JsonConvert.DeserializeObject(json);

                    foreach (dynamic element in elements)
                    {
                        string path = element.path;
                        object value = element.value;
                        updateTwinData.AppendReplace(path, value);
                    }
                }
                catch (Exception e)
                {
                    exceptions.Add(e);
                }
            }

            using var response = await client.UpdateDigitalTwinAsync("mytwin", updateTwinData);//throws error


            if (exceptions.Count > 1)
            {
                throw new AggregateException(exceptions);
            }

            if (exceptions.Count == 1)
            {
                throw exceptions.Single();
            }
        }

**Comment by drwill-ms** [comment]
Hi @uriel-kluk 

You wrote:
> Could you confirm the following:

## ADT instance

>IoT Hub does not host its own ADT instance.

It does not host its own ADT instance. Only the customer may provide an ADT instance.

## DigitalTwinChange events

> The DigitalTwinChange events are operations to invoke on an external ADT instance

Are you using the IoT Hub routing feature described [here](https://learn.microsoft.com/azure/iot-hub/iot-hub-devguide-messages-d2c#non-telemetry-events) for digital twin change events coming from plug-and-play devices in the hubs? It looks like it is an event to do with as you wish but keeping an ADT instance in sync may be an intended scenario.

My impression, based on the error message `Could not resolve path /cellular/$metadata/StatusInval/desiredVersion`, is that the `DigitalTwinEvent` is not an exact match for what needs to be ingested into ADT. That path is part of the twin metadata, but not the actual value. You may benefit from printing out the various payloads that are delivered to the function app and deciding which to ignore and which to process. Something like this:

```csharp
log.LogDebug($"EventData: {JsonConvert.SerializeObject(eventData)}");
```

> Do you have a sample, or suggestion on how to apply the captured operations to the external ADT? Otherwise, what is the use for the generated event?

I searched and could not find one either. I'd recommend reaching out to the Azure Digital Twins team directly. Try one of these repos and opening a GitHub issue there:

- https://github.com/Azure-Samples/azure-digital-twins-getting-started (better)
- https://github.com/Azure/azure-sdk-for-net/labels/Digital%20Twins (log issue with `Digital Twins` label).

## JsonPatchDocument vs. string parameter

> Note: The iothub DigitalTwinClient utility supports passing the patch as a string, but the ADT client doesn’t. As feedback: add the method UpdateDigitalTwinAsync using strings to the ADT client.

We're working on a v2 of the IoT Hub service client. It still accepts a string, but we have a [code sample](https://github.com/Azure/azure-iot-sdk-csharp/blob/previews/v2/iothub/service/src/DigitalTwin/DigitalTwinsClient.cs#L149-L152) showing how to do make it with the `JsonPatchDocument` utility to try to bring more parity there. That data type isn't native to our IoT Hub SDK, so we have chosen not to link to it directly, but it is the preferred way to build a patch.

You can submit feedback for the ADT service client at <https://github.com/Azure/azure-sdk-for-net/labels/Digital%20Twins> to support a string parameter option.

**Comment by uriel-kluk** [comment]
Hi David,

Yes, I am using the routing feature “Digital twin change events” from the link you sent.

I triple check, everything aligns:

The Digital Twin `itb001` matches the properties.
I believe the bug/problem is that ADT does not accept UpdateDigitalTwinAsync for the $metadata fields StatusInval,

Do I need to instantiate the Twin with all the $metadata fields?
This is the `itb001` twin for the cellular component. And it doesn’t include desiredValue

"cellular": {
        "StatusInval": 55,
        "$metadata": {
          "StatusInval": {
            "lastUpdateTime": "2022-12-06T21:39:51.1999734Z"
          }
        }
      },


This is the JSON for the device twin in IoT Hub:
    "properties": {
        "desired": {
            "cellular": {
                "__t": "c",
                "StatusInval": 66
            },


And these are the event traces

[2022-12-06T21:29:48.358Z] Host lock lease acquired by instance ID '0000000000000000000000000D355875'.
[2022-12-06T21:32:24.047Z] Executing 'DigitalTwinProperties' (Reason='(null)', Id=e411b015-4101-4c5c-b675-8034fd18a211)
[2022-12-06T21:32:24.051Z] Trigger Details: PartionId: 0, Offset: 4294970616-4294970616, EnqueueTimeUtc: 2022-12-06T21:32:23.7780000+00:00-2022-12-06T21:32:23.7780000+00:00, SequenceNumber: 85-85, Count: 1
[2022-12-06T21:32:24.159Z] DigitalTwinProperties Properties
[2022-12-06T21:32:24.162Z] [hubName, dvrgolypkiiothub] | [deviceId, itb001] | [operationTimestamp, 2022-12-06T21:32:23.4085141Z] | [iothub-message-schema, digitalTwinChangeNotification] | [opType, updateTwin] | [solutionId, $twin.tags.solutionId] | [organizationPath, Floor1/Room7/Unit6]
[2022-12-06T21:32:24.167Z] [{"op":"replace","path":"/cellular/$metadata/StatusInval/desiredValue","value":66},{"op":"replace","path":"/cellular/$metadata/StatusInval/desiredVersion","value":33}]
[2022-12-06T21:32:36.078Z] Executed 'DigitalTwinProperties' (Failed, Id=e411b015-4101-4c5c-b675-8034fd18a211, Duration=12056ms)
[2022-12-06T21:32:39.924Z] System.Private.CoreLib: Exception while executing function: DigitalTwinProperties. Azure.DigitalTwins.Core: Could not resolve path /cellular/$metadata/StatusInval/desiredVersion. Please provide a valid patch document. See section on update apis in the documentation https://aka.ms/adtv2twins.
[2022-12-06T21:32:39.941Z] Status: 400 (Bad Request)
[2022-12-06T21:32:39.955Z] ErrorCode: JsonPatchInvalid
[2022-12-06T21:32:39.957Z]
[2022-12-06T21:32:39.973Z] Content:
[2022-12-06T21:32:39.976Z] {"error":{"code":"JsonPatchInvalid","message":"Could not resolve path /cellular/$metadata/StatusInval/desiredVersion. Please provide a valid patch document. See section on update apis in the documentation https://aka.ms/adtv2twins."}<https://aka.ms/adtv2twins.%22%7d>}
[2022-12-06T21:32:39.989Z]
[2022-12-06T21:32:39.991Z] Headers:
[2022-12-06T21:32:39.992Z] Strict-Transport-Security: REDACTED
[2022-12-06T21:32:39.993Z] traceresponse: REDACTED
[2022-12-06T21:32:39.995Z] mise-correlation-id: REDACTED
[2022-12-06T21:32:40.002Z] Date: Tue, 06 Dec 2022 21:32:34 GMT
[2022-12-06T21:32:40.010Z] Content-Length: 234
[2022-12-06T21:32:40.022Z] Content-Type: application/json; charset=utf-8
[2022-12-06T21:32:40.025Z] .

**Comment by drwill-ms** [comment]
I think my subsequent reply has the relevant payload info for you. It looks like you need to filter out the "desired" property requests, and only process a subset of the device property update payload (the one with the actual value).

**Comment by drwill-ms** [comment]
@uriel-kluk happy new year to you. :) Do you have any other questions?

**Comment by uriel-kluk** [comment]
Thank you David.

We can close this issue, As feedback, the ADT team should update the code to include $metadata fields to the writable properties into the procedure that imports DTDL JSON files.

**Comment by drwill-ms** [comment]
I've shared your comment with a member of the ADT team, who may drop in to ask more questions.

Thanks!

**Comment by johngallardo** [comment]
@uriel-kluk - is the issue that you want to write $metadata/<parameter>/desiredValue? Maybe if you could provide a sample repro of what you are trying to do without the IoTHub complexity in there it would be helpful.

To your original question, ADT and IoT Hub are under the portfolio of "IoT" products in Azure, but don't have a specific requirement on each other to function. Indeed you can use ADT to model any environment you are care to and IoT hub can be used as one of several sources of data to populate your ADT graph.

**Comment by uriel-kluk** [comment]
Thank you, John.

We have a store with 100+ models and some are very complex.

As a developer, I would like to integrate IoT Hub exports for Digital Twin and preserve desired and reported properties using the patch operation provided by IoT Hub.

I don’t want to change my DTDL models to include the desired properties, instead I would like to manage the synchronization using metadata as the IoT Hub route suggest.

As discussed in this thread, the patch operation fails because models don’t support the special $metadata elements for writable properties.

If you point me to the DeserializeDigitalTwinsModelData code, we will submit a PR to decorate the model’s writable properties with the required metadata extensions.

Hope this helps.
