### ISSUE TITLE
AMQP WebSocket Tests failing with TimeoutException when the target is NetCoreApp2.0

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#302]
```
Failed	Method_DeviceReceivesMethodAndResponse_AmqpWs	Microsoft.Azure.Devices.E2ETests.MethodE2ETests.Method_DeviceReceivesMethodAndResponse_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.MethodE2ETests.Method_DeviceReceivesMethodAndResponse_AmqpWs threw exception: ...	
Failed	Twin_DeviceSetsReportedPropertyAndGetsItBack_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceSetsReportedPropertyAndGetsItBack_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceSetsReportedPropertyAndGetsItBack_AmqpWs threw exception: ...	
Failed	Twin_DeviceReportedPropertiesTcpConnRecovery_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceReportedPropertiesTcpConnRecovery_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceReportedPropertiesTcpConnRecovery_AmqpWs threw exception: ...	
Failed	Twin_DeviceReportedPropertiesGracefulShutdownRecovery_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceReportedPropertiesGracefulShutdownRecovery_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceReportedPropertiesGracefulShutdownRecovery_AmqpWs threw exception: ...	
Failed	Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_AmqpWs threw exception: ...	
Failed	Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_WithObseleteCallbackSetter_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_WithObseleteCallbackSetter_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesEvent_WithObseleteCallbackSetter_AmqpWs threw exception: ...	
Failed	Twin_ServiceSetsDesiredPropertyAndDeviceReceivesItOnNextGet_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesItOnNextGet_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_ServiceSetsDesiredPropertyAndDeviceReceivesItOnNextGet_AmqpWs threw exception: ...	
Failed	Twin_DeviceSetsReportedPropertyAndServiceReceivesIt_AmqpWs	Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceSetsReportedPropertyAndServiceReceivesIt_AmqpWs	Test method Microsoft.Azure.Devices.E2ETests.TwinE2ETests.Twin_DeviceSetsReportedPropertyAndServiceReceivesIt_AmqpWs threw exception: ...	
```

```
Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeout>b__73_2(Task t) in S:\cs\device\Microsoft.Azure.Devices.Client\DeviceClient.cs: line 883
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Devices.E2ETests.TwinE2ETests.<_Twin_DeviceSetsReportedPropertyAndServiceReceivesIt>d__52.MoveNext() in S:\cs\e2e\Microsoft.Azure.Devices.E2ETests\TwinE2ETests.cs: line 630
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Devices.E2ETests.TwinE2ETests.<Twin_DeviceSetsReportedPropertyAndServiceReceivesIt_AmqpWs>d__45.MoveNext() in S:\cs\e2e\Microsoft.Azure.Devices.E2ETests\TwinE2ETests.cs: line 363
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Creating device E2E_Twin_CSharp_d1cda84c-d47e-4635-b04d-d55f789b1870 on *********azure-devices.net
Device successfully created
```

**Comment by jenoola** [comment]
Method_DeviceReceivesMethodAndResponse_AmqpWs in 1.20.0 fails with

System.AggregateException: One or more errors occurred. (A certificate is required to complete client authentication) ---> System.Net.Http.WinHttpException: A certificate is required to complete client authentication
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.<ReadAsyncCore>d__21.MoveNext() in C:\Users\ebelouso\source\repos\AzureIoT\azure-iot-sdk-csharp\iothub\device\src\Common\Amqp\ClientWebSocketTransport.cs:line 149
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.WinHttpException (0x80072F0C): A certificate is required to complete client authentication
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.<ReadAsyncCore>d__21.MoveNext() in C:\Users\ebelouso\source\repos\AzureIoT\azure-iot-sdk-csharp\iothub\device\src\Common\Amqp\ClientWebSocketTransport.cs:line 149<---
, AmqpLogError:).

**Comment by abhipsaMisra** [comment]
As mentioned above, websocket tests fail with `System.Net.Http.WinHttpException: A certificate is required to complete client authentication`
This is because of implementation gap in .NET Core 2.0. It has been fixed with .NET Core 2.1
Reference issue [here](https://github.com/dotnet/corefx/issues/20191).

**Comment by abhipsaMisra** [comment]
NetCoreApp2.0 went out of support on October 1, 2018. We currently support NetCoreApp2.1; which does not have the above issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, @jenoola, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
