### ISSUE TITLE
ISO 8601 date strings are modified in cloud to device method results

### ISSUE THREAD

**Issue by pihai** [Azure/azure-iot-sdk-csharp#3093]
# Context

- **SDK version used:** Microsoft.Azure.Devices 1.38.2

## Description of the issue
If a `DateTimeOffest` formatted as ISO 8601 string is used in a `CloudToDeviceMethodResult` then the SDK messes with the date, like removing trailing zeros.

## Code sample exhibiting the issue
```csharp
using System.Globalization;
using System.Text;
using Microsoft.Azure.Devices;
using Microsoft.Azure.Devices.Client;
using Newtonsoft.Json;

const string serviceConnectionString = "<TODO>";
const string deviceConnectionString = "<TODO>";

var deviceId = Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.Create(deviceConnectionString).DeviceId;
const string methodName = "test";
var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, Microsoft.Azure.Devices.Client.TransportType.Amqp_WebSocket_Only);

var date = new DateTimeOffset(638107582284599400, TimeSpan.FromHours(1));
var responseJson = JsonConvert.SerializeObject(new MyDto { MyIso8601Date = date.ToString("o", CultureInfo.InvariantCulture) });
var responseBytes = Encoding.UTF8.GetBytes(responseJson);

await deviceClient.SetMethodHandlerAsync(
    methodName, 
    async (request, context) => new MethodResponse(responseBytes, 0),
    null);

var serviceClient = ServiceClient.CreateFromConnectionString(serviceConnectionString, Microsoft.Azure.Devices.TransportType.Amqp_WebSocket_Only);

var result = await serviceClient.InvokeDeviceMethodAsync(deviceId, new CloudToDeviceMethod(methodName).SetPayloadJson("{}"));

var actualResponse = result.GetPayloadAsJson();

Console.WriteLine(responseJson);
Console.WriteLine(actualResponse);

public class MyDto
{
    public string MyIso8601Date { get; set; }
}
```

Outputs:
```
{"MyIso8601Date":"2023-01-31T10:37:08.4599400+01:00"}
{"MyIso8601Date":"2023-01-31T10:37:08.45994+01:00"}
```

Notice that the trailing zeros are gone. This is problematic when the string is converted back into a `DateTimeOffset` using the same format identifier because a `FormatException` is thrown:

```csharp
DateTimeOffset.ParseExact("2023-01-31T10:37:08.45994+01:00", "o", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
```

I think that the problem originates from here, where the response gets deserialized with Newtonsoft.Json: https://github.com/Azure/azure-iot-sdk-csharp/blob/27685d1898e96bf69870adc673baf1a2e9b39407/common/src/service/HttpClientHelper.cs#L314

It is a known and unfortunate behavior of Newtonsoft.Json: https://github.com/JamesNK/Newtonsoft.Json/issues/862

In my opinion the SDK should not alter the strings returned from the device methods.

**Comment by brycewang-microsoft** [comment]
Hi @pihai, thanks for bringing this to our attention! The fix has been merged in, and I will update this thread again once we ship the release.

**Comment by drwill-ms** [comment]
The fix is available in the latest release https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2023-03-13-v2preview

**Comment by drwill-ms** [comment]
My mistake, this was only shipped in v2 preview so far.

**Comment by brycewang-microsoft** [comment]
Hi @pihai, the fix has been shipped in Microsoft.Azure.Devices [1.39.0](https://www.nuget.org/packages/Microsoft.Azure.Devices/1.39.0) with the latest [release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2023-05-01). I am closing this issue.
