### ISSUE TITLE
Stable version of V2 clients

### ISSUE THREAD

**Issue by ravi-mungalpara** [Azure/azure-iot-sdk-csharp#3094]
Hi,

When can we expect stable version(GA) of [V2 clients](https://github.com/Azure/azure-iot-sdk-csharp#v2-clients-release-notice). Also wanted to understand is there any issue while using [2.0.0-preview001](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-10-14-v2preview).

thanks in advance.

**Comment by andyk-ms** [comment]
First of all, thanks for your interest in this preview client.

If you plan to test it out, please note that there is now an updated preview002 version with the latest updates.

At this time, there is no firm GA timeframe yet. Our goal is to release V2 Client as soon as possible when we address all the feedback received from users like yourself. As a reminder, preview release is not meant for production use, given there can be breaking change is future updates to address user feedback.

Should you have any feedback on the V2 clients, please let us know and we still have some time to consider your inputs.

Thanks.
