### ISSUE TITLE
UWP Application NuGet upgrade from 1.6.0 to 1.6.1  fails

### ISSUE THREAD

**Issue by KiwiBryn** [Azure/azure-iot-sdk-csharp#310]
Hi

I'm building background application for Windows 10 IoT core and found I couldn't upgrade NuGet package Microsoft.Azure.Devices.Client; from version 1.6.0 to 1.6.1

Figured problem was most probably in my code so I went back to 

https://github.com/ms-iot/samples/tree/develop/Azure/HelloCloud.Headless

For a working example but this failed as well.

What am I missing?

@KiwiBryn

From the output window after failed upgrade

Running restore with 8 concurrent jobs.
Reading project file C:\Users\bryn.lewis\Downloads\Windows10IoT\CS\HelloCloud.csproj.
Restoring packages for C:\Users\bryn.lewis\Downloads\Windows10IoT\CS\project.json...
Restoring packages for UAP,Version=v10.0.15063...
Resolving conflicts for UAP,Version=v10.0.15063...
Scanning packages for runtime.json files...
Merging in runtimes defined in package/Microsoft.NETCore.UniversalWindowsPlatform 6.0.5.
Merging in runtimes defined in package/Microsoft.NETCore.Runtime.CoreCLR 1.0.3.
Merging in runtimes defined in package/Microsoft.NETCore.Platforms 1.1.0.
Merging in runtimes defined in package/Microsoft.NETCore.Jit 1.0.3.
Merging in runtimes defined in package/Microsoft.NETCore.Windows.ApiSets 1.0.1.
Merging in runtimes defined in package/Microsoft.NETCore.Targets 1.1.0.
Restoring packages for UAP,Version=v10.0.15063/win10-arm...
Resolving conflicts for UAP,Version=v10.0.15063/win10-arm...
Restoring packages for UAP,Version=v10.0.15063/win10-arm-aot...
Resolving conflicts for UAP,Version=v10.0.15063/win10-arm-aot...
Restoring packages for UAP,Version=v10.0.15063/win10-x64...
Resolving conflicts for UAP,Version=v10.0.15063/win10-x64...
Restoring packages for UAP,Version=v10.0.15063/win10-x64-aot...
Resolving conflicts for UAP,Version=v10.0.15063/win10-x64-aot...
Restoring packages for UAP,Version=v10.0.15063/win10-x86...
Resolving conflicts for UAP,Version=v10.0.15063/win10-x86...
Restoring packages for UAP,Version=v10.0.15063/win10-x86-aot...
Resolving conflicts for UAP,Version=v10.0.15063/win10-x86-aot...
Checking compatibility of packages on UAP,Version=v10.0.15063.
...
Checking compatibility for runtime.win7.System.Private.Uri 4.3.0 with UAP,Version=v10.0.15063 (win10-arm).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0.15063, but there is no run-time assembly compatible with win10-arm.
Incompatible packages: 1
...
Checking compatibility for runtime.win7.System.Private.Uri 4.3.0 with UAP,Version=v10.0.15063 (win10-arm-aot).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0.15063, but there is no run-time assembly compatible with win10-arm-aot.
Incompatible packages: 1
...
Checking compatibility for runtime.win7.System.Private.Uri 4.3.0 with UAP,Version=v10.0.15063 (win10-x86).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0.15063, but there is no run-time assembly compatible with win10-x86.
Incompatible packages: 1
...
Checking compatibility for System.ComponentModel 4.3.0 with UAP,Version=v10.0.15063 (win10-x86-aot).
Checking compatibility for runtime.win10-x86-aot.runtime.native.System.IO.Compression 4.0.1 with UAP,Version=v10.0.15063 (win10-x86-aot).
Checking compatibility for runtime.win7.System.Private.Uri 4.3.0 with UAP,Version=v10.0.15063 (win10-x86-aot).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0.15063, but there is no run-time assembly compatible with win10-x86-aot.
Incompatible packages: 1
Package restore failed. Rolling back package changes for 'HelloCloud'.
Time Elapsed: 00:00:01.6538440
========== Finished ==========

**Comment by jasmineymlo** [comment]
I tried to repro by upgrading the UWP sample from 1.6.0 to 1.6.1 and it works fine.  I have both 10.0.16299.0 and 10.0.15063.0 Windows 10 SDK for UWP installed...not sure if an upgrade on VS will help with your issue... Try with our sample to do an upgrade on your machine to see how it looks like.

**Comment by KiwiBryn** [comment]
Hi

I found the issue when doing RPI deployments, will try repro to this evening

Bryn

**Comment by ZingPow** [comment]
On my Raspberry Pi device using 1.6.0 this works

var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
var message =  new Message(Encoding.ASCII.GetBytes(messageString));
await _deviceClient.SendEventAsync(message);

but in 1.6.1 you get two reference errors

CS7069	Reference to type 'Stream' claims it is defined in 'System.Runtime', but it could not be found
CS7069	Reference to type 'Task' claims it is defined in 'System.Runtime', but it could not be found

could be a helper to finding out the problem.

**Comment by KiwiBryn** [comment]
That's what I was getting with 1.6.1+ a lot of messages like this (Build & deploy to RPI was fine with 1.6.0)

Warning		Found conflicts between different versions of "System.Runtime.InteropServices.RuntimeInformation" that could not be resolved.

**Comment by jasmineymlo** [comment]
@KiwiBryn The latest release (1.6.1) has support for UWP SDKs 10.0.16299.0 and above only. This allows us to rely on the .Net Core 2.0 implementation which adds a number of missing APIs and fixes a lot of issues for UWP. (<TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>)
The latest Windows IoT Core is at the same version: https://developer.microsoft.com/en-us/windows/iot/Downloads (16299.15).

**Comment by LeivoSepp** [comment]
My solution doesnt work as well with 1.6.1
exactly after upgrading to 1.6.1 the code ha red lines under following commands:
await **receiveDeviceClient.OpenAsync()**;
                Message receivedMessage = await **receiveDeviceClient.ReceiveAsync()**;
                if (receivedMessage?.Properties.Count > 0)
                {
                    string receivedText = Encoding.ASCII.GetString(receivedMessage.GetBytes());
                    ProcessCommand(receivedText);
                    await **receiveDeviceClient.CompleteAsync**(receivedMessage);
                }

And also in another place:

var message = new **Message**(Encoding.ASCII.GetBytes(messageJson));
                var azureDevice = _deviceClient.HomeControllerDeviceClient();
                await **azureDevice.SendEventAsync**(message);

The error is something like this: 
Error	CS7069	Reference to type 'Task' claims it is defined in 'System.Runtime', but it could not be found.

How to solve this?
With 1.6.0 everything is OK.

**Comment by CIPop** [comment]
@LeivoSepp I've upgraded to the latest Visual Studio 2017 and was able to create both a UWP UI application and a Windows IoT UWP application. I've tested that sending Telemetry works as expected for all but AMQP + WS (requires further investigation).

The Task reference sounds like incorrect NuGet configuration (you may be referencing extra NuGets that are not required or using an older csproj file format). 

The best way I know to have the latest csproj file format is to create a new UWP solution and manually add all your source files. 

You should only add references to libraries that your application actually uses (e.g. don't reference System.Threading). Here are the two package references that I have tested with:

```XML
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Devices.Client">
      <Version>1.6.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.6</Version>
    </PackageReference>
  </ItemGroup>
```

Closing for now. If you're still hitting this issue, please reopen, attaching a ZIP file containing the simplest VS UWP solution exhibiting the problem.
