### ISSUE TITLE
Can't use SDK from Service Fabric

### ISSUE THREAD

**Issue by skyflyer** [Azure/azure-iot-sdk-csharp#313]
- **OS and version used:** Windows 10 and Azure Service Fabric

- **SDK version used:** Microsoft.Azure.Devices 1.5.0  (latest from NuGet)

# Description of the issue:
I have configured IoT hub to forward messages to ServiceBus queue, where messages get processed. The worker then uses IoT Hub SDK to send messages to devices. While initializing the IoT hub client, it fails with the following exception (this happens if I run the code on a local Service Fabric dev cluster in windows 10):

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.Azure.Devices.AmqpServiceClient..ctor(IotHubConnectionString iotHubConnectionString, Boolean useWebSocketOnly)
   at Microsoft.Azure.Devices.ServiceClient.CreateFromConnectionString(String connectionString)
   at Stateless1.ServiceBusResponder.StartMessageReceiver() in C:\work\MessageResponder\Stateless1\ServiceBusResponder.cs:line 91
```
I'm not sure what's wrong in the Azure Service Fabric as logging is pretty much non-existent there and the service creates the client in the initial phase -- it might be something else completely.

# Code sample exhibiting the issue:

```c#
// iotHubConnectionString is read from a config file
iotHubClient = ServiceClient.CreateFromConnectionString(iotHubConnectionString, Microsoft.Azure.Devices.TransportType.Amqp);
```

# Console log of the issue:

The stacktrace from the log file is pasted above. The console version, executed directly (not via service fabric) works.

**Comment by skyflyer** [comment]
Found out what was going on. It is all related to dotnet/standard#328 and dotnet/standard#481.

The `System.Net.Http` assembly that the SDK lib depends on wasn't properly resolved. I removed automatically generated binding redirects, added a custom binding redirect to use the platform's `System.Net.Http` assembly and referenced platform's assembly in the service project. It now works in Service Fabric also.

Note that this was happening with .NET 4.6.x and 4.7.1.

**Comment by CIPop** [comment]
Thanks for documenting this workaround @skyflyer ! 
@davidsh @karelz FYI

**Comment by karelz** [comment]
I would expect automatically generated bindings to work properly.
@skyflyer do you know how to get into the "bad state" with VS projects? (ideally starting with a HelloWorld style app/lib) I'd be interested to dig deeper into it, if it is not one off.

**Comment by skyflyer** [comment]
@karelz, I was using VS 2017 (latest update) and:

1. File -> New Project -> Console project (first it was .NET 4.6.1, later on 4.7.1)
1. Then added a bunch of NuGet packages for Microsoft.Configuration (to configure via JSON file), Microsoft.Devices, Serilog, etc.). The list is below.
1. Build and run locally, where it worked.  (which is strange)
1. It failed on Service Fabric.

The packages I added were:
* Microsoft.ApplicationInsights
* Microsoft.Azure.Amqp
* Microsoft.Azure.Devices
* Microsoft.Azure.ServiceBus
* Microsoft.Extensions.Configuration.Json
* Serilog.Sinks.Console
* Serilog.Sinks.RollingFile

If you go through the linked issues it will make sense once you read what's going on under the hood, but it was quite puzzling as it partially worked (locally without service fabric). I'm still not sure why is that, but...
