### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.2.1.0

### ISSUE THREAD

**Issue by mmu69** [Azure/azure-iot-sdk-csharp#314]
- **Raspberry PI 3 10.0.16299.125->

- **SDK version used:** <Microsoft.Azure.Devices.Client 1.5.0 ... 1.6.0> 

# Description of the issue:
Build and deploy without issues, error at runtime at DeviceClient.Create

# Code sample exhibiting the issue:

using Microsoft.Azure.Devices.Client;
deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(deviceName, deviceKey));

# Console log of the issue:
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by jasmineymlo** [comment]
Just to make sure that the target version of your project has the correct one (16299)?
"SDK version used: <Microsoft.Azure.Devices.Client 1.5.0 ... 1.6.0> "  Do you mean you are trying to upgrade from 1.5.0 to 1.6.0 and find this issue?  Was it all fine with 1.5.0?  Thanks.

**Comment by cameronphillips** [comment]
Had exactly the same issue...set your Target and Minimum Versions to Build 16299 in Properties > Library, you should be able to build and deploy assuming this is UWP.

**Comment by CIPop** [comment]
Note that with the v1.6.1 release, the minimum version required for UWP is `10.0.16299.0`. 
I've updated several dependencies in the latest release. Could you give that a try?

**Comment by CIPop** [comment]
@mmu69 closing for now. Please reopen if you're still seeing this issue.
