### ISSUE TITLE
[feature request] Use token credentials for ProvisioningServiceClient

### ISSUE THREAD

**Issue by lukasbrun** [Azure/azure-iot-sdk-csharp#3143]
**Is your feature request related to a problem? Please describe.**
The IoT Device SDK allows creation of the RegistryManager for the IoT Hub by using Token Credentials. This option would be great to have on the ProvisioningServiceClient for the DPS as well, as using the connection string is discouraged by company policy due to security concerns.

**Describe the solution you'd like**
A way of instantiating the ProvisioningServiceClient from Token Credentials, e.g. a constructor or a factory method.

**Comment by mburumaxwell** [comment]
+1 on v2 also

**Comment by drwill-ms** [comment]
That feature is currently in [preview](https://learn.microsoft.com/en-us/azure/iot-dps/concepts-control-access-dps).

<https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2022-3-24>

Look for package Microsoft.Azure.Devices.Provisioning.Service version 1.19.1-preview-001.

Regards,
David

**Comment by mburumaxwell** [comment]
Thanks for the pointer. Could this be added to the V2 preview or does the feature on Azure have to GA first?

**Comment by drwill-ms** [comment]
@mburumaxwell it would have to be GA in the Azure service first.

Our v2 preview is GA features only as we'll ship it independently of service versions or timelines.

**Comment by mburumaxwell** [comment]
Thanks. It makes sense.
