### ISSUE TITLE
[Technical Question] Interpreting the '404' when status code '101' was expected error message

### ISSUE THREAD

**Issue by haledv** [Azure/azure-iot-sdk-csharp#3144]
Hi,

what would be a good way to debug those error messages returned by the SDK, in terms of connectivity problems. For example, we are in a Enterprise Enviroment, which has strong regulations (firewalls, proxys etc). Running our IoT .net core App (with the latest SDK) on a windows server has sometimes some challenges, as we can't interpret what's the exact Problem with the connection. In our latest case, the AmqpClientConnection.CreateClientWebSocketAsync(...) Method throws an System AggregateException (AMQP  transport exception)-> WebSocketException, which states: "The server returned status code '404', when status code  '101' was excepted.  

As you could read in the error message, we use AMQP over Websockets as TransportProtocol.  The app with the same configuration runs absolutly fine on any other PC, but it seems to have Problems with this one.

Beside turning on Wireshark and deepdiving in the connections, I don't see any other solution to finding out what the issue is? The Microsoft documentation states that port 443 needs to be open and that's the "only" thing. 

Is there any kind of more detailed documentation or tooling that would help here? Connectivity tester for example?

I am wondering also, if 404 is the right code returned in this exception, as it is indicating that something is maybe wrong with the Provisioning, but it's absolutely fine and exists and works. 

Thank you!

**Comment by abhipsaMisra** [comment]
Thank you for your question.
We except our APIs to throw exceptions that can be interpreted reliably by users, eg. by exposing an error code or specific error type on the exception returned. However, it looks like for your scenario you are receiving an AggregateException instead.
Could you share some additional details so we can assist you better?

- Name and version of the client used
- A code snippet that throws this exception
- Stacktrace or SDK logs when this exception was encountered.

The steps for collecting SDK logs are here: https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs

**Comment by abhipsaMisra** [comment]
@haledv Are you still having issues with the above scenario?

**Comment by drwill-ms** [comment]
Closing as inactive. Feel free to reopen if you are available @haledv.
