### ISSUE TITLE
[UWP] Compile to .net native ---> application crash

### ISSUE THREAD

**Issue by IotCore-Developer** [Azure/azure-iot-sdk-csharp#315]
Windows 10 fall creator
SDK fall creator

Client devices 1.6.1

When I include package version 1.6.1 and then compile using .net native i can't run my application anymore.
Entry point not found is the error.

including the package is enough to get this startup error.

[App4.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1596110/App4.zip)

**Comment by jasmineymlo** [comment]
I downloaded the app provided and am able to run it.  I build it on x64 debug.  Do I need to modify anything on the project to get a repro?

**Comment by IotCore-Developer** [comment]
Hi

You need to build release (.net Native) startup then fails.

Thx

On Friday, January 5, 2018, jasmineymlo <notifications@github.com> wrote:
> I downloaded the app provided and am able to run it. I build it on x64
debug. Do I need to modify anything on the project to get a repro?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/zYhQJdzDg0K4yShw48TWWGaeB61AFfsMljYGdMzGNQDh9CKYa8EQeWa_0a5GctgpKmAgc7HK86zA-zFcWPUXKpIqWs0hDiL33pxK03uCXXuWR35QpwcpWvWmIA1QWimhBTsbMOk_jAu8j1tKq2zFVcAh_4jU9A=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvV_dZXav0PWS5Z7qZXd__2reCgjvbks5tHWdagaJpZM4RQFfT.gif>

**Comment by IotCore-Developer** [comment]
KEY_VALUES_STRING: 1

    Key  : CLR.System.IO.FileNotFoundException._fileName
    Value: System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

    Key  : CLR.System.IO.FileNotFoundException._message
    Value: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by jasmineymlo** [comment]
@IotCore-Developer, it repro with Release build.  We will take a look at it.  Thanks for filing the issue.

**Comment by IotCore-Developer** [comment]
Thank you

I also placed a comment concerning the details.

Best regards

On Monday, January 8, 2018, jasmineymlo <notifications@github.com> wrote:
> @IotCore-Developer, it repro with Release build. We will take a look at
it. Thanks for filing the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/RBhdqVHJjWAh1L2D-UyEUz1T3Ne4u46ipgeflWtAbCKepKatZPnW3eeVmufAOKkDHW9K6hF7KEqCmdMDhvV_ThKljdxRHbgwMiLNW74E33czRJlhBkDQ6tajqVhdoGbNxXGkdZ7IyVeas13SHiTLiKaBjS7Kfw=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvVzA6vhOeBAXe2xqyZLKJpnRrtfQPks5tIonigaJpZM4RQFfT.gif>

**Comment by IotCore-Developer** [comment]
Hi Jasmineymlo,

Van you give me An estimation of the planning on solving this bug?
I need to update some customers on that but then i need to Be able to
compile Native.

Best regards

On Monday, January 8, 2018, jasmineymlo <notifications@github.com> wrote:
> @IotCore-Developer, it repro with Release build. We will take a look at
it. Thanks for filing the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/RBhdqVHJjWAh1L2D-UyEUz1T3Ne4u46ipgeflWtAbCKepKatZPnW3eeVmufAOKkDHW9K6hF7KEqCmdMDhvV_ThKljdxRHbgwMiLNW74E33czRJlhBkDQ6tajqVhdoGbNxXGkdZ7IyVeas13SHiTLiKaBjS7Kfw=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvVzA6vhOeBAXe2xqyZLKJpnRrtfQPks5tIonigaJpZM4RQFfT.gif>

**Comment by CIPop** [comment]
> Can you give me An estimation of the planning on solving this bug?
I need to update some customers on that but then i need to Be able to
compile Native.

@IotCore-Developer I'm currently investigating this issue. Since this is not happening in Debug mode, I'll include the UWP AOT compiler team.

**Comment by IotCore-Developer** [comment]
If you’ll need some information I’ll be glad to assist you.

Sent from Mail for Windows 10

**Comment by CIPop** [comment]
Thanks @IotCore-Developer.
I've made some progress with help from someone in ILC: The application fails to load one of the native Windows crypto libraries.
Will keep you posted as we make more progress on this.

**Comment by IotCore-Developer** [comment]
Ok thx for the update

On Tuesday, January 30, 2018, Cristian Pop <notifications@github.com> wrote:
> Thanks @IotCore-Developer.
> I've made some progress with help from someone in ILC: The application
fails to load one of the native Windows crypto libraries.
> Will keep you posted as we make more progress on this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/fHxBMD0h1_12l5bWJ8RNo-YOxs1v4viq-P0_Xi7sRu8YAivjrmOK4maEU5OhL-pAzsJnZfIPAvKKq5e7V1QMkxnXH6g3V6OnlysUp-YPxsJrIBZ2Erlel9Dw4YQ9_581ZSVDrAFcEdf6LvBkoW0Jms0w-atf_w=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvV9JNQHusHSoFRe-eukvGv5G-HdDzks5tPov3gaJpZM4RQFfT.gif>

**Comment by CIPop** [comment]
This is caused by https://github.com/AArnott/PCLCrypto/issues/137. 
I'm following up with both ILC and @aarnott offline.

As a future solution we are considering removing the PCLCrypto dependency and switching to netstandard2.0. (That is a bigger work-item requiring some assessment of all the current #ifdefs for UWP/Xamarin.)

**Comment by AArnott** [comment]
I'm not sure how we can say that it's caused by AArnott/PCLCrypto#137, given that issue has no root cause. Given that this is a suddenly new issue and PCLCrypto hasn't changed, I daresay this is more likely to be a bug in the AOT compiler or the Windows UWP libraries. I'll investigate a bit thought to see if I can figure out which it is.

**Comment by AArnott** [comment]
Ok, I see @CIPop already put all the logs into AArnott/PCLCrypto#137 that we need to see that IMO this is a UWP WinOS bug rather than anything we can fix within PCLCrypto.

**Comment by IotCore-Developer** [comment]
What Will Be the prognose on a real solution because since version 1.2.2
this is a problem and I need to update my customers.
I can't tell them they have to wait another half year

On Wednesday, January 31, 2018, Cristian Pop <notifications@github.com>
wrote:
> This is caused by AArnott/PCLCrypto#137.
> I'm following up with both ILC and @AArnott offline.
>
> As a future solution we are considering removing the PCLCrypto dependency
and switching to netstandard2.0. (That is a bigger work-item requiring some
assessment of all the current #ifdefs for UWP/Xamarin.)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/HuZjL677Tw2nIkaEHjV-rMKojnwWYJS18f3RN6t9tzi3JpBeeLYLxctdm_MIajs1QHj10lb_f56nq4YN1eT9vAk6y4Yy0vy9nVtQhh8cInuWF0UARCeEb2eCy7AV0fomsZgIaHcX4XyY0BtI3Qf23XRcWMnvWw=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvV4S1Lw-fEIs-nRq8vgXpbBkDPDS6ks5tP8p1gaJpZM4RQFfT.gif>

**Comment by AArnott** [comment]
@IotCore-Developer "version 1.2.2" of what? The Windows SDK?

**Comment by CIPop** [comment]
> @IotCore-Developer "version 1.2.2" of what? The Windows SDK?

@AArnott it's the Azure IoT SDK.

> I hope we can get Windows to fix this rather than have everyone suddenly drop dependencies on "the messenger."

I agree: ILC should have figured out if PCLCrypto was using DLLs or APIs not supported in the UWP profile.

@IotCore-Developer We understand the urgency: Short term, I will try to remove PCLCrypto and change only the Crypto APIs to use NetStandard2.0 APIs. (This is less work than converting everything to NS2.0).

**Comment by AArnott** [comment]
> ILC should have figured out if PCLCrypto was using DLLs or APIs not supported in the UWP profile.

PCLCrypto isn't using anything illegal for UWP. The Windows folks have already confirmed this is a bug in Windows.

**Comment by IotCore-Developer** [comment]
Ok thx for your updates and the fact everyone understands the urgency of this problem.

I really appreciate the efforts on this.

Sent from Mail for Windows 10

**Comment by CIPop** [comment]
@IotCore-Developer I'm actively working on this:
1. The Windows Crypto team is looking into the SDK issue from their side. Fixing this should in theory allow older versions of our SDK to work.
2. I'm removing this dependency from our SDK entirely since UWP is now .NET Standard 2.0 compliant and so we have access to the .NET Core 2.0 Crypto APIs. I should have a PR out hopefully by EOW.

**Comment by IotCore-Developer** [comment]
Ok that sounds promising, thx

Sent from Mail for Windows 10

**Comment by AArnott** [comment]
Incidentally, the issue is due to a bug in the Windows SDK.
We have [a workaround in PInvoke.Kernel32](https://github.com/AArnott/pinvoke/pull/378) now, so if you're facing this problem, you can just install (or depend on) the latest version of PInvoke.Kernel32 and your app should start working again.

**Comment by CIPop** [comment]
Thanks @AArnott !

* For V1.7.0 this should not be a problem.
* For our LTS, please manually upgrade/add the latest PInvoke.Kernel32 version to your project to work-around.
