### ISSUE TITLE
AMQP TokenRefresh will randomly fail to re-initiate the CBS link

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-iot-sdk-csharp#319]
.Net Core
OS:  Ubuntu 16.04.1 or Windows 10.0.16299.192
SDK: 1.6.1

After ~220 minutes calling a registered method I get the error "Not Registered" on Ubuntu or Windows. I am calling this method every 15 minutes but after ~220 minutes I get this error.

Using the following code:

using Microsoft.Azure.Devices.Client;
using System;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
namespace Linux
{
    class Program
    {
        static DeviceClient mydevice;
        static String connectionString = "HostName=kevinsayIoT.azure-devices.net;DeviceId=Linux;SharedAccessKey=7R2clREMOVEDDTI=";
        static void Main(string[] args)
        {
            mydevice = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Amqp);
            mydevice.SetMethodHandlerAsync("testMethod", testMethodCallback, null);
            mydevice.OpenAsync();
            int minute = 0;
            while (true)
            {
                // Sleep a minute
                Thread.Sleep(1000 * 60);
                minute++;
                Console.WriteLine("Slept for: " + minute.ToString() + " minutes");
            }
        }
        private static Task<MethodResponse> testMethodCallback(MethodRequest methodRequest, object userContext)
        {
            Console.WriteLine("Method called: " + methodRequest.DataAsJson);
            return Task.FromResult(new MethodResponse(Encoding.UTF8.GetBytes("{\"status\":\"Success\"}"), 200));
        }
    }
}

I get the following error when I call the method from Device Explorer after ~220 minutes:

One or more errors occurred. (Device {"Message":"{\"errorCode\":404103,\"trackingId\":\"d8248f029def4348b4f51915c766fdf4-G:11-TimeStamp:01/02/2018 01:01:17\",\"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:10\"},\"timestampUtc\":\"2018-01-02T01:01:17.9205026Z\"}","ExceptionMessage":""} not registered)

**Comment by ksaye** [comment]
Update:  It would appear that this happens on .Net Core and .Net Standard.

The issue appears to be during retry.  When a connection is retried, it appears that the registered MethodHandler and the ConnectionStatusChangesHandler are lost.

Simple to reproduce:

1. Create a client and register a Method Handler and a ConnectionStatusChangesHandler
2. Disconnect the network and reconnect
3. Note the Method Handler and ConnectionStatusChangesHandler are no longer registered.

K

**Comment by CIPop** [comment]
Thanks for the investigation @ksaye ! Did you try on .NET Framework as well (are you sure it's specific to Core)?

Also, if you already have the code fix, feel free to submit a PR.

**Comment by ksaye** [comment]
it happens on .Net Framework too.

**Comment by CIPop** [comment]
This may be related to CBS token refresh. The test is detecting intermittent issues with the refresh as well: #263.

**Comment by CIPop** [comment]
Keeping this as the root bug# and closing all others as duplicates.
This is being addressed in #357.
