### ISSUE TITLE
Not able to monitor device events

### ISSUE THREAD

**Issue by man2nainwal** [Azure/azure-iot-sdk-csharp#320]
Hi all,
I am using Azure Edge V1 with Ubuntu, I have created 1 IoT Hub with the name say X and then created 2 Devices say dev1 & dev2. After that I changed simulated_device_cloud_upload_lin.json file.
modules:
IotHub - "args": {
"IoTHubName": "X",
"IoTHubSuffix": "azure-devices.net",
"Transport": "MQTT",
"RetryPolicy": "EXPONENTIAL_BACKOFF_WITH_JITTER"}

       mapping - "args": [
    {
      "macAddress": "01:01:01:01:01:01",
      "deviceId": "dev1",
      "deviceKey": "primary key of dev1"
    },
    {
      "macAddress": "02:02:02:02:02:02",
      "deviceId": "dev2",
      "deviceKey": "Primary key of dev2"
    } ] }
And then I go inside build folder and run command
./samples/simulated_device_cloud_upload/simulated_device_cloud_upload_sample ../samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_lin.json

And this start sending messages to IoT Hub, then I opened device explorer and try to monitor events it gives me error - "An error occurred during communication with 'N/A'. Check the connection information and retry"

Could you please tell me what have I done wrong?

**Comment by CIPop** [comment]
@damonbarry @varunpuranik @myagley PTAL

**Comment by damonbarry** [comment]
@CIPop There's a lot of extraneous information in the description, but the focus of this issue is:

> I opened device explorer and try to monitor events it gives me error - "An error occurred during communication with 'N/A'. Check the connection information and retry"

How does one receive such an error in Device Explorer? This is independent of IoT Edge.

**Comment by damonbarry** [comment]
BTW the IoT Edge-specific part of this scenario is being tracked with Azure/iot-edge#447.

**Comment by CIPop** [comment]
@man2nainwal The repro steps are unclear. From your description, it appears that you're getting the error from the "Monitoring" tab of Device Explorer.
Please make sure you have an "Event Hub" and Device ID selected when you start monitoring.

Also, please note that Device Explorer does not have support for Modules or Edge devices.

Tentatively closing for now. @man2nainwal feel free to reopen with more information.
