### ISSUE TITLE
Error while add package v.1.6.1 to xamarin.forms

### ISSUE THREAD

**Issue by JokerstudioDev** [Azure/azure-iot-sdk-csharp#323]
**OS and version used:** macOS High Sierra

**SDK version used:** Microsoft.Azure.Devices.Client 1.6.1

while we add package to xamarin.forms. , an error message is

"Could not install package 'System.Threading.Overlapped 4.3.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, conta"

**Comment by SamuelDebruyn** [comment]
Why did you close this issue? You can't add this package to Xamarin.Android or Xamarin.iOS projects without a workaround...

**Comment by CIPop** [comment]
@SamuelDebruyn Please create a new bug including the Xamarin versions, etc.
With an up-to-date Visual Studio and Xamarin on Windows, I can't repro the problem.
