### ISSUE TITLE
mqtt-dup property handling

### ISSUE THREAD

**Issue by Draczech** [Azure/azure-iot-sdk-csharp#329]
# Setup Description
In my company's setup we use set of services (written in Java + Spring) running as Docker swarm containers. One of these services takes care of processing messages from IoT Hub, augmenting them and dispatching them to their respective destinations (mostly Service Bus queues).

When an event is read from IoT Hub, it is read by [Event Processor Host](https://github.com/Azure/azure-event-hubs-java/tree/dev/azure-eventhubs-eph) and all of its application properties are copied while system properties are ignored apart from sender device ID.

When a message is sent to the receiver's queue, the [Spring's JmsTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/core/JmsTemplate.html) is used and BytesMessage is created with the payload and properties read from the initial event's application properties as well as properties collected during message augmentation are assigned to it as String properties.

# Problem Description
Sometimes when trying to send the message via JMS tools to the Service Bus queue we get following JMSException:
> Identifier contains invalid JMS identifier character '-': 'mqtt-dup'

After escallation of the topic today with MS support technician **Enes Uysal** we found there is problem in the [Util class](https://github.com/Azure/azure-iot-sdk-csharp/blob/d7a5ddd734c635479e63a2732ac5bec3dc7543c1/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/Util.cs) on line 156. The _DupProperty_ cannot be treated as a applicationproperty, but has to be treated as one of the system properties instead.

If any application property slips from the IoT Hub and is later processed by different technology it may cause serious trouble. In this case the solution of reading IoT Hub messages as Event Hub events and later dispatching them through JMS compatible technology is rendered invalid.

Please consider making any internal message property a system property to prevent similar problems from hapenning in the future.
Thanks

**Comment by jasmineymlo** [comment]
@Draczech, you are right that the CompleteMessageFromPacket() in the Util.cs seems to be doing something wrong here.  We shouldn't be adding dup and retain as application properties nor system properties.  It seems to me that application is calling into the util function, do you know why?

**Comment by Draczech** [comment]
Unfortunately I don't know why. This issue has been spotted first when using following libraries to read events from IoT Hub:
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-eventhubs</artifactId>
    <version>0.14.5</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-eventhubs-eph</artifactId>
    <version>0.14.4</version>
</dependency>
```
If there is a problem with obtaining events it is probably related to the code in one of those libraries.
Furthermore when treating the events read from IoT Hub I transform the Event into my internal object likewise:
```
// add all application properties as Strings
for (Map.Entry<String, Object> entry:e.getProperties().entrySet()) {
	if (entry.getValue() != null) {
		wbm.addProperty(entry.getKey(), String.valueOf(entry.getValue()));
	}
}
```
While only taking the _iothub-connection-device-id_ and _iothub-enqueuedtime_ from:
```
SystemProperties sysProps = e.getSystemProperties();
```
So as I see it the _DupProperty_ is included in those application properties. While it should be only internal property and should never leave the IoT Hub.

**Comment by jasmineymlo** [comment]
@Draczech Do you have access to the device's application code and find out where and why it is calling into the util function?  I think the util function is only for testing purpose.  It will be nice to locate where the call is and remove that...

**Comment by Draczech** [comment]
Actually some of the devices are sending messages via JMS based Java client using older version of the qpid library:
```
<dependency>
	<groupId>org.apache.qpid</groupId>
	<artifactId>qpid-jms-client</artifactId>
	<version>0.10.0</version>
</dependency>
```
I admit this version is quite outdated at the moment. But I don't see any direct relation to the issue.

I still have to check the other big group of devices which are maintained by third party developers. I'll let you know when I have more information.

Just to rule out some possibilities - can IoT hub routing mess with the aforementioned properties somehow?

**Comment by jasmineymlo** [comment]
@Draczech Let's check the 3rd party ones...we gotta track down on where the util function is called.  I believe iothub routing wouldn't mess with that, but anything is possible.

**Comment by Draczech** [comment]
So I finally received message from our 3rd part developers team. They are using [iot-device-client, version 1.3.32](https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure.sdk.iot%7Ciot-device-client%7C1.3.32%7Cjar) library. Again not the latest release, but hopefully safe lib.

Please let me know if there are any updates in your investigation. Thanks

**Comment by prmathur-microsoft** [comment]
Can this be filed on azure iot java repository (https://github.com/Azure/azure-iot-sdk-java) ?

**Comment by ewertons** [comment]
This issue will be tracked by https://github.com/Azure/azure-iot-sdk-java/issues/557, which is filed under the proper repository (Azure IoT Client Java SDK)

**Comment by az-iot-builder-01** [comment]
@Draczech, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
