### ISSUE TITLE
sample of device registration against enrollment group missing

### ISSUE THREAD

**Issue by mwotruba** [Azure/azure-iot-sdk-csharp#330]
Hi there,
I would like to build a device client that uses the provisioning device client. 
My client is written in C# and should use a X509 leaf cert for authentication against an enrollment group.
I created the test certs in the way described here (https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md)

If I follow your documentation (https://github.com/Azure/azure-iot-sdk-csharp/tree/master/provisioning/device/samples) I fail with errors like 

> ProvisioningTransportException: MQTT Protocol Exception: CONNACK failed with RefusedNotAuthorized

I think the reason is that I have to handle the cert chain in my client code by myself but I could not find any sample for that. 
Please could you provide a C# ProvisionDeviceClient sample that uses leaf certs of a cert chain. 

Thanks, Marco

**Comment by jasmineymlo** [comment]
@mwotruba, I believe you should be able to use the same sample against a group enrollment.  Just presenting the leaf cert would results in the exception.  You will need to present the cert chain instead AFAIK.  @CIPop to confirm.  Thanks.

**Comment by amogh79** [comment]
Please refer the device client code for individual x509 device provisioning. While creating securityprovider call the method with optional parameter certificate collection. You certificate collection will have either 2 certificates - root and intermediate or a single certificate where the root and intermediate are clubbed.

Following is the modified method for group device provisioning:

public static async Task RunSample(X509Certificate2 certificate, X509Certificate2Collection certificate2Collection = null)
        {
            /*X509Certificate2Collection collection = new X509Certificate2Collection();
            collection.Add(new X509Certificate2($"{s_certificateFileName}groupintercert.cer"));
            collection.Add(new X509Certificate2($"{s_certificateFileName}grouprootcert.cer"));

            X509Certificate2 testCert = new X509Certificate2();*/

            using (var security = new SecurityProviderX509Certificate(certificate, certificate2Collection))
            using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
            {
                ProvisioningDeviceClient provClient =
                    ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, s_idScope, security, transport);

                Console.WriteLine($@"RegistrationID = {security.GetRegistrationID()}");
                Console.Write(@"ProvisioningClient RegisterAsync . . . ");
                DeviceRegistrationResult result = await provClient.RegisterAsync();

                Console.WriteLine($@"{result.Status}");
                Console.WriteLine($@"ProvisioningClient AssignedHub: {result.AssignedHub}; DeviceID: {result.DeviceId}");
                device_Id = result.DeviceId;
                if (result.Status != ProvisioningRegistrationStatusType.Assigned) return;

                IAuthenticationMethod auth = new DeviceAuthenticationWithX509Certificate(result.DeviceId, certificate);
                Client = DeviceClient.Create(result.AssignedHub, auth);

                Console.WriteLine(@"DeviceClient OpenAsync.");
                await Client.OpenAsync();
                Console.WriteLine(@"DeviceClient SendEventAsync.");
                Console.WriteLine(@"Sending test message...");

                await iotClient.SendEventAsync(new Message(Encoding.UTF8.GetBytes("TestMessage")));

                //Console.WriteLine(@"Message successfully sent..");
}

**Comment by CIPop** [comment]
> Just presenting the leaf cert would results in the exception. You will need to present the cert chain instead AFAIK.

Right: you would need to present the leaf certificate and either:
1. Install the certificate chain (except the root certificate) in your Intermediate Certification Authorities store. (use `certmgr.msc`)
2. Supply the certificate chain `certificate2Collection` within the ctor:     `using (var security = new SecurityProviderX509Certificate(certificate, certificate2Collection))` as @amogh79 pointed out above. As an optimization, the collection doesn't have to include the root certificate (although there is no harm in providing it - it won't be sent out on the wire during the TLS handshake).

**Comment by mwotruba** [comment]
Thank you for your responses.
Unfortunately it's not working in my environment.

I'm still using the test certs from here (https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md). 
I just changed some subject names and I kept the Itermediate{0}.cer files for later use. The original implementation deletes these cer files.

I uploaded and verified the Intermediate2.cer.
![image](https://user-images.githubusercontent.com/22099776/35229339-77564228-ff93-11e7-9c47-607ce352926a.png)

Based on this I created the enrollment group.
![image](https://user-images.githubusercontent.com/22099776/35228320-b715555a-ff90-11e7-8a8e-1e023bb7e9cf.png)

My client code looks like:
```
           var certificate = new X509Certificate2(certFile, certificatePassword);
            // cert File is a pfx file

            X509Certificate2Collection chain = null;
            if (chainPath != null)
            {
                chain = new X509Certificate2Collection();
                chain.Add(new X509Certificate2($"{chainPath}/Intermediate3.cer"));
                chain.Add(new X509Certificate2($"{chainPath}/Intermediate2.cer"));
                chain.Add(new X509Certificate2($"{chainPath}/Intermediate1.cer"));
                chain.Add(new X509Certificate2($"{chainPath}/RootCA.cer"));
            }
            return NewDevice(certificate, chain, transport, log);

public DeviceClient NewDevice(X509Certificate2 certificate, X509Certificate2Collection chain, string selTrans, IConsoleLogger log)
        {
            var security = new SecurityProviderX509Certificate(certificate, chain);
            var transport = _allTransports[selTrans];
            ProvisioningDeviceClient provClient =
                ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, s_idScope, security, transport);

            log.WriteLine($"RegistrationID = {security.GetRegistrationID()}");
            log.Write("ProvisioningClient RegisterAsync . . . ");
            DeviceRegistrationResult result = provClient.RegisterAsync().GetAwaiter().GetResult();
            .....
```
There is still the same exception in RegisterAsync:
> ProvisioningTransportException: MQTT Protocol Exception: CONNACK failed with RefusedNotAuthorized

My local cert chain, I additionally installed locally, looks like.
![image](https://user-images.githubusercontent.com/22099776/35229249-328d781e-ff93-11e7-9498-6663fbff0bfd.png)

**Comment by amogh79** [comment]
From my experience only the last certificate in the chain should work with the device certificate. I have faced issues with the certificates created by powershell. I recommend use the description from this [link](https://jamielinux.com/docs/openssl-certificate-authority/introduction.html) works like a charm. Follow the steps meticulously, also note that the commands in this article are for Linux, you will need to tweak them a bit to work on windows. chmod is not required on windows.

**Comment by jetiba-ms** [comment]
@mwotruba I had the same issue working with DPS group enrollment. 
I solved it using a device name without capital letters when I create device certificate using [this guide for bash](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md). It seems that capital letters are not allowed for devices on DPS. 
In the X509Certificate2Collection it is enough to use the intermediate certificate.

**Comment by CIPop** [comment]
@mwotruba I've found and corrected a problem with the Powershell generated certificates: https://github.com/Azure/azure-iot-sdk-c/issues/362 
Please regenerate the certificates if you've used the PS script. (Bash didn't have the problem.)

Also, @jetiba-ms is correct: The registration ID is alphanumeric, lowercase, and may contain hyphens (from https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device).

**Comment by CIPop** [comment]
Closing: I believe that the only issue here was the problem in the Powershell cert generator.
If you believe that the documentation can be further improved, please reopen.
