### ISSUE TITLE
Device not able to connect module twin

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-iot-sdk-csharp#3333]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#36356](https://github.com/Azure/azure-sdk-for-net/issues/36356).

### Library name and version

Microsoft.Azure.Devices.Client: 1.41.0

### Describe the bug

Hi,

My device is registered in IoTHub with x.509 certificate. I am trying to connect IoTHub over MQTT via console app but it gives UnauthorizedException. Same code is working for AMQP protocol. Not sure what could be the issue. Here is the sample code.

```csharp

string ModuleModelId = "dtmi:azure:iot:deviceUpdateModel;2";

        var modelOptions = new ClientOptions { ModelId = ModuleModelId };
        ModuleClient moduleClient = ModuleClient.CreateFromConnectionString($"{parameters.IoTHubConnectionString};DeviceId={deviceId};ModuleId={moduleId}",
            TransportType.Mqtt, modelOptions);
```

### Expected behavior

Device should be able to fetch device/module twin.

### Actual behavior

Device is getting unauthorized access.

### Reproduction Steps

- Register device on IoTHub with x.509 certificate.
- Fetch device/module twin over MQTT- getting unauthorized error.

### Environment

Facing issues on dev environment. 

- dotnet sdk  version: .net 6.0

**Comment by ravi-mungalpara** [comment]
Hi team,

Just wanted to check if there is any update here ?

**Comment by tmahmood-microsoft** [comment]
Hi @jsquire can you provide details about what fields are you providing in the parameters.IoTHubConnectionString and also, how are you providing certificate information, since the device you are connecting to is registered with x509 certificate.

**Comment by jsquire** [comment]
> Hi @jsquire can you provide details about what fields are you providing in the parameters.IoTHubConnectionString and also, how are you providing certificate information, since the device you are connecting to is registered with x509 certificate.

You'll want to ask @ravi-mungalpara who is the author of the original issue.

**Comment by sourabhkrishna** [comment]
@tmahmood-microsoft Will we be able to spin up the device client using the iothubowner shared access policy for a device that is registered with an x509?

**Comment by tmahmood-microsoft** [comment]
Hi @sourabhkrishna we are still looking into this. I have raised this issue with the relevant team. I will keep you posted on any updates. Let me know if you have any further issues. Thanks.

**Comment by tmahmood-microsoft** [comment]
Hi @ravi-mungalpara, @sourabhkrishna, sorry for the delay on this. It looks like this indeed is a bug in IoT Hub v1 and we currently have IoT Hub v2 which already has a fix for this specific issue. 
I would need your permission and name(s) of IoT hub(s) you want us to migrate to v2.

**Comment by sourabhkrishna** [comment]
Can you share more about IoTHub V2?

**Comment by tmahmood-microsoft** [comment]
IoT Hub V2 is designed to be in full parity with V1, it does not contain many new features, mostly fix for bugs in V1. 
From a user's point of view, you should not observe any differences in functionality or usage with IoT Hub V2.

**Comment by sourabhkrishna** [comment]
So is this an internal thing at some point in time that MS will force migrate all v1 hubs to v2?

**Comment by tmahmood-microsoft** [comment]
Yes, v2 IoT Hubs are internal and Microsoft is currently in process of migrating all v1 hubs to v2.
