### ISSUE TITLE
[Bug Report] [v2] Opened connection on a device consumes my message

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-iot-sdk-csharp#3335]
Hello
I implemented communication between a device and a backend server. 
I use [previews/v2](https://github.com/Azure/azure-iot-sdk-csharp/tree/previews/v2) SDK

My code for a device:
```csharp
static async Task Main(string[] args)
        {
            X509Certificate2 x509Certificate = Helper.LoadProvisioningCertificate();
            var security = new AuthenticationProviderX509(x509Certificate);

            var provClient = new ProvisioningDeviceClient(
                "global.azure-devices-provisioning.net",
                 Helper.IdScope,
                security,
                options: new ProvisioningClientOptions(new ProvisioningClientMqttSettings()));

            var result = await provClient.RegisterAsync();

            IAuthenticationMethod auth = new ClientAuthenticationWithX509Certificate(x509Certificate, security.GetRegistrationId());

            var deviceClient = new IotHubDeviceClient(result.AssignedHub, auth, new IotHubClientOptions(new IotHubClientMqttSettings()));
            deviceClient.ConnectionStatusChangeCallback = (ConnectionStatusInfo info) =>
            {
                Console.WriteLine($"Device Status {info.Status}; Change reason: {info.ChangeReason}; Recommended action {info.RecommendedAction}.");
            };
            await deviceClient!.OpenAsync(CancellationToken.None);

            await Task.Delay(-1);
        }
```

Device (uses Self-signed X509 Certificate Auth type, MQTT protocol for communication)
Backend service (uses AMQP protocol for communication)

Steps to reproduce:
1. Device: is attested in DPS
2. Device: connects (create client and open connection) to assigned IoT Hub (from step 1)
3. Backend service: sends a message
4. **Expected result:** the message is stored in IoT Hub and is waiting until the device starts a listener (deviceClient.SetIncomingMessageCallbackAsync(...))
**Actual result:** Backend service: receives message feedback.
```
{
  "EnqueuedOnUtc": "2023-05-29T20:49:52.395+00:00",
  "Records": [
    {
      "originalMessageId": "b2db3ca4-6f37-4b27-bd25-5c1d90a61943",
      "deviceGenerationId": "638156339749833913",
      "deviceId": "iothubx509device1",
      "enqueuedTimeUtc": "2023-05-29T20:49:48.2826815+00:00",
      "statusCode": "Success",
      "description": "Success"
    }
  ]
}
```

It looks like something on the device side receives messages, but I haven't started any incoming message callback.

Steps to reproduce (another approach):
1. Backend service: sends a message to the device
Result: the message is still stored in an IoT Hub (see Azure Portal)
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/6165551/036b9822-c57c-436c-ab00-cf433728c179)
2. Device: has been attested in DPS
Result: the message is still stored in an IoT Hub (see Azure Portal)
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/6165551/036b9822-c57c-436c-ab00-cf433728c179)
3. Device: connects to assigned IoT Hub (from step 2)
**Expected result:** the message is stored in an IoT Hub
**Actual result**: the message has disappeared from an IoT Hub  (see Azure Portal)
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/6165551/05cc608a-8ef4-471f-b43b-70a003a94191)
Backend service: receives message feedback.
```
{
  "EnqueuedOnUtc": "2023-05-30T05:19:25.598+00:00",
  "Records": [
    {
      "originalMessageId": "24434c54-1177-428d-9a44-2bd986c95a6e",
      "deviceGenerationId": "638156339749833913",
      "deviceId": "iothubx509device1",
      "enqueuedTimeUtc": "2023-05-30T05:16:05.3227162+00:00",
      "statusCode": "Success",
      "description": "Success"
    }
  ]
}
```

It looks like the opening connection consumes the message. But I expect that `deviceClient.SetIncomingMessageCallbackAsync(...)` will consume the message when I set one.

From my point of view, it's a bug. Let's imagine a real situation, Backend sends a message to Device but Device is offline or established on a vehicle that moves through the different areas with bad or absent mobile internet connection and always reconnects. It means that the sent message will be lost.

As proof that my code works at all ... Steps to reproduce:
1. Device: is attested in DPS
2. Device: connects (create client and open connection) to assigned IoT Hub (from step 1)
3. Device: starts listener `deviceClient.SetIncomingMessageCallbackAsync(...)`
4. Backend service: sends a message
5. Device: receives and handles the message in `deviceClient.SetIncomingMessageCallbackAsync(...)` as expected

**Comment by tmahmood-microsoft** [comment]
Hi @bastyuchenko, the changes to fix this behavior have been merged. Please let me know if you face any further issues.

**Comment by bastyuchenko** [comment]
Hi @tmahmood-microsoft ,
Currently I see a very weird behavior. I'm running the same code mentioned in this topic and 
- sometimes your changes work as expected (I added Microsoft.Azure.Devices.Client project to my solution to debug and I catch the execution process in the breakpoint on this line `_messageQueue.Enqueue(receivedCloudToDeviceMessage);` during debugging)
- sometimes I cannot see the execution process came into `HandleReceivedCloudToDeviceMessageAsync` at all and the backend client receives the feedback `Rejected`. It's weird because MQTT doesn't allow to reject messages.

So, I'm going to investigate the issue on my side and return to you with additional details. Please don't close this issue for awhile.

**Comment by bastyuchenko** [comment]
Hi @tmahmood-microsoft 
I pulled the latest version of previews/v2 branch after your changes and tried to debug Azure IoT SDK .NET from my solution.

1. I observe different behavior for different cases.
   - if my application connects to Azure IoT Hub without `deviceClient.SetIncomingMessageCallbackAsync(NotNullCallbackMethod)`, and the incoming message callback has never been set in previous connections of my device to IoT Hub - messages are NOT consumed from IoT Hub and NOT saved in "offline queue". I suppose it behaves in such a way because there is no open session for the clientId of my device and `deviceClient.SetIncomingMessageCallbackAsync(NotNullCallbackMethod)` works only with a session left from a previous connection.
   - if my application connects to Azure IoT Hub without `deviceClient.SetIncomingMessageCallbackAsync(NotNullCallbackMethod)`, and the incoming message callback has been "turned off" `deviceClient.SetIncomingMessageCallbackAsync(null)` in previous connections of my device to IoT Hub - messages are NOT consumed from IoT Hub and NOT saved in "offline queue". I suppose `deviceClient.SetIncomingMessageCallbackAsync(null)` close the session and it behaves in such a way due to the same cause as in the previous case.
   - if my application set an incoming message callback and doesn't disable callback in previous connections and my application connects to Azure IoT Hub without `deviceClient.SetIncomingMessageCallbackAsync(NotNullCallbackMethod)`, messages disappear from IoT Hub and saved in "offline queue" `_messageQueue.Enqueue(receivedCloudToDeviceMessage)` of SDK. I suppose new connection uses the session from the previous connection because `CleanSession=false` by default.
   
Thus, it looks like there are the tricky cases that are not obvious for a developer, and it requires for the developer to know how MQTT protocol works at all.

**Comment by bastyuchenko** [comment]
Also, there is a bug described [here](https://github.com/MicrosoftDocs/azure-docs/issues/98930). I want to understand is it an Azure IoT Hub bug or a .NET SDK bug? Why .NET SDK cannot work with Azure IoT Hub if "Feature" is not GWV2?

**Comment by tmahmood-microsoft** [comment]
Hi @bastyuchenko I appreciate your time in testing different scenarios using MQTT. 
The scenarios you described are actually correct and that's how the protocol is expected to behave.

You can find the documentation for CleanSession within the SDK [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/10e631ea827a70bf9201b87f87e929364222b542/iothub/device/src/TransportSettings/IotHubClientMqttSettings.cs#L52)
You can also find detailed description of how cloud-to-device messages are received using MQTT [here ](https://github.com/Azure/azure-iot-sdk-csharp/blob/10e631ea827a70bf9201b87f87e929364222b542/iothub/device/src/TransportSettings/IotHubClientMqttSettings.cs#L52)

Also, I really appreciate your feedback on how the current SDK documentation can be insufficient for understanding these tricky cases and will update the documentation accordingly.

**Comment by tmahmood-microsoft** [comment]
> Also, there is a bug described [here](https://github.com/MicrosoftDocs/azure-docs/issues/98930). I want to understand is it an Azure IoT Hub bug or a .NET SDK bug? Why .NET SDK cannot work with Azure IoT Hub if "Feature" is not GWV2?

Regarding this bug, I am currently looking into it and will update you on it soon.

**Comment by tmahmood-microsoft** [comment]
Hi @bastyuchenko, regarding the issue with MQTT message being rejected, I am able to reproduce it in GWv1 but not in GWv2. Are you seeing the same behavior?
Also, I have created a ticket with the gateway team to look further into this.

**Comment by bastyuchenko** [comment]
> I am able to reproduce it in GWv1 but not in GWv2. Are you seeing the same behavior?
Yes, the same in my case.  MQTT message is rejected if all 3 conditions met:
- a connection is opened from .NET SDK side 
- there is no open session in Azure IoT Hub for the client I have opened connection for
- Azure IoT Hub does not have GWv2 in Features. (I don't see GWv1 in Features of Azure IoT Hub explicitly maybe because it is default value).

I described my experience regarding this issue [here](https://github.com/MicrosoftDocs/azure-docs/issues/98930#issuecomment-1596319291).

> I have created a ticket with the gateway team to look further into this.

Could you give me the link to this issue if it is possible, to follow a future possible discussion?

**Comment by tmahmood-microsoft** [comment]
@bastyuchenko this seems like a possible bug with GWv1. GWv2 is latest version for IoT Hub service and Microsoft is currently in process of migrating all v1 hubs to v2. 
Unfortunately the tickets are created on internal use only platforms. I will keep you updated on any progress on it.

**Comment by bastyuchenko** [comment]
Hi @TYLOGIC 
Did you read my description of different scenarious above? - https://github.com/Azure/azure-iot-sdk-csharp/issues/3335#issuecomment-1601048849

and this discussion about the root cause why it is implemented in such a way? - https://github.com/Azure/azure-iot-sdk-csharp/pull/3336
