### ISSUE TITLE
[Technical Question]Read and Write access to IoT edge Modules built with Podman on IoT Edge Server

### ISSUE THREAD

**Issue by shivatyagi313** [Azure/azure-iot-sdk-csharp#3341]
Hi Have created custom IoT edge modules which require read and write operations to files inside a directory present in IoT edge server. Earlier I was using Docker desktop to build the modules so I was able to give read/write permission to the modules by referring this doc 
[Add local storage to Azure IoT Edge modules using Docker Bind](https://sandervandevelde.wordpress.com/2021/01/07/add-local-storage-to-azure-iot-edge-modules-using-docker-bind/)
But now when I am building similar IoT edge Module requiring read/write operation, with podman desktop so now the container is not even starting. on the IoT Edge Server when I checked the container, it gives the following error - 

_Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/SampleModule" to rootfs at "/app/SampleModule" caused: mount through procfd: open o_path procfd: open /var/lib/docker/overlay2/871b2e9e4e03.../merged/app/SampleModule: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type_

How can I resolve this issue?

**Comment by timtay-microsoft** [comment]
This is probably a question that is better asked on the [Edgehub repo](https://github.com/Azure/iotedge/issues) since it doesn't have much of anything to do with this SDK. I'll go ahead and close this thread because of that.
