### ISSUE TITLE
[Xamarin/iOS] Error MT3001: Could not AOT the assembly (MT3001)

### ISSUE THREAD

**Issue by JokerstudioDev** [Azure/azure-iot-sdk-csharp#335]
- **OS and version used:** macOS High Sierra

- **SDK version used:** Microsoft.Azure.Devices.Client 1.6.1

Error MT3001: Could not AOT the assembly (MT3001) while build ios project in xamarin.forms project

**Comment by CIPop** [comment]
Thanks @JokerstudioDev . I'll give this a try.

**Comment by CIPop** [comment]
@JokerstudioDev I was able to repro this on one of my machines over the weekend but I can't repro today on my main Dev machine and a different Mac machine used as build machine. XCode and Visual Studio for Mac have been installed yesterday and Visual Studio 2017 was updated yesterday to 15.5.6.

Could you give this another try after updating the entire tool-chain on both Mac (and Windows if you are using Windows) then reference Microsoft.Azure.Devices.Client 1.6.2 (and nothing else) in your project?

**Comment by abhipsaMisra** [comment]
@JokerstudioDev We are no longer to reproduce this issue. Please try updating the entire tool-chain, and then building our samples; and let us know if that helps.
In case you face further issues, please open another GitHub issue. Thanks!
