### ISSUE TITLE
[Bug Report] JsonConvert.DefaultSettings = JsonSerializerSettingsInitializer.GetJsonSerializerSettingsDelegate() affects settings globaly

### ISSUE THREAD

**Issue by AndreiStselmashenkaEPAM** [Azure/azure-iot-sdk-csharp#3358]
# Context

- **OS, version, SKU and CPU architecture used:** Alpine Linux v3.17
- **Application's .NET Target Framework :** .net 6.0.
- **SDK version used:** Microsoft.Azure.Devices 1.39.0

## Description of the issue
JsonConvert.DefaultSettings = JsonSerializerSettingsInitializer.GetJsonSerializerSettingsDelegate() modifies Newtonsoft default settings and can affect application behavior

**Comment by kennethahn** [comment]
Json deserialization changing behavior globally as a side effect of creating an instance of ServiceClient, DeviceClient or RegistryManager. This seems like undesirable behavior. 

Small demo here https://dotnetfiddle.net/a2INHy

**Comment by stephen-swensen** [comment]
Just ran into same issue, had to downgrade back down to 13.8.1 to resolve. Luckily regression test uncovered the issue but was difficult to pin the culprit. Eventually was able to see through a debug session that `JsonConvert.DefaultSetting` was pointing to a Azure.Devices type.

**Comment by kristofferpagels** [comment]
Hi, do you have any news on this issue as it is blocking us from upgrading to 1.39.0.

**Comment by scherici** [comment]
Same for us, only different .net version (7); it took a lot of work to find out what could be our problem...and discovery this is frustrating. Downgrading to 1.38 fix also for us...but it is not a real....fix
Any news?

**Comment by timtay-microsoft** [comment]
This is definitely a bug and we're looking at this now in #3402

**Comment by timtay-microsoft** [comment]
This fix has been released as of [this release](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2023-12-11), so I'll close this thread
