### ISSUE TITLE
Unable to add properties to Microsoft.Azure.Devices.Client.Message object

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-iot-sdk-csharp#336]
- **OS and version used:** Raspberry Pi 3 Raspbian

- **SDK version used:** 1.6.1

# Description of the issue:

I was following this example:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-getstarted which has the following code snippet:

# Code sample exhibiting the issue:
```csharp
private static async void SendDeviceToCloudMessagesAsync()
{
    double minTemperature = 20;
    double minHumidity = 60;
    int messageId = 1;
    Random rand = new Random();

    while (true)
    {
        double currentTemperature = minTemperature + rand.NextDouble() * 15;
        double currentHumidity = minHumidity + rand.NextDouble() * 20;

        var telemetryDataPoint = new
        {
            messageId = messageId++,
            deviceId = "myFirstDevice",
            temperature = currentTemperature,
            humidity = currentHumidity
        };
        var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
        var message = new Message(Encoding.ASCII.GetBytes(messageString));
        message.Properties.Add("temperatureAlert", (currentTemperature > 30) ? "true" : "false");

        await deviceClient.SendEventAsync(message);
        Console.WriteLine("{0} > Sending message: {1}", DateTime.Now, messageString);

        await Task.Delay(1000);
    }
}

```

The problem is that the .Add function doesn't seem to be accessible.
```
message.Properties.Add("temperatureAlert", (currentTemperature > 30) ? "true" : "false");
```

A quick look at the code shows that it might be a private method?
https://github.com/Azure/azure-iot-sdk-csharp/blob/a5108f60f343dee867a2243e5a59c4483f0c5a8b/device/Microsoft.Azure.Devices.Client/Common/ReadOnlyDictionary45.cs#L130

What's the recommended way to add a property to a message?

**Comment by ryanzjohnson** [comment]
What version of the SDK are you using. I just followed the guide you linked to above and was able to send a message with a property as shown in the guide. 

![image](https://user-images.githubusercontent.com/35502607/35029656-c4ad5f7a-fb10-11e7-8bb4-49cc3f4392e4.png)

Are you seeing an error at all when attempting to send a message?

**Comment by tylerl0706** [comment]
Hey thanks for the fast reply! I ended up figuring out the issue.

I'm using the .NET SDK from PowerShell. The SDK works in PowerShell... but there was a small difference between how C# interprets the Message object and how PowerShell does it.

It didn't work in PowerShell because C# and PowerShell are using different types when doing the `Add` method call operation. In C#, `message.Property` is treated as `IDictionary<string, string>`, where the `Add` method is public. While in PowerShell, powershell uses the real type `ReadOnlyDictionary45`, which doesn't have a public `Add` method. Therefore, it works in C# but not in PowerShell.

This is fixable by casting `Properties` to an `IDictionary` like so:
```powershell
([System.Collections.Generic.IDictionary[string, string]]$message.Properties).Add("A", "b")
```

With all that said, it's very strange that `message.Properties` is being set to an instance of `ReadOnlyDictionary45` here:
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Message.cs#L72

`ReadOnly` makes me believe that we should not be able to `Add` to that dictionary at all so that's a bit confusing.

**Comment by tylerl0706** [comment]
Here's the PowerShell example btw... it requires all of the SDK dlls in a zip:
[AzureIoTDeps.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1640355/AzureIoTDeps.zip)

Here's the code - you'll notice the similarities between the C# example:
```powershell
using namespace "Microsoft.Azure.Devices.Client"
cd PATH/TO/AzureIoTDeps/bin/Debug/netcoreapp2.0/publish
gci -Include "*.dll" -File -Recurse -Path . | % {ipmo -Force $_.FullName -Verbose; Write-Verbose $_.FullName } -Verbose

$iotHubUri = "<url>";
$deviceKey = "<key>";

function SendDeviceToCloudMessagesAsync() {
    $minTemperature = 20;
    $minHumidity = 60;
    $messageId = 1;
    $rand = [Random]::new();

    while ($true) {
        $currentTemperature = $minTemperature + $rand.NextDouble() * 15;
        $currentHumidity = $minHumidity + $rand.NextDouble() * 20;

        $telemetryDataPoint = @{
            messageId = $messageId++;
            deviceId = "myFirstDevice";
            temperature = $currentTemperature;
            humidity = $currentHumidit;
        };

        $messageString = $telemetryDataPoint | ConvertTo-Json
        $message = [Message]::new([System.Text.Encoding]::ASCII.GetBytes($messageString));

        $val = "false"
        if ($currentTemperature > 30) {
            $val = "true"
        }
        # $message.Properties.Add("temperatureAlert", $val);
        ([System.Collections.Generic.IDictionary[string, string]]$message.Properties).Add("temperatureAlert", $val)
        $deviceClient.SendEventAsync($message).Wait();
        Write-Host "${DateTime.Now} > Sending message: ${$messageString}";
        Start-Sleep -s 1
    }
}

$auth = [DeviceAuthenticationWithRegistrySymmetricKey]::new("pi", $deviceKey);
$deviceClient = [DeviceClient]::Create($iotHubUri, $auth, [TransportType]::Mqtt);
$deviceClient.ProductInfo = "HappyPath_Simulated-CSharp";
SendDeviceToCloudMessagesAsync
```

**Comment by zolvarga** [comment]
@tylerl0706 

Please verify with the latest version of our client. I have tested your sample code with it and it works fine.
We are using the latest .Net Core and it fixed the issue.

Best Regards,
Zoltan

**Comment by tylerl0706** [comment]
Just curious, what was fixed? I thought I figured out what I was doing wrong 😅

**Comment by zolvarga** [comment]
@tylerl0706 

I don't know what did you do wrong. I just tested it with out sample code and it worked.
Because there was no changes in our client I blamed on NET Core. 
The good part - it works! :)

I am closing this issue now.

Best Regards,
Zoltan

**Comment by tylerl0706** [comment]
Oh basically it was a casting issue. The full details are in the comment above:
https://github.com/Azure/azure-iot-sdk-csharp/issues/336#issuecomment-358414793

**Comment by yzhong94** [comment]
@tylerl0706 , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
