### ISSUE TITLE
Simple logic error in FileUploadNotificationReceiverSample.cs - inverted check for null

### ISSUE THREAD

**Issue by jeffvan98** [Azure/azure-iot-sdk-csharp#3369]
See FileUploadNotificationReceiverSample.cs, line 83:

83:   if (fileUploadNotification != null)
84:   {
85:      _logger.LogInformation("Did not receive any notification.");
86:      continue;
87:   }

The if statement is backwards.  It should read: if (fileUploadNotification == null).

The way its programmed, file notifications don't make it through this if block and therefore never get completed.  This needs to be flipped so the subsequent logic may proceed and complete the notifications.

**Comment by timtay-microsoft** [comment]
Thanks for catching this. #3371 will address this
