### ISSUE TITLE
[Technical Question] How to use Device Registration Status Lookup API

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-iot-sdk-csharp#3372]
In the following documentation [Devices that can't store a connection string](https://learn.microsoft.com/en-us/azure/iot-dps/concepts-deploy-at-scale#devices-that-cant-store-a-connection-string) Microsoft doesn't recommend to connect to Azure DPS each time a device return on-line. Instead, it is recommended to store an Azure IoT Hub assigned to the device by Azure DPS previously or use Device Registration Status Lookup API and re-connect to this Azure IoT Hub every time the device returns online.

How to use Device Registration Status Lookup API from Azure IoT SDK for .NET ?

**Comment by timtay-microsoft** [comment]
I'm not entirely sure why the documentation you linked is making this suggestion. I would advise you to just call ```provisioningDeviceClient.RegisterAsync(...)``` again in cases like this. 

The Device Registration Status Lookup API you are referencing is actually part of the [provisioning service client](https://github.com/Azure/azure-iot-sdk-csharp/blob/34fd33a5c7c13a52d91933a4f270123c10d81ffb/provisioning/service/src/ProvisioningServiceClient.cs#L971) and would require another locally saved connection string (a DPS instance level connection string) to execute which defeats the purpose of not caching the device's credentials.

**Comment by timtay-microsoft** [comment]
I'll go ahead and close this thread since the question has been answered.
