### ISSUE TITLE
GroupCertificateVerificationSample failing

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#338]
- **OS and version used:** Windows 10

- **SDK version used:** latest code from github

# Description of the issue:

When I run the GroupCertificateVerificationSample it fails. After some debuggign I found out that GetPrivateKey method returns null in VerificationCertificateGenerator.cs resulting which "ECPrivateKeyParameters privateKey" gets set to null and the whole process of certificate verification goes for a toss. Can you please help with issue on priority? We have a upcoming release in next week.

# Code sample exhibiting the issue:
ECPrivateKeyParameters privateKey = GetPrivateKey(store);

        private static ECPrivateKeyParameters GetPrivateKey(Pkcs12Store store)
        {
            ECPrivateKeyParameters privateParameter = null;

            foreach (string alias in store.Aliases)
            {
                var key = store.GetKey(alias);

                if (key != null && key.Key.IsPrivate)
                {
                    privateParameter = key.Key as ECPrivateKeyParameters;
                }
            }

            return privateParameter;
        }

**Comment by CIPop** [comment]
@amogh79 can you share the properties of the certificate you are trying to use (we don't need any Private info such as Issuer or Subject).
Cold it be that you're trying to use a certificate not using [Elliptic Curves](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) ?

**Comment by amogh79** [comment]
@CIPop attached is a sample cert I created using PS, please change the extension to .cer
[RootCA1_18_2018_3_03_46_PM.cer.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/1642290/RootCA1_18_2018_3_03_46_PM.cer.txt)

**Comment by CIPop** [comment]
Thanks @amogh79 . The cert is using ECDSA which is what I've tested with as well. 

You need to use the private key (PFX file with password) within the tool:
__Important__: In production environments, we don't recommend using the sample. Instead, you should use a Certificate Signing Request (CSR) towards your Certificate Authority (CA). For how to achieve this in Windows Server please see [this link](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc770827%28v%3dws.10%29).

```
Usage:
        GroupCertificateVerificationSample <certificate.pfx> <certificatepassword> <verificationCode>
```

The idea is that if you can generate a certificate with a random name, you have proved you are the rightful owner of the certificate.

**Comment by CIPop** [comment]
@amogh79 I've submitted #342 to fix the tool to output a better error message if the key is missing.

**Comment by amogh79** [comment]
@CIPop thanks for the update. I have a root cert which gets created from  azure-iot-sdk-java ProvisioningX509CerGen.java. Output from this file is the encrypted certificate text in BEGIN....END format. Any idea how I create pfx file from that cert? For our project I have exposed DPS functionalities via api using the service SDK, having said that I am testing my service side apis by creating device simulators. Do you know what would be the best way to create certificates - root, inter and leaf for testing purposes? I am unable to find a reliable way to do this.

Thanks

**Comment by CIPop** [comment]
@amogh79 To convert from PEM to PFX you can use the following. You must also provide a password when asked:

`openssl pkcs12 -export -out certwithprivatekey.pfx -inkey key.pem -in public.pem`

You will need both the key and the public cert public part for this to work. PKCS12 (PFX) defines a format that may contain both the private and public keys protected by a password.

You may want to refer to the Java certificate readme on how to perform proof of possession using the PEM format.

**Comment by amogh79** [comment]
@CIPop thanks for the update. I found out a way to create root, intermediate and leaf certs for simulating a device. I also found out a way to verify. I used this [link](https://jamielinux.com/docs/openssl-certificate-authority/introduction.html), this link details all the steps to create root, intermediate and leaf certs. Please keep in mind that the commands on this link are targeted for Linux but should be easy to convert those commands to work on windows.
On that note there, to verify a certificate one needs to sign the certificate and use the verification code as the common name.
