### ISSUE TITLE
IoT Edge not connecting to IOT Hub

### ISSUE THREAD

**Issue by IoTEdgeUser** [Azure/azure-iot-sdk-csharp#3393]
Hi,

We have deployed IOT Edge on an on-premise system and are connecting to Azure IoT Hub from it via Site to SIte VPN. Outbound ports 443 and 5671 are enabled via site to site vpn for IoT Hub and 443 is enable for container registry. As the system does not have internet we have installed iotedge via packages and copied tar files of Edge Agent, Edge Hub from Microsoft container registry. On executing docker load command for these tar files, all the docker images are getting created for these modules. However no containers for them are available in docker ps -a. Only Edge Agent is up but with error. Where as Edge Hub is giving error. On running IoTEdge check we get error that the containers cannot resolve to the host name. However host connectivity works fine. We have added host entry in etc/hosts for the FQDN and IP. Our assumption is that the container has not got these details and hence the hostname is not able to resolve the IP. We tried to add hostname explicitly to the docker by using docker run add host for the Edge Agent and Hub but they are giving null exceptions. Kindly suggest how to resolve this issue.

**Comment by rido-min** [comment]
Hi @IoTEdgeUser, this issue is not related to the azure-iot-sdk, can you re-open it in https://github.com/Azure/iotedge/issues ?

**Comment by timtay-microsoft** [comment]
Closing this thread since the thread has been opened in the right repo now
