### ISSUE TITLE
Route data directly from opc publisher to rabbit mq is possible?

### ISSUE THREAD

**Issue by Priyanka-L-Dalawai** [Azure/azure-iot-sdk-csharp#3394]
Route data directly from opc publisher to rabbit mq is possible?

**Comment by timtay-microsoft** [comment]
Can you share a bit more context here? Are you asking about routing from the IoT hub service side? [This documentation](https://learn.microsoft.com/azure/iot-hub/tutorial-routing?tabs=portal) may be able to help you.

**Comment by timtay-microsoft** [comment]
Closing as off-topic as this question doesn't seem to have anything to do with this SDK
