### ISSUE TITLE
Microsoft.Azure.Devices.Client v1.42.0 has indirect security vulnerabilies

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-iot-sdk-csharp#3397]
I use Microsoft.Azure.Devices.Client Version 1.42.0 in an IoT Edge project, and it appears that this project has a (transitive) dependency on System..Net.Http v4.3 which would contain security vulnarabilities:

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/3605786/cc20b3ce-d904-40c7-82be-569b3465cca7)

**Comment by timtay-microsoft** [comment]
This has been fixed by removing some out-of-support .net targets from this project via #3400

**Comment by timtay-microsoft** [comment]
It looks like we also need to replace the Azure Storage SDK that we use in our file upload APIs to fully clear the current security issues here, so I'll un-mark this as "fix checked in" while we work on making that happen

**Comment by andyk-ms** [comment]
Addressed in 1.42.2 build
