### ISSUE TITLE
AOT-compatible Microsoft.Azure.Devices.Client

### ISSUE THREAD

**Issue by michalczerwinski** [Azure/azure-iot-sdk-csharp#3398]
I tried to use AOT-compiled .NET 8 with ModuleClient but it failed:
* it builds with warnings about Newtonsoft.Json.dll, DotNetty.Transport.dll and Microsoft.Azure.Amqp.dll
* in runtime I got
```
Unhandled Exception: Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling GetTrustBundleWithRetry
```
After closer examination this is due to old json serializer used here:

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/1795630/3a0ecf2a-8169-4c24-8f95-7fc062a5156d)

Is there any roadmap for AOT-compatible Microsoft.Azure.Devices.Client ?

**Comment by timtay-microsoft** [comment]
We don't have any plans to support AOT compiled applications at this time. We also don't plan on migrating away from Newtonsoft in the near future either, unfortunately.
