### ISSUE TITLE
Create a SAS for a service

### ISSUE THREAD

**Issue by georgeonofrei** [Azure/azure-iot-sdk-csharp#34]
Hi,

How can I create a SAS for a server to send a message to a specific device and only that?

I am thinking about something like: sr= <host_url>/devices/<device_id>
Atm I have generated a SAS with this resource, but I keep getting Unauthorized when trying to send amessage from the server side to the device. 
Am I doing it wrong or does IoT accept only SAS for sending messages to all devices (like resource: <host_url>/devicebound)

Thanks,
George

**Comment by olivierbloch** [comment]
Hi @georgeonofrei 
The IoT Hub service doesn't support this.
The supported IoT Hub permissions are listed [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security#iot-hub-permissions). To send a Cloud to Device Message to a specific device, the service side app must use a policy that has the ServiceConnect permission, which covers all devices and cannot restrict to a single one.

**Comment by georgeonofrei** [comment]
How would a scenario like the one I described be possible? Or what workarounds are available?

Thanks,
George
