### ISSUE TITLE
Building digital twin of the robotic arm [Technical Question]

### ISSUE THREAD

**Issue by addy1997** [Azure/azure-iot-sdk-csharp#3428]
Hi there,

I am new to Azure Digital Twins and Azure IoT hub concepts. To use this SDK to send data from my robotic arm to the IoT hub, do I need to build a digital twin (something like [this](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/iothub/device/samples/solutions/PnpDeviceSamples/TemperatureController/Models/DeviceInformation.json)) first?

If so, what are the best resources to start building quickly?

**Comment by timtay-microsoft** [comment]
Hi @addy1997! When getting started with digital twins, I recommend starting out by learning about the DTDL modeling language from docs like [this one](https://learn.microsoft.com/en-us/azure/digital-twins/how-to-manage-model). Once you have defined your own DTDL model, then you can try out implementing the device-side code like in temperature controller sample you linked above.

**Comment by rido-min** [comment]
this other tutorial might also be helpful to learn how to describe IoTHub device capabilities.

https://learn.microsoft.com/en-us/azure/iot/concepts-modeling-guide
