### ISSUE TITLE
Unhandled exception. Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Request 817bda7c-6fc4-40e0-8946-93eb851fcb12 returned status 403 [Bug Report]

### ISSUE THREAD

**Issue by addy1997** [Azure/azure-iot-sdk-csharp#3433]
# Context

- **OS**: Ubuntu 16.04 LTS
- **.NET version**: 6.0
- **Device:** Laptop

## Description of the issue
ON running **dotnet run**, I get this error (see the screenshot below)
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/29406906/d8e84418-b189-4de1-8e46-85ca39c7cf14)

I'll be thankful for any guidance.

**Comment by timtay-microsoft** [comment]
Can you share what the sample code being run here is? And can you try using AMQP instead of MQTT to see if you get the same error?

**Comment by timtay-microsoft** [comment]
Depending on your code, that 403 may be a [403002](https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403002-iot-hub-quota-exceeded) which just means you can't send more telemetry today unless you upgrade your Hub to handle more messages per day or it may be [403006](https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403006-device-maximum-active-file-upload-limit-exceeded) which means you have too many file uploads happening simultaneously.

**Comment by addy1997** [comment]
Hi @timtay-microsoft ,

Thanks for replying. Here's the [link](https://github.com/addy1997/azure-iot-sdk-csharp/blob/main/iothub/device/samples/solutions/PnpDeviceSamples/Robot/RobotSample.cs) to the code.

after getting into the directory, when I run `dotnet run`. It shows this error on Ubuntun  but not on Windows.

**Comment by timtay-microsoft** [comment]
Do you see this 403 error consistently? Or just sometimes?

**Comment by addy1997** [comment]
> Do you see this 403 error consistently? Or just sometimes?

Sometimes, but when I tried running it on Ubuntu yesterday, it didn't show up.

**Comment by timtay-microsoft** [comment]
Can you check the Azure Portal to see if your IoT hub has been reaching its daily limit for messages allowed?

**Comment by addy1997** [comment]
I am primarily sending these messages to the hub outside my subscription. My daily message quota shows 4,00,000 messages.

**Comment by ancher788** [comment]
@timtay-microsoft I'm faced with the same issue on linux based OS, this issue occurs sometimes and my project doesn't fit to these two cases [403002](https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403002-iot-hub-quota-exceeded) and [403006](https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403006-device-maximum-active-file-upload-limit-exceeded). Could you please tell what problem might be?
