### ISSUE TITLE
Processing D2C messages sample does not support .Net Core 2.0

### ISSUE THREAD

**Issue by ryanzjohnson** [Azure/azure-iot-sdk-csharp#344]
# Description of the issue:
The [documentation ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-process-d2c)on reading D2C messages shows how to do it with .Net Framework 4.5.1 but not for .Net Standard applications. It references WindowsAzure.ServiceBus which only supports .Net Framework.

**Comment by ryanzjohnson** [comment]
.Net Standard uses the new Nuget package Microsoft.Azure.EventHubs

**Comment by yzhong94** [comment]
You can edit the document using Edit button on top right.

**Comment by CIPop** [comment]
@yzhong94 this is not as simple as pointing to the new package - there are substantial code changes that a user needs to do to use EventHubs vs ServiceBus. We need a sample & document to guide developers throughout the port.

@ryanzjohnson is there such a porting document available from the ServiceBus team?

**Comment by ryanzjohnson** [comment]
No document exists. They don't want to give the illusion that one package or way of doing it is better than another.

**Comment by ash2017** [comment]
Thank you for the feedback. We will add this in our backlog and look for providing this information in the next update.

**Comment by CIPop** [comment]
The new NetCore EventHub SDK doesn't have support for IoT Hub connection strings.
Support is tracked by https://github.com/Azure/azure-event-hubs-dotnet/issues/167

**Comment by CIPop** [comment]
While we get to write a proper sample for this, please see code here on how to connect to the IoT Hub's associated EventHub from a netstandard application: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/e2e/test/netstandard13/MessageE2ETests.NetCore.cs#L193

**Comment by bobjac** [comment]
The above link seems to be getting a 404

**Comment by yzhong94** [comment]
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/e2e/test/MessageE2ETests.cs @CIPop is the the right link, the folder for netstandard13 has been removed.

**Comment by abhipsaMisra** [comment]
Samples are now placed in the [Azure-Samples](https://github.com/Azure-Samples/azure-iot-samples-csharp) repository, with the messaging sample placed here: https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/MessageSample

For and end-to-end flow of sending telemtry from device, and inspecting the telemetry on IoT hub's associated Event hub, you can see our end-to-end test here: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/e2e/test/MessageSendE2ETests.cs#L286

**Comment by az-iot-builder-01** [comment]
@CIPop, @ash2017, @bobjac, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
