### ISSUE TITLE
MQTT Channel is Closed / Migrating Sample to .net8 caused an issue

### ISSUE THREAD

**Issue by codeputer** [Azure/azure-iot-sdk-csharp#3440]
See attached screen shot of the repo that I'm using.

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/1adaf02e-c1da-428c-bb74-98236a3fe186)

i did have some stable code, running for at least 8 months, in which I was using DPS (ProvisioningClient) to provision an IOT device.  when I upgraded to .Net8, my testing revealed an error.

I got this sample working as is (.net6) , but used my DPS and IOT service credentials.  Then I upgraded the transport and the provisioning client to current versions, and .Net8, and got the following error without any other changes made to the repo.

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/cef3e6d8-467e-4aa2-9f40-8e11a2292d62)
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/6ba3be40-6038-4168-9da6-da00e5799ede)

I then downgraded to versions in this repo (not sure which NUGET, as I ran out of time) the error disappeared!

Following is a more detailed shot the call stack and error generated - it takes at least 40 seconds or so before it fails.

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/2bfbdac1-731b-4e23-abfe-9980ff7117b3)

I'm on  production issue, and I'm now rolling back to get this working.

**Comment by codeputer** [comment]
Using the sample project from the repo, I made two changes.  changed the project to .Net8, and updated the Microsoft.Azure.Devices.Client library from 1.41.2 to 1.42.2 - and it broke the RegisterAsync() method - MQTT Socket Closed after about 40 seconds.  Change it back to 1.41.2, and it worked
![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/103926bf-2ac6-46eb-9503-12c761be8da1)

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/611541/5d1635db-f7d0-4399-a22b-9979a55265e6)

**Comment by codeputer** [comment]
Need help on this one as its a production issue for me - will try to work around by downgrading my application.

**Comment by timtay-microsoft** [comment]
This is likely a dup of #3413. The latest dotnetty library has some compatibility issues with .NET 8 that we are aware of and are working on

**Comment by timtay-microsoft** [comment]
Closing as dup

**Comment by codeputer** [comment]
Oh good...that took three days out of my life. Client not happy with the instability.

R

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
