### ISSUE TITLE
[Technical Question] Device Update for IoT Hub support

### ISSUE THREAD

**Issue by dme-development** [Azure/azure-iot-sdk-csharp#3458]
Does the C# SDK support Device Update for IoT Hub? Or are there any plans to integrate this in the future?

**Comment by timtay-microsoft** [comment]
There is a C# SDK for Device Update for IoT Hub, but it does not live in this repo:

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/deviceupdate
