### ISSUE TITLE
Add e2e tests for service sdk query 

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-csharp#346]
# Description of the issue:
service sdk is lacking e2e tests for query

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
