### ISSUE TITLE
Invoking methods on a device times out

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#351]
OS: Windows 10  (also repros on Linux)
SDK Version: 1.6.1

# Description of the issue:
Invoking methods on a device or module seems to time out after about 2 hours. 

Scenario –
-	A device connects to IoTHub over AMQP and registers for a method invocation callback. 
-	A service side component invokes methods on the device, say every 30 secs
-	This works fine for about 2 hours, and the device sends the expected response, but then IoTHub starts throwing “Device not found” exception.
-	It doesn’t seem to matter whether the device is sending telemetry or idly waiting for methods to get invoked. 

# Code sample exhibiting the issue:
Here is the snippet of the code that runs on the device - 
`

        static async Task SetupMethodInvocation(string deviceConnectionString)
        {
            var dc = DeviceClient.CreateFromConnectionString(deviceConnectionString);
            await dc.OpenAsync();
            await dc.SetMethodHandlerAsync("Test", ReceiveMethod, null);
            Console.WriteLine("Initialized");
        }
        static Task<MethodResponse> ReceiveMethod(MethodRequest methodrequest, object usercontext)
        {
            Console.WriteLine($"Received method request for method {methodrequest.Name}");
            if (methodrequest.Name == "Test")
            {
                return Task.FromResult(new MethodResponse(200));
            }
            return Task.FromResult(new MethodResponse(500));
        }`

Here is the snippet of the code that invokes the methods on the device - 
`
        

        private static async Task InvokeMethod(string iotHubConnectionString, string deviceId)
        {
            var sc = ServiceClient.CreateFromConnectionString(iotHubConnectionString);
            for (int i = 0; i < 2000; i++)
            {
                try
                {
                    Console.WriteLine($"Invoking method... count - {i}");
                    var response = await sc.InvokeDeviceMethodAsync(deviceId, new CloudToDeviceMethod("Test"));
                    Console.WriteLine($"Got response status = {response.Status}");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
                await Task.Delay(TimeSpan.FromSeconds(30));
            }
        }`

# Console log of the issue:
For the first 2 hours, I get the following logs - 
Starting up...
Invoking method... count - 0
Got response status = 200
Invoking method... count - 1
Got response status = 200
Invoking method... count - 2
Got response status = 200
Invoking method... count - 3
Got response status = 200
Invoking method... count - 4
Got response status = 200

After 2 hours, I start seeing errors like this - 
Invoking method... count - 239
Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: Device {"Message":"{\"errorCode\":404103,\"trackingId\":\"f914b733ca594e198a24922afc8ff99c-G:6-TimeStamp:01/25/2018 20:27:53\",\"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:00\"},\"timestampUtc\":\"2018-01-25T20:27:53.3835577Z\"}","ExceptionMessage":""} not registered
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__26`2.MoveNext()
--- End of stack trace from previous location where exception was th

**Comment by CIPop** [comment]
Closing as duplicate to #319
