### ISSUE TITLE
Multi-tenant IoT hub application

### ISSUE THREAD

**Issue by georgeonofrei** [Azure/azure-iot-sdk-csharp#36]
Hello,

Firstly I would like to indicate that I am well aware that this is not a SDK issue, but rather a question regarding application implementation. If this is not the place where such questions can be answered, then tell me at least where I can present my case.

------
I would like to implement a multi-tenant environment with IoT hub where I want to allow each tenant to connect directly to IoT hub (as service) to communicate with devices. Of course I would want each tenant to have access only to their own devices and not have the possibility to connect to devices from other tenants (thus I require the proper SAS).

Following the documentation on the ServiceConnect permissions, it would seem that it is not possible to do this restriction on a SAS level. I am expecting an URL like "{host}/devices/{device_id}/...." (where .... is devicebound or messages or something), but did not find a sample and the piece of code that I came up with result in Unauthorized.

I would like to know what strategies can I use to allow this multi-tenant connection to IoT hub. Did anyone manage to create a SAS with ServiceConnect to device specific URL? Is it even possible or what other workarounds are there for this scenario?

Also, if you have any samples with generating a SAS that allows me to use the endpoint {host}/messages/devicebound, I would appreciate it a lot.

-----

Thanks,
George

**Comment by fsautomata** [comment]
Hi George,

Unfortunately, it is not possible at this time to restrict access to individual devices from the service-side.
The current suggested solution is to have the solution provider create a back-end which acts as an enforcer.

We are aware of these scenarios, though. Please vote (and provide additional details) on the Azure IoT user voice: https://feedback.azure.com/forums/321918-azure-iot/suggestions/17755732-support-multitenant-solutions-in-iot-hub

Please, feel free to articulate any other requirements you might have in your multitenant solutions, such as device-to-cloud messages routing/security, metrics, per-tenant throttling, ...
