### ISSUE TITLE
Error when add ScheduleDeviceMethodAsync job  

### ISSUE THREAD

**Issue by MehranMazhar** [Azure/azure-iot-sdk-csharp#361]
when i try to add ScheduleDeviceMethodAsync   job  i get this  error  : 

{
    "$id": "1",
    "ClassName": "Microsoft.Azure.Devices.Common.Exceptions.IotHubException",
    "Message": "{\"Message\":\"ErrorCode:ThrottlingMaxActiveJobCountExceeded;Error: 429 {\\\"Message\\\":\\\"ErrorCode:ThrottlingMaxActiveJobCountExceeded;429\\\",\\\"ExceptionMessage\\\":\\\"Tracking ID:9659f77467c24bcf8a717f07e5a8e449-TimeStamp:02/05/2018 11:41:56\\\"}\",\"ExceptionMessage\":\"Tracking ID:99d7deda8fcb4f8d819fe5477754b7a6-G:3-TimeStamp:02/05/2018 11:41:55\"}",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__36.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.HttpClientHelper.<PutAsync>d__13`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Wenda.Api.Controllers.JobController.<Add>d__5.MoveNext() in C:\\Users\\Mehran Mazhar\\Source\\Workspaces\\Iot_WebSite\\Wenda.Api\\Controllers\\JobController.cs:line 118",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nMoveNext\nMicrosoft.Azure.Devices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nMicrosoft.Azure.Devices.HttpClientHelper+<ExecuteAsync>d__36\nVoid MoveNext()",
    "HResult": -2146233088,
    "Source": "Microsoft.Azure.Devices",
    "WatsonBuckets": null,
    "IotHubException-IsTransient": true,
    "IoTHubException-TrackingId": ""
}

here is my code  : 
  public async Task<IHttpActionResult> Add([FromBody] AddJobInput value)
        {
            CloudToDeviceMethod directMethod = new CloudToDeviceMethod(value.MethodName, TimeSpan.FromSeconds(5), TimeSpan.FromSeconds(5));

            var relaySwith = new RelaySwith { Relay = 1 };
            var json = new JavaScriptSerializer().Serialize(relaySwith);
            directMethod.SetPayloadJson("{}");
            

            DateTime startDate = new DateTime(value.Date.Year, value.Date.Month, value.Date.Day, value.Hour, value.Minute,0);
            string methodJobId = Guid.NewGuid().ToString().Replace("-", "");
            try
            {
                
                JobResponse result = await jobClient.ScheduleDeviceMethodAsync(methodJobId,
                "deviceId='" + value.DeviceId + "'",
                directMethod,
                startDate,
                10);
                return Ok(result);
            }
            catch (Exception ex)
            {
                return Ok(ex);
            }

        }

**Comment by CIPop** [comment]
@MehranMazhar you're getting throttled by the Service: `ErrorCode:ThrottlingMaxActiveJobCountExceeded;429`.

If you believe this is a bug on the service side, please open a Support Request using the help button:
![image](https://user-images.githubusercontent.com/8635911/35880301-6815610e-0b32-11e8-8e34-35775a43aa6c.png)

It's important that you add the same information that you've added in this issue, especially any tracking IDs.

**Comment by torimos** [comment]
Hello, Any updates on this issue. What was root cause?
