### ISSUE TITLE
SDK support to add certificates in certificate blade, link iot hubs and get list of linked iot hubs

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#363]
- **OS and version used:** <Windows 10> 

- **SDK version used:** <Latest from github> 

# Description of the issue:

Hi,

I want to know if the SDK supports retrieving, adding, removing and verifying certificates in the DPS. I also want to if the SDK supports getting the list of linked iot hubs, adding, removing iot hub from the list. If this is not supported can the support for this be added?

Thanks
Amogh

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by CIPop** [comment]
/cc @tameraw @nberdy @alextolp

@amogh79 for security purposes, there is a separation between the control plane and the enrollment data plane. 

1. For the control plane you will need to go through Azure Resource Manager ([REST API](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-rest-api) or [CLI ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/xplat-cli-azure-resource-manager)). The following actions will require you to use your credentials (and not a connection string):
- CRUD operations on what we call the "CA certificate" 
- verifying proof of possession of the "CA certificate"
- linking IoT Hubs with Provisioning Service

"CA certificate" should be the root of your PKI that you own. (There is no requirement that this certificate is a self-signed certificate - it could have been issued by a larger PKI entity.)

2. For adding new intermediate certificates issued by the verified CA certificate uploaded in step 1 you can use the existing Service SDK with a connection string. This is achieved via the following API:
`public static X509Attestation CreateFromRootCertificates(X509Certificate2 primary, X509Certificate2 secondary)`

`primary` and `secondary` must be certificates part of a chain that links up to one of the verified "CA certificates" (from the Certificate blade). The public portion of these certificates will be uploaded to the service and devices with certificates signed from these intermediates will belong to the newly created group.
