### ISSUE TITLE
DeviceExplorer returns error when using Call Method On Device form when using latest API version 2016-11-14

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-iot-sdk-csharp#37]
![image](https://cloud.githubusercontent.com/assets/1763519/22056138/ec1b9eda-dd5e-11e6-881a-8887c5c12fba.png)

Error details:

```POST https://pilot-restore.azure-devices.net/twins/pilot-004/methods?api-version=2016-11-14 HTTP/1.1
Authorization: SharedAccessSignature sr=pilot-restore.azure-devices.net&sig=hidden&se=1484730554&skn=iothubowner
UserAgent: Microsoft.Azure.Devices/1.1.0-preview-004
Accept: application/json
Content-Type: application/json; charset=utf-8
Host: pilot-restore.azure-devices.net
Content-Length: 75

{"methodName":"MethodName","timeoutInSeconds":60,"payload":'MethodPayload'}
HTTP/1.1 404 Not Found
Content-Length: 180
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
iothub-errorcode: DeviceNotOnline
Date: Wed, 18 Jan 2017 08:11:45 GMT

{"Message":"ErrorCode:DeviceNotOnline;Timed out waiting for device to connect.","ExceptionMessage":"Tracking ID:66b8d59066b24105a49bffcbde18495d-G:5-TimeStamp:01/18/2017 08:11:45"}
```

**Comment by damonbarry** [comment]
It looks like the device isn't connected (`ErrorCode:DeviceNotOnline`). Are you sure the device is connected, and is it connected **via MQTT**? Cloud-to-device methods are only supported currently for devices connected over MQTT.

**Comment by tedvanderveen** [comment]
@damonbarry yes the device is connected via MQTT. Also what is strange is that the error says `Timed out waiting for device`, but the error response is returned in less than a second while timeout is set to 60 secs as you can see.
Any help is very much appreciated.

**Comment by tedvanderveen** [comment]
I searched for the Tracking ID in the IoT Hub instance diagnostic logs, but cannot find that record. Maybe someone in the IoT Hub team can look it up for more details about this error?

**Comment by tedvanderveen** [comment]
Is there a working end to end sample/test codd available so we can see Direct Methods in action?

**Comment by jasmineymlo** [comment]
Below is the sample code for Methods on mqtt
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/samples/DeviceClientMethodMqttSample/Program.cs

**Comment by tedvanderveen** [comment]
@jasmineymlo that sample is not applicable to this use case as it uses Devices Client and in our case we need to call the method from the Cloud.

**Comment by olivierbloch** [comment]
Hi @tedvanderveen 
You can find a sample here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-node-direct-methods

**Comment by tedvanderveen** [comment]
Thanks @olivierbloch but I tried it, still exactly same error. Did you try it and got successful results?

**Comment by olivierbloch** [comment]
Hi @tedvanderveen.
I was indeed successful with both a device using the node sdk and also using the C# direct method sample.
Here is how I proceeded:
- For Node
  - I cloned the https://github.com/azure/azure-iot-sdk-node
  - navigated in a prompt to the folder device/samples
  - Ran the following commands
      npm install
      node device_method.js <mydeviceconnectionsting>
(using an actual connection string)
  - then I used the Device Explorer tool (just installed from latest release of this repo) to invoke the method "getDeviceLog"
  - Got response in Device Explorer

- For the C# sample:
  - Cloned the current repo
  - Opened the solution device/iothub_client_deviceclient.sln
  - In the project Samples/DeviceClientMethodMqttSample, I edited the connection string, then built and ran (only this project, not the full solution)
  - Then I used the Device Explorer tool to invoke the method "GetDeviceName"
  - Got response in Device Explorer.

Are you able to see telemetry data from the device in Device Explorer when running the sample DeviceClientMqttSample with the same connection string as the one you use for testing Methods?

**Comment by tameraw** [comment]
@tedvanderveen - Closing. Please reopen if you're still having an issue.

**Comment by epaulson** [comment]
Sorry for posting on an old topic, but for what it's worth, I hit this error when I connected directly via MQTT with mosquitto, but forgot to include the API version in the -user <myiothub>.azure-devices.net/<deviceid>/api-version=2016-11-14. 

If you leave off the /api-version bit, you can connect via mosquitto and get data on the /devices/<deviceid>/messages/devicebound topic just fine, but the device twin and direct methods don't work.
