### ISSUE TITLE
SetMethodHandlerAsync while having a Bad connection is not working ( in node it does )

### ISSUE THREAD

**Issue by SdtBarbarossa** [Azure/azure-iot-sdk-csharp#375]
- **OS and version used:** Microsoft Windows Server 2012
- **SDK version used:** Microsoft.Azure.Devices.Client (1.5.2)

# Description of the issue:
SetMethodHandlerAsync is not working under a weak connection. While that sounds like only a Connection problem it should also be a Problem in Code maybe because in Node its working.

I Have a Pi that i run as a IOT Device Connecting to my IOT Hub on Azure. This Pi Connects with a Mobile Connection Stick. So i got bad pings like 300ms on ww.google.de .

(EXAMPLE)
setting up handler on C# : 
deviceClient.SetMethodHandlerAsync("reboot", onReboot, null).Wait();
setting up handler on NodeJS:
client.onDeviceMethod('reboot', onReboot);

both codes (C# and Node) are identicall in term of functionality for my usecase. We just switched to C# for improving some lifecyle and Logging stuff. But the fact that the registration of Handlers is failing in C# stops us from working with it atm. Our current situation is like:

Pi Connected with Wifi:
C# working + Node working
Pi Connected with Mobile Connection:
C# NOT working + Node working

im sorry for my english and i hope you understand what my problem is about. I Hope you can fix this or atleast find the reason for this.

greetings Di Marco

# Code sample exhibiting the issue:
(EXAMPLE)
setting up handler on C# : 
deviceClient.SetMethodHandlerAsync("reboot", onReboot, null).Wait();
setting up handler on NodeJS:
client.onDeviceMethod('reboot', onReboot);

# Console log of the issue:
One or more errors occured. (connection timed out: 13.XX.XX.XXX:8883 )
(IP Xed by me )

**Comment by CIPop** [comment]
Thanks for reporting @SdtBarbarossa !

1. What is the actual OS running on Raspberry PI? Windows IoT or a version of Linux? ( Microsoft Windows Server 2012 doesn't run on Pi as far as I know.)
2. Can you try running this with the latest version of the SDK? (1.6.1?)

**Comment by SdtBarbarossa** [comment]
Hello @CIPop ,

1. Windows Server 2012 is my Development enviroment. 
    The Pi runs with "Raspian GNU/Linux 8 (jessie)"
2. i did the Update but this didnt solved the problem.

greetings,

SdtBarbarossa

**Comment by SdtBarbarossa** [comment]
Hello @CIPop ,

are there any news regarding this issue?

greetings,

SdtBarbarossa

**Comment by CIPop** [comment]
@SdtBarbarossa sorry, I didn't get a chance to try this out on my device. If this is urgent, please open a support ticket within your Azure subscription.
From the log it appears that your device looses connectivity. Even if that happens, our Retry mechanism should reconnect so this is a bug.

I noticed you are using an unsupported version of DeviceClient (our LTS is at 1.6.3 today and master is at 1.7 while your report is for 1.5.2). I do remember a Retry algorithm fix sometime late last year. 

Could you please give the latest version a try and let us know if you see the same behavior?

**Comment by prmathur-microsoft** [comment]
Can you please try this with 1.20.0. We had a major redesign and we believe these issues should be addressed there.

**Comment by SdtBarbarossa** [comment]
Thank you for the answer. I will try to reproduce this bug with the newer version. Will let you know of its fixed.

**Comment by CIPop** [comment]
@SdtBarbarossa please let us know if the latest version solved this issue. If not, please reopen.

**Comment by az-iot-builder-01** [comment]
@CIPop, @SdtBarbarossa, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
