### ISSUE TITLE
Creation Time Utc

### ISSUE THREAD

**Issue by Hinton** [Azure/azure-iot-sdk-csharp#376]
- **OS and version used:** Windows 10

- **SDK version used:** 1.6.2

# Description of the issue:

The C# SDK supports setting a `CreationTimeUtc` property on the `Microsoft.Azure.Devices.Client.Message` class, which afterwards shows up in the Event Hub endpoint of the IoT Hub as `iothub-creation-time-utc`.

I've been unable to find any references to this property in the [IoT Hub documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct) or in the other SDKs (C, Node.js). Is this an official supported property, and the best practice for sending the timestamp of the message?

# Code sample exhibiting the issue:

```c#
using (DeviceClient iotClient = DeviceClient.Create(config.IoTHub, auth))
{
    var message = new Message(Encoding.ASCII.GetBytes("{}"));
    message.CreationTimeUtc = DateTime.UtcNow;
    await iotClient.SendEventAsync(message);
}
```

**Comment by CIPop** [comment]
@tameraw @pierreca @jspaith Is this property supported / planned on the Node and C SDKs? If not, is there a workaround?

>  Is this an official supported property, and the best practice for sending the timestamp of the message?

@yzhong94 @simonporter PTAL

**Comment by yzhong94** [comment]
@Hinton Can you give some details on your use case for setting CreationTimeUtc?  Do you need it for downstream processing or for debugging?

**Comment by Hinton** [comment]
@yzhong94 In our use case, the IoT device may be offline for some periods, during which we continue to collect telemetry data. Once the device gets connectivity to Azure IoT Hub we stream up the collected telemetry. This requires us to also send the timestamp of when the telemetry was collected.

**Comment by CIPop** [comment]
@Hinton please use the [support options ](https://github.com/Azure/azure-iot-sdk-csharp#need-support ) or equivalents in the C and NodeJS repos to track this request.

@dominicbetts / @yzhong94 please add the following system property documentation within https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct :
https://github.com/Azure/azure-iot-sdk-csharp/blob/cd93e75fd8914b6247f23eb6a5cfd7aea459676f/iothub/device/src/MessageSystemPropertyNames.cs

**Comment by dominicbetts** [comment]
@CIPop - I've merged the doc change -it'll be published later today. I don't have permission to close this issue - can you do it? Thanks

**Comment by CIPop** [comment]
Thanks @dominicbetts !
