### ISSUE TITLE
Provisioning Service - CreateEnrollmentGroupQuery always returns 0 results

### ISSUE THREAD

**Issue by alextolp** [Azure/azure-iot-sdk-csharp#377]
- **OS and version used:** Windows 10

- **SDK version used:** Microsoft.Azure.Devices.Provisioning.Service 1.0.1

# Description of the issue:
RegistrationStatusManager.CreateEnrollmentGroupQuery() always returns 0 members. Tracked the issue down to the following -

1) RegistrationStatusManager class calls GetGetDeviceRegistrationStatus() to build a path that looks something like: registrations/groupName
2) Query class calls GetQueryUri() which calls WebUtility.UrlEncode(path); and changes the path to:

registrations%2FgroupName

This causes the lookup to fail.

**Comment by CIPop** [comment]
Thanks for reporting @alextolp!
