### ISSUE TITLE
How to receive the message from Iot Hub and display on MVC View

### ISSUE THREAD

**Issue by jeywinlizy** [Azure/azure-iot-sdk-csharp#38]
I have followed a link on _iot-hub-csharp-csharp-getstarted_ 
https://docs.microsaoft.com/en-us/azure/iot-hub/iot-hub-csharp-getstarted

1. With this I have created an Console App that sends messages  to the simulated device in my  IoT Hub.
2. I have then created a ASP.Net MVC app to subscribe the data from the cloud.

**_My Requirement_**
I would like to subscribe the data being continuously sent by the device in IoT Hub and display it on a MVC View. Please show me some pointers or an example to do this.

**Comment by olivierbloch** [comment]
Hi @jeywinlizy 
The Azure IoT Suite Remote Monitoring dashboard is an ASP.Net MVC app and you can find the code here: https://github.com/Azure/azure-iot-remote-monitoring
You'll see that it is using an event processor host to get Device to Cloud messages.
If you are looking for a little bit simpler example of an ASP.Net app (not MVC) you can also check out this project: http://connectthedots.io

**Comment by jeywinlizy** [comment]
Thanks @olivierbloch . I shall have a look on that and try.

**Comment by olivierbloch** [comment]
Hi @jeywinlizy 
Shall we close this "issue" considering it is not an issue?
Thanks

**Comment by jeywinlizy** [comment]
Hi @olivierbloch 
I went thru' the code at a higher level.  It looks like you have used Storage Table in your app.
My understanding is that the device sent messages are inserted to the Storage Tables, from where the message are retrieved as per the updated time stamp to display the message on the View(web page).

>  Is my understanding correct?

It would really be helpful if you can help me with the details of sequence of actions taking place to Receive the message from IOT Hub and displaying continuously on the web page.

As per my code I am calling Receive method 
`EventData eventData = await eventHubReceiver.ReceiveAsync();`

After this call , what & how next  ==> I would like to know how to take it next to display the message continuously on the View; as the message is being received on the device in the IOT hub
> My requirement is to get the message from IoT HUb and keep displaying continuously on the View.


Kindly suggest on how to take this forward. Thanks in advance.

**Comment by olivierbloch** [comment]
Hi @jeywinlizy 
You are actually right for the Remote Monitoring dashboard (which I don't own and don't know all the details about).
In the ConnectTheDots project I am not using the MVC model, but I leverage WebSockets to stream the data update to the browser client from the ASP.Net site backend.

**Comment by jeywinlizy** [comment]
Thanks @olivierbloch . 
From your suggestion I was looking into the webSocket to implement my solution.
When executing the javascript I am getting message ==> Connection Closed

I am having Windows 7. Is it possible to execute the WebSocket javascript in Windows 7.

**Comment by olivierbloch** [comment]
Hey @jeywinlizy 
unfortunately I am not the WebSocket expert and can't help you further on this very topic. All I have a know is in the ConnectTheDots.io project.
Additionally, considering this is not an issue related to our SDKs, I will close this thread,
I would suggest you post the question on StackOverflow to ensure the right people can help you out.
