### ISSUE TITLE
DirectMethod returns although Timeout is not satisfied

### ISSUE THREAD

**Issue by Loreno10** [Azure/azure-iot-sdk-csharp#380]
- **OS and version used:** Windows 7 x64

- **SDK version used:** 1.5.1

# Description of the issue:
I am thinking to use Direct Methods as a way to check if devices are connected to IoTHub or not (if they are online). When invoking Direct Method I need to specify timeout (minimum 5 seconds). The problem is (well, for me it's actually good, because it returns results quickly) that timeout is not respected. I check availability of 4 devices and I get a response after less than a second. How does it get response if all devices are offline? Why it does not wait for timeout?

# Code sample exhibiting the issue:
```
        static void Main(string[] args)
        {
            serviceClient = ServiceClient.CreateFromConnectionString(connectionString);

            List<Task<Boolean>> results = new List<Task<bool>>();

            string[] ids = { "7", "8", "16", "17" };

            Console.WriteLine(DateTime.Now.ToString());
            foreach (var id in ids)
            {
                results.Add(InvokeMethod(id));
            }

            Task.WaitAll(results.ToArray());
            Console.WriteLine(DateTime.Now.ToString());

            Console.WriteLine("RESULTS:");
            foreach (var result in results)
            {
                Console.WriteLine(result.Result);
            }
            //Console.WriteLine(res.Result);
            Console.WriteLine("Press Enter to exit.");
            Console.ReadLine();
        }

        private static async Task<Boolean> InvokeMethod(string deviceId)
        {
            var methodInvocation = new CloudToDeviceMethod("conn") { ResponseTimeout = TimeSpan.FromSeconds(5) };
            CloudToDeviceMethodResult response;
            try
            {
                response = await serviceClient.InvokeDeviceMethodAsync(deviceId, methodInvocation);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine();
                return false; //OFFLINE
            }

            return true; //ONLINE
        }
```

**Comment by sister4sale** [comment]
I had the same question and use case. I came to the conclusion that the service client is able to tell that the device is not connected and throws an error before the timeout would be able to be honored. If you want the invokeDeviceMethod call to have a time out you would need to use a cancellation token

**Comment by CIPop** [comment]
@Loreno10 I tried this from DeviceExplorer and tried to call a method on a device that is not connected to IoT Hub.
I assume that the response from the IoT Service is immediate because it doesn't have any connection from the device. Since it can't initiate connections toward devices it will immediately time-out.

This is the error I'm getting from service when attempting to call a method on a device that is not connected with Timeout = 10s:
```
Device {"Message":"{\"errorCode\":404103,\"trackingId\":\"8d33149792194c2798d9c7ae01689640-G:9-TimeStamp:02/28/2018 03:08:55\",\"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:00\"},\"timestampUtc\":\"2018-02-28T03:08:55.7304418Z\"}","ExceptionMessage":""} 
```

@mastermanu @simonporter  to confirm this is the expected service behavior.

**Comment by ailn** [comment]
@Loreno10 There're actually 2 timeouts in the CloudToDeviceMethod:
- ResponseTimeout
- ConnectionTimeout

default value for ConnectTimeout is 0 and this value is used to wait for the device to connect.
ResponseTimeout is to wait for response from device if connected.
