### ISSUE TITLE
Device Explorer Shows "Disconnected" Status for Edge Devices

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-sdk-csharp#381]
The Device Explorer is always showing a "disconnected" status for IoT Edge devices, despite the the portal reporting a healthy edge status and still being able to view the Edge device's streaming telemetry in the Device Explorer.

**Comment by CIPop** [comment]
@WilliamBerryiii and @pmuschi: DeviceExplorer doesn't support IoT Edge devices yet.

/cc @damonbarry @myagley @tameraw

**Comment by damonbarry** [comment]
@WilliamBerryiii @pmuschi The reason the Device Explorer shows "disconnected" status is because the IoT Edge runtime connects to IoT Hub using the identity of the two core runtime _modules_ (Edge Agent and Edge Hub), not the identity of the device. So technically the device identity is disconnected, and the Device Explorer is accurately reflecting that. But it's misleading because, practically speaking, the device _is_ connected...via its modules.

This gets back to what @CIPop is saying...Device Explorer doesn't have any support for or awareness of IoT Edge at this time.

**Comment by pmuschi** [comment]
Ok, so how do we get back the functionality that it had at one point so that it shows the correct connection status? My confusion stems from the differing behavior between between the pre-compiled SDK version and what's available here.

**Comment by damonbarry** [comment]
What functionality to you want to get back to? Device Explorer has never had support for IoT Edge devices.

**Comment by pmuschi** [comment]
"Device Explorer Twin", packaged with the Azure IoT Hub SDK, shows the connected state correctly. What's changed?

**Comment by damonbarry** [comment]
If I go to https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2018-1-23 and download/install SetupDeviceExplorer.msi, then start Device Explorer, enter my hub credentials, and select the Management tab, I see the following:
- The ConnectionState column has the value "Disconnected" for my IoT Edge device
![image](https://user-images.githubusercontent.com/9042469/36618991-0940b548-18a2-11e8-9587-40ab78a4e29b.png)
- If I click the "Twin Prop" button and look in the "Device Twin" window, it shows `"connectionState": "Disconnected"` under the "Entire Twin" tab
![image](https://user-images.githubusercontent.com/9042469/36619033-3455668e-18a2-11e8-804f-9d96238c5652.png)

Are you doing/seeing something different?

**Comment by WilliamBerryiii** [comment]
I guess the meta point here is that IoT folks are using Device Explorer as part of their development tool chain; and there's likely an expectation that as they go to explore Edge preview, their tools don't have to all shift.  Should we start an RFC for how it Edge might be integrated into the tool? Is this work underway already?

**Comment by pmuschi** [comment]
I see the connection state change from "Connected" to "Disconnected" and back again as devices connect and disconnect from the MQTT broker.

![image](https://user-images.githubusercontent.com/21107054/36619458-e6d99b08-18bc-11e8-9cc4-04bdaa9150d5.png)

I can click "Refresh" and the connectionState will update.

I guess I really don't understand what's changed with the Edge preview and why this existing functionality now long works.

**Comment by damonbarry** [comment]
@pmuschi In your screenshot, are there any IoT Edge devices in that list? Or are they all non-edge devices? Device Explorer will correctly show the connection state of non-edge devices. But it will always show IoT Edge devices as "Disconnected" even if the Device Details pane at https://portal.azure.com says they are connected.

**Comment by pmuschi** [comment]
They are non-Edge devices, but that's my problem. My non-Edge devices are showing up as disconnected in the Management tab, even though they show their connection state properly when using the app bundled with the SDK. Why is that not working correctly anymore?

**Comment by damonbarry** [comment]
OK, it's sounds like we both agree that if you install Device Explorer from the MSI provided in the latest release, everything works.

But you're also saying that, when you build Device Explorer **from source code** and run it, the ConnectionState column is wrong (says devices are disconnected when they're really connected).

Which git commit are you building? Which branch?

**Comment by pmuschi** [comment]
Yes! Sorry I've had such a difficult time communicating that.

Master branch with the last commit [5b64bed](https://github.com/Azure/azure-iot-sdk-csharp/commit/5b64bed02c872841c2d4fe089f31cc88b55c0402).

**Comment by WilliamBerryiii** [comment]
Given the conversation drift, I'm going to close this and open a new issue to specifically track adding Edge Device support into Device Manager.

**Comment by damonbarry** [comment]
@WilliamBerryiii where we're at currently with this conversation, it's not about edge devices at all. @pmuschi is saying that the ConnectionState for regular devices is incorrect when he builds recent bits directly from the GitHub repo. When he uses the MSI file from the latest release, the ConnectionState is correct.

I just filed #384 for the Device Explorer issue. Thanks!

**Comment by WilliamBerryiii** [comment]
@damonbarry got it.  Should I create a new issue that specifically tracks the request for Device Explorer to work with Edge V2?

**Comment by damonbarry** [comment]
@WilliamBerryiii Sure!
