### ISSUE TITLE
RegistryManager .GetDeviceAsync() not returning device id

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-iot-sdk-csharp#382]
When I retrieve a device via GetDeviceAsync() it comes back with all the things you would expect, a record with the Authentication object, he connection status updated time, etag, etc, but missing one critical thing - the actual *Id* is `null`

**Comment by CIPop** [comment]
Thanks for reporting @onionhammer !

Is this device an Edge-preview device by any chance?
Have you tried using DeviceExplorer (that uses this API as well)? Does it show the ID there?

**Comment by onionhammer** [comment]
@CIPop Nope, this is not any sort of preview. It's not even a real device, it's a simulated device using the registry manager itself to add the device. Yes the ID does appear in the device explorer

**Comment by CIPop** [comment]
@onionhammer, I'm not able to repro this using `Microsoft.Azure.Devices v1.6.1` and my IoT Hub. Trying to query the `Device` I get all fields populated:

```C#

            RegistryManager registryManager = RegistryManager.CreateFromConnectionString("#########"); // Replace with your connection string.

            Device d = await registryManager.GetDeviceAsync("MyDevice");

            Console.WriteLine($"ID='{d.Id}' Status='{d.Status}'");
```

Output:

```
ID='MyDevice' Status='Enabled'
```

**Comment by CIPop** [comment]
@onionhammer if this is still a bug for your IoT Hub, my suggestion is to open a Service Request from your Azure subscription to verify the IoT Hub data. (See [here ](https://github.com/azure/azure-iot-sdk-csharp#need-support) for details on how to open the SR.)
