### ISSUE TITLE
ConnectionState inaccurate in Device Explorer

### ISSUE THREAD

**Issue by damonbarry** [Azure/azure-iot-sdk-csharp#384]
@pmuschi reported in #381 that the ConnectionState column in DeviceExplorer's Management tab is inaccurate **when he builds Device Explorer directly from source code** in master (5b64bed). But when he installs it from the [MSI](https://github.com/Azure/azure-iot-sdk-csharp/releases/download/2018-1-23/SetupDeviceExplorer.msi) provided in the latest release, the ConnectionState column accurately reflects the connected/disconnected state of the various devices in his IoT hub. This may indicate that a bug has crept in since the last release.

**Comment by CIPop** [comment]
Thanks for reporting: I'm not aware of any changes to the Device Explorer or the service SDK since the last release. I'll give it a try.

**Comment by CIPop** [comment]
Can't repro with the latest DeviceExplorer release (1.5.0). The original query API has been deprecated and replaced by the Twin API. 
There are known server-side limitations caused by caching and, for certain customers we could also be observing an actual service-side bug: #448, #510.

**Comment by CIPop** [comment]
@pmuschi please let us know if you still see this issue (adding detailed repro steps). Note that DeviceExplorer does not support Modules or Edge devices.
