### ISSUE TITLE
Issue in receiving data continuously from IoT Hub

### ISSUE THREAD

**Issue by jeywinlizy** [Azure/azure-iot-sdk-csharp#39]
**My Issue**
I am having issues on receiving data continuously from IoT Hub.

I have used [iot-hub-csharp-csharp-getstarted](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-getstarted) as reference to create my ASPNet MVC app

Below is the function to receive data from IoT Hub

```
private static async Task ReceiveMessagesFromDeviceAsync(string partition, CancellationToken ct)
    {
        var eventHubReceiver = eventHubClient.GetDefaultConsumerGroup().CreateReceiver(partition, DateTime.UtcNow);
        while (true)
        {
            if (ct.IsCancellationRequested) break;
            EventData eventData = await eventHubReceiver.ReceiveAsync();
            if (eventData == null) continue;

            string data = Encoding.UTF8.GetString(eventData.GetBytes());

            //Console.WriteLine("Message received. Partition: {0} Data: '{1}'", partition, data);

        }
    }
```

The value is getting received in var string data But it comes out of the loop after some time (whereas in the Console app which sends data to IoT hub, it keeps continuously sending data )

The above function is called via the below one

```
private void SetHubs()
        {
            eventHubClient = EventHubClient.CreateFromConnectionString(connectionString, iotHubD2cEndpoint);
            var d2cPartitions = eventHubClient.GetRuntimeInformation().PartitionIds;
            CancellationTokenSource cts = new CancellationTokenSource();

            var tasks = new List<Task>();
            foreach (string partition in d2cPartitions)
            {
                tasks.Add(ReceiveMessagesFromDeviceAsync(partition, cts.Token));
            }
            //Task.WaitAll(tasks.ToArray());


        }
```

**My problem**

So in the receiving MVC app (using the above method _ReceiveMessagesFromDeviceAsync_, it comes out of the loop (though it is inside while loop ==>while(true)) Only some 50 - 70 message are received after which it exists the while loop, What is that I am missing here?

## Update

I tried including try catch block
i.e placing the code statements - while(true) part - of the method ReceiveMessagesFromDeviceAsync in try catch block as below.
I have confirmed that it never hits the statements marked below as ====>
STT-A or STT-B or STT-E or STT_END_OF_METHOD
It loops inside while for some number of times (i.e receives data from IoT Hub)
and at one point of time at the statement STT- IoT_DATA it comes out of the method and returns to the calling method - i.e to the method SetHubs() I have mentioned in my query\comment
(This proceeds to display the page)

```
try{
          if (ct.IsCancellationRequested) 
                break; // STT-A
          EventData eventData = await eventHubReceiver.ReceiveAsync(); // STT- IoT_DATA
          if (eventData == null) 
                 continue;//STT-B
          string data = Encoding.UTF8.GetString(eventData.GetBytes());
}
catch(Expecption exp){
string e =exp.message(); //STT-E
}
} //STT-END_OF_METHOD
```
Am I missing something like the partition limit or so. If so please guide me how to do or make the required settings to make this work.

## Note : The same code works fine in a Console App.

**Comment by v-tbert** [comment]
Is your cancellation token timing out?

if (ct.IsCancellationRequested) break;

**Comment by jeywinlizy** [comment]
No itis not executing the break
```
 if (ct.IsCancellationRequested)
                    break;
```

But I see that it just comes out of the method and so the return View gets executed.
So after this I am able to see the page.

**Comment by jeywinlizy** [comment]
I tried including _try catch block_ 
i.e placing the code statements -  while(true) part - of the method _ReceiveMessagesFromDeviceAsync_  in try catch block as below. 
I have confirmed that it never hits the statements marked below  as   ====>   
                                              **_STT-A_**   or   _**STT-B**_   or   _**STT-E**_     or    _**STT_END_OF_METHOD**_ 
It loops inside while for some number of times (i.e receives data from IoT Hub)
and at one point of time at the statement  STT- IoT_DATA it comes out of the method and returns to the calling method - i.e to the method  SetHubs() I have mentioned in my query\comment
(This proceeds to display the page)

```
try{
          if (ct.IsCancellationRequested) 
                break; // STT-A
          EventData eventData = await eventHubReceiver.ReceiveAsync(); // STT- IoT_DATA
          if (eventData == null) 
                 continue;//STT-B
          string data = Encoding.UTF8.GetString(eventData.GetBytes());
}
catch(Expecption exp){}
string e =exp.message(); //STT-E
} //STT-END_OF_METHOD
```

Am I missing something like the partition limit or so. If so please guide me how to do or make the required settings to make this work.

**## _Note : The same code works fine in a Console App._**

**Comment by serkantkaraca** [comment]
I would like to know why you commented out Task.WaitAll ?

//Task.WaitAll(tasks.ToArray());

**Comment by jeywinlizy** [comment]
If that is not commented the system hangs - continuously waits - there ;
even when I'm debugging the debugger doesn't get back if that statement is hit.

When this statement is a Console App the control(or debugger) continuously loops thro while\foreach loop
until a break given.

**Comment by serkantkaraca** [comment]
I don't think you can fire and forget async receivers this way. You need to have a background task manager to root client objects and tasks. For example, what happens when eventHubClient is garbage collected while your receiver is still running. Can you dig into web for correct implementation of "fire and forget" programming in ASPNet applications?

**Comment by olivierbloch** [comment]
Hi @jeywinlizy 
I think the conversation has now gone way beyond the SDK use itself. Would it be possible for you to post the issue you are having on StackOverflow to make sure you get the right people looking into it?
Thanks

**Comment by tameraw** [comment]
@jeywinlizy - Since this issue is not related particularly to this SDK, we're closing it here.
