### ISSUE TITLE
Assert hit in IoTHub DeviceClient MQTT transport when running E2E tests in Debug mode

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#391]
I see the following Assert hitting every time we run E2E tests in Debug:
https://github.com/Azure/azure-iot-sdk-csharp/blob/5b64bed02c872841c2d4fe089f31cc88b55c0402/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/Util.cs#L192

The netcoreapp2.0 test runner considers this fatal and stops executing other tests. 

Tracking the investigation of the assert with this issue as I need to temporarily remove the assert to allow `netcoreapp2.0` runs. `net451` and `net47` also show a pop-up message with the assert but execution is not interrupted.

**Comment by cabbagecreek** [comment]
I have tested with a Windows Form app.. This works
`_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Mqtt);`

Then testing the same code in UWP I get System.Net.Security not found.
Changing to:
`_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Http1);`
Works!!!

**Comment by CIPop** [comment]
@cabbagecreek - please open a new issue.

**Comment by RubiaL** [comment]
we have added this into our backlog and we would address it as part of the next planning cycle.

**Comment by az-iot-builder-01** [comment]
@cabbagecreek, @CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
