### ISSUE TITLE
await query.NextAsync().ConfigureAwait(false) not throwing error when endorsement key is a non base64

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#392]
- **OS and version used:** Windows 10

- **SDK version used:** Latest Nuget version

# Description of the issue:

It seems that no error is returned from the SDK when the following code snippet runs. **_TpmAttestation.cs_** calls **_ParserUtils.EnsureBase64String_** and in such cases where enrollment entries are returned from the DPS with non base64 endorsement keys, it keeps me wondering why the heck this is failing. In my case I found a bunch of enrollment entries with non base64 EKs, these devices were added a few months back possibly before the DPS went GA. Now that there is a validation in place on UI to ensure that the EK is a indeed a base64 string goin forth its good to go on the UI side. I have not yet tried creating an enrollment entry using the SDK with a non base64 EK.

   

# Code sample exhibiting the issue:

            using (ProvisioningServiceClient provisioningServiceClient = 
             ProvisioningServiceClient.CreateFromConnectionString(dpsConnectionString))
            {
                string jsonQuery = "SELECT * FROM enrollments";
                 QuerySpecification querySpecification = new QuerySpecification(jsonQuery);
                using (var query = provisioningServiceClient.CreateIndividualEnrollmentQuery(querySpecification, pageSize))
                {
                    while (query.HasNext())
                    {

                        var queryResult = await query.NextAsync().ConfigureAwait(false);

                    }
                }
            } 

# Console log of the issue:

**Comment by abhipsaMisra** [comment]
Validating for Base64 Endorsement Key was removed from DPS Service code as a part of fix #378 (PR #422).
