### ISSUE TITLE
DeviceClient.SendEventAsync() throws exception after update to sdk version 1.6.2 

### ISSUE THREAD

**Issue by Meandron** [Azure/azure-iot-sdk-csharp#395]
- **OS and version used:** <VERSION> 
Windows 7, Visual Studio 2013, .net Framework 4.5.2
- **SDK version used:** <VERSION> 
1.6.2

# Description of the issue:

All I did was to update the SDK from version 1.2.4 to 1.6.2. 
Before being able to do so i had to install System.Linq.Queryable version 4.3 as the referenced version 4.0 by the SDK requires Nuget 3.x -> but I'm on VS2013 and cannot upgrade Nuget easily due to company restrictions.

Now when calling:
`client.SendEventAsync(message).Wait();`

it gives me a FileNotFoundException: 
{"File or assembly \"System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" not found.

I checked my dependencies and saw that there is no such assembly. So I tried to install the corresponding NuGet package myself without success however: When building the project, there is no such assembly. So I checked the System.Runtime.InteropServices NuGet package and saw the net45 folder being empty!?

Am I missing something? 

Any help would be appreciated!

# Code sample exhibiting the issue:

```
DeviceClient client = DeviceClient.CreateFromConnectionString(azureConnectionString, TransportType.Http1);
client.OpenAsync().Wait(); //no error
client.SendEventAsync(message).Wait() //exception
```
# Console log of the issue:

**Comment by Meandron** [comment]
I did some more testing - and now it works:

What I did:
- Revert project (SDK version 1.2.4)
- Installed System.Linq.Queryable, Version 4.3
- Installed Azure Client SDK, version **1.5.2**

**Comment by CIPop** [comment]
Thanks for reporting @Meandron ! I've cleaned up several unused dependencies in master and am currently working on a release. 
Hopefully the new package will address the issue for IoT Hub with the net451 binary (should work as expected on your target of net452).

**Comment by CIPop** [comment]
@Meandron could you please try again with V1.7.0? We've changed the way we build&pack the binaries.

**Comment by Meandron** [comment]
@CIPop:
I tried with V1.7.0. and fortunately could not reproduce the issue I'd reported.
Thank you!

However what could be improved is the reference to System.Linq.Queryable. 
With Nuget 2.x it is not possible to install the SDK as System.Linq.Queryable V4.0 requires Nuget 3.x.
I still had to install the latest version (=V4.3) of that package, which requires Nuget 2.x only, before I could finally install V1.7 of the SDK.

**Comment by zolvarga** [comment]
There is no repro with the new packages.
Closing it as fixed.
