### ISSUE TITLE
Inline Documentation: Microsoft.Azure.Devices.AuthenticationMechanism is missing the Type property

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-iot-sdk-csharp#397]
Hi there! I'm the maintainer of the reference docs for Azure .NET SDKs.  This is a reference doc issue that requires a change to the underlying `///` comments.

From @DOliana (https://github.com/Azure/azure-docs-sdk-dotnet/issues/427):

> I think the title says it all :-)

cc: @dominicbetts

**Comment by CIPop** [comment]
Thanks @CamSoper . I've added FXCop warnings and there are several public APIs missing comments.

**Comment by CamSoper** [comment]
@CIPop - Appreciate the assist!  🙂

**Comment by CIPop** [comment]
@CamSoper I don't think the title is sufficient here. We already have documentation on both `AuthenticationMechanism` and `AuthenticationType`.

**Comment by CamSoper** [comment]
@CIPop Fair enough, let's close it out unless @DOliana has any further comment.

**Comment by yzhong94** [comment]
@CamSoper , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
