### ISSUE TITLE
Multiple connections for one deviceId

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-iot-sdk-csharp#404]
Hi,

I did some tests and I saw that it's possible to have several connections to the IoTHub for the same deviceId.

This state has several impacts :
- The ConnectionState is not reliable
- When I send a cloud 2 device message, it is not delivered until there is only one connection per device.

Is it possible to know if the IoTHub already have a connection to a specific device Id?
Is it possible to configure the IoTHub to reject several connections for the same device id ?

Thanks,

**Comment by CIPop** [comment]
I'm not sure we support this scenario.
@sergaz-msft @mastermanu @simonporter @tameraw @yzhong94 This is a valid scenario in cases where a device is decommissioned but the swap is not atomic. Any recommendations?

**Comment by CIPop** [comment]
@Sbou I've confirmed this internally: we don't support this scenario. You must ensure a single connection for each DeviceID.
