### ISSUE TITLE
Unable to create IoT Edge Devices via Azure IoT service SDK for C#

### ISSUE THREAD

**Issue by Hammatt** [Azure/azure-iot-sdk-csharp#406]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp2.0
- **Device:** <DEVICETYPE> n/a
- **SDK version used:** <VERSION> Microsoft.Azure.Devices 1.16.0-preview-001

# Description of the issue:
I'm able to add new IoT devices to the hub using ```RegistryManager.AddDeviceAsync```,  
but can't find a way to add IoT Edge devices to the hub.

# Code sample exhibiting the issue:
n/a

# Console log of the issue:
n/a

**Comment by CIPop** [comment]
@myagley @damonbarry Is there any preview support for IoT Hub Service SDK preview to create Edge devices today?

**Comment by damonbarry** [comment]
Sure. Something like this should do it:

````
var device = new Device(deviceId);
device.Capabilities = new DeviceCapabilities();
device.Capabilities.IotEdge = true;
await registryManager.AddDeviceAsync(device);
```

**Comment by Hammatt** [comment]
Perfect, thanks!
