### ISSUE TITLE
Executing ConnectTheDots

### ISSUE THREAD

**Issue by jeywinlizy** [Azure/azure-iot-sdk-csharp#41]
I have downloaded the code ConnectTheDots  http://connectthedots.io
I am able to successfully comiple & build it.

To execute this app do I need to have the below ?
         1. Windows 8 or above
         2. IIS 8

I am having Windows 7 and IIS 7. Will I be able to execute with this system spec
If no are there any updates that I can run in my system to make this workable in my system?

**Comment by olivierbloch** [comment]
Hi @jeywinlizy 
I have created a [new issue](https://github.com/Azure/connectthedots/issues/259) on the ConnectTheDots repo. Let's have the conversation there.
Thanks
