### ISSUE TITLE
UI is unresponsive while reading from IoT Hub

### ISSUE THREAD

**Issue by andrew-laughlin** [Azure/azure-iot-sdk-csharp#414]
Release: 2018-3-13
OS: Window 10 x64

When monitoring data on an IoT hub, the UI becomes completely unresponsive. For example, the user cannot select "Cancel" to stop the download of events.

Scenario:
I'd like to see a range of data stored on an IoT hub. From the "Data" tab I set a start time to the beginning of the desired range (say 24 hours ago), then click "Monitor". Since an end range cannot be set, I have to wait for all data from the start time to be consumed. During the download of historical events, the UI does not respond to cancel events.

**Comment by CIPop** [comment]
@andrew-laughlin Our SDK doesn't have an UI. Please re-open using the Issue Template and specifying exactly what product you're referring to.

If this is about the Azure IoT Portal please use the question mark in the top right hand to create a service support request.
