### ISSUE TITLE
Method handlers not called after device is disabled and enabled again

### ISSUE THREAD

**Issue by johannesegger** [Azure/azure-iot-sdk-csharp#42]
* SDK: C#
* Version: Microsoft.Azure.Devices.Client v1.2.1 (let me know if you need the versions of the other packages, as of 2017-01-27 they're all at the latest version)
* Code snippet to reproduce the bug

        private static async Task Do()
        {
            const string deviceId = "...";
            const string deviceConnectionString = "...";
            const string managerConnectionString = "...";
            const string serviceClientConnectionString = "...";

            var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, Microsoft.Azure.Devices.Client.TransportType.Mqtt);
            var registryManager = RegistryManager.CreateFromConnectionString(managerConnectionString);
            var serviceClient = ServiceClient.CreateFromConnectionString(serviceClientConnectionString);

            deviceClient.SetMethodHandler("ping", HandlePing, null);

            Console.WriteLine("Send ping to enabled device");
            await SendPing(deviceId, serviceClient);

            Console.WriteLine("Disable device");
            await SetDeviceStatus(registryManager, deviceId, DeviceStatus.Disabled);

            Console.WriteLine("Send ping to disabled device");
            await SendPing(deviceId, serviceClient);

            Console.WriteLine("Enable device");
            await SetDeviceStatus(registryManager, deviceId, DeviceStatus.Enabled);

            Console.WriteLine("Send ping to re-enabled device");
            await SendPing(deviceId, serviceClient);
        }

        private static Task<MethodResponse> HandlePing(MethodRequest methodRequest, object userContext)
        {
            return Task.FromResult(new MethodResponse(new byte[0], 200));
        }

        private static async Task SetDeviceStatus(RegistryManager registryManager, string deviceId, DeviceStatus status)
        {
            var device = await registryManager.GetDeviceAsync(deviceId);
            device.Status = status;
            await registryManager.UpdateDeviceAsync(device);
        }

        private static async Task SendPing(string deviceId, ServiceClient serviceClient)
        {
            try
            {
                var method = new CloudToDeviceMethod("ping", TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(20));
                method.SetPayloadJson("{}");
                var result = await serviceClient.InvokeDeviceMethodAsync(deviceId, method);
                Console.WriteLine("Sending ping succeeded.");
            }
            catch (Exception e)
            {
                Console.WriteLine("Sending ping failed: " + e);
            }
        }

* Logs

        Send ping to enabled device
        Sending ping succeeded.
        Disable device
        Send ping to disabled device
        Sending ping failed: Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: Device {"Message":"ErrorCode:DeviceNotFound;Device unavailable","ExceptionMessage":"Tracking ID:5a4dcda3933f4649bfb2d4e8466859ef-G:11-TimeStamp:01/27/2017 06:41:33"} not registered
           at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__30.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__23`2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at IotTest.Program.<SendPing>d__4.MoveNext() in C:\Users\Hannes\Work\IotTest\IotTest\Program.cs:line 65
        Enable device
        Send ping to re-enabled device
        Sending ping failed: Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: Device {"Message":"ErrorCode:DeviceNotOnline;Timed out waiting for device to connect.","ExceptionMessage":"Tracking ID:cc156c9e4ab9419cb5a2b5b916d90a40-G:11-TimeStamp:01/27/2017 06:41:53"} not registered
           at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__30.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__23`2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at IotTest.Program.<SendPing>d__4.MoveNext() in C:\Users\Hannes\Work\IotTest\IotTest\Program.cs:line 65

As you can see, method handlers don't work after re-enabling the device. However, message sending and receiving still works. Also method handlers work if `deviceClient` is disposed and recreated.

So a work-around would be to dispose and recreate the client every time an error occurs. But here's the next problem: the client doesn't really know that he got disabled.

Any ideas?

**Comment by jasmineymlo** [comment]
@eggapauli, disabling a device is virtually the same as deleting it from IoTHub which would terminate the connection to that particular device.  On re-enabling the device, it is equivalent to recreating the device with the same configuration data as before.  So, it is by-design that the device has to initiate reconnection to the IoTHub in this scenario.

Message sending and receiving still work in this case because recovery logic has kicked in once the connection was terminated by the IoTHub.  The connection for messaging will reestablished once the device is re-enabled.

We have a task for method handlers recovery logic in our product backlog.  This should solve the issue.

Your suggested work-around about disposing and recreating the client every time would work.  Maybe you can use "message sending" as a pointer for when to recreate the client for methods before we have the recovery logic in place?

Hope this helps.  Thanks.

**Comment by eggapauli** [comment]
Perfect, thanks a lot. It would also be nice to get notified when that happens. Could you imagine creating an event or something that notifies about connection problems?

**Comment by jasmineymlo** [comment]
Thanks for your comment.  We have a work item for the notification regarding connection status in our backlog as well.

**Comment by eggapauli** [comment]
Perfect, thanks a lot.

**Comment by tameraw** [comment]
@johannesegger - Forgot to update on this one, but a fix has been checked in. Please feel free to reopen if still having issues. Thanks.
