### ISSUE TITLE
Operation timeout expired exception while sending telemetry data continuously.

### ISSUE THREAD

**Issue by mathisharp** [Azure/azure-iot-sdk-csharp#423]
Hi SupportTeam, 

We are using DeviceClient of Azure IOT hub to send data to device.

- **OS used:** <VERSION> Windows server 2012

- **Protocol used:** <VERSION> Amqp_WebSocket_Only

- **SDK version used:** <VERSION> IoT Device Client 1.7.0

- **programming language used:** <VERSION> C#

- **IOThub Units:** <VERSION>  1 units

- **Quota/Standard:** <VERSION>  S1

- **DeviceConnected:** <VERSION> 32

- **Device running parallel:** <VERSION>  - 1 to 3

# Description of the issue:

	Sudden operation timeout exception while sending telemetry to IOThub. We have multiple device simulator running in a machine. With each device sending telemetry data to different iothubs.
	We noticed that only one of the device simulator gets this exception, but other devices sending data to the same iothub didn't face any issue.

# Possibility verified:

 
	
Note. : 
	We are facing this issue from the specific site.
	
We have also rolled out the following possibility- 
	
	1) Devices being disabled.
	2) firewall block.
        3) Exceeding quota limit.

		
We had checked there is no firewall block or device disabled or quota exceed during the test run. Please let us know any updates on fixing this issue.

# Console log of the issue:

ERROR -- Failed to send message: MessageType MessageV1 MessageId 6ff8856e-dac1-4add-b6bb-d9ab040bfb7a, Exception-System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by CIPop** [comment]
Thanks for reporting @mathisharp . Since the other hubs and devices continued to transmit it doesn't sound like a network issue so we'll need to look at this from the hub side.

To investigate we would need private information such as the Hub, Device ID and time when you observed this. We do not recommend adding Hub/DeviceID details to GitHub.
Please follow the [support guide ](https://github.com/azure/azure-iot-sdk-csharp#need-support) to open a support request from within Azure Portal with these details.

**Comment by yzhong94** [comment]
@mathisharp , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
