### ISSUE TITLE
CreateEnrollmentGroupQuery with query.NextAsync() returns group info without the list of devices contained in the group

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#424]
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows 10
- **Application's .NET Target Framework :** <NETVERSION>  .Net 4.6
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION>  Latest version from the Nuget

# Description of the issue:

I have exposed custom apis for DPS using DPS SDK. There is an api which returns the groups from the DPS. I observed that the when following code snippet is run I am getting the group info but not the devices within the group which is kinda counter intuitive. Can you please make changes or put a flag which can be set so that devices from the group are returned. Also please suggest any other ways via which I can retrieve the devices in a given group.

Please be advised that we need the the group info and the list of devices within the group to be exposed via api for our project which is already running on very aggressive deadlines.

# Code sample exhibiting the issue:

           Query g = _helper.CreateEnrollmentGroupsQuery(dpsConnectionString, querySpecification, pageSize);
           QueryResult queryResult = await g.NextAsync().ConfigureAwait(false);
           
           public Query CreateEnrollmentGroupsQuery(string dpsConnectionString, QuerySpecification querySpecification, int datapageSize = 0)
        {

            var provisioningServiceClient = ProvisioningServiceClient.CreateFromConnectionString(dpsConnectionString);
            if (datapageSize != 0)
            {
                Query q = provisioningServiceClient.CreateEnrollmentGroupQuery(querySpecification, datapageSize);

                return q;
            }
            else
            {
                Query q = provisioningServiceClient.CreateEnrollmentGroupQuery(querySpecification);
                return q;
            }

        }

# Console log of the issue:

**Comment by CIPop** [comment]
/cc @nberdy @alextolp 
Thanks for pointing this out @amogh79 ! We're missing a sample for querying the registration state for a particular group:

```c#
Query query = client.CreateEnrollmentGroupRegistrationStateQuery(querySpecification, this.enrollmentGroup.EnrollmentGroupId));
```

**Comment by amogh79** [comment]
@CIPop Thanks for the update you made by day, now I can get the devices within a group too....yaaaay

**Comment by yzhong94** [comment]
@amogh79 , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
