### ISSUE TITLE
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException when using UploadToBlobAsync() - CA authenticated device

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#425]
**Description:**
When trying to upload file to blob storage connected to IoT hub I am getting following exception:
**Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException**.  

**Details:**
Device authentication mechanism: **CA certificate**  
Protocol: **MQTT**
.NET Framework: **net451**
Library: **Microsoft.Azure.Deivces.Client 1.7.0**
Method: **DeviceClient.UploadToBlobAsync()**
OS Version:  **Windows 10 Enterprise 2016 LTSB**

In order to verify functionality I also used device authenticated with symmetric keys as well. With that device everything was working fine, and files were correctly uploaded to storage. 

If you need any other information, please let me know.

**Comment by CIPop** [comment]
Thanks for reporting this @Perun85 ! We need to further investigate why this doesn't work.

**Comment by Perun85** [comment]
One more thing. I also had issue with sending files via DeiceClient from .NET Core application when I used device authenticated by self signed certificate.

Here is the test code that works when executed on net451 runtime but not on netcoreapp2.0:

NOTE: Executed inside the main method of  netcoreapp2.0 console application.

``` var certificate = new X509Certificate2(@"C:\TEMP\certificate.pfx", "password");
  var authentication = new DeviceAuthenticationWithX509Certificate("Device001", certificate);
  var deviceClient = DeviceClient.Create("<my-iothub-url>", authentication, TransportType.Mqtt);
  var fileContent = new FileStream(@"C:\TEMP\TestFile.txt", FileMode.Open);
  deviceClient.UploadToBlobAsync("TestFile.txt", fileContent).Wait();

When executed example above raises NullReferenceException with following stack trace:

 at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Devices.Client.IAuthorizationProvider.GetPasswordAsync()
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__17`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<UploadToBlobAsync>d__11.MoveNext()
 ```

**Comment by CIPop** [comment]
@Perun85 the second issue sounds similar to https://github.com/azure/azure-iot-sdk-csharp/issues/259.

**Comment by bespinfw** [comment]
I have the same issue. Any update on this issue? Thanks

Device authentication mechanism: CA certificate, Self-Signed Certificate
Protocol: MQTT
.NET Core 2.0
Library: Microsoft.Azure.Deivces.Client 1.8.0
Method: DeviceClient.UploadToBlobAsync()
OS Version: Windows 10 Enterprise 1803

**Comment by Perun85** [comment]
I experienced this issue, on two different environments.

**Details:**
Device authentication mechanism: **CA certificate**
Protocol: **MQTT**
.NET Framework: **net461**
Library: **Microsoft.Azure.Deivces.Client 1.19.0**
Method: **DeviceClient.UploadToBlobAsync()**
OS Version: **Windows 10 Enterprise 2016 LTSB**

I have tried with two last versions of Microsoft.Azure.Devices.Client (1.19.0 and 1.29.0-preview-001), both time I got the same **UnauthorizedException**.

Only call to UploadToBlobAsync() failed, other features worked as expected.

Do you need more details, in order to reproduce this issue on your environment?

**Comment by prmathur-microsoft** [comment]
Can you please provide us with logs and stack Trace?

**Comment by Perun85** [comment]
Here is the relevant part of the log

```
08:45:09,640;ERROR;AuditLog;25;0;64d11e89-a2cb-404b-9920-f870d5c3af26;Error while uploading file to the cloud
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:44fabd5ea74b456e9bb4ff359c1b48c9-G:1-TimeStamp:02/13/2019 07:45:02"}
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__18`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<UploadToBlobAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Comment by prmathur-microsoft** [comment]
Thanks for the stack trace. We will investigate this issue on our side.

**Comment by Perun85** [comment]
It looks like this issue was resolved during last few weeks.

From how situation manifested itself, it looked like IoTHub was not authorized to access Blob storage. This was probably due to IoTHub not verifying CA signed certificates (CRL to be precise and Blob storage was). Now, when certificate CRL is correctly set and accessible, file upload with CA signed certificates is working. I haven't tested it with OSCP.

**Comment by az-iot-builder-01** [comment]
@CIPop, @Perun85, @bespinfw, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
