### ISSUE TITLE
SetMethodHandler not working when using MethodResponse constructor (int)

### ISSUE THREAD

**Issue by carlosaxpires** [Azure/azure-iot-sdk-csharp#43]
Hey guys,

Just found a bug on SetMethodHandler.

When setting an handler using SetMethodHandler and that handler returns "new MethodResponse(200)", it doesn't work server-side (reponse timeout exception is thrown), and on client-side an ArgumentNullException appears on the Debug console.
If instead, I use new MethodResponse(byte[], int) constructor it works!

(SDK Version: 1.2.1)

Thanks

**Comment by 86simonepenna** [comment]
I have the same problem:

`public sealed class StartupTask : IBackgroundTask
    {
        public void Run(IBackgroundTaskInstance taskInstance)
        {

           string deviceConnectionString = "xxxxxxxxxxxxx";

            var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt);

            deviceClient.OpenAsync().Wait();

            deviceClient.SetMethodHandlerAsync("WriteToConsole", WriteToConsole, null).Wait();


        }




        static Task<MethodResponse> WriteToConsole(MethodRequest methodRequest, object userContext)
        {
            var pin = GpioController.GetDefault().OpenPin(5);
            pin.SetDriveMode(GpioPinDriveMode.Output);

            if (pin.Read() == GpioPinValue.High)
            {
                pin.Write(GpioPinValue.Low);

            }
            else
            {
                pin.Write(GpioPinValue.High);
            }

            return Task.FromResult(new MethodResponse(200));
        }


    }`

When from my webapi app call the method with:
`serviceClient = ServiceClient.CreateFromConnectionString(connectionString);

        CloudToDeviceMethod oc = new CloudToDeviceMethod("WriteToConsole");

        CloudToDeviceMethodResult r = await serviceClient.InvokeDeviceMethodAsync("RaspberryVecomp", oc);`


non function.

The error is:

"Device {"Message":"ErrorCode:DeviceNotOnline;Timed out waiting for device to connect.","ExceptionMessage":"Tracking ID:b467cb8e1c544fbea30eb68bc0fee870-G:6-TimeStamp:01/29/2017 23:16:41"} not registered"

**Comment by tameraw** [comment]
@carlosaxpires - Thanks for filing. We'll provide a fix shortly.

**Comment by tameraw** [comment]
latest package released with this fix.
