### ISSUE TITLE
DeviceNotFoundException: Not registered when device is working and registered

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-csharp#431]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop and Server x64
- **Application's .NET Target Framework :** net451 and Java 1.8
- **Device:** Desktop computer / Azure Server
- **SDK version used:** Microsoft.Azure.Devices 1.6.0, Microsoft.Azure.AMQP 2.2.0, Microsoft.Azure.Devices.Shared 1.5.0, Java iot-device-client 1.9.0

# Description of the issue:
As I'm not sure which end is responsible for the issue I've also opened it here: 

[Java issue 216](https://github.com/Azure/azure-iot-sdk-java/issues/216)

Often receiving "Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException -> Not registered" when trying to invoke a method on a device that's running Java iot-device-client using MQTT protocol. The device is online, registered and not blocked, that's been checked on Azure portal directly while reproducing the issue. 

The error happens randomly but very often, some of the method calls work perfectly and some throw the exception (but we can see more exceptions than successful calls), when it fails it's not waiting the connection / response time before it returns the exception and most of the time the device is receiving the message and executing the method properly (even if we see the exception, which prevents us from receiving the method invocation result).

# Code sample exhibiting the issue:

.NET
```
CloudToDeviceMethod method = new CloudToDeviceMethod(METHOD_NAME, TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(20));
method.SetPayloadJson(JsonConvert.SerializeObject(message));

var result = await serviceClient.InvokeDeviceMethodAsync(DEVICE_ID, method);
```

Java

```
client.subscribeToDeviceMethod(new DeviceMethodCallback() {
	@Override
	public DeviceMethodData call(String methodName, Object methodData, Object context) {
		try{
			// ....
		        // Some operations with methodData which generate methodResponseStr
		        // ....
		        return new DeviceMethodData(200, methodResponseStr);
		} catch (Exception e){
			log.debug("Method exception", e);
		}
		return new DeviceMethodData(500, null);
	}
	}, null, new IotHubEventCallback() {
		@Override
		public void execute(IotHubStatusCode responseStatus, Object callbackContext) {
			log.debug("Method status: {}", responseStatus);
		}
	}, null);
```

# Console log of the issue:

> Device {"Message":"{\"errorCode\":404001,\"trackingId\":\"TRACKING_ID:18-TimeStamp:03/27/2018 09:47:35\",\"message\":\"Device not found\",\"timestampUtc\":\"2018-03-27T09:47:35.503359Z\"}","ExceptionMessage":""} not registered

**Comment by CIPop** [comment]
@pizerg Is this happening only on a particular HUB or any hubs? 
Could you please try to call the method using the Azure Portal?

**Comment by pizerg** [comment]
@CIPop It happened only on one HUB, it was created quite long ago so maybe that was the cause of the issue. I've tested the same scenario with a freshly created HUB and it works perfectly so as my original HUB had just less than 100 devices registered I've decided to migrate all of them to the new one.

I'm not closing the issue though as it might affect to other customers' old HUBS.

**Comment by CIPop** [comment]
> I've tested the same scenario with a freshly created HUB and it works perfectly so as my original HUB had just less than 100 devices registered I've decided to migrate all of them to the new one.

@pizerg thanks for finding the root cause! We can't talk about private information here. Could you please open a [Support Request](https://github.com/azure/azure-iot-sdk-csharp#need-support) from your subscription and add IoT Hub and device details for our service team to take a look?

/cc @simonporter @yzhong94 FYI

**Comment by CIPop** [comment]
> I'm not closing the issue though as it might affect to other customers' old HUBS.

For anyone hitting this issue, please open a [Support Request](https://github.com/azure/azure-iot-sdk-csharp#need-support) and specify the IoT Hub and DeviceID with the problem also referencing this GitHub issue.
_Do not_ share your subscription, hub or device information on GitHub.

**Comment by yzhong94** [comment]
@pizerg , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by ewinkiser** [comment]
I am getting this same exact Exception. DeviceNotFoundException. Was anything resolved with the Support Issue or should I open another one? Thanks Mike Kiser

**Comment by androidand** [comment]
I have the same issue as well, and in the message the Code property is not populated, however the ErrorCode is included inside the Message string...

**Comment by aleksve** [comment]
Same issue here. "not registered" pops up randomly

**Comment by rcastill** [comment]
Can you give us some support on this? I have a project from 2018 running on iot edge, but I cannot execute direct invokation from a script that I have from back then (that worked flawlessly).

**Comment by abhipsaMisra** [comment]
@ewinkiser , @androidand , @aleksve , @rcastill - We do not monitor issues that have been closed; would you mind opening a new issue with steps on how to reproduce this.

**Comment by rcastill** [comment]
Can this be reopened? I think it's difficult to reproduce since it happens with dated iot hubs (created some time ago). But it doesn't seem to be a problem with newer instances.

Unlike OP, I'd prefer to know what can be done other than migrating the devices/modules to a brand new hub.

**Comment by abhipsaMisra** [comment]
I see, thanks for the explanation. If this is an issue that you see only with older bugs, it indicates an issue on the service side. 

I would recommend opening a [support ticket](https://github.com/azure/azure-iot-sdk-csharp#need-support) so that the service team can investigate it at their end. There isn't anything that we can do from the SDK side here.
