### ISSUE TITLE
"Authorization required, resend request using supplied key",

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-iot-sdk-csharp#432]
hi,

Instead of SDK am directly calling rest api to enroll device and then register it.

Enroll call to rest api works fine but register call fails with error ""Authorization required, resend request using supplied key"" + gives me keyname and authenticationkey in error response.

I intercepted using fiddler how sdk makes register call and noted that sdk first gets 401 with above error and then it reissues another request which succeeds.

Currently am generating sas token based on shared keyname and primarykey of azure dps.

**Comment by CIPop** [comment]
@krishnasingh1818 this is not the right place to report this. This GH repo is exclusively for the .NET SDK.
See https://github.com/azure/azure-iot-sdk-csharp#need-support on how to open a Support Request from within your Azure subscription.

**Comment by yzhong94** [comment]
@krishnasingh1818 , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute customer satisfaction survey
