### ISSUE TITLE
Availability of routes and endpoints on Device Provisioning Service

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#435]
- **OS, version, SKU and CPU architecture used:**  Windows 10
- **Application's .NET Target Framework :** .net core and .net 4.5.6
- **Device:** TBD
- **SDK version used:** Latest from nuget

# Description of the issue:
Hi,

I want to know if DPS will ever have routes and endpoints made available on it (similar to IoT Hub). We are creating apis on top of the DPS to be used by the customer's custom UI and want to maintain a shadow of the individual and group enrollments. This is required because the the enrollments especially group one's will be created per customer or division or a business unit, having said that its imperative that the shadow of groups and devices and their associate with the entity is maintained somewhere (read database).

Any insights on this would be highly appreciated which will help us plan our road-map.

Thanks
Amogh
# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by CIPop** [comment]
@nberdy @alextolp PTAL

**Comment by amogh79** [comment]
@CIPop Thanks for routing the issue :)
@nberdy : Thanks for your response. What I mean to say here is like the IoT hub which allows us to act on device lifecycle events is there a way (or is planned) in DPS to capture events like enrollment (individual or group) added, updated, enabled/disabled, removed, device added to group, device removed from group etc.

**Comment by nberdy** [comment]
@amogh79 Thanks for the clarification! Right now we log errors via Azure diagnostics settings. One of the points of discussion within the team is how chatty logging successful events would be and what the best way for our customers to consume them. I don't have anything I can share at this time for DPS, but I'd love to hear your thoughts on consuming these events.

**Comment by alextolp** [comment]
One other question - which of the APIs are missing the paging functionality?

**Comment by amogh79** [comment]
@nberdy Its more about maintaining a association between a group created on DPS and the division to which DPS is agnostic (and it should be), plus consider a situation wherein there is a group which has millions of devices and the api that we have built on top of DPS makes a get on the group to get the group info and the device list within it. In this situation if I have a shadow copy of the group and devices I can easily query the DB and return the results instead of hitting the DPS to retrieve the group and device details.

**Comment by amogh79** [comment]
@alextolp I am using the DPS SDK but didn't find a way to get paginated results e.g. all the individual enrollments from the DPS.

**Comment by amogh79** [comment]
@alextolp Update: I was able to find how to paginate with a continuation token using query.NextAsync(continuationToken).ConfigureAwait(false);

**Comment by amogh79** [comment]
@alextolp My understanding is that the continuation token can help forward only paging. Any thoughts how I can move back within the pages?

**Comment by alextolp** [comment]
@amogh79 unfortunately moving back within pages is not supported on the service side. One way it could be accomplished is by using a caching layer on the client side.

**Comment by zolvarga** [comment]
Closing as resolved
