### ISSUE TITLE
Should SetDesiredPropertyUpdateCallbackAsync only send updates for Desired Property changes?

### ISSUE THREAD

**Issue by jillcary** [Azure/azure-iot-sdk-csharp#438]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp2.0
- **Device:** Azure Vm

# Description of the issue:
We are consuming `SetDesiredPropertyUpdateCallbackAsync` and have found from the documentation that a change notification will be fired any time there is a change to either the desired or reported properties.

From [docs.microsoft.com for SetDesiredPropertyUpdateCallbackAsync](https://docs.microsoft.com/dotnet/api/microsoft.azure.devices.client.deviceclient.setdesiredpropertyupdatecallbackasync?view=azure-dotnet)
> Set a callback that will be called whenever the client receives a state update (desired or reported) from the service. This has the side-effect of subscribing to the PATCH topic on the service.

Why is the event fired when reported properties are changed? Shouldn't the event only be fired on desired property changes?

# Code sample exhibiting the issue:
Because the event could be fired for reasons other than a desired property change, does this mean the desired properties callback may include an empty `TwinCollection` when fired?
```
public Task OnPropertyUpdateRequestedCallback(TwinCollection desiredProperties, object userContext)
{
   // do we need to do this check?
    if (desiredProperties != null && desiredProperties.Count > 0)
...
```

I have only been able to replicate the behavior that the callback is fired when a desired property is changed. 

For more context, see discussion on [Azure/device-simulation-dotnet](https://github.com/Azure/device-simulation-dotnet/pull/184/files/5ce81363d9770e42054b700034a877e64daa9ae0#diff-c770b2d3ed4cd2cff9c935e35b13f6daR67).

**Comment by CIPop** [comment]
Thanks for reporting this @jillcary !

**Comment by dluc** [comment]
could you provide an update, are you planning to change/fix this?

thanks

**Comment by az-iot-builder-01** [comment]
@jillcary, @CIPop, @dluc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
