### ISSUE TITLE
SetMethodHandlerAsync and SetMethodDefaultHandlerAsync cause failures on reconnect

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#443]
I have created a simple repro demonstrating that registering a handler with SetMethodHandlerAsync and/or SetMethodDefaultHandlerAsync causes consistent connection failures upon subsequent connection attempts.
 
The sequence is:
- Manually create a device in IoThub using Device explorer or similar.
- Run example code using connection string from device above, registering all the callbacks. This works.
- Run same code again. It will now fail getting an IotHubCommunicationException. 

The inner exception is quite peculiar in that it is a success exception. According to [this blog](https://www.medo64.com/2013/03/error-the-operation-completed-successfully/), this indicates that a pinvoke call hasn't had SetLastError set to true.  The stack trace doesn't make it obvious how that could be the case though.  Also, if you use the normal retry behavior, behind the scenes it will connect/disconnect repeatedly until it times out. 

This is on Windows 10, .net 4.6.1, with Microsoft.Azure.Devices.Client 1.6.0-preview-001.
[IoTHubTest.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1869841/IoTHubTest.zip)

**Comment by v-tbert** [comment]
I tried the same code with a .net core 2.0 project as well and got the same result. I also tried upgrading to 1.17.0-preview-004, again with the same result.

**Comment by v-tbert** [comment]
My real code is intended to run as edge preview modules however there is a separate blocking problem with the EdgeHub module I am tracking down with the team. That issue prevents me from running in that context currently so I was trying to use a stripped down of my device code to communicate directly with iothub since the docs say device twin properties/methods work currently.

**Comment by v-tbert** [comment]
This is the stack trace but I fear it may be misleading. When I ran the debugger against decompiled sources it looked like the exception might actually be originating from mscorlib. I look forward to your diagnosis. :)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.<SubscribeAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.<WriteAsync>d__28.MoveNext()

**Comment by prmathur-microsoft** [comment]
Can you try this with 1.20.0 ? We believe we have handled issues like this in the redesign.

**Comment by abhipsaMisra** [comment]
I am trying to repro this issue using the sample code provided, and wanted some clarification:
```
The sequence is:
- Manually create a device in IoThub using Device explorer or similar.
- Run example code using connection string from device above, registering all the callbacks. This works.
- Run same code again. It will now fail getting an IotHubCommunicationException.
```
For the 3rd step, are you re-registering the method handlers for the same device client instance; or are you running the entire application again (starting from device client creation - registering - closing etc)?

I tried both of the options using Microsoft.Azure.Devices.Client 1.20.3, and did not get any exceptions.
Could you give it a try from your end and let us know in case you face further issues.

**Comment by prmathur-microsoft** [comment]
Closing this for now as we believe our latest SDK resolves this issue. Feel free to open another issue in case you still see it.

**Comment by az-iot-builder-01** [comment]
@v-tbert, @CIPop, @prmathur-microsoft, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
