### ISSUE TITLE
device-explorer hangs on receiving high volume of events

### ISSUE THREAD

**Issue by bospoort** [Azure/azure-iot-sdk-csharp#444]
when processing a large number of events from IOT hub, the device-explorer UI hangs. You have to kill it with task manager

**Comment by CIPop** [comment]
Thanks @bospoort for opening and __fixing__ the issue!

**Comment by tameraw** [comment]
@bospoort thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
