### ISSUE TITLE
Calling CloseAsync on DeviceClient doesn't trigger handler registered with SetConnectionStatusChangesHandler

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#449]
Explicitly closing a DeviceClient connection that has a handler registered for connection status does NOT cause the handler to be fired. 

deviceClient.SetConnectionStatusChangesHandler(OnStatusChanged);
await deviceClient.OpenAsync();
await deviceClient.CloseAsync();
await deviceClient.OpenAsync();

  <package id="DotNetty.Buffers" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Codecs" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Codecs.Mqtt" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Common" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Handlers" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Transport" version="0.4.7" targetFramework="net461" />
  <package id="Microsoft.Azure.Amqp" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices" version="1.6.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Client" version="1.7.1" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.5.0" targetFramework="net461" />

**Comment by v-tbert** [comment]
Relevant packages:
`  <package id="DotNetty.Buffers" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Codecs" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Codecs.Mqtt" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Common" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Handlers" version="0.4.7" targetFramework="net461" />
  <package id="DotNetty.Transport" version="0.4.7" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.Azure.Amqp" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices" version="1.6.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Client" version="1.7.1" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.5.0" targetFramework="net461" />`

**Comment by zolvarga** [comment]
@v-tbert 

Thanks for reporting the issue we will take a look at it.

Best Regards,
Zoltan

**Comment by RubiaL** [comment]
Can you try with our latest sdk this issue is resolved in our latest version(1.21.1)

**Comment by abhipsaMisra** [comment]
As tested with the latest SDK, we do return the connection status change on `CloseAsync()`.

```csharp
using var dc = DeviceClient.CreateFromConnectionString(s_deviceConnectionString, s_transportType);
dc.SetConnectionStatusChangesHandler((status, reason) =>
{
    Console.WriteLine($"{DateTime.Now}>> Connection status change: status={status}, reason={reason}");
});

await dc.OpenAsync().ConfigureAwait(false);
await Task.Delay(1000).ConfigureAwait(false);
await dc.CloseAsync().ConfigureAwait(false);
await Task.Delay(1000).ConfigureAwait(false);
```
Output:
```
4/14/2020 1:22:08 PM>> Connection status change: status=Connected, reason=Connection_Ok
4/14/2020 1:22:09 PM>> Connection status change: status=Disabled, reason=Client_Close
```

Closing this issue since the SDK works as expected.

**Comment by az-iot-builder-01** [comment]
@v-tbert, @Zuendelmeister, @RubiaL, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
