### ISSUE TITLE
SetDesiredPropertyUpdateCallback() is not working.

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-csharp#45]
Using master from https://github.com/Azure/azure-iot-sdk-csharp.git, the callback function is not getting called when the Device Twin desired properties change.

Here's the WPF application code I have tested with:

    public partial class MainWindow : Window
    {
        private const string DeviceConnectionString = "<connection string>";
        private DeviceClient _deviceClient;

        public MainWindow()
        {
            InitializeComponent();
        }

        private void OnTest(object sender, RoutedEventArgs e)
        {
            _deviceClient = DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);
            _deviceClient.SetDesiredPropertyUpdateCallback(OnDesiredPropertyUpdate, this);
            _deviceClient.SetMethodHandlerAsync("MyMethodAsync", MyMethodAsync, null);

        }

        public Task OnDesiredPropertyUpdate(TwinCollection desiredProperties, object userContext)
        {
            Debug.WriteLine("Property!");
            return null;
        }

        Task<MethodResponse> MyMethodAsync(MethodRequest methodRequest, object userContext)
        {
            Debug.WriteLine("Method!");
            return null;
        }
    }

**Comment by gmileka** [comment]
Based on investigation, the code creates the first chain of inner handlers correctly and sets the callback. However, within the call of SetDesiredPropretyUpdateCallback(), the code resets part of the chain without setting the callback again - so it gets lost.
We did a work around where we checked if the inner handler is present before creating a new one. This unblocked us.

**Comment by gmileka** [comment]
Jasmine pointed me to the sample, and the problem is that I’m missing the explicit call to OpenAsync()

                Client = DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);
                Client.OpenAsync().Wait(); // <-- this is missing in my repro.
                Client.SetDesiredPropertyUpdateCallback(OnDesiredPropertyChanged, null).Wait();

Once I added this, things started to work.

This makes sense, because when I debugged SetDesiredPropertyUpdateCallback(), it ended-up calling OpenAsync(), and during that call the callback was lost. In other words, the code path for OpenAsync() does not expect the callbacks to be set, and overwrites them.

So, if SetDesiredPropertyUpdateCallback() is expected to handle the case where OpenAsync() hasn't been called yet - we might still have a bug.

**Comment by jasmineymlo** [comment]
The is a valid bug and SetDesiredPropertyUpdateCallback() is expected to handle the case where OpenAsync() hasn't been called.  Fix is on the way.  Thanks.

**Comment by jasmineymlo** [comment]
commit: ccd8bc9fcd9d5bbacee9977421e0471aee1f335c

**Comment by olavt** [comment]
I'm trying to run the sample (https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/samples/DeviceClientTwinMqttSample/Program.cs), but it crashes on:

``Client.SetDesiredPropertyUpdateCallback(OnDesiredPropertyChanged, null).Wait();``

Connecting to hub

Error in sample: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.Transport.TransportHandlerFactory.Create(IPipelineContext context)
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass24_0.<BuildPipeline>b__4(IPipelineContext ctx)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.EnsureInnerHandlerInitialized()
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.get_InnerHandler()
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.set_TwinUpdateHandler(TwinUpdateCallback value)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.set_TwinUpdateHandler(TwinUpdateCallback value)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.set_TwinUpdateHandler(TwinUpdateCallback value)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.set_TwinUpdateHandler(TwinUpdateCallback value)
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass60_0.<<SetDesiredPropertyUpdateCallback>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__17.MoveNext()

The only modification I did to the code was to set the connection string for my device on the form:

"HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>"

using my real connection string for the device of course.

**Comment by tameraw** [comment]
Fix provided in 1.2.3. Please let us know if still having issue.

**Comment by Se3ker** [comment]
This issue still remains, I'm using v. 1.2.10.
Also the fix Client.OpenAsync().Wait(); or await Client.OpenAsync(); does not work either
As per documentation the client should upon startup fetch desired properties, I'm also not seing that to work, currently I'm fetching them myself in code on startup.
