### ISSUE TITLE
Device client unregistered after calling a direct method with no payload

### ISSUE THREAD

**Issue by davidjrh** [Azure/azure-iot-sdk-csharp#452]
- **OS, version, SKU and CPU architecture used:** Windows 10 IoT Core arm32
- **Application's .NET Target Framework :** net452
- **Device:** Raspberry PI3
- **SDK version used:** N/A

# Description of the issue:
This seems a bug not from the device point of view, since the device registers correctly. I found the problem when building a client application with the Microsoft.Azure.Devices nuget (v1.6.0). After having the device correctly registered and responding to the direct methods calls done through the Azure portal, once I call the direct method of the device from a client app, the device is no longer available (message exception saying my device was not found). 

# Code sample exhibiting the issue:
I initially created a console app to call a direct method, that works well. The call was something like this:
```
var connectionString = "HostName=xxxx.azure-devices.net;SharedAccessKeyName=xxxbowner;SharedAccessKey=...";
using (var serviceClient = ServiceClient.CreateFromConnectionString(connectionString))
{
   var methodInvocation = new CloudToDeviceMethod("MyMethodName") { ResponseTimeout = TimeSpan.FromSeconds(30) };
   var response = serviceClient.InvokeDeviceMethodAsync("mydevicename", methodInvocation).Result; 
}
```
But then I moved the code to another app and was causing the device being unregistered. After trying to find a difference, I found the cause using Fiddler. The console app was sending the following request body:
```
{
  "methodName": "OpenTheDoor",
  "payload": null,
  "responseTimeoutInSeconds": 30
}
```

while the second app was sending the following on the request body:
```
{
  "methodName": "OpenTheDoor",
  "responseTimeoutInSeconds": 30
}
```

The second application had this setting on the serializer:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
            {
                NullValueHandling = NullValueHandling.Ignore
            };
```
So the problem I see on the IoT API, is that if for whatever reason I don't send the "payload" element on the request body, the device is disconnected, sounds like a bug on the server side. 

Another workround is to send an explicit empty payload like this one:

```
var connectionString = "HostName=xxxx.azure-devices.net;SharedAccessKeyName=xxxbowner;SharedAccessKey=...";
using (var serviceClient = ServiceClient.CreateFromConnectionString(connectionString))
{
   var methodInvocation = new CloudToDeviceMethod("MyMethodName") { ResponseTimeout = TimeSpan.FromSeconds(30) };
   methodInvocation.SetPayloadJson(JsonConvert.SerializeObject(""));
   var response = serviceClient.InvokeDeviceMethodAsync("mydevicename", methodInvocation).Result; 
}
```

**Comment by timtay-microsoft** [comment]
This may have been a service side bug at some point, but I can't repro this on the current client SDK version against the current service, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@davidjrh, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
