### ISSUE TITLE
DeviceClient.OpenAsync() takes ~2 minutes to throw UnauthorizedException when the device is unregistered.

### ISSUE THREAD

**Issue by trbenning** [Azure/azure-iot-sdk-csharp#453]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64, Ubuntu 17.10 x64
- **Application's .NET Target Framework :** netcoreapp2.0
- **Device:** Desktop, VM, & Custom SBC running Ubuntu 17.10
- **SDK version used:** 1.7.1

# Description of the issue:
I have a workflow where I create a DeviceClient using `DeviceAuthenticationWithX509Certificate` with `TransportType.Amqp_Tcp_Only`, and call `DeviceClient.OpenAsync()`. If the call throws `UnauthorizedException`, I attempt to register the device via a custom registration server before attempting to open the client again.

The issue I'm seeing is that the initial call to `OpenAsync` takes around 2 minutes before throwing the exception, which seems a bit extreme. I can obviously work around this behavior (and I am), but I was hoping there might be a better, faster way to handle this. In the future, I plan to change the implementation to use CA certificate auth & Device Provisioning Service, but I need this auth scheme to work in the meantime.

# Code sample exhibiting the issue:
```
using(var cert = new X509Certificate2(appSettings.CertificatePath))
using(var client = DeviceClient.Create(appSettings.IoTHubHost,
    new DeviceAuthenticationWithX509Certificate(appSettings.DeviceId, cert), TransportType.Amqp_Tcp_Only))
{
    try
    {
        await client.OpenAsync().ConfigureAwait(false);
    }
    catch(UnauthorizedException)
    {
        // ~ 2 mins pass before getting here.
        await RegisterDevice().ConfigureAwait(false);
    }
}
```

**Comment by zolvarga** [comment]
@trbenning 

Thank for reporting the issue, we will take a look at it.

Best Regards,
Zoltan

**Comment by prmathur-microsoft** [comment]
We have had several releases post the version of the SDK you mentioned for this issue.
Could you please try and let us know if you still see issues on our latest SDK.

**Comment by trbenning** [comment]
I cannot reproduce this in the 1.21.0 SDK.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @trbenning, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
