### ISSUE TITLE
JobResponse.EndTimeUtc is DateTime.MaxValue instead of null when JobStatus is Running

### ISSUE THREAD

**Issue by jillcary** [Azure/azure-iot-sdk-csharp#467]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop
- **Application's .NET Target Framework :** netcoreapp2.0
- **Device:** <DEVICETYPE> simulated devices
- **SDK version used:** <VERSION> Microsoft.Azure.Devices v1.4.1

# Description of the issue:

In [Azure Remote Monitoring](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet) we were seeing an issue where a running job was returning the max date value for `EndTimeUtc` (pictured below)
![image](https://user-images.githubusercontent.com/3317135/39552782-955587ae-4e1f-11e8-9bd3-e3c8a7c1b1d2.png)

On inspection of the result from the `JobResponse` from `jobClient.GetJobAsync(jobId)` was returning DateTime.MaxValue (...12/30/9999) when the `JobStatus` is "Running".

Since the [`JobResponse.EndTime`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.jobresponse.endtimeutc?view=azure-dotnet) property is a `Nullable<DateTime>` I would expect the value returned to be null instead of max date.

The current workaround is to check the JobStatus and return null to our UI for any state that would not have an EndTimeUtc [Running, Enqueued, Queued, Scheduled] (example workaround from azure/iothub-manager-dotnet [here](https://github.com/Azure/iothub-manager-dotnet/pull/117/files))

**Comment by bikamani** [comment]
@jillcary Does this issue still exist? Also, is it still using same version of Service Client SDK (which is deprecated)?

**Comment by bikamani** [comment]
As there has not been any update on this, we are closing the issue. Please re-open it if needed. Thanks

**Comment by az-iot-builder-01** [comment]
@jillcary, @bikamani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
