### ISSUE TITLE
How to handle connection issue during sending message in AMQP protocol

### ISSUE THREAD

**Issue by bartoszbr** [Azure/azure-iot-sdk-csharp#47]
I investigate topic about handling connection issues with Azure IoT.
I need information how to handle connection issue during sending message (C2D) from ClientService object to Device using AMQP protocol.
I can easily test situation when Internet is disconnected and I try send message - I receive exception System.OperationCanceledException: The AMQP object link25 is aborted at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__27.MoveNext()
Test with Internet disconnection during transfer message is harder. I assume that protocol AMQP uses checksum so this situation should throw also some exception, but I'm not sure about this. I dont't know what exception should it throw and how to be sure that message won't be lost?

**Comment by jasmineymlo** [comment]
You should get OperationCancelledException for the case of disconnection during transfer message as well.  Both AMQP and service client libraries do not retry on exceptions.  You will have to resend on exceptions to ensure messages are send successfully.
