### ISSUE TITLE
Using SendEventBatchAsync does not send whole batch like AMQP

### ISSUE THREAD

**Issue by ai0038911** [Azure/azure-iot-sdk-csharp#472]
Hi There,
I am building a scenario where I need to send 10K messages per second to IOT hub and dump it in Cosmos DB, our requirement is to use MQTT Protocol but it is resulting in more time as compare to AMQP. when I look at the logs of Azure function receiving these messages when Batch sent over MQTT, function executes once per message as opposed to when sent over AMQP, functions executed only once for whole Batch.

Configurations used for simulating with 1 device
Message Batch :  120
IOT HUB: S2 with 1 Unit
trying to send a batch of 120 messages takes around 0-40secs with MQTT as compare to AMQP which takes 0-2Secs.

Your help with Ideas & Other Approach would be highly appreciated.

Thanks
Amol

**Comment by prmathur-microsoft** [comment]
Currently we do not support batching over MQTT and currently we don't have plans for the same.

**Comment by az-iot-builder-01** [comment]
@ai0038911, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
