### ISSUE TITLE
Proxy support for Azure IoT Hub and Provisioning SDKs

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-csharp#477]
With the release of .net core 2.1, is HTTP proxy support a planned feature of C# device  SDK?
iot-edge v2 relies on this particular feature of C# device sdk. 

This was initially raised on user voice with no response([1](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109161-setup-proxy-settings-through-device-client-sdk)). Is there an approximate time line we can look at?

**Comment by yzhong94** [comment]
Hi @kiranpradeep , this is something in our backlog.  Can you provide more background on the scenario?  This will help us with priority.  In addition, we are an open-sourced project, so you can also contribute back by providing a pull request.

**Comment by kiranpradeep** [comment]
@yzhong94 Thanks for the reply. For background, please see this comment[1]. Unless this C# SDK implements HTTP Proxy support, iot-edge v2(edgeAgent) project cannot proceed with HTTP Proxies.

Sorry. I don't know C# enough to get to a pull request. 

[1] https://github.com/Azure/iot-edge/issues/465#issuecomment-358491430

**Comment by stpapaix** [comment]
Hi, 
With my Customer  (large Oil & Gas company) we have several IoT opportunities in industrial environement (refineries and offshore site) 
"No proxy support"  is a strong blocking point for IoT project deployment .  
If I can have an update on the planning to implement this feature it will be great for me. 
Thanks in advance,

**Comment by CIPop** [comment]
@JakkeFiejest, Similarly to https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md, please submit an API design for our review.

**Comment by abhipsaMisra** [comment]
In Windows and Linux machines, I set the system proxy and tested if we are able to gather the proxy information from the system settings. The results below are on testing by switching the project Target Framework between .NET Core 2.0 and .NET Core 2.1.
 We currently have support for the following:

__HttpClient__

Windows:

  | http_proxy | https_proxy
-- | -- | --
.NET Core 2.0 | Yes | Yes
.NET Core 2.1 | Yes | Yes

Linux:

  | http_proxy | https_proxy
-- | -- | --
.NET Core 2.0 | Yes | Yes
.NET Core 2.1 | Yes | Yes

__ClientWebSocket__

Windows:

  | ws | wss
-- | -- | --
.NET Core 2.0 | No | No
.NET Core 2.1 | Yes | Yes

Linux:

  | ws | wss
-- | -- | --
.NET Core 2.0 | No | No
.NET Core 2.1 | Yes | Yes

__Steps followed to set system proxy:__


- Windows:
  * Open Settings --> Network & Internet --> Proxy
  *  Configure the proxy server address and port in Manual Proxy Setup


- Linux:

  * For http_proxy, configure the proxy server in the following format:

    `export http_proxy=http://<proxy_server_ip>:<port>`
  * For https_proxy, configure the proxy server in the following format:

    `export https_proxy=http://<proxy_server_ip>:<port>`

For additional details on how corefx handles proxies, please refer to [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs)

**Comment by abhipsaMisra** [comment]
CoreFX issue reference: https://github.com/dotnet/corefx/issues/31242

**Comment by abhipsaMisra** [comment]
The PR for this feature has been merged. The sample usage can be found [here](https://github.com/Azure/azure-iot-sdk-csharp/pull/569). Thanks!

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, @stpapaix, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
