### ISSUE TITLE
Buffer length mismatch when parsing TPM key

### ISSUE THREAD

**Issue by andrepodnozov** [Azure/azure-iot-sdk-csharp#478]
https://github.com/Azure/azure-iot-sdk-csharp/blob/93fddf0eeae787e23b1611b649ed22013c86466f/security/tpm/src/SecurityProviderTpmHsm.cs#L105

Currently this line reads:
encWrapKey = m.GetArray<byte>(encryptedSecret.Length, "encWrapKey");

If my understanding of this code is correct, it should be instead:
encWrapKey = m.GetArray<byte>(encWrapKey.Length, "encWrapKey");

Thanks,
#IotAiInsiderLabs

**Comment by abhipsaMisra** [comment]
@andrepodnozov - Thank you for bringing this to our notice, we have updated the code. Thanks!
