### ISSUE TITLE
Add Feature to Remove and Link IoT Hub to Device Provisioning Service Programmatically 

### ISSUE THREAD

**Issue by vithal-wadje** [Azure/azure-iot-sdk-csharp#479]
- **OS, version, SKU and CPU architecture used:**  Windows 10 Desktop x64, x86
- **Application's .NET Target Framework :** 4.6.1 , Visual Studio 2017
- **Device:**  Laptop, Desktop
- **SDK version used:** Microsoft.Azure.Management.DeviceProvisioningServices 0.9.0-preview and Microsoft.Azure.Management.ResourceManager.Fluent 1.10.0

# Description of the issue:
I am using **Microsoft.Azure.Management.DeviceProvisioningServices 0.9.0-preview** and **Microsoft.Azure.Management.ResourceManager.Fluent 1.10.0** to get the DPS & Linked IoT hub details for particular DPS. I am getting Linked IoT hub details using **ProvisioningServiceDescription** class which falls under **Microsoft.Azure.Management.DeviceProvisioningServices 0.9.0-preview** successfully. Now I wants to link IoT hub to DPS  and remove IoT hub from DPS programmatically instead of doing from Azure portal,It will be huge value addition if you introduce these feature in next version of  **Microsoft.Azure.Management.DeviceProvisioningServices 0.9.0-preview** .

Let me know if requires any other details

**Comment by yzhong94** [comment]
@vithal-wadje Thanks for filing the issue.  This repository is for client SDKs, not management SDKs.  @alextolp as FYI for this request.

**Comment by vithal-wadje** [comment]
Hi @alextolp 

This template is for creating Whole DPS. This feature is also available in SDK to Delete, Update or create DPS but I wants specifically Link IoT hub to the **Existing DPS**  and Remove Linked IoT Hub from **existing DPS** , I can not be wanted to Modify the whole SDK. 

Consider the example 

- I **have existing DPS instance** 
I have linked two IoT hubs to existing DPS instance , Now my DPS has two linked IoT hubs , now I wants to remove specific IoT hub or again I want to link other IoT hub. It means  that should only specific to linking to removing IoT hub from existing DPS instead of whole DPS.

if you introduce the method , like it will take resource group name , DPS name & IoT hub details to link & second method for removing linked IoT hub which will take parameters resource group name , DPS name & name of the IoT hub which needs to be remove from existing DPS linked IoT hub.

Similar to following , This option given in azure portal , Go to the existing DPS instance ->find linked IoT hubs option -> then choose link IoT hub

![image](https://user-images.githubusercontent.com/9838323/40100140-82495f14-5900-11e8-9a0c-f35730cde741.png)

Let me know if requires any other details

**Comment by alextolp** [comment]
We don't have this method today, but you could certainly implement it yourself using our SDK -

https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/DeviceProvisioningServices/Management.DeviceProvisioningServices/Generated

**Comment by yzhong94** [comment]
Closing this issue for now.  Please use azure-sdk-for-net for this issue.  

@vithal-wadje , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by alextolp** [comment]
@vithal-wadje  thanks for your feedback! We'll review our API surface to ease usability of managing IotHubs.
