### ISSUE TITLE
Devices communicating with IoT hub from behind a firewall

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#487]
- **OS, version, SKU and CPU architecture used:** <Windows 10> 
- **Application's .NET Target Framework :** <.net 4.6> 
- **Device:** <Other> 
- **SDK version used:** <Latest from nuget> 

# Description of the issue:
Hi,

We are in very funny situation here. Devices are behind a corporate firewall and need to communicate with IoT hub in the cloud. There are 5k-6k odd ips that Azure has and client is not ready to open ports to all those ips. What would be the best solution to have this issue addressed? I have suggested having a gateway on a VM to which ports are opened and devices send data to the gateway. The gateway in turn sends the data to IoT hub. Are there any better options? Please suggest.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by yzhong94** [comment]
Hi @amogh79, here's some [documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-protocols) on our communication protocols.  Would AMQP over websocket work for you?

**Comment by zolvarga** [comment]
@amogh79 

Please let us know if your question has been answered or not

Best Regards,
Zoltan

**Comment by CIPop** [comment]
I agree with @yzhong94 's answer. In summary:

- Open the ports required by the preferred protocol for _outbound_ communication.
- Open ports for generic _outbound_ HTTPS access and use WebSockets over either AMQP or MQTT.
- Your solution of using a Gateway. You could also look into the new Edge component (SDK portion within our modules-preview branch) for the same purpose.

@amogh79, Please reopen if that doc doesn't answer your question.
