### ISSUE TITLE
RegistryManager.AddDeviceAsync throws ArgumentException after upgrade to 1.5 - 1.6

### ISSUE THREAD

**Issue by DOliana** [Azure/azure-iot-sdk-csharp#500]
I have upgraded the Microsoft.Azure.Devices nuget package from 1.4.1 to 1.5.1 and 1.6 (tried both) and the following code does not work anymore - it throws an ArgumentException.

## Code:
```CS
var Id = Guid.NewGuid().ToString();
var device = new Device(Id)
{
	Authentication = new AuthenticationMechanism
	{
		Type = AuthenticationType.CertificateAuthority
	}
};
device = await registryManager.AddDeviceAsync(device);
```
## Exception
```
System.ArgumentException: {"Message":"ErrorCode:ArgumentNull;BadRequest","ExceptionMessage":"Tracking ID:aa9a5d1e6b2f4fbbb2e67cd71994f931-G:4-TimeStamp:06/07/2018 10:15:21"}
   bei Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__36.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Azure.Devices.HttpClientHelper.<PutAsync>d__12`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Functions.RESTDeviceRegister.Function.<Run>d__2.MoveNext() in ***\RESTDeviceRegister\Function.cs:Zeile 46.
```
## Plattform:
- .NET Framework 4.6.1
- destined to run within Azure function (currently runs locally)

**Comment by CIPop** [comment]
@DOliana thanks for reporting. I'll try to repro.

**Comment by CIPop** [comment]
@DOliana I can't repro with 1.6.1 and my test IoT Hub.

If you still observe this with the latest release, it could be a service-side issue. 
For service-side issues please use your Azure Subscription to create a service request: https://github.com/azure/azure-iot-sdk-csharp#need-support

**Comment by DOliana** [comment]
@CIPop you are right - it does not occur from a console app.

What I am facing is a library mismatch, since I am running that code from within an Azure Function which relies on Newstonsoft.JSON version 9.0.1 whereas the SDK requires > 10.0.3. So this means, that versions of the SDK > 1.4.1 cannot be used from within an Azure function v1.
