### ISSUE TITLE
DeviceClient loses connection with Azure

### ISSUE THREAD

**Issue by MarkoatPriva** [Azure/azure-iot-sdk-csharp#513]
Hello,

we have an issue in our production environment.
Devices come into a state in which the DeviceClient thinks there is a connection (or is in a retrying state) but the device in unreachable from the outside. The device does not recover and the service has to be restarted (Windows 10).

In the logs we see the DeviceClient changing state:

"2018-06-07";"02:42:40.850";"Event";OnDeviceConnectionStateChanged. Message: Connection state changed to Disconnected_Retrying because of No_Network."

or

"2018-06-07";"01:00:02.716";"Event";"OnDeviceConnectionStateChanged. Message: Connection state changed to Connected because of Connection_Ok."

After these connection state changes the DeviceClient is unreachable from Azure.
This only happens sometimes and is hard to reproduce.

A reproduction example can be found here; https://1drv.ms/u/s!Ai1EWmdAubY4ibdfGwFGl9INjoicow
To best way to 'force' a reproduction is starting the application two times, because the two applications will both try to claim the connection, the sate we cannot recover from is always reproducible like this, it is hard to reproduce otherwise (without starting the application two times).

![repro](https://user-images.githubusercontent.com/40236044/41350282-ecb111bc-6f12-11e8-8ff0-b7e032628a55.PNG)

I have added a screenshot with the repro app with the latest DeviceClient package 1.7.1.
What you can see is that one of the two applications is connected and the other one thinks it is in a connection_ok state, while it is unreachable.
This is wat we see in production sometimes and because there is no way to check  if the connection is really ok (or can we?), we are trying to find a way to detect this situation @ runtime so we can reconnect (without physical intervention).

I can image we are handling the reconnect scenario in a wrong way, that is why I’m looking for an example or guidance from Microsoft on how to handle the scenario. I’m not sure at this time if it is an issue in our code or in the SDK.

Marko

**Comment by CIPop** [comment]
Thanks for the report @MarkoatPriva !

Using the same DeviceID in two different applications is not supported: as you are saying, one of the devices will be allowed through while the other will not although I don't think that the state is correct (network is available although the connection might have been refused). Also, not recovering after some time seems to be a bug.

I have a few follow-up questions while I attempt to repro this:

1. What is the exact OS version / .NET Runtime are you using?  (I did notice that the sample app has a TFM of .NET 4.6.2.)
2. What do you mean by "service"? Is this a Windows Service (managed through SCM)?
3. Is there any chance that two processes are active at the same time?

**Comment by MarkoatPriva** [comment]
Hi Cristian,

It is clear that using the same DeviceID is not supported. We just did this to be able to reproduce the issue about the DeviceClient coming into a 'Wrong' connection state. In production it is not possible to have two services running with the same DeviceID. This is just the only sure way to reproduce this in a short amount of time.

- What is the exact OS version / .NET Runtime are you using? (I did notice that the sample app has a TFM of .NET 4.6.2.) :  _.NET 4.6.1_

![winer](https://user-images.githubusercontent.com/40236044/41399179-eaaa7c62-6fb9-11e8-827f-78c6431bfdbf.PNG)

- What do you mean by "service"? Is this a Windows Service (managed through SCM)? _Yes_
- Is there any chance that two processes are active at the same time? : _No_

**Comment by jason-e-gross** [comment]
I've noticed that after an initial "iotedgectl restart", when the containers start back up again -- on the very first SendEventAsync of a module - the connection is lost and 99.9% of the time it reconnects successfully.  A super rare few times it doesn't, and the module is in a "hung" state.

Noticed this by adding the connection watcher right after OpenAsync.

**Comment by jason-e-gross** [comment]
It wasn’t just Edge or Modules.  The point I was making that in either – the delay and timeout happened, with .NET Core 2.1 being the culprit.   Whether it was DeviceClient or ModuleClient.    Bumping back down to 2.0, it went away.   Bumping it up to NET Core 2.1, the OpenSync delay and timeout returned.

________________________________

**Comment by MarkoatPriva** [comment]
Hi Cristian,

any news?
Or examples on the best way to handle connection changed events?

Question, do we have to create a new DeviceClient when we reconnect?
Or can we use the existing one? Using the already created DeviceClient makes certain scenario's more easy to deal with.

**Comment by MarkoatPriva** [comment]
When we keep the created DeviceClient  in the attached example, and do not call:

await this.deviceClient.CloseAsync();
await this.deviceClient.Dispose();

But do call: await this.deviceClient.OpenAsync();

we end up in a connected state: Connected -- Connection_Ok
Now, messages are received .. but direct method calls can not be received :(.

**Comment by CIPop** [comment]
> It wasn’t just Edge or Modules.  The point I was making that in either – the delay and timeout happened, with .NET Core 2.1 being the culprit.

Thanks @jason-e-gross for clarifying. We need to move to .NET Core 2.1 within our test code. I'll try to get to this soon. We did test 2.1 preview sometime in March-April and didn't notice any issues back then.

**Comment by CIPop** [comment]
> Question, do we have to create a new DeviceClient when we reconnect?
> Or can we use the existing one? Using the already created DeviceClient makes certain scenario's more easy to deal with.
> [..]
> Now, messages are received .. but direct method calls can not be received :(.

Sorry, no news yet..
You shouldn't need to re-create the DeviceClient objects if you didn't dispose them. What you are describing is a bug.

**Comment by jason-e-gross** [comment]
I have my toes in another issue related that you're involved with, but I did want to comment also that it only happens with mqtt for us.  If we switch to aqmp, there's no timeouts.  2.0 and 2.1.

________________________________

**Comment by CIPop** [comment]
> I have my toes in another issue related that you're involved with, but I did want to comment also that it only happens with mqtt for us.  If we switch to aqmp, there's no timeouts.  2.0 and 2.1.

@jason-e-gross sounds like #521. Let's continue there and keep this issue to track the investigation for method call and DeviceClient connectivity state reported by @MarkoatPriva.

**Comment by prmathur-microsoft** [comment]
Can you please check if this issue is resolved in latest SDK 1.20.3? We have a had a major redesign and we addressed a bunch of failures related to retry there.

**Comment by timtay-microsoft** [comment]
@MarkoatPriva are you still seeing any issues here?

**Comment by MarkoatPriva** [comment]
No, we do not, _**but**_ we did change the implementation.
We no longer reuse the DeviceClient, but create a new one and use that.

**Comment by RubiaL** [comment]
we believe this issue should be fixed in our latest version ( 1.21.1) feel free to re open if you still see this issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, @MarkoatPriva, @jason-e-gross, @prmathur-microsoft, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
