### ISSUE TITLE
DeviceClient and System.Net.Security not found when using "MQTT" (works with "HTTP")

### ISSUE THREAD

**Issue by cabbagecreek** [Azure/azure-iot-sdk-csharp#516]
I have tested with a Windows Form app.. This works
_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Mqtt);

Then testing the same code in UWP I get System.Net.Security not found.
Changing to:
_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Http1);
Works!!!

**Comment by CIPop** [comment]
> UWP I get System.Net.Security not found.

Sounds like you are not using the correct version of UWP: we only support netstandard2.0 versions which means your application must target Windows 10 version 1709 (build 16299 and above).

**Comment by cabbagecreek** [comment]
I am using Windows 10, version 1803,(10.0; Build 17134)

![image](https://user-images.githubusercontent.com/713313/41483340-0ee26818-70d9-11e8-9d87-81a3a4624e5f.png)
