### ISSUE TITLE
DeviceClient/ModuleClient .OpenAsync Timeouts/Delays with .NET Core 2.1

### ISSUE THREAD

**Issue by jason-e-gross** [Azure/azure-iot-sdk-csharp#521]
- **OS, version, SKU and CPU architecture used:** Windows 10 64 bit, Linux Ubuntu 16.04 (the delay appears in both).
- **Application's .NET Target Framework :** netcoreapp21
- **Device:** AMD64 machines

## Description of the issue:
When updating the IOT Edge project to use .NET Core 2.1, it introduces delays and timeouts in devices or modules at .OpenAsyc.         About 30% timeouts to crashing (which edgeAgent restarts the module) to 70% delays of over 20-30 seconds or more.

## Code sample exhibiting the issue:
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />

It shows in either:
~~~~
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.17.0-preview-007" />
~~~~
or 
~~~~
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.6.0-preview-001" />
~~~~

If we downgrade back to .NET Core App 2.0, the timeout/delay goes away, and .OpenAsync is as quick as you would expect it to be.      It exhibits itself in three modules we tried updating - which range from nothing more special than the FilterModule example to one that uses Kestrel/SignalR (port 8012).  

Updating to the 1.17.0-preview-007 has made it *less* likely to timeout and crash the module, but it still takes over 20 seconds.   An example of a timeout is below (4 mins passed before it crashed).   Includes a .ContinueWith to capture the stack trace.

~~~~
06/15/2018 14:02:22 | INIT: Opening ModuleClient
06/15/2018 14:06:23 | INIT: ModuleClient Initialized, CW: {"Id":1,"Exception":{"ClassName":"System.AggregateException","Message":"One or more errors occurred.","Data":null,"InnerException":{"ClassName":"System.TimeoutException","Message":"Operation timeout expired.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233083,"Source":"Microsoft.Azure.Devices.Client","WatsonBuckets":null},"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":null,"WatsonBuckets":null,"InnerExceptions":[{"ClassName":"System.TimeoutException","Message":"Operation timeout expired.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233083,"Source":"Microsoft.Azure.Devices.Client","WatsonBuckets":null}]},"Status":7,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":false,"CreationOptions":0,"AsyncState":null,"IsFaulted":true}
06/15/2018 14:06:23 | INIT: DeviceClient StateChange Handler Enabled
~~~~

**Startup.cs**
~~~~
        public void ConfigureServices(IServiceCollection services)  {
            services.AddMvc();
            services.AddCors();
            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            if (env.IsDevelopment())    app.UseDeveloperExceptionPage();

            app.UseFileServer();
            app.UseStaticFiles(
                new StaticFileOptions    {
                    FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "resources")),    //physical
                    RequestPath = "/resources"                                                                              //pseudo
                }
            );
            app.UseCookiePolicy();
            app.UseCors(builder =>
                builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
            );
            app.UseSignalR(routes => {routes.MapHub<UserInterfaceHub>("/uihub");});
            app.UseMvc();
        }
~~~~
**relevant Program.cs**
~~~~
            moduleClient = ModuleClient.CreateFromConnectionString(connectionString, settings);
			await moduleClient.OpenAsync().ContinueWith(_result =>
                Console.WriteLine($"{DateTime.Now.ToString()} | INIT: ModuleClient Initialized, CW: {JsonConvert.SerializeObject(_result)}")
             );
            moduleClient.SetConnectionStatusChangesHandler(onConnectionChange);
~~~~

**Comment by CIPop** [comment]
@jason-e-gross , we are aware of the issue. 
Could you give this a try with yesterday's GA release (1.17.0) please? It could be related to #352 or #495 which we fixed only in GA bits.

**Comment by jason-e-gross** [comment]
@CIPop -- I've been able to reduce it down to:

1. It happens with MQTT on the old runtime, if .NET Core 2.1
2. It happens with MQTT on the new GA runtime, if .NET Core 2.0 and 2.1

If I switch to AMQP transport settings, there's zero delay in .OpenAsync.

**Comment by CIPop** [comment]
Thanks @jason-e-gross for the new info! I've moved all our testing to `netcoreapp2.1` and didn't see any timing issues yet - this is strictly related to the network configuration in edge / Docker. I'm continuing the investigation.

**Comment by myagley** [comment]
We believe this issue has been fixed in DotNetty here: https://github.com/Azure/DotNetty/pull/413

We need to cut a new release of DotNetty and update the SDK with this new version.

**Comment by myagley** [comment]
Version 1.18.0 of the C# SDK has been released to nuget.org. Please give it a try.

**Comment by isimanovich** [comment]
Any update on when new version of DotNetty will be available?

**Comment by isimanovich** [comment]
@varunpuranik I was referring to DotNetty package. However, I get following error message after exactly 1 hr and 5 minutes of DeviceClient being used to send messages to IoTHub:

`at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

**Comment by isimanovich** [comment]
`using (var security = new SecurityProviderTpmHsm(_clientConfig.RegistrationID))
            {
                var auth = new DeviceAuthenticationWithTpm(_clientConfig.DeviceID, security);
                _iotDeviceClient = DeviceClient.Create(_clientConfig.IotHubHostName, auth, Microsoft.Azure.Devices.Client.TransportType.Amqp);
                _iotDeviceClient.OpenAsync().ConfigureAwait(false).GetAwaiter().GetResult();
            } `

**Comment by varunpuranik** [comment]
@isimanovich - Dotnetty version 0.5.0 which includes the fix has also been released.

As for the exception, is it a timeout (you included the callstack but not the exception)?

**Comment by isimanovich** [comment]
@varunpuranik sorry, i totally missed exception line, I edited it above. As to versions, I have DotNetty 0.5.0 and 1.18.0 of the C# SDK

**Comment by isimanovich** [comment]
i think, i found root-cause of my issue

**Comment by prmathur-microsoft** [comment]
@isimanovich - Could you update us with your findings ? Are you unblocked?

**Comment by CIPop** [comment]
We are very interested in your findings - they may help other users of the SDK as well so if you have some time, please add them to this thread.

Closing for now. @isimanovich please follow https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs to collect logs when you're getting this exception with the latest release.

**Comment by az-iot-builder-01** [comment]
@jason-e-gross, @myagley, @isimanovich, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
