### ISSUE TITLE
GetModulesOnDeviceAsync and SELECT * from devices.modules Returns Ghosted Modules

### ISSUE THREAD

**Issue by jason-e-gross** [Azure/azure-iot-sdk-csharp#525]
Tracking two service side issues where the following APIs may return stale modules:
- [ ] `registryManager.GetModulesOnDeviceAsync` A subscription-specific __ticket__ has been opened to further investigate.
- [ ] `.CreateQuery("("SELECT * FROM devices.modules WHERE deviceId='XXXX'")`; - The IoT service team is aware of this issue.

Original description:
---

When Using `registryManager.GetModulesOnDeviceAsync` or `.CreateQuery("("SELECT * FROM devices.modules WHERE deviceId='XXXX'")`;

They return modules that are no longer on the device.    If we add a module, use it for a bit, then remove it - through the Azure Portal -- the module twin that was removed is still returned with this - even weeks and months later.

It's not on the device, it's not in the device's $edgeAgent, it's not in the docker images/containers of the device.   For whatever reason, these modules that are removed from the device via the portal, not showing in the list of modules anymore - still show up with these commands.

Why would I want to see a module that I added two months ago, removed 1.5 months ago - show up in a query to get me the modules for a device?   Of what use is this?    Any module that's not in the Azure Portal's profile for that device shouldn't come back with this command - especially one that -- for all of our intents and purposes (module isn't in the portal, isn't on the device physically, isn't in edgeAgent module, isn't ANYWHERE as far as we can see anymore) -- somehow is still stored by Microsoft and returned to us in the query -- and there's no way to determine it's a ghosted module by looking at the twin.

**Comment by CIPop** [comment]
Thanks for reporting @jason-e-gross - this sounds like a bug.
I'll forward this to the service team.

**Comment by CIPop** [comment]
The service team reported that the Query bug is known.

@jason-e-gross The `GetModulesOnDeviceAsync` should return correct results though. Since we can't investigate without knowledge of your subscription, please open a support ticket from the Azure portal. (See details on how to do that [here](https://github.com/azure/azure-iot-sdk-csharp#need-support)).

**Comment by jason-e-gross** [comment]
@CIPop   Thanks for the update.    I've also created the ticket in Azure portal as you suggested.   Wasn't a great sub-category under IOT Edge for this , so just put it as "Connectivity Errors"   - hopefully it'll find its way to the right hands.

**Comment by CIPop** [comment]
Thanks @jason-e-gross! Keeping this active since it tracks two separate service-side issues.

**Comment by CIPop** [comment]
@jason-e-gross we got a reply from the service team:

`RegistryManager`'s `GetModulesOnDevice` gives the accurate information about Modules on device. The modules you see on portal are derived from `$edgeAgent` desired and reported properties. The Delete Module on portal only removes the modules from `$edgeAgent` desired properties (actual edgeAgent module when running will delete those module from the IotHub registry). We are working on making the portal experience and SDK experience in-line. For now you can delete the unwanted modules by calling `RemoveModule` from SDK.

Closing here as this is tracked by the service team.
