### ISSUE TITLE
Change Module sample to have wildcard NuGet reference

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#527]
We need to update the Modules sample to have a wildcard NuGet reference after releasing:

```XML
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.17.0-preview-007" />
```

should become

```XML
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*" />
```

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
