### ISSUE TITLE
Message.DeliveryCount property description in reference documentation seems incorrect

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-iot-sdk-csharp#531]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@ali-nazem commented on [Thu Jun 07 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/668)

"Time when the message was received by the server" seems to be an irrelevant description for a property called "DeliveryCount".
It looks like this description was copy pasted from the description of "EnqueuedTimeUtc" property, hence still unclear what DeliveryCount property provides.

Best regards, 
Ali

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e589d5-b37d-c203-794e-edb04529240a
* Version Independent ID: a9d44046-5cbb-5ace-835d-26c797dd9709
* Content: [Message.DeliveryCount Property (Microsoft.Azure.Devices.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.message.deliverycount?view=azure-dotnet#Microsoft_Azure_Devices_Client_Message_DeliveryCount)
* Content Source: [xml/Microsoft.Azure.Devices.Client/Message.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/Message.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CIPop** [comment]
Thanks @ali-nazem for reporting and @CamSoper for forwarding!

**Comment by jenoola** [comment]
@CamSoper @ali-nazem Right now Message.DeliveryCount has the following description: "Number of times the message has been previously delivered". 

Please reopen the issue if you have more questions.

**Comment by az-iot-builder-01** [comment]
@CamSoper, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
