### ISSUE TITLE
the first ITransportSettings[] are replicated to all Amqp client connections 

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-csharp#544]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64,

- **Application's .NET Target Framework :** netcoreapp2.1,
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client - 1.17.0

## Description of the issue:
When multiple Amqp client connections are created and opened in the same app, the `ITransportSettings[]` of the first opened connection are used to all subsequent connections.

**How to repro:** Create two `ModuleClient` instances with different settings, e.g. different `RemoteCertificateValidationCallback`.

The settings of the the `ModuleClient` that connects first will be used to the second `ModuleClient`.

**Comment by CIPop** [comment]
@paloukari this is by design: the code iterates through the array until a connection is made. After that, for AMQP, we would try to reuse the same connection for all other DeviceClient and ModuleClient communications.
