### ISSUE TITLE
IoT Edge Module - Missing Connection String for Module

### ISSUE THREAD

**Issue by MPapst** [Azure/azure-iot-sdk-csharp#546]
- **OS, version, SKU and CPU architecture used:** Ubuntu 16.04 x64, 
- **Application's .NET Target Framework :** netcoreapp2.11
- **Device:** B1ms Azure VM/Local VM
- **SDK version used:** GA, 1.17.0

## Description of the issue:
In the preview versions the Connection String for the ModuleClient was injected into the docker container. The Environment Variable `EdgeHubConnectionString` is missing in the version. Additional there is no candidate in the Env-vars with could suits those needs. Even when combining the evn-vars, the SAS Token is missing.

**Comment by CIPop** [comment]
@MPapst I don't think this is an SDK issue - our libs should not alter the local environment during run-time. Please open an issue in https://github.com/azure/iotedge repo (or a Support ticket from your Azure subscription).

@myagley @damonbarry FYI

Closing as external.
