### ISSUE TITLE
Robust upload of large files

### ISSUE THREAD

**Issue by johannesegger** [Azure/azure-iot-sdk-csharp#55]
Azure supports uploading large files in chunks to support continuing broken uploads. Do you plan to support this in the SDK as well?

I could also imagine having the user implement this and just providing a hook to doing something with a `CloudBlockBlob`:

```
public Task UploadBlobAsync(string blobName, Func<CloudBlockBlob, Task> upload);
```

**Comment by tameraw** [comment]
@eggapauli 
1. > Azure supports uploading large files in chunks to support continuing broken uploads. Do you plan to support this in the SDK as well?

Currently our IoT Hub Device SDK uses the Azure Storage SDK internally to upload files to the Azure Storage. So uploading in chunks should be inherently supported. Let us know if you encounter issues with that.

2. > I could also imagine having the user implement this and just providing a hook to doing something with a CloudBlockBlob: public Task UploadBlobAsync(string blobName, Func<CloudBlockBlob, Task> upload);

Thanks for the suggestion. But unfortunately it wouldn't be something we can add at the moment.

**Comment by eggapauli** [comment]
@tameraw thanks for your response.

As far as I can tell the SDK internally just uses [`CloudBlockBlob.UploadFromStreamAsync`](https://github.com/Azure/azure-iot-sdk-csharp/blob/2366f032697127571220a3ebd236c59ae590a7bb/device/Microsoft.Azure.Devices.Client/Transport/HttpTransportHandler.cs#L231), but resuming a cancelled upload task requires something like [this](http://blog.geuer-pollmann.de/blog/2014/07/21/uploading-blobs-to-azure-the-robust-way/). So it doesn't seem you get this for free when using the Storage SDK and `CloudBlockBlob.UploadFromStreamAsync`.

**Comment by tameraw** [comment]
@eggapauli - You are correct. Resuming a cancelled upload is not currently supported by the IoT Hub SDK.

**Comment by olivierbloch** [comment]
Now tracked on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109194-robust-file-upload-with-resume-for-the-c-device),. Please vote the feature up on there.
Thanks
