### ISSUE TITLE
RegistryManager.UpdateTwins2Async method doesn't work when trying to update a module twin

### ISSUE THREAD

**Issue by galmicrosoft** [Azure/azure-iot-sdk-csharp#554]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 
- **Application's .NET Target Framework :** net462 
- **Device:** Laptop 
- **SDK version used:** Microsoft.Azure.Devices.1.16.0 

## Description of the issue:
`RegistryManager.UpdateTwins2Async` method doesn't work when trying to update a module twin, instead it updates the device twin itself.
I checked with Fiddler, and the request body indeed lacks the moduleId property. I added it manually and sent the request again and the module twin updated as expected.

## Code sample exhibiting the issue:
```
var twin = new Twin();
twin.ModuleId = "mymod";
twin.DeviceId = "device1";
twin.Tags = new TwinCollection();
twin.Tags["mytag"] = "tag";
var rm = RegistryManager.CreateFromConnectionString("<connstring>");
rm.UpdateTwins2Async(new List<Twin> { twin }, true).Wait();
```

**Comment by CIPop** [comment]
Thanks for reporting @galmicrosoft ! We'll need to take a look to see why this isn't working.

**Comment by az-iot-builder-01** [comment]
@galmicrosoft, @CIPop, @luyaok, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by saikovvuri** [comment]
Hello, 
Wanted to point out that the fix was made to updatetwin2sync method and not updatetwinsync method which still doesn't work for me
