### ISSUE TITLE
Two different versions of Microsoft.Win32.Primitives referenced by SDK on DotNetCore

### ISSUE THREAD

**Issue by ryanzjohnson-ms** [Azure/azure-iot-sdk-csharp#560]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop
- **Application's .NET Target Framework :** <NETVERSION>  netcoreapp2.0
- **Device:** <DEVICETYPE>  Laptop
- **SDK version used:** <VERSION> 1.16.0

## Description of the issue:

When running the following command I get the following error:

`dotnet publish --self-contained`

![image](https://user-images.githubusercontent.com/35502607/43100316-d7f0a554-8e79-11e8-9fe1-15dcce697abd.png)

Link to repo [here](https://github.com/ryanzjohnson-ms/DotNetCoreError)

**Comment by ryanzjohnson-ms** [comment]
My current work around is to directly add a reference to the Primitives package in my csproj but was wondering if this didn't have to be a work around.

**Comment by CIPop** [comment]
Closing - no answer to above question.
