### ISSUE TITLE
Deployment manifest json file cant be read - wrong json attribute name for modules used

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-csharp#566]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Laptop
- **SDK version used:** 2018-6-29 

## Description of the issue:
Reading IoT Edge deployment manifest files (as described [here)](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#configure-modules) doesn't work, because ConfigurationContentclass uses wrong Json attribute name for the modules configuration. It should be 'moduleContent', but 'modulesContent' is used.

## Code sample exhibiting the issue:
```
namespace Microsoft.Azure.Devices
{
    using System.Collections.Generic;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Configurations for Module Management Agent, Edge Hub and Modules on the device.
    /// </summary>
    public class ConfigurationContent
    {
        /// <summary>
        /// Gets or sets Module Configurations
        /// </summary>
        [JsonProperty(PropertyName = "modulesContent")]
        public IDictionary<string, IDictionary<string, object>> ModulesContent { get; set; }

        /// <summary>
        /// Gets or sets Module Configurations
        /// </summary>
        [JsonProperty(PropertyName = "deviceContent")]
        public IDictionary<string, object> DeviceContent { get; set; }
    }
}
```

**Comment by CIPop** [comment]
@JMayrbaeurl thank you for following-up and driving https://github.com/MicrosoftDocs/azure-docs/issues/12440 to completion! Closing this as a duplicate.

I have verified this works using the ADM sample: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/service/AutomaticDeviceManagementSample/AutomaticDeviceManagementSample.cs#L128

```
Configuration Content [type = assignment]
ModuleContent:
                properties.desired.modulesContent_key = modulesContent_value-config001
DeviceContent:
        properties.desired.deviceContent_key = deviceContent_value-config001
Configuration TargetCondition: properties.reported.chillerProperties.model='4000x'
```
