### ISSUE TITLE
Comments in DPS X.509 device sample are misleading

### ISSUE THREAD

**Issue by nberdy** [Azure/azure-iot-sdk-csharp#568]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:
The comment in the DPS x.509 device sample explicitly mentions individual enrollments, which has caused folks to think that this does NOT work for enrollment groups. But it does work for enrollment groups. Comment needs to be updated.

## Code sample exhibiting the issue:
Lines 17-24 [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/device/samples/ProvisioningDeviceClientX509/Program.cs)

**Comment by CIPop** [comment]
Thanks @nberdy !

Should be fixed here instead: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/provisioning/Samples/device/X509Sample/Program.cs#L24
We will remove samples from this repo.

@jenoola PTAL.

**Comment by yzhong94** [comment]
@prmathur-microsoft i think this is only pending removing samples in this folder.

**Comment by jenoola** [comment]
Comments updated in PR https://github.com/Azure-Samples/azure-iot-samples-csharp/pull/25

**Comment by az-iot-builder-01** [comment]
@jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
