### ISSUE TITLE
Connecting Modules Client to IoTHub or Edge through HTTP throws Unauthorized Exception

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#573]
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION>  netcoreapp2.1
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION>  Microsoft.Azure.Devices.Client v1.17.1

## Description of the issue:

Setting transport type as Http1, create a module client.
Use the client to send messages to IoT Hub.
It fails throwing Unauthorized exception.

## Code sample exhibiting the issue:

```
s_moduleConnectionString = …
private static TransportType s_transportType = TransportType.Http1;
ModuleClient moduleClient = ModuleClient.CreateFromConnectionString(s_moduleConnectionString, s_transportType);
eventMessage = ...
await _moduleClient.SendEventAsync(eventMessage).ConfigureAwait(false);
```

## Console log of the issue:

```
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: 
'{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized",
"ExceptionMessage":"Tracking ID:58ab8ddc71ab42b0b9aa7225ecdcdcdb-G:3-TimeStamp:08/06/2018 22:33:10"}'
```

**Comment by CIPop** [comment]
@BertKleewein reported that the same happens when connecting to Edge for method invoke.

This seems to be caused by incorrect server certificate validation:

```
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
---> (Inner Exception #0) Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
  at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
```

**Comment by ancaantochi** [comment]
IotHub doesn't support module authentication over HTTP, except for InvokeMethod. So it is expected behavior that SendEventAsync is not working.

I seems it is not related to the issue that @BertKleewein reported.

**Comment by abhipsaMisra** [comment]
Closing as this is expected behavior.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @ancaantochi, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
