### ISSUE TITLE
[moduleClient]Cannot connect to edgeHub in native process

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-csharp#574]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10, Docker 18.06.1-ce-win72 linux container mode
- **SDK version used:** <VERSION> 
1.17.1

# Description of the issue:

I am trying to run an edge module in local machine (without docker). The steps are as follows
1. Start edgeHub container with all credential, network and volume. (Port is exposed correctly)
2. Open the csharp module in VSCode, and inject the connection, certificate value as environment variable
3. Run the csharp module, cannot connect to edgeHub

Tried to investigate, it seems the issue is caused by It seems when there are multiple ips matched . But the first connect try throws error. It just returns and there is no channel. Comment added at https://github.com/Azure/azure-iot-sdk-csharp/pull/551/files#diff-1490bd8ef1099d0eb857b65d89056e49R959

related to the fix of issue #549

**Comment by CIPop** [comment]
@adashen please add more info and a repro.

**Comment by adashen** [comment]
We can use iotedgehubdev to test this scenario on edge simulator
1. Install iotedgehubdev with "pip install --upgrade iotedgehubdev"
2. Setup with "iotedgehubdev setup -c <edge-device-connection-string>"
3. Start the simulator with "iotedgehubdev start -i input1"
4. Get the module credential with "iotedgehudev modulecred"
It will output the module connectionstring and CA path

EdgeHubConnectionString=<connectionstring>
EdgeModuleCACertificateFile=<CA path>

5. Create a csharp edge module project with "dotnet new aziotedgemodule -n <your_module_name>"
6. Change Amqp protocol to Mqtt in Program.cs.
7. Run and Debug the module project with the env variables got in step 4

Result: Timeout, since the connection cannot parse to the correct IP.
But amqp could work correctly.

**Comment by CIPop** [comment]
Thanks @adashen ! We'll need to give this a try.

**Comment by adashen** [comment]
@CIPop the issue is still not fixed. And I found the reason is https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L874 only catches AggregateException . However the exception throw is "DotNetty.Transport.Channels.ConnectException
". So it fails to catch it.

**Comment by SLdragon** [comment]
Seems SDK side fixed this issue:
https://github.com/Azure/azure-iot-sdk-csharp/commit/20558374a0f4869ea6ac2498ccf093511102f1dc

**Comment by abhipsaMisra** [comment]
That is correct @SLdragon , this issue should be fixed as for v1.21.4. The transport handler should now also handle Connect exceptions thrown on `CreateChannelFactory`.

**Comment by az-iot-builder-01** [comment]
@CIPop, @adashen, @SLdragon, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
