### ISSUE TITLE
Make SharedAccessSignatureBuilder public

### ISSUE THREAD

**Issue by johannesegger** [Azure/azure-iot-sdk-csharp#58]
It's already public in [`Microsoft.Azure.Devices`](https://github.com/Azure/azure-iot-sdk-csharp/blob/a5108f60f343dee867a2243e5a59c4483f0c5a8b/service/Microsoft.Azure.Devices/Common/Security/SharedAccessSignatureBuilder.cs), but we don't really want to reference this library from a client, because it mostly contains service stuff.

**Comment by tameraw** [comment]
@eggapauli - Thanks for filing this issue.
Currently it is not in our backlog to make this change. Is there a particular scenario that leads you to need access to this class on the Device side?

**Comment by eggapauli** [comment]
@tameraw we would use it to implement a more robust file upload (see #55). But it could be used in all scenarios where you want to interact with the IoT Hub without using the SDK directly.

**Comment by olivierbloch** [comment]
Now tracked on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109212-make-sharedaccesssignaturebuilder-public-in-csharp). Please vote the feature up if interested.
Thanks
