### ISSUE TITLE
IoTHub DeviceClient ConnectionString Unit Tests are disabled

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#583]
This is tracking tests disabled within iothub\device\tests\ConnectionString\DeviceClientConnectionStringTests.cs

**Comment by drwill-ms** [comment]
Updated the tests.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
