### ISSUE TITLE
Enable the AmqpTransportHandler_RejectAmqpSettingsChange test

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#584]
Tracking re-enabling the `AmqpTransportHandler_RejectAmqpSettingsChange` unit-test.

**Comment by vinagesh** [comment]
Re-enabled the test and it passes correctly now.

**Comment by az-iot-builder-01** [comment]
@CIPop, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
