### ISSUE TITLE
FaultInjection tests - ThrottledConnectionRecovery fails with internal server error

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#588]
Test method Microsoft.Azure.Devices.E2ETests.MessageE2ETests.Message_ThrottledConnectionRecovery_AmqpWs threw exception: 
Microsoft.Azure.Devices.Client.Exceptions.IotHubException: 
Tracking Id:6d0212128b16475b93a67f9ce2bae9a2-G:1-TimeStamp:08/17/2018 15:37:23

**Comment by abhipsaMisra** [comment]
Closing this issue since we're no longer seeing this failure on our CI system:
![image](https://user-images.githubusercontent.com/22563986/74484381-48eb3f80-4e6d-11ea-8b95-7f75ce750922.png)

**Comment by az-iot-builder-01** [comment]
@CIPop, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
