### ISSUE TITLE
Provisioning tests should perform provisioning and IoT Hub communications over the same protocol

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#591]
A service-level issue prevents device registration and usage over MQTT immediately after provisioning.
Currently the tests always use MQTT after registration. I am temporarily switching this to HTTP.

This issue is tracking a test enhancement to use the same protocol for both registration and IoT Hub.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
