### ISSUE TITLE
Able to exceed max batch size with DeviceClient.SendEventBatchAsync()

### ISSUE THREAD

**Issue by jesseik** [Azure/azure-iot-sdk-csharp#596]
Hi,
I am using Microsoft.Azure.Devices.Client v. 1.6.2. In document https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-limits.md it is stated that maximum size of device-to-cloud batch is 256KB. However using SendEventBatchAsync() I am able to send batches a lot bigger. The limit of 256KB seems to apply to single message but I was able to send a batch of 50 messages, each being 255KB in size. Is there an error in documentation I referred or have I misunderstood something? Is this a bug? Do all my messages actually get sent to IoT Hub?

**Comment by CIPop** [comment]
/cc @simonporter @tameraw @jspaith

@jesseik which protocol are you using?

* MQTT seems to simply send each message separately - no batching so it should only be limited by single message size.
* AMQP uses an `AmqpBatchedMessageFormat` which should be limited by the batch size..
* HTTP will attempt to POST all messages in a single JSon which should also be limited by the batch size.

**Comment by jesseik** [comment]
@CIPop thank you for your answer. I am using MQTT protocol so this behavior would make sense. Is `SendEventBatchAsync()` with MQTT implemented like this because of some limitation in the protocol?
Anyway this answered my question, thanks! Should this be mentioned in a document though?

**Comment by yzhong94** [comment]
@rezasherafat can you help update the documentation to reflect this behavior?  Thanks

**Comment by rezasherafat** [comment]
@yzhong94 here's the [PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/52125).

**Comment by yzhong94** [comment]
Closing this issue as the doc has been merged.

**Comment by az-iot-builder-01** [comment]
@CIPop, @jesseik, @rezasherafat, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
