### ISSUE TITLE
Reduce size of bulk import file when deleting devices

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdk-csharp#600]
## Description of the issue:

When using [ExportImportDevice](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/service/src/ExportImportDevice.cs) to delete a set of devices, the resulting blob file could be considerably smaller (over 40% difference), removing some mandatory fields. The `status` field is mandatory and `authentication` doesn't have `NullValueHandling = NullValueHandling.Ignore`:

```csharp
[JsonProperty(PropertyName = "status", Required = Required.Always)]
public DeviceStatus Status { get; set; }

[JsonProperty(PropertyName = "authentication")]
public AuthenticationMechanism Authentication { get; set; }
```

If possible, please make these fields optional, so that they don't appear in the export file.

I'm using this feature to manage millions of devices, so the space and bandwidth saved would be considerable. For instance, instead of:

```
{"id":"1.elevator-02.1","importMode":"delete","status":"enabled","authentication":null}
{"id":"1.truck-02.1","importMode":"delete","status":"enabled","authentication":null}
{"id":"1.chiller-01.1","importMode":"delete","status":"enabled","authentication":null}
```

the file content could be:

```
{"id":"1.elevator-02.1","importMode":"delete"}
{"id":"1.truck-02.1","importMode":"delete"}
{"id":"1.chiller-01.1","importMode":"delete"}
```

and with 1M devices with similar IDs, the file size could be ~49MB instead of ~90MB.

**Comment by CIPop** [comment]
Thanks for reporting @dluc !

**Comment by RubiaL** [comment]
Thanks for the feedback. This is not currently in our backlog and we are unlikely to implement it. Please vote on this User [voice](https://feedback.azure.com/forums/321918-azure-iot) item and it can also be used for tracking our plans

**Comment by az-iot-builder-01** [comment]
@dluc, @CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
