### ISSUE TITLE
It seems that SetRetryPolicy method does not work

### ISSUE THREAD

**Issue by xuliujian** [Azure/azure-iot-sdk-csharp#601]
I tested the retry policy with Microsoft.Azure.Devices.Client v1.18.0. I set the policy as NoRetry with method **SetRetryPolicy** .

```
       static void Main(string[] args)
        {
            Console.WriteLine("Simulated device\n");

            deviceClient = DeviceClient.CreateFromConnectionString(iotHubDeviceConnctionString, TransportType.Mqtt);

            //deviceClient.RetryPolicy = RetryPolicyType.No_Retry;
            deviceClient.SetRetryPolicy(new NoRetry());
            //Set custom retry policy for the device
            //CustomRetryPolicy retryPolicy = new CustomRetryPolicy();
            //deviceClient.SetRetryPolicy(retryPolicy);
            //ExponentialBackoff exponentialBackoff = new ExponentialBackoff(5, new TimeSpan(), new TimeSpan(), new TimeSpan());
            //deviceClient.SetRetryPolicy(exponentialBackoff);
            deviceClient.SetConnectionStatusChangesHandler( new ConnectionStatusChangesHandler(ConnectionStatusChanged));

            SendDeviceToCloudMessagesAsync().ConfigureAwait(false);
            Console.ReadLine();
        }

        private static void ConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
        {
            Console.WriteLine("ConnectionStatus:{0}, ConnectionStatusChangeReason:{1}", status, reason);
            logger.Debug("ConnectionStatus:{0}, ConnectionStatusChangeReason:{1}", status, reason);
        }

        private static async Task SendDeviceToCloudMessagesAsync()
        {
            double minTemperature = 20;
            double minHumidity = 60;
            int messageId = 1;
            Random rand = new Random();

            while (true)
            {
                double currentTemperature = minTemperature + rand.NextDouble() * 15;
                double currentHumidity = minHumidity + rand.NextDouble() * 20;

                var telemetryDataPoint = new
                {
                    messageId = messageId++,
                    deviceId = DeviceId,
                    temperature = currentTemperature,
                    humidity = currentHumidity

                };

                var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
                var message = new Message(Encoding.ASCII.GetBytes(messageString));

                message.Properties.Add("temperatureAlert", (currentTemperature > 30) ? "true" : "false");

                try
                {

                    Console.WriteLine("{0} > Sending message: {1} to {2}", DateTime.Now, messageString, DeviceId);
                    logger.Debug("{0} > Sending message: {1} to {2}", DateTime.Now, messageString, DeviceId);

                    await deviceClient.SendEventAsync(message);
                }
                catch(Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

                await Task.Delay(1000 * 60);
            }
        }
```

But actually, form the log, i found that the status of device client would change per about 65 minutes, and the device would retry to connect to the iot hub service and send the messages. Logs as following:

> 2018-08-29 02:09:31.7734 DEBUG 8/29/2018 2:09:31 AM > Sending message: {"messageId":1,"deviceId":"raspberry","temperature":22.382650274030237,"humidity":63.958085628206881} to raspberry
> 2018-08-29 02:09:33.9367 DEBUG ConnectionStatus:Connected, ConnectionStatusChangeReason:Connection_Ok
> 2018-08-29 02:10:34.4456 DEBUG 8/29/2018 2:10:34 AM > Sending message: {"messageId":2,"deviceId":"raspberry","temperature":26.658259817239951,"humidity":66.158275579176035} to raspberry
> 2018-08-29 02:11:34.5797 DEBUG 8/29/2018 2:11:34 AM > Sending message: {"messageId":3,"deviceId":"raspberry","temperature":34.7946078678568,"humidity":74.697504152868646} to raspberry
> 2018-08-29 02:12:34.7150 DEBUG 8/29/2018 2:12:34 AM > Sending message: {"messageId":4,"deviceId":"raspberry","temperature":27.243310386428288,"humidity":68.779409410794926} to raspberry
> 2018-08-29 02:13:34.8937 DEBUG 8/29/2018 2:13:34 AM > Sending message: {"messageId":5,"deviceId":"raspberry","temperature":29.489685373608808,"humidity":72.400441408343823} to raspberry
> 2018-08-29 02:14:35.0333 DEBUG 8/29/2018 2:14:35 AM > Sending message: {"messageId":6,"deviceId":"raspberry","temperature":30.745892085016656,"humidity":70.199751039128643} to raspberry
> .......
> 2018-08-29 03:12:48.1205 DEBUG 8/29/2018 3:12:48 AM > Sending message: {"messageId":64,"deviceId":"raspberry","temperature":31.506790854738462,"humidity":64.5086019600316} to raspberry
> 2018-08-29 03:13:48.2656 DEBUG 8/29/2018 3:13:48 AM > Sending message: {"messageId":65,"deviceId":"raspberry","temperature":28.437643984070814,"humidity":74.254481640762876} to raspberry
> 2018-08-29 03:14:34.3253 DEBUG ConnectionStatus:Disconnected_Retrying, ConnectionStatusChangeReason:No_Network
> 2018-08-29 03:14:34.3403 DEBUG ConnectionStatus:Disconnected, ConnectionStatusChangeReason:Retry_Expired
> 2018-08-29 03:14:48.4071 DEBUG 8/29/2018 3:14:48 AM > Sending message: {"messageId":66,"deviceId":"raspberry","temperature":21.708218190683155,"humidity":73.365656898061587} to raspberry
> 2018-08-29 03:14:49.0851 DEBUG ConnectionStatus:Connected, ConnectionStatusChangeReason:Connection_Ok
> 2018-08-29 03:15:49.5797 DEBUG 8/29/2018 3:15:49 AM > Sending message: {"messageId":67,"deviceId":"raspberry","temperature":24.57800083774049,"humidity":75.845332534911734} to raspberry
> ......
> 2018-08-29 04:20:48.9624 DEBUG 8/29/2018 4:20:48 AM > Sending message: {"messageId":125,"deviceId":"raspberry","temperature":25.802767386568135,"humidity":73.477836751135925} to raspberry
> 2018-08-29 04:20:48.9654 DEBUG ConnectionStatus:Disconnected_Retrying, ConnectionStatusChangeReason:No_Network
> 2018-08-29 04:20:49.6190 DEBUG ConnectionStatus:Connected, ConnectionStatusChangeReason:Connection_Ok
> 2018-08-29 04:21:48.9676 DEBUG 8/29/2018 4:21:48 AM > Sending message: {"messageId":126,"deviceId":"raspberry","temperature":25.448562938463205,"humidity":77.906921048605312} to raspberry
> 2018-08-29 04:22:49.2026 DEBUG 8/29/2018 4:22:49 AM > Sending message: {"messageId":127,"deviceId":"raspberry","temperature":27.591550439871639,"humidity":60.99895662674632} to raspberry

**Comment by CIPop** [comment]
Thanks for reporting @xuliujian !

**Comment by prmathur-microsoft** [comment]
Can you verify this with our latest SDK ? We have had several retry related issues fixed on latest releases.

**Comment by CIPop** [comment]
Should be fixed from 1.19+. Please reopen if this is still not working.

**Comment by az-iot-builder-01** [comment]
@xuliujian, @CIPop, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by rajatjain4949** [comment]
It doesn't seem to be working. Below is what i did -

DeviceClient iotClient = null;
iotClient = IoTHubHelper.CreateIoTHubInstance(deviceId);
IRetryPolicy retryPolicy = new ExponentialBackoff(Convert.ToInt32(Settings.ErrorRetryCount), TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(100));
iotClient.SetRetryPolicy(retryPolicy);
await iotClient.OpenAsync();

While debugging getting -
Microsoft.Azure.Devices.Client.RetryPolicyType.No_Retry

    <PackageReference Include="Microsoft.Azure.Devices" Version="1.27.0-preview-003" />
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.29.0-preview-002" />
