### ISSUE TITLE
Message.DeliveryCount has wrong description

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#607]
The description for Message.DeliveryCount property says "Time when the message was received by the server". Looks like this was incorrectly copied from a another property's description.

**Comment by CIPop** [comment]
Thanks for reporting @wickste !

**Comment by az-iot-builder-01** [comment]
@wickste, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
