### ISSUE TITLE
UpdateReportedPropertiesAsync doesn't update the Device Twin timestamps

### ISSUE THREAD

**Issue by tymtam2** [Azure/azure-iot-sdk-csharp#609]
I have a device that periodically updates reported properties using `DeviceClient`'s `UpdateReportedPropertiesAsync` but the timestamps stay empty:

```
  "statusUpdateTime": "0001-01-01T00:00:00",
  "connectionState": "Connected",
  "lastActivityTime": "0001-01-01T00:00:00",
```

I'm using 
Microsoft.Azure.Devices.Client, Version=1.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\Developer\.nuget\packages\microsoft.azure.devices.client\1.18.0\lib\netstandard2.0\Microsoft.Azure.Devices.Client.dll

**Comment by CIPop** [comment]
Thanks for reporting @tymtam2 ! 
I think this might be caused by the `Twin` data objects being reused by both Service and Device clients. Some of the fields may not be filled in on the device side. We need to take a look and decide if this is a documentation or functional issue.

**Comment by jenoola** [comment]
Unable to reproduce.

@tymtam2 do you still see the issue?

**Comment by jenoola** [comment]
@tymtam2 Please reopen the issue if you still see it

**Comment by az-iot-builder-01** [comment]
@tymtam2, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
