### ISSUE TITLE
MissingMethodException when calling ServiceClient.SendAsync(deviceId, message) from UWP

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#612]
- **OS, version, SKU and CPU architecture used:** Windows10 Enterprise (1803) x64  
- **Application's .NET Target Framework :** UWP version 17134, Microsoft.NETCore.UniversalWindowsPlatform 6.1.7 
- **Device:** Laptop  
- **SDK version used:** 1.17.0  

## Description of the issue:

MissingMethodException when calling ServiceClient.SendAsync(deviceId, message) from a UWP app.
The same code works in a .NET Core console app, as well as in a .NET Framework 4.6 console app.

## Code sample exhibiting the issue:

`await ServiceClient.SendAsync(deviceId, message);`

## Console log of the issue:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Microsoft.Azure.Amqp.Transport.TlsTransportSettings.set_Certificate(System.Security.Cryptography.X509Certificates.X509Certificate2)'.
  Source=Microsoft.Azure.Devices
  StackTrace:
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Azure_IoT_Service_SDK_Explorer.Views.SendPage.<btnSend_Click>d__8.MoveNext() in C:\Users\wicks\source\repos\Azure IoT Service SDK Explorer\Azure IoT Service SDK Explorer\Views\SendPage.xaml.cs:line 77

**Comment by CIPop** [comment]
@xinchen10 this is similar to #610

**Comment by jenoola** [comment]
Was able to repro the issue. We are blocked here, cannot do anything about it until https://github.com/Azure/azure-amqp/issues/127 and/or https://github.com/Azure/azure-amqp/issues/120 fixed

**Comment by jenoola** [comment]
@wickste  please try to add Microsoft.Azure.Amqp 2.4.1 to your project, it should fix the issue.

**Comment by jenoola** [comment]
Fix checked in the new release 1.20.0

**Comment by az-iot-builder-01** [comment]
@wickste, @CIPop, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by wickste** [comment]
Thanks!
