### ISSUE TITLE
AMQP should use unique correlation IDs

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#618]
Thanks @nayato for reporting this offline:

We're using deviceId as correlation token: https://github.com/Azure/azure-iot-sdk-csharp/blob/2c9bce0bc060b1869ec7a5bcfe9e63e736ed450f/iothub/device/src/Transport/AmqpTransportHandler.cs#L814 
This means that when connection is re-established, client opens links with the same correlation id that we had been using before. There are some negative side effects to this:
1. On server side we can't really distinguish attempts to create req-rep channels and can link req side of one attempt to rep side of another (if there happens to be more than one attempt at a time)
2. When we see an attempt to create two links of the same type (sender or receiver) with the same correlation id, we will error out with 409 Conflict error

The recommendation is to switch to something more unique here. GUID would surely do, so would simple counter I think.

- [ ] IoT Hub DeviceClient AMQP
- [ ] IoT Hub ServiceClient AMQP
- [ ] ProvisioningTransportHandlerAmqp

**Comment by timtay-microsoft** [comment]
@nayato @CIPop I'm looking into fixing this issue. Does the service want correlation id's attached to the service client links as well? Right now it looks like the SDK isn't sending a correlation id in the amqp links for service client operations

**Comment by nayato** [comment]
correlation id is for correlating request and response links where we establish this comm pattern: direct methods, twin.

**Comment by timtay-microsoft** [comment]
So it is only necessary when we are opening twin, method, and direct links? Then the device client is the only place where we need to ensure correlation id's are being sent. I'll get a PR out for this soon.

**Comment by timtay-microsoft** [comment]
During the amqp redesign, this issue was fixed (as seen [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/1aa4e08f84cbba13b2073685229ab659c7a99ba6/iothub/device/src/Transport/Amqp/AmqpUnit.cs#L303)) so that links send a guid as a part of the correlation id, so they will be unique. Since the issue has been fixed, I'm closing this issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, @nayato, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
