### ISSUE TITLE
Application properties are not implemented

### ISSUE THREAD

**Issue by nanowireUK** [Azure/azure-iot-sdk-csharp#62]
Apologies if this is incorrect but having looked through the code and documentation it doesn't seem that the C# library implements the setting of ApplicationProperties for Messages (despite being implemented within MessageConverter). Is this missing or am I simply missing how it was implemented?

**Comment by jasmineymlo** [comment]
Try the below:
                Message eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                eventMessage.Properties.Add("p1", Guid.NewGuid().ToString());
                eventMessage.Properties["p2"] = Guid.NewGuid().ToString();
Thanks.

**Comment by nanowireUK** [comment]
Thanks, that does appear to work but seems a very confusing implementation since Properties is declared as a type ReadOnlyDictionary4.5 (which admittedly has Add method if ReadOnly is not set).

Anyway, very much appreciate the response and will close the question.
