### ISSUE TITLE
How IoT Hub knows if the device certificate is revoked

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#622]
- **OS, version, SKU and CPU architecture used:** <Windows 10> 
- **Application's .NET Target Framework :** <4.7.1> 
- **Device:** <Linux based> 
- **SDK version used:** <latest> 

## Description of the issue:
Hi,

I am using X509 based authentication for devices. Root certificate is installed and verified in IoT Hub, device certificates are the certificates in the trusted chain of the root certificate.

If one of the device certificate is revoked how IoT Hub knows that the certificate is revoked and the device shouldn't be allowed to connect?

Inputs on this will be highly appreciated

Thanks
Amogh

**Comment by amogh79** [comment]
Any updates on this please??

**Comment by timtay-microsoft** [comment]
This is more a question for the service rather than the SDK. I suggest filing an issue [here](https://azure.microsoft.com/en-us/support/create-ticket/) instead

**Comment by az-iot-builder-01** [comment]
@amogh79, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
