### ISSUE TITLE
TimeOutException with Policy Connection String and one device NotFound or Disabled

### ISSUE THREAD

**Issue by royto** [Azure/azure-iot-sdk-csharp#627]
- Deployed on Azure Service Fabric on Windows Server 2016. (Reproduce with a console App) 
- Using .NET Core 2.0
- Using Microsoft.Azure.Devices.Client, Version=1.70.0

## Description of the issue:
We are building a protocol gateway for devices. We are using policy connection as we do not have device keys.

From  Microsoft.Azure.Devices.Client (1.17.0), we encountering an issue when a device, among all devices, is not Found or disbale on IoTHub.

`Microsoft.Azure.Devices.Client.Exceptions.IotHubException: 'receiver10' is closed
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeviceClientTest.Program.<>c__DisplayClass1_0.<<ReceiveLoop>b__0>d.MoveNext() in C:\Users\SESA302242\source\repos\DeviceClientTest\DeviceClientTest\Program.cs:line 81}`

If All devices exists and are enable, it works wells.

## Code sample exhibiting the issue:
```csharp
using System;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Devices.Client;

namespace DeviceClientTest
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
            I tried with with the following version 
            Microsoft.Azure.Devices.Client (1.18.0) KO
            Microsoft.Azure.Devices.Client (1.17.1) KO
            Microsoft.Azure.Devices.Client (1.17.0) KO
            Microsoft.Azure.Devices.Client (1.7.2) OK
            Microsoft.Azure.Devices.Client (1.7.0) OK
            Microsoft.Azure.Devices.Client (1.6.0) KO Pb dependencies :(s
            Microsoft.Azure.Devices.Client (1.5.2) OK
             */

            var iotHubName = "XXX.azure-devices.net";
            var policyName = "MyPolicy";
            var policyKey = "myAwesomeKey";
            var iotHubConnectionString = $"HostName={iotHubName};SharedAccessKeyName={policyName};SharedAccessKey={policyKey}";

            

            var transportSettings = new ITransportSettings[]
                        {
                            new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
                            {
                                AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
                                {
                                    Pooling = true,
                                    MaxPoolSize = 5
                                }
                            }
                        };

            var deviceClient = DeviceClient.CreateFromConnectionString(iotHubConnectionString, "existingDevice", transportSettings);

            var deviceClient2 = DeviceClient.CreateFromConnectionString(iotHubConnectionString, "existingDevice2", transportSettings);
            var deviceClient3 = DeviceClient.CreateFromConnectionString(iotHubConnectionString, "deviceNonExisting", transportSettings);

            deviceClient.OpenAsync();
            deviceClient2.OpenAsync();

            //try catch to avoid exception but it fails ...
            try
            {
                deviceClient3.OpenAsync();
                ReceiveLoop(deviceClient3);
                SendLoop(deviceClient3);
            }
            catch (Exception e)
            {
                deviceClient3.Dispose();
                Console.Error.WriteLine(e.Message);
            }

            ReceiveLoop(deviceClient);
            SendLoop(deviceClient);
            ReceiveLoop(deviceClient2);
            SendLoop(deviceClient2);

            Console.ReadLine();
        }

        private static void ReceiveLoop(DeviceClient deviceClient)
        {
            Task.Run(async () =>
            {
                while (true)
                {
                    try
                    {
                        var message = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(5));

                        if (message == null)
                        {
                            Console.WriteLine("Null Message");
                        }
                        else
                        {
                            Console.ForegroundColor = ConsoleColor.Red;
                            Console.WriteLine(Encoding.UTF8.GetString(message.GetBytes()));
                            Console.ResetColor();
                        }
                    }
                    catch (Exception e)
                    {
                        Console.Error.WriteLine(e.Message);
                    }
                }
            });
        }

        private static async void SendLoop(DeviceClient deviceClient)
        {
            while (true)
            {
                try
                {
                    var message = new Message(Encoding.UTF8.GetBytes("my message"));
                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    await deviceClient.SendEventAsync(message);
                    sw.Stop();

                    Console.WriteLine($"Message send in {sw.ElapsedMilliseconds} ms");
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine(e.Message);
                }
            }
        }
    }
}

```

**Comment by prmathur-microsoft** [comment]
#620 
We currently don't support using Iothub Connection String for device client. You will need to extract device ID and use that in forming a connection. Can you explain your scenario, as to why do you need IotHubConnection staring. Also have you looked at our EdgeHub ? It will probably help you in your scenario. 
@veyalla to explain about EdgeHub.

**Comment by royto** [comment]
As said before, we are building a protocol gateway for devices.

Devices send messages as Http Post request,we convert to iothub messages and push them into the iothub. We only have deviceId in request and not device keys. That's why we using iothub connection string.

As well, we listen to C2D message to push message to device via a WebHook.

EdgeHub is not appropriate in our case as devices are communicating using HTTP ...

**Comment by timtay-microsoft** [comment]
I believe you are running into the same issue as #620, with the fix being in [this PR](https://github.com/Azure/azure-iot-sdk-csharp/pull/652).

Do you have the full logs of your run of this sample code? When I run it locally, I see "Exception thrown: 'System.ObjectDisposedException' in Microsoft.Azure.Devices.Client.dll" but no lines about "Microsoft.Azure.Devices.Client.Exceptions.IotHubException: 'receiver10' is closed"

**Comment by timtay-microsoft** [comment]
And just to be clear, this SDK does support using IotHub connection string for device client, even if we don't recommend it. The issue you are hitting is likely unrelated to your connection string.

**Comment by royto** [comment]
Looks great !

Thanks

**Comment by timtay-microsoft** [comment]
This SDK went through a major redesign of the AMQP stack, and this issue has been fixed as a result. The latest release of this SDK no longer has this issue, so I'm closing this issue.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @royto, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
