### ISSUE TITLE
Exception when trying to send Device Message

### ISSUE THREAD

**Issue by VladVladovich** [Azure/azure-iot-sdk-csharp#630]
Steps:

1. Create new .Net 4.7.1 project
2. Install nuget from nuget.org Microsoft.Azure.Devices.Client 1.18.0 
3. Update all the nugets in project
4. Copy code from Iot Hub sample (update Iot Hub DeviceConnectionString) [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/iothub/device/samples/DeviceClientMqttSample)
5. Run

Actual result:
_DotNetty.Transport.Channels.ClosedChannelException: I/O error occurred.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()_

Note, that the same code executed directly from the sample (.Net Core + Microsoft.Azure.Devices.Client 1.0.0 ) works fine.

**Comment by CIPop** [comment]
@VladVladovich step 3 might have updated the Devices.Client dependencies to something that we don't support.
Also, please use the samples from here instead: https://github.com/Azure-Samples/azure-iot-samples-csharp

**Comment by VladVladovich** [comment]
I tried to remove all the automatically generated binding redirects from config and currently it works

**Comment by az-iot-builder-01** [comment]
@VladVladovich, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
