### ISSUE TITLE
RegistryManager.AddDeviceWithTwinAsync does not create Edge device

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#631]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Enterprise 1803
- **Application's .NET Target Framework :** <NETVERSION> .NET 4.6.1
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION> Microsoft.Azure.Devices/1.17.0
## Description of the issue:
RegistryManager.AddDeviceWithTwinAsync does not create Edge device, even though I have set capability IotEdge=true. If I use RegistryManager.AddDeviceAsync the Edge device is created as expected.

## Code sample exhibiting the issue:
await _registryManager.AddDeviceWithTwinAsync(new Device(equipment.DeviceId) { Capabilities = new DeviceCapabilities() { IotEdge = true } }, twin);

**Comment by jenoola** [comment]
Was able to repro with the latest SDK. Investigating.

**Comment by jenoola** [comment]
@wickste why do you need to use AddDeviceWithTwinAsync in this particular scenario? Can you work around with AddDeviceAsync?

We are working on figuring out how to support AddDeviceWithTwinAsync for edge devices in the meantime.

**Comment by wickste** [comment]
@jenoola I logged this issue on behalf of a customer who posted this on stackoverflow. Not sure about their scenario, and it looks like their question got deleted since, so I can't follow up further.

**Comment by jenoola** [comment]
IoT Hub service is planning on rolling this feature soon. In the meantime, please, use AddDeviceAsync for adding edge devices.

**Comment by az-iot-builder-01** [comment]
@jenoola, @wickste, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
