### ISSUE TITLE
NETMF version of API lacks Direct Method support

### ISSUE THREAD

**Issue by hbraasch** [Azure/azure-iot-sdk-csharp#633]
There is no [SetMethodHandler or equivalent] API method in the device NETMF part of the API. It is therefore not possible to receive any direct method calls when using a device running NETMF.

Shown below are the DeviceClient methods exposed in the regular .Net API (see SetMethodHandler highlighted) :
![iotsdknet](https://user-images.githubusercontent.com/7484186/46111593-ef0fb880-c22a-11e8-84b0-ce5e93ab21e8.jpg)

Shown below are the NETMF DeviceClient methods. It is somewhat different (which is fine), but nothing there to support direct methods:
 
![iotsdknetmf](https://user-images.githubusercontent.com/7484186/46111594-efa84f00-c22a-11e8-8936-e1b035d92830.jpg)
Would you please be so kind to add the missing direct method support? It is an extremely powerful and important part of IOT and if not supported on small devices, make them almost useless for real applications.

**Comment by prmathur-microsoft** [comment]
We have added this feature to our backlog. And we will address it. In the mean time, we welcome PR from you and I'll be happy to review it.

**Comment by CIPop** [comment]
@hbraasch given the current work-load and NETMF state it's unlikely we'll pick this up (for example we have no testing for NetMF at the moment). I've added the `help wanted` label. We'll accept PRs for additional enhancements if they come with proper e2e tests.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently not a priority in our backlog and do not plan on adding this feature to our SDK. But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure portal](https://azure.microsoft.com/en-au/features/azure-portal/)

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @CIPop, @hbraasch, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
