### ISSUE TITLE
C# DPS device API "SecurityProviderTpmHsm" does not conform to "Registration ID" requirement. SecurityProviderTpmHsm should not get Registration ID from caller, caller does not have the ability to generate Registration ID for TPM. 

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-sdk-csharp#636]
The csharp implementation of DPS client utilizing TPM is quite different from C implementation.
While in azure-iot-sdk-c DPS sample, both "Registration ID" and "Endorsement Key" are read from TPM module. But the csharp SDK interface require caller to provide "Registration ID", which is against the definition of "Registration ID" in Azure document (https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device#registration-id):

> **Registration ID**
> The registration ID is used to uniquely identify a device in the Device Provisioning Service. The device ID must be unique in the provisioning service ID scope. Each device must have a registration ID. The registration ID is alphanumeric, lowercase, and may contain hyphens.
> In the case of TPM, the registration ID is provided by the TPM itself.
> 
> 

It clearly state that TPM Registration ID is provided by the TPM itself.

In this case, how caller is possible to assign "Registration ID" to "SecurityProviderTpmHsm(string registrationId")"?

Of course, we could use C program to query TPM registration ID and endorsement key, and then get back to C# program to register the device to DPS, but does this really make sense?

**Please enable "SecurityProviderTpmHsm" to be able to query "Registration ID" from TPM device.**

**Comment by prmathur-microsoft** [comment]
Usually in other SDK's we provide an optional API to provide registration ID (if user does not have it) eg in Java we have https://github.com/Azure/azure-iot-sdk-java/blob/master/provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java#L58 
Perhaps that is what is needed here too. We will add this to our backlog. In the meantime could you follow the workaround you mentioned i.e query for registration ID. 

Also we are happy to accept a PR for this and I'll be happy to review it in the meantime.

**Comment by AlmaJensen** [comment]
I'm trying to work on something similar and got directed to the nuget package Microsoft.Devices.TPM source found here.  https://github.com/ms-iot/security/tree/master/Limpet

**Comment by CIPop** [comment]
@AlmaJensen @yphuangms feel free to propose a PR for our SDK. 

> https://github.com/ms-iot/security/tree/master/Limpet

Our dependency is https://github.com/Microsoft/TSS.MSR

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@yphuangms, @prmathur-microsoft, @AlmaJensen, @CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
