### ISSUE TITLE
small bug with the Device Explorer tool UpdateTwinAsync is not awaited

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-csharp#64]
On class DeviceTwinAndMethod
Line 82:
registryManager.UpdateTwinAsync(dp.DeviceId, dp, dp.ETag);

**UpdateTwinAsync** not awaited. There is a delay for one second, but if there is a problem it will not be catched.

change to:
await registryManager.UpdateTwinAsync(dp.DeviceId, dp, dp.ETag);

**Comment by tameraw** [comment]
@ukluk - Please submit a PR and we'll review it. Thanks.

**Comment by ukluk** [comment]
@tameraw I am not authorized: Request failed with status code: 403.

Let me know how to contribute 😊


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sergaz-msft** [comment]
Hello @ukluk ,

I see that you managed to do the change :).
I am closing this issue.

All Best
