### ISSUE TITLE
CreateChannelFactory not correctly handling exceptions

### ISSUE THREAD

**Issue by danigian** [Azure/azure-iot-sdk-csharp#648]
The CreateChannelFactory method in MqttTransportHandler.cs (line 907) contains a "foreach (IPAddress address in addresses)" with the aim to try to find the proper IP address to use.

If the address is a IPv6 one, in scenarios like IoT Edge Transparent Gateway, the ConnectAsync will fail and the exception will not be correctly catched, letting the foreach fail

Apart from asking to please catch the correct exception: do we really need to try to connect to IPv6 addresses right now? Neither IoT Hub or IoT Edge support IPv6 by default as of today
 
Could it be possible to check whether the AddressFamily of the addresses is InterNetwork or InterNetworkV6 and then only try to connect to IPv4 addresses?

**Comment by CIPop** [comment]
@prmathur-microsoft @timtay-microsoft a PR already exists for this item.

>  do we really need to try to connect to IPv6 addresses right now? 

@danigian @myagley I believe the answer is yes: we need to support IPv6.  If a customer chooses to IPv6 / IPv4 translation (to maintain only an IPv6 network) then the SDK will fail.

1. The _current_ lack of support is a missing feature. We would need to support IPv6 in the future: https://technet.microsoft.com/en-us/library/hh994905.aspx
2. It sounds like edge has a bug: name lookup should not return network addresses where the service isn't present. If IPv6 is not supported by the service you may need to remove the IPv6 address from your Edge server. @danigian please open a bug in the edge repo for this to be addressed in either code or docs.

**Comment by danigian** [comment]
@CIPop thank you for the feedback about IPv6. Honestly I don't think we should ask our customers to remove IPv6 addresses from all the network interfaces they have.
As written in a comment to my previous PR, maybe, you are not able to generate the exception because the MqttTransportHandlerTests is mocking the channel factory and not using one created with the CreateChannelFactory method.

To be able to reproduce the error you have to:
1) Have your machine with IPv6 enabled on network interfaces
2) Configure IoT Edge as Transparent Gateway (it should work even with only loading edgeHub, it does not matter if the certificates checks are failing right now)
3) Start this [sample console application](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/MessageSample) using your device connection string with the appended GatewayHostName properly set to your machine hostname

You will notice the behavior of this issue (CreateChannelFactory looping over the foreach infinitely because of the correct exception not catched)

Please, let me know if you need more details

**Comment by timtay-microsoft** [comment]
We have opted to not do any soft of IP address filtering since customer's may be doing IPv6 / IPv4 translation (as per Cris above), but I have created a PR to correctly handle the ConnectException case that you are encountering

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of device client version 1.21.4, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
