### ISSUE TITLE
Documentation and samples for AddConfigurationAsync

### ISSUE THREAD

**Issue by elvinm** [Azure/azure-iot-sdk-csharp#649]
- **OS, version, SKU and CPU architecture used:** Windows 10 x64 
- **Application's .NET Target Framework :** .Net core 2.0 
- **Device:** Laptop 
- **SDK version used:** Microsoft.Azure.Devices/1.17.0 

## Description of the issue:

Not enough details are provided for calling AddConfigurationAsync in regards to expected exceptions to catch. Details should be provided about failures in cases such as using the same configuration id, or an invalid target condition.

## Code sample exhibiting the issue:

[Samples](https://github.com/Azure/azure-iot-sdk-csharp/blob/c93b167058708aead0d2849972c21dabf815b945/iothub/service/samples/ADMSample/ADMSample.cs#L55)

**Comment by prmathur-microsoft** [comment]
@yzhong94 - Can you please take a look at this ?

**Comment by CIPop** [comment]
@elvinm please open this in our samples repo : https://github.com/Azure-Samples/azure-iot-samples-csharp

**Comment by elvinm** [comment]
I've created https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/23 so I am closing this issue.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @elvinm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
