### ISSUE TITLE
Set property for custom metrics in AddConfigurationAsync

### ISSUE THREAD

**Issue by miteshpatekar** [Azure/azure-iot-sdk-csharp#658]
I am trying to add configuration through .net sdk but there is no support for setting the Configuration class metrics property. I am able to set others and add configuration. 
var config = new Configuration(configId)
            {
                Content = new ConfigurationContent()
                {
                    DeviceContent = new Dictionary<string, object>()
                {
                    { "properties.desired.firmware",patch }
                }
                },
                Priority = 20,
                TargetCondition = "tags.deviceType = \'chiller\'"                
            };
There is no current support to add metrics in above object. It only has a {get;} property.

public ConfigurationMetrics SystemMetrics { get; }
public ConfigurationMetrics Metrics { get; }

Can you add this feature. 
The only current way to do this is using Azure CLI and nodeJs. It will be great if you provide the set property as well.

Thank you,
Mitesh

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. We have added it to our backlog and will address it. In the mean time feel free to provide a PR and I will be happy to review it.

**Comment by CIPop** [comment]
@sudeepster @zolvarga PTAL. This appears to be a bug in the ADM API spec.

**Comment by jenoola** [comment]
SystemMetrics cannot be modified and it is by design.

Metrics can be changed, please, see an example [here](https://github.com/jenoola/azure-iot-samples-csharp/blob/master/iot-hub/Samples/service/AutomaticDeviceManagementSample/AutomaticDeviceManagementSample.cs#L80).

Please, reopen the issue if you have more questions

**Comment by az-iot-builder-01** [comment]
@miteshpatekar, @prmathur-microsoft, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
