### ISSUE TITLE
Trying to install Microsoft.Azure.Devices.Client to a UWP app 

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-sdk-csharp#66]
Hi, I am currently trying to install Microsoft.Azure.Devices.Client to a Blank App Universal Windows project called App2 (.NET framework 4.5.2) and I have the following error messages:

PM> Install-Package Microsoft.Azure.Devices.Client
Restoring packages for 'App2'.
Restoring packages for c:\users\mtheolog\documents\visual studio 2015\Projects\App2\App2\project.json...
Install-Package : System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for 
System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for 
System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for 
System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Package restore failed for 'App2'.
Install-Package : Package restore failed. Rolling back package changes for 'App2'.
At line:1 char:1
+ Install-Package Microsoft.Azure.Devices.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I would appreciate your feedback.
Regards,
Maria.

**Comment by arturl** [comment]
Hi there!
Please upgrade your Microsoft.NETCore.UniversalWindowsPlatform package to version 5.2.2, it should take care of this issue.

**Comment by cabbagecreek** [comment]
I have tested with a Windows Form app.. This works
`_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Mqtt);`

Then testing the same code in UWP I get System.Net.Security not found.
Changing to:
`_deviceClient = DeviceClient.Create(IotHubUri,new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey),Microsoft.Azure.Devices.Client.TransportType.Http1);`
Works!!!
