### ISSUE TITLE
Need method to determine real size of message

### ISSUE THREAD

**Issue by Mikkelcv** [Azure/azure-iot-sdk-csharp#669]
We have a case where our messages can be large due to the content we are sending. We have a fall back mechanism for those large messages but it is hard to determine when a message is too large. Right now we have chosen a threshold that is "low enough".

Is there a way to determine upfront if the message that I am going to send will exceed the maximum allowed limit? 
Or a method to tell how large it will be, then I can compare to the limits defined in: https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-limits.md

Since the calculation of the size includes all headers which the SDK adds and message is also further json serialized and added as content on HttpRequestMessage. Then it is hard to determine if the message will be too large for us.

Thanks
Mikkel

**Comment by prmathur-microsoft** [comment]
Thats a good idea for enhancement. Could you please provide this input at user voice located https://feedback.azure.com/forums/321918-azure-iot and we will take it from there.
Also in the mean time if you want to provide a PR we will be happy to review it.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle

**Comment by az-iot-builder-01** [comment]
@Mikkelcv, @prmathur-microsoft, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
