### ISSUE TITLE
IoTHub.EnqueuedTime not set in Message() to IoTHub

### ISSUE THREAD

**Issue by JohnKozell** [Azure/azure-iot-sdk-csharp#67]
I have a stream analytics job being sourced from an IoTHub. I noticed that IoTHub properties are largely being set (ex: ConnectionDeviceId) but the EnqueuedTime is NOT. In some messages this property is missing altogether. Here is an example of the relevant properties:
```
    "EventProcessedUtcTime": "2017-03-04T13:03:47.4294959Z",
    "PartitionId": 1,
    "EventEnqueuedUtcTime": "2017-03-04T13:02:42.6930000Z",
    "IoTHub": {
        "MessageId": null,
        "CorrelationId": null,
        "ConnectionDeviceId": "Experiment1",
        "ConnectionDeviceGenerationId": "636146743722094236",
        "EnqueuedTime": "0001-01-01T00:00:00.0000000",
        "StreamId": null
```
Should I expect EnqueuedTime be set to the current time the DeviceClient sends the message to the IoTHub?

-John

**Comment by rajeevmv** [comment]
EnqueuedTimeUtc is a property that is stamped by IoTHub only when it receives a command destined for a Device. A device will received the EnqueuedTimeUtc property when it receives a command.

This property is not supported on the telemetry path when a Device/DeviceClient sends a telemetry message to IoTHub.

**Comment by tameraw** [comment]
@rajeevmv  - provided document update clarifying that EnqueuedTimeUtc is not available on the telemetry path (Device to Cloud).
https://github.com/Microsoft/azure-docs/pull/1037
