### ISSUE TITLE
High CPU at high scale when reconnecting AMQP/pooling

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-iot-sdk-csharp#675]
**OS, version, SKU and CPU architecture used**: <Windows 10> Cloud service
**Application's .NET Target Framework** : <.net 4.5.2>
**Device**: Protocol Gateway (AMQP)
**SDK version used**: 1.7.1
### **Description of the issue**:
Hi,

I use the device SDK  in a protocol gateway.
Each gateway manages around 1000 devices.
When the connection with the IoTHub is ok all is fine. My CPU usage is under 20%. But when there is an issue with an IoTHub connection (some internal error in IoTHub or network issue) the CPU usage rises to 100%.
In debug mode, I receive a lot of 'System.OperationCanceledException' in mscorlib.dll. I guess something keep running but I don't know what.

I did some test with some settings around retry policy and timeouts but I alway have CPU issue more or less quickly.

Is there some best practice to set device client in a gateway ?

Thanks

### **Code sample exhibiting the issue:**
`var amqpConnectionPoolSettings = new AmqpConnectionPoolSettings
                {
                    MaxPoolSize = 100,
                    Pooling = true
                };

                if (connectionIdleTimeout.HasValue)
                {
                    amqpConnectionPoolSettings.ConnectionIdleTimeout = 300;
                }

                var transportSettings = new ITransportSettings[]
                {
                    new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
                    {
                        AmqpConnectionPoolSettings = amqpConnectionPoolSettings
                    },
                    new AmqpTransportSettings(TransportType.Amqp_WebSocket_Only)
                    {
                        AmqpConnectionPoolSettings = amqpConnectionPoolSettings
                    }
                };

deviceClient = DeviceClient.Create(
                    this.iotHubUri,
                    new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, primKeyb64),
                    transportSettings);
deviceClient.OperationTimeoutInMilliseconds = 15000;
deviceClient.SetRetryPolicy(new ExponentialBackoff(3, TimeSpan.FromMilliseconds(200), TimeSpan.FromSeconds(3), TimeSpan.FromMilliseconds(100)));
`

**Comment by CIPop** [comment]
Thanks @Sbou  for reporting! @zolvarga is actively working on a new internal AMQP pooling architecture.
The portion of the fix without pooling is currently in PR: https://github.com/Azure/azure-iot-sdk-csharp/pull/741

**Comment by JohnLTaylor** [comment]
[Over in the ApplicationInsights](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/857/files/138a6bb613642bd49fd31971af49f3f481d56589) there is a high memory/CPU usage bug that traces back to .net core.  They had to change the HttpClient from an instance variable to a static to prevent the leaking of Timers/HttpClients/etc.  We are seeing a similar leaking pattern in iot and also having problems with [Issue 699](https://github.com/Azure/azure-iot-sdk-csharp/issues/699) at the same time

**Comment by prmathur-microsoft** [comment]
We are actively working to resolve this issue. We should soon have a fix for this issue.

**Comment by CIPop** [comment]
We're still seeing this, potentially after AMQP redesign as closed/faulted connections are not evicted from the pools.
/cc @prmathur-microsoft  @tameraw @nayato  FYI - using this to track the pooling issue. Looks like it dates back to 1.7, before all redesign work.

**Comment by CIPop** [comment]
@JohnLTaylor thanks for reporting, we appreciate your patience!
We were able to repro this with the latest Protocol Gateway and 1.20.2. We're working on a fix.

**Comment by prmathur-microsoft** [comment]
[https://github.com/Azure/azure-iot-sdk-csharp/pull/1001](url) PR where these issues are being addressed.

**Comment by davilu** [comment]
@Sbou  @JohnLTaylor  thanks for the patient and we get a PR([1001](https://github.com/Azure/azure-iot-sdk-csharp/pull/1001)) out to fix PG CPU spike during re connection. We're under long haul testing in a stress platform. It will be released once the test are completed.

**Comment by prmathur-microsoft** [comment]
This issue is now fixed and should be a part of latest release [v1.21.1](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-9-11)

**Comment by az-iot-builder-01** [comment]
@Sbou, @CIPop, @JohnLTaylor, @prmathur-microsoft, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
