### ISSUE TITLE
ADM Sample project not added to samples solution

### ISSUE THREAD

**Issue by sushilraje** [Azure/azure-iot-sdk-csharp#678]
Please use your Azure subscription if you need to share any information from your Azure subscription such as connection strings, service names (IoTHub, Provisioning), etc.

## Need Support?
* Found a bug? Please help us fix it by thoroughly documenting it and filing an issue on GitHub (C, Java, .NET, Node.js, Python).

- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64
- **Application's .NET Target Framework :** 2.0 
- **SDK version used:** latest

## Description of the issue:
Please add ADMSample project to the samples solution.

**Comment by jenoola** [comment]
ADM sample is added as [AutomaticDeviceManagementSample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/service/AutomaticDeviceManagementSample) in Azure-Samples/azure-iot-samples-csharp repo

**Comment by az-iot-builder-01** [comment]
@sushilraje, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
