### ISSUE TITLE
DeviceClient.GetTwinAsync() should throw exception if not MQTT.

### ISSUE THREAD

**Issue by JohnKozell** [Azure/azure-iot-sdk-csharp#68]
My understanding is presently twin functionality is only available for devices if the MQTT protocol is used when the connection is created.
Enhancing GetTwinAsync() to throw an exception, instead of simply returning NULL, I believe would save developers time and serve to supplement sparse documentation on the subject.

**Comment by tameraw** [comment]
@JohnKozell - Thanks for providing this feedback. Makes sense to me. We'll create a backlog item for that; meanwhile if you're interested in contributing, please submit a pull request and we'll review it. Thanks.

**Comment by johannesegger** [comment]
Is it a current limitation that might change in the future? I mean do you intend to implement device twin stuff with AMQP?

**Comment by tameraw** [comment]
@johannesegger - Implementing Device Twin functionality over AMQP is currently in our backlog and we'll be providing this feature in the very near future.

**Comment by sergaz-msft** [comment]
Hi @JohnKozell , please see the changes for throwing that exception here: https://github.com/Azure/azure-iot-sdk-csharp/commit/8f52cf4dd03640f0599e7892ded1874ebc9b7f23 

Changes going to the master branch soon.
All Best
