### ISSUE TITLE
Device Explorer Twin : Monitoring Events

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-csharp#680]
- **OS, version, SKU and CPU architecture used:** <Windows 10 Desktop x64> 

## Description of the issue:

Hello, 
since a couple of weeks I am not able to monitor any D2C-Messages (events) on the Device-Explorer-Twin. Everything else works perfect (Messages To Device, Call Method on Device etc.). If I start to Monitoring, the Application hangs and after a couple of minutes i get following error-message: "An error occured during communication with 'DeviceGateway_.....'. Check the Connection Information, then retry."

**Comment by raycon94** [comment]
Problem solved: a port was blocked by the firewall...

**Comment by az-iot-builder-01** [comment]
@raycon94, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
