### ISSUE TITLE
Question: What is the GatewayHostName is used for and how do I obtain it?

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/azure-iot-sdk-csharp#681]
Hi,

I'm looking at your samples for how to create modules to communicate through a Gateway, especially:

https://github.com/Azure/azure-iot-sdk-csharp/tree/master/iothub/device

However, I'm wondering what the `GatewayHostName` is used for in the connection string, and how I do obtain it?:

```c#
HostName=<iothub_host_name>;GatewayHostName=<edge_host>;ModuleId=<module_id>;DeviceId=<device_id>;SharedAccessKey=<device_key>"
```

Thank you.

/Henrik

**Comment by HenrikBach1** [comment]
Read: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-edge/how-to-create-transparent-gateway-linux.md

**Comment by az-iot-builder-01** [comment]
@HenrikBach1, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
