### ISSUE TITLE
Question: How do I backtrack references, in source code, to automagically generated values from a resource file (resx)?

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/azure-iot-sdk-csharp#683]
Hi,

I'm trying to follow an error track from the file in the sample: `azure-iot-sdk-csharp/provisioning/service/src/Properties/ApiResources.Designer.cs`, which is automagically generated from the resource file: `azure-iot-sdk-csharp/provisioning/service/src/Properties/ApiResources.resx`.

However, my problem is, that I cannot find any references, in other source code, to the `internal static string <Get-Property>`!

How is the running (and linked) sample able to reference this <Get-Property> and thus gets the real value string?

For instance, if I try to follow the track for `ConnectionStringIsNotWellFormed`, no references shows up for it in the sample code, other than in those mentioned "resource files"!

I'm using Visual Studio Code.

Help is appreciated to shed light on, what I do miss or don't know to connect the dots?

Thank you very much.

/Henrik

**Comment by CIPop** [comment]
@HenrikBach1 we plan to remove all localization constructs in a future version.
Provisioning V1 service copied a lot of items from IoT Hub. In this case, VS is correct: there is no reference and that is dead code which should and will be removed.

/cc @abhipsaMisra who is working on v2 of this service.

**Comment by az-iot-builder-01** [comment]
@HenrikBach1, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by CIPop** [comment]
@HenrikBach1 work is tracked by https://github.com/Azure/azure-iot-sdk-csharp/issues/177
