### ISSUE TITLE
ProvisioningServiceClient_v2: Add unit tests for ProductInfo in common

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#684]
Need to add unit tests for the ProductInfo class in commons

**Comment by abhipsaMisra** [comment]
The updated autorest generator defines an API surface different from the one implemented here above; once we get back to this item the entire thing will have to be re-worked. Closing this for now.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
