### ISSUE TITLE
ProvisioningServiceClient_v2: Refactor the connection string parsing logic

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#686]
Refactor the provisioning service connection string parser - remove token generation logic from the connection string class

**Comment by CIPop** [comment]
@abhipsaMisra please create a new GitHub Project for these tracking issues.

**Comment by abhipsaMisra** [comment]
Closing this issue; the updated autorest generator expects the credentials to be supplied in a different format; so this will need to be reworked entirely in a separate project.

**Comment by az-iot-builder-01** [comment]
@CIPop, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
