### ISSUE TITLE
Timeout exceptions since version 1.17

### ISSUE THREAD

**Issue by FredyFLU** [Azure/azure-iot-sdk-csharp#693]
Starting with v1.17 I have very frequent Timeout exceptions (>20 % calls) calling either : 
DeviceClient.OpenAsync();
or
DeviceClient.SendEventAsync(message);

DeviceClient instance is created using DeviceClient.CreateFromConnectionString(connectionString, deviceId);
Connection string is only specifying HostName, SharedAccessKeyName and SharedAccessKey.
I have tried using DeviceClient.OperationTimeoutInMilliseconds set to 30 sec. and 60 sec. 
I have less than 10 IoT devices declared.
I have not discovered any way to reproduce the exception systematically.

Using V1.18.1 release, my unit tests using above methods most often fails.
I need to fallback to V1.7.2 to reach again a 100% success. I never had this kind of issue with that version or the previous ones.

Thanks for fixing.

**Comment by CIPop** [comment]
Thanks for reporting @FredyFLU. 
We're aware of these and are working on fixing architectural issues with both our timeout and retry systems. These are non-trivial and so may take a while.

**Comment by az-iot-builder-01** [comment]
@FredyFLU, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
