### ISSUE TITLE
Internal device client failures

### ISSUE THREAD

**Issue by hathind-ms** [Azure/azure-iot-sdk-csharp#700]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

We are running simulation tests with high number of devices (>20K) and  see high number of Internal Device Client failure exceptions while sending telemetry to IoT Hub. From the simulation client side, we are explicitly disposing device client before trying to reconnect. 

## Console log of the issue:

[ERROR][2018-11-02 20:32:05.283][WebService.befc4883-5960-4e19-90fd-520cc7630fba][DeviceClient.cs:261:SendRawMessageAsync] Message delivery failed, internal client failure, {"Protocol":"AMQP","ExceptionMessage":"Cannot access a disposed object.
Object name: 'FaultTolerantAmqpObject`1'.","Exception":"System.ObjectDisposedException","InnerException":null}

[ERROR][2018-11-02 20:32:05.287][WebService.befc4883-5960-4e19-90fd-520cc7630fba][SendTelemetry.cs:85:SendTelemetryMessageAsync] Client broke while sending telemetry, {"timeSpentMsecs":67,"deviceId":"14227e0c-fd72-41e6-9143-5750bf8cf858.truck-01.182620","e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.BrokenDeviceClientException","ExceptionMessage":"Message delivery failed, internal client failure","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<SendRawMessageAsync>d__24.MoveNext() in /home/azureiotpcs/vsts-agent/_work/46/s/Services/DeviceClient.cs:line 270

**Comment by timtay-microsoft** [comment]
This issue should be fixed by upgrading to the latest device client version. The AMQP layer has undergone some design changes so you shouldn't see this exception anymore.

**Comment by az-iot-builder-01** [comment]
@hathind-ms, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
