### ISSUE TITLE
DeviceClient - Connection recovery 

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#702]
- **OS, version, SKU and CPU architecture used: Windows 10 Desktop x64,** <VERSION> 
- **Application's .NET Target Framework : net461** <NETVERSION> 
- **Device: Laptop** <DEVICETYPE> 
- **SDK version used: 1.17.1** <VERSION> 

## Description of the issue:

When connection state changes to Disabled due to Client_Close reason is it responsibility of application 
to reconnect to IoTHub or DeviceClient should do it? It usually happens when device is changing WiFi access points (if switching takes longer than approximately 2 minutes).

## Console log of the issue:

11:00:01,991;Internal client connection status changed to: Disconnected_Retrying. Status change reason: No_Network.
11:00:03,252;Internal client connection status changed to: Disabled. Status change reason: Client_Close.

**Comment by prmathur-microsoft** [comment]
Client_Close should happen only when client is explicitly tried to close the client. Can you explain your behavior and flow with device client ?

**Comment by CIPop** [comment]
Thanks @Perun85 : we've received a lot of GitHub and customer reports of our retry logic not being reliable. We're currently fixing important design bugs around timeouts and retry.

> When connection state changes to Disabled due to Client_Close reason is it responsibility of application
to reconnect to IoTHub or DeviceClient should do it? 

The desired behavior is that within the configured `OperationTimeoutInMilliseconds` (default 4 minutes) the SDK will handle any network related failures, including the WiFi / media disconnected case. The fact that it doesn't is a bug within the same category as the ones we're currently working on.

Meanwhile, as a workaround, you can call `Dispose` on the existing client and try to reconnect.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @Perun85, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
