### ISSUE TITLE
Symmetric key attestation support

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-iot-sdk-csharp#703]
Support for symmetric key attestation was [launched in preview](https://azure.microsoft.com/en-us/blog/happy-anniversary-new-iot-hub-device-provisioning-service-features-out-today/) on 24-Sep - would be great to get support added to the .NET SDK.

**Comment by cocowalla** [comment]
My mistake, I see it's in a branch :man_shrugging:

**Comment by az-iot-builder-01** [comment]
@cocowalla, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
