### ISSUE TITLE
How to provision devices using symmetric key attestation?

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-iot-sdk-csharp#705]
Using Azure Device Provisioning Service, I've created an enrollment group configured for symmetric key attestation, and now I want to register some devices.

The problem is, there doesn't seem to be a `SecurityProvider` implementation for use with `ProvisioningDeviceClient.RegisterAsync()`.

```
using (var transport = new ProvisioningTransportHandlerAmqp())
{
	using (var security = new SecurityProvider???????())
	{
		var provisioningClient = ProvisioningDeviceClient.Create("global.azure-devices-provisioning.net", HubIdScope, ???????, transport);
		var result = await provisioningClient.RegisterAsync();
		// use the result
	}
}
```

I can't find _anything_ in the docs, or the code, for how to register devices using symmetric key attestation - would appreciate some guidance.

**Comment by prmathur-microsoft** [comment]
This feature in work in progress on our side. We will have it ready by End of January.

**Comment by az-iot-builder-01** [comment]
@cocowalla, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
