### ISSUE TITLE
Ensure all fault modes are implemented by all IoT Hub DeviceClient

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#707]
The following exceptions are not thrown by any Transport:
- `DeviceDisabledException`
- `IotHubNotFoundException`

**Comment by CIPop** [comment]
@yzhong94 @prmathur-microsoft  @tameraw FYI

**Comment by vinagesh** [comment]
These exceptions are not being used in the SDK and can be used if the service throws the corresponding errors back. As these are public and un-used, we are having a conversation to see if it can be removed from our code base instead. The service plans to fix the errors returned in v2 and we can use those in our track2 SDK.

**Comment by vinagesh** [comment]
We will be removing the un-referenced exceptions as we have got the approval for it.

**Comment by az-iot-builder-01** [comment]
@CIPop, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
