### ISSUE TITLE
[BUG] ServiceClient connection recovery

### ISSUE THREAD

**Issue by bragma** [Azure/azure-iot-sdk-csharp#708]
Hi,
I am trying to understand is ServiceClient can survive as a long lived object, i.e. can reconnect, etc. 
While testing, I've found that it fails to reconnect because of calling IOThreadTimerSlim "Cancel" twice. The first call sets the timer to null, the second one (on a connection retry) crashes due to using the null reference.

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp2.1
- **SDK version used:** Microsoft.Azure.Devices 1.17.1

## Description of the issue:
I run the code sample shown below in a console app. While looping, I disconnect the network cable or disable the driver. The service client instance never resumes from its error state even when network functionality is properly restored.

## Console log of the issue:

Sending C2D message to UB-423,C-1
Sending C2D message to UB-423,C-1
Sending C2D message to UB-423,C-1
Sending C2D message to UB-423,C-1
<----NETWORK DISABLED MANULLY, EX: REMOVE NET CABLE
The operation was canceled. <--- Notice first exception thrown
Sending C2D message to UB-423,C-1
Unable to connect to the remote server <--- Notice another exception thrown, trying to reconnect
Sending C2D message to UB-423,C-1
Object reference not set to an instance of an object. <--- This should not happen
<----NETWORK RESTORED
Sending C2D message to UB-423,C-1
Object reference not set to an instance of an object. <--- Never recovers from repeating this error

## Code sample exhibiting the issue:
```
			while(true)
			{
				var message = new Message(Encoding.ASCII.GetBytes(DateTime.Now.ToString()));
				Console.WriteLine($"Sending C2D message to {deviceId}");
				try
				{
					await _serviceClient.SendAsync(deviceId, message).ConfigureAwait(false);
				}
				catch(Exception e)
				{
					Console.WriteLine(e.Message);
				}
				
				await Task.Delay(5000);
			}
```

## What happens:

Here, the timer is removed with Cancel. This sets the internal timer value to null.
https://github.com/Azure/azure-iot-sdk-csharp/blob/690c0e4d541a33a6f595d83d0c90e2dc58c54802/iothub/service/src/IotHubConnection.cs#L176

Here the client crashes with an exception, since it cannot connect. The timer is deleted and never restored, by the previous call to Cancel.
https://github.com/Azure/azure-iot-sdk-csharp/blob/690c0e4d541a33a6f595d83d0c90e2dc58c54802/iothub/service/src/IotHubConnection.cs#L191

When the client code retries the send, another "Cancel()" is called on the timer, again here:
https://github.com/Azure/azure-iot-sdk-csharp/blob/690c0e4d541a33a6f595d83d0c90e2dc58c54802/iothub/service/src/IotHubConnection.cs#L176

## Possible fix

The problem is here:
https://github.com/Azure/azure-iot-sdk-csharp/blob/690c0e4d541a33a6f595d83d0c90e2dc58c54802/iothub/service/src/netstandard13/Common/IOThreadTimerSlim.cs#L38

If I try changing the line to:

`timer?.Dispose();`

Everything works well. The client reconnects.

**Comment by bikamani** [comment]
I am unable to repro this exception and also it is not recommend using disposed object. Service Client does not have retry logic. Closing this for now, if you still see this issue feel free to reopen.

**Comment by az-iot-builder-01** [comment]
@bragma, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
