### ISSUE TITLE
Subscribe to Azure IoT Hub Device Events

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-iot-sdk-csharp#711]
I want to read the "Microsoft.Devices.DeviceConnected" events (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid#event-types) from Azure IoT Hub. The only examples I found deals with Azure Event Grid but I'd rather like to use the IoT Hub's internal endpoint (Event Hub). Is this even possible? When I subscribe to the internal Event Hub using the EventProcessorHost interface all I get are D2C user telemetry messages.

**Comment by prmathur-microsoft** [comment]
At the moment this is not supported. Please feel free to voice your request in uservoice (https://feedback.azure.com/forums/321918-azure-iot) and we will attend to it.

**Comment by az-iot-builder-01** [comment]
@Bnjmn83, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
