### ISSUE TITLE
Incorrect device twin timeouts with AMQP (compared to MQTT)

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdk-csharp#712]
- **OS, version, SKU and CPU architecture used:** macOS Mojave 10.14.1
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** simulated ([Azure IoT Device Simulation](https://github.com/Azure/device-simulation-dotnet))
- **SDK version used:** Microsoft.Azure.Devices 1.17.1 and Microsoft.Azure.Devices.Client 1.18.1

## Description of the issue:
Our application used to run with a default timeout of 10 seconds (set at the application level), passed to the SDK at the time of creating a device client. We recently increased the default timeout to 20 seconds, and noticed a strange behavior, depending on the protocol used:
* when using MQTT if a timeout occurs, it's correctly happening after 20 seconds
* when using AMQP, timeout occurs after 10 seconds

This is how clients are created, and how twin reported properties are sent:
```
var client = Azure.Devices.Client.DeviceClient.CreateFromConnectionString(connectionString, TransportType.Amqp_Tcp_Only);
// or        Azure.Devices.Client.DeviceClient.CreateFromConnectionString(connectionString, TransportType.Mqtt_Tcp_Only);
client.OperationTimeoutInMilliseconds = 20000
await client.UpdateReportedPropertiesAsync(reportedProperties);
```

and the following is a sample log collected by our application. Note: this has been observed using the Free IoT Hub SKU, but there shouldn't be any reason for a different behavior.

MQTT, timeout after 20006 msecs:
 
> [ERROR][21:35:47.887][DeviceClient.cs:UpdatePropertiesAsync] Reported properties update timed out, {"timeSpentMsecs":20006,"deviceId":"8.truck-01.1","Protocol":"MQTT","e":{"ExceptionFullName":"System.TimeoutException","ExceptionMessage":"Operation timeout expired.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<UpdatePropertiesAsync>d__23.MoveNext() in simulation/Services/DeviceClient.cs:line 210","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}
 
AMQP, timeout after 10006 msecs:
 
> [ERROR][21:39:12.619][DeviceClient.cs:UpdatePropertiesAsync] Failed to update reported properties, {"timeSpentMsecs":10006,"deviceId":"8.truck-01.172","Protocol":"AMQP","e":{"ExceptionFullName":"Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException","ExceptionMessage":"The operation has timed out.","StackTrace":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<UpdatePropertiesAsync>d__23.MoveNext() in simulation/Services/DeviceClient.cs:line 210","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":{"ExceptionFullName":"System.TimeoutException","ExceptionMessage":"The operation has timed out.","StackTrace":"   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<RoundTripTwinMessage>d__65.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<SendTwinPatchAsync>d__67.MoveNext()","Source":"Microsoft.Azure.Devices.Client","Data":{},"InnerException":null}}}

**Comment by jenoola** [comment]
Can't repro on Windows with latest SDK. Will try on mac.
@dluc could you try the latest SDK?

**Comment by jenoola** [comment]
Correction: no repro on Win or macOS using latest SDK and regular device. Will try with simulation next

**Comment by dluc** [comment]
I'm not working on this project any longer - could you reproduce with the versions reported? If you can repro with those and compare the behavior with the latest version, then you could assume that the issue has been fixed.

**Comment by prmathur-microsoft** [comment]
Closing this as it has not been repro'ed. Feel free to reopen this issue if you are able to successfully repro.

**Comment by az-iot-builder-01** [comment]
@jenoola, @dluc, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
