### ISSUE TITLE
How do you consume Operations Monitoring messages (Connected,Disconnected) ?

### ISSUE THREAD

**Issue by Core-TT** [Azure/azure-iot-sdk-csharp#72]
There isnt any samples on how to consume the Operations Monitoring messages and the "documentation" [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-operations-monitoring) doesnt explain how to consume the messages (apart from using a tool, which is useless when i need to consume the messages for business processing).

The operations monitoring tab in the portal says "Event Hub-compatible name" and "Event Hub-compatible endpoint" but where are the credentials? Do we use the iothubowner connection string? Because when you use the iothubowner connection string with the EventProcessorHost you get an instant error saying "Illegal connection string parameter name 'HostName'" and if you remove the HostName part from the connection string it then fails when calling RegisterEventProcessor<T> with a message saying "Encountered error while fetching the list of EventHub PartitionIds".

So what are the correct values to use to get the EventProcessorHost consuming messages from the Operations Monitoring ?

**Comment by nberdy** [comment]
You can use the sample app in the [getting started tutorial](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-getstarted#receive-device-to-cloud-messages), only in step 5 you need to replace "messages/events" with "messages/operationsmonitoringevents" and you'll be able to read from the endpoint.

Best,
Nicole
