### ISSUE TITLE
Invoke direct methods from IoT Hub with a timeoute of 50 minutes not possible

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-iot-sdk-csharp#724]
- **Application's .NET Target Framework :** net 461
- **SDK version used:**  Microsoft.Azure.Devices" version="1.4.0" 

## Description of the issue:
If I try to call a direct method with an timeout of 3000 seconds I get an error. In the documentation is written that a timeout max is 3600 seconds. 

> (Direct methods are synchronous and either succeed or fail after the timeout period (default: 30 seconds, settable up to 3600 seconds). [Documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods) 

Also in the code you can see there is set the default to `const int DefaultKeepAliveInSeconds = 300;`
[Mqtt implementation](https://github.com/Azure/azure-iot-sdk-csharp/blob/679e75ca3cea9ea0dba2feecb6b79ad6ef229764/iothub/device/src/Transport/Mqtt/MqttTransportSettings.cs)

Error: 
> {
>   "Message": "{\"errorCode\":400004,\"trackingId\":\"ca2359224b794d2db52baeb75c648bdd-G:14-TimeStamp:12/04/2018 12:33:53\",\"message\":\"responseTimeoutInSeconds must be within [5; 300].\",\"timestampUtc\":\"2018-12-04T12:33:53.2091489Z\"}",
>   "ExceptionMessage": ""
> }

Why is the timeout period not supported by the SDK as described in the documentation?

## Code sample exhibiting the issue:
`ServiceClient _serviceClient;
// 3600 -> 1 hour send timeout
CloudToDeviceMethod directMethod = new CloudToDeviceMethod(defaultCommandName, 3000, connectionTimeout);
await _serviceClient.InvokeDeviceMethodAsync(deviceId, directMethod, cancellationToken).ConfigureAwait(false);`

**Comment by CIPop** [comment]
@simonporter @srivanie Sounds a documentation bug but I'd like to first confirm.

**Comment by ChangeTheCode** [comment]
@CIPop is there any update ?

**Comment by jenoola** [comment]
I've verified that it is documentation issue and maximum timeout is 300 seconds. Documentation will be updated.

**Comment by az-iot-builder-01** [comment]
@CIPop, @ChangeTheCode, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
