### ISSUE TITLE
DeviceClient.GetTwinAsync().Version is null (along with everything except "Properties")

### ISSUE THREAD

**Issue by brentstineman** [Azure/azure-iot-sdk-csharp#728]
OS: Windows 10 Desktop x64
Application's .NET Target Framework : .NET Core 2.1
Device: laptop
SDK version used: 1.18.1

## Description of the issue:
I'm using DeviceClient.GetTwinAsyn to retrieve the device twin (via MQTT transport). The returned object ONLY has Properties property populated. (see attached)
![mostlyemptytwin](https://user-images.githubusercontent.com/1760519/49609528-6a939180-f961-11e8-829c-902c97bc591d.PNG)

I'm trying to implement a sample of a device updating its properties at startup based on the twin's values and had planned to leverage the version (available in the json metadata sections). As best I can determine, it appears that while the DeviceClient has all the properties available its its Twin, they're not actually being brought down to the device. 

I'd really like access to the metadata. But I'd settle for having an SDK that doesn't seem quite so misleading. 

## Code sample exhibiting the issue:
deviceClient = DeviceClient.CreateFromConnectionString(connectionString, TransportType.Mqtt);
 var twin = await deviceClient.GetTwinAsync();

**Comment by brentstineman** [comment]
@sebader That's my belief as well. And while I can understand the desire to keep the GetTwinAsync response payload to a minimum, I think is also a bit confusing that the properties are there and simply return null. I would have expected something more like a [NotImplemented ](https://docs.microsoft.com/en-us/dotnet/api/system.notimplementedexception?redirectedfrom=MSDN&view=netframework-4.7.2) exception. Along with that, having to make a separate call to get the metadata specifically would be acceptable.  

Are these types of enhancements something that a feature the SDK owners would be interested in?

**Comment by CIPop** [comment]
Thanks @brentstineman for reporting!

I believe this is by design: ServiceClient and DeviceClient share the Twin APIs. I'll need to check with the service team if having only the properties was intentional.

**Comment by jenoola** [comment]
I've verified with the service team that this is by design, for the reason @CIPop suggested.

**Comment by az-iot-builder-01** [comment]
@sebader, @brentstineman, @CIPop, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by texyh** [comment]
@jenoola please i have the same issue, how do i get the device twin then, besides using the RegistryManager.

**Comment by abhipsaMisra** [comment]
@texyh This is by service design that the device client GetTwinAsync() call returns only the twin property information and nothing else. The device identity information requires iothub-scope credentials for retrieval, and can be retrieved using the RegistryManager. 

On a separate note, closed issues are not monitored; I would recommend opening a new issue if you have further questions.
