### ISSUE TITLE
Amqp transport handler creates tasks within tasks on SafeAddClosed()

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-csharp#729]
- **OS, version, SKU and CPU architecture used:** this issue is platform-independent
- **Application's .NET Target Framework :** This issue is framework-version-independent
- **Device:** This issue is device-independent. 
- **SDK version used:** from release  [2018-10-09](https://github.com/Azure/azure-iot-sdk-csharp/tree/2018-10-9)

## Description of the issue:

This issue is from a comment from @CIPop on another incoming feature:
"Why is this a new task? (I see this patter throughout the code so it may have been a copy paste from somewhere else.)"
Related to https://github.com/Azure/azure-iot-sdk-csharp/blob/2018-10-9/iothub/device/src/Transport/AmqpTransportHandler.cs#L952

This same code pattern is present throughout the csharp SDK AmqpTransportHandler. The fix shall be discussed with @CIPop for consistency.

## Code sample exhibiting the issue:
```csharp
            methodReceivingLink.SafeAddClosed(async (o, ea) =>
                await Task.Run(async () =>
                    {
                        await this.SafeAddClosedMethodReceivingLinkHandler(
                            o,
                            new ConnectionEventArgs
                            {
                                ConnectionType = ConnectionType.AmqpMethodReceiving,
                                ConnectionStatus = ConnectionStatus.Disconnected_Retrying,
                                ConnectionStatusChangeReason = ConnectionStatusChangeReason.No_Network
                            }).ConfigureAwait(false);
                    }
                ).ConfigureAwait(false));
```

## Console log of the issue:
None.

**Comment by prmathur-microsoft** [comment]
If this is a task, please leave it on kanban. If its a bug then its suitable here.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
