### ISSUE TITLE
Remove MyStringCopy(...) from C# SDK code base, use standard framework patterns for that

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-csharp#730]
- **OS, version, SKU and CPU architecture used:** this issue is platform-independent
- **Application's .NET Target Framework :** This issue is framework-version-independent
- **Device:** This issue is device-independent. 
- **SDK version used:** from release  [2018-10-09](https://github.com/Azure/azure-iot-sdk-csharp/tree/2018-10-9)

## Description of the issue:

This issue is from a comment from @CIPop on another incoming feature:
"MyStringCopy? You may want to use Buffer or Span instead.
...
In general, use existing framework patterns to achieve basic operations."

Related to https://github.com/Azure/azure-iot-sdk-csharp/blob/2018-10-9/iothub/device/src/Transport/AmqpTransportHandler.cs#L909

This same code pattern is present throughout the csharp SDK AmqpTransportHandler.

## Code sample exhibiting the issue:
```csharp
            MyStringCopy(methodSendingLink.Name, out methodSendingLinkName);
```

## Console log of the issue:
None.

**Comment by prmathur-microsoft** [comment]
Please file this task under the PBI. This is not the right place to track tasks. If it is bug leave it as is.

**Comment by abhipsaMisra** [comment]
This is no longer used in current implementation of Amqp transport handler, closing this.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
