### ISSUE TITLE
InvalidOperationException is thrown and the app is getting crashed

### ISSUE THREAD

**Issue by Vishnunavaneeth** [Azure/azure-iot-sdk-csharp#731]
- **OS, version, SKU and CPU architecture used:** <VERSION> Android and iOS all versions
- **Application's .NET Target Framework :** <NETVERSION> xamarin
- **Device:** <DEVICETYPE> Android and iOS all devices
- **SDK version used:** <VERSION> 1.18.0 and below

## Description of the issue:

I am using Microsoft.Azure.Devices.Client in my Xamarin Forms App to connect to azure IOT Hub using AMQP protocol. The communication works as expected mostly. But we found an issue when network switches(not often, but crash is a crash), it throws an unhandled exception which will crash my Android and iOS apps. The exception details are below
 
TaskCompletionSource`1[TResult].SetException (System.Exception exception)
AmqpTransportInitiator+<>c__DisplayClass15_0.<ConnectTaskAsync>b__0 (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs a)
AmqpTransportInitiator.Complete (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs args)
AmqpTransportInitiator.OnConnectComplete (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs args)
TlsTransportInitiator.Complete ()
TlsTransportInitiator.HandleInnerTransportConnected (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs innerArgs)
TlsTransportInitiator.OnInnerTransportConnected (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs innerArgs)
TcpTransportInitiator.Complete (System.Net.Sockets.SocketAsyncEventArgs e, System.Boolean completeSynchronously)
TcpTransportInitiator.OnConnectComplete (System.Object sender, System.Net.Sockets.SocketAsyncEventArgs e)
SocketAsyncEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs e)
SocketAsyncEventArgs.Complete ()
<.cctor>b__308_3 (System.IAsyncResult ares)
SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state)
IThreadPoolWorkItem.ExecuteWorkItem ()
ThreadPoolWorkQueue.Dispatch ()
_ThreadPoolWaitCallback.PerformWaitCallback () 
## Console log of the issue:

TaskCompletionSource`1[TResult].SetException (System.Exception exception)
AmqpTransportInitiator+<>c__DisplayClass15_0.<ConnectTaskAsync>b__0 (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs a)
AmqpTransportInitiator.Complete (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs args)
AmqpTransportInitiator.OnConnectComplete (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs args)
TlsTransportInitiator.Complete ()
TlsTransportInitiator.HandleInnerTransportConnected (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs innerArgs)
TlsTransportInitiator.OnInnerTransportConnected (Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs innerArgs)
TcpTransportInitiator.Complete (System.Net.Sockets.SocketAsyncEventArgs e, System.Boolean completeSynchronously)
TcpTransportInitiator.OnConnectComplete (System.Object sender, System.Net.Sockets.SocketAsyncEventArgs e)
SocketAsyncEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs e)
SocketAsyncEventArgs.Complete ()
<.cctor>b__308_3 (System.IAsyncResult ares)
SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state)
IThreadPoolWorkItem.ExecuteWorkItem ()
ThreadPoolWorkQueue.Dispatch ()
_ThreadPoolWaitCallback.PerformWaitCallback ()

**Comment by CIPop** [comment]
Thanks @Vishnunavaneeth : the details are missing the actual exception. Can you please add that as well?

**Comment by jenoola** [comment]
@Vishnunavaneeth do you still see the issue? If so, please provide the actual exception

**Comment by prmathur-microsoft** [comment]
Please let us know if you still see this issue with the new SDK - 1.19.0. And feel free to reopen if you still see it.

**Comment by az-iot-builder-01** [comment]
@Vishnunavaneeth, @CIPop, @jenoola, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Vishnunavaneeth** [comment]
We are seeing the crash issue in the latestSDK as well.

**Comment by Vishnunavaneeth** [comment]
Could you please reopen and investigate. Thanks

**Comment by omiimo** [comment]
I am also facing the same issue. Any suggestion ?
