### ISSUE TITLE
Typo: `MethodResposeStatusCode` -> `MethodResponseStatusCode`

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-iot-sdk-csharp#735]
https://github.com/Azure/azure-iot-sdk-csharp/blob/24cda41372314402fff6cd5e82a056dde9174ede/iothub/device/src/MethodResponseStatusCode.cs#L9

**Comment by CIPop** [comment]
Argh... Thanks @cmenzi - unfortunately that's public API that has been shipped. We cannot safely modify public API without breaking our SemVer promise and so we cannot fix this until we go to v2.

(Won't fix: public API.)

**Comment by az-iot-builder-01** [comment]
@cmenzi, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
