### ISSUE TITLE
DPS Group Enrollment device Provisioning AMQP issue when device RegistrationId contains @ Symbol

### ISSUE THREAD

**Issue by vithal-wadje** [Azure/azure-iot-sdk-csharp#738]
## Description of the issue:

I am  Provisioning devices in group using DPS C# SDK with help of X509 certificate . We have certain logic to generate deviceId with combination of @ symbol (eg. device@product12) , I am creating the device certificate with combination of certain character and @ symbol (eg. device@product12), my device certificate is creating successfully but while Provisioning using C# SDK its throwing following error 

 
![image](https://user-images.githubusercontent.com/9838323/50154717-3076a800-02f0-11e9-9ffb-665e857e1a8f.png)

but when my device certificate name does not contain @ symbol then device get added successfully into the group.

## If your conclusion is @ not allowed in Device registration-id 

- Then how Individual enrollment allows @ symbol 
- Also from IoT hub I can Add device Id having @ symbol 

So what will be the issue , does it SDK issue or its issue like in Individual enrollment I can specify the device id & if I haven't specify device-id then its takes from certificate CA name & also CA name is considered as registration-Id & registration-id does not allows special symbols expect hyphen -, So similarly to this in group enrollment does not have option to specify device-id , So while provisioning group enrollment devices certificate CA name treated as Registration-id not device-id, that's why its throwing error?

If yes then I think its SDK implementation issue & it has missing functionality to differentiate between registration-id & device-id. Its should be behave  similar way as individual enrollment because at the end (provisioning) whatever devices whether in group or Individual its get registered into the IoT hub as Device-id.

![image](https://user-images.githubusercontent.com/9838323/50155963-7c771c00-02f3-11e9-8d65-34d33c96e6a0.png)

Let me know if requires any other details .

**Comment by CIPop** [comment]
Thanks @vithal-wadje : you are correct - the @ sign is not supported within a registrationId. 
The constraints for `registrationId` are listed here: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device 

> the registration ID is alphanumeric, lowercase, and may contain hyphens.

/cc @alextolp @nberdy

**Comment by az-iot-builder-01** [comment]
@vithal-wadje, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by vithal-wadje** [comment]
@alextolp  @CIPop  , @nberdy  , Sorry to say this but issue is closed without answering my question please read all the details what I am trying to say , I knew about naming conventions of registration-id but I am trying to say that if I can Add the device from IoT hub as well as from DPS Individual enrollment which having @ symbol then why not from group enrollment because whatever in group enrollment leaf certificate after provisioning its goes to the IoT hub as device-id & device-id don't have any rules about naming conventions, my question is why this is bug or why you treating registration-id as device-id in group enrollment because both these things are different & we don't have option to specify device-Id in group enrollment & you treating registration-id as group enrollment which is wrong .
