### ISSUE TITLE
Unable to connect to the remote server - While getting device twin

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-iot-sdk-csharp#740]
I have following code deployed on the device which is of OS - **Windows Embedded Standard**

    using Microsoft.Azure.Devices.Client
       
    ConfigHubClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt_WebSocket_Only);
    var twin = await ConfigHubClient.GetTwinAsync();
    TwinCollection deviceTwinConfig;
    deviceTwinConfig = twin.Properties.Desired;`

It's working totally fine locally (Windows 7 OS) but not on **Windows Embedded Standard**

It returns below exception message

> Unable to connect to the remote server

- I have all the basic certificate available on the device. 
- I have .NET Core self contained deployment on the target OS
- Same code working fine in some other device with same configuration!

So now how do I troubleshoot?

**IMPORTANT NOTE**

I have written small application to troubleshoot. I created a code which reads only the device twin but this time I used **RegistryManager** from Microsoft.Azure.Devices.Client and **did not specify any TransportType** . This connects without any issue!

Anything to do with Mqtt_WebSocket_Only?

**Comment by ewertons** [comment]
Hi @kudlatiger ,
we apologize but couldn't prioritize this issue sooner.

Is this still an issue for you?
If yes, could you share more details about the platform you are using, version of the SDK, etc?
Specifically
- What version of Windows Embedded are you using?
- Which .NET framework do you have installed in the platform showing issues?
- What version of the Azure IoT C# SDK are you using?

**Comment by prmathur-microsoft** [comment]
As we have not heard from you in a long time, I will close this for now. Feel free to reopen if you are still seeing it.

**Comment by az-iot-builder-01** [comment]
@kudlatiger, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
