### ISSUE TITLE
EventHubClient "An existing connection was forcibly closed by the remote host" in office network

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-iot-sdk-csharp#753]
Hi

When I use Device Explorer , I get error in office network "An existing connection was forcibly closed by the remote host" in office network"

seems like some protocol or port issue. Is there any way to configure protocol and port? so that I can make it run in office network.

**Comment by prmathur-microsoft** [comment]
At the moment we don't have such functionality in Device explorer. I recommend you use our portal 
https://portal.azure.com/#home and work with devices from there.

**Comment by kudlatiger** [comment]
What might be the reason behind this network issue? I have enabled all the required ports. still it's not working

**Comment by jenoola** [comment]
Office networks equipment may be configured in a way that interferes with Device Explorer. Please try to use Azure portal and ask your network admin about the error.

**Comment by kudlatiger** [comment]
Yes, I heard from admin that only port 80 and 443 is enabled in firewall.

**Comment by jenoola** [comment]
Have you tried using online Azure portal? Do you run into any issues there?

**Comment by kudlatiger** [comment]
I am not sure why we have to use azure portal. I am using device explorer c# code.

**Comment by kudlatiger** [comment]
This does not help in real use case. we have devices in field which are sending messages to cloud. I am not sure what you are referring. how does portal help for field devices.  devices in field are source of the messages.

**Comment by prmathur-microsoft** [comment]
If you are talking about C2D messages then you could use our service client and send C2D messages.

**Comment by jenoola** [comment]
And Azure portal allows to send messages from cloud to devices too

**Comment by prmathur-microsoft** [comment]
Does the above answer your question ? If so we would like to close this. Please feel free to reopen if you have any further issues.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @kudlatiger, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
