### ISSUE TITLE
Azure.Devices.Client deprecated dotnetty signed nuget dependency

### ISSUE THREAD

**Issue by krish-gh** [Azure/azure-iot-sdk-csharp#76]
Azure.Devices.Client nuget has dependencies on dotnetty signed nugets which are deprecated and has different public token in the dlls than the mainstream ones. Since Azure.Devices.Client is also used in https://github.com/Azure/azure-iot-protocol-gateway, it's makes it impossible to update dotnetty nugets there because of difference of publictoken. Protocol Gateway needs to move to dotnetty mainstream nugets and this issue is preventing that.

Raised https://github.com/Azure/azure-iot-sdk-csharp/pull/77

**Comment by krish-gh** [comment]
I created a Pull request #77 since there is an urgency in a customer engagement. Otherwise, I have to create a private nuget from the fork.

**Comment by jasmineymlo** [comment]
fixed in commit cfc7dc89f358d44576701e35e5cdeb95bd7899cc
