### ISSUE TITLE
How do I configure 'ConsumerGroup` in local.settings.json while developing Azure Function Version 2

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-iot-sdk-csharp#762]
I have below code to catch all the messages arrives at `IoT Hub`

        [FunctionName("device-message--funcapp-v2")]
        public static void Run([IoTHubTrigger("testhub", 
                           Connection = "IoTHubEventEndPoint", 
                           ConsumerGroup = "ActualConsumerGroup")]EventData message, 
            ILogger log)
        {
            log.LogInformation($"C# IoT Hub trigger:
           {Encoding.UTF8.GetString(message.Body.Array)}");     
        }

This works fine as expected, but now I do not want to hard code the `ConsumerGroup`. So I added below configuraiton entry in `local.settings.json`

       {
         "IsEncrypted": false,
         "Values": {
              "AzureWebJobsStorage": "",
              "FUNCTIONS_WORKER_RUNTIME": "dotnet",
              "EventHub": "",
              "CosmosDb": "",
             "ConfigurationConsumerGroup": "ActualConsumerGroup"
              }
            }

and changed code as below

           [FunctionName("device-message--funcapp-v2")]
        public static void Run([IoTHubTrigger("testhub", 
            Connection = "IoTHubEventEndPoint", 
            ConsumerGroup = "ConfigurationConsumerGroup")]EventData message, 
            ILogger log)

But it fails.

> [1/18/2019 9:47:11 AM] Microsoft.Azure.EventHubs: The messaging entity 'iothub-ns-testhub-945897-3a6f492cc4:eventhub:lctesthub~8191|ConfigurationConsumerGroup' could not be found.

**Comment by prmathur-microsoft** [comment]
Does the above answer your issue ? We will close it for now. Feel free to reopen if it doesn't work.

**Comment by az-iot-builder-01** [comment]
@kudlatiger, @fbeltrao, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kudlatiger** [comment]
Yes resolved
