### ISSUE TITLE
Please add more  information from edge Agent for telemetry 

### ISSUE THREAD

**Issue by initmahesh** [Azure/azure-iot-sdk-csharp#775]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION>

**Comment by jenoola** [comment]
Please provide more detail/context when you open issues. And you probably want to open it with IoT Edge project since we do not control the agent https://github.com/Azure/iotedge

**Comment by az-iot-builder-01** [comment]
@initmahesh, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
