### ISSUE TITLE
Randomly happens Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException

### ISSUE THREAD

**Issue by KirillSelyak** [Azure/azure-iot-sdk-csharp#776]
- **OS, version, SKU and CPU architecture used:** <VERSION>   Azure Function runtime version ~2, Microsoft.NET.Sdk.Functions-1.0.24, runtime identifier - portable 
- **Application's .NET Target Framework :** <NETVERSION>  netcoreapp2.1
- **Device:** <DEVICETYPE>  Azure function
- **SDK version used:** <VERSION> 
 Microsoft.Azure.Devices.Client 1.19.0
 Microsoft.Azure.WebJobs.Extensions.EventHubs  3.0.0
 Microsoft.NET.Sdk.Functions 1.0.24

## Description of the issue:

The flow is next:
Device =>  IoT hub => Azure function => IoT hub => Stream Analytics

at phase Azure Function => IoT hub we enrich message with data from 3rd party service and here 
we get this exception: Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized if we use Mqtt . It happens pretty often but not regularly , could even work for days ... 

if we use default protocol then situation is even worse, we get Microsoft.Azure.Devices.Client.Exceptions.IotHubException: The request has been throttled. Wait 10 seconds and try again. Operation type: AmqpLinkOpen that misinforms. 

## Code sample exhibiting the issue:

 [FunctionName("Enrichment")]

       public static async Task Run([EventHubTrigger("iot-hub-name", Connection = "InputIoTHubEndPoint", ConsumerGroup = "enrichmentGroup")]EventData message, ILogger log)
        {
            var outgoingMessage = await CreatedEnrichedMessageAsync(message);
            var deviceId = message.SystemProperties["iothub-connection-device-id"] as string;
            await SendBackToIotHub(outgoingMessage, deviceId)
                .ConfigureAwait(false);
        }

        private static async Task<OutgoingMessage> CreatedEnrichedMessageAsync(EventData message)
        {
            throw new NotImplementedException();
            //ToDo: here is communication with 3rd party
        }

        private static async Task SendBackToIotHub(OutgoingGnssMessage message, string deviceId)
        {
            var connectionString = Environment.GetEnvironmentVariable("OutputIotHubConnectionString");
            using (var deviceClient = DeviceClient.CreateFromConnectionString(
                connectionString,
                deviceId,
                Microsoft.Azure.Devices.Client.TransportType.Mqtt))
            {
                var messageString = JsonConvert.SerializeObject(message, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                });
                var bytes = Encoding.UTF8.GetBytes(messageString);
                var iotHubMessage = new Message(bytes);
                await deviceClient.SendEventAsync(iotHubMessage)
                    .ConfigureAwait(false);
            }
        }

## Console log of the issue:

Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass17_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)

**Comment by jenoola** [comment]
Could you try it with Azure Functions v2? There are known compatibility issues between Azure Functions v1 and more recent versions of our SDK, And Azure Functions team recommends to switch to newer version. To do so, you may either create a new Azure Functions project in VS and choose Azure Functions v2 
![image](https://user-images.githubusercontent.com/16417362/51932397-f7802780-23b3-11e9-9136-1931168ffcb7.png)

or modify some of your project files
csproj file:
```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
    <UseNETCoreGenerator>true</UseNETCoreGenerator>
</PropertyGroup>
```

host.json:

```
{
  "version": "2.0"
}
```

local.settings.json:

```
{
  ...
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    ...
  }
}
```
Please be aware that Azure Functions v2 are based on .NETCore instead of .NET Framework, so this may require additional changes to your app

**Comment by KirillSelyak** [comment]
Hi jenoola,
We are using version 2.

**Comment by jenoola** [comment]
Sorry, missed that. We will get back to you when we have an update on the issue

**Comment by matringer** [comment]
Seeing the same behavior on a recently implemented solution.  Code is very similar except using DeviceClient.Create instead of CreateFromConnectionString

**Comment by abhipsaMisra** [comment]
From the code snippet attached, it looks like you are using the IoT hub - scope connection string, along with your device ID, to initialize the device client instance.
`var deviceClient = DeviceClient.CreateFromConnectionString(connectionString, deviceId, Microsoft.Azure.Devices.Client.TransportType.Mqtt)`

Using the IoT hub scope connection string is only supported for Amqp and Http, and not over Mqtt.
Is there a reason why you are choosing to use the IoT hub - scope connection string, instead of the device-scope connection string?

Could you replace your device client initialization with device scope connection string, and give that a try?

**Comment by KirillSelyak** [comment]
It was more than 1 year ago :)  
This solution is not alive anymore, we moved to another technology .
@abhipsaMisra ,  @matringer sees this issue as well and using DeviceClient.Create.
Not sure it is related to your scope proposal or not.

**Comment by matringer** [comment]
Here's the code I'm using:

`var device = await iotHubRm.GetDeviceAsync(deviceId);
using (DeviceClient deviceClient = DeviceClient.Create(iotHubHostname,
    new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, device.Authentication.SymmetricKey.PrimaryKey),
    Microsoft.Azure.Devices.Client.TransportType.Mqtt))
{
    var iotHubMsg = new Microsoft.Azure.Devices.Client.Message(payload);
    await deviceClient.OpenAsync();
    await deviceClient.SendEventAsync(iotHubMsg);
    await deviceClient.CloseAsync();
}`

If there's an alternate approach (or different transport type) that might help, please advise.

**Comment by abhipsaMisra** [comment]
Thanks for the information @matringer . 
Your usage of the device client looks good; do you still see unauthorized exceptions over Mqtt? Is the usage more stable over Amqp/ Http?

**Comment by matringer** [comment]
No new errors in the last 10 days.  I have not made any changes or tried any other protocols.  Do we think it might help avoid issues by using Amqp or Http ?

**Comment by abhipsaMisra** [comment]
All 3 protocols should have similar reliability in communication with IoT hub, especially when using a symmetric key for authentication. If you still see issues over Mqtt, please let us know so that we can investigate it further.

**Comment by abhipsaMisra** [comment]
@matringer Any update on this?

**Comment by matringer** [comment]
No failures in the last 2 weeks.  Volume has been low on this service though...not sure if that might  related.  FYI, I changed the code to use TransportType.Http1 (instead of MQTT) before reading your comment above...but it seems to be working fine as expected.

**Comment by abhipsaMisra** [comment]
@matringer Thanks for the update!
If you feel confident with your solution I can close this issue, or we can keep this open if you want to investigate the behavior with Mqtt.

Let me know!

**Comment by abhipsaMisra** [comment]
@matringer Any update on this?

**Comment by matringer** [comment]
No new failures since my last comment.  It would be nice to keep this open since it's still not fully understood.  If I see the issue happen again, what additional information would you need from me to troubleshoot it further?

**Comment by abhipsaMisra** [comment]
@matringer We would prefer to not have an open issue lying around with no action item. That being said, if you do see this issue re-occur, you can either reopen this issue or create a new issue linking it to this one.
The additional information that we would require for this investigation are SDK logs. The instructions for collection are present [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs). Make sure that you clean out any confidential information from the logs before sharing them with us.

Let me know if you have further questions.

**Comment by matringer** [comment]
OK, this is fine with me.

**Comment by az-iot-builder-01** [comment]
@KirillSelyak, @matringer, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
