### ISSUE TITLE
Suggestion: Dont use dynamic

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-iot-sdk-csharp#778]
## Description of the issue:
There are very very very few reasons to ever use 'dynamic'/DLR in C# nowadays, and Microsoft should not be encouraging its use in things like the TwinCollection. This makes for some very annoying coding to just use the API.

## Code sample exhibiting the issue:

Code I have to write to use TwinCollection (something that could just be IDictionary or even JObject)

```C#
new Item {
                NextVersion = twin.Tags.Contains("nextVersion") 
                           ? twin.Tags["nextVersion"] : default,
}
```

If Tags was a simple IDictionary, the equivalent would be:

```C#
new Item {
                 NextVersion = twin.Tags.TryGetValue("nextVersion", out int nextVer) 
                           ? nextVer : default
}
```

Slightly less verbose, fewer lookups in the collection, faster because it doesnt rely on the DLR. There are very few downsides here.

**Comment by sharmasejal** [comment]
It's a good point, but we can't change the interface now since we have customers using it. Thanks for the feedback.

**Comment by az-iot-builder-01** [comment]
@onionhammer, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
