### ISSUE TITLE
Need to include Microsoft.Azure.Amqp 2.0.4 in the latest NuGet package

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdk-csharp#78]
Microsoft.Azure.Amqp 2.0.2 which is currently listed as a dependency has a bug that's fixed in 2.0.4. The bug manifests itself as described in https://github.com/Azure/azure-iot-sdk-csharp/issues/75.

**Comment by jasmineymlo** [comment]
commit ede7e789a0df0ee6804ace6d0e91d05e01bbbb83

**Comment by tameraw** [comment]
Released.
