### ISSUE TITLE
Microsoft.Azure.Devices.Shared v1.25.0-preview-001 NuGet Package dependency issue

### ISSUE THREAD

**Issue by philipktlin** [Azure/azure-iot-sdk-csharp#781]
In Microsoft.Azure.Devices.Shared v1.25.0-preview-001 nuget package, nuspec specified a dependency of Microsoft.CodeAnalysis.FxCopAnalyzers.  This will cause any project referring to this NuGet running FxCop checkings during build.  This will make other referencing projects build fail.

For example, I tried to update IoT Edge solution to use this latest preview NuGet of Microsoft.Azure.Devices.Client NuGet; then build the solution.  Expected the build succeeds, but actually build failed with many errors related to FxCop rules.

**Comment by ewertons** [comment]
Hi @philipktlin ,
this fix has been released already.
It is available starting from this package: https://www.nuget.org/packages/Microsoft.Azure.Devices.Shared/1.25.0-preview-002 

Thanks for contributing to the Azure IoT SDK project.
