### ISSUE TITLE
C# Sdk: DeviceClient.SetMethodHandlerAsync does not receive message from iotHub 

### ISSUE THREAD

**Issue by mohakraaj** [Azure/azure-iot-sdk-csharp#79]
DeviceClient.SetMethodHandlerAsync does not receive messages from cloud for C# sdk only. IoTHubClient_SetMessageCallback works as expected in c++. 

Sample https://github.com/Azure/azure-iot-sdk-csharp/tree/master/device/samples/DeviceClientMethodMqttSample will help to reproduce the issue.

**Comment by sergaz-msft** [comment]
Hello @mohakraaj I am able to receive Methods on Device using DeviceClientMethodMqttSample in C# sdk. Are you using the latest version of the SDK? You can use Device Explorer to Call a Method on Device. For that sample you have two methods registered: "GetDeviceName" and "WriteToConsole".

**Comment by sergaz-msft** [comment]
Hi @mohakraaj ,
I am setting this issue as resolved. Let me know if you find any other related issues.
All Best.
