### ISSUE TITLE
Provisioning Service - Individual Enrollment query returns always all enrollments

### ISSUE THREAD

**Issue by dmakarenko-connyun** [Azure/azure-iot-sdk-csharp#794]
I'm using static allocation policy to assign a device to the specified IoT Hub. My intention is to get enrollments by given IoT Hub. The adapted code from SDK samples:
```
QuerySpecification querySpecification = new QuerySpecification("SELECT * FROM enrollments WHERE iotHubHostName = 'my-iot-hub'");
using (Query query = _provisioningServiceClient.CreateIndividualEnrollmentQuery(querySpecification))
{
    while (query.HasNext())
    {
        Console.WriteLine("\nQuerying the next enrollments...");
        QueryResult queryResult = await query.NextAsync().ConfigureAwait(false);
        Console.WriteLine(queryResult);
    }
}
```
1. Doesn't matter what is my query (even if it is complete wrong, for example `SELECT * FROM devices`) I always get the full list of enrollments which are defined in the DPS.
2. `IotHubHostName` property is correctly returned by API only if the enrollment was created using API not from the Azure Portal (in this case the property is always `null` but the portal shows Assigned IoT Hub correctly)

Is it generally possible to use API to make queries for DPS enrollments?

**Comment by dmakarenko-connyun** [comment]
I see that #790 introduces `IotHubs` collection which can be used to extract the assigned IoT hub.

**Comment by prmathur-microsoft** [comment]
As per your above comment, can we close this? Do you see any further issues with extracting `IotHubs` from collection ?

**Comment by dmakarenko-connyun** [comment]
@prmathur-microsoft Thanks for the response. The first point is still actual but I think it is not an SDK problem because I can't do any query against enrollments collection neither with SDK nor with plain [http](https://docs.microsoft.com/en-us/rest/api/iot-dps/queryindividualenrollments/queryindividualenrollments) request. 
May be you know Is it by design or it's a bug?

**Comment by yzhong94** [comment]
+ @alextolp

**Comment by isabelcabezasm** [comment]
Same issue here:  :(

QuerySpecification query = new QuerySpecification("{\"query\":\"SELECT * FROM enrollments WHERE provisioningStatus='enabled'\"}");

**Comment by nelsonmorais** [comment]
Hi @anushprabhu any ETA to have full support for query options on DPS?

**Comment by gregorybleiker** [comment]
@anushprabhu we are having this issue as well... any new solutions or updates?

**Comment by nelsonmorais** [comment]
Pinging @alextolp as well to see if we can get any answers on the status of this topic

**Comment by alextolp** [comment]
We understand that lacking support for queries makes it hard to use our APIs. We are looking into it, no ETA just yet, but will update here once we have an update.

**Comment by timtay-microsoft** [comment]
Closing this issue as it is a service side issue, not an SDK side issue.

**Comment by az-iot-builder-01** [comment]
@dmakarenko-connyun, @prmathur-microsoft, @anushprabhu, @isabelcabezasm, @nelsonmorais, @gregorybleiker, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by shaunco** [comment]
> We understand that lacking support for queries makes it hard to use our APIs. We are looking into it, no ETA just yet, but will update here once we have an update.

@alextolp @anushprabhu @yzhong94  Any updates on this? I just spent the better part of a day trying to figure out why no matter what query I provided in this `enrollments/query` API, I just got back ALL of my enrollments. This is a very painful thing to be missing when you have more than a few enrollments. At a minimum, updates to the [documents](https://docs.microsoft.com/en-us/rest/api/iot-dps/queryindividualenrollments/queryindividualenrollments) to indicate the query parameter in the request body is useless would be helpful.

**Comment by bcb44** [comment]
@alextolp @anushprabhu @yzhong Seems like this issue still exists.  Can you put a note in the docs.microsoft.com page that explains the query API isn't fully functional? Pretty frustrating debugging something for a while only to find out that it doesn't actually work in the first place - could all be fixed by a note in there

**Comment by shaunco** [comment]
"isn't fully functional" --> "isn't implemented in the slightest"
