### ISSUE TITLE
 Unauthorized exception in device streams echo sample with AMQP over websockets and certs auth

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-csharp#797]
See [link](https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/39)

**Comment by prmathur-microsoft** [comment]
Could you provide a  sample for this scenario to repro?

**Comment by rezasherafat** [comment]
@prmathur, this was reported using the AMQP protocol when running the C# proxy sample. The link above has stack trace and other info.

I believe @ewertons also has repro'd this issue in his tests which is how he was working on the fix prior to this customer report.

**Comment by prmathur-microsoft** [comment]
@ewertons - Could you point to simple steps to repro this?

**Comment by prmathur-microsoft** [comment]
Closing this as the issues is fixed as per link above.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @rezasherafat, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
