### ISSUE TITLE
Exception after first login with device streams proxy sample

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-csharp#798]
See [Link](https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/38)

**Comment by prmathur-microsoft** [comment]
As I have not heard any update on this issue in a long time I'm closing this for now. Feel free to reopen if you see further issues.

**Comment by az-iot-builder-01** [comment]
@rezasherafat, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
