### ISSUE TITLE
Unhandled exception using device streams sample with MQTT

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-csharp#799]
See [link](https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/37)

**Comment by prmathur-microsoft** [comment]
As I have not had any update on this issue for a long time, I'm closing this. Feel free to reopen in case you see any further errors.

**Comment by az-iot-builder-01** [comment]
@rezasherafat, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
