### ISSUE TITLE
Empty message sent when using latest version with HTTP or AMQP

### ISSUE THREAD

**Issue by japf** [Azure/azure-iot-sdk-csharp#8]
We're using a very simple code to push data from the C# SDK to our Azure IoT Hub. After upgrading to the latest version of the library, we're seeing empty messages being pushed to the IoT Hub, either using HTTP or AMQP.

With HTTP, a Fiddler trace looks like that:

```
POST https://jeremy-iot-hub.azure-devices.net/devices/deviceID/messages/events?api-version=2016-11-14 HTTP/1.1
Authorization: SharedAccessSignature sr=jeremy-iot-hub.azure-devices.net%2Fdevices%2FComX200RN-SIMAGENT-000000&sig=xxx%3D&se=yyy
User-Agent: Microsoft.Azure.Devices.Client/1.1.3
iothub-messageid: 10
iothub-app-DSP_MESSAGE_ID: 10
iothub-app-DSP_QA_BATCH_ID: 0
iothub-app-DSP_QA_MESSAGE_PREFIX: test13
Accept: application/json
Host: jeremy-iot-hub.azure-devices.net
Content-Length: 0
```

Our code looks like this:

```csharp
var deviceClient = DeviceClient.Create("jeremy-iot-hub.azure-devices.net", new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, device.Authentication.SymmetricKey.PrimaryKey), TransportType.Http1);

var jObject = new JObject
{
    {"MessagePrefix", MessagePrefix},
    {"Batch", batchId},
    {"Message", msgId}
};

string messageString = jObject.ToString();
Message message = new Message(Encoding.UTF8.GetBytes(messageString)) { MessageId = msgId.ToString() };
message.Properties.Add("MESSAGE_ID", msgId.ToString());
message.Properties.Add("QA_BATCH_ID", batchId.ToString());
message.Properties.Add("QA_MESSAGE_PREFIX", MessagePrefix);

await deviceClient.SendEventAsync(outgoingMessage);
```

The same code was working just fine with version 1.0.11.

**Comment by japf** [comment]
**Update:**

After debugging our code with the code of the SDK, I was able to find out the root cause. Before sending the message via *SendEventAsync()* we log it, and we call the *GetBytes()* method.

It turns out that calling *GetBytes()* once prevent the message from being sent properly. What is weird is that if we call *GetByes()* twice we can an exception but calling *GetBytes()* and *SendEventAsync()* fails silently. 

I will try to submit a PR if I find a way to improve this behavior.

**Comment by japf** [comment]
Looks like the source of this problem is in the SendMessageWithRetryAsync method:

```csharp
async Task SendMessageWithRetryAsync(SendMessageState sendState, Message message, Func<Task> action)
{
    if (sendState.Iteration == 0)
    {
        sendState.InitialStreamPosition = message.BodyStream.CanSeek ? message.BodyStream.Position : UndeterminedPosition;
        message.TryResetBody(sendState.InitialStreamPosition);

        await TryExecuteActionAsync(sendState, action);
        return;
    }

    EnsureStreamIsInOriginalState(sendState, message);

    await TryExecuteActionAsync(sendState, action);
}
```

Since we called the GetBytes() method before reaching this one, we're going to set the InitialStreamPosition to the end of the stream.

Please let me know if that is clear enough. I also would welcome guidance about how to fix that in the source so that I can propose a PR.

**Comment by jasmineymlo** [comment]
Hi Japf,
You mentioned that the code works fine with v1.0.11, were you calling GetBytes() to log the message before sending also?
Regards,
Jasmine

**Comment by japf** [comment]
Yes.

**Comment by jasmineymlo** [comment]
Hi Japf,
I can repro the issue is v1.0.12 as well and it is fine on v1.0.11.  The issue is surfaced due to the fix for taking care of non-seekable stream.  Originally, the stream position is hard reset to the beginning before send.  Removing the hard reset surfaced the bug in GetBytes()

The proposed fix would be to reset the position in within GetBytes() after reading the stream so that the position would not be altered after the call.  I should have the fix ready in next release.

Btw, why are you using GetBytes for logging send messages?  You should be able to log using the byte[] which is used for creating the Message object.  Thanks.

Regards,
Jasmine

**Comment by japf** [comment]
I don't have a good reason for using GetBytes() to log the message, the code was just written this way :-)

**Comment by jasmineymlo** [comment]
Thanks for letting us know about this bug.  Here is the commit:
d533f986c5ff0a4343ae787a644578236c44f322
