### ISSUE TITLE
Remove cancellation token and timeout from proxy sample

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-csharp#800]
Remove use of cancellation tokens in device stream samples ([here ](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/device-streams-proxy/device/DeviceStreamSample.cs#L59)and [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/device-streams-proxy/service/DeviceStreamSample.cs#L68))

**Comment by timtay-microsoft** [comment]
Closing this since this issue should be open on the samples repo, not the SDK repo

**Comment by az-iot-builder-01** [comment]
@rezasherafat, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
