### ISSUE TITLE
Get error, unable to retrieve list of devices

### ISSUE THREAD

**Issue by sharadshrestha1** [Azure/azure-iot-sdk-csharp#804]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:
After configuration step, the app throws "Unable to retrieve list of devices. Please verify your connection strings. "

## Console log of the issue:

![image](https://user-images.githubusercontent.com/12172615/53032205-02b6f800-3434-11e9-8606-6427071b056b.png)

**Comment by sharadshrestha1** [comment]
After configuration step, the app throws "Unable to retrieve list of devices. Please verify your connection strings. "

![image](https://user-images.githubusercontent.com/12172615/53032167-eb780a80-3433-11e9-8c6c-c25b1967779f.png)

**Comment by prmathur-microsoft** [comment]
Could you please provide information here : 
* **OS, version, SKU and CPU architecture used:**
* **Application's .NET Target Framework :**
* **Device:**
* **SDK version used:**

**Comment by prmathur-microsoft** [comment]
Are you using service client or device explorer ?

**Comment by prmathur-microsoft** [comment]
Please let us know if you are still seeing this issue. I'm closing this for now as I have not heard in more than month. Feel free to reopen if you have more data.

**Comment by az-iot-builder-01** [comment]
@sharadshrestha1, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
