### ISSUE TITLE
Proxy Settings in IoT Core

### ISSUE THREAD

**Issue by mgrontzki** [Azure/azure-iot-sdk-csharp#809]
I want to send temperature values with amqp_ws to the Azure Iot-Hub. In my private Network all works fine, but my client has a protected network and all traffic must be send over the proxy server.
I'm using a Raspberry Pi 3 with Windows 10 Iot Core (10.0.17763.107)
How can I config the proxy settings?
- In my code?
- In the Dashboard?
- With PowerShell?
I found no useable instruction or step by step sample, so I hope that someone here could help me.
Thanks a lot.

**Comment by mehtavipul** [comment]
I do have similar issue. Upload file fails while I try to upload from company network to Azure IoT Hub. Network team suggested to go through another proxy. Implemented proxy as mention in below code but doubt that this code is not respecting proxy settings and upload still fails. Below is the sample C# code I am using.

```
var conSettings = new Http1TransportSettings
{                
    Proxy = new System.Net.WebProxy {
        UseDefaultCredentials = true,
        Address = new Uri("http://proxy.com:1234"),
        BypassProxyOnLocal = true            
    }                
};            

using(var deviceClient = DeviceClient.CreateFromConnectionString(conString, "xxx:xxx:xxx:xxx", new ITransportSettings[] { conSettings }))
using(var sourceData = new FileStream(file, FileMode.Open))
{
    await deviceClient.UploadToBlobAsync(fileName, sourceData);
}
```

**Comment by jenoola** [comment]
Have you tried running our e2e tests? We have tests for using different protocols with proxy. You may check how the tests are implemented to get the idea https://github.com/Azure/azure-iot-sdk-csharp/tree/master/e2e/test

**Comment by mgrontzki** [comment]
I think I made a stupid mistake. 
It is not working, but I'm one the way now. I will inform here if everything will be working.

**Comment by mgrontzki** [comment]
Hello again. I have looked in the e2e test sample code tried a little bit with my code and now I have a vb.net code which is normally working with HTTP1 Transport settings, but not with AMQP/AMQPWS.
I don't know why AMQP don't work, because it works for long time, but this is a second question.

I have installed me now a CCProxy-Server for logging and testing the proxy settings and I could see that there is **NO** traffic over the proxy. Please tell me why?

Here is my code:
`
    Private Async Sub SendIotMessage(Message As Microsoft.Azure.Devices.Client.Message)
        
        'Neu mit Proxy !!!
        Dim ProxyServerAddress As String = "192.168.1.103:808"                  '"10.64.1.145:8080"

        'Mit Proxy
        Dim transportSettings As New Microsoft.Azure.Devices.Client.Http1TransportSettings  'AmqpTransportSettings(TransportType.Amqp_WebSocket_Only)
        transportSettings.Proxy = New WebProxy(ProxyServerAddress, False)

        Dim ListOfTransportSettings(0) As ITransportSettings
        ListOfTransportSettings(0) = transportSettings

        Dim authMethod As IAuthenticationMethod = AuthenticationMethodFactory.CreateAuthenticationWithRegistrySymmetricKey(DeviceId, deviceKey)

        Using myDeviceClient As DeviceClient = DeviceClient.Create(iotHubUri, authMethod, ListOfTransportSettings)
            Try
                Await myDeviceClient.SendEventAsync(Message)

                Debug.Print("SendEventAsync: OK" & vbCrLf)
            Catch ex As Exception
                Debug.Print("SentIoTMessage: " & ex.Message & vbCrLf & ex.InnerException.Message)
            End Try
            Await myDeviceClient.CloseAsync()

        End Using

    End Sub
`

**Comment by mgrontzki** [comment]
I tried everything, but I have no traffic on my proxy server.

Please help me!!!

**Comment by jenoola** [comment]
Is there no traffic to proxy just from your app or in general? Can you ping it?
Also, could you run our e2e tests for proxy (don't forget to set your environment variables first) and check if there are any errors there?

**Comment by mgrontzki** [comment]
Hello jenoola, if I set the proxy settings in my edge browser on my Laptop, i can see this traffic on my CCProxy Client on another PC in my Network.
If I set the proxy settings in the transportsetting (see code above) then I can't see anything on this CCProxy client, but my Raspberry Client works normally. I think he use the normal way out, not over the proxy server. But in the network from my client, there is no normal way out. 

My Raspberry use Windows 10 IoT Core Version 10.0.17763.107 (Target and min. Target)
My nuget packages:
Microsoft.Azure.Devices.Client - Version 1.19.0
Microsoft.Azure.AMQP - Version 2.4.1
Microsoft.NetCore.UniversalWindowsPlattform - Version 6.1.9
IoTHelpers - Version 0.8.0

All what I need is a sample for my Raspberry Pi that I could send messages to my Azure Iot-Hub with AMQP over Websockets, over a Proxy Server.

Can I run these e2e sample on my Raspberry?

**Comment by jenoola** [comment]
Please run our e2e tests on your Raspberry Pi with env variables set.

Also, please try to run your app from your laptop and see if you can reach proxy server

**Comment by mgrontzki** [comment]
Hello jenoola, I have tested my code in a new UWP App on my Laptop now. With the same effect.
The code:
transportSettings.Proxy = New WebProxy(ProxyServerAddress, False)
has no effect. The traffic is not going over the Proxy Server. 

The difference on my laptop is, that I can go to the Edge-Browser settings, proxy settings, add proxy, and it works! 
But on my Raspberry I don't have this browser-settings.

**Comment by jenoola** [comment]
@mgrontzki please try to run our e2e tests on your laptop, and don't forget to set env variables. I do not get repro on UWP.

```
            string ProxyServerAddr = "<ip>:<port>";

            DeviceClient client = null;
            try
            {
                Http1TransportSettings tsets = new Http1TransportSettings();
                tsets.Proxy = new WebProxy(ProxyServerAddr, false);
                ITransportSettings[] transportSettings = new ITransportSettings[] { tsets };
                IAuthenticationMethod authMethod = AuthenticationMethodFactory.CreateAuthenticationWithRegistrySymmetricKey("<deviceID>", "<symm key>");

                client = DeviceClient.Create("<iothub address>", authMethod, transportSettings);

                await client.SendEventAsync(new Message()).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }
            finally
            {
                await client?.CloseAsync();
                Debug.WriteLine("Done.");
            }
```
Dependencies:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Amqp">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Azure.Devices.Client">
      <Version>1.19.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.7</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by jenoola** [comment]
Have you tried using Amqp_Tcp_Only as transport type? What do you see there?

**Comment by mgrontzki** [comment]
Amqp_Tcp_Only doesn't work over the proxy, that's the point why I must use Websockets.
I have tested it now, but I have no traffic on my proxy. Also not if I use the browser proxy setting.
I think it must be HTTP and not TCP, so only Websockets could work.

**Comment by jenoola** [comment]
Well, things working in your browser make sense, because your browser uses HTTP and not AMQP, and in your app HTTP also works. Have you tried setting a global default proxy in your application?

**Comment by jenoola** [comment]
@mgrontzki please check if you see the issue in a console app/our e2e tests, this will allow to see if the root cause is in your code/setup or in uwp/win iot core libraries

**Comment by mgrontzki** [comment]
@jenoola this was a great idea! If I use a console core app, it works!

Than the next question: Must I use IoT Core UWP app on the raspberry, if I write only a background app?

**Comment by jenoola** [comment]
AFAIK, all apps on Win IoT Core are using the same base libraries.

Also, if everything works fine in a console app, uwp/iot core should give an exception at some point. Please check if you might have missed it.

**Comment by mgrontzki** [comment]
@jenoola There was no exception. The code runs normally and the message was send to my IoT-Hub without the redirection over the proxy.

**Comment by mgrontzki** [comment]
@jenoola Is there anything what I can do to solve this Problem?

**Comment by mgrontzki** [comment]
@jenoola is it possible to solve this problem with C++?

**Comment by jenoola** [comment]
@mgrontzki we do not have C++ version of SDK. You can choose from C#, Java, Python, Node and C.

**Comment by mgrontzki** [comment]
"customer-input-needed" - What kind of input can I give to solve this?

**Comment by jenoola** [comment]
I am still investigating the issue, I don't quite see the behaviour you are describing. I'll update you when there are any news

**Comment by jenoola** [comment]
@mgrontzki so, you should actually be able to run .NETCore console apps on Rapsberry Pi. With .NETCore 2.1, you should build the app on your dev machine and then copy the binaries to RaspPi. With .NETCore 2.2, you can install it to RaspPi and then it will work as with any other supported platform. This could be your workaround

**Comment by mgrontzki** [comment]
@jenoola if this works, it would be great. I will try this in the next days and sending my experience. Thanks!

**Comment by mgrontzki** [comment]
@jenoola, the first tests are working! I use now Raspbian as OS and a .NET Core Console App, like Scott Hanselman explain this in his blog. The last thing I must do, is to change my IoT Code for the measuring and I2C-Display to the Console App. I hope that this will be working also.

**Comment by prmathur-microsoft** [comment]
As per the above comment, I'm assuming you got this working. Feel free to reopen this issue if you still facing problems.

**Comment by az-iot-builder-01** [comment]
@mehtavipul, @jenoola, @mgrontzki, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
