### ISSUE TITLE
API Feedback: ServiceClient.CreateStreamAsync() should take stream name argument directly

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#811]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

**API Review Feedback:** ServiceClient.CreateStreamAsync() should take the stream name as argument directly. No need to ask the developer to first create a DeviceStreamRequest instance. If in the future more parameters are needed to create the request, we can add an overload that takes a structure to pass those in.

**Comment by timtay-microsoft** [comment]
Closing this issue as we plan on re-working the device streaming API surface completely later

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
