### ISSUE TITLE
API Feedback: DeviceStreamRequest.Url should be Uri

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#814]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

**API Review Feedback:** DeviceStreamRequest.Url should be renamed to Uri

**Comment by timtay-microsoft** [comment]
Closing this issue as this has now been checked in

**Comment by az-iot-builder-01** [comment]
@wickste, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
