### ISSUE TITLE
API Feedback: Remove empty DeviceStreamRequest type from device SDK

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#815]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:

**API ReviewFeedback:** Remove empty DeviceStreamRequest type from device SDK

**Comment by timtay-microsoft** [comment]
@wickste I see the DeviceStreamRequest type in the device SDK being used in several APIs. Can you expand a bit on what you wanted here?

**Comment by timtay-microsoft** [comment]
Closing this issue as there is no empty DeviceStreamRequest type in this repo

**Comment by az-iot-builder-01** [comment]
@wickste, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
