### ISSUE TITLE
SetConnectionStatusChangesHandler never fired when connection restored

### ISSUE THREAD

**Issue by backspacer80** [Azure/azure-iot-sdk-csharp#819]
- **OS, version, SKU and CPU architecture used:** Windows 7 Desktop x64
- **Application's .NET Target Framework :** .NET Core 2.0
- **Device:** Desktop PC
- **SDK version used:** Azure Device SDK for .NET 1.9

## Description of the issue:
When connection from device to IoT Hub is lost and eventually restored again the connection status is not reported back to OK. For this reason I am not able to detect when the connection is up again and when I can continue sending telemetry data. This is 100% reproducible with the code below. Protocol is AMQP.

Observations:
1. As soon as OpenAsync is called the status is reported as connected.
2. When I disconnect the network the status is reported as disconnected right away.
3. However, when I connect back the network the status is never reported as connected.

I tried with different timeout values, I tried to wait after the connection is restored, I tried to send an event after the restore. However, the status change handler is never again fired after connection is lost.

## Code sample exhibiting the issue:
```
var deviceClient = DeviceClient.CreateFromConnectionString(AzureIotHubConnectionString, TransportType.Amqp);
deviceClient.SetConnectionStatusChangesHandler((status, reason) => Console.WriteLine($"Connection status: {status}. Reason: {reason}"));
deviceClient.OpenAsync().Wait();
Console.WriteLine("Please disconnect and connect and watch the status change.");
Console.ReadLine();
```

## Console log of the issue:
Connection status: Connected. Reason: Connection_Ok
Please disconnect and connect and watch the status change.
// I disconnect the network here.
Connection status: Disconnected. Reason: Communication_Error
// I connect back the network here. No status.

**Comment by davilu** [comment]
@backspacer80 Thanks to report this issue. We'll working on it and let you know how it goes.

**Comment by jenoola** [comment]
Got a repro, investigating the cause

**Comment by jenoola** [comment]
@backspacer80 according to current design, if there is no receiver link (e.g. method or twin enabled), device will stay disconnected. Could you try this? I've tried to add method handler with 1.20 version, and device does get reconnected.

**Comment by az-iot-builder-01** [comment]
@backspacer80, @davilu, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
