### ISSUE TITLE
Unexpected behavior when trying to query device twins information 

### ISSUE THREAD

**Issue by kyberpunk** [Azure/azure-iot-sdk-csharp#82]
Hello,
I found unexpected behavior when executing device twins query.

When I change reported property value on the IoT Hub client device and then get the single device twin info on service side, the property value is always set correctly. But there is usually old value when I get the twin device info by executing a query in short time.

I prepared the following sample to ilustrate it:

```cs
// query for device twin select
var queryString = $"SELECT * FROM devices WHERE deviceId IN ['{_deviceId}']";

// clients initialization
_registryManager = RegistryManager.CreateFromConnectionString(_connectionString);
await _registryManager.OpenAsync();
_client = DeviceClient.Create(_connectionStringBuilder.HostName, new DeviceAuthenticationWithRegistrySymmetricKey(_deviceId, "<primaryKey>"), TransportType.Mqtt);
await _client.OpenAsync();

// set reported property to initial value
var properties = new TwinCollection { ["isSwitchedOn"] = true };
await _client.UpdateReportedPropertiesAsync(properties);

// wait a minute to ensure the query gets the latest value
await Task.Delay(60000);
// execute query
var query = _registryManager.CreateQuery(queryString);
var queryTwin = (await query.GetNextAsTwinAsync()).Single();

// change reported property value
properties = new TwinCollection { ["isSwitchedOn"] = false };
await _client.UpdateReportedPropertiesAsync(properties);
// get device twin
// there is "isSwitchedOn" property value corretly false
var twin1 = await _registryManager.GetTwinAsync(_deviceId);
// execute device twin query
// there is "isSwitchedOn" property value still true
//await Task.Delay(60000); // if you add about a minute delay, the value should be correct
query = _registryManager.CreateQuery(queryString);
queryTwin = (await query.GetNextAsTwinAsync()).Single();
```

When I call the IoT Hub REST API directly, the behavior also occurs. I didn't found any mentions about this behavior in IoT Hub guides and docs. 

Is there any caching on the IoT Hub service when using query engine? Do I have to get every single device separately, when I want to show current information about devices in the list in my application? It will be much slower, I hoped the query should solve it.

Thank you for answering.

**Comment by fsautomata** [comment]
Hi,

The store that we use for queries is eventually consistent, so you can expect a few mins of delay (<5 mins).
It is always preferrable to use the getDeviceTwin call from the service to retrieve a single twin. That will always get you the latest values, in addition to being is faster and cheaper (in the sense that you have much higher throttle limits).

**Comment by kyberpunk** [comment]
Ok. Thank you for explanation.

**Comment by yosephlodamo** [comment]
Hello @fsautomata,
Thank you for your explanation. getDeviceTwin is giving me the latest value. What shall I use to get the latest device twins for all devices? I need to query latest values of few properties of all devices.

Thank you
