### ISSUE TITLE
Problem when adding device and twin in IoT Edge

### ISSUE THREAD

**Issue by YohskDista** [Azure/azure-iot-sdk-csharp#827]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp2.2
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION> 1.17.2

## Description of the issue:

When we want to add an IoT Edge device we use the method `AddDeviceAsync` of the `RegistryManager`, but we want also to add some tags to our device during the creation.
So we see an other method that could help us : `AddDeviceWithTwinAsync` but the problem is that when we execute this method our device is created in the IoT Devices and not in the IoT Edge.

## Code sample exhibiting the issue:

The code who add the device in the IoT devices instead of the IoT Edge :

```
private static async Task AddDeviceAsync(string companyId, string deviceId)
        {
            var registryManager =
                RegistryManager.CreateFromConnectionString(IoTHubConnectionString);
            Device device;

            try
            {
                var twin = new Twin
                {
                    Tags = new TwinCollection(@"{ companyId: '" + companyId + "' }")
                };

                var iotEdgeDevice = new Device(deviceId)
                {
                    Capabilities = new DeviceCapabilities { IotEdge = true }
                };

                await registryManager.AddDeviceWithTwinAsync(iotEdgeDevice, twin);
            }
            catch (DeviceAlreadyExistsException)
            {
                device = await registryManager.GetDeviceAsync(deviceId);
            }
        }
```

The code who add the device in the IoT Edge and update the Twin after the add :

```
private static async Task AddDeviceAsync(string companyId, string deviceId)
        {
            var registryManager =
                RegistryManager.CreateFromConnectionString(IoTHubConnectionString);
            Device device;

            try
            {
                var iotEdgeDevice = new Device(deviceId)
                {
                    Capabilities = new DeviceCapabilities { IotEdge = true }
                };

                device = await _registryManager.AddDeviceAsync(iotEdgeDevice);

                var twin = await registryManager.GetTwinAsync(deviceId);

                await registryManager.UpdateTwinAsync(deviceId, "{\"tags\": {\"companyId\":\"" + companyId + "\"}}",
                    twin.ETag);
            }
            catch (DeviceAlreadyExistsException)
            {
                device = await registryManager.GetDeviceAsync(deviceId);
            }
        }
```

Thank you for your help !

Leonardo

**Comment by timtay-microsoft** [comment]
This is a bug on our side, and I'll try to get the fix out for it soon. Thanks for reporting this issue.

**Comment by az-iot-builder-01** [comment]
@YohskDista, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
