### ISSUE TITLE
Special character DeviceID test for Edge

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#829]
Missing Edge test with device special characters:

            string deviceId = "n@m.et#st";
            string moduleId = "$edgeAgent";

See https://github.com/Azure/azure-iot-sdk-csharp/pull/771/files for details.

**Comment by timtay-microsoft** [comment]
Closing this issue because the test for this has been added in since https://github.com/Azure/azure-iot-sdk-csharp/commit/93128d3625d3bc77d4621fcd0c0579513bf43f15

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
