### ISSUE TITLE
UWP Javascript sample 

### ISSUE THREAD

**Issue by rangedsp** [Azure/azure-iot-sdk-csharp#83]
Hi there,

I noticed the JS sample link is broken and there's no sample for it. Is this still supported?
I've attempted to wrap the sdk in a .winmd component but had lots of issues. (mostly around .net core versioning)

Cheers,
Jonny

**Comment by arturl** [comment]
Hi,

We no longer support JS via this SDK. The .NET SDK now only supports .NET languages, and no longer exposes WinRT interfaces.

**Comment by rangedsp** [comment]
Thanks for responding, would you have any tips around wrapping up the .net sdk in a .winmd component?

In an earlier version of this repo the js sample worked for UWP so I've been using that, but I eventually want to use the newer version.

**Comment by arturl** [comment]
Hi @rangedsp, 

You can still do that by writing a wrapper C# WinRT library (similar to how Azure IoT SDK for UWP was structured) and use the latest Azure IoT SDK in it. Your JS code would call the wrapper.

**Comment by rangedsp** [comment]
Alright I'll try that, my project wasn't building before, I think it has something to do with the .net core versions. 

But that's another issue. I'll close this now. Thanks!
