### ISSUE TITLE
C# Service SDK - Device twin operations

### ISSUE THREAD

**Issue by bragma** [Azure/azure-iot-sdk-csharp#852]
Hi,
I plan to use device twins for handling device configuration and I'd like to do it from Azure Functions and/or my backend ASP .Net Core API. I'm a bit perplexed by the main Readme of the Service SDK stating that twin operations are not supported. What's the actual status and plans?
Thanks!

**Comment by prmathur-microsoft** [comment]
Can you point me to documentation which says that. Device twin is currently functional on service SDK as we know of it. Locating the doc might help me understand what you are actually looking for?

**Comment by prmathur-microsoft** [comment]
As I have not heard from you in a long time, I'm closing this. Feel free to reopen if you have any further questions

**Comment by az-iot-builder-01** [comment]
@bragma, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by alexanderbikk** [comment]
@prmathur-microsoft, I think @bragma talking about readme file in this repo.

Device Twins operations | ✖️ | Use your backend app to perform twin operations. This SDK only supports Get Twin at the moment.

It's a bit confusing actually.MAybe you can fix it

Thanks.
