### ISSUE TITLE
ProvisioningDeviceClient Create() fails in hosted App in Azure only

### ISSUE THREAD

**Issue by timhenn** [Azure/azure-iot-sdk-csharp#855]
Running an ASP.NET Core 2.2 Web App API in Azure.  Running the code locally works.  The code fails when hosted in Azure.  Nuget package is version 1.2.2 (Microsoft.Azure.Devices.Provisioning.Client).

I removed the logging statements for readability:

```
using (var securityProvider = new SecurityProviderX509Certificate(pfxDeviceContents.certificate, pfxDeviceContents.collection))
                    {
                        using (var transport = new ProvisioningTransportHandlerHttp())
                        {
                            var globalendp = _configuration["ProvisioningEndpoint"];
                            var scope = _configuration["DpsScopeId"];

                            var provClient = ProvisioningDeviceClient.Create(globalendp, scope, securityProvider, transport);
....
```

The exception thrown is:

> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied
   at Internal.Cryptography.Pal.StorePal.Add(ICertificatePal certificate)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.Azure.Devices.Provisioning.Client.CertificateInstaller.EnsureChainIsInstalled(X509Certificate2Collection certificates)
   at Microsoft.Azure.Devices.Provisioning.Client.ProvisioningDeviceClient.Create(String globalDeviceEndpoint, String idScope, SecurityProvider securityProvider, ProvisioningTransportHandler transport)

I've gone so far as taking the exact same certificate that fails in the hosted app and running it using a local instance of the same app.  So the certificate itself is not an issue.  Is there additional information i can gather to help solve this problem? Can anyone else confirm the use of this class in Azure is working?

**Comment by sergaz-msft** [comment]
@jenoola adding as reference that the same question was asked on SO: https://stackoverflow.com/questions/55240562/provisioningdeviceclient-create-fails-in-hosted-app-in-azure-only

**Comment by jenoola** [comment]
@timhenn getting certificates from device requires admin access rights. Do you run your app in Azure as admin?

**Comment by zweim1** [comment]
We have an IoT device implemented as Azure Function using Consumption plan. We observed the same exception when the device uses group enrollment. But Individual Enrollment works fine. 

For the group enrollment, the certificate chain needs to be added to Security Provider
SecurityProviderX509Certificate(X509Certificate2 clientCertificate, X509Certificate2Collection certificateChain). In the ProvisioningDeviceClient.create() method, it will call CertificateInstaller.EnsureChainIsInstalled() to check whether the CA exists in the trust store: X509Store(StoreName.CertificateAuthority, StoreLocation.CurrentUser). If it does not exist, it will attempt to add the ca to the truststore. But Azure Function (or other Web App) does not have permission to add a cert to the trust store (StoreName.CertificateAuthority), resulted in "Access is denied" exception. In addition, Azure does not provide an option to add CA to the trust store during deployment.
For individual Enrollment, SecurityProviderX509Certificate(X509Certificate2 clientCertificate) does not include CA chain. So no permission issue. 
Question: why CSharp IoT SDK needs to add the CA certificate to the trust store? For group enrollment, this is the CA that signs the entity certificate used by the device. Seems that the Java IoT SDK does not perform the same operations.

**Comment by anhashia** [comment]
To **workaround** this problem, you do following 

Upload Intermediate CA in DPS and do proof of possession on Intermediate CA 
**Intermediate CA (POP)** -> device

After  that make following call in you device application code
```
 var security = new SecurityProviderX509Certificate(device_certificate))
```
This way you **won't** have to install chain Root CA-> Intermediate CA on machine hosting Azure Function for Group Enrollment scenario.

**Comment by prmathur-microsoft** [comment]
Since you need your trusted certs manager to contain Intermediate cert on azure functions, what anhasia mentions above would be work around.
Closing this issue as per above. Feel free to reopen it if you have any further questions.

**Comment by az-iot-builder-01** [comment]
@timhenn, @jenoola, @zweim1, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
