### ISSUE TITLE
X509 Authentication to Azure IoT Hub fails

### ISSUE THREAD

**Issue by dropsonic** [Azure/azure-iot-sdk-csharp#857]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client 1.19.0

## Description of the issue:
Authentication error when trying to call Azure IoT Hub on IoT device (simulation).

Followed the steps from [the official manual](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started).
Uploaded my self-signed certificate to Azure IoT Hub and verified it.
Created a device named "Device1Cert" with X.509 CA Signed authentication type.
Auth via a secret key works fine.
Also it works with a test certificate generated by [this script from Azure IoT SDK](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md).
Seems that I'm missing something about intermediate certificates?

## Code sample exhibiting the issue:

    var cert = new X509Certificate2("device1.pfx", "1234");
    var auth = new DeviceAuthenticationWithX509Certificate("Device1Cert", cert);
    var device = DeviceClient.Create("myhub.azure-devices.net", auth, TransportType.Amqp);
    await device.SetMethodHandlerAsync("HelloWorld", HelloWorld, null); 

## Steps that I did to create my certificates:

    -- Root CA
    openssl genrsa -out rootCA.key 2048
    openssl req -x509 -new -key rootCA.key -days 10000 -out rootCA.crt
    -- Device certificate
    openssl genrsa -out device1.key 2048
    openssl req -new -key device1.key -out device1.csr
    openssl x509 -req -in device1.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out device1.crt -days 10000
    openssl pkcs12 -export -inkey device1.key -in device1.crt -out device1.pfx
    -- entered "1234" as a password

## Console log of the issue:

    Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: 'Tracking Id:f66aaee755694618b690ddb425e49e04-G:4-TimeStamp:03/19/2019 16:59:09'

**Comment by prmathur-microsoft** [comment]
Do you intend to use intermediate or not? I can answer better depending on that.

**Comment by dropsonic** [comment]
> Do you intend to use intermediate or not? I can answer better depending on that.

No, I don't think it will be needed in my case.

**Comment by jenoola** [comment]
@dropsonic I do not get see any issue with your code (run as admin) but I did not use direct openssl commands. I used scripts from [this tutorial](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) that is mentioned in the guide you gave the link to.

Any certificate issues you are seeing are not caused by our SDK

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @dropsonic, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by dropsonic** [comment]
@jenoola the tutorial mentioned does not provide any guidance on generating production-ready certificates. That is the reason why I used OpenSSL.

**Comment by jenoola** [comment]
@dropsonic the issue you are experiencing is most likely connected to how your certificates are generated, which is not about our SDK. You can check the scripts I mentioned to see how certificates are generated there and adapt them to your need or contact openssl project to get instructions from them

**Comment by dropsonic** [comment]
@jenoola thanks, I'll check it; but it would be very nice to have an article in SDK documentation about generating production-ready certificates for simple cases.

**Comment by jenoola** [comment]
@dropsonic thank you for the feedback we will look into that
