### ISSUE TITLE
Windows Store Certification Failure for TPM

### ISSUE THREAD

**Issue by danebou** [Azure/azure-iot-sdk-csharp#858]
- **OS, version, SKU and CPU architecture used:** 1809 Windows 10 IoT Core arm32
- **Application's .NET Target Framework :** Universal Windows Build 17763
- **Device:** N/A
- **SDK version used:** 1.1.4

## Description of the issue:
As if a few weeks ago, the windows store app review updated their requirements which caused our app to fail the review. 

Starting from a bare-bones passing UWP app, adding the `Microsoft.Azure.Devices.Provisioning.Security.Tpm` package causes the review to fail. (See log for failed review output). 

**This means no app that contains this package can get published on the windows store.**

## Console log of the issue:
> FAILED
>     Supported APIs
> 
>     Error Found: The supported APIs test detected the following errors:
>         API SetDllDirectoryW in kernel32.dll is not supported for this application type. TestUpload.dll calls this API.
>     Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
>     How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:
>     Alternatives to Windows APIs in Microsoft Store apps.

**Comment by danebou** [comment]
Update: [`TbsDevice`](https://github.com/Microsoft/TSS.MSR/blob/master/TSS.NET/TSS.Net/TbsDevice.cs) from TSS.NET makes a reference to `SetDllDirectory` which is likely the source. Testing the bare-bones app with just `TSS.Net` still causes the failure. 

I've [re-posted the issue posted on the TSS.Net github repo](https://github.com/Microsoft/TSS.MSR/issues/34)

I'll leave this issue up until the TSS.Net package is updated.

**Comment by danebou** [comment]
Minor update:
The fix has been merged for TSS.NET, but is waiting a new release.
It also appears the windows store review has reverted the requirements so we can publish apps.

**Comment by CIPop** [comment]
Fixed by #981 

@danebou this will be included in the next release. Please give it a try with code from `master` and reopen the bug if it still doesn't work.

**Comment by az-iot-builder-01** [comment]
@danebou, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
