### ISSUE TITLE
Getting timeout issue with DeviceClient version 1.18

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-iot-sdk-csharp#860]
I'm sending data to IoT hub device using DeviceClient inside while loop.

I'm not very sure why i'm getting "I/O error occurred" while executing below while loop code I'm may be creating DeviceClient object at wrong place.

Can anyone help me here.

public async Task ProcessData()
        {
            Device device;
            string messageData = "{\"name\":\"DemoData\",\"no\":\"111\"}";
            var startTime = DateTime.UtcNow;

            foreach (var deviceId in DataList)
            {
                device = await registryManager.GetDeviceAsync(deviceId.DeviceId);
                if (device != null)
                {
                    await SendMessages(startTime, deviceId.DeviceId, device.Authentication.SymmetricKey.PrimaryKey, "URI", messageData);
                }
            }
            // need to wait until ProcessMessages while loop completes
            callNextAfterWhileLoopDone();

        }

        private async Task SendMessages(DateTime startTime, string deviceId, string deviceKey, string hostName, string messageData)
        {
            DeviceClient deviceClient = DeviceClient.Create(hostName, new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, deviceKey), Microsoft.Azure.Devices.Client.TransportType.Mqtt);

            await ProcessMessages(startTime, deviceId, deviceClient, messageData);
        }

        private async Task ProcessMessages(DateTime startTime, string deviceId, DeviceClient deviceClient, string messageData)
        {
            try
            {
                while (DateTime.UtcNow - startTime < TimeSpan.FromMinutes(15)) //run for 15minutes
                {
                    await deviceClient.SendEventAsync(messageData);
                }
            }
            catch (Exception ex)
            {
                // i got exception here 
            }
        }
exception details -

{"I/O error occurred."}

at Microsoft.Azure.Devices.Client.InternalClient.<>c.b__62_2(Task t) at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at IoTSimulatorDev.Controllers.HomeController.d__21.MoveNext()

FullName = "Microsoft.Azure.Devices.Client.InternalClient+<>c.b__62_2(System.Threading.Tasks.Task)"

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. We are working on getting a repro.

**Comment by jenoola** [comment]
@ashuthinks I do not get a repro with SDK 1.19.0 on Windows 10. Please try your code with SDK 1.19.0. If you are still seeing the issue, please provide the full exception output, as well as the following info for your environment:
- Device type
- Device OS
- Target .NET Framework

**Comment by jenoola** [comment]
@ashuthinks Do you still see the issue with the latest SDK?

**Comment by prmathur-microsoft** [comment]
Closing this issue as I have not heard from you in  along time. Feel free to reopen if you see further issues.

**Comment by az-iot-builder-01** [comment]
@ashuthinks, @prmathur-microsoft, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
