### ISSUE TITLE
Twin fault injection test does not check desired property update callback operation properly

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#867]
The twin DesiredPropertyUpdate callback is not tested properly for the fault injection tests (highlighted for MqttWs test):

Steps:

1. Perform initialization operation (set the device client desired property update callback handler).

1. Perform baseline test operation - service updates the twin, device client desired property update callback handler should get the updated properties.

1. Inject fault for duration <durationInSec>.

1. During faulted duration, perform the test operation in step 2 again (sdk should retry and finally succeed once fault duration has passed). As a result, service should update the twin, device client desired property update callback handler should get the updated properties.

1. Close the device client instance.

Checking the logs, we can see that device client desired property callback handler is not getting called in step 4. 
If we add a delay of 1s before step 4, we can see the callback being called.

**Comment by abhipsaMisra** [comment]
Verified with tests, the desired property callback gets invoked as expected. Closing this issue.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
