### ISSUE TITLE
Support Microsoft Fake

### ISSUE THREAD

**Issue by kolauy** [Azure/azure-iot-sdk-csharp#87]
Current the SDK marks many methods as internal. This makes Microsoft Fake does not work.

I have no way to shim or stub ServiceClient & RegistryManager in tests. Please support Microsoft Fake for the SDK library.

**Comment by tameraw** [comment]
@kolauy - Currently this is in our backlog but has not yet bubbled up in terms of priority. We'll keep you posted.

**Comment by CIPop** [comment]
Closing as a duplicate to #61 . Feel free to submit a PR to address this issue.
