### ISSUE TITLE
ServiceClient webproxy problem

### ISSUE THREAD

**Issue by HiroyukiSakoh** [Azure/azure-iot-sdk-csharp#871]
See [link](https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/41)

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. We are working on getting a repro.

**Comment by HiroyukiSakoh** [comment]
@prmathur-microsoft @jenoola
What is the status of this issue?

I created a [program](https://gist.github.com/HiroyukiSakoh/dd8770ce915e001aa33d063a51e0f691) that reproduces the same root cause problem.
The second request does not via WebProxy.

In Microsoft.Azure.Devices.HttpClientHelper,
Webproxy is set to httpClientObj, but it is not set to httpClientObjWithPerRequestTimeout.
https://github.com/Azure/azure-iot-sdk-csharp/blob/7f37ee1b4526bd6bcaf3b887b6ed7048777c10b4/common/src/service/HttpClientHelper.cs#L52-L73

**Comment by HiroyukiSakoh** [comment]
#1178

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @HiroyukiSakoh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
