### ISSUE TITLE
Handle AmqpConnectionHolder graceful disconnect

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#887]
Currently, when all devices got removed, AmqpConnectionHolder will terminate the TCP connection/websocket instead of graceful disconnect (`CloseAsync`).

This is tracking work to add a mechanism to gracefully disconnect within the last device's CloseAsync task context.

**Comment by vinagesh** [comment]
Adding more context -> When we don't do a graceful disconnect handshake, windows can put the existing connections in a bad state and eventually we can not open any more connections.

**Comment by drwill-ms** [comment]
Tracking in ADO.
