### ISSUE TITLE
Receiving DeviceMessageLockLostException 

### ISSUE THREAD

**Issue by MattHoneycutt** [Azure/azure-iot-sdk-csharp#89]
I've built a virtual device using the C# library.  The virtual device runs just fine on my local box, but when I try to run the app on a different machine, I see two odd things:

First, calls to DeviceClient.ReceiveAsync *immediately* return with null, always.  

Second, when a cloud-to-device message is received by the client, trying to call DeviceClient.CompleteAsync on it always throws a DeviceMessageLockLostException.  

Again, this does not happen when I run the app locally, it only happens when the app is executed as an Azure Web job.

Interestingly, if I stop the job, but use Kudu's debug console to navigate to where the app executable is, then run it manually, it also works just fine. 

What am I missing?  I can't find any guidance on what a DeviceMessageLockLostException even means...

**Comment by sergaz-msft** [comment]
Hi @MattHoneycutt can you detail better what sample did you tried from the C# SdK? I would like to try and reproduce your issue on my own environment. Thanks.

**Comment by MattHoneycutt** [comment]
Hi @sergaz-msft, I apologize, I meant to close this out already.  I found the issue: I actually had *two* DeviceClients connecting up with the same device ID.  Long-story short, I missed that this particular web job was configured to have two instances instead of operating as a singleton.  

It would be nice if the DeviceClient raised an exception or something so that an outside user (me) could tell that it was being disconnected though.

**Comment by sergaz-msft** [comment]
Hi @MattHoneycutt ,

Thanks for confirming it. For your reference you can see the Message Lifecyle [here.](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages) Also reading through the comments on [DeviceMessageLockLostException.cs](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Common/Exceptions/DeviceMessageLockLostException.cs) we can understand it better.

At the server side I will raise this to the team and check if we are already logging some metrics on the Azure Portal whenever two instances of DeviceClient are using the same DeviceID.
