### ISSUE TITLE
Remove method unsubscription dead code

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#890]
This is to track removing the code that is removing method subscription within the inner stack. This is dead code as we've decided that the only way to unsubscribe (from Methods, Twin) is to close and open a new `DeviceClient`.

**Comment by CIPop** [comment]
> - [ ] Switch the retry policy to always retry even if no subscriptions (method, twin, module events) are present

This is tracked by #985 .

**Comment by CIPop** [comment]
Timeout on EnsureOpenAsync (the async semaphore) is tracked by #992

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@CIPop, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
