### ISSUE TITLE
Automatic Device Management Target Condition IN operator Support for C# SDK 

### ISSUE THREAD

**Issue by vithal-wadje** [Azure/azure-iot-sdk-csharp#908]
I am using the Microsoft.Azure.Devices C# SDK to create the IoT hub device Configuration but want specific condition to be set IN operator  for target condition as following 

` ```
string[] deviceId = new string[]{"device1","device2"};
            string filterDevices = string.Empty;

```
            foreach (var item in deviceId)
            {
                filterDevices += "'" + item + "'" + ",";
            };
          
            configuration.TargetCondition = "deviceId IN [" +  filterDevices.TrimEnd(',')+ "]";`

The preceding query is get failing following exception 

`{"Message":"ErrorCode:InvalidConfigurationTargetCondition;BadRequest","ExceptionMessage":"Tracking ID:616e71798e4d4e33a91caf84c40c88fc-G:8-TimeStamp:04/11/2019 11:47:37"}`


but when I use same query over the portal then its work, So the question is that does I am missing something or SDK does not support IN operator

**Comment by prmathur-microsoft** [comment]
Can you give more details ?

OS, version, SKU and CPU architecture used: 

Application's .NET Target Framework : 

Device: 

SDK version used:

**Comment by prmathur-microsoft** [comment]
Closing this issue as I have not heard from you in a long time. Feel free to reopen if you still see any further issues.

**Comment by az-iot-builder-01** [comment]
@vithal-wadje, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by spinosae** [comment]
Hi I have seen same issue with az iot cli. For example:
```
az iot edge deployment update -n my-hub --deployment-id my-deployment --set targetCondition="tags.my_tag in ['true', true]"
```
would fail with same error `{'Message': 'ErrorCode:InvalidConfigurationTargetCondition;BadRequest',...}`

I could apply same target condition from Azure Portal without issue.

Actually I couldn't find a definitive schema for target condition.  "IN" operator was not mentioned in [Microsoft documentation](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring). I guessed it.
