### ISSUE TITLE
How to get status of the message delivery from Device to IOTHub in C#

### ISSUE THREAD

**Issue by mathisharp** [Azure/azure-iot-sdk-csharp#91]
Hi Support, 

We are using DeviceClient of Azure IOT hub to push data from device to cloud.

- **OS used:** <VERSION> Windows 7

- **Protocol used:** <VERSION> Amqp_WebSocket_Only

- **SDK version used:** <VERSION> IoT Device Client 1.2.6

- **programming language used:** <VERSION> C#

# Description of the issue:

how do i confirm the message send from device is successfully delivered to IOTHub. I noticed that the java sdk has an eventcallback class but not in C# . In C# we use SentEventAsync() to sent data but this does not give any response of delivery. how to get the status for messages sent to IOTHub in C#

# Code sample exhibiting in Java for eventcallback:

protected static class EventCallback implements IotHubEventCallback { public void execute(IotHubStatusCode status, Object context) { System.out.println("IoT Hub responded to message with status " + status.name()); } } 

# Console log of the issue:

**Comment by jasmineymlo** [comment]
@mathisharp, In C# sdk, we use await and async.  As soon as the async task is complete and return, we can assume that the messages are sent to the IoThub successfully.  If there is any error in the operation, there will be exception throw.  Thanks.

**Comment by jasmineymlo** [comment]
@mathisharp Hope the above information helped.  Feel free to reopen the issue for more discussion if needed.  Thanks.
