### ISSUE TITLE
Direct method call is timing out, but C2D and D2C message works

### ISSUE THREAD

**Issue by hnigam-git** [Azure/azure-iot-sdk-csharp#913]
- **OS, version:**  Windows 10 Desktop x64, 
- **Application's .NET Target Framework :** net461
- **SDK version used:**  Microsoft.Azure.Devices.Client - 1.18.1, Microsoft.Azure.Devices.Shared - 1.15.1
- **Protocol used:** TPM

## Description of the issue:
I'm seeing my calls to direct method will fail after sometime ending with timeout error. Once I restart my device client service, then it will again start working for me. I get the same timeout error even if I increase the timeout seconds.

Response message:

{"message":"Device {\"Message\":\"{\\\"errorCode\\\":404103,\\\"trackingId\\\":\\\"99604e9ed25a4a6a8b4a08b96f389dd5-G:11-TimeStamp:04/16/2019 05:58:20\\\",\\\"message\\\":\\\"Timed out waiting for device to connect.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:00:10\\\"},\\\"timestampUtc\\\":\\\"2019-04-16T05:58:20.4667031Z\\\"}\",\"ExceptionMessage\":\"\"} not registered"}

**Comment by prmathur-microsoft** [comment]
Can you try 1.20.1 ? We had a major redesign on AMQP in 1.20.0 and lot of fixes went in.

**Comment by jenoola** [comment]
Also, can you please provide a code sample for reproducing the issue?

**Comment by Mikkelcv** [comment]
We are experiencing the same issue with this setup:

- OS, version: Windows 10 Desktop x64,
- Application's .NET Target Framework : net472
- SDK version used: 1.20.0
- Protocol used: AMQP

The test program is same as in:
https://github.com/Azure/azure-iot-sdk-csharp/issues/946

There is no way to provoke the issue on purpose that we have discovered, it is something that happens. There is no correlation on how long a period that has to pass before it happens, and we also see that the system do recover again after a period. This can be 1 hour or 8 hours or even more.

We have setup a test that calls a DirectMethod on the device once in a while and then monitor the result.

When DirectMethod fails, then C2D and D2C is still working.

On the IoTHub in azure portal is Diagnostic log enabled for: Connections and DirectMethod

```
AzureDiagnostics  
| where TimeGenerated > ago(48h) 
| where parse_json(properties_s).deviceId == "EndToEnd" 
| order by TimeGenerated asc  
```

![image](https://user-images.githubusercontent.com/39376179/58234869-e3d04680-7d3f-11e9-9e4d-8991e3ac5455.png)

We see the issue across multiple IoTHubs and multiple devices

**Comment by rquackenbush** [comment]
I'm seeing the same thing in my environment. I can create this situation by unplugging the network cable on the device running the DeviceClient code. Once the cable is plugged back in, the client is able to send telemetry (D2C messages) but Direct Methods fail as above.

**Comment by timtay-microsoft** [comment]
@rquackenbush @Mikkelcv @hnigam-git do any of you still see this issue in the latest version of the device client (1.25.0)?

**Comment by Mikkelcv** [comment]
Just updated to 1.25.0, will see in a day or two how it goes.

**Comment by timtay-microsoft** [comment]
@Mikkelcv are you hitting any issues?

**Comment by Mikkelcv** [comment]
Hi,

Thanks for the reminder, we have not seen the problem for a while now. 
I am ok with closing the issue.

**Comment by timtay-microsoft** [comment]
Great! I'll go ahead and close this issue

**Comment by az-iot-builder-01** [comment]
@hnigam-git, @prmathur-microsoft, @Mikkelcv, @rquackenbush, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
