### ISSUE TITLE
AmqpConnectionPoolSettings.ConnectionIdleTimeout is not used anywhere

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#916]
## Description of the issue:
AmqpConnectionPoolSettings has a ConnectionIdleTimeout property, which should be set on the AMQP Connection. But with the latest changes in master, this property is not being used anywhere. 

@zolvarga @CIPop

**Comment by CIPop** [comment]
Also solve #887

**Comment by CIPop** [comment]
1. Short fix: do not close connections for pooled settings for the entire lifetime of the process (or allow an infinite setting).
2. Provide the correct fix to close the connections after the specified timeout period.

**Comment by CIPop** [comment]
This is a regression from 1.19.0 - the ConnectionIdleTimeout API exists (no breaking change) but the behavior is missing (connections are closed immediately).

**Comment by timtay-microsoft** [comment]
We have marked this field as obsolete, and will not be adding any functionality to it

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
