### ISSUE TITLE
A lot of tokens being sent to the server over the CBS link when using SDK v1.20.0

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#917]
## Description of the issue:
I have a few modules using C# SDK Version 1.20.0 deployed to an Edge device. With this arrangement, the EdgeHub logs show a lot of tokens being sent by the client rapidly. 

I also noticed that the network bandwidth usage goes up significantly when connecting to IoTHub using the latest SDK, presumably because of the same issue.

## Code sample exhibiting the issue:
Any C# device/module using the latest version of the SDK seems to have this problem.

## Console log of the issue:
<6> 2019-04-19 00:21:42.968 +00:00 [INF] - Token updated for d1/Sender3
<6> 2019-04-19 00:21:42.969 +00:00 [INF] - New token received on the Cbs link
<6> 2019-04-19 00:21:42.969 +00:00 [INF] - Token updated for d1/Sender3
<6> 2019-04-19 00:21:42.970 +00:00 [INF] - New token received on the Cbs link
<6> 2019-04-19 00:21:42.970 +00:00 [INF] - Token updated for d1/Sender3
<6> 2019-04-19 00:21:42.971 +00:00 [INF] - New token received on the Cbs link
<6> 2019-04-19 00:21:42.972 +00:00 [INF] - Token updated for d1/Sender3
<6> 2019-04-19 00:21:42.973 +00:00 [INF] - New token received on the Cbs link
<6> 2019-04-19 00:21:42.973 +00:00 [INF] - Token updated for d1/Sender3
<6> 2019-04-19 00:21:42.974 +00:00 [INF] - New token received on the Cbs link

**Comment by prmathur-microsoft** [comment]
1.20.1 resolves this issue. Feel free to reopen if you still see it.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
