### ISSUE TITLE
AMQP drops null app properties while MQTT and HTTP do not. All protocols should be consistent in their implementation.

### ISSUE THREAD

**Issue by aklintsevich** [Azure/azure-iot-sdk-csharp#919]
![image](https://user-images.githubusercontent.com/4860052/56604614-3be82180-65b7-11e9-8e27-2fa5044d56c3.png)

**Comment by aklintsevich** [comment]
CustomNullProperty was added to all protocols, but as we can see in the picture it appears in MQTT and HTTP, but not AMQP.

**Comment by prmathur-microsoft** [comment]
Can you give details on 
OS, version, SKU and CPU architecture used: 

Application's .NET Target Framework : 

Device: 

SDK version used:

**Comment by aklintsevich** [comment]
@prmathur-microsoft 

"OS, version, SKU and CPU architecture used:

Application's .NET Target Framework :

Device:"

This is not necessary to know. This occurs on the latest SDK version and can be easily verified on any
OS, version, SKU, CPU architecture.

**Comment by jenoola** [comment]
@aklintsevich please provide the information requested, as well as the actual number for SDK version you are using and a code sample for repro

**Comment by az-iot-builder-01** [comment]
@aklintsevich, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
