### ISSUE TITLE
Reconnection mechanism

### ISSUE THREAD

**Issue by jamesguitar3** [Azure/azure-iot-sdk-csharp#92]
Is there any update on C# sdk supporting the D2C messaging's re-connection mechanism? Thanks
@ewertons @jasmineymlo

**Comment by jasmineymlo** [comment]
@jamesguitar3 Do you mean D2C messaging retries on disconnect?  The sdk supports retry on operations with default retry policy.  Each operation will be retry for the duration of the default timeout(4min) or by setting the OperationTimeoutInMilliseconds.  Thanks.

**Comment by jamesguitar3** [comment]
@jasmineymlo Thank you for the feedback. I did some test and indeed observed the data re-sent to Hub after the connection is resumed, but there seem to be some data lost (missing some messageIDs) even though the disconnection was less than 4 minutes. Additionally, do you have a rough ETA for the local data cache implementation for C# (even persistent after reboot)?  Per Pierreca's comments (https://github.com/Azure/azure-iot-sdk-node/issues/18#issuecomment-297131839), I am assuming you guys are still working on implementing this in other languages, including C#. Thank you.

**Comment by jasmineymlo** [comment]
@jamesguitar3 it would be nice if you could give me more details on the data lost.  The sdk is supposed to silently retry within the 4 minutes default operation timeout.  On any non-transient error, the operation in retry would stop and exception should be throw.  It's best to have try catch block around SendEventAsync() to make sure the operation is completed without any exception.  Please note that messages in retry are not persisted after reboot.  Thanks.
