### ISSUE TITLE
DEV

### ISSUE THREAD

**Issue by MOMOX9** [Azure/azure-iot-sdk-csharp#933]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION>

**Comment by az-iot-builder-01** [comment]
@MOMOX9, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by MOMOX9** [comment]
Thanks Verymuch,,

Pada 03/05/2019 9:24 PTG, az-iot-builder-01 <notifications@github.com> menulis:

@MOMOX9<https://github.com/MOMOX9>, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute customer satisfaction survey<https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu>

**Comment by MOMOX9** [comment]
BIG TROBLE IN AZURE SITE
Hi fried, Iam Master Admin
MOMOX9.Github.com
To night i found the big trouble in verification method by using creditcard,
If verification by card use for signup how the users in malaysia need to use, tonigt my AMEX and Visa Signature Was block and declined by local bank after 3 time submited reject if like G suite use same method verification we must change curency for local before submit, . i just feed back to you becouse u are more very profesional and your voice is hight value in AZURE org. I just users,

Thanks
MOMOX@MOMOX8.COM
A.ZURE@Outlook.my

Pada 03/05/2019 9:46 PTG, MOMOX9 <notifications@github.com> menulis:
Thanks Verymuch,,

Pada 03/05/2019 9:24 PTG, az-iot-builder-01 <notifications@github.com> menulis:

@MOMOX9<https://github.com/MOMOX9>, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute customer satisfaction survey<https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu>
