### ISSUE TITLE
Need to connect to IoTHub via IP Address (Not HostName) 

### ISSUE THREAD

**Issue by mesgar** [Azure/azure-iot-sdk-csharp#939]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> 
netcoreapp2.2
- **Device:** <DEVICETYPE> 
A Simulated Device
- **SDK version used:** <VERSION> 
Microsoft.Azure.Devices.Client(1.29.0-preview-002)
## Description of the issue:

Hi guys,
Everything works fine when connecting to IoT Hub using host name.  Since the router is not DNS capable we need to use IoT Hub's global IP address.(aware of changing stuff)
We obtained the temporary IP address using nslookup.
But it doesn't work that way. first we faced  "TLS authentication error". 
With overriding RemoteCertificateValidationCallback, now we're getting "UnauthorizedException: CONNECT failed: RefusedServerUnavailable" 
Scenario: Send data from device to IoT Hub using mqtt protocol. very simple!
Any suggestions?
## Code sample exhibiting the issue:

          //DeviceClient s_deviceClient = DeviceClient.CreateFromConnectionString(s_connectionString[i], TransportType.Mqtt);
          var settings = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
          settings.Proxy = null;
          settings.RemoteCertificateValidationCallback = (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) =>
          {
            Console.WriteLine("SSL Error {0}\n", sslPolicyErrors);
            return true;
          };

          DeviceClient s_deviceClient = DeviceClient.CreateFromConnectionString(s_connectionString[i], new ITransportSettings[] { settings });

  
## Console log of the issue:

Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedServerUnavailable
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass41_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass18_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at DeviceSimulator.MyJob.SendMessage() in C:\dev\c#\core\DeviceSimulator\QuartzJob.cs:line 123

**Comment by jenoola** [comment]
How are you using the IP? Are you passing it as a part of connection string to DeviceClient?

**Comment by mesgar** [comment]
hey @jenoola,
   Yes, It's a part of connection string(uri).
    Here is my code. I'm quite sure the code is fine, since  everything works fine when I use host name.
    It must be a SSL certificate problem. Like most Azure services there should be a wildcard certificate for all IoT Hub subdomains (*.azure-devices.net). Hence, accessing with IP causes certificate error. I added  a certificate validation handler but it didn't help.

    #region definitions
    //-----------------------------------------------------------------------------------------------------//
    private const string IotHubUri = "40.74.xxx.xxx"; //"xxxosakahub.azure-devices.net";
    private const string DeviceKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    private const string DeviceId = "CouldBeAnyDevice";
    private static DeviceClient _deviceClient;
    //-----------------------------------------------------------------------------------------------------//
    #endregion      
    #region implementation
      //-----------------------------------------------------------------------------------------------------//
      var settings = new MqttTransportSettings(Microsoft.Azure.Devices.Client.TransportType.Mqtt_Tcp_Only);
      settings.Proxy = null;
      settings.RemoteCertificateValidationCallback = (object sender, 
        X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) =>
      {
        Console.WriteLine("SSL Error {0}\n", sslPolicyErrors);
        return true;
      };

      _deviceClient = DeviceClient.Create(IotHubUri, 
        new DeviceAuthenticationWithRegistrySymmetricKey(DeviceId, DeviceKey), new ITransportSettings[] { settings });
      //-----------------------------------------------------------------------------------------------------//
     #endregion

**Comment by CIPop** [comment]
This is by design: TLS authentication is based on the DNS host name. Our stack doesn't expose the ability to specify an IP and the host-name separately.
There are two solutions:
1. Use a `hosts` file to bind the name with the IP.  (Recommended.)
2. Create your own TLS authentication validation (Not recommended as implementing it incorrectly creates a security issue) - see https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.transport.mqtt.mqtttransportsettings.remotecertificatevalidationcallback?view=azure-dotnet#Microsoft_Azure_Devices_Client_Transport_Mqtt_MqttTransportSettings_RemoteCertificateValidationCallback

**Comment by az-iot-builder-01** [comment]
@jenoola, @mesgar, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
