### ISSUE TITLE
NullReferenceException is thrown while device client completes Receive operation

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#942]
In the E2E fault injection tests; device client throws `NullReferenceException` while executing `CompleteAsync()` after finishing `ReceiveAsync()`. This occurs because of a potential race condition after fault injection, where the `ReceivingAmqpLink` is null because of the fault, and the complete/dispose operation is carried out in another task at the same time.

**Comment by davilu** [comment]
@abhipsaMisra It is fixed in PR([1001](https://github.com/Azure/azure-iot-sdk-csharp/pull/1001)). Please verify once it's been merged.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
