### ISSUE TITLE
Honor different pool sizes for different pools

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#943]
Currently, the pool size is set at application level, and cannot be modified. We need to have different pools identifiable by different pool names; and they should be able to take in different pool sizes.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently in our backlog and will consider it as part of our planning cycle.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
