### ISSUE TITLE
StackOverflowException when using MQTT

### ISSUE THREAD

**Issue by SebastianRoether** [Azure/azure-iot-sdk-csharp#944]
Hi,

we currently have problems with StackOverflowExceptions when using the MQTT protocol. 
Trace: [stackoverflow_mqtt_websock.txt](https://github.com/Azure/azure-iot-sdk-csharp/files/3177175/stackoverflow_mqtt_websock.txt)

Basically it looks like the event raised [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/e1dd08eacd1caf58f3b318d8ad5ad94dde961d78/common/src/device/transport/mqtt/ClientWebSocketChannel.cs#L160) (or [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/e1dd08eacd1caf58f3b318d8ad5ad94dde961d78/common/src/device/transport/mqtt/ClientWebSocketChannel.cs#L168)) results in [this code](https://github.com/Azure/azure-iot-sdk-csharp/blob/e1dd08eacd1caf58f3b318d8ad5ad94dde961d78/iothub/device/src/Transport/Mqtt/MqttIotHubAdapter.cs#L219) to be executed which in turn (indirectly) calls the method that invokes the event in the first place.

Raising the event from within the exception handler seems especially suspicious, since I can see the same Exception occuring in every subsequent call

Best regards
Sebastian

**Comment by jenoola** [comment]
Please provide the following information:
- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:


## Code sample exhibiting the issue:


## Console log of the issue, including stack trace:

**Comment by prmathur-microsoft** [comment]
Please let us know if you are still facing problems. I will close this for now but feel free to reopen if you have the requested data above.

**Comment by az-iot-builder-01** [comment]
@jenoola, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
