### ISSUE TITLE
StatusCode: 403

### ISSUE THREAD

**Issue by raamanihilent** [Azure/azure-iot-sdk-csharp#948]
Hi

I am trying to upload files with IoT Hub, following the documentation.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload

To initialize file upload, i created a http client with a HttpClientHandler with X509 certificate(self-signed).
 
client.PostAsync($"https://{iotHubUri}/devices/{Program.deviceId}/files?api-version=2018-06-30", new StringContent(payload, Encoding.UTF8, "application/json"));

I am successful receiving correlationId, hostName, containerName, blobName & sasToken.

Then i created a new httpclient, used the sasToken to upload the file

putHttpClient.PutAsync(uploadUri, new StreamContent(source));
where uploadUri = $"https://{uploadInfo.hostName}/{uploadInfo.containerName}/{blobName}{uploadInfo.sasToken}";

I am getting the below error

{StatusCode: 403, ReasonPhrase: 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:{  Server: Microsoft-HTTPAPI/2.0  x-ms-request-id: b930b391-f01e-0047-1767-0c4d70000000  Date: Fri, 17 May 2019 04:15:27 GMT  Content-Length: 524  Content-Type: application/xml}}

Please help me resolve the issue.

Thanks

**Comment by jenoola** [comment]
@raamanihilent please provide the following information:

OS, version, SKU and CPU architecture used:
Application's .NET Target Framework :
Device:
SDK version used:

Code sample exhibiting the issue:

**Comment by raamanihilent** [comment]
I am running the sample from my Windows 10 Pro, Intel Core i7 6500U CPU @ 2.50 GHz
Applications target framework : .NET Core 2.1
Device: Simulated device from my latop
SDK Version used: (version.csv content) 
AssemblyPath, Version
iothub\device\src\Microsoft.Azure.Devices.Client.csproj, 1.20.0
iothub\service\src\Microsoft.Azure.Devices.csproj, 1.17.3
shared\src\Microsoft.Azure.Devices.Shared.csproj, 1.16.0
provisioning\device\src\Microsoft.Azure.Devices.Provisioning.Client.csproj, 1.3.0
provisioning\transport\amqp\src\Microsoft.Azure.Devices.Provisioning.Transport.Amqp.csproj, 1.1.6
provisioning\transport\http\src\Microsoft.Azure.Devices.Provisioning.Transport.Http.csproj, 1.1.5
provisioning\transport\mqtt\src\Microsoft.Azure.Devices.Provisioning.Transport.Mqtt.csproj, 1.1.7
security\tpm\src\Microsoft.Azure.Devices.Provisioning.Security.Tpm.csproj, 1.1.5
provisioning\service\src\Microsoft.Azure.Devices.Provisioning.Service.csproj, 1.4.0

Code Sample exhibiting the issue:

        private static async Task UploadToBlobUsingX509AsyncUsingHttpClient(string iothubnamespace, string deviceId, string deviceKey)
        {
            try
            {
                var cert = new X509Certificate2(projectFolderName + certificateName, certificatePassword);
                HttpClientHandler requestHandler = new HttpClientHandler();
                requestHandler.ClientCertificates.Add(cert);

                HttpClient client = new HttpClient(requestHandler);

                bool isUploaded = false;
                //loop through all files for uploading
                foreach (var blobName in Program.blobList)
                {
                    string blobFileName = projectFolderName + blobName;
                    if (!File.Exists(blobFileName))
                    {
                        FileLogging.Log("File not exists on " + blobFileName, Program.consoleLogging);
                        continue;
                    }
                    Stream source = new FileStream(blobFileName, FileMode.Open);
                    long blobSizeInBytesSize = source.Length;

                    //Create header
                    if (client.DefaultRequestHeaders.Contains("x-ms-blob-type"))
                    {
                        client.DefaultRequestHeaders.Remove("x-ms-blob-type");
                    }

                    //Initialise a file upload using Rest API
                    FileLogging.Log(blobName + " initialization started", Program.consoleLogging);
                    //?api-version=2018-06-30
                    var payload = JsonConvert.SerializeObject(new { blobName });
                    var response = await client.PostAsync($"https://{Program.iotHubUri}/devices/{Program.deviceId}/files?api-version=2018-06-30", new StringContent(payload, Encoding.UTF8, "application/json"));
                    var infoType = new { correlationId = "", hostName = "", containerName = "", blobName = "", sasToken = "" };
                    var uploadInfo = JsonConvert.DeserializeAnonymousType(await response.Content.ReadAsStringAsync(), infoType);
                    if (response.StatusCode != System.Net.HttpStatusCode.OK)
                    {
                        FileLogging.Log("File initialisation not happened : " + response.StatusCode.ToString() + " " + response.ReasonPhrase, Program.consoleLogging);
                        continue;
                    }
                    FileLogging.Log("Initialization of file upload completed.", Program.consoleLogging);

                    //Upload a file using Rest API
                    //add into year, month and date
                    DateTime currentDateTime = DateTime.UtcNow;
                    FileLogging.Log("Uploading a file for device " + Program.deviceId, Program.consoleLogging);

                    //Created new instance because Put request didnt require authentication
                    HttpClient putHttpClient = new HttpClient();
                    
                    var uploadUri = $"https://{uploadInfo.hostName}/{uploadInfo.containerName}/{blobName}{uploadInfo.sasToken}";

                    response = await putHttpClient.PutAsync(uploadUri, new StreamContent(source));
                    isUploaded = response.StatusCode == System.Net.HttpStatusCode.Created;
                    if (response.StatusCode != System.Net.HttpStatusCode.Created)
                    {
                        FileLogging.Log("File not uploaded: " + response.StatusCode.ToString() + " " + response.ReasonPhrase, Program.consoleLogging);
                        continue;
                    }
                    FileLogging.Log("Device " + Program.deviceId + " : " + blobName + " file uploaded successfully.", Program.consoleLogging);


                    //Notify IoT Hub of a completed file upload
                    //client.DefaultRequestHeaders.Add("Authorization", deviceSasToken.ToString());
                    payload = JsonConvert.SerializeObject(new { uploadInfo.correlationId, statusCode = isUploaded ? 0 : -1, statusDescription = "Hi", isSuccess = isUploaded });
                    response = await client.PostAsync($"https://{Program.iotHubUri}/devices/{Program.deviceId}/files/notifications?api-version=2016-11-14", new StringContent(payload, Encoding.UTF8, "application/json"));
                    FileLogging.Log("Notification sent to IoT Hub for completed uploading.", Program.consoleLogging);

                }
            }
            catch (Exception ex)
            {
                FileLogging.Log(ex.Message, consoleLogging);
            }
        }

**Comment by raamanihilent** [comment]
Any updates?

**Comment by raamanihilent** [comment]
Can you please share an update? This piece of code was working before and now it is failing. I see that the documentation on put blob (https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) was updated on Apr 23.

**Comment by timtay-microsoft** [comment]
I'm a little confused here. From the code sample you provided, it doesn't appear that you are using the C# IotHub SDK. You are hitting unexpected behavior when directly interacting with the HTTP endpoints using your own httpclient. Since that is the case, this issue was filed in the wrong place. I suggest opening up a new support request through the azure portal for your resource instead. This issues page is for the SDK, not the service.

**Comment by az-iot-builder-01** [comment]
@jenoola, @raamanihilent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
