### ISSUE TITLE
Broken link to API reference

### ISSUE THREAD

**Issue by micahswitzer** [Azure/azure-iot-sdk-csharp#95]
In readme.md at the end of the last paragraph before section titled "OS platforms and hardware compatibility" there is a broken link to the API reference documentation. I've encountered this same link other places and I'm really getting frustrated because there seems to be no documentation whatsoever on the .NET Azure IoT Hub sdk. If anyone could point me in the right direction I would be really grateful.

**Comment by micahswitzer** [comment]
Any updates?

**Comment by tameraw** [comment]
@micahswitzer - Understand that these broken links are frustrating. It should be fixed now. Let us know if you run into other ones.
Thanks.

**Comment by dominicbetts** [comment]
@tameraw - we updated a couple of instances of the same link in the docs on docs.microsoft.com last week. The API reference links should now all be correct - but please let me know if you come across any other instances.

**Comment by tameraw** [comment]
@dominicbetts - Thanks!
