### ISSUE TITLE
Link/session faults for message send/ method/ twin operations closes the connection

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#950]
For fault injection tests where we request session/link closure for Telemetry Send, Method or Twin operations for a particular device client instance, it results in closure of the connection (and all devices multiplexed over that connection).
Further, for twin operation - reported properties update, only the faulted device recovers; the other devices sharing the connection that got disconnected do not recover successfully.

**Comment by CIPop** [comment]
@abhipsaMisra let's confirm this is FaultInjection closing the TCP connection.

**Comment by abhipsaMisra** [comment]
This is a bug with the fault injection implementation (which is a test feature of the service). Closing this issue.
