### ISSUE TITLE
CloseAsync and Dispose should place the DeviceClient in an unusable state

### ISSUE THREAD

**Issue by davilu** [Azure/azure-iot-sdk-csharp#955]
If `CloseAsync` or `Dispose` is called, the client will be disposed and mark as unusable. 
`ObjectDiposedException` will be throw on any pending or new operation including OpenAsync.

**Comment by perahlberg** [comment]
What it the release status of this redesign?
We waiting for it!

**Comment by CIPop** [comment]
@perahlberg thanks for the interest in our SDK! We are working on this with the highest priority - designing the stack and stabilizing it at scale is a larger effort. The first phase of the redesign is already checked in.
We'll track the status with https://github.com/Azure/azure-iot-sdk-csharp/projects/5.

**Comment by davilu** [comment]
@perahlberg thanks for the patient and we get a PR([1001](https://github.com/Azure/azure-iot-sdk-csharp/pull/1001)) out for this redesign. We're under long haul testing in a stress platform. It will be released once the test are completed.

**Comment by prmathur-microsoft** [comment]
This issue is now fixed and should be a part of latest release [v1.21.1](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2019-9-11) Feel free to reopen this issue if you still see it.

**Comment by az-iot-builder-01** [comment]
@perahlberg, @CIPop, @davilu, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
