### ISSUE TITLE
High CPU load if Disconnected_Retrying status

### ISSUE THREAD

**Issue by SergiiChurakov** [Azure/azure-iot-sdk-csharp#969]
- **OS, version, SKU and CPU architecture used:** <VERSION>  Windows 10 Pro x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp2.1, net472
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION> 1.20.2

## Description of the issue:
Connect to the device with your credentials and register any direct method. Disconnect from the network. After 2-4 minutes, the application begins to heavily load the CPU.

This is because:
- Default retry strategy in RetryDelegatingHandler class created ExponentialBackoff with retryCount parameter = int.MaxValue.
- When dicsonnect happen ExponentialBackoff.GetShouldRetry() method after 20-25 attempts retrun negative value in retryInterval parameter.
- In AsyncExecution<TResult>.ExecuteAsyncContinueWith(Task<TResult> runningTask) method, if retryInterval parameter is negative, set TimeSpan.Zero. Thus, there is no interval between attempts.

## Code sample exhibiting the issue:
       public class IoTHubClient
       {
        private DeviceClient deviceClient;

        public async Task Connect(string deviceId, string connectionString, string hostname)
        {
            string key;

            using (RegistryManager registryManager = RegistryManager.CreateFromConnectionString(connectionString))
            {
                Device device = await registryManager.GetDeviceAsync(deviceId).ConfigureAwait(false);
                if (device == null)
                {
                    device = await registryManager.AddDeviceAsync(new Device(deviceId)).ConfigureAwait(false);
                }
                key = device.Authentication.SymmetricKey.PrimaryKey;
            }

            if (deviceClient == null)
            {
                deviceClient = DeviceClient.Create(hostname, new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, key), TransportType.Mqtt);
                deviceClient.SetConnectionStatusChangesHandler(SomeConnectionStatusChangesHandler);
            }
        }

        public async Task RegisterDirectMethodAsync(string Name, MethodCallback MethodHandler)
        {
            await deviceClient.SetMethodHandlerAsync(Name, MethodHandler, new object()).ConfigureAwait(false);
        }

        private void SomeConnectionStatusChangesHandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
        {
            Console.WriteLine($"Status changed to: {status}. Reason : {reason}");
        }
    }

## Console log of the issue:
Status changed to: Connected. Reason : Connection_Ok
Status changed to: Disconnected_Retrying. Reason : Communication_Error

**Comment by timtay-microsoft** [comment]
Good catch, I've created a fix that prevents this bug and am working to get it checked in now. There was some integer arithmetic that underflowed once larger retryCount attempts were reached. I've made these all double arithmetic instead so that it will never underflow

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released in the device client 1.21.2, so I'm closing this issue. Thanks for the detailed write-up on this issue, @SergiiChurakov

**Comment by az-iot-builder-01** [comment]
@SergiiChurakov, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
