### ISSUE TITLE
sas token generated for 360s with TTL=0 days

### ISSUE THREAD

**Issue by vppillai** [Azure/azure-iot-sdk-csharp#97]
In the release UI, when SAS token is generated for a device with TTL=0 days, the generated token has `se` set to a value 360 seconds ahead of current time. Expectation is that the `se` will be large enough to avoid quick expiration

**Comment by tameraw** [comment]
@vppillai - Apologies for the delay responding to this one. The service does use a constant 5 mins to handle clock skews.
