### ISSUE TITLE
[Service] Previously created enrollments are unable to perform IoTHub operations on Mqtt/ Mqtt_WS

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#976]
There is an issue identified on service side where previously created enrollments, when provisioned, are unable to perform IoTHub operations on mqtt/mqtt_ws.
The OpenAsync() call fails with SocketException.:

```
Test method Microsoft.Azure.Devices.E2ETests.ProvisioningE2ETests.ProvisioningDeviceClient_ValidRegistrationId_MqttWsWithProxy_X509Individual_RegisterOk threw exception: 
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
```

The following affected E2E tests are being ignored until the fix is rolled out:
```
ProvisioningDeviceClient_ValidRegistrationId_MqttWsWithProxy_X509Individual_RegisterOk
ProvisioningDeviceClient_ValidRegistrationId_MqttWsWithNullProxy_X509Individual_RegisterOk
ProvisioningDeviceClient_ValidRegistrationId_Mqtt_X509Individual_RegisterOk
ProvisioningDeviceClient_ValidRegistrationId_MqttWs_X509Individual_RegisterOk
```

**Comment by abhipsaMisra** [comment]
We did not disable these tests. Closing the tracking issue.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
