### ISSUE TITLE
Modify individual device twins registered in group enrolment.  

### ISSUE THREAD

**Issue by Shreyasnie** [Azure/azure-iot-sdk-csharp#979]
I am trying to modify device twin property of device registered under group enrolment, it updating properties of other devices also which are under same group enrolment. is there a possible way to modify device twins only single device?

**Comment by ewertons** [comment]
Hi @Shreyasnie ,
Device Twin is a "property bag" that is independent per device ID.
On your group enrollment configuration, there is an initial (!) template for the device twin.
A copy of that template is then assigned to a device in that enrollment group when it connects/authenticates with IoT Hub for the first time. 
Once the device gets its own device twin assigned, the enrollment group twin template does not affect the device twin functionality of any of the devices in the given group.

So once you get your device connected and authenticated, yes, you can modify the individual device twin of that device (and only of that device) using the DeviceClient API.
Please refer to [this sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/TwinSample) for guidelines of how to achieve that.

**Comment by prmathur-microsoft** [comment]
Closing this as per the ans above. Feel free to reopen if you have any further questions.

**Comment by az-iot-builder-01** [comment]
@Shreyasnie, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
