### ISSUE TITLE
Question: Are the device tag going to accept array type ?

### ISSUE THREAD

**Issue by ApiO** [Azure/azure-iot-sdk-csharp#98]
Hi,

I try to import devices from a Storage Account blob and I get an error when a tag property is an array.

The [documentation ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twins) says:

> All values in JSON objects can be of the following JSON types: boolean, number, string, object. **Arrays are not allowed**.

Curious limitation. Does this feature will come one day ? In my case avoiding this limitation will complicate my work :s
Is it a bareer to help on the blob size limitation?

Regards

**Comment by fsautomata** [comment]
Hi ApiO,

What is your scenario for using arrays, and most importantly, how are you planning to use arrays in queries (if you are planning to?)

**Comment by ApiO** [comment]
Hi fsautomat,

There is two facts:
- First, around the IoT Hub twins, the device properties (required/desired) sync process is not guarantee right now. There is some C2D direct message and a "retry message" sent one time at the first next connection but that is not enough, devs must be done.
- Last, in my scenario, devices have some external resources informations, like name and version. Resources change often and different versions of the same ressources can exist on the same time.

As you guessed, because we can query Twins on Tag I can avoid to use an external data source to store my business data and the corresponding "middleware" that expose them. Plus, tags use less bytes to be store, thus allowing me to avoid to reach the size limitation early.

I'm totally aware that my approach "smells". Using tags as properties is a design violation and my twins' data has a little complexity that may be abstract. I guess this is the design you want with Twins : devices twins must not be used to store applications variables, only device configurations.

I don't want to setup now a huge environement just for this little case. The solution may evolve, and to be honest it certainly will, but in my scenario I'm really near to do what I want, there is just this "little" surprising type restriction.

And last,

> how are you planning to use arrays in queries 

Through function from Function App, triggered by a timer or by external events.


Regards

**Comment by olivierbloch** [comment]
I have create a User Voice item [here](https://feedback.azure.com/forums/321918-azure-iot/suggestions/20162305-support-arrays-for-tags-in-device-twins) to track this request.
Please vote there.
Thanks

**Comment by ApiO** [comment]
Alright, thanks 👍
