### ISSUE TITLE
Upgrade needed to latest Microsoft.TSS Nuget Package

### ISSUE THREAD

**Issue by danigian** [Azure/azure-iot-sdk-csharp#981]
## Description of the issue:
A new NuGet package for [Microsoft.TSS](https://www.nuget.org/packages/Microsoft.TSS/) has been released, fixing some issues encountered in Linux ARM environments.

Please update the Microsoft.Azure.Devices.Provisioning.Security.Tpm.csproj to include the new 2.1.1 version.

**Comment by danigian** [comment]
cc @CIPop

**Comment by CIPop** [comment]
Thanks @danigian for pointing this out!

**Comment by CIPop** [comment]
Feel free to submit a PR changing the root versions.csv then running versionUptade.ps1 -update

**Comment by danigian** [comment]
@CIPop PR #983 created.

**Comment by az-iot-builder-01** [comment]
@danigian, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
