### ISSUE TITLE
New operations should be allowed after RetryPolicy ran to completion.

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#984]
In the current implementation, during internal reconnect (i.e. when Methods/Twin, etc subscriptions exist), the DeviceClient will be placed in an unusable state once the RetryPolicy ran to completion (i.e. a non-retriable error was encountered).
We would like to change this behavior so that new Open/Send/ReceiveAsync operations can be processed. These operations will attempt to reconnect (applying the policy).

Exceptions causing the RetryPolicy to terminate can be monitored by implementing a custom IRetryPolicy.

(was in #955)

**Comment by jamdavi** [comment]
Fixed in #1001

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
