### ISSUE TITLE
Internal retry should be applied even if no subscriptions exist

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#985]
Today, we only reconnect DeviceClient if the application subscribed to methods,twin,etc. 
This is changing the behavior to always reconnect after either `OpenAsync` was called or an implicit open was performed (by calling any of the Send/ReceiveAsync, etc. operations).

(was in #955)

**Comment by bikamani** [comment]
Already taken care of hence closing the issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
