### ISSUE TITLE
DeviceStreaming / ModuleStreaming failing intermittently

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#987]
We are aware of what appears to be a service-side issue of the Device Streaming preview feature.
`DeviceStreaming_RequestAccepted_*` and `ModuleStreaming_RequestAccepted_*`  tests are intermittently failing to connect to the created channel. (IoT channel setup is passing).

**Comment by CIPop** [comment]
@rezasherafat FYI

**Comment by CIPop** [comment]
This has been fixed in at least the canary region where `preview` is tested.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
