### ISSUE TITLE
Honor cancellation token during implicit (re)open

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#992]
Implicit open will guarantee reopening the connection with any new operation. 
If the application is creating other operations in parallel, these will be queued behind a semaphore (`WaitAsync`). 

This issue is tracking addition of the `CancellationToken` within the WaitAsync and proper handling of the timeout if the operation failed to acquire the lock due to cancellation.

**Comment by bikamani** [comment]
Already taken care of hence closing the issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
