### ISSUE TITLE
Dispose during OpenAsync race condition

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#993]
Properly handle Dispose/CloseAsync during `OpenAsync` and applies to creation of sessions and links.
There are multiple ways of fixing this. One of them to check before returning / commiting the new session/link to the owner object. Only complete the operation is the owner of the session/link is still alive.

**Comment by vinagesh** [comment]
Currently once dispose/close is called, the connection needs to be re-initialized. The race condition itself has been solved using locks. Please re-open if you still find this to be a problem.

**Comment by az-iot-builder-01** [comment]
@CIPop, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
